### ISSUE TITLE
sw-offline-google-analytics: console filled with error messages when browsing offline

### ISSUE THREAD

**Issue by sikko** [GoogleChrome/workbox#100]
**Library Affected**: sw-offline-google-analytics

**Browser & Platform**: all browsers

**Issue or Feature Request Description**:

The helper works like it should. Except each event recorded by google analytics while browsing offline returns 3 errors:

```
Failed to load resource: net::ERR_INTERNET_DISCONNECTED: https://www.google-analytics.com/collect?v=1&_v=j47&a=2067088040&t=pageview...

The FetchEvent for "https://www.google-analytics.com/collect?v=1&_v=j47&a=2067088040&t=pageview..." resulted in a network error response: the promise was resolved with an error response object.

GET https://www.google-analytics.com/collect?v=1&_v=j47&a=2067088040&t=pageview... net::ERR_FAILED
```

Which results in a dirty console after a while. I know it's not that much of a problem, but is it possible to "catch" those errors and swallow them into the fetch event?

**Comment by gauntface** [comment]
This is related to #93

**Comment by philipwalton** [comment]
@gauntface is this still an issue now that `workbox-google-analytics` uses the the routing and strategy packages?

**Comment by gauntface** [comment]
I'm going to close this given that google-analytics has changed a great deal as has all of the Workbox logging. There may still be some logs that we simply can't surpress which is logged by devtools, but let's see.
