### ISSUE TITLE
Why should we broadcast the update event in fetchAndCache()?

### ISSUE THREAD

**Issue by xiaoiver** [GoogleChrome/workbox#1001]
I found following code from workbox-precaching on v2.1.1:
``` javascript
// base-cache-manager.js
async _cacheEntry(precacheEntry) {
    const isCached = await this._isAlreadyCached(precacheEntry);
    const precacheDetails = {
        url: precacheEntry.request.url,
        revision: precacheEntry.revision,
        wasUpdated: !isCached,
    };
    //...
    // can we broadcast update event here ?
    await this._requestWrapper.fetchAndCache()
```

My question is why we should broadcast update event after fetching and comparing some headers such as ETag and content-length of two responses. I think we know current entry was changed when **isCached** is false so the update event can be broadcasted before calling **fetchAndCache**.

**Comment by jeffposnick** [comment]
The precaching logic piggy-backs on top of the logic used by the [`BroadcastCacheUpdatePlugin`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-broadcast-cache-update.BroadcastCacheUpdatePlugin), and waits for the appropriate lifecycle event to be fired before announcing the update, even if the information could have been inferred earlier on.

The benefit is that we have a consistent way of checking for and announcing updates, regardless of whether it's via runtime caching or precaching.

I'm not sure what the downside is. If you're running into problems with the current approach, could you be more specific about what issue you're seeing?

**Comment by xiaoiver** [comment]
In my project, I have two kinds of resources to precache:

**Comment by xiaoiver** [comment]
Thanks, in my project, I have two kinds of resources to precache:
1. main.[hash].js, main.[hash].css, etc.
2. /appshell 

For the first kind of files, I use `dontCacheBustUrlsMatching: /\.\w{8}\./` to let workbox treat filename as revision. But when my new building process finished, [hash] was already changed, I still didn't see the update event get fired. I think workbox don't know **main.2.js** is an updated version of **main.1.js**. I'm not sure if it is related to this Issue [#875](https://github.com/GoogleChrome/workbox/issues/875).

For the **/appshell**, I use `templatedUrls` so workbox generates the revision based on some server-side logic. When the revision changed, I still can't see the update event being fired. I find workbox will go into the following logic in such circumstance:
``` javascript
// workbox-broadcast-cache-update/responses-are-same.js
responsesAreSame()
```
It compares two responses with their headers such as **content-length** and **etag**. But I use gzip so there's no content-length header in response. I don't add etag because I think we already have different revisions.

I'll be so appreciated if you can give me any help :).

**Comment by jeffposnick** [comment]
Regarding `main.1.js` v.s. `main.2.js` being effectively the same file, despite the different filenames—that's not something that the broadcast update logic can easily deal with. It would require keeping some additional metadata about which parts of the filenames matter and which don't, and that's probably outside the scope of the plugin.

I don't think there's anything in practice [stopping you](https://stackoverflow.com/a/36194775/385997) from using a `Content-Length` header along with gzip content encoding; additionally, using the `Last-Modified` header to reflect when `/appshell` was updated is another option that works "out of the box" with the broadcast update plugin.

But if you're looking for a more brute-force solution that will work any time there's an update to any resource, independent of the plugin logic, you can listen for changes to the controlling service worker from within the client page: https://github.com/GoogleChromeLabs/sw-precache/blob/master/demo/app/js/service-worker-registration.js#L29-L50

**Comment by xiaoiver** [comment]
Thanks @jeffposnick, I realized some misunderstandings I have made, especially the usage of **BroadcastCacheUpdatePlugin**. BTW, the solution from sw-precache works!
