### ISSUE TITLE
Drop support for WorkboxSW's handleFetch?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1002]
**Library Affected**:
*workbox-sw*

Historically, we've supported a `handleFetch` option that gets passed in as part of the build process, and when set to `false`, disables the `fetch` handler that Workbox registers. The primary use case was creating a somewhat no-op-y service worker to use in development environments.

I'm debating whether to port this over to v3, as there's no longer centralized `fetch` handlers to control under `WorkboxSW`'s purview, and am open to removing it.

Thoughts from other folks?

**Comment by gauntface** [comment]
Couldn't this be moved into `workbox-routing`?

By default register the fetch event listener and add a method `disableFetch()`? But also happy to remove and just recommend using Chrome DevTools.

**Comment by jeffposnick** [comment]
One complication I was thinking of was that there's a separate `fetch` handler added by `precacheAndRoute()`. That, and the act of registering and then optionally de-registering the automatic `fetch` handler from `workbox-routing/_defauly.mjs` seems a little inelegant.

I could always conditionally output either `precache()` or `precacheAndRoute()` depending on the `handleFetch` value, and call `removeEventListener()` as needed, so it's not impossible.

Just wanted to get a feel for how useful folks felt this was in v3.

**Comment by gauntface** [comment]
I'm really torn to be honest.

While DevTools will just work, it's a nice developer workflow to have handleFetch in the build chain.

Arguably, for development, you could just output an empty SW, I can't imagine there is much benefit otherwise.

**Comment by jeffposnick** [comment]
I'll leave it out initially and we can see if anyone asks for it to be added back during the public previews.

We've got so many different entry points/build pipelines nowadays, it's hard to know what folks will actually find useful.

**Comment by jeffposnick** [comment]
Closing this since the decision was reached, and we can reopen to track `handleFetch` back to v3 if there's demand.
