### ISSUE TITLE
Treat registerRoute('/foo/:bar', ...) as exact match in v3

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1012]
**Library Affected**:
*workbox-routing*

Following up from https://github.com/GoogleChrome/workbox/issues/1011, in v3 we are going to stop creating `ExpressRoute`s implicitly whenever there's a string argument passed to the `registerRoute()` helper.

Instead, strings will be tested for an exact match, either against the `url.path` (if the string begins with `'/'`) or against the `url.href` (if the string begins with `http`).

We'll continue the logging that https://github.com/GoogleChrome/workbox/issues/1011 introduces, and ensure that we direct developers to documentation about constructing an equivalent `RegExpRoute` and/or creating their own custom `matchHandler` as alternatives.

**Comment by gauntface** [comment]
SGTM.

Worth calling out that matches for strings **not** starting with `http` should only match same-origin requests - same as regular expressions.

I'm still open to supporting an express style "matcher" if developers want it but I'm fairly sure a RegExp will be easy to replace the express routes in *most* cases.
