### ISSUE TITLE
`cacheExpiration` on the `runtime` cache - should we prevent?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1014]
At the moment this is valid:

```javascript
workbox.routing.registerRoute(/\/images\//, workbox.strategies.cacheFirst({
  cacheExpiration: {
    maxEntries: 4
  }
}));
```

Reading this code for the first time you'd expect the rule to only apply to images, but that's not the case, it applies to all of the `runtime` cache. Should we require developers to specify a cache to enforce this behavior?

**Comment by jeffposnick** [comment]
Yup, we should require that. If we didn't in v2 that was an oversight that we should fix in v3.
