### ISSUE TITLE
Problem with templatedUrls in workbox-build

### ISSUE THREAD

**Issue by hjortureh** [GoogleChrome/workbox#1039]
**Library Affected**:
workbox-build

**Browser & Platform**:
Node v6.11. 

**Issue or Feature Request Description**:
I have the following Workbox Build config to update the route version in the Service Worker when we make changes to some of our PUG templates.

```
const workboxBuild = require('workbox-build')

workboxBuild.injectManifest({
  swSrc: './src/service-worker.js',
  swDest: './public/sw.js',
  …
  templatedUrls: {
    '/': [
      './src/**\/*.pug'
    ]
  }
})
```

When we run this using NodeJS we get the following error: 

> (node:36553) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: There was an issue reading one of the provided templatedUrls. './src/**/*.pug' in templateUrl '{"/":["./src/**/*.pug"]}' could not be found.

The paths seem correct according to the docs and I've tried it with simpler paths without success. Any ideas what the problem might be?

**Comment by jeffposnick** [comment]
The values passed in to the array in `templatedUrls` are [`glob` patterns](), and the [syntax](https://github.com/isaacs/node-glob#glob-primer) for `glob` patterns takes some getting used to.

While the actual pattern to use depends on your directory layout, based on what you attempted to use, I'd imagine that this would be the working equivalent:

```js
globDirectory: './src',
templatedUrls: {
  '/': ['**/*.pug']
}
```

Note that the base location from which this glob pattern is evaluate is whatever you specify for your `globDirectory` configuration option. I'm guessing that you're using `globDirectory: './src'`, but if you're using something different, you may need to just the `templatedUrls` pattern further.

Let me know if that works for you and we can close this issue.

**Comment by hjortureh** [comment]
Thank you for the response. The problem is that my PUG templates are outside the `./public` directory which I have set in my `globDirectory`. It seem to need it have it there as if I change it to the root of the application `./` and put `public/` in front of all my `globPatters ` - the resources in my SW will be generated with that included, example:

```
workbox.precache([
  {
    "url": "public/main-compiled.js",
    "revision": "f1cf086ba0751997c351ecd12f359919"
  },
  {
    "url": "public/modernizr.js",
    "revision": "683a61743e9c39d243f1f4203e0a61ab"
  },
  {
    "url": "public/styles.css",
    "revision": "3a147669aff40cc312c1429e43cfab7f"
  },
...
```

However, I would need to skip the `public/` prefix from there, any way to do that?

**Comment by jeffposnick** [comment]
You can use the [`modifyUrlPrefix` option](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.Configuration) to strip prefixes:

```js
modifyUrlPrefix: {
  'public/': '',
  'src/': '',
  // Etc.
}
globDirectory: './',
templatedUrls: {
  '/': ['**/*.pug']
}
```

**Comment by hjortureh** [comment]
It totally worked 👊  thanks a lot!
