### ISSUE TITLE
Call `suppressWarnings()` in the service worker template

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1047]
**Library Affected**:
*workbox-build*

Moved over from https://github.com/GoogleChrome/workbox/pull/1042#pullrequestreview-76543644

I think it's safe to unconditionally call [`workbox.precaching.suppressWarnings()`](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-precaching/_default.mjs#L253) inside the [`sw-template.js` template](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/templates/sw-template.js), since the template is used in conjunction with a build tool, and we can assume that if a build tool created a `ManifestEntry` without a `revision`, it's intentional.

**Comment by gauntface** [comment]
SGTM
