### ISSUE TITLE
Automate the generation of the global babelHelpers object in workbox-core

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1050]
#1048 manually adds the global `babelHelper` functions object, but this has the potential to break in the future if someone adds new code that needs a helper not already present. Ideally this process would be automated, and helpers would be added based on the actual transformed code.

Currently this isn't possible with babel, but I've filed [a feature request](
https://github.com/babel/babel/issues/6835), so it may be possible in the future.

Adding this here as a reminder.

**Comment by jeffposnick** [comment]
As of Workbox v4, we're not using `babelHelpers` anymore.
