### ISSUE TITLE
workbox-build doesn't provide a default inject point confusing things

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1056]
workbox-cli and workbox-build should have the same defaults.

Looking at workbox-build the injectManifest function requires a regex instead of providing the same default at the CLI

For the most common use case this muddies the water.

**Comment by jeffposnick** [comment]
[There's a default](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/entry-points/options/inject-manifest-schema.js#L23) that should be used consistently for `injectManifest`, regardless of whether it's called directly from `workbox-build` or indirectly from `workbox-cli`.

That's covered by, e.g., [this test case](https://github.com/GoogleChrome/workbox/blob/v3/test/workbox-build/node/entry-points/inject-manifest.js#L153) and others.

What steps did you take when you ran into this?
