### ISSUE TITLE
No Splash Screen

### ISSUE THREAD

**Issue by Snickdx** [GoogleChrome/workbox#1063]
**Library Affected**:
*workbox-cli*

**Browser & Platform**:
*Google Chrome for Android*

**Issue or Feature Request Description**:
I noticed that a pwa with a workbox generated service worker dont open with a splash screen on android after installation, also the display mode remains browser regarless of what is specified in the manifest. When I add to homscreen it basically added a shortcut to the browser yet the service worker is shown runnin in the debugger. When I press add to homecreen the a2hs confirm shows up instead of the new install banner. I have gotten all of these to work with a service worker generated with sw-precache however.

[workbox sw app](https://pwa-snickdx.c9users.io:8081/) (Cloud nine)
[same app but with sw precache](https://github.com/uwijammers/pwa-intro)

**Comment by gauntface** [comment]
Looking at Lighthouse report for the cloud nine app:

> User will not be prompted to Install the Web App
> Browsers can proactively prompt users to add your app to their homescreen, which can lead to higher  engagement. Learn more.
> Failures: No manifest was fetched, Site does not register a service worker, Service worker does not  successfully serve the manifest's start_url.

If you can add a manifest, then we can look at any further issues.

**Comment by Snickdx** [comment]
Hi maybe the c9 container went to sleep at the time. There manifest is indeed there, attached is a screenshot of an audit I just took of the c9 app.

![image](https://user-images.githubusercontent.com/5845054/33144704-5651e386-cf94-11e7-81a1-b4b29ef0a30f.png)

**Comment by gauntface** [comment]
I can't view the page you are displaying unfortunately (I just get the orange page and when attempting to open the page, I see an error message).

> No application seems to be running here!
> Cloud9 can't get you to your requested workspace. Here are some suggestions on how to figure out what's going on:
>
> Check that the workspace name (pwa) and username (snickdx) are typed correctly.
> Check that the server is successfully running on Cloud9:
> If the server hit an error, the output window will have a message telling you what it is
> If you're in the middle of debugging code, your server might be paused right now
> The server might be running on a different port; make sure it's on port $PORT with $IP as the IP address

**Comment by Snickdx** [comment]
I switched to firebase hosting, https://jcal-6d7d9.firebaseapp.com/. Splash screen works with this service worker (generated from "workbox-cli generate:sw"). I believe I used inject: manifest in the OP but I'll open another issue if I can recreate the issue. Thanks.
