### ISSUE TITLE
Add a new workbox copyLibraries <path> command

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1066]
**Library Affected**:
*workbox-cli*

We should expose a new command in `workbox-cli` that will run https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/lib/copy-workbox-libraries.js using a directory specified.

Example usage:

```sh
workbox copyLibraries ./path/to/parentDir
```

**Comment by gauntface** [comment]
This would be fore Workbox Build and Workbox CLI.

**Comment by addyosmani** [comment]
👍 As discussed in team chat, this is preferred to having a flag for specifying the path. Having this work for both build and CLI sgtm.

**Comment by jeffposnick** [comment]
It's already exposed in `workbox-build`:https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/index.js#L394, so the change here is to put it in the CLI.
