### ISSUE TITLE
Sanitize URLs linked to from logs

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1072]
**Library Affected**:
*all*

There are a number of places in the codebase where we log messages which link to external reference docs that provide additional context.

We need to sanitize those URLs prior to launch and make sure that they point to documents that live under https://developers.google.com/web/tools/workbox/guides/ (without `v3` in the URL), as any other URL won't be stable.

(Using https://goo.gl shortlinks for these URLs from the log messages is preferred.)

**Comment by gauntface** [comment]
There is a link pointing to drive for the plugins docs, so will leave this open for now. After that doc is written and moved over to d.g.c we should be good to close this.

**Comment by gauntface** [comment]
This should be all done now. We ended up using the final URL's for docs. The only thing that might change is the URL's for prerelease docs (URLs like: https://developers.google.com/web/tools/workbox/reference-docs/prerelease/)

@jeffposnick do you have a feel for what would be needed here?
