### ISSUE TITLE
Use BroadcastCacheUpdate from within Precaching?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1073]
**Library Affected**:
*workbox-precaching*

In v2, we implicitly used `workbox-broadcast-cache-update` as part of `workbox-precaching`'s `RequestWrapper`, and announced changes to precached resources via a standard channel name.

We're not doing this in v3 right now. I'd argue that it's useful in theory, but at the same time, I don't think developers really took advantage to it, and there's obviously a hit in terms of extra runtime code.

We could:
- Not implement this in v3.
- Implement it by default in v3, matching v2's behavior.
- Implement as an opt-in in v3. (I'm assuming that we'd still take the hit in default bundle size if we took that approach?)

**Comment by gauntface** [comment]
I don't think there is currently a way to add plugins, so I would be in favor of making that possible in the default precaching export and just provide a guide that explained how and why you would do this.

how does that sound?

**Comment by jeffposnick** [comment]
Are you suggesting the third option that I listed? Would we avoid the bundle size hit if we went with that approach?

**Comment by gauntface** [comment]
@jeffposnick Yes the third option

**Comment by gauntface** [comment]
This was implemented via the `addPlugins()` API. https://developers.google.com/web/tools/workbox/reference-docs/prerelease/workbox.precaching#.addPlugins
