### ISSUE TITLE
Use a default config file location when none is specified in CLI

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1078]
**Library Affected**:
*workbox-cli*

As per https://github.com/GoogleChrome/workbox/issues/1052#issuecomment-347930791, it would be friendlier to check in a default file location for a config instead of requiring with when using `workbox generateSW` and `workbox injectManifest`.

Currently, the default file name/location used when you create a config file via `workbox wizard` is `./workbox-config.js`, so we should presumably use that as the default for reading, too.

After this is fixed, these two commands would be equivalent:

```sh
$ workbox generateSW workbox-config.js
$ workbox generateSW
```

**Comment by gauntface** [comment]
:+1:
