### ISSUE TITLE
[ISSUE?] Workbox Precache Issue with Parameters?

### ISSUE THREAD

**Issue by dertuerke** [GoogleChrome/workbox#1083]
**Issue or Feature Request Description**:
I do not know if that's a issue. But can it be that if files have a parameter that is not properly precached?

If I look in Chrome now, then I see that the file does not come from the service worker but is loaded from the disk cache.

I use the workbox version 2.1.2.

Example:
I precache all fonts, but some fonts has a parameter in the CSS-file
```
staticFileGlobs: [
   'assets/fonts/**/*.*',
]
```
```
@font-face {
  font-family: Ionicons;
  src: url(../assets/fonts/ionicons.woff2?v=3.0.0-alpha.3) format("woff2"),
        url(../assets/fonts/ionicons.woff?v=3.0.0-alpha.3) format("woff"),
        url(../assets/fonts/ionicons.ttf?v=3.0.0-alpha.3) format("truetype");
  font-weight: 400;
  font-style: normal
}
```

Network-Tree
![image](https://user-images.githubusercontent.com/2199151/33423363-dedb4768-d5b8-11e7-83a5-2f9cf3e44734.png)

Cache-Storge
![image](https://user-images.githubusercontent.com/2199151/33423477-41ac78bc-d5b9-11e7-814d-265bc74216e7.png)

**Comment by gauntface** [comment]
To help debug a little could you answer the following:

1.) What is your code to generate the precache lists
2.) What files do you have on your file system
3.) What does your final precache list look like
4.) What files are in the cache after the service worker has installed
5.) What do you expect to happen and what actually happens.

**Comment by gauntface** [comment]
Closing this due to no response.
