### ISSUE TITLE
Author migration guide for sw-framework/goog

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#109]
**Library Affected**:
*sw-framework*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:

Let's write a guide for folks already using sw-precache and sw-toolbox to help them transition their existing code to the newer sw-framework work (I imagine this will primarily be through the higher level library @gauntface has been working on).

**Comment by addyosmani** [comment]
@jpmedley Does it make sense for us to track the docs work for the libraries via this issue tracker or would you prefer for them to live in Web Fundamentals? (I'm still trying to figure out the balance of where guides should live - in-repo vs. WF)

**Comment by gauntface** [comment]
Doc is here: https://docs.google.com/document/d/1qN3dHKkTHG-jWjWTwNzIN7NhVzd555R6FGa3AqRya_c/edit?usp=sharing just needs writing
