### ISSUE TITLE
Follow symbolic links when performing glob operations

### ISSUE THREAD

**Issue by beatrizdemiguelperez** [GoogleChrome/workbox#1093]
**Library Affected**:
workbox-build

**Issue**:
Hi, 
We are trying to wrap workbox with ember build using the package workbox-build. 
On post build hook ember-cli has some symbolic-links. The problem is that when workbox-build tries to list the files, those files that are symbolic are ignored and then not included on the manifest. In fact, we get no error at all.

We want to raise an error when an unusual error is encountered when attempting to read a directory and follow symlinked directories when expanding ** patterns.

For that,[node-glob](https://github.com/isaacs/node-glob) by default dont follow symlinks if its not specified. So we want an available config to add these glob options:

```JavaScript
// config
runtimeCaching: [ ...],
globDirectory: ...
globPatterns: ..
globFollows: true, // new one
globStrict: true // new one
```

On [get-file-details.js](https://github.com/BBVAEngineering/workbox/blob/v3/packages/workbox-build/src/lib/get-file-details.js)

```JavaScript
// 
globbedFiles = glob.sync(globPattern, {
      cwd: globDirectory,
      ignore: globIgnores,
      strict: globStrict,
      follows: globFollows,
    });
```

Thanks!

**Comment by jeffposnick** [comment]
I'm on board with just defaulting to `follows: true` in v3 of `workbox-build`, and marking it as a breaking change.

I can't think of scenarios in which developers would have symbolic links that match one of the patterns but which they wouldn't want to be picked up.

I'll just confirm that the logic we have that generate hashes of files' contents works when the source is a symbolic link, but I'm assuming that `fs-extra` knows how to deal with that automatically.

**Comment by gauntface** [comment]
Would be good to still offer this as an option and default to true.

**Comment by beatrizdemiguelperez** [comment]
https://github.com/GoogleChrome/workbox/pull/1104
