### ISSUE TITLE
Consider --migrate support for the SW-CLI

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#110]
**Library Affected**:
*sw-cli*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:
We might be able to help move more users over to sw-framework by providing a migration flag/option via the CLI that can help rewrite their existing config to use the higher-level framework. 

I'm thinking something that considers their existing config immutable, but can read it and write out new config that works with sw-framework but can be thrown away by the developer once they've confirmed everything works as expected.

**Comment by addyosmani** [comment]
Assigning Matt initially as an idea we might explore if there's time.

**Comment by gauntface** [comment]
@addyosmani closing this as it feels like the CLI and build modules have feature parity with sw-precache and toolbox is similar enough that conversion can be covered in a migration guide.
