### ISSUE TITLE
logs are sometimes not being grouped properly

### ISSUE THREAD

**Issue by beatrizdemiguelperez** [GoogleChrome/workbox#1114]
I notice something weird with logs
Sometimes logs are not being grouped properly and my logs are inside "workbox level"
I mean, the groupEnd sometimes is not working well and my logs go inside yours

![screenshot](https://user-images.githubusercontent.com/9552730/33838069-a6824d56-de8e-11e7-8c54-f6ec269318a9.png)

**Comment by gauntface** [comment]
My guess is that the error is resulting the groupEnd() not getting called. I'll have a look at a fix shortly when I get in the office - will likely need to do this in a few places.

If you get a chance, could you provide the stack trace for "Entry was not found."

**Comment by beatrizdemiguelperez** [comment]
The stack trace for "Entry was not found" was:
`sw.js:1 Uncaught (in promise) DOMException: Entry was not found.
    Promise rejected (async)
   self.addEventListener.event @ _default.mjs:152`
