### ISSUE TITLE
Webpack-Workbox-plugin 3.0.0-alpha.2 console error produced Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by stevenfitzpatrick** [GoogleChrome/workbox#1117]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Chrome 63

**Issue or Feature Request Description**:
Bug

When trying out the v3 version of workbox-webpack-plugin 3, with the following set up.

```
new WorkboxPlugin({
    skipWaiting: true,
    clientsClaim: true
  })
``` 

I am seeing the following console errors when deployed.

```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.prod.js:1:5765
    at new Promise (<anonymous>)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.prod.js:1:5727
    at Generator.next (<anonymous>)
    at n (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.prod.js:1:160)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.prod.js:1:254
    at <anonymous>
```

I have the file deployed here if you want to see in action the error.
https://stevenfitzpatrick.io/

You might need to refresh the page to see the error.

Also seeing a warning regarding source maps produced by the plugin
DevTools failed to parse SourceMap: https://stevenfitzpatrick.io/workbox-sw.prod.v2.1.2.js.map

**Comment by jeffposnick** [comment]
Apologies that you're running into this.

That sounds very much like https://github.com/GoogleChrome/workbox/issues/1109. It should be fixed in the next alpha release (likely later this week).
