### ISSUE TITLE
workbox-webpack-plugin@3.0.0-alpha.2 Service Worker throws this error: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by johnnyreilly** [GoogleChrome/workbox#1119]
**Library Affected**:
*workbox-webpack-plugin@3.0.0-alpha.2*

**Browser & Platform**:
webpack 3

**Issue or Feature Request Description**:
Hi!

When using a Service Worker generated by this code: https://github.com/johnnyreilly/workbox-3-globPatterns-bug-repro but with `new WorkboxPlugin({clientsClaim: true, skipWaiting: true})` in the config and this added to __index.js__: 

```
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('/sw.js').then(registration => {
            console.log('SW registered: ', registration);
        }).catch(registrationError => {
            console.log('SW registration failed: ', registrationError);
        });
    });
}
```

When accessing the application the following error results:

```
DBWrapper.mjs:228 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at result (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.dev.js:1275:32)
    at new Promise (<anonymous>)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.dev.js:1274:28
    at Generator.next (<anonymous>)
    at step (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.dev.js:14:32)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-core.dev.js:25:15
    at <anonymous>
result @ DBWrapper.mjs:228
(anonymous) @ DBWrapper.mjs:227
step @ workbox-core.dev.js:14
(anonymous) @ workbox-core.dev.js:25
Promise rejected (async)
self.addEventListener.event @ _default.mjs:152
```

**Comment by gauntface** [comment]
@johnnyreilly is there anything else on the stack trace? IDBWrapper lives in workbox-core so it's not 100% clear what is causing this.

My hunch is that this is related to a bug that existed in workbox-precaching that is fixed on the v3 branch (I'll cut a release tomorrow so you can try it out). See: https://github.com/GoogleChrome/workbox/issues/1109

**Comment by johnnyreilly** [comment]
That was the full stack trace I'm afraid. Ping me when the release is cut and I'll give it a test. If it's still unhappy I'll supply a minimal repro to ease your investigation

**Comment by gauntface** [comment]
@johnnyreilly could you give v3.0.0-alpha.3 a try and see if you still hit this issue: https://github.com/GoogleChrome/workbox/releases/tag/v3.0.0-alpha.3

**Comment by johnnyreilly** [comment]
Yup - all good.  Well done!
