### ISSUE TITLE
workbox-webpack-plugin 3.0.0-alpha.2 - importWorkboxFromCDN: false not possible

### ISSUE THREAD

**Issue by johnnyreilly** [GoogleChrome/workbox#1122]
**Library Affected**:
*workbox-webpack-plugin@3.0.0-alpha.2*

**Browser & Platform**:
webpack 3

**Issue or Feature Request Description**:
`importWorkboxFromCDN: false` doesn't seem to be a supported option for the Workbox 3 webpack plugin.  I'd really like to push for this to be included as an option.  I'm afraid, based on my own experience, many organisations are likely to resist using Workbox 3.0 if it ties them to a CDN they don't control.  

FWIW I'm not taking a view on this myself, but I'd like to be in a position to use Workbox 3 with clients of mine.

Attempted use errors with:

```
ValidationError: "importWorkboxFromCDN" is not a supported parameter.
```

**Comment by gauntface** [comment]
:+1:

**Comment by jeffposnick** [comment]
Yup, this is still a pain point that needs to be addressed prior to the final v3 release.

https://github.com/GoogleChrome/workbox/issues/933 tracks a similar discussion; @johnnyreilly are you cool with closing this in favor of weighing in there?

**Comment by johnnyreilly** [comment]
Sure - I'll repost there.
