### ISSUE TITLE
Unable to access IndexedDB on Android Webview

### ISSUE THREAD

**Issue by adrigzr** [GoogleChrome/workbox#1123]
**Library Affected**:
*workbox-core*

**Browser & Platform**:
*Android 7 Webview with Google Chrome Chrome/62.0.3202.84*

**Issue or Feature Request Description**:
*On Webviews, when workbox opens IndexedDB for precaching, it throws "DOMException: The user denied permission to access the database.". `StoragePermission` is granted for the app.*
*On the other hand, IndexedDB on `window` context of Webviews is working fine.*
*It seems IndexedDB in ServiceWorkers in Webviews is not supported.*

Edit: remove scaffolding

**Comment by gauntface** [comment]
Thanks for the issue, I'll nudge some people and see if there is an explanation / solution.

**Comment by gauntface** [comment]
Turns out that this was a bug in the webview and has been fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=783159

However, it'll be some time before I imagine the WebView will get updated. The only option I can think of to get around this is to implementa basic precache yourself:

```javascript
self.addEventListener('install', function(event) {
  event.waitUntil(caches.open('mycache').then((cache) => cache.addAll(myUrls)));
});

self.addEventListener('fetch', function(event) {
    if(myUrls.indexOf(event.request.url) !== -1) {
        event.respondWith(caches.match(event.request));
    }
});

// Use Workbox here
```

You can use workbox-build to still get a manifest of assets to precache. There are still likely some nuances I'm missing (like relative URL's vs full URLs on event.request).

cc @jeffposnick in case he has any other ideas.

**Comment by jeffposnick** [comment]
That's a really unfortunate bug. At least the failures weren't a complete mystery.

It's worth noting that in addition to precaching, cache expiration and background sync rely on `IndexedDB` as well, so it's possible that you'd bump up against this bug even if you avoid using precaching.

If I were to recommend a workaround that didn't involve the official Workbox precaching behavior, I'd probably go with a global stale-while-revalidate handler and rely entirely on runtime caching (without cache expiration).

workbox.routing.registerRoute(
  new RegExp('.'), // This will match all same-origin URLs.
  workbox.strategies.staleWhileRevalidate()
);

Using stale-while-revalidate has some drawbacks (you won't end up caching URLs until they've been requested at least once; you'll end up firing off more requests just to revalidate things that might not have changed), but it's a safer approach than doing precaching without having access to `IndexedDB`'s versioning information.

(I'm loathe to suggest it, but if you need something that works right now, [`sw-precache`](https://github.com/GoogleChromeLabs/sw-precache) offers precaching that keeps track of versioning information without depending on `IndexedDB`.)

**Comment by gauntface** [comment]
Side Note: You could warm the runtime cache as outlined in the upcoming docs here: https://github.com/google/WebFundamentals/pull/5493/files#diff-2ab944086580b765976735c780105b07R137

This way you'd have initial cached entries and they'd regularly get updated

**Comment by adrigzr** [comment]
Thanks for the quick response!

Do you know when the patch will be released? Maybe on Chrome 64?

**Comment by jeffposnick** [comment]
I don't have any timelines, but https://bugs.chromium.org/p/chromium/issues/detail?id=783159#c28 has details on which patch releases are likely to get the fix.

**Comment by jeffposnick** [comment]
(Also, I'm going to close this issue for the sake of housekeeping, since I don't think there's anything actionable from the Workbox side of things.)
