### ISSUE TITLE
sw.js:1 Uncaught (in promise) DOMException: The requested version (1) is less than the existing version (2).

### ISSUE THREAD

**Issue by beatrizdemiguelperez** [GoogleChrome/workbox#1124]
Hi,

I got this error on page load:

```
sw.js:1 Uncaught (in promise) DOMException: The requested version (1) is less than the existing version (2).
Promise rejected (async)
self.addEventListener @ workbox-sw.js:274
```

 (screenshot)
![captura de pantalla 2017-12-13 a las 14 40 34](https://user-images.githubusercontent.com/9552730/33941979-c0501650-e014-11e7-94d0-395a77e47c93.png)

ServiceWorker was generated with workbox-build on branch v3 (generateSW) with this options:

```
{ 
  maximumFileSizeToCacheInBytes: 31457280,
  swDest:' ...'
  globDirectory : '...'
  globPatterns: [ '**/*.{json,css,js,png,svg,eot,ttf,woff,jpg,gif,ico,xml,html,txt}' ],
  skipWaiting: false,
  clientsClaim: false,
  importWorkboxFromCDN: false,
  cacheId: 'buzz',
  importScripts: [ 'assets/service-workers/skip-waiting.js' ] 
}

```

**Comment by gauntface** [comment]
I think your versions are getting mixed up somewhere.

If you look in the screenshot - you have workbox-sw.prod.v2.1.2.js in your files, and that would match the error where version 1 of the indexedDB is being used. If you have sw.js building with v3, it'll register v2 of iDB.

My hunch is you were using v3, it registered v3 of indexedDB and for some reason (maybe a fresh install of workbox) you have ended up using Workbox v2 and that is where indexedDB is trying to downgrade.

Is there a URL or a sample repo when can see this on?

**Comment by beatrizdemiguelperez** [comment]
Hi, i can not deploy this, but you are right, i don't know what happened but now i rerun gulp build and it works. Something weird. you can close this issue. I'm sorry

**Comment by gauntface** [comment]
You would not believe how often I hit the same issue - it's easier to do than you'd think.
