### ISSUE TITLE
Docs on how to set credentials

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1131]
This Q: https://stackoverflow.com/questions/47808749/how-to-add-fetch-options-to-workbox

How do we do this for v3?

See: https://github.com/GoogleChrome/workbox/issues/179#issuecomment-351639894 for info.

**Comment by jeffposnick** [comment]
I just took a look at the codebase, and it's not currently possible in v3 for runtime caching strategies.
