### ISSUE TITLE
Add docs on V2 to V3 migration.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1135]
Think it would be good to create this doc to direct people to.

**Comment by ayumihamsaki** [comment]
Hi going to add a comment here if ok. Just going through the doc's now and updating my code from V2 to V3.

I got a question with regards to it and the solution seems to be missing to the doc's.

On the doc's page: https://developers.google.com/web/tools/workbox/guides/common-recipes

Under the heading: Restrict Caches for a Specific Origin

The following code is very useful:

```
workbox.routing.registerRoute(
    'https://hacker-news.firebaseio.com/v0/*',
    workbox.strategies.cacheFirst({
        cacheName: 'stories',
        plugins: [
          new workbox.expiration.Plugin({
            maxEntries: 50,
            maxAgeSeconds: 5 * 60, // 5 minutes
          }),
          new workbox.cacheableResponse.Plugin({
            statuses: [0, 200],
          }),
        ],
    }),
);
```

My question is that when I was using V2 I had the following:

```
    // Set a timeout threshold of 3 seconds to advoid Single Point of Failure
    networkTimeoutSeconds: 3  
```

There is no mention to `networkTimeoutSeconds` so I am not sure if it has been left out of V3 or I need to add it to a plugins[] etc.

I thought I'd ask and also suggest you update the example on that doc's page.

Thanks.

**Comment by ayumihamsaki** [comment]
p.s. +1 for migration doc's although the guide is very good at updating things.

**Comment by addyosmani** [comment]
As a start, we can link folks out to the migration codelab: https://codelabs.developers.google.com/codelabs/sw-precache-to-workbox/index.html?index=..%2F..%2Findex#0

**Comment by DavidScales** [comment]
just to note - that Codelab currently documents an sw-preache --> workbox v2 transition

hopefully @nasearle (who authored it) can update it at some point. would it better as an sw-precache --> workbox v3 lab, or as a workbox v2 --> workbox v3 lab? 

I'm currently updating the [Build a PWA with Workbox Codelab](https://codelabs.developers.google.com/codelabs/workbox-lab/#0) from v2 to v3 right now.

**Comment by gauntface** [comment]
I would love a focus on sw-precache / toolbos to V3.

This V2 to V3 guide will likely be applicable to a smaller bunch of people and the changes can largely be summarised succinctly - I just want it to exist when we launch.

**Comment by nasearle** [comment]
Should be able to start updating that codelab this week! I'll keep you posted

**Comment by jeffposnick** [comment]
These were published at https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2
