### ISSUE TITLE
Make swSrc webpack plugin mode toggling explicit?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1136]
**Library Affected**:
*workbox-webpack-plugin*

As of v3-alpha.3, the `workbox-webpack-plugin` supports two distinct modes, which roughly translate to what we refer to as `generateSW` and `injectManifest` elsewhere in Workbox.

- If `swSrc` *is not* configured, then the plugin is in `generateSW` mode, where the entire service worker file is created "from scratch" each time a build occurs.
- If `swSrc` *is* configured, then we're in a rough equivalent of `injectManifest` mode, where a source service worker file is mostly left as-is, with the only changes being those necessary to import the Workbox runtime and fresh precache manifest. (This isn't 100% the same as `injectManifest` elsewhere, since it's a call to `importScripts()` that's injected, rather than values in the `precacheAndRoute()` array. But it's functionally equivalent.)

For `workbox-build` and `workbox-cli`, we decided that developers should explicitly choose which mode they wanted, instead of inferring the mode based on the presence/absence of a config parameter. This makes it easier to reason about the different ways of using the plugin, without having to read through each parameter description and realize that something is fundamentally different when one of those parameters is set.

If we were to make the same decision for `workbox-webpack-plugin`, we could do that by removing the current default export of the `WorkboxWebpackPlugin` class from our source code and instead use two named exports of new classes, `GenerateSW` and `InjectManifest`.

So the current source code

```js
// Inside workbox-webpack-plugin/src/index.js:
module.exports = WorkboxWebpackPlugin;
```

would change to

```js
// Inside workbox-webpack-plugin/src/index.js:
module.exports = {
  GenerateSW,
  InjectManifest,
};
```

and usage would be:

```js
// Inside webpack.config.js:
const WorkboxPlugin = require('workbox-webpack-plugin');
module.exports = {
  plugins: [
    new WorkboxPlugin.GenerateSW({})
  ],
};
```

CC: @gauntface @goldhand for thoughts.

**Comment by gauntface** [comment]
This looks good to me, only comment is whether this is any value instead of new, just do:

```javascript
plugins: [
    workbox.generateSW({})
]
```

Removing the "new" and lower casing the method name.

**Comment by jeffposnick** [comment]
Every Webpack plugin that I'm familiar with follows the pattern of exposing a class that gets explicitly initialized inside of the `plugins: []` array. That's the model used in the https://webpack.js.org/contribute/writing-a-plugin/ docs, as well.

They're obviously equivalent, but I'm assuming it would feel more fluent for webpack users if we went with `new WorkboxPlugin.GenerateSW({})`.

**Comment by gauntface** [comment]
SGTM

**Comment by prateekbh** [comment]
+1 for `new` pattern. practically every webpack plugin i have used is like this
