### ISSUE TITLE
Question: networkTimeoutSeconds in V3

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1140]
Hi I'm in the progress of updating from V2 to V3 and reading through all the new guide (Very Good by the way!!!) 

I got a question - issue with regards to it and the solution seems to be missing from the doc's.

On the doc's page: https://developers.google.com/web/tools/workbox/guides/common-recipes

Under the heading: Restrict Caches for a Specific Origin

The following code is very useful:

```
workbox.routing.registerRoute(
    'https://hacker-news.firebaseio.com/v0/*',
    workbox.strategies.cacheFirst({
        cacheName: 'stories',
        plugins: [
          new workbox.expiration.Plugin({
            maxEntries: 50,
            maxAgeSeconds: 5 * 60, // 5 minutes
          }),
          new workbox.cacheableResponse.Plugin({
            statuses: [0, 200],
          }),
        ],
    }),
);
```

My question - issue is that when I was using V2 I had the following:

```
// Set a timeout threshold of 3 seconds to avoid Single Point of Failure
networkTimeoutSeconds: 3  
```

There is no mention to `networkTimeoutSeconds` so I am not sure if it has been left out of V3 or I need to add it to a plugins[] or outside of that section etc.

Thanks.

**Comment by jeffposnick** [comment]
Hello @ayumihamsaki—`networkTimetoutSeconds` is still supported in v3, and is documented at https://developers.google.com/web/tools/workbox/reference-docs/prerelease/workbox.strategies.NetworkFirst

Please note that it's only a valid options when using the `NetworkFirst` strategy, so that's the only place it appears in the docs.

**Comment by gauntface** [comment]
@jeffposnick I'm going to keep bugs like this open as it's a point we can add to the docs that will hopefully help others.

**Comment by ayumihamsaki** [comment]
Thank you @jeffposnick I was about to use it for a `CacheFirst` strategy as well. So I will make a note of that.

@gauntface where can I keep in the loop, as you mentioned you might be creating a V2 to V3 migration guide. As I would be keen to see it and also I seem to be getting some strange errors with V3 alpha 3. So have decided to wait for a beta release and try again with upgrading from V2.1.0
