### ISSUE TITLE
Please version the documentation for Workbox 

### ISSUE THREAD

**Issue by ZhangYiJiang** [GoogleChrome/workbox#1147]
I've just wasted an hour trying to figure out why some options were having no effect, only to realize that I was looking at the docs for version 3, while we are still using version 2. 

There's no indication *anywhere* on the page which version I'm looking at - not in the URL, the header or footer. The documentation for v3 for some components already rank higher than v2 on Google searches, even though the former is still in alpha. 

Webpack plugin documentation for v3: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin  
Webpack plugin documentation for v2: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin-WorkboxBuildWebpackPlugin and https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build

**Comment by gauntface** [comment]
@ZhangYiJiang thanks for the issue - do you have any opinion on where it would make most sense to add the version number?

**Comment by ZhangYiJiang** [comment]
The easiest way would be to just add it to the title of the project on the documentation - for example, Google Sheets API [v3](https://developers.google.com/sheets/api/v3/) vs [v4](https://developers.google.com/sheets/api/reference/rest/). 

A more elegant solution would be to make the version number part of the URL, and put the version number somewhere on the page as a menu and let users switch between different versions, eg [Laravel, in the header](https://laravel.com/docs/5.5) and [Django, stickied to bottom right corner](https://docs.djangoproject.com/en/1.11/)

**Comment by gauntface** [comment]
Thanks @ZhangYiJiang I'll take a look.

I've avoided the version number in the URL for the main URL's simply because google results end up being a nightmare (i.e. old docs get surfaced instead of the newest). But there should be ways around this.

**Comment by gauntface** [comment]
@ZhangYiJiang please re-open if you think this isn't enough.

**Comment by ZhangYiJiang** [comment]
Hi, thanks for the quick response! The changes to the reference documentation are fine, however the v3 page I linked in above still does not have any sort of indication that it is v3. I noticed there's warning at the top of pages in the 'Guides' section - it may be useful to have this over on the pages in the 'Modules' section too 

![screenshot from 2018-01-04 14-22-21](https://user-images.githubusercontent.com/445650/34552138-b984cb2a-f15a-11e7-9d9d-dce15ed41295.png)

**Comment by gauntface** [comment]
Adding that in this PR: https://github.com/google/WebFundamentals/pull/5604
