### ISSUE TITLE
V3 documentation (minor) - redundant code in example

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1152]
**Library Affected**:
*workbox-sw*

**Issue**
*v3 documentation*
 
I just started reading through the v3 docs - they are awesome so far! :D

The [Force a Timeout on Network Requests example](https://developers.google.com/web/tools/workbox/guides/common-recipes#force_a_timeout_on_network_requests) in the Common Recipes section is as follows:

```
workbox.routing.registerRoute(
    'https://hacker-news.firebaseio.com/v0/*',
    workbox.strategies.networkFirst({
        networkTimetoutSeconds: 3,
        cacheName: 'stories',
        plugins: [
          new workbox.expiration.Plugin({
            maxEntries: 50,
            maxAgeSeconds: 5 * 60, // 5 minutes
          }),
          new workbox.cacheableResponse.Plugin({
            statuses: [0, 200],
          }),
        ],
    }),
);
```

I see here that the `cacheableResponse` statuses include 0 for no-CORS requests. Should the `cacheableResponse` plugin be redundant in this example, since the `networkFirst` strategy accepts 0 status responses by default (as described in [Handle Third Party Requests](https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests))?

**Comment by gauntface** [comment]
Thanks for calling this out @DavidScales - should be fixed with linked PR.
