### ISSUE TITLE
V3 documentation - canonical method for setting cache expiration in routes

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1153]
**Library Affected**:
*workbox-sw*

**Issue**:
*v3 documentation*

I see that there are two documented ways of configuring cache expiration details when setting up a route.

In the [Get Started](https://developers.google.com/web/tools/workbox/guides/get-started) guide, the `cacheExpiration` property is used directly (note that I stripped the comments from this snippet): 

```
workbox.routing.registerRoute(
  /.*\.(?:png|jpg|jpeg|svg|gif)/,
  workbox.strategies.cacheFirst({
    cacheName: 'image-cache',
    cacheExpiration: {
      maxEntries: 20,
      maxAgeSeconds: 7 * 24 * 60 * 60,
    }
  })
);
```
and in the [Home page](https://developers.google.com/web/tools/workbox/next/) & most other places, `workbox.expiration.Plugin` is used:

```
 workbox.routing.registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  workbox.strategies.cacheFirst({
    cacheName: 'images',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
); 
```

I think this may have been the case for v2 as well. Is it safe to assume that the canonical method is the latter, since I see that in most places? Is the former example just shorthand for simplicity?

**Comment by gauntface** [comment]
We ended up removing the first approach you call out because it meant that there was no way to use the cacheFirst strategy without loading all plugins. Instead the developer has to explicitly add the plugin (as shown in the second example).

Should be fixed in the linked PR.
