### ISSUE TITLE
Generate Changelog 

### ISSUE THREAD

**Issue by romulocintra** [GoogleChrome/workbox#1159]
**Issue or Feature Request Description:**

Will be great if in some way you can generate a change log to easy follow changes on workbox , i've been following commits etc ... but change log will be really helpful to all community using workbox

**Comment by jeffposnick** [comment]
Our strategy has been to compile a list of changes in each tagged release we publish, and make those available at https://github.com/GoogleChrome/workbox/releases

We've got another alpha release coming up shortly, and we'll continue that practice to cover the significant changes.

Then, when the final v3 release is ready, we'll aggregate all of the individual pre-release change listings into a single larger list (ideally in the context of a migration guide; see https://github.com/GoogleChrome/workbox/issues/1135).

Does that plan sound like what you're looking for?

**Comment by gauntface** [comment]
@romulocintra if the above doesn't work for you - can you suggest any way of automatically managing this? I can guarantee that we will fail to manage it manually.

**Comment by romulocintra** [comment]
Hi  @gauntface  and @jeffposnick  , your are doing a good job 🥇 with workbox and we are following updates on codebase to keep up to date  in our developments . The previous strategy for me is ok and together with commit history is "easy"  to track  changes.

But following a pattern and using something like  [lerna-changelog](https://github.com/lerna/lerna-changelog) could make easy and all changes will be tracked in more "organized" way.

**Comment by gauntface** [comment]
@romulocintra I'm fine with adding this in. We currently have a github publish step that posts a draft for each release so if we could get the change log from the module, we can just auto-add it to the github release.

Is there anyone wanting to have an attempt at this?

**Comment by romulocintra** [comment]
@gauntface i can take a look at ;)

**Comment by romulocintra** [comment]
@gauntface  silly question on runing demos  locally 

gulp demos:serve:local

Error: Unable to authorize access to project workbox-demos

**Comment by gauntface** [comment]
Chances are thats Firebase's serving infra not working because you don't have access to firebase project (Not that it's needed for any reason other than Google Cloud probably being greedy with it's emulation)

**Comment by jeffposnick** [comment]
I'm honestly okay with our current process of "hand crafting" release notes, based on looking at all the PRs that have come in since the previous tagged release. I think it lets us give developers an overview of what we consider the most important changes, and GitHub's native tools for comparing tags could be used to generate a complete list of changes if someone really needs to determine every single line of code that's been modified.

I'm closing this for now—if folks disagree, we can revisit.
