### ISSUE TITLE
Add docs on using Workbox CLI in Alpha 

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1162]
The command should be:

```
npm install -g workbox-cli@3.0.0-alpha.3
```

But we don't document this in the "next" release docs.

**Comment by svdoever** [comment]
We are now already at workbox-cli@3.0.0-alpha.6, did this by trial and error... is there a way to specify "latest" from the alpha, like in @next that is used by many other libs?

**Comment by jeffposnick** [comment]
Looks like @gauntface added info on installing the beta release [to the docs](https://developers.google.com/web/tools/workbox/modules/workbox-cli#install_the_cli). It's

```sh
npm install workbox-cli@beta --global
```
