### ISSUE TITLE
Question: Which file to link too?

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1163]
Sorry this might be the dumbess question in the world.

It seems like everything in V2 has been changed. I will post a screenshot of the old layout:

![1](https://user-images.githubusercontent.com/17784082/34722979-dbeaed40-f540-11e7-804e-abee2323e79c.png)

So before we would link to a .js file in the import scripts choosing either production or dev. Now all that is gone and we have this:

![2](https://user-images.githubusercontent.com/17784082/34723099-38de1220-f541-11e7-9378-3fdbc77017a2.png)

So my question is which .js file do we link up too now?

The `build.js` or `index.js` in each package.

Also you should update your examples website as well, see here:

https://workbox-samples.glitch.me/examples/workbox-sw/

The code line:

`importScripts('https://unpkg.com/workbox-sw@2.0.3/build/importScripts/workbox-sw.dev.v2.0.3.js');`

Is still using the old method of dev / prod.

Thanks and sorry this is a dumb question I feel, I just want to double check.

**Comment by jeffposnick** [comment]
I'm sorry that you're running into issues.

You mention that something's changed with your local copies of the Workbox library, but can you let us know whether you recently did something like reinstall the library via `npm`, or redownload an archive of the library files (if so, from which URL)?

Since you're showing screenshots of your local filesystem, we need to know what method you used to obtain the files locally, and then we should be able to point you in the right direction.

**Comment by ayumihamsaki** [comment]
Hi @jeffposnick 

I have worked it out now after reading your comment. Yes you are correct. When you download using `npm` and download the `zip` from the releases section they are not packaged in the same way. I thought they were exactly the same, but they are totally different.

To answer you: I first downloaded using `npm`, but today I downloaded using the releases `zip`.

Thanks for your help, personally I would think it's better to have both the same.

Thanks for your time.

**Comment by jeffposnick** [comment]
Thanks to @gauntface's efforts, the upcoming v3 releases will all have links to `.zip` archives of the fully compiled library code. You can see that for one of the v3 alpha releases at https://github.com/GoogleChrome/workbox/releases/tag/v3.0.0-alpha.4

(In v3, you'll also be able to run `workbox copyLibraries <path/to/dest/dir>` using `workbox-cli`.)

So you're suggestion will be implemented in the near future.
