### ISSUE TITLE
add expiration rule for globPatterns in workbox-build?

### ISSUE THREAD

**Issue by nulun** [GoogleChrome/workbox#1167]
Can I add expiration rules for globPatterns in workbox-build?

**Comment by gauntface** [comment]
@nulun the globPatterns is for precaching (i.e. caching files during the installation of the service worker). To change these files, you should publish a new service worker (i.e. re-deploy your app).

The expiration is useful for files that don't need to be cached during install and / or for files that are dynamic and seperate from your build process.

For that you should be using a strategy under `workbox.strategies` and using the expiration on that.

If you still have more questions, could you show some example config you are using and your use case.
