### ISSUE TITLE
Error: Plugin.cacheWillUpdate() fails to return Response

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1185]
**Library Affected**:
*workbox-sw (v3 alpha 5)*

Hi again @gauntface,

#1182 fixes my issue in #1178 👍 

but my original code:

``` javascript
// building directly from Workbox repo
importScripts('workbox-sw.js');
importScripts('workbox-cache-expiration.dev.js');
importScripts('workbox-core.dev.js');

workbox.routing.registerRoute(
  /(.*)articles(.*)\.(?:png|gif|jpg)/,
  workbox.strategies.cacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200],
      }),
    ]
  })
);
```

is now throwing a new console error: 

```
Uncaught (in promise) WorkboxError: The return value from 'Plugin.cacheWillUpdate()' must be an instance of class Response.
    at Object.isInstance (http://localhost:8081/workbox-core.dev.js:513:11)
    at http://localhost:8081/workbox-core.dev.js:927:28
    at Generator.next (<anonymous>)
    at step (http://localhost:8081/workbox-core.dev.js:14:32)
    at http://localhost:8081/workbox-core.dev.js:25:15
    at <anonymous>

WorkboxError | @ | workbox-core.dev.js:325
  | isInstance | @ | workbox-core.dev.js:513
  | (anonymous) | @ | workbox-core.dev.js:927
  | step | @ | workbox-core.dev.js:14
  | (anonymous) | @ | workbox-core.dev.js:25
  | Promise rejected (async) |   |  
  | (anonymous) | @ | workbox-strategies.dev.js:169
  | step | @ | workbox-core.dev.js:14
  | (anonymous) | @ | workbox-core.dev.js:25
  | Promise resolved (async) |   |  
  | step | @ | workbox-core.dev.js:24
  | (anonymous) | @ | workbox-core.dev.js:32
  | (anonymous) | @ | workbox-core.dev.js:11
  | _getFromNetwork | @ | workbox-strategies.dev.js:172
  | (anonymous) | @ | workbox-strategies.dev.js:116
  | step | @ | workbox-core.dev.js:14
  | (anonymous) | @ | workbox-core.dev.js:25
  | Promise resolved (async) |   |  
  | step | @ | workbox-core.dev.js:24
  | (anonymous) | @ | workbox-core.dev.js:32
  | (anonymous) | @ | workbox-core.dev.js:11
  | handle | @ | workbox-strategies.dev.js:150
  | handleRequest | @ | workbox-routing.dev.js:365
  | workbox.routing.self.addEventListener.event | @ | workbox-routing.dev.js:817
```

Sorry to keep breaking stuff 😿

**Comment by gauntface** [comment]
Are you sure everything is up to date? 

This looks like workbox-core is up to date but the cacheable-response plugin is not, i.e. it's returning a promise like it did before which caused the original error.

**Comment by NoamPaz** [comment]
I am using it as following:
```
workbox.routing.registerRoute(
	({ url }) => {
		if (url.origin !== location.origin) {
			return false;
		}
		return (/.*f2f_config\.json/).test(url.href);
	},
	workbox.strategies.networkFirst({
		cacheName: `${prefix}-${runtime}-${suffix}`,
		plugins: [
			new workbox.expiration.Plugin({
				maxAgeSeconds: 60 * 60
			}),
			new workbox.cacheableResponse.Plugin({
				statuses: [0, 200, 304]
			})
		]
	})
);
```
And I'm still getting:
```
workbox-core.prod.js:1 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': parameter 2 is not of type 'Response'.
    at Object.<anonymous> (workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at workbox-core.prod.js:1
    at <anonymous>
```
I thought it was already solved and I'm using alpha.5.
@DavidScales Does the above error happen to you? The examples are almost the same, except I'm using networkFirst, while you're using cacheFirst strategy.

**Comment by DavidScales** [comment]
@gauntface I'm not entirely sure, here is what I'm doing:

1. git pull workbox repo's v3 branch
2. `npm install` & `gulp build` to generate the most up-to-date files
3. copying the generated files (`workbox/packages/workbox-cache-expiration/build/workbox-cache-expiration.dev.js`, etc.) into my local app directory
3. `importScript`ing those into my SW instead of the v3-alpha-5 file from the CDN. 

Is this the right process / what can I do to confirm that I'm getting the most up-to-date files?

@NoamPaz I was originally getting that error, and do still get that error when using alpha 5 from the CDN. I think the CDN is simply not updated with the most recent changes. Could you try my method described above and see if it resolves your issue and/or if you get the same results as I do?

**Comment by gauntface** [comment]
@DavidScales can you create a fake repo with just the build files that reproduces the problem?

**Comment by DavidScales** [comment]
@gauntface Okay here is the [code repo](https://github.com/DavidScales/workbox-test). 

If you clone the repo & run a local server, you should see the `The return value from 'Plugin.cacheWillUpdate()' must be an instance of class Response` error. 

However, the GitHub pages [hosted app](https://davidscales.github.io/workbox-test/index.html), throws a different error... of course ;) For that, on install I get:

```
Uncaught TypeError: Cannot read property 'isType' of null
  | Plugin | @ | workbox-cache-expiration.dev.js:450
  | (anonymous) | @ | sw.js:37
```
but one bug at a time is fine for now haha

**Comment by nasearle** [comment]
Including the workbox-cacheable-response.dev.js file fixes the error

**Comment by nasearle** [comment]
Also works with just the workbox-sw.js library imported if we use the short hand code without using the plugins explicitly:

```
importScripts('workbox-sw.js');

workbox.routing.registerRoute(
  /(.*)articles(.*)\.(?:png|gif|jpg)/,
  workbox.strategies.cacheFirst({
    cacheName: 'images-cache',
    cacheExpiration: {
      maxEntries: 50,
      maxAgeSeconds: 30 * 24 * 60 * 60,
    },
    cacheableResponse: {statuses: [0, 200]}
  })
);
```

**Comment by DavidScales** [comment]
@nasearle ah yes! adding that file fixes it, thanks. I think Matt said they are moving away from supporting the shorthand in #1153 

@gauntface you were right I just misread **cacheable-response** plugin as **cache-expiration** plugin in your previous message (my bad), thanks!

@NoamPaz using the earlier mentioned strategy seems to be working now - I just modified my code to include the additional library:

```javascript
// building directly from Workbox repo
importScripts('workbox-sw.js');
importScripts('workbox-cache-expiration.dev.js');
importScripts('workbox-core.dev.js');
importScripts('workbox-cacheable-response.dev.js');

workbox.routing.registerRoute(
  /(.*)articles(.*)\.(?:png|gif|jpg)/,
  workbox.strategies.cacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200],
      }),
    ]
  })
);
```

I've updated my test [repo](https://github.com/DavidScales/workbox-test), but the GitHub Pages [hosted site](https://davidscales.github.io/workbox-test/) still throws that `Cannot read property 'isType' of null` error. Which is weird and I'm fine with splintering that into a separate issue if appropriate and/or coming back to it later.
