### ISSUE TITLE
Missing files in the precache (only up to 50 files)

### ISSUE THREAD

**Issue by NoamPaz** [GoogleChrome/workbox#1189]
**Library Affected**:
3.0.0-alpha.5

**Browser & Platform**:
Version 63.0.3239.108 (Official Build) (64-bit) - PC

**Issue Description**:
I'm using precache as following:
```
if (Array.isArray(self.__precacheManifest)) {
	workbox.precaching.suppressWarnings();
	workbox.precaching.precacheAndRoute(self.__precacheManifest, {
		ignoreUrlParametersMatching: [/./]
	});
}
```
I have a precache manifest array with 80 files.
After the workbox was loaded I get a "prefetching 80 files" message in the console, but in the application tab of the devtool I see only 50 files under the install time cache storage.
Can you please try a manifest with more than 50 files and count how many files is actually in the cache storage?

**Comment by jeffposnick** [comment]
Chrome's cache storage viewer paginates the entries, and only shows 50 at a time.

To move between pages of entries, use the back/forward arrows at the top of the viewer:

<img width="118" alt="screen shot 2018-01-18 at 10 32 16 am" src="https://user-images.githubusercontent.com/1749548/35106003-155fe642-fc3b-11e7-8995-b94e078ace4a.png">

**Comment by NoamPaz** [comment]
Thanks @jeffposnick. How did I miss those buttons :/

**Comment by jeffposnick** [comment]
Don't blame yourself for a non-obvious UX!

**Comment by gauntface** [comment]
Please feel free to file bugs on crbug.com for things like this - I've hit this issue some many times and without more reports - the devtools team won't change it.
