### ISSUE TITLE
Have another parse at webpack docs.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1202]
https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

May be out of date with latest changes - configuration is still insanely large block of content, if there is a better way to present the information, we should go for it.

**Comment by jeffposnick** [comment]
(Also tracked in https://github.com/google/WebFundamentals/issues/5567, and is currently a WIP to reflect the latest changes.)

**Comment by jeffposnick** [comment]
See https://github.com/google/WebFundamentals/pull/5677

**Comment by gauntface** [comment]
I still think the information could be reorganized to be easier to read / navigate.

At the moment the top level structure is:

- What are the plugins?
- Considerations
    - Should the plugin create your service worker file?
    - Do you need to cache additional, non-webpack assets?
- Configuration
    - GenerateSW Plugin
    - InjectManifest Plugin

Ideally it would look a little more like:

- What are the Webpack Plugins?
- Generate a complete SW
- Inject a Manifest
- How to cache extra assets
- Configuration Options
    - GenerateSW Plugin
    - InjectManifest Plugin
