### ISSUE TITLE
Add FAQ with explanation of scoping

### ISSUE THREAD

**Issue by izyl** [GoogleChrome/workbox#1211]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*Google Chrome Version 63.0.3239.132 (Build officiel) (64 bits)*

**Issue or Feature Request Description**:
*Route is not working if sw.js is not served at root*

## Context description 

Hello all,

I got a portal with a lot of site like this :
server:port/portal/app1
server:port/portal/app2
...
server:port/commons/servlet1
server:port/commons/servlet2
...

And i got an SPA running under server:port/portal/app1
Now i need my SPA to be a PWA so i would like to use Workbox and especially the Router feature.

## Problem

if i don't serve sw.js at the root ie : server:port/sw.js
The routing is not working for internals : server:port/xxx
**And its not working for externals also** : https://httpbin.org/image/(.*)

The routes are registered but nothing goes to the chache. In this configuration the only files that go to the cache is the precached ones.

So i tried to make it work on a simple server : 
To test out i am using external urls provided in the router example
With the same file locations it is still not working, but when i move my sw.js directly at localhost:port/sw.js
then the routes are working and i can see my files cached

```
const workboxSW = new self.WorkboxSW({
	skipWaiting : true,
	clientsClaim : true
});

workboxSW.router.registerRoute('https://httpbin.org/image/(.*)', workboxSW.strategies.cacheFirst({
	cacheName : 'images',
	cacheExpiration : {
		maxEntries : 2,
		maxAgeSeconds : 7 * 24 * 60 * 60,
	},
	cacheableResponse : {
		statuses : [ 0, 200 ]
	},
}));
```

Is there a way to make the routes working if my sw.js is not at the root of my server ?

**Comment by jeffposnick** [comment]
You're bumping into restrictions in the service worker specification.

There's background information on service worker scoping at various places:
- https://stackoverflow.com/questions/35780397/understanding-service-worker-scope
- https://developers.google.com/web/fundamentals/primers/service-workers/#register_a_service_worker
- https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#scope_and_control

In practice, it sounds like you have two options:
1. Deploy a separate service worker file for each app instance, hosted at `https://server:port/portal/appN/sw.js`. Those service workers can be configured differently, with independent routing logic.
2. Deploy a single service worker file that could control all pages for all of your separate web apps, hosted at `https://server:port/sw.js`. This top-level service worker file would contain all of your runtime routing information, which you'd have to keep up to date as you deployed additional independent apps. This would also make it difficult to do precaching, since you wouldn't know which apps should have their resources precached.

**Comment by izyl** [comment]
I knew about the scope pb this id why i tried attention the root ans resigned myself tout add a route in the server config. 

But i don't understand why route doesnt work for external urls when the service worker is nested ?

**Comment by gauntface** [comment]
@izyl You should be able to get requests for external URL's in your page *if* your service worker is controlling the current page the user is viewing.

A service worker can control the current page *if* it's scope matches that of the current page.

The scope is a little tricky to explain but previously I had written to describe it:

> When you register a service worker, it is given a “scope” which be default is the location of the service worker. The scope restricts which pages are controlled by a service worker.
> 
> For example, if we register a service worker with this code:
>
> ```javascript
> navigator.serviceWorker.register('/sw.js', {scope: '/blog/'});
> ```
> 
> What we are saying is that the service worker should only control pages that have a URL starting with /blog/ on our site. If we left out the scope argument, the scope would have be ‘/’ since that is the location of the service worker file, in that case any page starting with ‘/’ will be controlled — i.e. every page on the site.
> 
> One thing to note is that scopes must can be made longer that the location of the service worker file, but they can’t be shortened or completely different.
>
> ```javascript
> // OK
> navigator.serviceWorker.register(‘/blog/sw.js’, {scope: ‘/blog/article/’});
> 
> // Not OK
> navigator.serviceWorker.register(‘/blog/sw.js’, {scope: ‘/’});
> 
> // Not OK
> navigator.serviceWorker.register(‘/blog/sw.js’, {scope: ‘/about/’});
>```
> 
> There is however a way around this limitation, if the web server that serves the service worker file includes a ‘Service-Worker-Allowed’ header, the header value can define the valid minimum scope.
> 
> ```javascript
> // OK when ‘Service-Worker-Allowed’ header is set to ‘/’
> navigator.serviceWorker.register(‘/blog/sw.js’, {scope: ‘/’});
> ```

Does that make things more confusing or easier to understand? Either way we should add some info on this on the Workbox site as you're the second person to hit this issue recently.

**Comment by izyl** [comment]
Ok i understand and i will try what you say.

**I modified my tomcat to serve the sw.js at the root and now all my routes are working.**
This is enough for me since i got only one disconnect SPA in my portal for the time being.

Thank you a lot for your time and this wonderfull project.
The loading time is incredible, i can even load a page with data in tables instantly, you give us INCREDIBLE UX.
Keep on changing the web !

**Comment by gauntface** [comment]
Thanks @izyl. I'm going to change the title of this bug to add the above to an FAQ as I fear this question may keep on arising and having a consistent place to tweak the wording for easier understanding would be useful.

**Comment by garviand** [comment]
*bump* this did trip me up for a while. I was under the impression that you can have a service worker registered at any scope to control any page, but it could not intercept fetch events for URLs outside of its scope. This isn't as much of a workbox issue as a general service worker issue to be fair.

**Comment by gauntface** [comment]
@garviand no need to bump - I will get to this.
