### ISSUE TITLE
Investigate reducing the size of the production bundles

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/workbox#1218]
Comparing two examples of same `preact-cli` project below for simple precache use case.

1.) https://preact-cli-workbox.surge.sh/ <= With workbox

2.) https://default-preact-cli.surge.sh/ <= With sw-precache

The first one's(Workbox) sw file usage cost ~13kb(core+precache+actual SW - manifest) while the later(sw-precache) costs ~4kb(actual SW + manifest).

**Comment by gauntface** [comment]
This isn't something we can really do anything about in v3 as we are too late in the game, but we could try and have another crack and file size in v4.

@prateekbh it would be helpful if you can just dump these files into a repo - just so that we can easily view the contents of files (I'm not crazy familiar with sw-precache's output).

It's also very justified to stick with sw-precache (or anything else) if it's serving the purpose needed.

**Comment by gauntface** [comment]
I've taken @prateekbh's builds and just reduced it down to the source code for sw precache and workbox.

[Service Worker Pieces.zip](https://github.com/GoogleChrome/workbox/files/1657117/Service.Worker.Pieces.zip)

This is a kind of brain dump.

SW-Precache:
- sw.js 4030B (4KB) **GZIP: 1.73KB**

Workbox Files:
- sw.js 945B (1KB) **GZIP: 515B (0.5KB)**
- precache-manifest 1469B (1.5KB) **GZIP: 538B (0.5KB)**
- workbox-core.prod.js 6379B (6KB) **GZIP: 2.53 kB**
- workbox-precaching.prod.js 5183B (5KB) **GZIP: 2.02 Kb**

# sw.js
sw-precache's  `sw.js` file minified where as workbox's is not. This is minimal but for the sake of completeness it is a saving we are missing out on. 

Did sw-precache minify it's output?

# Manifest.js

The manifest output for sw-precache vs workbox again shows some growth in file size for Workbox.

Moving the `precacheManifest` variable out of SW-precache's sw.js into file shows its 1084B (about 0.5KB saving on the Workbox Manifest).

Workbox can get down to 1139B (1KB) by removing padding and by not quoting the keys `revision` and `url`.

We will generally be larger as the format of `revision` and `url` requires it.

Comparing GZIP size of sw-precache vs workbox manifests (SW-Precache is 567B and Workbox with changes mentioned above is 516B)

# Workbox Core + Precaching vs sw-precache Templating

This is obviously a big chunk of stuff on workbox core that may not be needed by precaching and precaching is still larger on it's own compared to sw-precache.

Feautre Differences I am aware of when comparing workbox v3 and sw-precache:
- Cache names are just string in sw-precache. We have more logic in workbox.
- All options can be configured in library vs template (i.e. sw-precache just stamps in the value, we have defaults + checks)
- Precaching has plugin support that sw-precaching does not.
- Optional skipWaiting and clients claim is heavier than just stamping out
- We've add support for pretty URL's and extra url manipulation compared to sw-precache.
- Workbox is using indexedDB vs in memory info from sw-precache.
- Workbox requires the babel async await generators where as sw-precache is just promise based.

Core is probably bigger than I would have liked but this contains:
- Logger that could perhaps be stripped out (Same as assert is)
- Cache name handling
    - This is more complex than before and while it add's benefits, I know Surma raised some concerns about it not really sitting well with him
- Fetch Wrapping and Cache Wrapping is a large chunk of logic that sw-precache didn't have.
- IndexedDB support. I still would keep this as it makes precaching usable outside of workbox-precaching (i.e. you could precache and then add your own fetch handling etc.

Possible Action Items:
- Ensure we can minify `sw.js` with our webpack plugin
    - Talking to Prateek he mentioned that he just used the sw-precache plugin as it and it produced minified output, so sounds like we are missing a trick somewhere.
- Minify our precache manifest
- Remove logger from prod builds
- Land https://github.com/GoogleChrome/workbox/pull/1183 to support minifying babel generator etc
- Research further savings with shared minification:
    - More classes in workbox-core are private but because they are referenced by other modules, the naming is kept at the moment. With shared uglified names, can we minify the private core modules?
- Investigate the cost of asyncToGenerator again - just to confirm what the size diff is compared to normal promises.

**Comment by jeffposnick** [comment]
We've removed the IndexedDB code from `workbox-precaching` and the async-to-promise runtime code across the board. My understanding is that the `preact-cli` integration has gone forward.

I'm going to close this with the understanding the developers who need more control over exactly what code is included in their service worker in the future can generate their own custom bundle of exactly the Workbox code that they want.

@philipwalton is going to be publishing some guidance for doing this using Workbox v4 in the near future.

**Comment by behnam-maqsudi** [comment]
@gauntface workbox caches files is too much how fix that

i just have multi js file 
![image](https://user-images.githubusercontent.com/40948849/93604167-42601000-f9da-11ea-9695-304de76057d9.png)

but storage size 44mB :)

![image](https://user-images.githubusercontent.com/40948849/93604217-53108600-f9da-11ea-81f6-984dd5653f79.png)
