### ISSUE TITLE
Throw when precaching is used async

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1224]
Throw error when precache is used async (i.e. not in the synchronous flow of the service worker).

@sorin-davidoi was attempting to do the following:

```javascript
addEventListener('message', function(event) {
    const { data: { chapters } } = event;

    workbox.precaching.precacheAndRoute(
        chapters.map(chapter => ({ url: chapter, revision: chapter }))
    );
});
```

**Comment by jeffposnick** [comment]
This will end up throwing in Chrome soon by virtue of disallowing async `importScripts()`.

It's not specific to `workbox.precaching`, but we've added guidance about avoiding this at https://developers.google.com/web/tools/workbox/modules/workbox-sw#avoid_async_imports
