### ISSUE TITLE
Service worker event waitUntil() was passed a promise that rejected with 'Error: '.

### ISSUE THREAD

**Issue by maple3142** [GoogleChrome/workbox#1229]
**Library Affected**:
workbox-build@2.1.2

**Browser & Platform**:
chrome 63 & firefox 58 on windows 10

**Issue or Feature Request Description**:
go to [https://blog.maple3142.net/](https://blog.maple3142.net/) and open console, and get an error
but no error on a local http server

firefox error message: 
```
Service worker event waitUntil() was passed a promise that rejected with 'Error: '.
```
chrome error message: 
```
Uncaught (in promise) WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"https://blog.maple3142.net/404.html","error":{"name":"invalid-response-for-caching","message":"The fetched response could not be cached due to an invalid response code."}}'
    at https://blog.maple3142.net/wb.js:160:1358
    at Generator.throw (<anonymous>)
    at step (https://blog.maple3142.net/wb.js:83:30)
    at https://blog.maple3142.net/wb.js:96:13
    at <anonymous>
```

[gulp config of workbox](https://github.com/maple3142/Blog/blob/0f19a45b4de81aea07b53328ef0d4bddc08fa625/gulpfile.js#L185)
[custom sw.js](https://github.com/maple3142/Blog/blob/0f19a45b4de81aea07b53328ef0d4bddc08fa625/source/sw.js)

**Comment by gauntface** [comment]
The full error:

```
Uncaught (in promise) WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"https://blog.maple3142.net/404.html","error":{"name":"invalid-response-for-caching","message":"The fetched response could not be cached due to an invalid response code."}}'
    at https://blog.maple3142.net/wb.js:160:1358
    at Generator.throw (<anonymous>)
    at step (https://blog.maple3142.net/wb.js:83:30)
    at https://blog.maple3142.net/wb.js:96:13
    at <anonymous>
```

This error is because the 404 file is returning with a status code of `404`, which Workbox is treating as an error and refusing to cache.

The best option for this is to create a file that doesn't return a 404 status code.

**Comment by maple3142** [comment]
But `404.html` is meant to be 404 page.
And my server is firebase hosting, according to [document](https://firebase.google.com/docs/hosting/url-redirects-rewrites#section-404), `404.html` will send a 404 status code.

**Comment by jeffposnick** [comment]
Given that, I don't think you should precache your `404.html` page. (The scenarios in which you'd want to display it from the service worker's cache without going to the network are pretty limited, for one thing.)

If you add `**/404.html` to your list of `globIgnores` when configuring `workbox-build`, then it should end up excluded from the list.

**Comment by gauntface** [comment]
+1 @jeffposnick's comment and if you want to cache a page for offline usage, I'd use a seperate file - this will also help you differentiate between a missing file and an offline response from your service worker (i.e. use a page `offline.html` to cache and return in case of offline or error.)
