### ISSUE TITLE
Workbox CLI should disable or exclude maps when asking about file extensions

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1239]
I just went through the default wizard steps and it defaults result in map files being added to cache list.

**Comment by jeffposnick** [comment]
Is it because you saw `.map` as one of the extensions that you could choose from in the list of possible extensions, and you checked the box for it?

If so, we could filter that out so that it's not presented as an option to choose from.

**Comment by gauntface** [comment]
Yes it was @jeffposnick - I'm happy for it to be excluded or just unselected by default.
