### ISSUE TITLE
v3 bgSync queueDidReplay fires even when queue is empty

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1247]
**Library Affected**:
*workbox-backgroundSync*

**Browser & Platform**:
*Google Chrome v63.0.3*

After creating a background sync queue:

```javascript
const bgSyncQueue = new workbox.backgroundSync.Queue(
  'dashboardr-queue',
  {
    callbacks: {
      queueDidReplay: showNotification
    }
  }
);
```

Calling `bgSyncQueue.replayRequests()` fires the `queueDidReplay` callback even if there are no queued requests to replay. I'm assuming this is not intended behaviour but if I'm wrong about that, is there a more fine-grained way of determining if queued requests were truly sent during a bg sync? 

Related issue:
#1249

**Comment by prateekbh** [comment]
@DavidScales based on this code: https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-background-sync/Queue.mjs#L134

`queueDidReplay` should be called with an Array of replayed requests.

Now for a quick fix, I guess you can look into this array if this empty or not. But it might make sense to not call this callback at all if the array is empty @philipwalton WDYT?

**Comment by philipwalton** [comment]
Yeah, it probably makes sense to only replay if there's at least one request.

**Comment by DavidScales** [comment]
@prateekbh 

Ah I see. But I'm not sure how to call `queueDidReplay` with a specific array? My expanded code is here:

```javascript
const showNotification = (myArray) => {
  console.log(myArray); // logs an empty array
  self.registration.showNotification('Background sync success!', {
    body: '🎉`🎉`🎉`'
  });
};

const bgSyncPlugin = new workbox.backgroundSync.Queue(
  'dashboardr-queue',
  {
    callbacks: {
      queueDidReplay: showNotification
    }
  }
);

const networkWithBackgroundSync = new workbox.strategies.NetworkOnly({
  plugins: [bgSyncPlugin],
});

const addEventRoute = new workbox.routing.Route(
  ({url}) => url.pathname === '/api/add',
  networkWithBackgroundSync,
  'POST'
);

workbox.routing.registerRoute(addEventRoute);

bgSyncPlugin.replayRequests();
```

and is based on the [backgroundSync guide](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync). Testing the code above logs an empty array, suggesting to me that perhaps the queued requests (the `Array of StorableRequest` in [Queue doc](https://developers.google.com/web/tools/workbox/reference-docs/prerelease/workbox.backgroundSync.Queue) that I think you are referring to) are passed implicitly?

**Comment by DavidScales** [comment]
I guess on further reflection I could see use cases either way. Before it was confusing because I wasn't able to tell when syncing was actually occurring, but with @prateekbh's pointer, I could see showing info to the user regardless of if requests were sent. E.g., if some were sent, I could notify how many were sent, and if none were sent (empty array), I could still notify that they are up-to-date with the server.

**Comment by prateekbh** [comment]
Which actually is a valid use case, is this good to close @DavidScales  @philipwalton

**Comment by DavidScales** [comment]
@prateekbh Good with me. Thanks again.
