### ISSUE TITLE
v3 what's the purpose of precaching.addRoute?

### ISSUE THREAD

**Issue by nasearle** [GoogleChrome/workbox#1253]
**Library Affected**:
*workbox-sw (v3 alpha 6)*

Just wondering in what situation we would want to use `precaching.addRoute`? It seems like everything it does is covered by `precaching.precacheAndRoute`?

Maybe I'm missing something, but it would make more sense to me if `precaching.addRoute` were more like `routing.registerRoute`, letting you set up your own caching strategy, and just went to the precache cache instead of the runtime cache.

So something like this:

```javascript
workbox.precaching.addRoute(/(.*)cdn\.ampproject\.org(.*)/,
  workbox.strategies.staleWhileRevalidate()
);
```

Would be a shortcut for this:

```javascript
workbox.routing.registerRoute(/(.*)cdn\.ampproject\.org(.*)/,
  workbox.strategies.staleWhileRevalidate({
    cacheName: workbox.core.cacheNames.precache
  })
);
```

**Comment by gauntface** [comment]
The `addRoute()` method is an "advanced feature".

Basically there may be a case where you want to precache some files but not serve them up as you'd like some control, in that case you **wouldn't** want precache to add a route.

Perhaps the naming is wrong, open to suggestions, but the idea is, for those uses, instead of `precacheAndRoute()` you'd just use `precache()`.

Why seperate them out? Well you might want to precache files, but you can only call addRoute() once. Largely to ensure developers are understanding what they are doing.

```javascript
workbox.precaching.precache(self.__precacheManifest);
workbox.precaching.precache(self.__serverPrecacheList);
workbox.precaching.precache(self.__thirdPartyPrecacheList);
workbox.precaching.addRoute();
```

Regarding going to the precache cache - that's kind of the opposite use of the precache (i.e. precaching is strict over what is kept and removed from the precache and registerRoute is basically for runtime caching - i.e. add tot he cache over time.

**Comment by nasearle** [comment]
> Basically there may be a case where you want to precache some files but not serve them up as you'd like some control, in that case you wouldn't want precache to add a route.

I guess I'm not sure what those cases are and it seems like `precaching.addRoute()` is unnecessary.

> Regarding going to the precache cache - that's kind of the opposite use of the precache (i.e. precaching is strict over what is kept and removed from the precache and registerRoute is basically for runtime caching - i.e. add tot he cache over time.

Ok, right. I was incorrectly thinking that `precaching.precache()` was the solution to our problem in thread #773: that it's like a `warmRuntimeCache` that just puts things in the precache cache instead of the runtime cache. If that were the case we could use it to precache things, but still set up our own routes and strategies to retrieve them. 

But you're saying the precache cache shouldn't be used that way? In that case are we still intended to write our own install event handler to put stuff in the runtime cache? So then from a developer's point of view why would they use `precaching.precache`?

If we're not intended to set up our own routes for the precache cache it seems like the only way forward once you've precached a file with `precaching.precache` is to call `precaching.addRoute`, which is the same as simply using `precaching.precacheAndRoute`, unless there's something I'm missing?

**Comment by gauntface** [comment]
This is largely to be flexible.

For example, a site with service worker templating - will want to cache tempalte files, but all navigations go through the service worker and precached templates are retrieved in my own route, merged together and returned to the user.

In this case I may not want precaching responding to routes/

Precaching is still seperate from #773.

We could just remove all this - stick to precache() and force developers to use lower level API. @jeffposnick would you be happy dropping "addRoute()" and being like before?

**Comment by jeffposnick** [comment]
The historical discussions behind the current implementation can be found in https://github.com/GoogleChrome/workbox/issues/700 and https://github.com/GoogleChrome/workbox/issues/747

As a developer, I'd personally always use `precacheAndRoute()`, but as Matt says, there was enough of a demand outlined in those discussions to offer flexibility. We made the decision to break things up. I don't know that we should go back on that decision at this point.

I just wanted to address one thing, though:

> For example, a site with service worker templating - will want to cache tempalte files, but all navigations go through the service worker and precached templates are retrieved in my own route, merged together and returned to the user.

In that scenario, users won't navigate to the URLs for the underlying partial templates, so I whether or not there's a route set up to handle those URLs shouldn't be relevant.

**Comment by gauntface** [comment]
@nasearle is there a better naming for this?

Basically addRoute will add a fetch listener and for each request try and see if it's in the precache cache, otherwise it'll just fallback to the router.

If you don't call addRoute or precacheAndAddRoute then the files will be precached and updated with precache, but you are responsible for using and serving the files.

**Comment by nasearle** [comment]
@gauntface the names are fine; they describe what you get and they're simple. Ok I can see the case for having a separate `precache` method that lets you do something like retrieve templates from the precache in your own routes. `precaching.precache` makes sense to me.

Still not confident about the use cases of `addRoute`, but I accept yours and @jeffposnick's responses 😉
