### ISSUE TITLE
Documentation about importWorkboxFrom

### ISSUE THREAD

**Issue by mischnic** [GoogleChrome/workbox#1264]
The documentation at https://developers.google.com/web/tools/workbox/reference-docs/prerelease/module-workbox-build#.Configuration still references the old `importWorkboxFromCDN` (changed in #1137)

**Comment by jeffposnick** [comment]
Apologies for the lack of updates on this front—https://github.com/GoogleChrome/workbox/issues/1201 will be addressed in the near future, and a change like https://github.com/GoogleChrome/workbox/compare/update-configuration-links?expand=1 will follow once that's done to point to the new configuration guide.

I'm going to close this in favor of using #1201 to track the work.
