### ISSUE TITLE
`importScripts` include duplicated entries in Webpack development

### ISSUE THREAD

**Issue by raejin** [GoogleChrome/workbox#1267]
**Library Affected**:
workbox-webpack-plugin@3.0.0-alpha.6

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
We are using Webpack dev server to serve JavaScript from a separate subdomain, as per new changes come in the dev server will re-compile and update the asset. I notice the `importScripts` statement started to include multiple precache manifest script URLs like the following:

```js
importScripts("//webpack.localhost.com/static/workbox-sw.js", "//webpack.localhost.com/static/precache-manifest.ac66c5c0aebbbfd12eeeb04b549b27f6.js", "//webpack.localhost.com/static/precache-manifest.e9a5c1bdd2a12c4a2391588f6670ea25.js", "//webpack.localhost.com/static/precache-manifest.ac66c5c0aebbbfd12eeeb04b549b27f6.js", "//webpack.localhost.com/static/precache-manifest.edc98274e5c08f4c770765983151ad0e.js", "//webpack.localhost.com/static/precache-manifest.09533f69635032c7cded7a71bba623d4.js");
```

By digging into the source, I noticed that we are pushing a new precache-manifest path to the same array on every Webpack emit:
https://github.com/GoogleChrome/workbox/blob/f2adc5664c7827a0a926f0896f808d8849583c5c/packages/workbox-webpack-plugin/src/inject-manifest.js#L101-L102

I managed to fix the problem by constructing a new array every time, as to make sure we don't mutate the plugin config:
https://github.com/raejin/workbox/commit/44b2d9cbd9ce1673818a095a555f970b334f8c80#diff-4b4d07cea6eee21561a9e810df4793bcL101

If this sounds reasonable, I'm happy to submit a PR with tests. Thanks!

**Comment by gauntface** [comment]
That PR looks great to me although I'm not 100% what this is for: `Array.prototype.push.apply(importScriptsArray, workboxSWImports);`

**Comment by jeffposnick** [comment]
Thanks for pointing this out, @raejin!

The repeated compilations use case isn't something that's been on our radar, so I wonder whether there are other areas that we would to account for in regards to resetting back to initial state.

Do you have a good way to reproduce this without fully adopting your webpack dev server setup so that we can confirm whether anything else might be amiss?

**Comment by raejin** [comment]
@gauntface Since `workboxSWImports` is an array, and I want to push the elements onto `importScriptsArray` without creating a new array, this is how I did it. I will adopt a cleaner syntax in the PR.

@jeffposnick I have created a repo just to demonstrate this bug, which it doesn't require Webpack dev server. The demo uses the Webpack watch mode. 

https://github.com/raejin/workbox-webpack-plugin-bug-demo

Let me know if you have issue running it.

**Comment by jeffposnick** [comment]
Thanks, @raejin! We're not heavy webpack users on the core team, so getting feedback from developers in the real world is very much appreciated.

I tried out your demo with a few other configuration options that might be passed to Workbox and things look good other than the `importScripts` issue.

If you're up to filing the PR to fix the issue, go for it!

**Comment by gauntface** [comment]
Thanks again for digging in to all this @raejin  :)

**Comment by raejin** [comment]
🙌 

Thank you guys for working on this awesome toolbox, which makes it so much easier for us to implement & debug the service worker piece. Will definitely keep a closer eye on undiscovered edge case if it manifests in my development cycle. 

Again, appreciate the hard work on Workbox!
