### ISSUE TITLE
Using v3 today

### ISSUE THREAD

**Issue by ciampo** [GoogleChrome/workbox#1271]
Hello,
I'm starting a new project and I'd like to use v3. Is there any place where I can find up-to-date documentation about the library and its Webpack plugin? I couldn't find any specific info on the README and couldn't understand if [these docs](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) are up to date.

**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*N/A*

**Issue or Feature Request Description**:
*Docs*

**Comment by jeffposnick** [comment]
Thanks for bearing with us as we transition our docs over.

https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin should be up to date with the current v3 alpha.

(Other webpack docs, like https://developers.google.com/web/tools/workbox/get-started/webpack, still refer to the v2 syntax.)

**Comment by gauntface** [comment]
@ciampo rule of thumb - if the top is bright orange - it's v3, if its blue - it's v2.

**Comment by ciampo** [comment]
@jeffposnick and @gauntface — thank you for the very quick response and for the effort that you put in releasing this new version (I just noticed the version bump to beta!)
