### ISSUE TITLE
Self is undefined when importing precache-manifest file

### ISSUE THREAD

**Issue by DveMac** [GoogleChrome/workbox#1277]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
When using workbox-webpack-plugin and babel with webpack. In the generated file `precache-manifest.XYZ.js` self is undefined. And so an error is throw when trying to assign to `self.__precacheManifest`

**WorkboxPlugin config**
```
    new WorkboxPlugin.InjectManifest({
        swSrc: './src/client/serviceWorker/sw.js',
    }),
```

**Console logs**

```
precache-manifest.XYZ.js:1 Uncaught ReferenceError: self is not defined
    at precache-manifest.XYZ.js:1
    at sw.js:1
(anonymous) @ precache-manifest.XYZ.js:1
(anonymous) @ sw.js:1
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

**Comment by jeffposnick** [comment]
[`self` is defined](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self) as part of the `WorkerGlobalScope`, and when used inside of a service worker (or a script imported by a service worker) it should always refer to the current global scope.

So... there's no reason that I'm aware of why `self` would be undefined when evaluated in a service worker.

I wonder whether webpack is modifying your `precache-manifest.js` file in some way that's leading to the execution context getting confused. Could you pass along a full copy of your `precache-manifest.js` file, or a copy with the manifest contents redacted if they're sensitive?

**Comment by DveMac** [comment]
@jeffposnick many thanks for your reply. 

The precache-manifest file generated by the webpack plugin seems pretty standard...

```
self.__precacheManifest = [
  {
    "url": "/app.2d28d9b3ba87d98866a1.js"
  },
  {
    "url": "/_vendor.2d28d9b3ba87d98866a1.js"
  }
];
```

and the reference injected by the plugin does too

```
importScripts("/precache-manifest.248484c1df5f586a66f6ce9f8f59fd3d.js", "https://storage.googleapis.com/workbox-cdn/releases/3.0.0-beta.0/workbox-sw.js");
```

My gut feeling too is that that webpack/babel is somehow interfering but I am at a loss as to where to look.

**Comment by DveMac** [comment]
Gah, I found the issue. Elsewhere in sw.js I had `const self = this || {}`.  Removing this fixed the issue. Apologies for a confusing issue report!
