### ISSUE TITLE
Delay precaching

### ISSUE THREAD

**Issue by merlinnot** [GoogleChrome/workbox#1283]
I have an app which loads some data through web channels. I’d like to be able to load an application shell and all relevant data before service worker starts downloading any assets, but I’d like the service worker to cache those files which are a part of the shell/current view.

My desired scenario goes as follows:
1. User requests the page
2. `index.html` is downloaded alongside with service worker (HTTP2 push)
3. Service worker is installed and activated.
4. Appliaction shell is downloaded and precached by a service worker.
5. Relevant data is downloaded via web channels/web sockets/whatever 
6. Some additional modules which should also be cached and are not critical are downloaded
7. Service worker precaching is programmatically activated so it downloads any other resources in the background.

Hope you will find my use case relevant :)

**Comment by jeffposnick** [comment]
Thanks! Closing in favor of tracking this in https://github.com/GoogleChrome/workbox/issues/155
