### ISSUE TITLE
Module Exports in Workbox Failing to Precache

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1286]
I'm still exploring the cause of this so bare with me on the amount of information (which may or may not be relevant).

SW just needs to cache a file with an export:

```javascript
export function test() {}
```

```javascript
workbox.precaching.precache([{
  url: '/module.js',
  revision: '123',
}])
```

The error printed the the console is:

> Uncaught (in promise) SyntaxError: Unexpected token export
>    at Object.<anonymous> (workbox-core:843)
>    at Generator.next (<anonymous>)
>    at step (workbox-core:14)
>    at workbox-core:25

The base of the stack trace is Babels generators.

The interesting thing here is why the contents of the file is being examined in any form during precaching.

Other side note: It seems that even that the SW fails to activate - it still caches the entries although indexedDB doesn't.

**Comment by gauntface** [comment]
Basic Repro: https://quixotic-quit.glitch.me/

**Comment by gauntface** [comment]
Bug occurs in Chrome 65 (Canary)

**Comment by gauntface** [comment]
Reduced test case outside of Workbox exposed the same behavior: https://bugs.chromium.org/p/chromium/issues/detail?id=810469 so closing this for now.

**Comment by devliber** [comment]
Same issue, from another two sources:
[Precaching modules throws error to console #1433](https://github.com/GoogleChrome/workbox/issues/1433)
