### ISSUE TITLE
Fail the Webpack build if a chunk doesn't exist

### ISSUE THREAD

**Issue by raejin** [GoogleChrome/workbox#1287]
**Library Affected**:
workbox-webpack-plugin@^3.0.0-beta.0

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
It would be problematic if we cannot track if a specified precaching Webpack chunk doesn't actually exist in the compilation. According to the source, `chunks` option is used as a whitelist to ensure the specified chunks to be considered from the compilation. 

Perhaps we can consider pushing an error to the compilation when a chunk is not found? This would make the precache-manifest more robust.

https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L166-L172

**Comment by gauntface** [comment]
@jeffposnick does this make sense? I'm 50/50. It's a whitelist and blacklist (i.e. allow these things to be included or not) but I'm not sure that it's a requirement that these things be included (at least, that's not how I think of whitelist and blacklist).

That being said, I don't know what a "chunk" is and I don't know how a chunk is formed and what the end result looks like in the config, so maybe this does make sense.

**Comment by jeffposnick** [comment]
In v5, I'll add info about any mismatch between what's provided in `chunks` and what's found in the compilation to the webpack warnings. I don't think it's worth treating it as a more serious error, though.

**Comment by jeffposnick** [comment]
This should be addressed by the current Workbox v5.0.0 alpha.
