### ISSUE TITLE
Can't pass credentials when precaching routes

### ISSUE THREAD

**Issue by mnquintana** [GoogleChrome/workbox#1288]
**Library Affected**:
workbox-precaching@3.0.0-beta.0

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
Currently `workbox.precache` isn't passing credentials along when fetching assets, which means that any requests that require, say, a valid cookie, will fail. 😢 

It looks like this is because the `PrecacheController` is explicitly passing in `null` for `fetchOptions` to the `fetchWrapper`: https://github.com/GoogleChrome/workbox/blob/08d323ef98998827c162b988c8e9fe4854cd0a0b/packages/workbox-precaching/controllers/PrecacheController.mjs#L207-L211

What I'd like to see is an API to pass `fetchOptions` down to the fetch wrapper, potentially on a per route / asset basis.

### Steps to Reproduce
1. Create a precache manifest entry pointing to an asset that can only be accessed with a cookie
1. `workbox.precache.precacheAndRoute(...)`
1. Load the page and wait for the Service Worker to activate
1. Fetching the asset will fail

Let me know if there's any more info I could provide that'd be helpful! 🙇

**Comment by jeffposnick** [comment]
Thanks for reporting this!

We hardcoded `same-origin` for precaching in the previous Workbox release (and in `sw-precache`), and it seemed to be non-controversial. Here's the v2 code:

https://github.com/GoogleChrome/workbox/blob/60d90262077c18e34240921fe0d36b876f5ca3b0/packages/workbox-precaching/src/lib/controllers/base-cache-manager.js#L28-L35

@gauntface, I'll put together a PR to add this in to v3, unless you're aware of why we wouldn't want to do this anymore.
