### ISSUE TITLE
workbox-build: broadcast update

### ISSUE THREAD

**Issue by mischnic** [GoogleChrome/workbox#1289]
**Library Affected**:
workbox-build, maybe other?

**Browser & Platform**:
Chrome 64, workbox-build@3.0.0-beta.0

**Issue or Feature Request Description**:
The documentation for `generateSW` at https://developers.google.com/web/tools/workbox/modules/workbox-build#full_generatesw_config says the option key is `broadcastUpdate`, while in reality it is `broadcastCacheUpdate`.

https://github.com/GoogleChrome/workbox/blob/50fab168140067c213f97fea58bdc0657dd60b89/packages/workbox-build/src/entry-points/options/common-generate-schema.js#L46

After that's changed, the service worker throws an error: 
`Uncaught TypeError: Cannot read property 'Plugin' of undefined`

sw.js:
```js
importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/3.0.0-beta.0/workbox-sw.js"
);

workbox.skipWaiting();
workbox.clientsClaim();

self.__precacheManifest = [...].concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.routing.registerNavigationRoute("/dist/index.html");

workbox.routing.registerRoute(/http:\/\/cors-anywhere.herokuapp.com\/http:\/\/tycho.usno.navy.mil\/cgi-bin\/time.pl/, workbox.strategies.networkFirst({ plugins: [new workbox.broadcastCacheUpdate.Plugin({"channelName":"my-update-channel"})] }), 'GET');
workbox.routing.registerRoute("https://cdn.rawgit.com/parcel-bundler/website/01a1f7dd/src/assets/parcel%403x.png", workbox.strategies.cacheFirst(), 'GET');

```

config:
```json
"runtimeCaching": [
	{
		"urlPattern": [
			"http://cors-anywhere.herokuapp.com/http://tycho.usno.navy.mil/cgi-bin/time.pl"
		],
		"handler": "networkFirst",
		"options": {
			"broadcastCacheUpdate": {
				"channelName": "my-update-channel"
			}
		}
	},
	{
		"urlPattern": "https://cdn.rawgit.com/parcel-bundler/website/01a1f7dd/src/assets/parcel%403x.png",
		"handler": "cacheFirst"
	}
]
```

**Comment by jeffposnick** [comment]
Thanks for pointing that out—we'll get that mapping updated (as well as the docs).

**Comment by jeffposnick** [comment]
(Marking this as `breaking-change` so we make sure to take note of it when documenting the v3 options.)
