### ISSUE TITLE
Safari Tech Preview - No controllerchange events.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1294]
https://planet-money.glitch.me/

This page demonstrates how we test when a service worker is activated and controlling a page. In Firefox and Chrome the red background turns green when the SW is registered and becomes the controller.

Safari Tech Preview doesn't seem to trigger controllerChange events, meaning the page stays red - refreshing the page will show its controlled and turn green.

**Comment by jeffposnick** [comment]
I'm not seeing the same issue—on Release 49 (Safari 11.2, WebKit 13606.1.3.3), I see the red background turn green for the initial visit.

And then if I do `navigator.serviceWorker.ready.then(r => r.unregister())` and reload, it turns green again. Am I testing the right way?

**Comment by gauntface** [comment]
Ooohhh interesting - I was definitely not seeing this - will need to check my version and get back to you.

**Comment by gauntface** [comment]
Just tried and it's working as expected now. I will need to test out the test bed without the changes I added to get around this to see if there are any other differences.

**Comment by gauntface** [comment]
Closing this as it worked as expected before - I must of just had something funky before.
