### ISSUE TITLE
Safari Tech Preview - IndexedDB in SW is Separate from Window IndexedDB

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1297]
1. Run `gulp serve` 
2. visiting `http://localhost:3004/test/workbox-precaching/static/precache-and-update/` 
3. in the window, open devtools and register a service worker like so:
```javascript
navigator.serviceWorker.register('/sw-1.js');
```
4. Go to `Develop > Service Workers > localhost` in the top menu and look for the **new** devtools window.
5. Copy and paste the following snippet:

```javascript
const request = indexedDB.open('workbox-precaching');
request.onerror = function(event) {
    console.log('Error opening indexedDB');
};
request.onsuccess = function(event) {
  const db = event.target.result;

  const transaction = db.transaction(['precached-details-models'], 'readwrite');
  const objectStore = transaction.objectStore('precached-details-models');
  const getAllRequest = objectStore.getAll();
  getAllRequest.onerror = function(event) {
    console.log('Error opening getting all content');
  };
  getAllRequest.onsuccess = function(event) {
     console.log(event.target.result);
  };
};
```

You should get an array of files printed, no errors.

In the origin window, copy and paste the same IDB code above into the window devtools. Notice you get errors claiming the IDBDatabase is not open. IndexedDB in the Window is separate form the SW.

**Comment by jeffposnick** [comment]
(https://cdn.rawgit.com/jeffposnick/59be4000cf048c30beb142b43aec6b67/raw/55479d6e479b4134b9f97cbba31fba5fa92a927f/index.html is a standalone repro of the underlying issue, without involving Workbox.)

**Comment by jeffposnick** [comment]
It turns out that this was due to a bug in Safari Tech Preview 49, and it should be fixed in a future release: https://bugs.webkit.org/show_bug.cgi?id=182574
