### ISSUE TITLE
v3: workbox-analytics throws error on sync 

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1309]
**Library Affected**:
*v3 beta workbox-google-analytics*

**Browser & Platform**:
*Google Chrome v64*

Hi again guys!

I'm trying trying to use the v3 beta workbox-google-analytics library for offline analytics. 

While offline, events are being stored in IndexedDB, but when returning online, I get this error:

```
Uncaught (in promise) TypeError: Failed to construct 'Request': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>)'
    at n.toRequest (workbox-background-sync.prod.js:1)
    at workbox-background-sync.prod.js:1
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at workbox-core.prod.js:1
    at <anonymous>
toRequest | @ | workbox-background-sync.prod.js:1
-- | -- | --
  | (anonymous) | @ | workbox-background-sync.prod.js:1
  | n | @ | workbox-core.prod.js:1
  | (anonymous) | @ | workbox-core.prod.js:1
```

And from the network tab it doesn't appear that the stored requests are being sent. 

Note: The IndexedDB entry is removed nonetheless. Also, if I queue up multiple events in IndexedDB, it looks like only one is removed. 

I have a [glitch demo](https://alike-pyjama.glitch.me/) with [code](https://glitch.com/edit/#!/alike-pyjama?path=sw.js:4:57). Any ideas?

**Comment by gauntface** [comment]
I've altered the demo to force debug mode and work as a web page offline and the errors quickly mount up:

https://glitch.com/edit/#!/copper-cough?path=sw.js:7:35

The full error is: 

```
workbox-background-sync.dev.js:125 Uncaught (in promise) TypeError: Failed to construct 'Request': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>)'
    at StorableRequest.toRequest (workbox-background-sync.dev.js:125)
    at workbox-background-sync.dev.js:354
    at Generator.next (<anonymous>)
    at step (workbox-core.dev.js:14)
    at workbox-core.dev.js:25
```
