### ISSUE TITLE
v3 Documentation

### ISSUE THREAD

**Issue by Vitaly-V** [GoogleChrome/workbox#1311]
There is a typo on https://developers.google.com/web/tools/workbox/modules/workbox-cache-expiration

It seems like **it** should be instead of **if** in **What is Cache Expiration?** section.

> It’s fairly common to want to put restrictions on a cache in terms of how long **if** should allow items to be stored in a cache ...

**Comment by gauntface** [comment]
Thanks for raising the issue - PR raised to fix this.
