### ISSUE TITLE
Issue with templatedUrls base route

### ISSUE THREAD

**Issue by Sakarisson** [GoogleChrome/workbox#1314]
I am not sure if this is already a feature that I have just overseen, but if not, consider this a feature request.

**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*all browsers*
*Node v8.9.4*

**Issue or Feature Request Description**:
I've been playing around with workbox in combination with Express and Pugjs.
Is it possible to use templatedUrls with catchall paths? In this case, the documents would be cached as the user accesses them. Below is an example of my current code:
```javascript
module.exports = {
  ...
  templatedUrls: {
    '/': [
      './src/views/index.pug'
    ],
    '/test/*': [
      './src/views/test.pug'
    ]
  },
  ...
  swDest: './src/sw.js',
  clientsClaim: true,
  skipWaiting: true
}

```
On the routing side, it is pretty simple for this test:
```javascript
module.exports = (app) => {
  app.get('/', (req, res) => {
    res.render('index')
  })

  app.get('/test/:value', (req, res) => {
    res.render('test', {
      value: req.params.value
    })
  })
}
```

I would love it if workbox had functionality for using routing like this.

**Comment by jeffposnick** [comment]
Based on your setup, it looks like you need to dynamically render each URL under `/test/` at runtime, serving a different HTML response for each. That makes it a bad fit for precaching via `templatedUrls`.

I'd recommend using a runtime caching strategy instead—it could be network-first, or stale-while-revalidate, depending on what kind of freshness guarantees you need.

```js
module.exports = {
  templatedUrls: {
    '/': [
      './src/views/index.pug'
    ],
  },
  runtimeCaching: [{
    urlPattern: new RegExp('^/test/'),
    handler: 'staleWhileRevalidate', // Or 'networkFirst'
  }],
  // Other config...
};
```

I'm going to close this for now, but let me know if that doesn't meet your use case and we can reopen and investigate further.
