### ISSUE TITLE
Warn/inform the user when files will be dropped due to `maximumFileSizeToCacheInBytes`

### ISSUE THREAD

**Issue by shakyShane** [GoogleChrome/workbox#1315]
This is a UX related issue. 

During development, it's often the case that files are not fully minified in order to speed up the workflow.

For example, running the `r.js` build optimizer tool on a large ecommerce Magento store can take **minutes** if `uglifyjs` is enabled.

To combat this, during development we will only *combine* assets into a single or multiple files, but will wait until the production deploy to apply the final step of optimization (which reduces the file size dramatically)

And so onto my issue, because of the following code, `workbox-build` will silently drop any files that exceed the `maximumFileSizeToCacheInBytes` - this is an extreme, unexpected occurrence.

https://github.com/GoogleChrome/workbox/blob/0d5e650147e916f8e21b43ed2e888b41391fe62a/packages/workbox-build/src/lib/filter-files.js#L86-L88

Whilst the user can configure this number, I believe we should incorporate some type of logging/warning system to indicate when & why this is happening.

**Library Affected**:
*workbox-build*

**Browser & Platform**:
Not relevant

**Issue or Feature Request Description**:
Warn/inform the user when files will be dropped due to `maximumFileSizeToCacheInBytes`

**Comment by gauntface** [comment]
I'd be done with adding a warning in `workbox-build` to highlight this: https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/lib/maximum-size-transform.js#L19

**Comment by gauntface** [comment]
@jeffposnick thoughts on this?

**Comment by jeffposnick** [comment]
Sounds reasonable, as I know that omitting files that are too large could cause trouble when you need a consistent bundle.

`workbox-build` shouldn't log anything directly. but instead return any error messages back as part of its response. That could then be displayed by `workbox-cli` or `workbox-webpack-plugin` or whatever.

(We could lump this error together with what's tracked in https://github.com/GoogleChrome/workbox/issues/1176#issuecomment-366100571, though if it's really common for glob patterns not to pick anything up, that points to what might be a deeper issue.)
