### ISSUE TITLE
Contribution guidelines should also be present in Wiki section.

### ISSUE THREAD

**Issue by mithlesh4257** [GoogleChrome/workbox#1322]
**Issue or Feature Request Description**:
Contribution guidelines should also be present in Wiki section.
This would be beneficial for newcomers to contribution. 
Also there should be explicitly written contributing guidelines.

Thanks GoogleChrome Team!

**Comment by merlinnot** [comment]
There’s already a `contributing.md` file, GitHub shows it’s presence and links it in all relevant places. I don’t think that a wiki is a good place for it.

**Comment by gauntface** [comment]
I added a short piece to the wiki: https://github.com/GoogleChrome/workbox/wiki
