### ISSUE TITLE
importScripts using Workbox + `workbox-build` can lead to broken SW

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1324]
@beatrizdemiguelperez pointed this out on the Slack channel.

If you add an `importScript` that uses the `workbox` API and `workbox-build` calls `workbox.setConfig()`, the service worker throws with `workbox-sw.js:1 Uncaught Error: Config must be set before accessing workbox.* modules ` to account for the fact that this is probably not intended.

@jeffposnick the easiest solution is to call setConfig *before* importing additional scripts.

**Comment by gauntface** [comment]
+1 to the seperate of workbox.js and using it that way.

**Comment by beatrizdemiguelperez** [comment]
Great. +1 first option. Thanks!
