### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by chrisfinazzo** [GoogleChrome/workbox#1328]
**Library Affected**:
*workbox-sw.*

**Browser & Platform**:
Google Chrome v64.0.3282.167 on macOS 10.13

**Issue or Feature Request Description**:
I am getting a syntax error when running the Workbox tutorial on Glitch. Although I see the service worker gets created, there is an exception  when I try to add caching as described in the tutorial [here][] under step 5.

    gulp.task('generate-service-worker', () => {
      return workbox.generateSW({
        ...
        runtimeCaching: [
          {
            urlPattern: new RegExp('https://hacker-news.firebaseio.com'),
            handler: 'staleWhileRevalidate'
          }
        ]
      }).then(() => {
        ...

[here]: https://developers.google.com/web/tools/workbox/get-started/gulp

Without this block, everything compiles normally, seems like something is not being terminated correctly...

The complete `gulpfile.js` is as follows:

```
const gulp = require('gulp'),
    del = require('del'),
    runSequence = require('run-sequence'),
    src = `${__dirname}/src`,
    dist = `${__dirname}/dist`;

const workbox = require('workbox-build');

gulp.task('clean', () => {
  return del(dist);
});

gulp.task('build', () => {
  gulp.src(`${src}/**/*`)
      .pipe(gulp.dest(dist));
});

gulp.task('generate-service-worker', () => {
  return workbox.generateSW({
    globDirectory: dist,
    globPatterns: ['**\/*.{html,css,js}'],
    swDest: `${dist}/sw.js`,
    clientsClaim: true,
    skipWaiting: true
  }).then(() => {
    console.info('Service worker generation completed.');
  }).catch((error) => {
    console.warn('Service worker generation failed: ' + error);
  });
});

gulp.task('default', () => {
  runSequence('clean', 'build', 'generate-service-worker');
});
```

I am not well-versed in Javascript, but wonder if this is simply a documentation error that has not been updated for v3.

**Comment by gauntface** [comment]
@chrisfinazzo thanks for raising the issue. This is very likely to be a documentation issue. 

Could you provide the actual error message and also the server worker code that is produced.

**Comment by chrisfinazzo** [comment]
```
importScripts('workbox-sw.prod.v2.1.3.js');

/**
 * DO NOT EDIT THE FILE MANIFEST ENTRY
 *
 * The method precache() does the following:
 * 1. Cache URLs in the manifest to a local cache.
 * 2. When a network request is made for any of these URLs the response
 *    will ALWAYS comes from the cache, NEVER the network.
 * 3. When the service worker changes ONLY assets with a revision change are
 *    updated, old cache entries are left as is.
 *
 * By changing the file manifest manually, your users may end up not receiving
 * new versions of files because the revision hasn't changed.
 *
 * Please use workbox-build or some other tool / approach to generate the file
 * manifest which accounts for changes to local files and update the revision
 * accordingly.
 */
const fileManifest = [
  {
    "url": "app.js",
    "revision": "d70e65002017be496979c6f63f4c595d"
  },
  {
    "url": "index.html",
    "revision": "d41d8cd98f00b204e9800998ecf8427e"
  }
];

const workboxSW = new self.WorkboxSW({
  "skipWaiting": true,
  "clientsClaim": true
});
workboxSW.precache(fileManifest);


```

<img width="594" alt="screen shot 2018-03-01 at 10 03 33 am" src="https://user-images.githubusercontent.com/1534882/36851823-36905194-1d38-11e8-9c8a-76c409941c9c.png">

Although I can see that a service worker has been generated, adding the `runtimeCaching` block to the example produces an `Unexpected token` error.

**Comment by jeffposnick** [comment]
The Workbox tutorial has been updated for Workbox v3, and I was not able to reproduce this error when testing against that. If you're still seeing issues, please let us know and I'll reopen this.
