### ISSUE TITLE
replace importScripts with inline scripts for compatibility?

### ISSUE THREAD

**Issue by thinkloop** [GoogleChrome/workbox#1331]
importScripts is not supported by many browsers: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts#Browser_compatibility

Is it possible to copy/paste the contents of the file to the top of sw.js to have a more compatible solution? If so, could/should this be a config option?

**Comment by thasmo** [comment]
Just learned that Firefox Desktop does not support `importScripts` so I'd love to see an option for inlining the workbox script.

**Comment by josephliccini** [comment]
I think in theory you could do this with the `injectManifest` option already (just copy paste `workbox-sw.prod.v2.1.2.js`) to the top of your `swSrc: `.

**Comment by jeffposnick** [comment]
`importScripts()` is supported in any browser that supports service workers.

E.g. https://workbox-samples.glitch.me/examples/workbox-sw/ loads properly in Firefox, and that example `importScripts()` Workbox via a CDN URL.

I believe that MDN is working on a new method of generating their compatibility tables, and the misinformation might be related to that.
