### ISSUE TITLE
CDN ACL issue 3.0.0.beta.1

### ISSUE THREAD

**Issue by frlinw** [GoogleChrome/workbox#1332]
https://storage.googleapis.com/workbox-cdn/releases/3.0.0-beta.1/workbox-sw.js

```
<Error>
  <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>
       Anonymous caller does not have storage.objects.get access to workbox-cdn/releases/3.0.0-beta.1/workbox-sw.js.
    </Details>
</Error>
```

**Comment by eskan** [comment]
+1

**Comment by jeffposnick** [comment]
Looking at the Google Cloud admin page for our storage buckets, it doesn't look like anything was created for `3.0.0-beta.1`.

@gauntface handled the release yesterday, but it might be that he wanted to polish up some things before making it official? I'll let Matt comment.

**Comment by gauntface** [comment]
Sorry about that.

I didn't run the follow up gulp command. Fixed now but I need to dig into the issue.

**Comment by frlinw** [comment]
Don't worry, we still love you
