### ISSUE TITLE
workbox-build: broadcastUpdate channelName

### ISSUE THREAD

**Issue by mischnic** [GoogleChrome/workbox#1334]
Again `broadcastUpdate` with workbox-build@3.0.0-beta.1: 

workbox-build wants this:
```js
"options": {
  "broadcastUpdate": {
    "channelName": "my-update-channel"
  }
}
```
(resulting in `new workbox.broadcastUpdate.Plugin({"channelName":"my-update-channel"})`)

but it should be:
```js
"options": {
  "broadcastUpdate": "my-update-channel"
}
```
(for `new workbox.broadcastUpdate.Plugin("my-update-channel")`, which actually works)

Without channelName, it doesn't get accepted: 

> Service worker generation failed: ValidationError: child "runtimeCaching" fails because ["runtimeCaching" at position 1 fails because [child "options" fails because [child "broadcastUpdate" fails because ["broadcastUpdate" must be an object]]]]

There is no `{channelName: ...}` in the test either:
https://github.com/GoogleChrome/workbox/blob/86c7ef7a8b6fe768c7fc52ba9e18aed8dee338b1/test/workbox-broadcast-cache-update/static/sw.js#L12-L14

**Comment by jeffposnick** [comment]
Thanks for catching this, @mischnic!
