### ISSUE TITLE
Typo in web guide

### ISSUE THREAD

**Issue by zamakkat** [GoogleChrome/workbox#1345]
Sorry don't know if it's the right place to file it and didn't find a repo to PR to so filing it here.

**Library Affected**:
https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
In the section `Workbox Caches Opaque Response Sometimes`, above the 2nd code block there is a reference to `stalteWhileRevalidate` which should be `staleWhileRevalidate` (an extra "t" in stale).

**Comment by jeffposnick** [comment]
Thanks! I've filed https://github.com/google/WebFundamentals/pull/5864 to address this.
