### ISSUE TITLE
Relocate/rename local `workbox` libs directory

### ISSUE THREAD

**Issue by Schlesiger** [GoogleChrome/workbox#1350]
**Library Affected**:
*workbox-webpack-plugin v3.0.0-beta.2 GenerateSW*

**Browser & Platform**:
*n/a*

**Issue or Feature Request Description**:
*Add feature: options to relocate/rename local `workbox` libs directory*

When using the option `importWorkboxFrom: 'local'`, I'd like to be able to move and rename the `workbox` libraries which copied to my build directory.

Thanks!

Edit: Trimming due to partial duplicate of #1285

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/workbox/issues/1285#issuecomment-376653175 for follow-up.
