### ISSUE TITLE
Add helper method to cleanup cache + expiration data in IDB

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1365]
**Library Affected**:
*workbox-cache-expiration*

**Issue or Feature Request Description**:
Extracting a feature request from https://github.com/GoogleChrome/workbox/issues/1354#issuecomment-373188977, @josephliccini and I write:

> One thing that I'm not sure about is how well the current workbox-cache-expiration code will behave if you do an "out of band" caches.delete() call to remove a specific runtime cache without also deleting the IDB entries corresponding to its expiration, and then later on recreate the same runtime cache. I'd imagine that it could lead to some confusion—@gauntface?
> 
> Maybe the solution there is to expose a workbox.expiration.deleteCache() method that took in a cache name and did both the Cache Storage API deletion as well as the IDB cleanup in one step.
> 
> Yes (regarding your response to 5.) this is basically how we've implemented /logout today, and the next step is to go to IDB and clear those out too. I would love a deleteCache() method that does IDB and Cache deletion for a workbox cache 👍

**Comment by gauntface** [comment]
This all sounds like a good idea to me.

**Comment by josephliccini** [comment]
This is how I achieved it: (Note I am on Workbox 2.1.3)
```js
const scope = self.registration.scope;

const cacheKeys = await self.caches.keys()
const workboxPrecachedAssetsCacheKeyRegExp = new RegExp(`^${cacheId}-workbox-precaching-revisioned`);

const runtimeCacheData = cacheKeys.filter(key => !workboxPrecachedAssetsCacheKeyRegExp.test(key));

await Promise.all(runtimeCacheData.map(cacheKey => caches.delete(cacheKey)));

const idbDeletePromises = Promise.all(runtimeCacheData.map(cacheKey => new Promise((resolve, reject) => {
	const dbKey = `workbox-cache-expiration-${scope}-${cacheKey}`;
	const request = indexedDB.deleteDatabase(dbKey);
	request.onerror = reject;
	request.onsuccess = resolve
})));

await idbDeletePromises;
```

**Comment by josephliccini** [comment]
Does workbox close connections to indexedDB?

I am having issues where my `deleteDatabase` request is continually hitting the `onblocked` callback.

The suggestions online recommend closing all open IndexedDB requests before calling `deleteDatabase`.  Is there a way we could do this today?

Thanks!

**Comment by jeffposnick** [comment]
No, Workbox deliberately keeps connections to IDB open while the SW remains running, which unfortunately necessitates the types of hacks that you put together.

The "official" method for cleaning up the IDB + cache storage pair will have to take that into account.

**Comment by josephliccini** [comment]
Thanks Jeff, looking forward to an official implementation 👍

**Comment by josephliccini** [comment]
Awesome! looking forward to hooking this up!
