### ISSUE TITLE
Add support of incremental cache

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/workbox#1371]
What about adding support of incremental cache, i.e. downloading only the delta (diff) between the old file in cache and the new file? Something like https://github.com/gmetais/sw-delta.

**Comment by jeffposnick** [comment]
I don't think there are any plans to pursue this as part of the core Workbox project at this time. I'd recommend going with a mix of any existing solutions + Workbox if you want to add that behavior into your service worker for some routes, while still using Workbox for others.

If you're interesting in writing your own custom [`handlerCallback`(https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~handlerCallback) that implemented that behavior, it should be even easier to mix in with Workbox.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
