### ISSUE TITLE
precache guide typo 

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/workbox#1374]
Slight typo on this page saying "preache"
https://developers.google.com/web/tools/workbox/guides/precache-files/

![image](https://user-images.githubusercontent.com/1892132/37548184-67034186-2933-11e8-9b19-999fa5a68323.png)

**Comment by jeffposnick** [comment]
Thanks! I filed https://github.com/google/WebFundamentals/pull/5933 to fix it.
