### ISSUE TITLE
Add support of P2P precache

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/workbox#1375]
What about adding support of P2P precache? Something like Planktos (https://xuset.github.io/planktos, https://github.com/xuset/planktos) — a WebTorrent precache service worker.

Learn more about WebTorrent here: https://webtorrent.io, https://github.com/feross/webtorrent.

It can be a separate Workbox module.

Since BitTorrent is based on [segments/pieces/chunks](https://en.wikipedia.org/wiki/BitTorrent#Description) that are typically downloaded non-sequentially and WebTorrent supports [HTTP seeding and HTTP range requests](https://github.com/webtorrent/webtorrent/issues/67), it can helps solve support of incremental cache (see #1371) problem.

**Comment by jeffposnick** [comment]
It's good to see that other folks are experimenting with what's possible in separate projects, but I think it's outside the scope of what we're going to focus on with Workbox.
