### ISSUE TITLE
Precaching cacheWrapper.put missing plugins args

### ISSUE THREAD

**Issue by djeeg** [GoogleChrome/workbox#1376]
**Library Affected**:
workbox-precaching

https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-precaching/controllers/PrecacheController.mjs#L221

Is this call missing a plugins argument?

`await cacheWrapper.put(this._cacheName, request, response);`

Should it be?

`await cacheWrapper.put(this._cacheName, request, response, plugins);`

Without the plugins arg, I cant get broadcast updates to fire 
(from here) https://github.com/GoogleChrome/workbox/issues/1073

**Comment by gauntface** [comment]
yeah this is an oversight and somewhat funky with the cache to temp directory and before the final cache, but will raise a PR so at least it's broadcast.
