### ISSUE TITLE
Guides > Generate a Complete Service Worker > Webpack link goes to 404 page because of typo in URL 

### ISSUE THREAD

**Issue by ZhangYiJiang** [GoogleChrome/workbox#1378]
This "Webpack" link right here 

![screenshot from 2018-03-19 20-11-54](https://user-images.githubusercontent.com/445650/37594934-c948c41c-2bb1-11e8-9b63-09d078f9e21d.png)

goes to a 404 page because its `href` is https://developers.google.com/web/tools/workbox/guides/generate-service-workers/webpack, whereas the correct link is https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack - there is an extra 's' in `generate-service-workers` 

Here's one of the affected pages: https://developers.google.com/web/tools/workbox/guides/generate-service-worker/

**Comment by jeffposnick** [comment]
This will be fixed in https://github.com/google/WebFundamentals/pull/5941

Thanks for pointing it out!
