### ISSUE TITLE
All  workbox-webpack-plugin code examples missing 'new' 

### ISSUE THREAD

**Issue by ZhangYiJiang** [GoogleChrome/workbox#1379]
**Library Affected**:
workbox-webpack-plugin

**Node version affected**: v8.9.4 (probably others too) 

**Issue or Feature Request Description**:

Both plugins in the package (GenerateSW and InjectManifest) are classes, which means they need to be called with `new`. All of the code examples in the docs do not use this, causing them to raise a `TypeError` exception when run 

``` 
> const { GenerateSW } = require('workbox-webpack-plugin');
undefined
> s = GenerateSW()
TypeError: Cannot call a class as a function
    at exports.default (node_modules/babel-runtime/helpers/classCallCheck.js:7:11)
    at GenerateSW (node_modules/workbox-webpack-plugin/build/generate-sw.js:76:34)
> s = new GenerateSW()
undefined
> s
GenerateSW {
  config: 
   { chunks: [],
     exclude: [ /\.map$/, /^manifest.*\.js(?:on)?$/ ],
     excludeChunks: [],
     importScripts: [],
     importWorkboxFrom: 'cdn',
     swDest: 'service-worker.js' } }
```

Pages with this issue: 

- https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack
- https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

**Comment by jeffposnick** [comment]
This will be fixed in https://github.com/google/WebFundamentals/pull/5941

Thanks for pointing it out!

**Comment by ShashankVinayak** [comment]
Hi,
Came across same issue in another page:
https://developers.google.com/web/tools/workbox/guides/precache-files/webpack

**Comment by jeffposnick** [comment]
Thanks. https://github.com/google/WebFundamentals/pull/5993
