### ISSUE TITLE
Proposal to better support query params in `workbox.routing.NavigationRoute`

### ISSUE THREAD

**Issue by raejin** [GoogleChrome/workbox#1385]
**Library Affected**:
workbox-routing

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
We found that we have to leverage the `blacklist` option to bypass service worker in a number of cases, specifically when some query strings are present. We would likely to be okay if we keep on using the regex to detect specific query strings, but am wondering if we could make this more robust by leveraging on `location` API.

This would likely change the API of the whitelist/blacklist configuration options like the following:
```js
new workbox.routing.NavigationRoute(
  handler,
  {
    whitelist: [
      /^\/$/,
    ],
    blacklist: [
      /[&?]abc=/,
      { type: 'search', key: 'abc' },
      { type: 'search', key: 'foo', match: 'bar' },
      { type: 'search', key: 'bar', match: /1234/ },
      { type: 'hash', match: '12345' },
    ],
  },
);
```

How do you folks feel about adding this support?

**Comment by jeffposnick** [comment]
Hello @raejin—The `blacklist` option currently matches against a string that consists of `url.pathname` + `url.search`:

https://github.com/GoogleChrome/workbox/blob/49f3d216fe79b2359ff88fb10ca5387dd5cb7bf4/packages/workbox-routing/NavigationRoute.mjs#L93-L101

I *think* that already gives you the behavior you're asking for, while keeping the same basic `RegExp` syntax for everything. You need to get a tad more involved with your `RegExp`, but it's nothing too bad:

```js
new workbox.routing.NavigationRoute(
  handler,
  {
    whitelist: [...],
    blacklist: [
      'foo=bar',
      'bar=\d{4}',
      // etc.
    ].map(fragment => new RegExp(`\?.*${fragment}`)),
  },
);
```

I'm going to close this issue for now, but if I'm misinterpreting your request, feel free to comment and I'll reopen.
