### ISSUE TITLE
waitUntil called on event that is already finished in NetworkFirst strategy

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1386]
**Library Affected**:
*workbox-strategies*

**Browser & Platform**:
webview with User-Agent:Mozilla/5.0 (Linux; Android 6.0.1; SM-A510F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36

**Issue or Feature Request Description**:
Reported by @beatrizdemiguelperez on Slack:

> i'm getting this error while trying to fetch a file with networkFirst strategy
> ```sh
> Uncaught (in promise) DOMException: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
>    at http://localhost:4200/workbox-v3.0.0/workbox-strategies.dev.js:510:15
>    at Generator.next (<anonymous>)
>    at step (http://localhost:4200/workbox-v3.0.0/workbox-core.dev.js:14:32)
>    at http://localhost:4200/workbox-v3.0.0/workbox-core.dev.js:25:15
> ```

**Comment by jeffposnick** [comment]
The underlying code is https://github.com/GoogleChrome/workbox/blob/49f3d216fe79b2359ff88fb10ca5387dd5cb7bf4/packages/workbox-strategies/NetworkFirst.mjs#L220-L229

There's some `setTimeout()` logic in the handler that might be leading to a race condition.

**Comment by beatrizdemiguelperez** [comment]
Also reproduced on User-Agent:Mozilla/5.0 (Linux; Android 7.1.1; SM-N950F Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

**Comment by mick-feller** [comment]
We have been noticing the same issue happening.

It's hardly impossible to reproduce but we got it on a handful of machines, what happened (or at least i think) we had some backend issue's and the service workers kicked in during this time. At that moment something is going south and i'm getting this exact same issue. I can confirm that on version 3.0.1 it was stopping the service worker all together and serving empty files. I've updated to version 3.2.0 and at least the service worker is now returning content.

All though it seems impossible to recover the service worker after this has happened unless you forcefully unregister the service worker and reinitialize it.

My caching strategy is mixed between staleWhileRevalidate, cacheFirst and preCache.

I wish i could put a case together were I could 100% replicate it but it's near impossible at this moment.

Do you have any pointers for me in how to recover the service worker after something like this happens?

Thanks
