### ISSUE TITLE
Can we have a PWA and AMP module

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1389]
Hi,

I have a website that is made up of two parts: 

Desktop = Progressive Web App (PWA)
Mobile = Accelerated Mobile Pages (AMP)

My service worker I am using Wordbox - of course! Amazing work done by you guys.

At the moment I am trying to speed up both my PWA and AMP performance in every way possible.

When a user comes to my website I want the following pages to be precached after the webpage has been loaded, these are:

1. Current Page
2. Home Page
3. Offline Page

However because I am using PWA and AMP I actually have 6 pages in total. For example:

```
https : // www .example .com / offline
https : // www .example .com / amp/ offline
```

The problem is that say a user is on a 3G regular connection and speed and data limits are an issue. Then I want the service worker to precache 3 webpages and not 6 webpages, thus saving time in useless 304  connections and extra data lookups.

So I am thinking is it possible to have two precaches where the first precache can cache the normal / desktop only webpages in the PWA site and the second precache it can cache the mobile only webpages in the AMP site.

I was thinking of just doing a simple test to see if the URL contains: `/amp` inside it or not? And having this option in the api. As most AMP websites have the word amp containing in their URL as per the spec.

I try to create an example of what I am thinking:

```
// Default set to /amp for ampUrl property.
  self.workbox.precaching.precacheAndRoute([], {
    directoryIndex: '/',
    ampUrl: '/amp'
  });

workbox.precaching.precacheAndRoute([
  {
    "url": "/home",
    "revision": "75fc52513755dc214009596aea7ebe8e"
  },
  {
    "url": "/offline",
    "revision": "6fb97d1d6ccf044b00e99850e8130058"
  }
]);

workbox.precachingAmp.precacheAndRoute([
  {
    "url": "/amp/home",
    "revision": "6354tred1d6ccf044b00e99850e81365"
  },
  {
    "url": "/amp/offline",
    "revision": "8976ujytccf044b00e99850e8g130072"
  }
]);
```

Then the amp precaching module can do the extra work of serving the precached list to the amp pages to users coming from amp webpages and developers then don't need to create the extra code to set it all up manually.

Maybe this idea is not so good but I am suggesting creating an extra part of the Workbox library to cater for people using both PWA and AMP in one website.

Thanks.

**Comment by gauntface** [comment]
I would just add an if statement to the code above:

```
let filesToPrecache = DEFAULT_FILES;
if (amp) {
  filesToPrecache = AMP_FILES;
}
workbox.precaching.precacheAndRoute(filesToPrecache);
```

Then setup the default and amp files however you wait.

The tricky bit here is get the files, which I would probably do via workbox-build's `getManifest` method: https://developers.google.com/web/tools/workbox/reference-docs/prerelease/module-workbox-build#.getManifest

**Comment by ayumihamsaki** [comment]
Thanks matt I will give it a go
