### ISSUE TITLE
Unknown Command error when using workbox-cli 2.1.2

### ISSUE THREAD

**Issue by jainAdijain** [GoogleChrome/workbox#1394]
When build my app I encountered an error as follows: 
Unknown Command: inject:manifest at _callee$ (/usr/local/lib/node_modules/workbox-cli/build/app.js:189:17)

What does this error stands for and what can be its rootcause as well as its workaround?

**Comment by jeffposnick** [comment]
That error, plus the fact that I see `app.js` in your stacktrace, very much points to the fact that you're using `workbox-cli` v3, and not v2.

If you run `workbox --help` you should see a list of valid commands for Workbox v3. In particular, `inject:manifest` is now called `injectManifest` (for consistency with the naming in the other build tools). This [migration guide](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2#workbox-cli) can also help out.
