### ISSUE TITLE
Broadcast cache updates should handle cases where the window hasn't loaded script yet

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1399]
**Library Affected**:
*workbox-broadcast-cache-updates*

In navigation requests where the service worker responds from the cache, its very likely that any `BroadcastChannel` message won't be received by the window because it'll be sent before the window has finished loading the page (and the page's script).

We could work around this issue by storing pending cache updates in IDB if we detect that `clients.matchAll()` doesn't include any clients where `type` equals `window`.

Unfortunately it's not clear when the best time to retry broadcasting those messages is, since it will most likely require communication from the window.

We've discussed the idea of a workbox module that runs on the window, and I think something that informs the Service Worker when it's ready to receive messages would be a great addition.

**Comment by piehei** [comment]
I was just thinking about implementing my own solution to this. I think communication from the window is required anyhow.

I think one of these would be nicer than to have something Workbox specific running in the window:

1. Have a flag that tells the SW to not send anything via the BroadcastChannel *before* the SW has received some sort of a confirmation "I'm ready" message from the window

2. Have a flag that tells the SW to retry the BroadcastChannel msgs until a some sort of response is received back from the window

**Comment by jeffposnick** [comment]
The nuance here is that "*the* window" is a misnomer. A single service worker instance can control multiple window clients—e.g. two different tabs with the same page loaded in each of them.

So, there are edge cases where one window client is "ready" and another client isn't, but the client that's "ready" is buried under a pile of other open tabs, while the client that the user is actually looking at isn't ready (yet).

**Comment by philipwalton** [comment]
The [Client API](https://w3c.github.io/ServiceWorker/#client) does expose the window's `visibilityState`, so we could potentially not send notifications if no clients are visible. That being said, I think it makes more sense to send them anyway and let apps decide how/when to dismiss them.

The main problem, though, occurs with normal usage of an app where the navigation request returns stale from the cache and the broadcast update sends the message before the requesting window is ready to receive it.

For navigation requests, we could solve this by only broadcasting the message if a client window exists matching the fetch event's [`clientId`](https://w3c.github.io/ServiceWorker/#fetch-event-clientid). This would avoid the issue of false positives from other tabs being open.
