### ISSUE TITLE
Cache expiration should have an option to base maxEntries on last accessed time

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1400]
**Library Affected**:
*workbox-cache-expiration*

Currently the cache expiration plugin takes a `maxEntries` option that removes old entries based on their added date. I think it'd be a nice addition to add an option to remove entires based on their "last accessed" date.

The use cases is a static assets cache where JS or CSS entries could quickly become obsolete, but image or SVG assets might have been originally added long in the past but are still currently referenced on the page.

Expiring entries based on their "last accessed" date would help provide a convenient way to auto expire assets that are no longer referenced.

**Comment by jeffposnick** [comment]
You're describing the [current documented behavior](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.expiration.Plugin):

> This plugin can be used in the Workbox API's to regularly enforce a limit on the age and / or the number of cached requests.
> Whenever a cached request is used or updated, this plugin will look at the used Cache and remove any old or extra requests.
> When using `maxAgeSeconds`, requests may be used once after expiring because the expiration clean up will not have occurred until after the cached request has been used. If the request has a "Date" header, then a light weight expiration check is performed and the request will not be used immediately.
> When using `maxEntries` the last request to be used will be the request that is removed from the Cache.

In all cases, expiration is done on a least-recently-used basis, where "used" could be a read or a write (i.e., "last accessed").

**Comment by philipwalton** [comment]
Maybe I'm missing something, but the only place the timestamp of the IDB entry is updated is in [`CacheTimestampModel.prototype.setTimestamp`](https://github.com/GoogleChrome/workbox/blob/v3.0.1/packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs#L73-L78) method. And the only place that method is called is in [`CacheExpiration.prototype.updateTimestamp`](https://github.com/GoogleChrome/workbox/blob/v3.0.1/packages/workbox-cache-expiration/CacheExpiration.mjs#L226-L234), which is only called from the plugin's [`cacheDidUpdate`](https://github.com/GoogleChrome/workbox/blob/v3.0.1/packages/workbox-cache-expiration/Plugin.mjs#L212) lifecycle method.

That means it's not called when it's used; it's only called when it's updated. This also reflects what I'm seeing in my testing.

**Comment by jeffposnick** [comment]
Oh, yikes. I could have sworn we were also calling `updateTimestamp()` in the `cachedResponseWillBeUsed` callback (which is definitely what the docs imply). Good catch.

**Comment by jeffposnick** [comment]
@prateekbh has volunteered to look into this, likely for the v5 timeframe.
