### ISSUE TITLE
setCacheNameDetails() doesn't work after the default PrecacheController is created

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1402]
**Library Affected**:
*workbox-precaching*

`workbox-precaching`'s default controller doesn't work with `workbox-core`'s `setCacheNameDetails()` method. More specifically, it doesn't work after the default `PrecacheController` has been instantiated (since the default controller stores the cache value locally rather than referencing `workbox-core`).

This usually isn't an issue when using the workbox loader because the precaching package is lazily downloaded and thus lazily instantiated. For example, the following works because the `workbox-precaching` code isn't downloaded/run, until `workbox.precaching` is referenced at the bottom:

```js
importScripts('/path/to/workbox-sw.js');

workbox.core.setCacheNameDetails({
  prefix: 'my-app',
  suffix: 'v1',
  precache: 'custom-precache-name',
  runtime: 'custom-runtime-name'
});

workbox.precaching.precache(...);
```

But if you're using a bundler to build your service worker code, the precaching package is executed immediately, and that code instantiates the default `PrecacheController` with the default cache name before `setCacheNameDetails()` can be called.

There are a few ways to fix this, but I'd argue (and have before) that we shouldn't be instantiating custom objects outside of a method call or in response to an event. The default `PrecacheController` could be instantiated lazily the first time any of the precaching methods were called.

**Comment by jeffposnick** [comment]
After talking to @philipwalton, I believe this can be closed. In v4, the default `PrecacheController` is instantiated lazily when it's first used, not when it's loaded:

https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-precaching/precache.mjs#L38
