### ISSUE TITLE
Large number of precache requests crashes Chrome on Android

### ISSUE THREAD

**Issue by rjsteinert** [GoogleChrome/workbox#1404]
**Library Affected**:
workbox.precaching.precacheAndRoute

**Browser & Platform**:
Google Chrome v65 for Android, Google Pixel 2 and Lenovo Tab 4 for hardware

**Issue or Feature Request Description**:
Large number of precache requests crashes Chrome on Android. Example: https://tusome-lesson-plans.tangerinecentral.org/

**Comment by rjsteinert** [comment]
How might we precache and register route one by one? I was thinking that `workbox.precaching.precacheAndRoute` might return a promise that resolves when precaching finishes but I see it returns undefined.

**Comment by rjsteinert** [comment]
I'm working on a deployment of 1400 tablets in Kenya to go out into the field on Wednesday. For now our strategy is going to be to release the files onto the server as 100 file batches, generate SW again and then reload the app on each of the 1400 tablets. If we could release all 900 (soon to be 1400) files and code it up to batch for us, that would save us a bunch of time.

**Comment by jeffposnick** [comment]
Apologies that you ran into that issue—if you could provide details at https://new.crbug.com/, including any details about the crash itself (see https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug) that would be the best way to address this.

From what you describe, it sounds like an issue with Chrome on Android not handling cache operations gracefully when under storage and/or memory pressure, and that might be outside of Workbox's control.

**Comment by rjsteinert** [comment]
@jeffposnick Agreed, it would be great if Chrome on Android gracefully handled a large number of requests for caching. Until then, when it comes to a large number of operations we need to batch things but I understand that can be hard to find the right balance between performance and stability of the system.
