### ISSUE TITLE
removes Origin header in cross-origin requests 

### ISSUE THREAD

**Issue by nikugogoi** [GoogleChrome/workbox#1406]
**Library Affected**:
workbox

**Browser & Platform**:
Google Chrome v63.0.3239.84

**Issue Description**:
workbox removes request header Origin in cross domain requests. This behaviour is seen only in the Chrome browser. Mozilla firefox doesnt have this issue. The moment I import Workbox in my /sw.js file the Origin header is removed. This results in missing Access-Control-Allow-Origin header in the response headers and so I have a CORS issue

*Sorry for not being able to reproduce the issue*

**Comment by nikugogoi** [comment]
the problem is with a module I am using

**Comment by nikugogoi** [comment]
in all other versions of chrome its working fine

**Comment by anativ** [comment]
I checked it on Chrome version 64.0.3282.186
The name of the origin header was changed to "Origin" was "origin" this made a bug in many web frameworks that checked something like "Headers.origin"
I re-checked this on chrome 67.0.3396.99 and it seems to be back to normal "origin"

**Comment by jeffposnick** [comment]
Since this appears to be an issue triggered by behavior in specific, older versions of Chrome, rather than Workbox, I'm going to close this.
