### ISSUE TITLE
Link to TypeScript definitions for workbox-sw

### ISSUE THREAD

**Issue by matthew-a-thomas** [GoogleChrome/workbox#1410]
**Library Affected**:
workbox-sw

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Please add TypeScript support. 😃

https://github.com/GoogleChrome/workbox/issues/217 ended with [this](https://github.com/GoogleChrome/workbox/issues/217#issuecomment-306899129):
> Gonna close this until someone requests it.

So perhaps this can be the "official" request.

**Comment by jeffposnick** [comment]
Apologies, but we've come to the conclusion at https://github.com/GoogleChrome/workbox/pull/1436#issuecomment-396678604 that we're not going to host first-party definitions in this repo (at least not at this time).

**Comment by matthew-a-thomas** [comment]
> Apologies

> stale typings seem inevitable as we make changes to the codebase

@jeffposnick No worries. I understand the reasoning. I'll keep an eye out for `@types/workbox-sw`.

**Comment by wessberg** [comment]
The typings have been published:
https://www.npmjs.com/package/@types/workbox-sw

**Comment by jeffposnick** [comment]
Thanks! I'll re-open this issue to track linking to them.

**Comment by Manc** [comment]
> @matthew-a-thomas
> The typings have been published:
> https://www.npmjs.com/package/@types/workbox-sw

Hi @wessberg,
It's quite possible that I'm getting something wrong here. I installed `@types/workbox-sw`, but don't have a clue how to use it. I added it to my `tsconfig.json`:

```
{
	"compilerOptions": {
		/* … */
		"types": [
			"workbox-sw"
		]
	},
	/* … */
}
```

Then in my `serviceworker.ts`:
```
declare var self: ServiceWorkerGlobalScope;
export default null;

workbox.whatever... // [ts] Cannot find name 'workbox'.
```

I also tried stuff like this:
```
import WorkboxNamespace from 'workbox-sw';
declare var workbox: WorkboxNamespace;
```

I am expecting to get the workbox variable defined. I'm having doubts now if this is even the purpose of `@types/workbox-sw`.

Sorry for being more or less off topic with my question, but it might help others too... Thanks for understanding and any hints that might help me get this working!

**Comment by Manc** [comment]
@wessberg Thank you so much! I must admit, I have never seen a declaration like this (`declare const workbox: typeof import("workbox-sw").default`) before. It works perfectly.

**Comment by nick-lvov-dev** [comment]
I was getting this error when trying to use the `declare` solution:
![image](https://user-images.githubusercontent.com/15242942/130578269-dec09403-6dc5-4641-b222-a91a3b64602d.png)

Solved it like this:
![image](https://user-images.githubusercontent.com/15242942/130578307-2308727a-22b1-4bb8-85bc-e1da0ec89f28.png)
