### ISSUE TITLE
Add config to change prechache-manifest location

### ISSUE THREAD

**Issue by mazipan** [GoogleChrome/workbox#1411]
In v.3 when using `workbox-webpack-plugin` we will get generated file called `prechache-manifest`.
But there is no way to change it's location since it's always produce in root folder directory in webpack output.

There is some case that we need to change the location like to `dist/static` or `dist/cdn` folder in webpack output.

If this change is possible, we also need to change location where `importScripts` generated to be inline with this config.

**Comment by jeffposnick** [comment]
That was added in https://github.com/GoogleChrome/workbox/pull/1403 and should be exposed in the next Workbox release.

**Comment by DerekPixieset** [comment]
@jeffposnick 

Any idea when that next release should be happening? I too require the `importsDirectory` command before I can deploy my current project.

Cheers,
Derek
