### ISSUE TITLE
Check HTTP serving setup on CDN copies

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1412]
**Library Affected**:
all

@cramforce brought up [on Twitter](https://twitter.com/cramforce/status/980545224354119680):

> Hey, the workbox "CDN" URLs like https://storage.googleapis.com/workbox-cdn/releases/3.0.0-beta.0/workbox-core.prod.js … use short caching and have gzip/brotli turned off. Any chance you could fix that?

https://stackoverflow.com/questions/40895706/enabling-gzip-on-google-cloud-storage-static-files has some background info, but I'm a little confused, as it sounds like the source files need to be uploaded `gzip`-ed to allow them to be compressed by the web serving environment?

The `Cache-Control` stuff seems to be covered by https://cloud.google.com/storage/docs/metadata#cache-control

CC: @gauntface

**Comment by jeffposnick** [comment]
After chatting with some Google Cloud storage folks, there are a few wrinkles here:

Getting the behavior we want regarding `gzip` compression is apparently much more straightforward when using the `gsutil cp -z` CLI tool for doing the upload, instead of the `node` library for interacting with the Google Cloud Storage API (which we currently use).

There's an outstanding issue that apparently can prevent `gzip` from being used when the `Cache-Control` header is also set via `gsutil`: https://github.com/GoogleCloudPlatform/gsutil/issues/480#issuecomment-367184606

**Comment by gauntface** [comment]
We can fallback to the command line tool if you want - just need to ensure whoever is publishing has it installed (i.e. catch the error and show a helpful warning)
