### ISSUE TITLE
manifestTransforms documentation and/or implemetation is incorrect

### ISSUE THREAD

**Issue by nazar-pc** [GoogleChrome/workbox#1413]
**Library Affected**:
workbox-build

**Issue Description**:
Examples on [this page](https://developers.google.com/web/tools/workbox/modules/workbox-build) and even [this one](https://developers.google.com/web/tools/workbox/reference-docs/v3.0.0-alpha.3/module-workbox-build.html#.ManifestTransform) are like following:
```javascript
manifestTransforms: [
  // Basic transformation to remove a certain URL:
  (entries) => entries.filter((entry) => entry.url !== 'ignored.html')
]
```

However, this will fail with `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined` because it actually expects an object to be returned:
https://github.com/GoogleChrome/workbox/blob/07bef201ff65c886b2d989473ef5c04447368ba7/packages/workbox-build/src/lib/filter-files.js#L110-L114

**Comment by jeffposnick** [comment]
https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestTransform has since been updated to include the correct return value.

I'll file a PR against the documentation repo to resolve the other incorrect example.

Thanks!
