### ISSUE TITLE
cacheFirst appears to fetch when the response is already cached

### ISSUE THREAD

**Issue by rps** [GoogleChrome/workbox#1414]
I've been examining the Network calls for an app using Workbox Service Workers with Webpack to cache static images. After activating the SW and visiting the page, I can confirm that the cache is created and the assets are in the cache. However, when revisiting the page, the network tab shows two calls for the image: an image returned from the SW (expected) and a fetch event from the disk cache originating from Workbox (and suggesting that the SW is making a request, which it shouldn't be).

- What is the second unexpected fetch event and why is it being used in a cacheFirst strategy? I would expect just to see a single event for the image being returned from the SW.
- If I remove the expiration constraints, this issue is resolved. Why is that?

Sample code below. Thanks!

Webpack config:
```
            new GenerateSW({
                skipWaiting: true,
                clientsClaim: true,
                include: [],
                runtimeCaching: [
                    {
                        urlPattern: /^https:\/\/.*\.cloudfront\.net\/.*/,
                        handler: 'cacheFirst',
                        options: {
                            cacheName: 'cloudfront',
                            cacheableResponse: {
                                statuses: [0, 200],
                            },
                            expiration: {
                                maxEntries: 100,
                                maxAgeSeconds: 600,
                            },
                        },
                    },
                ],
            }),
```

Generated:
```
workbox.routing.registerRoute(/^https:\/\/.*\.cloudfront\.net\/.*/, workbox.strategies.cacheFirst({
    cacheName: "cloudfront",
    plugins: [new workbox.cacheableResponse.Plugin({
        "statuses": [0, 200]
    }), new workbox.expiration.Plugin({
        "maxEntries": 100,
        "maxAgeSeconds": 600
    })]
}), 'GET');
```

**Comment by jeffposnick** [comment]
This should have been fixed by #1422, which was deployed as part of the [`3.1.0` release](https://github.com/GoogleChrome/workbox/releases/tag/v3.1.0).

Please reopen if you're still having trouble after upgrading to `3.1.0`!
