### ISSUE TITLE
Typing mistake in the home page of the Workbox website

### ISSUE THREAD

**Issue by hugodichon** [GoogleChrome/workbox#1417]
**Library Affected**:
*None*

**Browser & Platform**:
*All browsers and platforms*

**Issue or Feature Request Description**:
*You can find the problem here https://developers.google.com/web/tools/workbox/.
The very critical issue here is to fix a typing mistake by adding a **r** in **stoage** in the sentence:*

> Images carry most of the weight for a web page. Use this rule to serve them quickly from the cache, while making sure you don’t cache them indefinitely, consuming your users' **stoage**.

*The correct sentence should be*

> Images carry most of the weight for a web page. Use this rule to serve them quickly from the cache, while making sure you don’t cache them indefinitely, consuming your users' storage.

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
Thanks! This is fixed by https://github.com/google/WebFundamentals/pull/6024
