### ISSUE TITLE
templatedUrls option fails if no globDirectory provided

### ISSUE THREAD

**Issue by piehei** [GoogleChrome/workbox#1418]
**Library Affected**:
*webpack-plugin-workbox*

```
new InjectManifestPlugin({
  ...
  ...
  templatedUrls: {
    "/": [ "index.html" ]
  }
})
```

If globDirectory is not provided this fails. Based on the error messages and a brief look at the code, getFileDetails function fails since globDirectory is undefined which then fails the templatedUrls implementation function itself. I don't have my work computer right now but I will provide logs if needed.

From the documentation it is not clear that globDirectory must be provided if templatedUrls is used since they both are optional. In my opinion the documentation should be updated but the functionality could be left as is.

**Comment by jeffposnick** [comment]
Closing, as Workbox v5 changed the interface so that `templatedUrls` is no longer an option in `workbox-webpack-plugin`. Instead, `manifestTransforms` or `additionalManifestEntries` can be used.

**Comment by dahousecat** [comment]
How can we use manifestTransforms for caching app shell in a Vue PWA with Server-Side rendering? Are there any examples?

**Comment by jeffposnick** [comment]
There's an example at https://github.com/GoogleChrome/workbox/issues/2398#issuecomment-597476208 if that helps.
