### ISSUE TITLE
Caching issue with service worker

### ISSUE THREAD

**Issue by gregpmillr** [GoogleChrome/workbox#1419]
Using webpack workbox plugin with React.

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
Browsers which have old cached files are not detecting changes in the service worker when updated or deleted. When cache is cleared, everything reloads and the site is back to functioning properly. However browsers holding old cached files, as shown below in chrome dev tools, aren't picking up any new changes made, and are keeping old files (index.html shown below is not what it should be)

![image](https://user-images.githubusercontent.com/14235977/38433898-e8555998-39a2-11e8-824e-2af72d70e87f.png)

Here are the requests on refresh:
![image](https://user-images.githubusercontent.com/14235977/38433363-eb8a04c6-39a0-11e8-8191-209a6ed1513d.png)

I could clear cache / unregister the service worker and everything works fine, however, I'd prefer not to email users to do this. I have since gotten rid of the service worker since I obviously need to research more about how they work, a blunder on my behalf. 

I've also tried to include a script in index.js to unregister the service workers, as well as the cached files, however, the older cached browsers don't pick up this change.

I'm not sure if this is relevant to this issue, however if it helps at all: before this I was working on a cache busting issue which I've since fixed using [name].[chunkhash].js in webpack.config.js as the output filename.

Below is the javascript console log, which is expected I believe since the js file is sending back starting with "<".
![image](https://user-images.githubusercontent.com/14235977/38433772-8c9fd9f2-39a2-11e8-9fb8-56930281ab80.png)

Are there any suggestions for this? And if there's any other useful info I can provide to help solve this issue, please let me know.

**Comment by jeffposnick** [comment]
This info [describing Workbox's precaching behavior](https://developers.google.com/web/tools/workbox/modules/workbox-precaching), as well as this [general info on the service worker update flow](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates) might help answer some of your questions.

Using service worker precaching to handle navigation requests isn't always going to give you the freshness guarantees you might want, but it does [allow for better, network-independent loading performance](https://developers.google.com/web/fundamentals/primers/service-workers/high-performance-loading).

There's some [general guidance](https://stackoverflow.com/a/38980776/385997) about implementing a service worker "kill switch", if you want to opt-out of using them after you've already deployed them.

Given those links with follow-up material, I'm curious whether there are any outstanding questions that need to be tracked in this GitHub issue. If not, we'll close the issue.

**Comment by gregpmillr** [comment]
This was an implementation error on my part. It looks like giving 0 maximum age would've fixed the issue if I had it from the start, along with the no-op SW...   I'll look into those resources @jeffposnick and take your suggestions @piehei. I will also post these types of questions on SO from now on. Thanks for all of the resources guys! Greatly appreciated.
