### ISSUE TITLE
WorkboxSW Precache doesn't allow for 'waiting' worker's precached assets to be used

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#1421]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*"all browers"*

**Issue or Feature Request Description**:
If we take a look here: https://github.com/GoogleChrome/workbox/blob/5b97922f3d4e06561097f02870f20693b79ee738/packages/workbox-sw/src/lib/workbox-sw.js#L314-L349

You can see the `precache` default `'fetch'` listener only will try to respond with URLs that are precached _for this worker_.

Shouldn't it be safe to let the `'fetch'` listener for assets reply with _any_ assets in the cache (i.e. if there is a worker in waiting that installed assets, should not those too be available to the client?) I say this because we are not a full PWA, and our HTML will not be cached (yet!).

We may do proactive updates to our SW to cause an installation of new assets to kick off in the background, but that new worker may not become active until the exit all tabs.  I think it would be safe to let an active worker reply with assets from workers in 'waiting', no?

I can probably use `PrecacheController` for this, or register my own `'fetch'` event listener for assets which would take care of it but is there any reason why the files that are valid to reply to asset requests have to be a part of the current worker?

Thanks!
Joe

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by josephliccini** [comment]
Basically I resolved this like this:
```js
const workboxPrecachedAssetsCacheKey = `${cacheId}-workbox-precaching-revisioned-v1-${scope}`;

// This is a mechanism to load assets that are precached from 'waiting' workers.
// Discussion here: 
workboxSW.router.registerRoute(/\.(css|js|svg|png|jpg|ico)$/, {
    handle: async ({ event }) => {
        const assetCache = await self.caches.open(workboxPrecachedAssetsCacheKey);
        return await assetCache.match(event.request) || workboxSW.strategies.networkOnly().handle({ event });
    }
});
```

**Comment by piehei** [comment]
I think the reasoning for not letting the SW return the newly cached assets from the waiting state SW is that if the new installation fails for some reason your app might end up using with different versions of assets.

It might happen that the page would get 1.js V1 and 1.css V2 and if they're not compatible the app is broken. "Broken" of course depends on the app, not the same for every app.

So it's all or nothing.

**Comment by josephliccini** [comment]
Got it! Thanks for the explanation.

I think in our case since we version the file path / file name it should be OK but in cases of unversioned filenames that makes sense
