### ISSUE TITLE
Prevent duplicate requests in the backgroundSync queue

### ISSUE THREAD

**Issue by kyro38** [GoogleChrome/workbox#1424]
**Feature Request Description**:
In a context where multiple PUT requests whould be enqueued (concerning the same ressource), it would be great to allow the newest request to "override" the previous one in order to prevent multiple "useless" PUT requests to be called (useless as PUT is idempotent) . 

Any thoughts on that ?

**Comment by jeffposnick** [comment]
CC: @philipwalton for thoughts.

**Comment by philipwalton** [comment]
Hmmm, I'm not sure this is something that workbox-background-sync should handle. @kyro38  Keep in mind that any feature we add to this library requires code that gets downloaded by everyone else who uses it.

I think it makes more sense to provide a clean way for developers to be able to hook into and control which/how requests get replayed (related: https://github.com/GoogleChrome/workbox/issues/1502).

As for the PUT case in particular:

- Doesn't your server already need to be able to handle duplicate PUT requests without erroring?
- As far as I know PUT is *supposed* to be idempotent (if following REST best practices), but that doesn't mean it's always going to be that way in practice.

**Comment by philipwalton** [comment]
FYI, I'm submitted #1710, which I believe will better address your issue. Please take a look at that PR and let me know what you think.

**Comment by jeffposnick** [comment]
Closing now that #1710 is part of Workbox v4.
