### ISSUE TITLE
InjectManifest is missing ignoreUrlParametersMatching option

### ISSUE THREAD

**Issue by piehei** [GoogleChrome/workbox#1426]
**Library Affected**:
*workbox-plugin-webpack*

The InjectManifest version of the workbox-plugin-webpack doesn't implement ignoreUrlParametersMatching.

Since it's left out from documentation I guess this has been an aware decision. If so, why? Is there some technical reason to not include that option into the InjectManifest version of the plugin?

I would really like to have it – InjectManifest gives more power to the developer over GenerateSW and this is a feature I think most PWAs will anyhow need. There doesn't seem to be a nicer way to handle for instance **start_url: /?home=1** scenarios, or is there?

Thanks!

UPDATE:

I've now understood that I can do this in my hand-written SW.js:

```
    workbox.precaching.precacheAndRoute(self.__precacheManifest,
      {
        ignoreUrlParametersMatching: [/^home/]
      });
```
This now achieves the functionality I was looking for. This, now as I think about it, also makes more sense: my code is calling the precaching and providing the list of cacheable resources -> it should be at that point when the configuration happens.

In my opinion this should be closed but I'll leave that to maintainers if they see something more to do here.

**Comment by jeffposnick** [comment]
(Some more context: https://twitter.com/jeffposnick/status/1016726121596030978)
