### ISSUE TITLE
Webpack doesn't rebuild when using InjectManifest with a custom service worker

### ISSUE THREAD

**Issue by green-arrow** [GoogleChrome/workbox#1428]
When using the `workbox-webpack-plugin` with `InjectManifest` and a custom service worker, the built version (with `importScripts`) is only created on the initial build. Making changes to the custom service worker source doesn't seem to trigger a rebuild.

When modifying other application files that are used to build `bundle` or `chunk`, the service worker is rebuilt correctly. The only issue is no rebuild when changing `swSrc`.

**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Webpack

**Issue or Feature Request Description**:
When modifying a custom service worker used in `InjectManifest`, changes to the custom service worker should cause a rebuild.

```js
  const workboxConfig = {
    swDest: 'service-worker.js',
    swSrc: './src/service-worker/sw.js',
    exclude: [/\.map$/, /^(?:asset-)manifest.*\.js(?:on)?$/],
  };
```

FWIW, I'm using `create-react-app` with `react-app-rewired`. Since the initial build works but never rebuilds, I thought the issue might be with the `workbox-webpack-plugin`.

Please let me know if there's any additional information I can provide to help with this.

**Comment by raejin** [comment]
Webpack is not watching the customized service worker script, but if you make changes to a file that Webpack is watching, then the change will be reflected.

It is probably possible to force triggering a rebuild when the customized service worker script changes.
