### ISSUE TITLE
Safari integration tests unhappy

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1429]
**Library Affected**:
all

**Browser & Platform**:
Safari TP Release 53 (Safari 11.2, WebKit 13606.1.11.2)

All of the `gulp test-integration` tests are currently failing for Safari when run against the `prod` bundles, with an error like:

```sh
1) [workbox-background-sync] Load and use Background Sync
       should load a page with service worker:
     Error: the string "Regstration is not installing" was thrown, throw an Error :)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

The same tests run against the `dev` bundles complete successfully.

That originates from https://github.com/GoogleChrome/workbox/blob/685e81673d5c190209137dcaf6871f9fd5d98ce5/infra/testing/activate-sw-safari.js#L3-L8

**Comment by jeffposnick** [comment]
Now, in Safari 11.1.1 (13605.2.8), `caches.keys()` runn from the `window` context by WebDriver always resolves with an empty array for me. That's causing issues in both our tests that check for cache contents, and more problematically, code like

https://github.com/GoogleChrome/workbox/blob/a1e3c3164dad50d0c5f48e20b3ba5dfddebd549b/infra/testing/clean-sw.js#L3-L7

which is used to clean up in between test cases. I'm assuming we're going to have to start doing something like https://github.com/GoogleChrome/workbox/tree/master/test/workbox-precaching/utils globally, where there's a Safari-specific version of everything that checks the Cache  Storage API which calls `postMessage()` to the service worker to get results.

(I'm currently not clear as to what might have changed in Safari that led to this, and when doing some manual tests in the JS console from the `window` context, I do see the expected cache names when `caches.keys()` resolves. It seems like something about WebDriver is triggering the issue for me.)

**Comment by jeffposnick** [comment]
My current thinking is that since we now have multiple instances where Safari is unhappy when performing operations from the `window` context instead of the `ServiceWorkerGlobalScope`, maybe standardizing on https://github.com/GoogleChromeLabs/comlink and using that consistently across all out of browsers would end up being cleaner.

The alternative right now seems to be creating more conditional code that runs differently on Safari vs. all the other browsers, and which would have to rely on a huge `message` handler with a `switch` statement to handle all the possible things we need the service worker to do.

**Comment by philipwalton** [comment]
Yeah, I think standardizing how we do this would be good. And if comlink can make it easier to understand what's going on in the tests, that'd be an added bonus.

I'm already doing a one-off version of this in the worbox-google-analytics tests by [writing a function to message the service worker](https://github.com/GoogleChrome/workbox/blob/07bef201ff65c886b2d989473ef5c04447368ba7/test/workbox-google-analytics/integration/basic-example.js#L14-L28) and then [writing a big switch statement in the service worker](https://github.com/GoogleChrome/workbox/blob/07bef201ff65c886b2d989473ef5c04447368ba7/test/workbox-google-analytics/static/basic-example/sw.js#L29-L58) to receive those messages.

It'd be great to define how we do this everywhere.

**Comment by jeffposnick** [comment]
Comlink looks viable with an approach like https://github.com/GoogleChromeLabs/comlink/issues/27#issuecomment-397675428

It's going to be a fairly large PR to rewrite our tests to use it, but given the current failures in Safari, I think that's unavoidable.
