### ISSUE TITLE
ValidationError: "importsDirectory" is not a supported parameter

### ISSUE THREAD

**Issue by nazar-pc** [GoogleChrome/workbox#1431]
**Library Affected**:
workbox-build

I was a bit excited that 3.1.0 introduced new option and tweaked my gulp task to look like this:
```javascript
  .task('generate-service-worker', function(){
    return workboxBuild.generateSW({
      cacheId: 'detox-chat-app',
      clientsClaim: true,
      globDirectory: '.',
      globPatterns: ['dist/*', 'index.html'],
      ignoreUrlParametersMatching: [/./],
      importWorkboxFrom: 'local',
      importsDirectory: 'dist',
      skipWaiting: true,
      swDest: 'sw.js',
      manifestTransforms: [function(entries){
        var i$, len$, entry;
        for (i$ = 0, len$ = entries.length; i$ < len$; ++i$) {
          entry = entries[i$];
          entry.revision = entry.revision.substr(0, 5);
          if (entry.url !== 'index.html') {
            entry.url += '?' + entry.revision;
          }
        }
        return {
          manifest: entries
        };
      }]
    });
  })
```

Unfotrunately, I'm getting error `ValidationError: "importsDirectory" is not a supported parameter`.

Am I missing something here? My goal is to have service worker file in `sw.js` and workbox's stuff under `dist/workbox-vx.y.z`. Currently I'm manually moving files around and changing sources with regular expressions and would really like to see an option for that.

**Comment by nazar-pc** [comment]
I somehow missed the `webpack` part of the changelog. Yes, it would definitely be useful for mentioned use case too.

**Comment by jeffposnick** [comment]
The plan for `generateSW` in Workbox v5 is to move away from using the per-module Workbox runtime bundles (either locally or via the CDN) and instead use Rollup under the hood to produce a custom bundle that contains exactly the Workbox runtime code you need for your given configuration. More details are at https://github.com/GoogleChrome/workbox/issues/2064

Given that, I don't believe we're going to move forward on this feature request.
