### ISSUE TITLE
NetworkFirst caches empty with Apache2 but OK with node.js 

### ISSUE THREAD

**Issue by Antoinebr** [GoogleChrome/workbox#1434]
I deployed a serviceworker created with workbox that's working on local and on production.

But the Network first caches are always empty on production, even is the pages got responses from the serviceWorker.

It's a big issue for me because I have to show the available offline pages when the users try to see a page not in the cache.

```JavaScript 

importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.0.1/workbox-sw.js");

workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);
workbox.core.setLogLevel(1);
workbox.skipWaiting();
workbox.clientsClaim();


self.__precacheManifest = [
  {
    "url": "/bug/stylesheets/style.css",
    "revision": "e348111mmlsitrezgmdppp72ss88067d"
  },
  {
    "url": "/bug/offline/",
    "revision": "e348111llmpouitrezgmdppp72ss88067d"
  }
].concat(self.__precacheManifest || []);

//workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.routing.registerRoute(/(https:\/\/fonts.googleapis.com)/, workbox.strategies.staleWhileRevalidate(), 'GET');


var networkFirstHandler = workbox.strategies.networkFirst({
  cacheName: 'articles-antoine',
  plugins: [
    new workbox.expiration.Plugin({
      maxEntries: 30
    }),
    new workbox.cacheableResponse.Plugin({
      statuses: [0,200]
    }),


  ]

});

const handler = (args) => networkFirstHandler.handle(args).then((response) => (!response) ? caches.match('/offline/') : response);

workbox.routing.registerRoute(/\/articles\//, handler);

 ```

## Reproduce the issue : 

* Go on : https://monbraceletnato.fr/bug/articles/?id=ddssd & https://monbraceletnato.fr/bug/articles/?id=ddssddLLL ( the files will be available offline, but the cache will remain empty )

* With Node.js it's working : https://racooon.herokuapp.com/article/dds 

## Infos 

* The serviceworker is here : https://monbraceletnato.fr/bug/serviceworker.js

Thank you a lot for your help 👍

**Comment by Antoinebr** [comment]
The code runs on a WordPress directory which runs a plugin which add .htacess rules

By removing this rule everything worked as expected 

    <IfModule mod_headers.c>
    
     Header append Vary User-Agent env=!dont-vary
    
    </IfModule>

**Comment by jeffposnick** [comment]
I think it might be possible to work around this sort of thing by explicitly including `ignoreVary` when performing the cache matches: https://developers.google.com/web/updates/2016/09/cache-query-options#ignoremethod_and_ignorevary

But... it's a bit of an edge case, and it's not clear that using `ignoreVary` would actually be a safe thing to do, so I think it's left up to each developer to figure out whether just removing the `Vary` headers completely, or using `ignoreVary`, makes more sense.
