### ISSUE TITLE
How to force a cache update of one file

### ISSUE THREAD

**Issue by laurentdebricon** [GoogleChrome/workbox#1438]
Hello,
i would like to force a cache update of one file who is in the workboxSW.precache. It seems there is no easy solution.

Do I have to send a request with something like "?forceUpdate" , then in the 
workboxSW.router.setDefaultHandler detect the string "?forceUpdate" and bypass any cache then update the cache ?

Does someone have something easier ?

Best regards

**Comment by jeffposnick** [comment]
The [idea](https://developers.google.com/web/tools/workbox/guides/precache-files/) behind precaching is that the precache manifest, which should be [generated whenever your build/deploy your site](https://developers.google.com/web/tools/workbox/guides/precache-files/#generating_a_precache_manifest), determines if and when a given cached asset should be updated.

If you have assets that need to be cached but need to be updated outside of your site's build/deploy cycle, your best bet is to [set up a route](https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy) that matches requests for that asset, and apply a runtime caching strategy like stale-while-revalidate (or network first, depending on the freshness guarantees you need).

**Comment by laurentdebricon** [comment]
Hello, 
thank you,
then i have to trigger manually the asset just after the service worker is set up ? like a jquery call ?

if ('serviceWorker' in navigator) {
	window.addEventListener('load', function() {
		navigator.serviceWorker.register('/sw.js', {
			scope: "/"
		});


		$.ajax({
		  url:"/myImportantAsset",
		  type:'get',
		  success: function(data){
		  // i don't need it yet, for later
		  }
		});

	});
}

with 

clientsClaim: true,
skipWaiting: true,


Best regards,
Laurent

**Comment by jeffposnick** [comment]
If your `/myImportantAsset` URL is included in the precache manifest generated at build time (which if what you suggested in the original post), then you don't need to explicitly do anything with `$.ajax()` or whatnot. It will be automatically updated "in the background" whenever you build and then deploy your site.

(If you're not seeing that behavior, [please make sure that you have HTTP caching disabled](https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug#common_problems) when you serve your `/sw.js` file.)

**Comment by laurentdebricon** [comment]
Thank you for helping me sir but :

I have an asset that need to be cached but need to be updated outside of my site's build/deploy cycle. 
So i can't put it in precache manifest because precache is cacheFirst (correct me if i'm wrong).

So is my piece of code provided the right thing to do ? (with also a special route with strategie network first)

**Comment by jeffposnick** [comment]
If you're not including that asset in your precache manifest, then yes, setting up a route with an appropriate strategy would be the right thing to do.

If you want to prepopulate the cache, you could do it via something like `$.ajax()`, if you wait until the service worker has taken control of your current page before making the `$.ajax()` call. Getting this timing right can be tricky.

A more direct approach would just be to just add the item to the cache directly, using the Cache Storage API, either in your [service worker's `install` handler](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#warm_the_runtime_cache), or, if you're using Workbox's `generateSW` mode and you don't have easy access to the `install` handler, just in the page's code:

```js
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    caches.open('my-cache-name').then(function(cache) {
      cache.match('/myImportantAsset').then(function(response) {
        if (!response) {
          cache.add('/myImportantAsset');
        }
      });
    });

    navigator.serviceWorker.register('/sw.js', {
      scope: "/"
    });                
  });
}
```

Just be sure to use the same cache name (`'my-cache-name'`) when you set up your Workbox route.

**Comment by laurentdebricon** [comment]
Hello @jeffposnick,
thank you for your help last time, it was perfect !
here is my following issue on StackOverflow , migrating my code from v2 to v3 and the lack of doc how to deal with the new v3 system `setdefaulthandler`  //  `setcatchhandler` .

https://stackoverflow.com/questions/50628467/migrate-google-workbox-setdefaulthandler-setcatchhandler-from-v2-to-v3

Best regards
Laurent
