### ISSUE TITLE
Precaching is not working | Workbox | Webpack

### ISSUE THREAD

**Issue by Demon137** [GoogleChrome/workbox#1442]
Hi, 

I want to create a src service work file where I create the routing rules and those rules would get copied from source file to destination file along with precache manifest files.

If I use GenerateSW pulgin then it only creates SW file with precache manifest code. 

If I use InjectManifest pulgin then it only creates SW file without precache manifest code and with routing rules (defined in service worker source file). 

When I use InjectManifest along with GenerateSW then insert manifest is not working. Below is the code. Please suggest.

Webpack.config.js

```js
const { GenerateSW, InjectManifest } = require('workbox-webpack-plugin');

plugins: [
       new InjectManifest({
        swDest: path.resolve(__dirname, '../','main-service-worker.js'),
        swSrc: path.resolve(__dirname, '../','source-service-worker.js'),
        globDirectory: path.resolve(__dirname, './../public/'),
        globPatterns: ['**/*.{html,js,css,ejs}'],
        include: [/\.html$/, /\.js$/],
      }),
       new GenerateSW({
         globDirectory: path.resolve(__dirname, './../public/'),
         globPatterns: ['**/*.{html,js,css,ejs}'],
         swDest: path.resolve(__dirname, '../','main-service-worker.js'),
         clientsClaim: true,
         skipWaiting: true,

      })
    ]
```

Source Service Worker:

```js
importScripts('workbox-sw.prod.js')
const workboxSW = new WorkboxSW({ clientsClaim: true })
workboxSW.precache([])


workboxSW.routing.registerRoute(
  new RegExp('.*/js|css/.*'),
  workboxSW.strategies.staleWhileRevalidate({
    "cacheName": "NF-STATIC-CACHE",
  })
);
```

**Comment by kanzelm3** [comment]
@Demon137 by default, workbox looks for `precacheAndRoute` and injects the manifest into the array there. To use only `precache` try adding this to your config:
```
  injectionPointRegexp: /(\.precache\()\s*\[\s*\]\s*(\))/,
```

**Comment by NithishReddy** [comment]
Precaching assets from domain is not happening using workbox  Injectmanifest.

workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
Any help???

**Comment by jeffposnick** [comment]
Modifying `injectionPointRegexp` and using `InjectManifest` is indeed the recommended use case here to address the initial question. Thanks for contributing the response!
