### ISSUE TITLE
Validate that options.cacheName is set when options.expiration is used

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1443]
**Library Affected**:
*workbox-build*

As reported by @hanford on the Slack channel, if you use a configuration like 

```js
runtimeCaching: [{
  urlPattern: /^https?.*/,
  handler: 'networkFirst',
  options: {
    expiration: {
      maxEntries: 100,
    },
  }
}]
```

with `generateSW`, you'll end up with a service worker that throws errors like

![image](https://user-images.githubusercontent.com/1749548/39134739-5270ae0a-46e5-11e8-9705-ab82ed1419ba.png)

at runtime.

This is because cache expiration only works when there's a custom cache name, and not on the default runtime cache. (See https://github.com/GoogleChrome/workbox/pull/1079)

We can start enforcing this at build time by modifying the `joi` validation rules to ensure that `options.cacheName` is set whenever `options.expiration` is used.

**Comment by neckaros** [comment]
On official website the example for webpack has the issue:
https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack
```
// Define runtime caching rules.
      runtimeCaching: [
        {
          // Match any request ends with .png, .jpg, .jpeg or .svg.
          urlPattern: /\.(?:png|jpg|jpeg|svg)$/,

          // Apply a cache-first strategy.
          handler: 'cacheFirst',

          options: {
            // Only cache 10 images.
            expiration: {
              maxEntries: 10,
            },
          },
        },
      ]
```

**Comment by jeffposnick** [comment]
Thanks @neckaros—I've filed https://github.com/google/WebFundamentals/pull/6236
