### ISSUE TITLE
missing applicationServerKey, and gcm_sender_id not found in manifest

### ISSUE THREAD

**Issue by danilosilvadev** [GoogleChrome/workbox#1446]
I'm using react-webpack and it is generating service-worker and manifest but seems like this error keep appearing.

**Library Affected**:
InjectManifest, cleanPlugin

**Browser & Platform**:
Chrome 66 on Linux

**Issue or Feature Request Description**:
*Your request here.*

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

At webpack.config.prod.js

```js
new InjectManifest({
         globPatterns: ['**/*.{html,js,css,ico}'],
         swSrc: './src/service-worker.js',
         swDest: 'sw.js'
       }),
    new cleanPlugin(pathsToClean),
```
At my service-worker
```js
/**
 * Welcome to your Workbox-powered service worker!
 *
 * You'll need to register this file in your web app and you should
 * disable HTTP caching for this file too.
 * See https://goo.gl/nhQhGp
 *
 * The rest of the code is auto-generated. Please don't update this file
 * directly; instead, make changes to your Workbox build configuration
 * and re-run your build process.
 * See https://goo.gl/2aRDsh
 */

importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.1.0/workbox-sw.js");

importScripts(
  "/precache-manifest.2660061f4095b8ddeb5434a7a681f075.js"
);

//Instructs the latest service worker to activate as soon as it enters the waiting phase.
workbox.skipWaiting();
//Instructs the latest service worker to take control of all clients as soon as it's activated.
workbox.clientsClaim();

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

```

The function called when the index initialize:

```js
export function registerServiceWorker() {
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/sw.js').then(registration => {
        console.log('SW registered: ', registration);
          registration.pushManager.subscribe({userVisibleOnly: true});
      }).catch(registrationError => {
          console.log('Error na registration')
      });
    });
  }
}

```

Error: 
> Uncaught (in promise) DOMException: Registration failed - missing applicationServerKey, and gcm_sender_id not found in manifest

Print at my screen, weird that says it is registered but after this says registering failed:
https://imgur.com/a/4YPdBrI

Full code:
https://github.com/danilosilvadev/workbox-pwa

**Comment by jeffposnick** [comment]
That error's due to your usage of Push Notifications, which is independent from Workbox. It's this line that's failing:

```js
registration.pushManager.subscribe({userVisibleOnly: true});
```

If you didn't intend to use Push Notifications, then just remove that line from your registration code.

**Comment by danilosilvadev** [comment]
@jeffposnick I do intend to use Push Notifications and this line is just the same as this tutorial from workbox docs: https://developers.google.com/web/tools/workbox/guides/codelabs/webpack

**Comment by jeffposnick** [comment]
Right, that part of the tutorial assumed you wanted to add push notifications. You can skip it!

**Comment by msbir** [comment]
@danilosilvadev Hey, did you figure out why this error happens?

I am using the same code
