### ISSUE TITLE
Tests shouldn't run on CI in PRs that don't touch code files

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1452]
We should update our `.travis.yml` file to only run the tests if files that could affect the tests have changed. We shouldn't have to wait for long Travis CI builds when changing things like #1449 :)

Here's an example I've used before that we could adopt for Workbox:
https://github.com/googleanalytics/autotrack/blob/master/.travis.yml#L6-L18

**Comment by jeffposnick** [comment]
We're going to be moving to GitHub Actions soon, and it looks like https://github.com/technote-space/get-diff-action could handle that.

**Comment by jeffposnick** [comment]
Let's skip this for now. I had trouble setting up `get-diff-action` originally, and our test suite completes faster than it used to.
