### ISSUE TITLE
New webpack plugin config option to specify hash length

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1458]
**Library Affected**:
*workbox-webpack-plugin*

Moved over from https://github.com/GoogleChrome/workbox/issues/1454#issuecomment-385608719

`workbox-webpack-plugin` attempts to determine whether an asset already includes a hash in its filename, and won't cache-bust requests for assets that do include a hash.

Unfortunately, we don't have a ton of context from the `webpack` build process to determine whether an asset has a hashed filename or not, and while we can detect full hash usage, we can't safely infer when developers use, e.g., `[chunkhash:6]` to only use a substring of the hash.

Rather than try to automatically guess, what we could do is add in a new config parameter for `workbox-webpack-plugin` called `hashSubstringLength` (or an alternative name, if there are objections). If set, we'll check asset filenames against all the full knowns hash, as well as the substring of each hash with the length specified.

Developers would need to know to manually set this, but it's something that could be automatically included as part of CLI/framework integrations that use a constant hash substring length.

**Comment by freezy** [comment]
Why not use a regex for cache busting like `dontCacheBustUrlsMatching` used to in v2?

**Comment by tmchng** [comment]
I believe it will be much easier if you let the developers specify `string` or `regex` that they wish to match. For instance:

```
dontCacheBustUrlsMatching: [
  '[hash:6]',
  '[chunkhash:8]',
  /\.[a-zA-z\d]{5}\./
]
```

**Comment by jeffposnick** [comment]
I'm closing this in favor of adding `dontCacheBustURLsMatching` support in v5.
