### ISSUE TITLE
Helper to detect when a registered service worker becomes redundant

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#1464]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*"all browsers"*

**Issue or Feature Request Description**:
Hi!

Sorry if this is already possible with workbox, but I couldn't find it in any docs and had no luck in my testing.

I am trying from our application, to detect if `installing` has failed (i.e. some sort of workbox exception happened during install)

The approach I'm taking is something like this:
```ts
private setupRegistrationInstrumentation(registration?: ServiceWorkerRegistration) {
        if (!registration) {
            return;
        }

        const _this = this;

        registration.onupdatefound = () => {
            const installingWorker = registration.installing;

            // Log SW installation failures to the ErrorHandler
            installingWorker.addEventListener('error', function onError(event) { // <-- when does this get fired?
                installingWorker.removeEventListener('error', onError);
                _this.globalErrorHandler.handleError(event.error);
            });
        };
    }
```

Maybe we had a bad deployment and installations started failing because scripts, CSS aren't present in CDN.  How else would be detect this?

Is this possible from Workbox, or Service Workers in general?

event adding something like this to `sw.js` doesn't trigger an error handler, so it may not even be possible from service workers to do this kind of instrumentation...:
```js
self.addEventListener('install', () => {
    throw new Error('Something terrible has happened');
});
```

Thanks!
Joe
*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
CC: @prateekbh, as this falls broadly under the "helper library that runs in `window`" project that he's been looking into.

**Comment by jeffposnick** [comment]
@philipwalton is now the one looking into this, and I think the thing to do would be to provide a callback in the `window` context  which fires when a newly registered service worker enters the [`'redundant'` state](https://w3c.github.io/ServiceWorker/#dom-serviceworkerstate-redundant).

As per the [`install` algorithm](https://w3c.github.io/ServiceWorker/#installation-algorithm), step 13.1, that's what happens when a service worker fails installation.

**Comment by jeffposnick** [comment]
This is part of `workbox-window` in v4:

https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-window/Workbox.mjs#L580-L595
