### ISSUE TITLE
Broken workbox-build#getFiles() link on "Using Local Workbox Files Instead of CDN"

### ISSUE THREAD

**Issue by abraham** [GoogleChrome/workbox#1469]
[Using Local Workbox Files Instead of CDN](https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn) has a broken link where `workbox-build#getFiles() ` links to `https://developers.google.com/`.

**Comment by jeffposnick** [comment]
Thanks, @abraham! The docs are in another repo, so I've filed https://github.com/google/WebFundamentals/pull/6108 there to fix this.
