### ISSUE TITLE
WorkboxSW throws upon registration if imported from the "module" property of the package.json file

### ISSUE THREAD

**Issue by wessberg** [GoogleChrome/workbox#1471]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
If `workbox-sw` is imported with a tool such as Webpack or Rollup that is configured to use the file referenced by the package.json `module` property if it exists, it will resolve the `index.mjs` which, indirectly exports `WorkboxSW` from `./controllers/WorkboxSW.mjs`.

Loading from this path will crash in browsers since the file contains the following hardcoded CDN path:

```javascript
// Inside ./controllers/WorkboxSW.mjs
const CDN_PATH = `WORKBOX_CDN_ROOT_URL`;
```
An attempt to register a Service Worker loading `workbox-sw` this way will result in the following error message in the console of, for example, Chrome 68.0.3409.2: `Unable to import module 'workbox-routing' from 'WORKBOX_CDN_ROOT_URL/workbox-routing.dev.js`

**Comment by wessberg** [comment]
@jeffposnick,

The reason for importing `WorkboxSW` this way is for better Typescript interoperability (see https://github.com/GoogleChrome/workbox/pull/1436). Something like `import WorkboxSW from "workbox-sw"` is nice to have in my opinion, even knowing that it dynamically imports the underlying imports under the hood. Would this be as simple as changing the value of the `const CDN_PATH` to a proper url?

**Comment by jeffposnick** [comment]
Closing for a similar reason to https://github.com/GoogleChrome/workbox/issues/1585

CC: @philipwalton to make sure that he takes this into account when writing up the guide to creating a custom bundle.

**Comment by philipwalton** [comment]
Yes, the guidance will be to not use `workbox-sw` if creating your own bundle. We'll have a guide on bundling that we publish with the v4 release, but you can read a [draft here](https://docs.google.com/document/d/1LbRxTbTKM8W6Qt0S6rGEP9V51sX8tRpGbqJ_IwoXxEQ/edit?usp=sharing) if you have concerns about our recommendations.
