### ISSUE TITLE
Does not copy workbox files to dest dir when imported as ESM

### ISSUE THREAD

**Issue by kirlat** [GoogleChrome/workbox#1472]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Windows 10 Pro 1709, node.js 9.10.1

**Issue or Feature Request Description**:
There is a node.js build script that uses an ESM syntax. It uses an InjectManifest mode of workbox-webpack-plugin. InjectManifest is imported as `import InjectManifest from '../../node_modules/workbox-webpack-plugin/build/inject-manifest.js'`. It seems to be the only way that works, importing directly from `workbox-webpack-plugin` returns an error. 
Plugin options:
```
new InjectManifest({
        swSrc: path.join(projectRoot, 'src/sw.js'),
        swDest: 'sw.js',
        importWorkboxFrom: 'local',
        globPatterns: ['dist/*.{json,js,html}']
      })
```
workbox and workbox-webpack-plugin versions are 3.2.0. Webpack version is 4.7.0.

`workbox-webpack-plugin` seems to be doing its job fine except it does not copy workbox files to the destination directory as `local` option require. It creates a folder named `workbox-v3.2.0`, but this folder is empty.

When loaded using `require` syntax (`require(workbox-webpack-plugin)`) and with the same options, it works perfectly.

I'm wondering if there is any way to fix this. Would really love to use this plugin with an ESM syntax, if possible. Does this issue has something to do with the way the InjectManifest mode file is imported? What's the proper way to load this plugin using ESM syntax?

**Comment by jeffposnick** [comment]
`importWorkboxFrom: 'local'` is no longer supported in Workbox v5, and we've moved to an approach where the `swSrc` file is compiled directly by webpack.
