### ISSUE TITLE
wokrbox-build: injectManifest fails silently with unfound glob patterns

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1477]
**Library Affected**:
*workbox-build v3.2.0*

Apologies if I'm just missing something simple.

workbox-build's `injectManifest` method is not injecting files into the `precacheAndRoute` call in the outputted service worker when a file specified by the `globPattern` is missing. For example, the following code:

```
const workboxBuild = require('workbox-build');
const buildSW = () => {
  return workboxBuild.injectManifest({
    swSrc: 'src/sw.js',
    swDest: 'build/sw.js',
    globDirectory: 'build',
    globPatterns: [
      'style/*.css',
      'scripts/*.js',
    ]
  });
}
buildSW();
```

Fails silently because my styles live in a **styles** directory instead of a mistyped **style** directory. 

It took me a while to figure out why manifest injection wasn't working, so perhaps an error could be logged in this situation?

**Comment by jeffposnick** [comment]
The [promise returned by `injectManifest`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.injectManifest) resolves to an object with a `warnings` property. What you should be seeing in this situation is a warning returned there. It's up to you to display these sorts of warnings as you see fit.

(This is a change from the v2 behavior, when this would have been a fatal warning; see https://github.com/GoogleChrome/workbox/issues/1176 for context.)
