### ISSUE TITLE
Plugins should have a callback for modifying network responses

### ISSUE THREAD

**Issue by shogun70** [GoogleChrome/workbox#1481]
Currently I can transform a network response before it is cached using `cacheWillUpdate()`.
I can even transform a cache response before it is used to respond to the fetch event using `cacheResponseWillBeUsed()`. 
But there is no callback allowing me to transform a network response before it is used to respond to the fetch event.

My use-case: 
I want a cache-first strategy for handling particular requests but I also need to transform the network response before it is used to  respond to the fetch event and I need to ensure that future cache hits return the same transformed response. I can ensure that later requests (which hit the cache) get the transformed response, but it does not seem possible to intercept network responses with the current design / implementation of CacheFirst (or any of the other strategies). 

Initially I assumed that the *result* of `cacheWillUpdate()` would be used both to update the cache and to respond to the fetch event. Testing demonstrated that the result is used to update the cache but is *not* used to respond to the fetch event. 

Then I thought I would construct a route handler using a CacheFirst handler to ensure that the cache is populated followed by a CacheOnly handler to pick up the transformed response, but the CacheFirst handler resolves before the cache is updated so CacheOnly handler fails. 

I finally solved my use-case using an async wrapper around a CacheFirst handler. The wrapper function is resolved by `cachedResponseWillBeUsed()` or `cacheWillUpdate()`. 

I suspect my use-case is common enough that it should be handled by CacheFirst with a custom-plugin instead of a custom handler that relies on inspecting the CacheFirst internals.

**Comment by jeffposnick** [comment]
This will be addressed in v4 via a new `fetchDidSucceed` callback.
