### ISSUE TITLE
generateSW assets location

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/workbox#1499]
**Library Affected**:
* workbox-build

**Browser & Platform**:
Not applicable

I was wondering, is it possible to change the output dir of workbox assets when using the `generateSW` function? For example, now if I use:

```js
importWorkboxFrom: 'local',
globDirectory: buildDir,
globPatterns: [
    '**/*.{html,css,gif,jpg,js,json,png,svg}'
],
swDest: `${buildDir}/sw.js`
```

then I get a folder `workbox-v1.2.3` in `buildDir`.

Sorry if this somewhere documented, I couldn't find a solution from a quick look. Also, I don't use SO, so, I thought I'd try asking here. :)

**Comment by jeffposnick** [comment]
It's not currently possible when using `workbox-build`/`workbox-cli` to generate your service worker. The versioned directory (`workbox-vX.Y.Z`) is an important requirement, since [`importScripts()` resources are cached aggressively](https://developers.google.com/web/updates/2018/06/fresher-sw), and we need to make sure that each new version of the script gets their own unique URL.

As for the output location, we need to keep that standard (alongside `swDest`) so that the `importScripts()` call inside of the final service worker knows where to look.

**Comment by XhmikosR** [comment]
@jeffposnick: first of all, thanks for the reply! I'm not using workbox-cli though, I'm using workbox-build via gulp/node.

I don't mind keep using workbox-build via `injectManifest()`, but I wanted to solve these 2 issues:

1. serve the workbox files from my server instead of the CDN
2. see if I can cache bust the workbox-build files

**Comment by jeffposnick** [comment]
`workbox-build` and `workbox-cli` should be equivalent in this regard. (The CLI is just a thin wrapper over `workbox-build`, written in node.)

> serve the workbox files from my server instead of the CDN

This is supported via the mechanism you're using.

> see if I can cache bust the workbox-build files

I'm not sure what you mean by this. If you're talking about cache-busting the Workbox library files that are pulled in via `importScripts()`, that isn't something that you should have to do—you can rely on the fact that the version number for the libraries are part of the URL (`workbox-vX.Y.Z`), and that should be sufficient from a versioning point of view. If you go out of your way to move the Workbox library files from the versioned subdirectory into an unversioned URL, then you'd end up creating a problem for yourself. I'd recommend not doing that.

**Comment by XhmikosR** [comment]
Thanks for the reply!

I was able to do everything I needed, including changing my assets URL by prepending my CDN's URL and caching opaque responses with `generateSW`.

Only thing left, mostly due to my habit of having assets organized in the same folders, is changing the output dir of workbox JS files when serving from my server.
