### ISSUE TITLE
sw-cache-video-playback

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#15]
**Library Affected**:
sw-cache-video-playback

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Video streaming from a service worker querying the Cache Storage API has some pain points at the moment—e.g., your service worker [needs to understand the `Range:` request header](https://bugs.chromium.org/p/chromium/issues/detail?id=575357) in order to support seeking/scrubbing. There's a good opportunity to provide a helper that handles that complexity.

(CC: @adrianholovaty)

**Comment by gauntface** [comment]
@paullewis is this related to your work on Video playback in SW?

**Comment by jeffposnick** [comment]
Closing this in favor of https://github.com/GoogleChrome/workbox/issues/372
