### ISSUE TITLE
broadcastUpdatePlugin requires a response header to determine response difference

### ISSUE THREAD

**Issue by 0xR** [GoogleChrome/workbox#1501]
**Library Affected**:
workbox-broadcast-cache-update

**Browser & Platform**:
All

**Issue or Feature Request Description**:
The broadcastUpdatePlugin will check response headers to determine whether responses are the same. However there is no way to disable this check for when your server doesn't send usable response headers.

I expect this to disable the response header check.
```js
      new workbox.broadcastUpdate.Plugin('api-updates', { headersToCheck: []})
```

However this code will just assume response are always the same: https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-broadcast-cache-update/utils/responsesAreSame.mjs#L55

Possible solution:
```
if(!headersToCheck.length) {
  return false;
}
```

At the top of `responsesAreSame`

**Comment by jeffposnick** [comment]
> An alterative would be to make the change detection algorithm of this plugin pluggable. That way it doesn't have to rely on response headers if you don't want that.

We do offer a pluggable solution, via the `cacheDidUpdate()` callback that is fired whenever a cache is written to.

You can implement your own, arbitrarily complex logic inside of that callback, giving you control over both how to determine whether something's "changed" (checking headers, checking response bodies [assuming you `clone()` the responses first], etc.), as well as what you want to do if a change is detected. The [recipe I linked to](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#use_postmessage_to_notify_of_cache_updates) illustrates one possible custom implementation.

Given the flexibility offered by that custom callback, I don't believe that we would want to change the default behavior of the "official" `workbox-broadcast-cache-update` plugin, which is fundamentally just one possible, prepackaged `cacheDidUpdate()` callback implementation.
