### ISSUE TITLE
[Feature] Add ability to specify [hash] in navigationFallback

### ISSUE THREAD

**Issue by mike-marcacci** [GoogleChrome/workbox#1506]
**Library Affected**:
workbox-sw

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I have the need to specify a `navigationFallback` that uses [webpack filename substitutions](https://webpack.js.org/configuration/output/#output-filename), like this:

```js
{
  new HtmlWebpackPlugin({
    template: "src/boltline.html",
    filename: "boltline-[hash].html"
  }),
  new GenerateSW({
    // ...
    navigateFallback: "/boltline-[hash].html",
    // ...
  })
}
```

Our caching strategy depends on idempotent URLs, or we risk serving old content for a **long** time.

**Comment by vasisouv** [comment]
This is not yet implemented, right? Same goes for the `precacheFallback.fallbackURL`, which can not be made dynamic at the moment.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
