### ISSUE TITLE
[Docs] CachedResponseWillBeUsed and CacheWillUpdate plugin callbacks can be async, but not noted in docs

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#1507]
**Library Affected**:
Docs for `workbox-sw` (workbox 3)

**Browser & Platform**:
None

**Issue or Feature Request Description**:
https://developers.google.com/web/tools/workbox/guides/using-plugins

In the workbox documentation, for custom plugins, it says that `cachedResponseWillBeUsed` and `cacheWillUpdate` return type of `Response` or `null`:
```js
const myPlugin = {
  cacheWillUpdate: ({request, response}) => {
    // Return `response`, a different Response object or null
    return response;
  },
  cachedResponseWillBeUsed: ({cacheName, request, matchOptions, cachedResponse}) => {
    // Return `cachedResponse`, a different Response object or null
    return cachedResponse;
  }
};
```

However, in my testing, these can be `async` functions, so returning a `Promise<Response>` should be OK too.

Having these plugin lifecycle hooks support async code is awesome.  I'm just double checking that this is by design to support async code / return `Promise<Response>`, and that it's just a documentation error?

I also assume that `requestWillFetch` allows for async code as well?

Here's a test app that shows that they do block for async code.
[WorkboxPromisePlugins.zip](https://github.com/GoogleChrome/workbox/files/2056072/WorkboxPromisePlugins.zip)

Thanks!

**Comment by jeffposnick** [comment]
Thanks for pointing that out—in v3, we started using `await` when calling all of the plugin lifecycle methods, just for consistency's sake, but https://developers.google.com/web/tools/workbox/guides/using-plugins wasn't updated to reflect that. I'll make the change in the docs.
