### ISSUE TITLE
Write precache-manifest path

### ISSUE THREAD

**Issue by hanagejet** [GoogleChrome/workbox#1508]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:
Can write precache-manifest.js dist path

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

write config:
```js
// config.js
new GenerateSW({
  swDest: path.resolve('./.next/static/sw.js'),
})
```

generated sw.js: `.next/static/sw.js`
generated manifest.js: `.next/static/precache-manifest.${hash}.js`

But this is not corrected path of importScripts
```js
// sw.js
importScripts(
  "static/precache-manifest.fc579fe473694393eb0b73821ed77bae.js" // change `static/` to ``
);
```

Can I fixed this??

**Comment by jeffposnick** [comment]
What does the rest of your `webpack` configuration look like, including the `output` and `publicPath` settings?

**Comment by hanagejet** [comment]
I used nextjs.

My next.config.js:
```js
const {GenerateSW} = require('workbox-webpack-plugin');
const withTypescript = require('@zeit/next-typescript');
const withCSS = require('@zeit/next-css');
const webpack = require('webpack');
const path = require('path');
const Dotenv = require('dotenv-webpack');

module.exports = withTypescript(
  withCSS({
    webpack(config) {
      if (process.env.NODE_ENV === 'develop') {
        config.plugins.push(
          new GenerateSW({
            cacheId: 'mercari-web-jp',
            swDest: path.resolve('./.next/static/sw.js'),
            importsDirectory: 'static',
            // importWorkboxFrom: 'local', TODO: fix this
            clientsClaim: true,
            skipWaiting: true,
            runtimeCaching: [
              {
                urlPattern: '/',
                handler: 'staleWhileRevalidate',
                options: {
                  cacheName: 'top-cache',
                  expiration: {
                    maxEntries: 5,
                    maxAgeSeconds: 60,
                  },
                },
              },
            ],
          })
        )
      }
      return config
    },
  }),
)
```

versions:
```json
"next": "^6.0.2"
"webpack": "^3.12.0",
"workbox-sw": "^3.2.0",
"workbox-webpack-plugin": "^3.2.0"
```

**Comment by azampagl** [comment]
+1 this request.

It would be nice to have a "precacheDestDir" option where we can at least define the folder relative to the publicPath.

To put in perspective, I'm using the new vue cli and I would like to put the precache file into a "static" directory, which is relative to the output path.

E.g.

    config
            .plugin('workbox')
            .tap(([workBoxConfig]) => {
                workBoxConfig.precacheDestDir = 'static'; // this would put it in {outputPath}/{precacheDest}/precache-manifest.xxxxxx.js
                return [workBoxConfig];
            });

So if my output path is.... lets say 'app', the import script would look something like:

    // service-worker.js
    importScripts(
      "/app/static/precache-manifest.fc579fe473694393eb0b73821ed77bae.js"
   );

instead of 

    // service-worker.js
    importScripts(
      "/app/precache-manifest.fc579fe473694393eb0b73821ed77bae.js"
   );

**Comment by jeffposnick** [comment]
Does `next` expose what the underlying `output` and `publicPath` settings are for `webpack`, under the hood?

**Comment by jeffposnick** [comment]
In `workbox-webpack-plugin` v5, we no longer emit a separate precache manifest file, so this is obsolete.

**Comment by DenisOH** [comment]
Even though I'm late to the party, but maybe it will help someone:
Here's a workaround I found [while looking](https://github.com/hanford/next-offline/blob/070c6330262e93ab3fc27c7f206afe454a13e246/packages/next-offline/index.js#L19) at [next-offline](https://github.com/hanford/next-offline) project.

```
// This option has to be passed to GenerateSW

modifyURLPrefix: {
  'static/': '_next/static/'
}
```
