### ISSUE TITLE
Cache Expiration Logic not running in Edge due to exceptions with running 'openCursor'

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#1509]
**Library Affected**:
workbox-sw / workbox-core (I think this is actually from the IndexedDB Helper library used internally in workbox-core)

**Browser & Platform**:
Edge (latest)

**Issue or Feature Request Description**:
Another browser compat bug with Edge.

In Workbox, cache timestamps are stored in IndexedDB.  When opening a cursor to iterate through the object store, one can pass optional parameters:
https://github.com/GoogleChrome/workbox/blob/118598366adfb22f3e74217ccd403713109dc277/packages/workbox-core/_private/DBWrapper.mjs#L200-L221

These optional parameters are in this block `opts.query` and `opts.direction`.

However, due to behavior in Edge, `openCursor(opts.query, opts.direction)` actually throw `DOMException: DataError`. because `opts.query` and `opts.direction` are `undefined`.

In workbox, what ends up happening is that the exception is thrown, but never handled, so the deletion logic never runs and it waits indefinitely for a `Promise` to never resolve.

I have a repro here for the cursor bug specifically:
[EdgeIndexedDBCursorUndefinedNonstandardBehavior.zip](https://github.com/GoogleChrome/workbox/files/2060114/EdgeIndexedDBCursorUndefinedNonstandardBehavior.zip)

I will also prepare a workbox specific repro app that shows the expiration logic never getting run for Edge.

This one I am not 100% sure on the spec details, I'll have to do some reading, but regardless, I think workbox will need to handle this case to expire cache entries properly on Edge.

**Comment by jeffposnick** [comment]
CC: @philipwalton, as IDB is something he really enjoys and appreciates.

**Comment by josephliccini** [comment]
Here's the workbox repro app.  Try running in Chrome and then in Edge.
[WorkboxEdgeNeverExpiresEntries.zip](https://github.com/GoogleChrome/workbox/files/2060363/WorkboxEdgeNeverExpiresEntries.zip)

**Comment by josephliccini** [comment]
I think I can get a CR out for this.  Will put one together (should be a straightforward fix)

**Comment by surajrautela** [comment]
is this fix going to be a part of next release?

**Comment by jeffposnick** [comment]
@surajrautela, you can follow along with the PR at https://github.com/GoogleChrome/workbox/pull/1510.

Once that's merged, it should make it into the next Workbox release.

**Comment by surajrautela** [comment]
Thanks a lot !!
