### ISSUE TITLE
Edge-specific regression from Workbox 2 to 3 in custom plugin lifecycle callback 'requestWillFetch' when mutating a Headers object

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#1512]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Edge (latest Windows)

**Issue or Feature Request Description**:
This one I think might be a bug in Edge, but it would be good to understand what has changed from a workbox perspective between workbox 2 and workbox 3, to help narrow down the Edge bug.

What happens is that if one tries to remove `Headers` entries from a cloned `Headers` object, in workbox 3, they will not actually get removed. (My theory is that this has now become async, and Edge tries to lazily do work on Headers, but I have to follow up with them to be sure).

In workbox 2 this is not an issue.

I have attached 2 apps.

1 app is with Workbox 3 where issue repros (in Edge only), here
[EdgeHeadersIssueWorkbox3.zip](https://github.com/GoogleChrome/workbox/files/2063963/EdgeHeadersIssueWorkbox3.zip)

the other is Workbox 2, where there were no issues in any browser, here: 
[EdgeHeadersIssueWorkbox2.zip](https://github.com/GoogleChrome/workbox/files/2063967/EdgeHeadersIssueWorkbox2.zip)

Thanks!

**Comment by gauntface** [comment]
To be honest there was so much changing that I'm not sure it's useful to compare v2 and v3.

The code for handling the plugins is here: https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-core/_private/fetchWrapper.mjs#L63

It looks like it should be using the correct request object. You can (naively) check that the return Request is being used by returning a non Request object and ensuring an error is logged.

**Comment by josephliccini** [comment]
I got a confirmation from the Edge team, and it is a bug in Edge that has been fixed.

This is not related to workbox.

Thanks!
