### ISSUE TITLE
Inconsistency in regex usage in route matching 

### ISSUE THREAD

**Issue by chrisdarroch** [GoogleChrome/workbox#1514]
**Library Affected**:
workbox-routing

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:

When registering a route either through `registerRoute` or `registerNavigationRoute`, you can provide a regular expression for matching the route. This regex is checked against `location.href`. 

You can also provide a regex in an array of `whitelist` and `blacklist` entries when registering a given navigation route. These regexes are checked against `location.path + location.search`.

This causes a bit of confusion. It is not possible to provide a root-relative regex as the first parameter of `registerRoute`. However, you *must* provide a root-relative regex for `whitelist` and `blacklist` options.

This can lead to spending dozens of minutes debugging the workbox implementation to find out why this seemingly reasonable code does not work:

```
const baseUrl = location.origin;

// this will work since it is tested against the full href
workbox.routing.registerRoute(
    new RegExp(`^${baseUrl}/api/`),
    handler
);

// this won't, because it is tested against the path
workbox.routing.registerNavigationRoute('/index.html', {
    whitelist: [
        new RegExp(`^${baseUrl}/item`)
    ]
});
```

The workbox API should behave in a consistent manner. Whenever the user's mental model is "I'm matching against a URL", the behaviour should be the same.

**Comment by zinara** [comment]
The fact that workbox-build.injectManifest's globPatterns can only work with rexexp patterns that are matched against it is a problem in itself. Like the normal service worker where one can add any url address both from the same origin and from a cross site origin. workbox seems not to have a solution for this. whereby I try adding files like this: var filesToCache = [
    '/',
    '/css/exchan.css',
    '/css/bootstrap.css',
    '/Currency-Converter/css/bootstrap.min.css',
    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css',
    'https://fonts.googleapis.com/css?family=Lateef&amp;subset=arabic'
]. The buildSw will return an error when called from the command line. My point is the fact that workbox relies heavily on regexp in creating the app shells, limits developers from adding the urls they which to. I use workbox-build and gulp

**Comment by jeffposnick** [comment]
@zinara, the issue you're bringing up has to do with the fact that the precache list is generated at build time (using `glob` patterns, not `RegExp`s, though they're similar) and can only generate hashes for local content that's deployed alongside the updated service worker. If there are third-party URLs that you want cached, you can [set up routes](https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests) to match them and use a runtime caching strategy.

@philipwalton is working on some new functionality that will make it easier to automatically cache all of the remote URLs that were loaded on a given page before the service worker was initially registered; you can follow along at https://github.com/GoogleChrome/workbox/issues/368

**Comment by jeffposnick** [comment]
I'm revisiting this issue in light of our final planning around what makes it into v4.

After thinking about it some more, I'm now of the opinion that what would make the most sense is to try to detect when there's a RegExp provided as part of the `navigateFallback*list` that *would* have matched the full URL, and log that when Workbox is in `dev` mode.

The precedent for this is the existing code that we have in place around cross-origin requests: https://github.com/GoogleChrome/workbox/blob/59e7d4f0bcb365126b4094d0700346c99ce7a8d9/packages/workbox-routing/_default.mjs#L92-L100

This should help alleviate the frustration (at least if the JS console is open), without introducing what would end up being a slightly different inconsistency, where we ended up checking `navigateFallback*list` `RegExp`s against both `url.pathname + url.search` and `url.href`, while we ended up checking `RegExpRoute` patterns against only `url.href`.

I'm going to leave this open to track that extra logging, but this isn't in scope for a `v4` breaking change.

**Comment by tonytonyjan** [comment]
Not related to the main topic: for people who are going to write ``new RegExp(`^${baseUrl}/api`)`` in their code, beware that `new RegExp("https://example.co.jp/api")` will both match `https://example.co.jp/api` and `https://examplexco.jp/api`, which is probably not expected.

**Comment by sharvilak11** [comment]
I ran into an issue where if prefix baseUrl is not provided and simply kept `.*` doesn't work. Is it intentional?

Workbox webpack plugin 4.3.1

This works
```
new RegExp(/http:\/\/localhost:5379\/admin\/.*/)
```

This doesn't;
```
new RegExp(/.*\/admin\/.*/)
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
