### ISSUE TITLE
Dynamically switch between debug and prod mode 

### ISSUE THREAD

**Issue by surajrautela** [GoogleChrome/workbox#1525]
**Library Affected**:
workbox.setConfig

**Browser & Platform**:
"all browsers".*

**Issue or Feature Request Description**:
I am planning to set debug mode : true 
here is the process i am following ;

1. using PWA to store the mode value : true/false in a cache
2. Open the cache and set the debug value using the stored variable.
3. the problem is everything is async and install event is getting called before workbox.setconfig

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
I left an answer at https://stackoverflow.com/a/50803321/385997

**Comment by surajrautela** [comment]
So Our system is pretty complex . We wanted our PWA to add debug mode in a cache and later use it in the service worker file here is the code:
const workboxCdnUrl = "https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-sw.js";
const cacheName = "sp-cache-v1";
const expirationTimeInSeconds = 60 * 60 * 24;
const CDN_HOST_ENDS_WITH = '.akamaihd.net';

async function main(){
    var importWorkbox = (cdnUrl) => {
        importScripts(cdnUrl);
    }

    importWorkbox(workboxCdnUrl);

    // function to enable logging if mode value is debug
    await (async function switchDebugMode()
    {
        var cache = await caches.open('sw-mode');;
        var res=await cache.match("https://sw-mode/cache");
        var json=JSON.parse(await res.text());
        //currently making it true for testing purpose
        if(1===1)
        {
        // if we want to enable logging for debugging puposes
            workbox.setConfig({
            debug: true
            });
            workbox.core.setLogLevel(workbox.core.LOG_LEVELS.log);
        }
    })()


    // function to check if the request if from sharepoint desktop app
    // In case of webapp we will only cache CDN requests
    function _isDataCachingEnabled(request) {
        var ua = request.headers.get('user-agent');
        return ua && (
            ua.indexOf('SharePointDesktop') !== -1
        );
    }

    // Check if the url is the CDN url
    function _isCDN(url) {
        const host = url.split('/')[2];
        return host && host.endsWith(CDN_HOST_ENDS_WITH);
    }

    // deleting index DB on new installation
    async function deleteIndexedDBDatabase(key) {
        return new Promise((resolve, reject) => {
            const request = indexedDB.deleteDatabase(key);
            request.onerror = reject;
            request.onsuccess = resolve;
        });
    }

    const expirationPlugin = new workbox.expiration.Plugin({
        // Only cache requests for a month
        maxAgeSeconds: expirationTimeInSeconds * 30
    })

    // On a new service worker implementation clear all the caches
    // VSO task:https://onedrive.visualstudio.com/WEX!/Sharepoint%20Desktop/_workitems/edit/583583
    // https://github.com/GoogleChrome/workbox/issues/1365
    self.addEventListener("install", async (event) => {
        cacheKeys = await caches.keys();
        cacheKeys.map(async cacheKey => {
            caches.delete(cacheKey);
            await deleteIndexedDBDatabase(cacheKey);
        });
    });

    // Custom Plugin to remove request headers from the service worker cache
    const removeRequestHeadersPlugin = {
        cacheDidUpdate: async ({
            cacheName,
            request
        }) => {
            caches.open(cacheName).then(function(cache) {
                cache.match(request).then(function(response) {
                    cache.put(request.url, response);
                })
            });
        }
    };

    // Custom plugin that checks whether to cache the request or not based on user agent
    const checkUserAgent = {
        cacheWillUpdate: async ({
            request,
            response
        }) => {
            if (_isDataCachingEnabled(request) || _isCDN(request.url)) {
                return response;
            }
            // Null response indicates request wont be cached
            return null;
        }
    };

    // using cache first strategy for requests to akamaihd.net
    workbox.routing.registerRoute(
        new RegExp("(.*)akamaihd.net(.*)"),
        workbox.strategies.cacheFirst({
            cacheName: cacheName,
            plugins: [
                expirationPlugin,
                new workbox.cacheableResponse.Plugin({
                    // cache only successful response with status code 200
                    statuses: [200]
                }),
                removeRequestHeadersPlugin
            ]
        })
    );

    // using stale while revalidate for all the other urls 
    workbox.routing.registerRoute(
        new RegExp(".*"),
        workbox.strategies.staleWhileRevalidate({
            cacheName: cacheName,
            plugins: [
                expirationPlugin,
                removeRequestHeadersPlugin,
                checkUserAgent
            ]
        })
    );
}
main().then(console.log("service worker is installed"))
this code works for chrome but not in edge

**Comment by surajrautela** [comment]
thanks for the fast reply @jeffposnick  . I wrote the above code to set the debug mode via cache but the code is not working in edge browser. It is not able to find modules like workbox-core etc , in chrome this code works fine

**Comment by jeffposnick** [comment]
That sounds like #1504. There are more details about best practices and workarounds there.

(This will stop working in an upcoming release of Chrome as well.)

**Comment by surajrautela** [comment]
fixed the issue by using request parameter . thanks for the help @jeffposnick
