### ISSUE TITLE
Lazyloading Images and Workbox

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1531]
**Library Affected**:
v3.2.0

**Browser & Platform**:
Google Canary 69.0.3457.0 (Have not tested on other browsers yet)

**Issue or Feature Request Description**:
Workbox and Lazy-loading Images

I have a website that is using the Lazysizes library which is lazy-loading some images and can be found here: https://github.com/aFarkas/lazysizes

A code example I am using is this:

```
<img data-src="image.jpg" class="lazyload" alt="example" width="100" height="100">
<noscript><img src="image.jpg" alt="example" width="100" height="100"></noscript>
```

I am precaching the webpage(s) with the following code:

```
  workbox.precaching.precacheAndRoute([
    '/', '/amp/home', '/offline-page', '/amp/offline-page'
  ], {
    ignoreUrlParametersMatching: [/^utm_/],	  
    directoryIndex: '/',
    cleanUrls: false,
  });
```

However, when I check Google Dev Tools and turn off the internet network, I notice that the webpage, css and javascript is cached. But not the lazy-loaded images! Only when I actually scroll the webpage and physically load the image manually, I see them go into the cache in dev tools.

I should mention that before I upgraded the images to lazy-loading, Workbox was adding them via the same setup no problem. 

I am going to write the URL Image Locations into the precache, to try and force them into the cache at run-time.

But I thought I'd post this issue as it may be useful and also wondered if there was a feature already built with the Workbox API, or maybe this could be a feature request to cache the lazy-loading images on request.

**Comment by spinmar** [comment]
I'm interested too.
Because lazy load images are not downloaded immediatly by the browser they are not present in the network traffic and the service worker can't save in the cache.
One solution could be identify the page with lazyload images, parse the response.text() with a dom parser, get all data-src of images and fetch them saving in the cache. 
@jeffposnick can you help us?
Thanks

**Comment by jeffposnick** [comment]
While there might be a number of reasons that developers choose to use lazy-loaded images, high on the list is to be considerate of a users' bandwidth, and not cause them to download data that might never be displayed.

That runs counter to the idea of adding them to a cache (which obviously requires downloading the data, albeit inside the service worker) ahead of time, before they're displayed on the page.

If there's some nuance that I'm missing as to why this is desirable, please let me know. But I'd think that if you want them to be cached, then *not* lazy-loading would be the most straightforward approach—conversely, if you do want them lazy-loaded, then *not* caching them in advance makes sense.

**Comment by ayumihamsaki** [comment]
If it helps I give an update for what I did in the end. For the pre-cache webpages of the home page and offline page that had lazy-loading images, I just added the URL image locations direct into the pre-cache and that fixed the problem.

However, I quickly found another issue with Workbox in that all my PWA webpages have lazy-loading and I was seeing issues below-the-fold, when trying to cache the current webpage. I decided to add Jeff's Fallback Image code to patch the errored images found here: https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route

Unfortunately, that code doesn't work with Lazy-loading images! So my solution was to use JQuery for the Fallback Images instead and serve a general "Sorry this image didn't load" Fallback Image for the missing images. Not the best solution but this is the issue I found with Workbox and Lazy-loading.

**Comment by jeffposnick** [comment]
> Unfortunately, that code doesn't work with Lazy-loading images!

I'm not sure why that would be the case—the act of setting an `img.src` to a valid URL should trigger a network request that a service worker's `fetch` handler could intercept.

Do you have an example of that failing?

**Comment by housseindjirdeh** [comment]
I also think it feels counter-intuitive to cache lazy loaded images in advance. If it helps, I think this [website](https://images.guide/) is a good example of how lazy loaded images can be cached on demand (Workbox config can be found [here](https://github.com/GoogleChrome/essential-image-optimization/blob/a1c7d745d81944a40d0c5b6edf27b4746ef6741a/gulpfile.babel.js#L307-L313)). The response for each image request is cached as the user scrolls past them.

**Comment by jeffposnick** [comment]
Closing for now. If there's some nuance that we're missing, let us know and we can revisit.

**Comment by asolopovas** [comment]
How about this scenario, I would like to make sure that if user downloaded images via lazy-loaded request once, they should remain in cache, so that in case of lost connection he can browse already downloaded ones.

**Comment by christian-hackyourshack** [comment]
I see, this is stone-old. However, I stumbled over it when looking for a way, how to cache a whole page with all images on demand. Background: We have a highly bandwidth-optimized website targetting the African market with step-by-step instructions. I want to allow users to store complete individual pages including all images for offline use by using a button, either when they are on the page or from a list of search results. I wish, I would not need to parse the HTML to find all images and download them, but to be able to tell workbox "Please cache this page (including all assets, even those that are lazy loading)".
