### ISSUE TITLE
Workbox webpack: first use first problem

### ISSUE THREAD

**Issue by spinmar** [GoogleChrome/workbox#1535]
Hi all
I'm trying to convert my native service worker using workbox webpack.
I'm using version workbox 2.1.3 and because I need to handle images, js, css and web page of my site I'd like to use a default router.
Reading this page:

[https://developers.google.com/web/tools/workbox/modules/workbox-routing#advanced_usage](url)

I wrote in my sw.js this piece of code:

const workboxSW = new self.WorkboxSW({ skipWaiting: true, clientsClaim : true });
.....
const router = new workboxSW.routing.Router();
self.addEventListener('fetch', (event) => {
  const responsePromise = router.handleRequest(event);
  if (responsePromise) {
    event.respondWith(responsePromise);
  } else {
    if ((!navigator.onLine) && (event.request.mode === 'navigate')) {
        caches.open(CACHENAME).then(function (cache) {
                if (event.request.mode === 'navigate') {
                       // precached
                        return cache.match('/templates/offline.html');
                }
        })
    }
  }
});
 
workboxSW.router.registerRoute(
  /https:\/\/xxx.xxx.xxx\/.+\.(png|jpg|jpeg|svg|gif|webp|bmp)/,
  workboxSW.strategies.cacheFirst({
    cacheName: CACHENAME_image,
    cacheableResponse: { statuses: [0, 200] },
    "cacheExpiration": {
        "maxEntries": 50
        },
  })
);
.........

Service worker generates a console error:

Uncaught TypeError: Cannot read property 'Router' of undefined

Can someone help me and explain me where is my error?
Thanks

**Comment by jeffposnick** [comment]
I'd recommend moving to Workbox v3, which is the latest release.

In it's most commonly used form, Workbox v3 exposes a single, global namespace under `workbox.*`, with standard sub-namespaces underneath it corresponding to each module, like `workbox.routing.`

The examples under https://developers.google.com/web/tools/workbox/modules/workbox-routing should correspond to that syntax.
