### ISSUE TITLE
Redirect to the offline page when the page is not in cache

### ISSUE THREAD

**Issue by robertofd1995** [GoogleChrome/workbox#1537]
**Library Affected**:
workbox-routing, workbox-precaching

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
In case of not having network and the user arrives to a page that is not cached, send the page an offline page that it was precached in the beginning.

I have been playing around with the library since some days, and thanks in advance for the work done with the library, for someone newby to PWA like me it has done the work easier.

But I found that the library is missing or at least I didn't find any way to redirect the user to an offline page in case the user goes into a page without internet and that page is not cached.

I have try this : 

``` javascript
workbox.routing.registerRoute(
  ({ event }) => event.request.mode === 'navigate', //if the requests is to go to a new url
  ({ url }) => fetch(url.href,{credentials: 'same-origin'}).catch(() => caches.match('/offline')) //in case of not match send my to the offline page
);
```

I also open a [question in stackoverflow](https://stackoverflow.com/questions/50901503/service-worker-does-my-web-slower-how-to-add-offline-capabilities-to-django-w)

How I could archive this? 

I think is a really must, It will be really cool if in a future this feature could be active in the following way

```javascript
workbox.precaching.precacheAndRoute(
  [
    '/',
    '/offline',
  ],
  {
    offlinePage: '/offline', //<- in case of getting offline and not have cache content , redirect here
  }
);
```

Thanks in advance

**Comment by jeffposnick** [comment]
Adding this to Workbox core is tracked in https://github.com/GoogleChrome/workbox/issues/438, but it hasn't been prioritized. I'm closing this in favor of that issue.

We have a general recipe at https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route that describes one approach, and there is further discussion in that other issue thread.
