### ISSUE TITLE
Is the staleWhileRevalidate() strategy compatible with a "native" stale-while-revalidate?

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/workbox#1538]
**Library Affected**:

workbox-sw

**Issue or Feature Request Description**

It seems Chrome is on the verge of enabling support for [stale-while-revalidate](https://bugs.chromium.org/p/chromium/issues/detail?id=348877). Is workbox's   `staleWhileRevalidate()` strategy compatible with this?

That is, if workbox caching + `staleWhileRevalidate()` is enabled and resources are served with a stale-while-revalidate cache-control header, does the behavior conform to [RFC5861](https://tools.ietf.org/html/rfc5861#section-3)?

**Comment by jeffposnick** [comment]
The "revalidation" step is treated by Workbox in the same way that we treat the network step of any other strategy (i.e. network-first, a cache miss for cache-first, etc.): under the hood, a `fetch()` request is made. That `fetch()` will, by default, honor the HTTP cache control settings, and I assume it would honor the behavior that ends up being implemented in Chrome w.r.t. stale-while-revalidate.

Developers who want to override that behavior can specify a different [cache mode](https://fetch.spec.whatwg.org/#concept-request-cache-mode) when they create a strategy, and this will be passed through to the underlying `fetch()` call.

So... that's how things behave right now. Do you have any concerns with that, based on how you anticipate developers using native stale-while-revalidate support in the future?

**Comment by ithinkihaveacat** [comment]
Thanks. I don't think I stated my question very well. To put it another way: if a site is using workbox's `staleWhileRevalidate()`, will it break in unfortunate ways once browsers support `stale-while-revalidate`? And from your answer, and reading the source code, the answer is no.

The reason is that workbox's implementation is equivalent to `max-age: 0, stale-while-revalidate: Infinity`: (1) cached content is always returned (if available); and (2) a revalidating network request is always performed. And this overrides whatever the cache-control headers say.

So browser support for `stale-while-revalidate` may change the number and timing of requests that go over the network, but the guarantees are preserved.

(I think it could be a problem if workbox's behavior was configurable though. If for example workbox's behavior was equivalent to e.g. `max-age: 0, stale-while-revalidate: 10` then problems could occur if the cache-control header was `max-age: 0, stale-while-revalidate: 60`. In this case you might expect fresh content if a resource was 20 seconds old, but the network cache would instead return cached content.)
