### ISSUE TITLE
workbox wizard hangs on Windows after the first step

### ISSUE THREAD

**Issue by ConnorPoort** [GoogleChrome/workbox#1542]
I am setting up a PWA and trying to add a Service Worker using Work Box. When I type 'Workbox Wizard' in to the terminal, only the first question about the root file is being asked and then the terminal freezes and I can't type anything else. Please help!

**Library Affected**:
*workbox-sw*

**Steps already taken**

Uninstalled and reinstalled the workbx cli, uninstalled and reinstalled NodeJS entirely, restarted computer several times
![screenshot_2](https://user-images.githubusercontent.com/40454828/41707322-1e076596-753e-11e8-8801-ecc6d026db0f.png)

**Comment by jeffposnick** [comment]
Using `workbox-cli@alpha` on `npm` should pick up our 4.0.0 alpha releases now, which contain a fix.

Feel free to [read the release notes](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0) and confirm that it's working for you know.

**Comment by rhroyston** [comment]
I encountered this running Node v8.1.0. Using nvm, I switched to Node v8.9.0 and issue was resolved.

```
		nvm install v8.9.0
		nvm alias default v8.9.0
```

**Comment by newschapmj1** [comment]
I have the same issue on Windows 10 [Version 10.0.18290.1000] & Node v10.13.0
workbox-cli v3.6.3

**Comment by jeffposnick** [comment]
@newschapmj1 You should be able to work around this by opting-in to the current v4 beta, via

```
npm install -g workbox-cli@beta
```

**Comment by newschapmj1** [comment]
Thanks, I  made progress using v4 beta

**Comment by jlchereau** [comment]
I have the same issue on Windows 10.0.17763 + Node v11.6.0 + workbox-cli v3.6.3
Using Bash on Unbuntu on Windows with nodeJS v8 works around it.

**Comment by furoTmark** [comment]
I also have the same issue on Windows 10.0.17763 + Node v10.15.0 + workbox-cli v3.6.3.
Opting-in and installing the current v4 beta made it work.

**Comment by philipwalton** [comment]
I'm closing this issue, as it should be fixed in v4. If you're still seeing this issue while using any of the v4 beta versions, please let us know!
