### ISSUE TITLE
Provide a CDN-free path to basic workbox usage

### ISSUE THREAD

**Issue by alirobe** [GoogleChrome/workbox#1544]
**Library Affected**:
documentation

**Issue or Feature Request Description**:

I want to try using Workbox on some projects where I can't be deploying any code that references external CDNs due to security constraints.

Please provide paths to implementing workbox that don't require importScripts from third party servers.

**Comment by jeffposnick** [comment]
There are a few options:

- If you are manually writing your service worker, and you want a local copy of the Workbox libraries, you can either install `workbox-cli` and run `workbox copyLibraries <path/to/dir>` or alternatively, download them from our [release pages](https://github.com/GoogleChrome/workbox/releases/tag/v3.3.0) as a `.zip` archive. Once you do that, you need to call `workbox.setConfig({modulePathPrefix: 'path/to/local/workbox'})` (as described in [this issue](https://github.com/GoogleChrome/workbox/issues/1541#issuecomment-398844805)) to ensure that all of the runtime imports happen from your local directory.

- If you are using `generateSW` via one of our build tools, you can set `importWorkboxFrom: 'local'`, and the build tool will take care of making a local copy of all the libraries and calling `workbox.setConfig({modulePathPrefix: 'path/to/local/workbox'})` on your behalf.

**Comment by alirobe** [comment]
@jeffposnick thanks. Will this be included on any official documentation? (that's what the issue was requesting)
