### ISSUE TITLE
globDirectory option seems required when using templatedUrls in InjectManifest

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/workbox#1546]
**Library Affected**:
workbox-webpack-plugin

**Issue or Feature Request Description**:
If I use templatedUrls option in InjectManifest, but do not provide globDirectory, I get an error:

Error: An error occurred when globbing for files. 'Path must be a string. Received undefined'

Webpack config:

```
const { InjectManifest } = require('workbox-webpack-plugin');

module.exports = {
  entry: {
    main: './src/client/js/app.js',
  },
  output: {
    filename: 'js/[name].js',
    chunkFilename: 'js/chunk-[name].js',
    path: path.resolve(__dirname, 'dist/static'),
  },
  plugins: [
    new InjectManifest({
      swSrc: './src/sw.js',
      // globDirectory: 'dist/static',
      templatedUrls: {
        '/shell': ['../templates/layouts/layout.hbs']
      },
    })
  ]
};
```

If I uncomment globDirectory (which is the same as webpack output root in this case), it works. 

It caught me off guard. Maybe its wort adding this in the doc for templatedUrls here: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#injectmanifest_plugin_1
The doc says it will be treated as glob patterns but I did not connect it with globDirectory option being required at first.

**Comment by devnook** [comment]
Ah, I should have done better job searching through issues then! :) Still, this is mainly a request to add documentation.

**Comment by jeffposnick** [comment]
(Part of the plan for v4 is to take these `glob`-specific options and extend them so that they can be used for `webpack` assets via a different config key.)
