### ISSUE TITLE
InjectManifest doing wrong path concatenation

### ISSUE THREAD

**Issue by AjayPoshak** [GoogleChrome/workbox#1548]
I have my build files generated in client and server folders.  So in client folder, precache-manifest.[hash].js generates path which does not have proper concatenation.

Generated precache-manifest
```js
self.__precacheManifest = [
  {
    "url": "build/clientvendors.e98cd1bb4b8ceed410d1.js.br"
  },
  {
    "url": "build/clientvendors.e98cd1bb4b8ceed410d1.js"
  },
  {
    "url": "build/clientmain.a71bb22a243e3527c9ad.js.br"
  },
  {
    "url": "build/clientmain.a71bb22a243e3527c9ad.js"
  },
  {
    "revision": "2bc046cfe001200837730844bac2fa50",
    "url": "build/clientindex.html"
  }
];
```
It should have slash('/') after client. My build folder structure is as follows

build
|-- client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- manifest.[hash].js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- vendors.[hash].js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- main.[hash].js  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- precache-manifest.[hash].js

**Library Affected**:
InjectManifest in workbox-webpack-plugin

**Issue or Feature Request Description**:
Correct precache-manifest.[hash].js would be

```js
self.__precacheManifest = [
  {
    "url": "build/client/vendors.e98cd1bb4b8ceed410d1.js.br"
  },
  {
    "url": "build/client/vendors.e98cd1bb4b8ceed410d1.js"
  },
  {
    "url": "build/client/main.a71bb22a243e3527c9ad.js.br"
  },
  {
    "url": "build/client/main.a71bb22a243e3527c9ad.js"
  },
  {
    "revision": "2bc046cfe001200837730844bac2fa50",
    "url": "build/client/index.html"
  }
];
```

**Comment by jeffposnick** [comment]
What are the `output.path` and `output.publicPath` options that you're using in your webpack configuration?

**Comment by asgouros** [comment]
Same issue here. No `/` after output path (`dist` instead of `dist/`)

Webpack output options: 
```       
output: {
    devtoolModuleFilenameTemplate: 'webpack:///[absolute-resource-path]',
    filename: '[name].js',
    path: path.join(__dirname, 'dist/'),
    publicPath: '/dist/',
    libraryTarget: 'this'
},
```
workbox-webpack-plugin configuration:
```
    new WorkboxPlugin.GenerateSW({
        clientsClaim: true,
        skipWaiting: true
    }),
```

Generated service-worker.js
```
importScripts(
  "/distprecache-manifest.e4cf780c5a66f076d7e345d363024c44.js"
);
```

Generated prechache-manifest file: 
```
self.__precacheManifest = [
   {
    "url": "/distjs/appInit.d3c02bfdc63eb4365962.js"
  },
  ...
```

**Comment by jeffposnick** [comment]
Re: @AjayPoshak, as per the [webpack documentation](https://webpack.js.org/configuration/output/#output-publicpath), the `publicPath` value is meant to be a string prefix that is prepended to each webpack asset URL in order to get the final, effective public URL.

Because the string is a prefix, there is no implicit `/` separators inserted in between the `publicPath` value and the URLs that are included in the precache manifest. Going back to the docs:

> The value of the option is prefixed to every URL created by the runtime or loaders. Because of this the value of this option ends with / in most cases.

Using `publicPath: 'build/client/'` in your webpack config seems like it would work around the issue.
