### ISSUE TITLE
Uncaught TypeError: quota_mjs.registerCallback is not a function

### ISSUE THREAD

**Issue by xe21500** [GoogleChrome/workbox#1549]
**Library Affected**:
*workbox-cache-expiration*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:

Hi,

I'm trying to use the new `purgeOnQuotaError` option but I'm getting the following console error:

![image](https://user-images.githubusercontent.com/24647195/41841371-620d97e2-7868-11e8-89f8-94077e3b71b9.png)

Looking at the [PR](https://github.com/GoogleChrome/workbox/pull/1505/files#diff-1096e1c07882fffbc045bb49452cc04f) of the change seems that the import is done from the `workbox-core/_private/quota.mjs` file directly, but while debugging the method seems that the iife ran passing the code `workbox-core/_private.mjs`, as you can see the `quota_mjs` object having the `registerQuotaErrorCallback` function but not the other one. I'm not familiar with the compilation process, so I don't really know where that module comes from or if I'm doing something wrong myself.

I'm using workbox 3.3.0 and generating the SW file with the `generateSW` entry point. Thank you!

**Comment by jeffposnick** [comment]
Sorry—this is fixed by #1552, and should make it into an upcoming `v3.3.1` release.

**Comment by rejhgadellaa** [comment]
@salmoro #metoo

**Comment by salmoro** [comment]
I've created #1642 issue to track this.
