### ISSUE TITLE
Is there a API for workbox monitoring error in service workers ?

### ISSUE THREAD

**Issue by mengxiangrui** [GoogleChrome/workbox#1555]
i use workbox webpack plugin [GenerateSW](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin), i want to monitoring error in service workers and report，but i can not find the API in the config doc。

**Comment by jeffposnick** [comment]
There's nothing in Workbox related to error monitoring or reporting.

I'm not sure exactly what you're looking for—whether there's an existing service that you want to hook into or what—but in general, if you've got your own code that you'd like run in your service worker and you're using `GenerateSW`, your best bet is to put that code into its own file, and then add it to the `importScripts: ['url/for/your/file.js']` configuration option. That will result in the file being pulled into the generated service worker and executed, via [`importScripts()`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts).
