### ISSUE TITLE
Uncaught TypeError: Cannot read property 'put' of undefined

### ISSUE THREAD

**Issue by DanJ210** [GoogleChrome/workbox#1558]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Chrome 67.0.3396.99

I'm using the getting started docs here, [workbox getting started](https://developers.google.com/web/tools/workbox/guides/get-started), and using the code to route and cache any file with `.js` in it. I'm getting the console logs shown in the docs of `Router responding to:` and `Using NetworkFirst to respond to` but I'm getting tons of `uncaught (in promise) TypeError: Cannot read property 'put' of undefined`. `The file is workbox-core.dev.js:955`. I have no idea what I'm doing wrong as I'm just following the very first guide exactly. There is no cache being created either.

I searched for this issue first but didn't find anything.

```
workbox.routing.registerRoute(
	new RegExp('.*\.js'),
	workbox.strategies.networkFirst()
);
```

**Comment by jeffposnick** [comment]
Sorry that you're running into issues.

That line of code corresponds to https://github.com/GoogleChrome/workbox/blob/27b8f383405ce0528227ed0c77371ec8a68e7c22/packages/workbox-core/_private/DBWrapper.mjs#L130-L132

but that ends up being used in a variety of places. Are there any more entries in the error message with additional lines of code? That would help point to where the `DBWrapper` instance is being used.

Also, a few other things: are you using the latest `3.3.1` release of Workbox? And can you reproduce the issue if you start in a Chrome Incognito window?

**Comment by DanJ210** [comment]
I'll have to check version and see if the issue persists incognito and then I'll report back. I'll also collect anymore info with the error messages.

Would it help pinpoint to know that it's one of the first pieces of code in the docs I linked? The header "Using Workbox" has us put together a method with two lines of code in it. Could that pinpint what `DBWrapper` instance is being used?

**Comment by jeffposnick** [comment]
I'm going to close this for now—please ping the issue if you were able to reproduce as described above, and we can revisit.

**Comment by DanJ210** [comment]
@jeffposnick Ok if I try to learn the tool again. I never got past the first two lines in the docs so I was hoping that the docs could pinpoint the info you were looking for.

I was just following the docs so I'm not sure what I could have done differently.
