### ISSUE TITLE
workbox-sw: Google fonts not rendering when fully offline

### ISSUE THREAD

**Issue by caleb531** [GoogleChrome/workbox#1563]
**Library Affected**:
*workbox-sw* (v3.3)

**Browser & Platform**:
*Google Chrome on macOS High Sierra (10.13.5)*

**Issue or Feature Request Description**:

(Repository to reproduce: https://github.com/caleb531/workbox-google-font-bug)

I am using Workbox's `workbox-sw` library to create a small service worker. I am trying to create a fully offline application, including serving my Google fonts when offline.

## TL;DR

My Google fonts are not rendering offline because (for whatever reason) the font CSS is not cached by my service worker, though the font files are. This is preventing my Google fonts from rendering fully offline.

### Long Story

I add the routing for Google fonts [exactly as the homepage describes](https://developers.google.com/web/tools/workbox/):

```js
 workbox.routing.registerRoute(
  new RegExp('^https://fonts.(?:googleapis|gstatic).com/(.*)'),
  workbox.strategies.cacheFirst(),
); 
```

The CDN-served font files appear to be cached by my service worker, but not the CDN-served CSS. This is apparent when I activate Offline mode in the DevTools Network panel.

**Network when online:**  
![Network when online](https://user-images.githubusercontent.com/872474/42139886-f1182e20-7d4a-11e8-80d3-81d7e58d1ba1.png)

**Network when offline:**  
(notice the font failed to render):  
![Network when offline](https://user-images.githubusercontent.com/872474/42139888-f1311016-7d4a-11e8-97f0-50badf52b523.png)

**Workbox debug in console:**  
(notice the font failed to render):  
![Workbox debug in console](https://user-images.githubusercontent.com/872474/42139890-f163ff8a-7d4a-11e8-84ae-29cc9f5ff891.png)

My only suspicion is that this has to do with the `private` setting in the `Cache-Control` header for the CSS only (the fonts are `public`).

**Google Font CSS response:**  
![Google Font CSS response](https://user-images.githubusercontent.com/872474/42139889-f14a98a6-7d4a-11e8-947e-48ee502ebf44.png)

Is this a bug? *Is* Workbox honoring `cache-control: private`? What can be done about this? It's the only obstacle keeping me from serving my app fully offline.

Thanks,
Caleb

P.S. Here's the HAR file too if it helps: [localhost.har.zip](https://github.com/GoogleChrome/workbox/files/2153332/localhost.har.zip)

**Comment by jeffposnick** [comment]
The `Cache-Control: private` doesn't come into play here.

The issue is almost certainly that the original CSS request was non-CORS, and that leads to an [opaque response](https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests#cross-origin_requests_and_opaque_responses), which isn't cached when using a cache-first strategy by default.

We have a [recipe](https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts) specifically for dealing with this; here's a copy of it:

```js
workbox.routing.registerRoute(
  new RegExp('https://fonts.(?:googleapis|gstatic).com/(.*)'),
  workbox.strategies.cacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 30,
      }),
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200]
      }),
    ],
  }),
);
```

**Comment by caleb531** [comment]
@jeffposnick Thanks, that worked perfectly. I would ask that you please update the [Google Fonts homepage example](https://developers.google.com/web/tools/workbox/) to match the recipe you gave, because it's otherwise misleading.

<img width="879" alt="screen shot 2018-07-02 at 8 35 41 pm" src="https://user-images.githubusercontent.com/872474/42197429-9f650434-7e37-11e8-9532-d8c27c831611.png">

**Comment by jeffposnick** [comment]
Ah, thanks for catching that!
