### ISSUE TITLE
InjectManifest Plugin: Generate manifest url based on config instead of webpack public path

### ISSUE THREAD

**Issue by sdad120** [GoogleChrome/workbox#1565]
**Library Affected**:
workbox-webpack-plugin

**Issue or Feature Request Description**:
We have different cdn domain based on different country. Webpack provide a [variable](https://webpack.js.org/guides/public-path/#set-value-on-the-fly) to override the public path in client(browser).

However, when we try to use workbox to generate different sw.js for different cdn domain. We found it only support config the cdn domain for chunks in precache-manifest.js by manifestTransforms but we can't config the cdn domain of precache-manifest.js itself because [workbox generate the url of it by webpack public path.](https://github.com/GoogleChrome/workbox/blob/22b855df190e7272ed13f20425a057f089e00314/packages/workbox-webpack-plugin/src/inject-manifest.js#L114-L116)

Could we add some config to support define cdn domain of precache-manifest.js?
For example,
```
importScriptsArray.push((this.config.publicPath || compilation.options.output.publicPath || '') +
  pathToManifestFile.split(path.sep).join('/'));
```

**Comment by jeffposnick** [comment]
Does the [`importsDirectory` option](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#injectManifest-importsDirectory) help here?

https://github.com/GoogleChrome/workbox/blob/27b8f383405ce0528227ed0c77371ec8a68e7c22/packages/workbox-webpack-plugin/src/inject-manifest.js#L110-L111

**Comment by sdad120** [comment]
No I think, what I want to change is `publicPath` not relative path. We don't want to rely on webpack options.

Like the default publicPath of our webpack configuration is `a.cdn.com/static/` but we want to use `b.cdn.com/static/` to importScripts.

**Comment by sdad120** [comment]
Actually, the `precacheManifest` is not the only thing in workbox to use the publicPath option of the webpack to generate importScripts url.
If I set local for importWorkboxFrom, the plugin will generate js to import `workbox-sw` also from the publicPath.
https://github.com/GoogleChrome/workbox/blob/a816ad266fab093c07e3a317d8632d69612c474f/packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js#L49

**Comment by jeffposnick** [comment]
`workbox-webpack-plugin` can't default to ignoring the configured `publicPath`, as there are developers out there who expect it to be prefixed to all of their URLs (which I think is the intended use case, as per the webpack docs).

The next major release of `workbox-webpack-plugin` is likely to include a complete rethink of the supported options, including ways of transforming the entries in the generated precache manifest. I think that flexibility should at least give folks in a similar situation the flexibility that they would need to override the defaults.

**Comment by jeffposnick** [comment]
This should be addressed in workbox-webpack-plugin v5. If you need to make any translations to the URL prefixes, you can either use the modifyURLPrefix or manifestTransforms configuration options.
