### ISSUE TITLE
Installation errors on legacy browsers

### ISSUE THREAD

**Issue by edgaraskazlauskas** [GoogleChrome/workbox#1567]
It seems that the production builds of workbox v3.3.0 break on older browser versions. I give an example for Chrome v49 as it shows the error clearly but I noticed that quite a few older browsers (especially mobile) do not register the service worker due to some error, the generic message is `Failed to register a ServiceWorker: ServiceWorker script evaluation failed`. I assume it's a compatibility thing as the up to date browser versions don't throw these errors. 

The current guideline is to check if there is `'serviceWorker' in navigator`, but if we want to avoid those errors and skip registering the service worker on devices it will not be supported on, we likely need additional checks for various ECMAScript features (if my assumption is correct).

How can we handle the prevention of registering service workers on workbox unsupported browsers on our side?

`workbox-sw.js:1Unable to import module 'workbox-precaching' from 'js/workbox-v3.3.0/workbox-precaching.prod.js'.loadModule @ workbox-sw.js:1get @ workbox-sw.js:1(anonymous function) @ sw.js:3(anonymous function) @ sw.js:3
workbox-precaching.prod.js:1 Uncaught SyntaxError: Unexpected token in`

**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
* Google Chrome, Version 49.0.2623.75 (64-bit), MacOS*

**Issue or Feature Request Description**:
*Browser support check guidelines.*

**Comment by jeffposnick** [comment]
Our browser support policy is [as follows](https://github.com/GoogleChrome/workbox/wiki/Browser-Support):

> Chrome, Firefox, Safari, Edge: latest version - 2
> Chromium based browsers (Samsung internet browser, Opera etc): latest version - 2 (as long as >= version 50)

We use `babel-preset-env` to achieve that compatibility.

I'm afraid that we don't specifically provide guidance for checking as to whether you're on a supported browser or not.

(I know that you're asking more about detecting compatibility than finding something that works with older browsers, but if you did need a library that might work with older versions of Chrome, https://github.com/GoogleChromeLabs/sw-precache is an option.)
