### ISSUE TITLE
Option to use workbox.googleAnalytics in workbox-cli

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/workbox#1568]
**Library Affected**:
workbox-cli

For now, I think I could just tack onto the generated sw.js, but it would be nice to have this case handled via the CLI.

**Comment by jeffposnick** [comment]
(Presumably, if we went ahead with this, it would be an option added to the underlying `workbox-build.generateSW()` method, which is what the `workbox-cli` calls under the hood.)
