### ISSUE TITLE
caching object element source ( SVG ) 

### ISSUE THREAD

**Issue by Beppe** [GoogleChrome/workbox#1569]
**Library Affected**:
workbox-sw

**Browser & Platform**:
"all browsers".

**Issue or Feature Request Description**:
Is there a way to cache SVG files used as object element data source?

`<object data="xxxxxx.svg" type="image/svg+xml" id="logoImg" class="xxxxxxx-img"></object>`

What I want is a working offline interactive SVG (having javascript inside a script node of it's own).

**Comment by jeffposnick** [comment]
The [service worker specification recommends](https://w3c.github.io/ServiceWorker/#implementer-concerns) that browsers bypass the service worker's `fetch` handler when fulfilling requests originating from `<object>` (or `<embed>`) tags.

> Plug-ins should not load via service workers. As plug-ins may get their security origins from their own urls, the embedding service worker cannot handle it. For this reason, the Handle Fetch algorithm makes the potential-navigation-or-subresource request (whose context is either `<embed>` or `<object>`) immediately fallback to the network without dispatching fetch event.

There's nothing that Workbox could do to change that.

If you changed your HTML and [loaded the SVG using an `<img>` tag](https://css-tricks.com/using-svg/#article-header-id-2), then the service worker (and by extension, Workbox) would have a chance to respond.

**Comment by madsenfr** [comment]
Is this remark still valid in 2021 ?
Because when SVG is used with `<img>` instead of `<object>`, DOM is not reachable.

**Comment by jeffposnick** [comment]
I'm not aware of any plans to change that recommendation in the service worker specification.
