### ISSUE TITLE
Workbox caches excluded html

### ISSUE THREAD

**Issue by DmitryVolkovTulaco** [GoogleChrome/workbox#1576]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Workbox-webpack-plugin caches html files unless I'm excluding them.
Previously using sw-precache-plugin I just wrote

```js
new SWPrecacheWebpackPlugin({
  dontCacheBustUrlsMatching: /\.\w{8}\./,
  filename: 'service-worker.js',
  minify: true,
  navigateFallback: '/index.html',
  staticFileGlobsIgnorePatterns: [/\.map$/, /asset-manifest\.json$/, /index\.html$/],
})
```

but it doesn't work for workbox

```js
new GenerateSW({
  cacheId: 'my-app-name',
  importWorkboxFrom: 'local',
  skipWaiting: true,
  clientsClaim: true,
  navigateFallback: '/index.html',
  exclude: [/\.map$/, /^manifest.*\.js(?:on)?$/, /\.html$/],
})
```

There are no html files in resulting manifest file but in browser html fetches from service worker anyway.

**Comment by shdq** [comment]
Hey,
Could you show generated service-worker.js please?
I think in precache stage there is no your root page, but when you moving through your app, service-worker fill your cache with additional assets and your root page during fetch event.

**Comment by DmitryVolkovTulaco** [comment]
@shdq my precache-manifest:

`self.__precacheManifest = [`
`  {`
 `   "revision": "ec353ff7be25b0aa6696758ca6b271d7",`
`    "url": "favicon.ico"`
 ` },`
  `{`
  `  "url": "app-e9b1ff373072ac060046.js"`
  `},`
  `{`
 `   "url": "1-e9b1ff373072ac060046.js"`
`  },`
`  {`
`    "url": "1-e9b1ff373072ac060046.css"`
`  },`
`  {`
`    "url": "0-e9b1ff373072ac060046.js"`
`  }`
`];`

and service-worker.js 

`importScripts("workbox-v3.4.1/workbox-sw.js");`
`workbox.setConfig({modulePathPrefix: "workbox-v3.4.1"});`

`importScripts(`
`  "precache-manifest.374b197dcffb52820d81553d4eb71746.js"`
`);`

`workbox.core.setCacheNameDetails({prefix: "my-app-name"});`

`workbox.skipWaiting();`
`workbox.clientsClaim();`

`self.__precacheManifest = [].concat(self.__precacheManifest || []);`
`workbox.precaching.suppressWarnings();`
`workbox.precaching.precacheAndRoute(self.__precacheManifest, {});`

`workbox.routing.registerNavigationRoute("/index.html");`

**Comment by DmitryVolkovTulaco** [comment]
@shdq removing navigateFallback: '/index.html', from config fixes an issue

**Comment by jeffposnick** [comment]
Right—in general, you shouldn't use `navigateFallback: '/index.html'` in your config unless you expect that file to be cached.

What you're seeing is expected, so I'm going to close this. If you have any concerns, or would suggest alternative behavior, please chime in and we can reconsider.
