### ISSUE TITLE
Why am I getting a warning about using glob* options?

### ISSUE THREAD

**Issue by leonaves** [GoogleChrome/workbox#1578]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
The webpack plugin seems to warn whenever you use any `glob*` options, and there's no way to turn it off? I don't want warnings in my console telling me the options I'm using are usually unnecessary when I know that they are.

**Comment by jeffposnick** [comment]
Apologies for the noise. We're planning on doing something along the lines of https://github.com/GoogleChrome/workbox/issues/1380#issuecomment-375757558 to address this—feel free to follow that issue for updates.
