### ISSUE TITLE
InjectManifest Plugin: it adds new lines of importScripts on top of the service-worker file after each webpack rebuild

### ISSUE THREAD

**Issue by shdq** [GoogleChrome/workbox#1579]
**Library Affected**:
workbox-webpack-plugin

**Issue**:
I generate precache manifest with plugin to inject in custom service worker with this webpack config:

```
    new InjectManifest({
      swSrc: './dist/sw.js',
      importWorkboxFrom: 'local'
    })
```
After each webpack rebuild it adds new lines with importScripts on top of the sw.js and empty lines  to end like this:
```
importScripts("precache-manifest.e3d372f129cb6b7b5427c8b7ef0cd62d.js", "workbox-v3.4.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "workbox-v3.4.1"});
importScripts("precache-manifest.9246066757e2c4189939a0229d04b162.js", "workbox-v3.4.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "workbox-v3.4.1"});
importScripts("precache-manifest.9246066757e2c4189939a0229d04b162.js", "workbox-v3.4.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "workbox-v3.4.1"});
```
Should it replace previous lines of importScripts with new ones?

**Comment by jeffposnick** [comment]
Apologies for the problems you're running into. The intention is that the `swSrc` and `swDest` should not be the same file.

It's unfortunately a bit tricky to enforce this, but there is more info in these two issues:

- https://github.com/GoogleChrome/workbox/issues/1495
- https://github.com/GoogleChrome/workbox/issues/1363

I'm going to close this issue in favor of following up in one of those.
