### ISSUE TITLE
missing possibility to apply modifyUrlPrefix or manifestTransforms to all automatically added assets as well

### ISSUE THREAD

**Issue by antony-k1208** [GoogleChrome/workbox#1580]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all platforms*

**Issue or Feature Request Description**:
We are currently stumbling upon a problem with this automatic generation of a precache manifest that contains URLs for assets created by the current webpack compilation. This is all fine, but the entries urls are totally unusable for our setup. It seems workbox-webpack-plugin is using webpacks **output.path** setting followed by other options made inside our **webpack.config**.

What we get is something like this:

```
{
    "revision": "51b9703cbbf90b6ca05a1b58e4e85051",
    "url": "../fonts/daxot-condbold-webfont.ttf"
  }
```

What we need is a possibility to apply something like the provided options **modifyUrlPrefix** or **manifestTransforms** which will also be applied to this automatic generation as well and not only to additional assets in order to get something like this:

```
{
    "revision": "51b9703cbbf90b6ca05a1b58e4e85051",
    "url": "ui/theme/fonts/daxot-condbold-webfont.ttf"
  }
```

With **gulp** and **workbox-build** we were able by using *globDirectory*, *globPatterns* and *manifestTransforms* to achieve exactly that behaviour.

Any help would be gladly appreciated.

Regards,
Antony

**Comment by jeffposnick** [comment]
Thanks, Antony.

That's planned for the next major release of `workbox-webpack-plugin`, and tracked in https://github.com/GoogleChrome/workbox/issues/1227
