### ISSUE TITLE
Auto-Generated import for precache-manifest pointing to the wrong location

### ISSUE THREAD

**Issue by antony-k1208** [GoogleChrome/workbox#1581]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all platforms*

**Issue or Feature Request Description**:
Currently the generated precache manifest will be included automatically in the generated service worker via **importScripts**. 

There is no option to specify which path it is using. Our production environment is quite different, so we get something like: 

`importScripts("../../../../precache-manifest.f2ad02297cbb47cee50795faa3bfee28.js", "https://storage.googleapis.com/workbox-cdn/releases/3.4.1/workbox-sw.js");`

but what we need is:

`importScripts("ui/theme/precache-manifest.f2ad02297cbb47cee50795faa3bfee28.js", "https://storage.googleapis.com/workbox-cdn/releases/3.4.1/workbox-sw.js");`

As far as i can tell there is currently no such option. With **gulp** and **workbox-build** we could just use the **injectManifest** function and in the service worker source file define an empty array, which got automatically filled by all prechachable files:

`workbox.precaching.precacheAndRoute([],
        {
            cleanUrls: false
        });`

after:

`workbox.precaching.precacheAndRoute([
{
    "revision": "51b9703cbbf90b6ca05a1b58e4e85051",
    "url": "ui/theme/fonts/daxot-condbold-webfont.ttf"
  },
  ...
],
        {
            cleanUrls: false
        });
`

With this automatic generation of a precache manifest as extra file, we are sadly confronted with the described issue.

**Comment by jeffposnick** [comment]
Does the [`importsDirectory` option](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generateSW-importsDirectory) help you accomplish what you're trying to do?

**Comment by antony-k1208** [comment]
Hi jeff,
thanks for your feedback. Yeah i see what you mean. I was using that option already but i read this as possibility to change the path of the file creation. Now im using webpack for copying that files over and its working as we need it.
