### ISSUE TITLE
Webpack workbox plugin doesn't cache all required scripts.

### ISSUE THREAD

**Issue by patrykbilka** [GoogleChrome/workbox#1582]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
Hi. I don't know if this is an issue. Documentation of webpack-worbox plugin is telling me that I don't need to specify which files I want to cache. So my webpack config is following:

`  
new CopyWebpackPlugin([
      { from: './src/manifest.json' },
      { from: './src/assets/homescreen', to: 'assets/homescreen/' }
    ]),
    new WorkboxPlugin.GenerateSW({
      globPatterns: ['dist/*.{js,png,html,css,json}'],
      globStrict: true,
      clientsClaim: true,
      skipWaiting: true
    }),`

Copy-webpack plugin copies my manifest.json, and homescreen assets to `dist` directory. After build, I also copy 'env.config.js' file to dist (this file contains API urls). However, manifest.json, service-worker.js and env.config.js files aren't precached. My precache-manifest file only contains index.html,style.css, splitted routes, bundle and vendor. I tried also this very basic config for plugin:
`    new WorkboxPlugin.GenerateSW({
      clientsClaim: true,
      skipWaiting: true
    }),`
But it doesn't work too. My question is - how can I precache also manifest.json, service-worker.js and env.config js files which are necessary for my application to work offline?

**Comment by patrykbilka** [comment]
I think I got the solution for this. I don't know if it is the proper way for caching additional assets.

My manifest.json and env.config.js files are non webpack assets. I handled cache for them using runtime caching:
`
    new WorkboxPlugin.GenerateSW({
      clientsClaim: true,
      skipWaiting: true,
      runtimeCaching: [
        {
          urlPattern: new RegExp('/'),
          handler: 'staleWhileRevalidate',
        },
      ],
    }),
`
I hope this will help someone.

In other hand - is this a proper way for handling non webpack assets using workbox?

**Comment by jeffposnick** [comment]
Is `manifest.json` your [web app manifest](https://developers.google.com/web/fundamentals/web-app-manifest/)? If so, when the browser makes a request for it it bypasses the service worker's `fetch` handler, so you don't accomplish anything by explicitly caching it.

Same for the `service-worker.js` file, which is cached automatically for you as required by the service worker specification.

But if you have an `env.config.js` file that's not a webpack asset, and you also want that to be precached, you can follow the "[Cache additional, non-webpack assets](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#cache_additional_non-webpack_assets)" section of the docs to learn about configuring the plugin's `glob` related options, along with the limitations there.

Using runtime caching is another option—both will work, but have different guarantees around when the asset will get updated.
