### ISSUE TITLE
Add documentation on how to use workbox-{build,cli} without your CDN

### ISSUE THREAD

**Issue by surma** [GoogleChrome/workbox#1585]
**Library Affected**:
README / Documentation

**Issue or Feature Request Description**:
I am using rollup and I’d like to bundle workbox so I can treeshake it. What’s the path to achieving that? It seems that the CLI and workbox-build inject an `importScripts` statement that pulls workbox from a CDN instead of using an `import` statement.

**Comment by surma** [comment]
Additionally, the `workbox-sw` package seems to be mostly auto-loading magic and doesn’t actually pull in the stuff I am using.

**Comment by jeffposnick** [comment]
Hey @surma! You can accomplish that by setting `importWorkboxFrom: 'disabled'` in your configuration, as explained at https://developers.google.com/web/tools/workbox/modules/workbox-build#generateSW-importWorkboxFrom

I'm CC:ing @philipwalton as he's been the one who's experimented the most with custom builds of Workbox by bundling the `.mjs` exports, and he might have some specific advice.

**Comment by jeffposnick** [comment]
This will be included as part of the Workbox v4 docs—the relevant PR is https://github.com/google/WebFundamentals/pull/7183.

I believe @philipwalton will be adding the bundling guidance there within the next week, and it's hard to coordinate issues across repos, so I'm going to close this in the meantime.
