### ISSUE TITLE
Preload header needed or not with Workbox?

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1586]
Very quick question, the following webpage: https://developers.google.com/web/updates/2017/02/navigation-preload

Says to add a header:

`Vary: Service-Worker-Navigation-Preload`

Just want to double check if this is needed with Workbox v3.4.1 Peloading setup's or not?

Thanks and Congrats with all the wonderful things this project has achieved.

**Comment by jeffposnick** [comment]
Just for a little more context, the full quote from [that page](https://developers.google.com/web/updates/2017/02/navigation-preload) is:

> The server can use this to send different content for navigation preload requests than it would for a regular navigation request. Just remember to add a `Vary: Service-Worker-Navigation-Preload` header, so caches know that your responses differ.

That still applies *if* your server plans on sending different response content for preload navigations vs. non-preload navigations.

That's a fairly advanced use case, so I'd imagine that for most cases (in which you just use the same HTML for both preload and non-preload responses) it's not needed. But if you are sending different content, then having your server include that header could be a good idea.
