### ISSUE TITLE
runtimeCaching does not cache without options

### ISSUE THREAD

**Issue by sime** [GoogleChrome/workbox#1593]
**Library Affected**:
*workbox-webpack-plugin@3.4.1*

**Browser & Platform**:
*Google Chrome Version 68.0.3440.75*

**Issue Description**:
I'm using workbox for the first time today and with the sole intention of trailing `networkFirst` runtime caching for cross origin URLs. It wasn't until I specified `cachebleResponses` the endpoints become available when simulating offline.

I don't know if this is by design, though it should at least be documented.

```
        options: {
          cacheableResponse: { // ***REQUIRED*** or nothing is cached!
            statuses: [0, 200]
          }
        }
```

```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');
const {GenerateSW} = require('workbox-webpack-plugin');

module.exports = {
  mode: process.env.NODE_ENV || 'development',
  devtool: "source-map",
  entry: './src/app.ts',
  output: {
    filename: './app.js', // in dist
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.ts/,
        loader: 'ts-loader',
      },
      {
        test: /favicon.(png|ico)/,
        loader: 'file-loader?name=[name].[ext]'
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './src/index.html'
    }),
    new GenerateSW({
      runtimeCaching: [{
        urlPattern: new RegExp('^https://example\.com/'),
        handler: "networkFirst",
        options: {
          cacheableResponse: { // ***REQUIRED*** or nothing is cached!
            statuses: [0, 200]
          }
        }
      }],
      clientsClaim: true,
      skipWaiting: true
    })
  ]
};
```

**Comment by jeffposnick** [comment]
Hello @sime—Sorry that this caused some frustration.

An explanation of what you're seeing is covered in our "[Handle Third Party Requests](https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests)" guide.

If you use the `dev` build of Workbox (which is automatically enabled on `localhost`), you should see a message logged in the JS console whenever an opaque response *isn't* cached, letting you know what went wrong: https://github.com/GoogleChrome/workbox/blob/096e44897e9c348f85bb51927c1113de4e339897/packages/workbox-core/_private/cacheWrapper.mjs#L194-L198

I'm going to close this given that we do have some docs and logging, but if you have any suggestions for getting this more up-front for new developers, we're happy to entertain that.

**Comment by jiayihu** [comment]
I came to the same issue, and I think that providing more info when the [guide](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) explains `runtimeCaching` would be quite helpful.
