### ISSUE TITLE
API route is handled only after second reload, even if service worker is active.

### ISSUE THREAD

**Issue by patrykbilka** [GoogleChrome/workbox#1594]
**Library Affected**:
*workbox-webpack-plugin, workbox in general*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
I know it's a common issue, but my problem is a little bit different.

I registered a custom API route. This route is triggered when the user clicks a 'login' button. The problem is that this route works only after the second visit. So you need to reload the page to see that this API call is handled. It is not automatic request during page load - the request is called after service worker is registered, closely after an user tries to login. Despite this, you still need to visit the page second time (or reload), to see the route is handled.

I have react-redux app bundled with webpack, so I'm using InjectManifest plugin with my custom service worker. Here is my service worker, you can see route registration here:
```js
const API_REGEX = '(?:https:\\/\\/.*)?\\/api\\/';
const networkOnlyHandler = workbox.strategies.networkOnly();
const dashboardDataFetchHandler = ({ event }) => networkOnlyHandler.handle({ event }).catch(() => {
  return Response.error();
});


workbox.routing.registerRoute(
  new RegExp(API_REGEX),
  dashboardDataFetchHandler,
  'POST' // post method for login page
);
```

After second reload, the route is handled properly, but I still don't know why I have to reload. Service worker is activated.

Thanks in advance for answers. :)

**Comment by jeffposnick** [comment]
What you're describing sounds expected, based on the way the service worker lifecycle is designed.

This [article](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#clientsclaim) provides a lot more background on what's going on—basically, you're describing an active service worker that does not control your page.

If you add in a call to `workbox.clientsClaim()`, as described in [this guide](https://developers.google.com/web/tools/workbox/modules/workbox-sw#skip_waiting_and_clients_claim), you service worker will take control over the existing page after it becomes active.

**Comment by patrykbilka** [comment]
Thank you. I am already calling ```workbox.clientsClaim()```. The problem was, that I registered my service worker in index.js file instead of index.html. Once I moved service registration code to index.html, right before the closing <body> tag, it started working as expected.
