### ISSUE TITLE
Is "precache-updates" still being broadcasted?

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChrome/workbox#1595]
I'm asking this here rather than on Stackoverflow as I'd love to to send a PR in case `precache-updates` is not there anymore

**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
I saw in this previous issue #309 that `precache-updates` was being automatically broadcasted to the BroadcastChannel whenever the precache has been updated. However I can't find this anymore on `master` and I tried it and it doesn't work. Has it been removed? If yes, are there any plans to get it back? or maybe adding a configuration to broadcast it?

or could it be that there's a way to enable it but not documented yet, then I can submit a PR to web-fundamentals' workbox docs

Thanks!

**Comment by jeffposnick** [comment]
Hello @jadjoubran!

This used to be the default behavior in v1/v2, but was removed as a default in v3.

We've got a [section](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2#workbox-precaching) in the migration guide that provides the equivalent code:

```js
workbox.precaching.addPlugins([
    new workbox.broadcastUpdate.Plugin('precache-updates')
]);

workbox.precaching.precacheAndRoute([...], {
  cleanUrls: false,
  directoryIndex: 'index.html',
  ignoreUrlParametersMatching: [/^utm_/],
});
```

**Comment by Connum** [comment]
For me (using 3.6.1), this still doesn't seem to work.
This is my entire worker script (with the array attribute of `precacheAndRoute` being populated of course:

```js
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-sw.js');

if (workbox) {
	workbox.precaching.addPlugins([
	    new workbox.broadcastUpdate.Plugin('precache-updates')
	]);

	workbox.precaching.precacheAndRoute([]);
}
```

When a file is updated, I can see that in the app page's console output:

    (workbox) Precaching 1 file. 47 files are already cached.

But I don't receive a broadcast message. The code in the app script looks like this:

```js
const updateChannel = new window.BroadcastChannel('precache-updates');
console.log(updateChannel);
updateChannel.addEventListener('message', (event) => {
	console.log(event);
});
```

I get the console log with the `updateChannel` object, but the `message` event is never fired!
If I go to chrome://serviceworker-internals/ and click the `inspect` button for the worker in question, I can get the `message` event triggered by calling

    workbox.broadcastUpdate.broadcastUpdate(new BroadcastChannel('precache-updates'), 'foo','bar','baz')

in the service worker console, so the communication between the worker and the client window evidently works, but apparently workbox never broadcasts the update! How can I get this to work? Is it a bug in workbox or am I missing something?

**Comment by jadjoubran** [comment]
@Connum it's probably better to create a new issue for this and if possible with a minimal reproduction use case

**Comment by stephengardner** [comment]
I'm also experiencing this - no notification of an update, despite registering the channel properly.  @Connum were you able to solve this?

**Comment by Connum** [comment]
> I'm also experiencing this - no notification of an update, despite registering the channel properly. @Connum were you able to solve this?

Unfortunally not, but I'm currently not working on the project where this occured.
