### ISSUE TITLE
Caching additional HTTP methods, e.g. OPTIONS

### ISSUE THREAD

**Issue by Tim15** [GoogleChrome/workbox#1600]
I have a big and convoluted app which makes HTTP `OPTIONS` calls before every API request to an endpoint.  These usually take ~700ms (because the server is not great). 

I am integrating `workbox` into the app, and it would be great if it could also cache the `OPTIONS` method as well as my other HTTP API methods, because this would significantly improve performance for our app

That's my use case but there may be other HTTP methods that others would like to also be cached

Thanks for making such a great library!

**Library Affected**:
workbox-routing

**Browser & Platform**:
all browsers (i'm guessing)

Stack trace:
```
Uncaught invalid-value: The 'method' parameter was given a value with an unexpected value. Valid values are ["DELETE","GET","HEAD","POST","PUT"]. Received a value of "OPTIONS".

WorkboxError (workbox-core.dev.js:331)
isOneOf (workbox-core.dev.js:530)
Route (workbox-routing.dev.js:135)
RegExpRoute (workbox-routing.dev.js:226)
registerRoute (workbox-routing.dev.js:744)
(anonymous) (sw.js:57)
```

**Comment by jeffposnick** [comment]
It's not possible to use a `Request` with a `method` of `'OPTIONS'` as a key in the Cache Storage API—that's part of the API's specification. So trying to set up a Workbox route that used a built-in strategy to cache those requests just wouldn't work.

If you have control over the remote API server, then adding in the `Access-Control-Max-Age` header to the `OPTIONS` response could help: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age

**Comment by Tim15** [comment]
Thanks for the clarification.
