### ISSUE TITLE
Timing Perf Issue on 'Cache-First' Strategies!

### ISSUE THREAD

**Issue by dcflow** [GoogleChrome/workbox#1601]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Google Chrome Canary v.70.0 / Windows 10

**Issue or Feature Request Description**:

Hi guys,

I'm using workbox-sw in my service worker to cache some assets (bundle.js, style.css etc).

When I tested the strategy `staleWhileRevalidate` and `offlineFirst` I saw that `bundle.js` in `staleWhileRevalidate` takes at least 10ms more to start evaluating than using `offlineFirst`.
There is also a slight difference in the time to retrieve the files where still `staleWhileRevalidate` takes longer. 
This leads to longer rendering times and I would guess on mobile it would be much slower.

Sample of results using `offlineFirst`

![1x](https://user-images.githubusercontent.com/6751025/43915573-67202bb6-9c0b-11e8-846e-aea40a475b87.png)

Sample of results using  `staleWhileRevalidate`

![2x](https://user-images.githubusercontent.com/6751025/43915616-8e054932-9c0b-11e8-8d4e-675a53bfd7f5.png)

I suppose this is because of the extra network calls but would be nice to find a way to make them both as fast.

Thank You!

**Comment by philipwalton** [comment]
@dcflow, it's not clear to me that this is due to the strategies. Have you tried reversing the strategies (and the order of applying them) for these assets?

From just looking at these screenshots, and without knowing more about your implementation, I'd say the difference you're seeing is primarily a result of these being different file types (that the browser will naturally handle and prioritize in different ways).

**Comment by dcflow** [comment]
Hey @philipwalton I only used one of the strategies at a time.
I did multiple tests with `staleWhileRevalidate` first and I saw that the browser would start evaluating bundle.js at around 80ms.
Then I just replaced `staleWhileRevalidate` with `offlineFirst` and did multiple tests again and the browser  started evaluating bundle.js at around 50ms.
I didn't change anything else during the tests except for the strategy.

**Comment by jeffposnick** [comment]
I'm not sure that there's anything actionable to do here, especially since the strategies themselves have been overhauled for `v6`.

Phil, feel free to reopen if you still want to investigate.
