### ISSUE TITLE
There's a syntax error  in Workbox ducuments website

### ISSUE THREAD

**Issue by smileShirely** [GoogleChrome/workbox#1602]
There are two same syntax error in Workbox ducuments website, [Workbox Strategies](https://developers.google.com/web/tools/workbox/modules/workbox-strategies),
1. **Configuring Strategies - Changing the Cache Used by a Strategy**, There is a parenthesis lacked in the second parameter
```js
workbox.routing.registerRoute(
  new RegExp('/images/'),
  workbox.strategies.cacheFirst({
    cacheName: 'image-cache'
  }
);
```
2. **Configuring Strategies - Using Plugins**, There is a parenthesis lacked in the second parameter too
```js
workbox.registerRoute(
  new RegExp('/images/'),
  workbox.strategies.cacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new workbox.expiration.Plugin({
        // Only cache requests for a week
        maxAgeSeconds: 7 * 24 * 60 * 60,
        // Only cache 10 requests.
        maxEntries: 10,
      }),
    ]
  }
);
```

**Comment by jeffposnick** [comment]
Thanks for pointing this out! I'll fix it with a PR filed against the docs at https://github.com/Google/webfundamentals
