### ISSUE TITLE
workbox.routing.RequestDestinationRoute?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1606]
This was suggested by @tomayac.

Using [`request.destination`](https://developer.mozilla.org/en-US/docs/Web/API/Request/destination) as a criteria for routing to a specific response strategy offers some advantages over URL-based matching, since your routing logic would not have to change as much due to changes in your URL structure.

A new `RequestDestinationRoute` class in `workbox-routing` could simplify creating routes that use that info. (The alternative is asking folks to write a custom [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~matchCallback).)

One wrinkle is that applying a different strategy based on whether a request is same- or cross-origin is frequently important, and you lose that nuance if you just check for `request.destination`. So perhaps there would need to be some configuration when constructing `RequestDestinationRoute` that allowed you to opt-in to cross-origin matching.

**Comment by tomayac** [comment]
Thanks for opening this issue, @jeffposnick! Some more background on this feature request can be found in this [article](https://medium.com/dev-channel/service-worker-caching-strategies-based-on-request-types-57411dd7652c). People can play with the property and see it in action in the [`Request.destination` playground app](https://request-destination-playground.glitch.me/).

**Comment by jeffposnick** [comment]
After chatting with @tomayac, I think the approach we're going to go with is to update https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_css_and_javascript_files to include a recipe that uses a custom `matchCallback` that feature-detects `request.destination`, and uses it if the current browser supports it (falling back to checking the `url.pathname` if not).
