### ISSUE TITLE
Allow ignoreUrlParametersMatching to vary for each precache entry

### ISSUE THREAD

**Issue by westonruter** [GoogleChrome/workbox#1613]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*all browsers*

**Feature Request Description**:

When doing precaching, the URL parameters that should be ignored can be highly bound to the specific URLs in question. For example, in WordPress URLs for scripts and stylesheets often have a `ver` parameter which should be ignored but such URLs would never get the `utm_*` parameters. However, it could be that a page on a WordPress site would actually need to not ignore the `ver` parameter when precaching. At the moment, however, it is not possible to limit the scope for ignored URL parameters. It would seem useful to allow something like the following:

```js
wp.serviceWorker.precaching.precache([
    {
        url: 'https://example.com/wp-content/themes/example/global.js',
        ignoreUrlParametersMatching: [ /^ver$/ ],
        revision: '1.2.3'
    },
    {
        url: 'https://example.com/available-offline/',
        ignoreUrlParametersMatching: [ /^utm_/ ],
        revision: '2018-12-25 00:00:00'
    },
]);
```

**Comment by jeffposnick** [comment]
Hmmm... what you're suggesting would not map very well into how we store our precache entries and configure the `fetch` handler for precaching. While it's possible to move in the direction, it would need to be done as part of a breaking change in a future major release.

Could we explore some alternatives that would work with the current codebase?

For instance, there's a [`urlManipulation` callback](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.precaching#~urlManipulation) that you can pass in as an option to either `workbox.precaching.addRoute()` or `workbox.precaching.precacheAndRoute()` (depending on how you're setting up the precache route). That function gives you some additional flexibility in modifying the URLs that are checked for precache matches based on arbitrary logic.

E.g.:

```javascript
wp.serviceWorker.precaching.precache([...]);
wp.serviceWorker.precaching.addRoute({
  // ...other options...
  urlManipulation: ({url} => {
    const additionalUrlsToCheck = [];
    // Put whatever logic you need here.
    if (url.pathname.endsWith('foo')) {
      const newUrl = new URL(url);
      newUrl.searchParams.delete('bar');
      additionalUrlsToCheck.push(newUrl.href);
    }
    return additionalUrlsToCheck;
  }),
});
```

**Comment by westonruter** [comment]
Thank you. Yes, what we can do is implement that `urlManipulation` callback to handle entry-specific URL parameters to ignore. The goal in the PWA WordPress plugin is to try to avoid theme/plugin developers from having to directly write JavaScript but instead to interact with the PHP abstraction. This will allow for that.
