### ISSUE TITLE
My files on html doesn't cached!

### ISSUE THREAD

**Issue by nataliawinter** [GoogleChrome/workbox#1615]
Hi! I have tried cached on workbox some pages of my website. 
But just HTTP requests were cached. 
My HTML files does not.
This is my code:
```
self.addEventListener('fetch', (event) => {
    log('[ServiceWorker] Fetch');
    workbox.routing.registerRoute(
        /water|gas|listblocs/,
        workbox.strategies.cacheFirst({
            cacheName: 'cache_water_and_gas'
        }),
    );
});
```

And this is was result on console
![image](https://user-images.githubusercontent.com/9592064/44747970-ed948880-aae4-11e8-9708-6dbc51d8cf41.png)

But this html file doesn't cache (his name is on regular expression)
![image](https://user-images.githubusercontent.com/9592064/44748009-09982a00-aae5-11e8-8aaa-aa8fc64ba77a.png)

Could somebody help me? Thanks!

**Comment by jeffposnick** [comment]
Hello @nataliawinter!

A couple of things:

It's not recommended to call `workbox.routing.registerRoute()` from inside your own `fetch` handler like that. `workbox.routing.registerRoute()` will automatically create a `fetch` handler for you, and additionally, that [usage may break](https://developers.google.com/web/tools/workbox/modules/workbox-sw#avoid_async_imports) in future versions of Chrome.

How is the `_watergasconsumeform.html` file being loaded? Is it a result of a navigation to a page on your site, or is it being loaded via something like `fetch()`?

**Comment by nataliawinter** [comment]
Hello @jeffposnick!
I realize that I was wrong in my code. I ignored the HTML before the workbox. 👎  When I made the changes, it worked! 
Thank you so much!

The `fetch` is a event of Service Worker, I call workbox inside it. But I tested it out of `fetch` and it works. You are alright. 
Thanks for the tips. I appreciate for your attention. 😃

**Comment by jeffposnick** [comment]
Glad things worked out!
