### ISSUE TITLE
problems with offline routes

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1627]
I have a legacy application with angularjs and I'm trying to make it more performative and making it offline.

Everything worked, serviceWorker running, but if I force offline and press f5, the same page does not go online, but if I go back to the root (/) while still offline and press f5, it loads everything right.

## manifest:
```
{
	"name": "Vimbo",
	"short_name": "Vimbo",
	"start_url": "/",
	"background_color": "#359be5",
	"display": "standalone",
	"theme_color": "#359be5",
	"icons": []
}
```

## workbox-config.js:
```
module.exports = {
  "cacheId": "Vimbo-APP",
  "globDirectory": "dist/",
  "globPatterns": [
    "**/*.{jpg,svg,png,jpeg,gif,ico,xml,webmanifest,eot,ttf,woff,woff2,json,html,js,css}"
  ],
  "swDest": "dist/sw-vimbo.js",
  "maximumFileSizeToCacheInBytes": 4 * 1024 * 1024
};
```

## Library Javascript:
Angularjs 1.7
html5Mode true

## Service Workers:
![captura de tela de 2018-09-13 09-42-07](https://user-images.githubusercontent.com/11314585/45488409-b73b4800-b737-11e8-94be-114060352811.png)

## forcing offline:

**Running after F5**:
![captura de tela de 2018-09-13 09-46-45](https://user-images.githubusercontent.com/11314585/45488606-4e080480-b738-11e8-9bfc-b21de7d27bb5.png)

**Not working after F5**:
![captura de tela de 2018-09-13 09-47-20](https://user-images.githubusercontent.com/11314585/45488635-62e49800-b738-11e8-8757-5291dcfb1cc5.png)

From what I noticed, in the url (/) base, when I leave offline and press f5, it works and the registered service worker appears, now in any part of the system, where the url changes, forcing offline and pressing f5, it does not work and does not register / retrieve the service worker.

**Please, can anyone help me :)**

**Comment by jeffposnick** [comment]
If you have an "[App Shell](https://developers.google.com/web/fundamentals/architecture/app-shell)" of generic HTML that you want to use to fulfill your navigation requests, you can use the [`navigateFallback` configuration option](https://developers.google.com/web/tools/workbox/modules/workbox-build#generateSW-navigateFallback) in to tell Workbox about it. It sounds like `/` might be your App Shell URL, so you'd use

```javascript
module.exports = {
  navigateFallback: '/',
  // ... other config...
};
```

**Comment by GlauberF** [comment]
Hello @jeffposnick 
includes in my configuration file and looks like this:
![captura de tela de 2018-09-13 16-00-07](https://user-images.githubusercontent.com/11314585/45509200-4020a680-b76d-11e8-8cde-5e966ab5f98c.png)


but even so, after F5 did not work.

## my .htaccess
![captura de tela de 2018-09-13 16-07-16](https://user-images.githubusercontent.com/11314585/45509260-74946280-b76d-11e8-85e5-752443eb96f5.png)


## base href in html
![captura de tela de 2018-09-13 16-07-45](https://user-images.githubusercontent.com/11314585/45509298-8e35aa00-b76d-11e8-8ef2-e7b72ad9e57f.png)

if testing go into my demo https://spa.vimbo.com.br/, will see that putting offline in the root url works offline, most in the authentication screen for example does not work

**Comment by GlauberF** [comment]
@jeffposnick worked with ```/index.html```

**Comment by jeffposnick** [comment]
Gotcha—glad that it worked when using `'/index.html'`!
