### ISSUE TITLE
Consider not logging "No route found for" messages

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1628]
When logging is set to debug, a workbox `Router` instance will log when it's asked to handle a request event but there's no handler for that event.

This perhaps makes sense if all you're using is the default router, but if you're using more than one router it starts to get pretty noisy pretty fast. It's also confusing, because you start seeing things like this:

<img width="398" alt="screen shot 2018-09-13 at 11 18 35 am" src="https://user-images.githubusercontent.com/326742/45507367-ca094900-b746-11e8-9acf-5546f4f37ce1.png">

Note that anyone using `workbox-google-analytics` and verbose logging will see *a lot* of messages about routes not being found.

Some possible solutions to this problem (in order of complexity):

- Do nothing
- Stop showing these messages at all
- Only show them for the default router
- Show them, but indicate which router is emitting the message (so it's less confusing)
- Only show them if *none* of the instantiated routers have matching routes

**Comment by jeffposnick** [comment]
_Stop showing these messages at all_ is probably fine, as long as we continue to log in the affirmative when there is a match.

**Comment by daffinm** [comment]
I'd vote for option 4 (Show them, but indicate which router is emitting the message (so it's less confusing) with, perhaps, the additional option of being able to switch these messages off.

**Comment by jeffposnick** [comment]
Long-term, we're looking to move to a model in which there's one, singleton `Router`. I don't think we're going to take action to resolve this issue directly, but it should become less of an annoyance once that happens.
