### ISSUE TITLE
disabling dynamic routes

### ISSUE THREAD

**Issue by hendrikeng** [GoogleChrome/workbox#1631]
I am sorry to post the question here, but i have tried stackoverflow and didn't get any response.

I am failing following the docs to disable caching of dynamic routes via the networkOnly handler. What am i missing, i did try full Urls in the RegEx pattern as well.

```js
workboxPlugin: {
        swDest: 'sw.js',
        clientsClaim: true,
        skipWaiting: true,
        runtimeCaching: [
            {
                urlPattern: new RegExp('/'),
                handler: 'staleWhileRevalidate',
            },
            {
                urlPattern: new RegExp('/shop'),
                handler: 'networkOnly',
            },
            {
                urlPattern: new RegExp('/admin'),
                handler: 'networkOnly',
            },
        ],
    },
```

**Comment by jeffposnick** [comment]
I'm not sure what you mean—there's *no* runtime caching by default, so you shouldn't have to explicitly disable caching via create a `networkOnly` route.

Depending on how you've configured Workbox, there might be some precaching, and perhaps what you're seeing is that precached URLs are being served from the cache when you don't want them to be?

If that's the case, the best course of action would be to configure your build step to omit those URLs from being precached. It looks like you're using the webpack plugin, so you have a [few options](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_generatesw_config) for controlling what gets precached, via both white and blacklists, based on URL patterns or chunk names.

**Comment by jeffposnick** [comment]
Well, the `new RegExp('/')` pattern will match just every URL—is that what you want? I'm guessing not.

If you're trying to match just the single URL path `'/'`, and nothing else, you can either use the string `'/'` (instead of a `RegExp`) or be really explicit with `new RegExp('^/$')`.

**Comment by hendrikeng** [comment]
@jeffposnick thanks jeff.

sorry for the confusion. So if i want to have the service worker prechaching everything on the site expect `/admin` and `shop` (and urls behind their routes like `shop/checkout`) i would go for:

```js
    workboxPlugin: {
        swDest: 'sw.js',
        clientsClaim: true,
        skipWaiting: true,
        runtimeCaching: [
            {
                urlPattern: '/',
                handler: 'staleWhileRevalidate',
            },
        ],
        navigateFallbackBlacklist: [/admin/, /shop/],
    },
```

thanks again, much appreciated.
