### ISSUE TITLE
GenerateSW does not support method option in runtimeCaching

### ISSUE THREAD

**Issue by chrisdns** [GoogleChrome/workbox#1636]
**Library Affected**:
*workbox-build, workbox-webpack-plugin*

**Browser & Platform**:
*Google Chrome Version 69.0.3497.92 (Official Build) (64-bit)*

**Issue or Feature Request Description**:
I would like to use POST method in *runtimeCaching* options from WorkboxPlugin.GenerateSW({ }) plugin instead of GET.

It is not possible at the moment to change the default method ; it leads to a validationError

`ValidationError: child "runtimeCaching" fails because ["runtimeCaching" at position 0 fails because ["method" is not a supported parameter.]]`.

It should be possible to change default method, I can make a PR if you think this is relevant.

**Comment by jeffposnick** [comment]
A PR would be appreciated—thanks!

This was just an oversight; there's already [logic in place](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/runtime-caching-converter.js#L120) to read in the `method`, but the [validation logic](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/entry-points/options/common-generate-schema.js) doesn't allow for it to be set, so I think that validation logic is the only thing that would need to change.
