### ISSUE TITLE
query queue in indexDB | background sync

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1637]
is there any way to find items that are in the indexDB queue, which will be executed through background sync?

**Comment by GlauberF** [comment]
@jeffposnick So I would need two things.

For example, know what has queued to be processed, so I can show on the user's screen, example:

- In this CRUD, you also have 2 items queued to be processed, to prevent the user from registering repeated information, and the item that he will register, has already been registered previously.

Second, I need in my application internally, get the queue events, eg when an item has queued or been processed.

**Comment by jeffposnick** [comment]
For the second point, the [`callbacks`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.backgroundSync.Queue#Queue) that can be passed in to the `Queue`/`Plugin` constructor should take care of that use case.

For the first point, what information are you looking to get out of the queue—the URL of of the failed request? The body? Im not 100% sure what the behavior is if you were to end up with two "identical" failed requests in the same queue.

CC: @philipwalton

**Comment by GlauberF** [comment]
@jeffposnick 
about using callback -> https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.backgroundSync.Queue#Queue, I implemented it in my code, but I need to access it within my application, but how to have this access?

## my code
![captura de tela de 2018-09-17 14-41-04](https://user-images.githubusercontent.com/11314585/45639327-11187680-ba86-11e8-8dd3-2c23baf8a60d.png)


## capture within my APP, in my javascript files, which has nothing to do with the workbox?

**Comment by GlauberF** [comment]
@jeffposnick 
help me, in the example above :)

**Comment by jeffposnick** [comment]
You could do something like>

```js
// In your service worker:
const callback = async (storableRequest) => {
  const message = {
    // Send whatever data you want.
  };
  const clients = await self.clients.matchAll();
  for (const client of clients) {
    client.postMessage(message);
  }
};


// In you web app's window context:
navigator.serviceWorker.addEventListener('message', (event) => {
  const message = event.data;
  // message is whatever you sent from the service worker.
});
```

Your `window` clients can listen for messages posted from the service worker using that pattern.

**Comment by GlauberF** [comment]
@jeffposnick  the perfect, thank you.


in my last function gave an error, can you tell me why?

![captura de tela de 2018-09-18 14-12-50](https://user-images.githubusercontent.com/11314585/45703659-5ce12380-bb4b-11e8-9882-4055ea63f568.png)

## code
```
queueDidReplay: async (storableRequestArray) => {
            console.log('callback post queue [queueDidReplay]', storableRequestArray)
            let message = {
                'status': 'executado',
                'identificacao' : "postQueueAPI",
                'data' : storableRequestArray
            };

            // emite notificação ao cliente window
            let clients = await self.clients.matchAll();
            for (const client of clients) {
                client.postMessage(message);
            }
        }
```

**Comment by philipwalton** [comment]
@GlauberF, the `StorableRequest` class cannot be used in `postMessage()` because it's not be [structured cloned](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). However, you can use the [`toObject()` method of `StorableRequest`](https://github.com/GoogleChrome/workbox/blob/v3.5.0/packages/workbox-background-sync/models/StorableRequest.mjs#L105-L118) to convert it to an object, which can be cloned and thus used in `postMessage()`.

**Comment by GlauberF** [comment]
Perfect, I'll do it @philipwalton,

At the beginning of the issue, I asked if there is a way for me to list what is in the indexDb to be processed.
I tried to use the normal read calls of IndexDB, but it does not work perfectly, because the call to open the bank, when it does not exist, it creates one and if it creates a bank with the name that is used by the workbox, the problem after the recording.

Do you have any suggestions as to how I can read indexDB files without affecting the process of writing new items to the workbox queue.

If you can share something in code, how would you go about it, thank you

**Comment by philipwalton** [comment]
I don't think there's a good way with the current API, but other people have asked for a similar feature, so I think what makes the most sense is to add methods to the `Queue` class that allow you to read/modify items in the current queue.

I discussed something similar here: https://github.com/GoogleChrome/workbox/pull/1503#issuecomment-395857569

**Comment by philipwalton** [comment]
FYI, I'm submitted #1710, which should make it easier for you to use the `Queue` directly. Please take a look at that PR and let me know what you think.
