### ISSUE TITLE
`injectManifest` with `importWorkboxFrom` option?

### ISSUE THREAD

**Issue by CarterLi** [GoogleChrome/workbox#1641]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
*Does `injectManifest` support `importWorkboxFrom`? I saw https://github.com/GoogleChrome/workbox/issues/1260 and https://github.com/GoogleChrome/workbox/pull/1290 but if I pass `importWorkboxFrom: 'local'` as an option of injectManifest, it still generates `ValidationError`. I'm using https://github.com/nuxt-community/pwa-module/tree/develop/packages/workbox *

*I'm in China. I can't access google cdn for well known reasons. `importWorkboxFrom: 'local'` is a must for me. Please help*

**When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.**

```
 ERROR  build:done

  ValidationError: "importWorkboxFrom" is not a supported parameter.

  - errors.js:190 Object.exports.process
    [eoi-portal]/[joi]/lib/errors.js:190:19

  - index.js:668 internals.Object._validateWithOptions
    [eoi-portal]/[joi]/lib/types/any/index.js:668:31

  - index.js:702 internals.Object.validate
    [eoi-portal]/[joi]/lib/types/any/index.js:702:21

  - validate.js:20 module.exports
    [eoi-portal]/[workbox-build]/build/entry-points/options/validate.js:20:33

  - inject-manifest.js:44 Object._callee$
    [eoi-portal]/[workbox-build]/build/entry-points/inject-manifest.js:44:23

  - runtime.js:62 tryCatch
    [eoi-portal]/[babel-runtime]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:296 Generator.invoke [as _invoke]
    [eoi-portal]/[babel-runtime]/[regenerator-runtime]/runtime.js:296:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [eoi-portal]/[babel-runtime]/[regenerator-runtime]/runtime.js:114:21

  - asyncToGenerator.js:17 step
    [eoi-portal]/[babel-runtime]/helpers/asyncToGenerator.js:17:30

  - asyncToGenerator.js:35
    [eoi-portal]/[babel-runtime]/helpers/asyncToGenerator.js:35:14

  - new Promise

  - _export.js:36 new F
    [eoi-portal]/[core-js]/library/modules/_export.js:36:28

  - asyncToGenerator.js:14 Object.<anonymous>
    [eoi-portal]/[babel-runtime]/helpers/asyncToGenerator.js:14:12

  - inject-manifest.js:123 Object.injectManifest
    [eoi-portal]/[workbox-build]/build/entry-points/inject-manifest.js:123:17

  - index.js:225 hook
    [eoi-portal]/[@nuxtjs]/workbox/index.js:225:20

  - nuxt.js:122 fn
    [eoi-portal]/[nuxt]/lib/core/nuxt.js:122:47
```

**Comment by jeffposnick** [comment]
`importWorkboxFrom` isn't a supported option when using `injectManifest` mode with the `workbox-build` plugin. (It is supported when using the `workbox-webpack-plugin`, but that's not what's being used here.)

You can replicate that behavior by using the `workbox-cli` and running `workbox copyLibraries <path/to/libraries>`, or just downloading the archive for a given version from the [release page](https://github.com/GoogleChrome/workbox/releases/tag/v3.5.0).

Then, in your `swSrc` file, you can [follow the steps documented here](https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn) to point to the local files.
