### ISSUE TITLE
Add means of disabling navigation preload after once enabled

### ISSUE THREAD

**Issue by westonruter** [GoogleChrome/workbox#1648]
**Library Affected**:
*navigation-preload*

**Browser & Platform**:
*Chrome (as of now)*

**Issue or Feature Request Description**:
The navigation preload module has an [`enable` method](https://github.com/GoogleChrome/workbox/blob/087ea6df2473b11f116feb1fe42d50199de5db73/packages/workbox-navigation-preload/enable.mjs). However, it does not have a corresponding way to _disable_ navigation preload, which is something that should be available per [
Speed up Service Worker with Navigation Preloads](https://developers.google.com/web/updates/2017/02/navigation-preload#activating_navigation_preload):

> You can call `navigationPreload.enable()` whenever you want, or disable it with `navigationPreload.disable()`. However, since your fetch event needs to make use of it, it's best to enable/disable it in your service worker's `activate` event.

In the [PWA plugin](https://github.com/xwp/pwa-wp) for WordPress, there is an API to configure navigation preload. At present when it is enabled (as it is by default) then the `enable` method is called. When it is disabled, however, we just omit the call to begin with:

https://github.com/xwp/pwa-wp/blob/1cbbaac06d15ba3e02bae03c6648eee2ae9e8a96/wp-includes/class-wp-service-workers.php#L272-L281

I've noticed in Chrome when updating the service worker with the `workbox.navigationPreload.enable()` call omitted, there will still be `preload` entries showing up in the network console while I navigate. It seems Chrome is holding onto the “preloadness” even after the service worker is updated without the `workbox.navigationPreload.enable()` call.

So there seems to need to be a way to disable navigation preload explicitly.

**Comment by jeffposnick** [comment]
This should make it into the upcoming `3.6.0` release.
