### ISSUE TITLE
cache strategy with staleWhileRevalidate and broadcastUpdate

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1650]
I'm using ```staleWhileRevalidate()```

## my code
workbox.routing.registerRoute (
      new RegExp ('https://api-production.vimbo.com/v1/*'),
     workbox.strategies.staleWhileRevalidate ({
          plugins: [
             new workbox.broadcastUpdate.Plugin ('api-updates', {
                 headersToCheck: ['last-modified'],
             })
          ]
      })
  );

On my client, I'm getting the change notification
![captura de tela de 2018-09-19 17-00-02](https://user-images.githubusercontent.com/11314585/45777299-cafd1780-bc2b-11e8-83b5-d7cdf217e58e.png)

my question, is this cache update made automated after being notified?
Do I need to do something to force caching?

**Comment by GlauberF** [comment]
@jeffposnick or @philipwalton can you help me ?

**Comment by jeffposnick** [comment]
The cache updates (the "revalidate" step in stale-while-revalidate") happen automatically. The broadcast of the change notification will only happen after a revalidate takes place, and only if the response `fetch()`ed during the revalidation differed from the previously cached response.

**Comment by GlauberF** [comment]
perfect @jeffposnick  , but in my case this is not happening well.

I'm working with the value in header **last-modified**

## step by step
1 - I got to the list of records, where it cached the values, including the **last-modified** header value.
2 - clicked edit and saved
3 - I was redirected to listing, where he made a new http request

**Note:** When it came back in the list, in step 3, it performed http again, actually it noticed that it changed the last-modified field, however I am already in the list and without the updated data, hence I have to force an update on the page by pressing F5.

**Comment by MohammadSabbagh** [comment]
probably similar to this
https://github.com/GoogleChrome/workbox/issues/1498

**Comment by jeffposnick** [comment]
Good point—can you check to see if the `Last-Modified` header isn't being exposed when accessing the CORS response due to the scenario outlined in #1498?

**Comment by jeffposnick** [comment]
I did recently chat with someone who was able to successfully use `StaleWhileRevalidate` and the `BroadcastUpdatePlugin`, so I think it's working in general.

If you need more control over determining what triggers a broadcast, I'd recommend adding in your own [custom Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) that implemented the `cacheDidUpdate` callback, and you can examine whatever properties of the old and newly cached responses you need inside of that.
