### ISSUE TITLE
Update all package.json dependencies

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1656]
In general, we should take the v4 release as an opportunity to do a sweep through our various `package.json`s and update all `dependencies` and `devDependencies` to the latest releases (unless there are one-off reasons not to update).

The PR that resolves this can probably replace https://github.com/GoogleChrome/workbox/pull/1609, which just tracks a subset of the dependencies.

**Comment by abraham** [comment]
What about using something like @renovatebot to automatically open update PRs?

**Comment by jeffposnick** [comment]
Sure; see https://github.com/GoogleChrome/workbox/issues/1696
