### ISSUE TITLE
add button to force pwa banner

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1662]
## add button to force pwa banner

today in the console > application > manifest, I have the option to force / test add to homescreen.
How can I include a button in my application, where the user can click and force, the banner appear?

a javascript call in the application, which forces the banner to appear to add to homescreen

**Comment by jadjoubran** [comment]
Hey @GlauberF 
This behavior is not related to workbox, however you can checkout this example here in [New in chrome 68](https://developers.google.com/web/updates/2018/07/nic68)

**Comment by GlauberF** [comment]
Perfect @jadjoubran , but if the user has already added the beforeinstallprompt, it will no longer be called.
And I would like some way to force it, even if the user has already added it.

## Because, I want this action:
Many users of my platform end up adding and then deleting, but deleting it disappears from the desktop, there was in fact the uninstallation of the app.

**Comment by jadjoubran** [comment]
as far as I know, I don't think you can force it but if your users uninstalled the PWA, then the beforeinstallprompt will fire again later on

**Comment by GlauberF** [comment]
perfect @jadjoubran


**I created your personalized call**


![captura de tela de 2018-09-25 10-43-30](https://user-images.githubusercontent.com/11314585/46017555-273dbc80-c0ae-11e8-825e-bd15a490bdef.png)


**but when I click, it calls the standard chrome banner again**

![captura de tela de 2018-09-25 10-44-27](https://user-images.githubusercontent.com/11314585/46017600-476d7b80-c0ae-11e8-9375-d93d2ff818c1.png)


**I would like that after clicking on accept from my custom banner, I already called the box to add**

![captura de tela de 2018-09-25 10-45-32](https://user-images.githubusercontent.com/11314585/46017670-6ec44880-c0ae-11e8-9c59-e3132086f52f.png)


## my code
```
(function() {

	'use strict';

    var deferredPrompt;


    window.addEventListener('beforeinstallprompt', function(e) {
        // Evitar que o Chrome 67 e anteriores mostrem automaticamente o prompt
        e.preventDefault();
        // Esconda o evento para que ele possa ser acionado mais tarde.
        deferredPrompt = e;
        showAddToHomeScreen();
    });


    function addToHomeScreen() {
        if (deferredPrompt) {
        	console.log('entrou em deferredPrompt')
            // Show the prompt
            deferredPrompt.prompt();
            // Wait for the user to respond to the prompt
            deferredPrompt.userChoice
                .then(function(choiceResult) {
                	console.log('choiceResult', choiceResult)

                    if (choiceResult.outcome === 'accepted') {
                        console.log('User acept the A2HS vibmo');
                    } else {
                        console.log('User dismissed the A2HS vimbo');
                    }

                    deferredPrompt = null;
                });
        }
    }


    function showAddToHomeScreen() {
        $('body').stoCookie({
            message: '<div layout="row" layout-wrap="" class="layout-wrap ng-scope layout-row" layout-align="center center">' +
                '<!-- <div class="flex-20" flex-20>' +
                '<img src="/assets/favicon/Icon-192.png">' +
                '</div> -->' +
                '<div class="flex">' +
                '<p style="margin-bottom: 1px;"><b>Adicionar aplicativo na tela inicial !</b></p>' +
                '<p>Para melhorar a experiência, nós aconselhamos que você adicione nosso aplicativo na tela inicial, não precisando abrir o navegador e acessando mais rapidamente</p>' +
                '</div>' +
                '</div>',
            mode: 'always', // 'cookie' | 'session' | 'always'
            scrollClose: 'y', // hide banner on scroll, true | false
            position: 'bottom', // 'top' | 'bottom'
            background: '#31b0d5', // banner background color
            color: '#fff', // banner text color
            linkColor: '#1b98ff', // link color
            slide: 'y', // slide effect, true | false
            fade: 'y', // fade effect, true | false
            btnText: 'Adicionar', // Agree button
            buttonBg: '#fff', // button background
            buttonColor: '#000', // button text color
            buttonAlign: 'center', // 'left' | 'center' | 'right'
            innerClass: 'text-center font-size-16 add-aplicativo-vimbo', // optional additional class to .biscotto
            removed: function() {}, // callback after the banner has been removed
            accepted: function() {} // callback after the acceptation check
        });

        // a2hsBtn.addEventListener("click", addToHomeScreen);

        // passou um indentificador personalizado
        var temIdentificador = ' body > .add-aplicativo-vimbo > div > div > p';
        $(document).on('click', temIdentificador, function(e) {
            // addToHomeScreen();
            console.log('no click webapp')
            addToHomeScreen()
        });

    }    


    showAddToHomeScreen();



})();
```
@jeffposnick and @philipwalton , 
know how I can do this or where I'm going wrong ?

**Comment by philipwalton** [comment]
As @jadjoubran mentioned, the add to homescreen feature is not something that workbox handles. It's a general service worker feature, so there's not really anything you can do with workbox to help you solve it.
