### ISSUE TITLE
Cache on certain pages

### ISSUE THREAD

**Issue by imiotis** [GoogleChrome/workbox#1666]
How to make the cache to be taken only on site.com/page1, but not site.com/page2, site.com/page3, etc.? I think I need to add something like this: return location.search (/page1/) != -1).
I have this code at the moment:
```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.3.1/workbox-sw.js');
if (workbox) {
    workbox.setConfig({debug: true});
    workbox.routing.registerRoute(
        new RegExp('.*\.js'),
        workbox.strategies.staleWhileRevalidate({
            cacheName: 'assets-cache',
            plugins: [
                new workbox.expiration.Plugin({
                  maxEntries: 60,
                  maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                })
            ]
        })
    );
}
```

**Comment by jeffposnick** [comment]
You're saying that you want a Workbox route to only match if the current page making the request is `/page1`?

As I'm sure you've realized, you can't take advantage of the service worker scoping rules (since `/page2` and `/page3` will also be under the same scope of `/`), so the best approach I could think of would be to use a custom [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~matchCallback) which checks the `Referer` header on the incoming `event.request` and only return `true` if it's set to what you want.

Something like:

    workbox.routing.registerRoute(
        ({event, url}) => {
          // Return true if this is a .js request with the Referer header we expect.
          return event.request.headers.get('referer').endsWith('/page1') &&
                 url.pathname.endsWith('.js');
        },
        workbox.strategies.staleWhileRevalidate({
            cacheName: 'assets-cache',
            plugins: [
                new workbox.expiration.Plugin({
                  maxEntries: 60,
                  maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                })
            ]
        })
    );

**Comment by imiotis** [comment]
Thanks, but event.request.headers.get('referer') returns undefined, but event.request.referer returns the current url.

**Comment by jeffposnick** [comment]
Oops—I always make that mistake. Definitely use `event.request.referer` instead 😄

I'll update the example.

**Comment by imiotis** [comment]
Me again.
```
const matchFunction = ({url, event}) => {
      return true;
}
```
The function above saves everything on the page:
1) scripts: (script.js)
2) styles: (style.css)
3) data from ajax requests (site.com/path/for/ajax/request/)
4) text/html of the current page (site.com/myapp/1)

I do not want ajax request data to be cached. How to exclude data caching ajax request from site.com/path/for/ajax/request/? It could be like this:
```
const matchFunction = ({url, event}) => {
      return url.pathname.endsWith ('. js') || url.pathname.endsWith ('. css') || url.pathname.search (/ myapp(\d+)/)! = -1
}
```
But this function saves only scripts and styles, because url.pathname returns only .css, .js, .png etc, but not text/html ...

**Comment by jeffposnick** [comment]
Looking at `event.request.destination` is an alternative to checking URL extensions. Here's some info on using that: https://medium.com/dev-channel/service-worker-caching-strategies-based-on-request-types-57411dd7652c
