### ISSUE TITLE
Missing info in the doc's

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1670]
Hi,

I am trying to update workbox from 3.4.0 to the latest version 3.6.2

I am reading the https://github.com/GoogleChrome/workbox/releases

The `workbox.navigationPreload.disable()` is not mentioned in the doc's, see webpage: https://developers.google.com/web/tools/workbox/modules/workbox-navigation-preload#basic_usage

**Comment by ayumihamsaki** [comment]
I dont like to complain and give no solution so here is a possible solution to an improvement:

![example](https://user-images.githubusercontent.com/17784082/46261260-0c71aa80-c4e9-11e8-93fe-939143eac08c.png)

Please note: When I was injecting this code there is NO documentation about the release update:

> Added the disable() method to workbox.navigationPreload

The doc's only talk about `enable()` and don't say anything about `disable()`, this highlights one of my points that releases are being created and no updates to the doc's to explain these updates are always being done.

See here: https://developers.google.com/web/tools/workbox/modules/workbox-navigation-preload#basic_usage

Above link only talks about `enable()` and not `disbale()`

Lastly, I would be grateful any help with the updates questions I said above.

**Comment by jeffposnick** [comment]
It's documented at https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.navigationPreload#.disable

We don't specifically call out each method that's exposed in the API in that "modules" section of the docs.
