### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by sashor** [GoogleChrome/workbox#1671]
**Library Affected**:
*[Documentation](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw#migrate_from_hand-crafted_sw-toolbox_to_workbox-sw)*

**Issue or Feature Request Description**:
I was following the guide called "Migrate from hand-crafted sw-toolbox to workbox-sw" and I spent some time trying to figure out what I was doing wrong. Then, thanks to other docs, I realized I should use "workbox.routing......" and not "workbox.router...." 😅 like it's currently written in the guide.

**Comment by jadjoubran** [comment]
Thanks @sashor for reporting!
It seems that this has been fixed already in [this commit](https://github.com/google/WebFundamentals/commit/f04998cd6296336f2f724950ad9d941acc68c9d3#diff-5c74a0296a8804aa2e55220ecc7f0be0) and the current [documentation](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw#migrate_from_hand-crafted_sw-toolbox_to_workbox-sw) has the correct `workbox.routing` 👍
