### ISSUE TITLE
Network request if cache fails on registerNavigationRoute but no cache

### ISSUE THREAD

**Issue by corne-alant** [GoogleChrome/workbox#1672]
On IOS 12, it appears the service worker is shared between Safari and the "Add to Homescreen" Webview but not the cache. That means that once a user actions "add to home screen" they will have a service worker installed but no cache. Thus, I believe this edge case will become quite common in the future.

Seeing as the try-catch below only resorts to the network as a backup and does not subsequently cache the result the files never get cached. 

In a project I'm working on, I've allocated the manifest to a constant and I trigger install and activate on the precacheController when this situation occurs. Should we consider an alternative approach in the library here?

https://github.com/GoogleChrome/workbox/blob/912080a1bf3255c61151ca3d0ebd0895aaf377e2/packages/workbox-routing/_default.mjs#L184

**Comment by corne-alant** [comment]
I've logged a bug https://bugs.webkit.org/show_bug.cgi?id=190269 - let's see what they come back with

**Comment by jeffposnick** [comment]
The underlying Safari bug is now marked as fixed.
