### ISSUE TITLE
Ensure we're mangling properties consistently across files

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1674]
We need to add the [`nameCache` minify option](https://github.com/terser-js/terser#minify-options) to our terser config to ensure properties and variables are renamed consistently across files.

I don't think we're currently affected by any issues resulting from *not* doing this, but we almost certainly would be if we ever start extending classes from other packages.

**Comment by jeffposnick** [comment]
Is this still worth tracking, now that we're shifting focus away from our pre-built bundles and towards developers using their own custom bundles?

**Comment by philipwalton** [comment]
I think so. As long as we're publishing separate files to the CDN, it's potentially a problem. But IIRC it'll only be a problem if we're extending a class from one package in another package. In that case we need to ensure that the property names are always mangled to the same final symbol.

Since we don't do that (AFAIK), it's not an issue at the moment.

**Comment by philipwalton** [comment]
Now that we're exposing a `Strategy` base class for other packages to potentially extend, we need to ensure this is added before v6 is released.
