### ISSUE TITLE
200 offline response ssr

### ISSUE THREAD

**Issue by ashwinkshenoy** [GoogleChrome/workbox#1681]
**Browser & Platform**:
"all browsers".*

**Issue or Feature Request Description**:
Is there a way to respond with a 200 when offline using **workbox** webpack plugin with **SSR** in **Vue**?
I found this option with SWPrecachePlugin
[https://github.com/vuejs/vue-hackernews-2.0/issues/173](https://github.com/vuejs/vue-hackernews-2.0/issues/173)

**Comment by jeffposnick** [comment]
In general, using https://www.npmjs.com/package/@vue/cli-plugin-pwa and then adopting the App Shell pattern (which implies setting a `navigateFallback` option corresponding to your generic HTML) should work. When the service worker is in control, the navigation requests won't actually make it to the server, so SSR is not a factor here.

There's some context at https://github.com/vuejs/vue-cli/issues/717#issuecomment-382079361
