### ISSUE TITLE
Cannot cache ssr page in runtime

### ISSUE THREAD

**Issue by lynnic26** [GoogleChrome/workbox#1686]
**Library Affected**:
*workbox*

**Browser & Platform**:
* all browsers.*

**Issue or Feature Request Description**:
I cannot cache ssr page while using registerRoute
``` 
workbox.routing.registerRoute(
    /home/,
    workbox.strategies.networkFirst({
      cacheName: 'home-cache'
    })
  )
```
/home page is rendered by express, but in dev tools the home-cache is always empty
![ssr](https://user-images.githubusercontent.com/7609558/46579507-fa8e8b00-ca45-11e8-8a04-17fee68d1730.jpeg)

It works fine when I use a static page like home.html 
So how can I get it work when using a server side rendered page?

==============
By the way , the service-worker file is also render by server side
the path is **/pwa/sw**

**Comment by lynnic26** [comment]
Finally I get it out, there are two ways
1. change the path of service worker file to root directory /sw.js instead of /pwa/sw.js
2. set scope to ./ when registering service worker, and make sure the resources has **service-worker-allowed** field in response header
https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug

**Comment by scaledrop** [comment]
Same issue persists here. Waiting for the stable fix!

**Comment by lynnic26** [comment]
> Same issue persists here. Waiting for the stable fix!

The two method I metioned above is what webbox official recommand

**Comment by lynnic26** [comment]
> > Same issue persists here. Waiting for the stable fix!
> 
> The two methods I metioned above is what workbox official site recommands

**Comment by philipwalton** [comment]
Yes, the scoping of the SW looks to be the problem indeed, glad you got it figured out @lynnic26!

@scaledrop, there won't be a fix added to Workbox for this, as setting the correct scope is the recommended (and only) way to do this.
