### ISSUE TITLE
workbox background sync url not matching never

### ISSUE THREAD

**Issue by tximpa91** [GoogleChrome/workbox#1690]
**Library Affected**:
workbox background sync
**Browser & Platform**:
Chrome 69

**Issue or Feature Request Description**:
Hi i am using workbox background sync for firing failed post but I can manage to this with this situation my web app is doing the post to API REST, when it failed the post it doesn't store the request in indexDB.

```js
workbox.routing.registerRoute(
    '/web/site/savedata',  // https://app.rateandgrade.com/ 
    workbox.strategies.networkOnly({
        plugins: [{
            fetchDidFail: async ({request}) => {
                await queue.addRequest(request);
            },
        }],
    }),
    'POST'
);
```

This one works.

```js
workbox.routing.registerRoute(
    'https://api.rateandgrade.com/corp/v1.0/blu/cuestionario', 
    workbox.strategies.networkOnly({
        plugins: [{
            fetchDidFail: async ({request}) => {
                await queue.addRequest(request);
            },
        }],
    }),
    'POST'
);
```

this is the rest api but is in the same domain but another path

**Comment by philipwalton** [comment]
It sounds like the issue may not be related to `workbox-background-sync` but instead related to route matching. Can you confirm that the `fetchDidFail` plugin method is being called in both cases?

**Comment by jeffposnick** [comment]
There's some background on routing at https://developers.google.com/web/tools/workbox/guides/route-requests

**Comment by jadjoubran** [comment]
I think the second one is working because you're providing the full URL, which is a requirement if you want to match a URL on a different domain/subdomain

**Comment by jeffposnick** [comment]
That sounds like a likely explanation. If you're still stuck, please let us know and we can reopen the issue.
