### ISSUE TITLE
workbox + GraphQL not working

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1691]
I am using in my GraphQL application, where I give a POST instead of GET, to fetch or list the data.
But it is not working, workbox is not caching

**Config workbox**:
![captura de tela de 2018-10-09 16-00-08](https://user-images.githubusercontent.com/11314585/46691177-a4068580-cbda-11e8-89f2-6cb847240bfd.png)

But you can see on the net that the workbox is not caching

![captura de tela de 2018-10-09 16-03-06](https://user-images.githubusercontent.com/11314585/46691331-09f30d00-cbdb-11e8-8ef0-4d9a754278dc.png)

**Comment by jeffposnick** [comment]
`POST` requests all have the same URL, and the Cache Storage API uses URLs as keys. There could never be more than a single cached entry corresponding to that `/graphql` endpoint.

Please see: https://github.com/GoogleChrome/workbox/issues/1620

**Comment by GlauberF** [comment]
@jeffposnick 
I changed to `GET` now, using query.
but is not yet cached

![captura de tela de 2018-10-09 17-22-58](https://user-images.githubusercontent.com/11314585/46695652-92c37600-cbe6-11e8-9b56-e3e5b3162cef.png)

![captura de tela de 2018-10-09 17-27-18](https://user-images.githubusercontent.com/11314585/46695768-ca322280-cbe6-11e8-8605-451eab24eda3.png)

**Comment by philipwalton** [comment]
@GlauberF I think your regex is wrong, try something like this: 

```js
new RegExp('https://api-production.vimbo.com.br/graphql\\?query.*');
```
