### ISSUE TITLE
Automate npm dependency updates

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1696]
As mentioned at https://github.com/GoogleChrome/workbox/issues/1656#issuecomment-428693893, a tool like @renovatebot could help keep things up to date.

**Comment by Nazanin1369** [comment]
RenovateBot is a good choice. Do we want to pin version for any dependency?

**Comment by jeffposnick** [comment]
I've recently been using a combination of `npx npm-check-updates` along with an [exclusion list](https://github.com/GoogleChrome/workbox/blob/d966d798a5e6ef4c16f090fa17a016d6060f9740/.ncurc.js) of packages that we can't update due to either Node version incompatibilities or breaking API changes that we can't accommodate. I think that strikes the right balance between automation and manual overrides.
