### ISSUE TITLE
Typo on a snippet in the Advanced Recipes page

### ISSUE THREAD

**Issue by TheMightyPenguin** [GoogleChrome/workbox#1713]
**Library Affected**: 
*workbox-sw*

**Browser & Platform**: None, docs typo.

**Issue or Feature Request Description**: I found a typo in the documentation for "Advanced Recipes", specifically in the "Provide a fallback response to a route" here:

https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route

The typo is on the 1st snippet of that section:

```js
const FALLBACK_IMAGE_URL = '/images/fallback.png';

workbox.routing.registerRoute(
  new RegExp('/images/'),
  async ({event}) => {
    try {
      return await workbox.strategies.cacheFirst().handle({event});
    } catch (error) {
      return caches.match(FALLBACK_IMAGE_URL);
    }
  }
} /* <-- this extra bracket is the typo */ );
```

So, could I please open a PR to fix this little typo?

**Comment by philipwalton** [comment]
Hmmm, I see it correctly when I go to that page:

<img width="890" alt="screen shot 2018-10-16 at 5 11 04 pm" src="https://user-images.githubusercontent.com/326742/47054422-8ef39e80-d166-11e8-95f0-7f49d2962bf6.png">

Also, the source code for that page shows it correctly: https://github.com/google/WebFundamentals/blob/master/src/content/en/tools/workbox/guides/advanced-recipes.md

**Comment by TheMightyPenguin** [comment]
Hey @philipwalton, here's an image to be more clear about what I mean:

<img width="1225" alt="screen shot 2018-10-16 at 11 03 03 pm" src="https://user-images.githubusercontent.com/11748696/47061642-f9710280-d197-11e8-830b-151ecb87655a.png">

Also, if you put that snippet on the babel repl it will throw an error and won't transpile, [you can check it here](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAYgQQDJIEIIMIGkD6BJAWQQHEBRHAVQCUkYBeGAcgHoBLAWwEMBzAUwmYAzTgBsRAI07AA1gDoADmG6MA3ACg1AdxAAnaeJAAPWTpABXKKyUne3VtF46q5qLwAUamDDC9NMKrakhvJuLBw8_MyMAJQANJ4wnBAAnmDAMG4A3rwAbrxgUAC-0fQAfDCZCV5QOskVVV4wOrxQZjpgiZqcrLDaegbG0Dqcrnb8ssBSABa8cKw60G7RslOcYAAmIu7ZeQXF6o0whTCTUMBTGY6mOiWVh17Nre0n0-NcZ1NuiCjo2PhEZEoNGiB0ahQS4P2aiAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

**Comment by philipwalton** [comment]
Ahh, sorry, I thought the snippet you were showing was the one you were saying was incorrect. I see the error now.

If you want to submit a PR you can submit it to the https://github.com/google/WebFundamentals repo, and I'll approve it.

**Comment by TheMightyPenguin** [comment]
Hello @philipwalton, just opened the PR 😄 https://github.com/google/WebFundamentals/pull/6739

**Comment by philipwalton** [comment]
Thanks! Merged.
