### ISSUE TITLE
_isResponseDateFresh store with service time ; but get with local time?

### ISSUE THREAD

**Issue by wxungang** [GoogleChrome/workbox#1714]
packages/workbox-cache-expiration/plugin.mjs

```js
  _isResponseDateFresh(cachedResponse) {
    if (!this._maxAgeSeconds) {
      // We aren't expiring by age, so return true, it's fresh
      return true;
    }

    // Check if the 'date' header will suffice a quick expiration check.
    // See https://github.com/GoogleChromeLabs/sw-toolbox/issues/164 for
    // discussion.
    const dateHeaderTimestamp = this._getDateHeaderTimestamp(cachedResponse);
    if (dateHeaderTimestamp === null) {
      // Unable to parse date, so assume it's fresh.
      return true;
    }

    // If we have a valid headerTime, then our response is fresh iff the
    // headerTime plus maxAgeSeconds is greater than the current time.
    const now = Date.now();
   //todo:  if local time is later then service time？
    return dateHeaderTimestamp >= now - (this._maxAgeSeconds * 1000);
  }
```

  **question：**
   //todo:  if local time is later then service time？

    const now = Date.now();
    return dateHeaderTimestamp >= now - (this._maxAgeSeconds * 1000);

**Comment by EvsChen** [comment]
Hi @wxungang. Here is my naive understanding.
If you're referring to **time zone** by "local time later than service time", both `Date` header and `Date.now()` are in UTC. They will return the same number no matter which time zone you're in.
Refer to [Headers/Date](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) and [Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) for details on `Date`.
If you're not talking about time zone, pls further clarify your problem.

**Comment by wxungang** [comment]
@EvsChen not about time zone 。Time is out of sync between local and server in the same time zone!

we have set maxAgeSeconds:5*60 (5min)。
but the local time（now) - server time (dateHeaderTimestamp) > maxAgeSeconds。

**Comment by jadjoubran** [comment]
@wxungang have you tested that this is actually what's happening?
Because I don't think the timezone on your server matters as the time workbox is comparing against the time the document was received and as @EvsChen mentioned everything is in UTC.

Feel free to post your configuration (the service worker code that uses maxAgeSeconds) so that I can check what's wrong
