### ISSUE TITLE
background sync plugin doesn't work after refresh 

### ISSUE THREAD

**Issue by nuritlh** [GoogleChrome/workbox#1724]
using workbox (workbox-webpack-plugin: ^3.5.0) and background sync plugin.
Chrome version 70 and windows 10.
1 .When sending post request online all works.
2. When sending post request offline and return to online all work (entering to queue).
3. When sending post request offline then refresh the page then return online the post request does not sending and the queue still with the request.

what can be the issue? 
The above working on Mac + Chrome 69 and on another computer with windows-10 + Chrome 70

Thanks

**Comment by nuritlh** [comment]
fix by removing the flag in SW "update on reload"

**Comment by philipwalton** [comment]
> 3. When sending post request offline then refresh the page then return online the post request does not sending and the queue still with the request.

Is the `sync` event firing in that case? If not then it's not a workbox issue but rather an issue with when the browser fires the `sync` event.

Can you confirm?
