### ISSUE TITLE
Networkonly and fallback

### ISSUE THREAD

**Issue by 2803media** [GoogleChrome/workbox#1729]
**Library Affected**:
workbox 3.6

**Browser & Platform**:
Google Chrome

**Issue or Feature Request Description**:

The aim is to cache some pages and exclude others (with networkonly). If the network connexion is not available the is a fallback to an "offline.html" page. 

The problem is that the pages excluded with the networkonly don't throw the offline.html... did I miss something or is the networkonly don't have fallback?

```
if ('function' === typeof importScripts) {
  importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-sw.js');
  if (workbox) {
    console.log(`Yay! Workbox is loaded 🎉`);
  } else {
    console.log(`Boo! Workbox didn't load 😬`);
  }


  workbox.setConfig({
    debug: true
  });


  workbox.precaching.precacheAndRoute([
    {
      url: '/',
      revision: '1',
    },
    {
      url: '/offline.html',
      revision: '1',
    }
  ]);

  workbox.precaching.addRoute();


  workbox.routing.registerRoute(
    new RegExp('.*\.js'),
    workbox.strategies.networkFirst()
  );

  workbox.routing.registerRoute(
    // Cache CSS files
    /.*\.css/,
    // Use cache but update in the background ASAP
    workbox.strategies.staleWhileRevalidate({
      // Use a custom cache name
      cacheName: 'css-cache',
    })
  );


  workbox.routing.registerRoute(
    // Cache image files
    /.*\.(?:png|jpg|jpeg|svg|gif)/,
    // Use the cache if it's available
    workbox.strategies.cacheFirst({
      // Use a custom cache name
      cacheName: 'image-cache',
      plugins: [
        new workbox.expiration.Plugin({
          // Cache only 20 images
          maxEntries: 20,
          // Cache for a maximum of a week
          maxAgeSeconds: 7 * 24 * 60 * 60,
        })
      ],
    })
  );

  // Cache the Google Fonts webfont files with a cache first strategy for 1 year.
  workbox.routing.registerRoute(
    /^https:\/\/fonts\.googleapis\.com/,
    workbox.strategies.cacheFirst({
      cacheName: 'google-fonts-webfonts',
      plugins: [
        new workbox.cacheableResponse.Plugin({
          statuses: [0, 200],
        }),
        new workbox.expiration.Plugin({
          maxAgeSeconds: 60 * 60 * 24 * 365,
        }),
      ],
    }),
  );

var networkFirstHandler2 = workbox.strategies.networkOnly();

const matcher2 = new RegExp('/search/');
const handler2 = (args) => networkFirstHandler2.handle(args).then((response) => (!response) ? caches.match('/offline.html') : response);

workbox.routing.registerRoute(matcher2, handler2);


var networkFirstHandler = workbox.strategies.networkFirst({
  cacheName: 'pages-cache',
});

const matcher = ({event}) => event.request.mode === 'navigate';
const handler = (args) => networkFirstHandler.handle(args).then((response) => (!response) ? caches.match('/offline.html') : response);

workbox.routing.registerRoute(matcher, handler);

}

```

**Comment by jeffposnick** [comment]
Can you try out updating to https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0 and take a look at the recipe following "Starting in Workbox v4..." at https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route

We normalized strategy failures in Workbox v4 and this should be easier to write now, either with a "global" `catch` handler using `workbox.routing.setCatchHandler()` as in that recipe, or by chaining a `.catch()`to the end of a strategy promise, like:

```js
const handler = (args) => {
  return networkFirstHandler.handle(args)
    .catch(() => caches.match('/offline.html'));
};
```

I'm closing with the assumption that that clears things up for you, but please let us know if it doesn't!

**Comment by 2803media** [comment]
Thanks @jeffposnick, the zip file can't be opened (on my mac I get an error when decompressing it)

**Comment by jeffposnick** [comment]
Hmm, sorry about that—you can pull in the v4 build tools using something like `npm install workbox-build@alpha` (or `workbox-cli`, `workbox-webpack-plugin`).

If you're not using the build tools and just want to pull in the latest Workbox runtime code, you can switch your `importScripts()` statement to `importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0-alpha.0/workbox-sw.js');`

**Comment by 2803media** [comment]
Great I will try!

**Comment by jeffposnick** [comment]
Oops, I just noticed a typo in the recipe for v4. (I'll fix it.) `request` isn't actually a named parameter; the parameters passed to the catch handler are `{url, event, err}`.

So you would want:

```js
workbox.routing.setCatchHandler(({event}) => {
  switch (event.request.destination) {
    case 'document':
      return caches.match('/offline.html');
    break;

    default:
      // If we don't have a fallback, just return an error response.
      return Response.error();
  }
});
```

**Comment by 2803media** [comment]
No problem it's an alpha!

Here is my code, it's simple I don't know what I miss to make it works... The goal is to only have the home and offline.html to be cache as document and send other pages to offline.html when the network failed.  

With this I only have the homepage and errors for others pages! 

Thanks for your help

```
if ('function' === typeof importScripts) {
  //importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-sw.js');
  importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0-alpha.0/workbox-sw.js');
  if (workbox) {
    console.log(`Yay! Workbox is loaded 🎉`);
  } else {
    console.log(`Boo! Workbox didn't load 😬`);
  }


  workbox.setConfig({
    debug: true
  });


  workbox.routing.registerRoute(
    new RegExp('.*\.js'),
    workbox.strategies.networkFirst()
  );

  workbox.routing.registerRoute(
    // Cache CSS files
    /.*\.css/,
    // Use cache but update in the background ASAP
    workbox.strategies.staleWhileRevalidate({
      // Use a custom cache name
      cacheName: 'css-cache',
    })
  );


  workbox.routing.registerRoute(
    // Cache image files
    /.*\.(?:png|jpg|jpeg|svg|gif)/,
    // Use the cache if it's available
    workbox.strategies.cacheFirst({
      // Use a custom cache name
      cacheName: 'image-cache',
      plugins: [
        new workbox.expiration.Plugin({
          // Cache only 20 images
          maxEntries: 20,
          // Cache for a maximum of a week
          maxAgeSeconds: 7 * 24 * 60 * 60,
        })
      ],
    })
  );

  // Cache the Google Fonts webfont files with a cache first strategy for 1 year.
  workbox.routing.registerRoute(
    /^https:\/\/fonts\.googleapis\.com/,
    workbox.strategies.cacheFirst({
      cacheName: 'google-fonts-webfonts',
      plugins: [
        new workbox.cacheableResponse.Plugin({
          statuses: [0, 200],
        }),
        new workbox.expiration.Plugin({
          maxAgeSeconds: 60 * 60 * 24 * 365,
        }),
      ],
    }),
  );


workbox.precaching.precacheAndRoute([
  {
    url: '/',
    revision: '1',
  },
  {
    url: '/offline.html',
    revision: '1',
  }
]);

workbox.precaching.addRoute();


workbox.routing.setCatchHandler(({event}) => {
  switch (event.request.destination) {
    case 'document':
      return caches.match('/offline.html');
    break;

    default:
      // If we don't have a fallback, just return an error response.
      console.log('error');
      return Response.error();
  }
});


}

```

**Comment by 2803media** [comment]
Finally I use an old method which works:

```
self.addEventListener('fetch', function(event) {
  event.respondWith(
    caches.match(event.request).then(function(response) {
      return response || fetch(event.request);
    }).catch(function() {
      return caches.match('/offline.html');
    })
  );
});

```

**Comment by jeffposnick** [comment]
That code is really not a good example to follow. It's going to end up returning a `Response` with HTML content for *any* network request that fails, even if it's a request for, say, an image.

If you really want to keep things simple and leave Workbox out of it, you need to adjust that code to check for `event.request.mode === 'navigate'` (or `event.request.destination === 'document'`), and only fall back to the cached HTML page if that's the case.

**Comment by jeffposnick** [comment]
Yup, I understand, and apologies about that—I still need to dig in to the code you're using to figure out why things are going wrong.

I just wanted to let you know *not* to use that vanilla service worker code as-is, since there's a bug in the logic.

**Comment by 2803media** [comment]
Thanks for this warning !

**Comment by salehdeh76** [comment]
Does the `workbox.routing.setCatchHandler` works fine in chrome offline mode? It seems in that case, the setCatchHandler does not even run! (a console.log is not printing!)

My code is this:
```
workbox.routing.setCatchHandler(({event}) => {
    console.log("setCatchHandler");
    console.log(event.request.mode);
    if (event.request.mode === "navigate") {
        return cache.match(
            workbox.precaching.getCacheKeyForURL('/not_connected.html')
        );
    }
});

```

But when switch to offline mode (in devtools) just the chrome network error is showing!

**Comment by adilhafiz** [comment]
@jeffposnick I have been trying to handle the above case and finally managed to use the below code to redirect user to offline page for all network requests. But I also want to cache my CSS and JS files and when I am doing that, I cant see them in my cache storage...Any ideas what is going wrong with it?

My Code is: 
importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0/workbox-sw.js');

if (workbox) {
        //const CACHE_PREFIX = 'XD';

        workbox.setConfig({
            clientsClaim: true,
            debug: true,
            skipWaiting: true
        });

        workbox.core.setLogLevel(workbox.core.LOG_LEVELS.warn);

       

        const CACHE_NAME = 'offline-html';
    // This assumes /offline.html is a URL for your self-contained
    // (no external images or styles) offline page.
        const FALLBACK_HTML_URL = 'Offline.html';
    // Populate the cache with the offline HTML page when the
    // service worker is installed.
        self.addEventListener('install', function (event) {
            event.waitUntil(
              caches.open(CACHE_NAME)
                .then((cache) => cache.add(FALLBACK_HTML_URL))
            );
        });

        workbox.navigationPreload.enable();

        const networkOnly = new workbox.strategies.NetworkOnly();
        const navigationHandler = function (params) {
            try {
                return new Promise(function (resolve, reject) {
                    return resolve(networkOnly.handle(params));
                })
                // Attempt a network request.                   

            } catch (error) {
                // If it fails, return the cached HTML.
                return caches.match(FALLBACK_HTML_URL, {
                    cacheName: CACHE_NAME,
                });
            }
        };

    // Register this strategy to handle all navigations.
        workbox.routing.registerRoute(
          new workbox.routing.NavigationRoute(navigationHandler)
        );




    // Javascript and CSS rule
        workbox.routing.registerRoute(
          /^.*(js|css)$/,
          workbox.strategies.staleWhileRevalidate({
              cacheName: 'XD-assets',
              plugins: [
                new workbox.expiration.Plugin({
                    maxEntries: 20,
                }),
                new workbox.cacheableResponse.Plugin({
                    statuses: [200]
                })
              ]
          })
        );

**Comment by guanzo** [comment]
@jeffposnick 

> request isn't actually a named parameter; the parameters passed to the catch handler are {url, event, err}.

Is this no longer true? I'm using workbox with all packages at 5.1.2. If i log the arguments to `setCatchHandler`, I see the same the same args that regular handlers receive, `{event, request, url}`, not `{url, event, err}`. 

Knowing the error at this point is useful to me. I only want to fallback to offline.html if the navigation request resulted in a connection error. Any other kind of error should be handled differently.

**Comment by jeffposnick** [comment]
You're correct; the current code uses `{url, request, event}` as the parameters to the handler.

https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-routing/src/Router.ts#L255

I'd suggest writing a custom `handlerCallback` if you want more fine-grained behavior, instead of using a built-in strategy, like so:

```
const networkOnly = new NetworkOnly({...});

const networkOnlyWithCustomFallback = async (params) => {
  try {
    return await networkOnly.handle(params);
  } catch (workboxError) {
    // This is wrapped as a WorkboxError
    const error = workboxError.details ?
      workboxError.details.error :
      undefined;

    // Do whatever validation you need against error.
    if (error === ...) {
      return caches.match(OFFLINE_URL);
    }

    // Otherwise, just return the exception.
    return workboxError;
  }
};

registerRoute(
  ({request}) => request.mode === 'navigate',
  networkOnlyWithCustomFallback,
);
```

(This will be cleaner in v6, as you'll be able to extend a base `Strategy` class and implement a custom strategy in a more "formal" way: #2455)
