### ISSUE TITLE
SW onupdatefound not triggered

### ISSUE THREAD

**Issue by debianw** [GoogleChrome/workbox#1734]
**Library Affected**:
*workbox-webpack-plugin@3.6.3

**Browser & Platform**:
*Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Issue or Feature Request Description**:
*When testing my app in localhost then the `onupdatefound` is triggered and I can display a message telling about "new content available please close application". But when I testing with a domain using https then `onupdatefound` is not triggered but I can see where service worker change its state from `activated` to `waiting to activate`*

**Comment by philipwalton** [comment]
> But when I testing with a domain using https then onupdatefound is not triggered but I can see where service worker change its state from activated to waiting to activate

Can you show the code you're using?

**Comment by jeffposnick** [comment]
I'm going to close this as I don't believe it's actionable at this point.

If you could provide more details, like a live deployment URL, we can revisit.
