### ISSUE TITLE
Migration Doc's for upgrading from V3 to V4

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1737]
I know the V4 is still in Alpha, but I just wanted to ask for the near future.

Will there be any Migration Doc's showing us how to upgrade from V3 to V4?

Any link to bookmark would be amazing.

Many thanks.

**Comment by philipwalton** [comment]
Yes, there definitely will be once it's fully released. For now I'd recommend looking at the release notes for anything tagged `v4.*` (currently there's only [v4.0.0-alpha.0](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0)).

**Comment by jeffposnick** [comment]
This will be included as part of https://github.com/google/WebFundamentals/pull/7183 within the next week or so.
