### ISSUE TITLE
Firefox: Unable to import module 'workbox-strategies'

### ISSUE THREAD

**Issue by markbrocato** [GoogleChrome/workbox#1740]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Firefox 63.0 (64-bit)

**Issue or Feature Request Description**:
It looks like the presence of a service worker built with workbox causes a site not to load in Firefox.  Here's the site that's breaking: https://pwa.moovweb.com.  The site initially loads and works fine, but when the service worker is installed, all network calls fail.  Reloading the page will give a Corrupted Content Error.

Failed to load ‘https://pwa.moovweb.com’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘NetworkError: Failed to load worker script at https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-strategies.prod.js (nsresult = 0x8053000b)’.

**Comment by jeffposnick** [comment]
Your https://pwa.moovweb.com/pwa/serviceWorkerBootstrap.beb338b844d7de3d8a2e78f28f393d03.js script includes the following:

```
workbox.routing.registerRoute(matchRuntimePath, async (context) => {
  try {
    // ...snip...

    if (cacheOptions.cacheName === ssrCacheName && !shouldServeHTMLFromCache(url, event)) {
      return workbox.strategies.networkOnly().handle(context)
    }
    // ...snip...
  } catch (e) {
    // ...snip...
  }
})
```

Those references to `workbox.strategies.networkOnly().handle(context)` inside of your async callback function trigger the initial import of `workbox-strategies`, and you're not allowed to do that after the initial execution of the service worker scripts.

This change will [start being enforced in Chrome 71](https://developers.google.com/web/updates/2018/10/tweaks-to-addAll-importScripts) (at which point your service worker will stop working there, too), but other browsers, like Firefox, already block this behavior.

There is [guidance in the Workbox docs](https://developers.google.com/web/tools/workbox/modules/workbox-sw#avoid_async_imports) for avoiding this; following those steps will resolve the issue for you.
