### ISSUE TITLE
[workbox-build] Feature request: dynamic navigation route whitelist/blacklist

### ISSUE THREAD

**Issue by davidbailey00** [GoogleChrome/workbox#1743]
**Library Affected**:
workbox-sw

**Browser & Platform**:
All platforms

**Issue or Feature Request Description**:

Hi there! We're using Workbox as part of Gatsby's offline plugin, in order to enable loading pages cache-first and add offline support. In order to achieve this we're currently using `registerNavigationRoute`, via `generateSW` with the `navigateFallback` options - see [gatsby-plugin-offline/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/gatsby-node.js) for our configuration.

You'll see that we blacklist URLs which end in `?no-cache=1` or `&no-cache=1`. This is because different users may have a website using Gatsby, but some additional non-Gatsby pages - for example, Netlify CMS at `/admin/` to manage their site's content. Previously, if we visited `/admin/`, then the offline shell would be loaded, and Gatsby tries to find the page resources - it can't find them because this isn't a Gatsby page, and hence displays a 404.

To work around this problem, we added a check which requests the URL in the background with `?no-cache=1` appended, in order to see the actual HTTP status code it returns - if it displays a 404 then we continue to display the Gatsby 404 page, but otherwise, we redirect to the page at the `?no-cache=1` URL so that the offline shell isn't loaded. It is possible for users to add configuration to the offline plugin to override the default workbox-build options, but we perform this check to make it easy for users who want stuff to "just work" without having to specify which pages they don't want the service worker to handle.

What we're wondering is if there's a way to modify the navigation route blacklist dynamically, so that we can blacklist URLs at runtime instead of appending `?no-cache=1`? In theory this means that when Gatsby can't find resources, we temporarily blacklist the URL and request it in the background, then if it's a 404 we un-blacklist it and display the Gatsby 404 page - otherwise, we keep the blacklist and redirect to that URL. Basically, something very similar to what we're doing currently, but in a way which doesn't require modifying URLs.

Is this possible currently? We would find the proposed behaviour beneficial, because the current method means that `?no-cache=1` always has to be appended to non-Gatsby pages (unless the user overrides the default blacklist). This can further result in SEO problems, since Google treats the pages differently when they redirect to a page with a query string appended, and other potential problems if a webpage depends on data from its query string. If it's not currently possible, are there any other way we could go about doing this, other than instructing users to override the blacklist?

cc @pieh @dschau @kyleamathews

**Comment by KyleAMathews** [comment]
@jeffposnick would love to hear your thoughts on this issue!

**Comment by davidbailey00** [comment]
@jeffposnick Thanks a ton, this looks perfect for what we want to achieve! I'll have a go at implementing this today and let you know if I have any problems.

**Comment by jeffposnick** [comment]
Okay!

Again, I don't feel *great* about that approach, and would encourage being more aggressive about setting `navigateFallbackBlacklist` to some common admin-type patterns as a first step, and see whether that's sufficient. But if you're looking for something more dynamic, hopefully that code will put you in the right direction.

**Comment by DSchau** [comment]
@jeffposnick I think we've decided to lean towards the navigateFallbackBlacklist approach as a first step, and then exposing that option and making it configurable if there are patterns we aren't aware of/wouldn't know about!

Thanks again for your help on this!

**Comment by jeffposnick** [comment]
Great! I'm going to close this issue for now, but feel free to ping it if you need to revisit that decision.
