### ISSUE TITLE
Firefox: fails on SW register/update cause it search previous precache-manifest file

### ISSUE THREAD

**Issue by coluccini** [GoogleChrome/workbox#1745]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Firefox 63 / Mac 10.14

**Issue Description**:
I'm making a web using create-react-app and after each webpack build, the first time you access the web using firefox the SW registration/update throws the following error:

```Failed to register/update a ServiceWorker for scope ‘http://localhost:5001/’: Bad Content-Type of ‘text/html’ received for script ‘http://localhost:5001/precache-manifest.de30338a2157ba31db15cdfbb191cd3e.js’.  Must be ‘text/javascript’, ‘application/x-javascript’, or ‘application/javascript’.```

The file `precache-manifest.de30338a2157ba31db15cdfbb191cd3e.js` is the file used by the previous build, it doesn't exist any longer so it fails. I thought it could be related to the SW being cached, but it isn't (the `no-cache` headers are there). I've tried it on Chrome and Safari and it always works well.

Because of this error, the onUpdate() method never gets trigger and the user doesn't know that they should reload the page to get the new code…

*Steps to reproduce*

- Create a brand new CRA app
- Change `serviceWorker.unregister()` to `serviceWorker.register()` at `src/index.js`
- Run `yarn build` and run it `serve -s build -c ./serve.json` (where serve.json has the config to avoid SW being cached)
- Access the web
- Make any change on the app code
- Build and run again
- Access the web

**Comment by jeffposnick** [comment]
I believe I've seen this before, and what you describe amounts to some logging noise in Firefox, rather than something that affects the update process. When I tried this just now using Firefox Nightly (v65), the failed attempt to re-validate the manifest which was previously stored using `importScripts()` did not affect the update flow.

Can you modify your process to do the following:

- Access the web
- Make any change on the app code
- Build and run again
- Access the web
- **Visit some other site/close the current tab**
- Access the web

I believe what you're seeing is just the normal expected behavior when a service worker [without `skipWaiting` is used](https://jeffy.info/2018/10/10/sw-in-c-r-a.html), where the updated precached resources aren't used until all of the current clients have navigated away/closed.

**Comment by coluccini** [comment]
I'm using `skipWaiting` and `clientsClaim`. I'm doing all kind of tests (closing the tab, closing the browser, etc) but it never reachs this point:
```javascript
registration.onupdatefound = () => {
  const installingWorker = registration.installing;
  installingWorker.onstatechange = () => {
    if (installingWorker.state === 'installed') {
      if (navigator.serviceWorker.controller) {
        // Ask the user to reload <---
```
In fact, it never gets into `registration.onupdatefound = () => {`…

I had assumed that the error was causing it, but if you say that it shouldn't be interfering I will try to find another culprit… thanks!

**Comment by jeffposnick** [comment]
Hmmm... the Workbox-generated service worker in the latest `c-r-a` makes it kind of tricky to use `skipWaiting` and `clientsClaim`. So how are you using them?

**Comment by coluccini** [comment]
I'm using `react-app-rewired` to be able to use `InjectManifest` into a SW previously generated using `GenerateSW` (now is a static file) that it has a pretty basic config:

```javascript
// importScripts() are injected here

workbox.skipWaiting();
workbox.clientsClaim();
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});
workbox.routing.registerNavigationRoute('/index.html', {
  blacklist: [/^\/__/, /\/[^\/]+.[^\/]+$/, /^\/service-worker.js/, /^\/robots.txt/, /^\/manifest.json/, /^\/favicon.ico/, /^\/icons\//],
});

// Push notification handling stuff
```

I know you're pretty busy, but If you could take a look to this at some point I would be really grateful: 

https://stackoverflow.com/questions/53074166/workbox-service-worker-removed-precached-files-and-avoid-serving-them-this-sess

Thanks!

**Comment by coluccini** [comment]
UPDATE: I've upgrade workbox, CRA and the content on the `serviceWorker.js` file (called `registerServiceWorker.js` in my version) and it's working now. I think updating the file is what make it work (even when, at first sight, they look basically the same). 
Thanks a lot!
