### ISSUE TITLE
Errors in Docs about "Migrate from sw-precache or sw-toolbox"

### ISSUE THREAD

**Issue by SukkaW** [GoogleChrome/workbox#1746]
**Library Affected**:

None.

**Browser & Platform**:

It doesn't matter :)

**Issue or Feature Request Description**:

I am reading the docs about [Migrate from sw-precache or sw-toolbox - sw-toolbox migrations](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw#sw-toolbox_migrations), trying to migrate from sw-toolbox to workbox, but got `undefined` when I was trying with code snippets provided.
Then I found out that in the code snippets they are using `workbox.router`, not `workbox.routing`.

![image](https://user-images.githubusercontent.com/40715044/47794494-910b4f00-dd5b-11e8-9e74-7e088ca55851.png)

**Comment by jeffposnick** [comment]
Thanks! This will be fixed in https://github.com/google/WebFundamentals/pull/6792
