### ISSUE TITLE
[InjectManifest]: Getting error "TypeError: Cannot read property 'readFile' of null"

### ISSUE THREAD

**Issue by pratikraj-mob-incedo** [GoogleChrome/workbox#1749]
I am getting following error when I am using "workboxPlugin.InjectManifest" in my webpack config.

WebPack Config:
`{
	  new WorkboxPlugin.InjectManifest({
	    swSrc: paths.rap('src/sw.js'),
		swDest: 'static/js/sw.js'
	  })
}`

When I run build, I get following error:
![image](https://user-images.githubusercontent.com/20592758/48047896-93d4cc80-e1bf-11e8-881f-d60791e7422b.png)

**Comment by jeffposnick** [comment]
What version of `webpack`, and what version of `workbox-webpack-plugin` are you using?

**Comment by jeffposnick** [comment]
I'm going to close this issue given the lack of additional info, but if you could provide the version that you're using, we can reopen and investigate further.

**Comment by TuffyLiu** [comment]
"webpack": "^1.13.2",
"workbox-webpack-plugin": "^3.6.3",
have same error.

**Comment by TuffyLiu** [comment]
@jeffposnick

**Comment by jeffposnick** [comment]
@TuffyLiu, `webpack` v1 isn't supported by `workbox-webpack-plugin`. Please update to at least `webpack` v2 if you'd like to use Workbox along with `webpack`.
