### ISSUE TITLE
workbox-webpack-plugin: accept chunk names in importScripts

### ISSUE THREAD

**Issue by gashawmola** [GoogleChrome/workbox#1752]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
All browsers.

**Issue or Feature Request Description**:
Background: I want to use the generated service worker from `WorkboxWebpackPlugin.GenerateSW` to handle precache of files but I want to handle `push` events from another script.
Right now imported scripts in service worker are not updating if changed, like the service worker itself does.

It would be very helpful if I could put the other script in a chunk and specify that chunk name in the `importScripts` option (right now you can only specify static file names.)
This way the service worker itself would update on any change in the push handling script (because of fingerprint) and I would avoid above issue.

(btw `sw-precache-webpack-plugin` does provide this capability)

**Comment by jadjoubran** [comment]
Hey @gashawmola 
Is [chunks](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generateSW-chunks) what you're looking for? as you could list out the name of the chunks

**Comment by gashawmola** [comment]
Hi @jadjoubran , thanks for the reply.
The chunks option, as I understand it, is for specifying which chunks to precache assets from.
What I'm looking for is a way to specify chunks in the `importScripts` option. Does it make sense?

**Comment by jadjoubran** [comment]
Oh okay, I got it now
it sounds like a feature request to me, @jeffposnick can you please verify that?

**Comment by jeffposnick** [comment]
Thanks for the feature request. I've added it to the [Big List of webpack Work](https://github.com/GoogleChrome/workbox/issues/1591) that needs to be done 😄

**Comment by jeffposnick** [comment]
This is slated for v5: #2131.

A couple of things to note:
- Passing in a chunk to `importScriptsViaChunks` will automatically add that chunk to the `excludeChunks` list, meaning that the files in that chunk won't be precached. `importScripts()` maintains its own cache of imported script files.
- You should take care that each file in the imported chunk has a hash as part of its filename. The service worker implementation in all browsers at this time will *not* check for updates to imported scripts unless the URL of the script changes.

**Comment by gashawmola** [comment]
Thanks @jeffposnick :clap:
