### ISSUE TITLE
'TypeError: Cannot supply flags when constructing one RegExp from another' when using  workbox.injectManifest

### ISSUE THREAD

**Issue by zhentian-wan** [GoogleChrome/workbox#1755]
**Library Affected**:
*workbox-build.*

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:
For **node.js version 4.2.2, or 4.x version**, build tool: **gulp**.

```js
var workbox = require('workbox-build');
gulp.task('sw', () => {
  return workbox.injectManifest({
    ...
  });
});
``` 

Has error: `TypeError: Cannot supply flags when constructing one RegExp from another
    at new RegExp (native)
    at Object._callee$ (/opt/jenkins/workspace/main-lobby/base-1.1.16.1/build/node_modules/workbox-build/build/entry-points/inject-manifest.js:54:28)`

**Comment by jadjoubran** [comment]
Hey @zhentian-wan 
Thanks for opening an issue here!
Can you please show the actual configuration inside `injectManifest`? feel free to rename your URLs to example.com
