### ISSUE TITLE
Workbox-build, empty callbacks for backgroundSync runtimeCaching options

### ISSUE THREAD

**Issue by dandro32** [GoogleChrome/workbox#1761]
Hi, 
I'm currently working on project based on Create React App v2.1.0 , that includes build-in workbox.
I'm generating a service worker using workbox-build. In runtimeCaching I have several caching options, including backgroundSync option, where I want to include some custom action after queueDidReplay
![2018-11-16 11_48_55-sw](https://user-images.githubusercontent.com/32488988/48617596-2717ba00-e997-11e8-9fdf-b209df731fec.png)

However, on my generated service worker there is no callback options.
![sw2](https://user-images.githubusercontent.com/32488988/48617744-98576d00-e997-11e8-8455-ae44522b26f0.png)

Is this option is available? Or this is CRA issue?
Would be gratefull for any directions or hints.
Thanks.

**Comment by jeffposnick** [comment]
We do make an attempt to transfer free-form `function` definitions inside of the `runtimeCaching` config into the final generated service worker code by using the `stringify-object` module under the hood, but only for entries in the `options.plugins` section: https://github.com/GoogleChrome/workbox/blob/b146d8d3c2db89fa51afc322049b9795894bb4f2/packages/workbox-build/src/lib/runtime-caching-converter.js#L32-L38

When using the shorthands for configuring the various plugins, like `options.backgroundSync`, we just use `JSON.stringify()`, which is what's causing what you're seeing: https://github.com/GoogleChrome/workbox/blob/b146d8d3c2db89fa51afc322049b9795894bb4f2/packages/workbox-build/src/lib/runtime-caching-converter.js#L75-L84

I think switching the `JSON.stringify()` there to use the same `stringify-object` wrapper we're using earlier would take care of the issue.

**Comment by jeffposnick** [comment]
This is fixed in Workbox v4.
