### ISSUE TITLE
Errata Workbox Documentation 

### ISSUE THREAD

**Issue by rhroyston** [GoogleChrome/workbox#1768]
Change "of" to "or" at workbox documentation https://developers.google.com/web/tools/workbox/guides/configure-workbox#configure_debug_builds_vs_production_builds

> If you are using the modules directly (via CDN **of** from npm modules)

Also, change "unsure" to "ensure" here: https://developers.google.com/web/tools/workbox/guides/generate-service-worker/cli

> as this will **unsure** your service worker

**Comment by jeffposnick** [comment]
Thanks a ton, @rhroyston! I've filed https://github.com/google/WebFundamentals/pull/6903 on your behalf 😄
