### ISSUE TITLE
Content Download of bundle.js is tremendously higher after registering SW

### ISSUE THREAD

**Issue by kristof0425** [GoogleChrome/workbox#1780]
**Library Affected**:
`workbox-webpack-plugin`

**Browser & Platform**:
Google Chrome v70 for Mac

**Issue or Feature Request Description**:
I'm using `workbox-webpack-plugin`'s `GenerateSW` and there is one thing, which I can't make up my mind about.

After registering and refreshing the web app for the 2nd time the `Content Download` property of our `bundle.js` got tremendously higher.

Here you can see the timing of the `bundle.js` **on the network, without service-worker**:

<img width="499" alt="screenshot 2018-12-07 at 14 32 33" src="https://user-images.githubusercontent.com/20532589/49650618-28378680-fa2d-11e8-98a0-f17009cd5d09.png">

Here are the results with the **service-worker registered and everything is cached**:

<img width="500" alt="screenshot 2018-12-07 at 14 37 33" src="https://user-images.githubusercontent.com/20532589/49650897-038fde80-fa2e-11e8-8c91-b8e994db9274.png">

The config we use in webpack:

```js
new GenerateSW({
        swDest: 'sw.js',
        include: [PATTERNS.HTML, PATTERNS.CSS, PATTERNS.JS],
        exclude: [PATTERNS.FONTS, PATTERNS.IMGS, PATTERNS.HOT_UPDATES],
        skipWaiting: true,
        clientsClaim: true,
        cacheId: 'my-app',
        ignoreUrlParametersMatching: [/idCompany/],
        directoryIndex: 'dist/index.html',
        runtimeCaching: [
          {
            urlPattern: PATTERNS.JS,
            handler: 'staleWhileRevalidate',
            options: {
              cacheName: 'my-app-js',
            },
          },
          {
            urlPattern: PATTERNS.CSS,
            handler: 'staleWhileRevalidate',
            options: {
              cacheName: 'my-app-css',
            },
          },
          {
            urlPattern: PATTERNS.FONTS,
            handler: 'cacheFirst',
            options: {
              cacheName: 'my-app-fonts',
              expiration: {
                maxAgeSeconds: 30 * 7 * 24 * 60 * 60,
              },
            },
          },
          {
            urlPattern: PATTERNS.IMGS,
            handler: 'cacheFirst',
            options: {
              cacheName: 'my-app-images',
              expiration: {
                maxAgeSeconds: 7 * 24 * 60 * 60,
              },
            },
          },
        ],
      })
```

I read this [article](https://developers.google.com/web/tools/chrome-devtools/network-performance/understanding-resource-timing) about the issue, but it only said that we should need to decrease the resource file size... We are already planning to code-split our bundle, but still, I'd like to know what goes under the hood.

**Could you tell me what causes this big difference in the `Content Download`?**

Btw, this question has also been asked by someone else on [StackOverflow](https://stackoverflow.com/questions/51354926/content-download-time-is-high-even-more-than-http-request-itself), but no one has answered for 4 months.

Thanks in advance!

**Comment by philipwalton** [comment]
Many factors (network latency, disk speed, etc) can cause a wide variance in these resource timing values, even for the exact same resource loaded the exact same way.

I'm not sure the difference you're seeing is the result of Workbox or service worker, and even if it were, it's impossible to say from just looking at the results from two runs without any additional context.

If you suspect that Workbox is doing something incorrectly here, please provide more details, and we can help diagnose the problem. But general questions about why a single resource timing value is higher than expected are probably out of scope for Workbox issues.

**Comment by philipwalton** [comment]
By the way, if you're curious to learn more about how service worker can affect performance (both positively and negatively), you might find this recent talk I gave at Chrome Dev Summit interesting: https://youtu.be/25aCD5XL1Jk

**Comment by kristof0425** [comment]
Thanks, @philipwalton for your detailed answer and special thanks for linking your recent talk! Watching your video was eye-opening for me.

I don't think that Workbox does something incorrectly here, I just wanted to understand better what might cause this big difference in the `bundle.js` loading.

You mentioned I should provide more *details* if I suspect something wrong from Workbox's side. **What *details* should I look for, if I'd like to dig deeper into this "issue" on my own?**

**Comment by philipwalton** [comment]
That's probably too big of a topic to go into here, but in general I was asking if you thought there was a mistake in Workbox's logic. For example, if you read a comment and then the following line of code seemed to not do what the comment said it was doing (something like that).

Also, if you add the metrics like I suggest in my talk to your site and then track the results for a large set of visitors and determine that a particular Workbox strategy (for example) is slow. That would be interesting for us to dive into. But if it's just a single instance it's usually the result of too many factors to do anything about.
