### ISSUE TITLE
revision is same for different files

### ISSUE THREAD

**Issue by rolandstarke** [GoogleChrome/workbox#1784]
**Library Affected**:
*workbox-webpack-plugin@3.6.3*

**Issue or Feature Request Description**:
*The revision is the same for css and js files, this results in an update of both even if only one is changed.*

Here the resulting precache-manifest
```javascript
self.__precacheManifest = [
  //[...]
  {
    "revision": "eff352b7020bf1abb0f7", //<-- 
    "url": "/js/app.12d0499e.js"
  },
  {
    "revision": "eff352b7020bf1abb0f7", //<-- 
    "url": "/css/app.e8acb75f.css"
  }
];
```

My vue.config.js file (using https://www.npmjs.com/package/@vue/cli-plugin-pwa)

```javascript
process.env.VUE_APP_VERSION = (new Date()).toISOString();

module.exports = {
    devServer: {
        proxy: 'http://localhost:8000'
    },
    // ...other vue-cli plugin options...
    pwa: {
        name: 'My App',
        themeColor: '#4DBA87',
        msTileColor: '#000000',
        appleMobileWebAppCapable: 'yes',
        appleMobileWebAppStatusBarStyle: 'black',
        workboxPluginMode: 'InjectManifest',
        workboxOptions: {
            //https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin
            swSrc: __dirname + '/public/service-worker.js',
            importWorkboxFrom: 'local',
        }
    }
}
```

**Comment by rolandstarke** [comment]
Here is the code that assigns the same hash to all files in a chunk:

https://github.com/GoogleChrome/workbox/blob/b146d8d3c2db89fa51afc322049b9795894bb4f2/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L110-L119

**Comment by jeffposnick** [comment]
This is definitely an area where improvement is needed—I believe https://github.com/GoogleChrome/workbox/issues/1454 already tracks this, and I'm closing this issue in favor of that.

If you're asking about a different issue, then please let us know and we can reopen this request.
