### ISSUE TITLE
[question] Bypassing ServiceWorker for certain URL requests

### ISSUE THREAD

**Issue by rtm619** [GoogleChrome/workbox#1788]
Hi,

I have a web app that I'm serving from Azure. I have written a redirection rule where if any URL ends with a '/' route, it will be redirected to its non-slash counterpart so that the app doesn't serve same pages from different routes. If I don't use workbox, the redirection works as expected and I get my non-slash route when I request for its with-slash counterpart. But if I use workbox, the request goes through the SW and my redirection doesn't get reflected in the url and it serves both the slash and non-slash URLs. This affects SEO for my website. Is there a way to bypass the service worker for the with-slash requests so that it gets 301 redirection to its non-slash counterpart?

Thanks in advance.

**Comment by rolandstarke** [comment]
Hi,

could you share some more infos how you use workbox? I could not confirm it. I testet it and requested `/storage` and got correctly redirected to `/storage/`. The workbox debug output is:
```
workbox Precaching found no match for /storage 
workbox Precaching found no match for /storage/
```


Btw you can also use `<link rel="canonical" href="/yourpage/" />` in case 2 urls serve the same content.

**Comment by rtm619** [comment]
I'm using the SSG Gatsby and its plugin "gatsby-offline". 
My workbox config: 
```
{
        importWorkboxFrom: `local`,
        cacheId: `gatsby-plugin-offline`,
        globDirectory: 'public/en-ca',
        globPatterns: ['index.html'],
        // Don't cache-bust JS or CSS files, and anything in the static directory,
        // since these files have unique URLs and their contents will never change
        dontCacheBustUrlsMatching: /(\.js$|\.css$|\/static\/)/,
        runtimeCaching: [
          {
            // Use cacheFirst since these don't need to be revalidated (same RegExp
            // and same reason as above)
            urlPattern: /(\.js$|\.css$|\/static\/)/,
            handler: `cacheFirst`,
          },
          {
            urlPattern: /^https?:.*\/$/,
            handler: `networkOnly`,
          },
          {
            urlPattern: /^https?:.*[^/]$/,
            handler: `networkFirst`,
          },
          {
            // Add runtime caching of various other page resources
            urlPattern: /^https?:.*\.(png|jpg|jpeg|webp|svg|gif|tiff|js|woff|woff2|json|css)$/,
            handler: `staleWhileRevalidate`,
          },
          {
            // Google Fonts CSS (doesn't end in .css so we need to specify it)
            urlPattern: /^https?:\/\/fonts\.googleapis\.com\/css/,
            handler: `staleWhileRevalidate`,
          },
        ],
        skipWaiting: true,
        clientsClaim: true,
      },
```
I am already using canonical urls in my pages.
I have mentioned my redirection rule in web.config:

```
<rule name="Remove trailing slash" stopProcessing="true">
          <match url="(.*)/$" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />   
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="false" />			  
          </conditions>
          <action type="Redirect" redirectType="Permanent" url="{R:1}" />
        </rule>
```
Can you tell me where I am going wrong with this?

**Comment by rolandstarke** [comment]
I am a little the lazy to set it all up. But based on the following answer https://stackoverflow.com/questions/27287982/remove-trailing-slash-from-the-url
your web.config should look like this:
```
<rewrite>
  <rules>

    <!--To always remove trailing slash from the URL-->
    <rule name="Remove trailing slash" stopProcessing="true">
      <match url="(.*)/$" />
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
      </conditions>
      <action type="Redirect" redirectType="Permanent" url="{R:1}" />
    </rule>

  </rules>
</rewrite>
```

Can you confirm the redirect is working? (In Firefox for example, you can bypass the service worker with CTRL + F5)

**Comment by rtm619** [comment]
Ok, I'll take a look at this. Whenever I removed the plugin, my url redirections would work. I'll do a deeper analysis and see what's up. But in the meanwhile, if there's any way to bypass SW for certain requests, I'd love to have it.

**Comment by philipwalton** [comment]
> But in the meanwhile, if there's any way to bypass SW for certain requests, I'd love to have it.

When a service worker is active, it intercepts all requests, and whatever routing logic you've applied will be run every time.

**Comment by jeffposnick** [comment]
I'm going to close this issue, primarily since web crawlers will not visit your site while controlled by a service worker.

I don't think there's anything specifically more that we can do.
