### ISSUE TITLE
Background-Sync on Chrome for Android Requires Service-Worker Restart to Sync.

### ISSUE THREAD

**Issue by kdesimini** [GoogleChrome/workbox#1789]
**Library Affected**:
workbox-sw, workbox-background-sync

**Browser & Platform**:
*E.g. Google Chrome 70 for Android*

**Issue**:
*When using background sync on chrome desktop, everything is working PERFECTLY. When I move over to a mobile device, background sync wont fire until I go into `chrome://serviceworker-internals` and restart the worker. Isn't this supposed to work in mobile chrome? Background sync api is supported for chrome on android.*

Everything is supported on https://www.caniuse.com
Here is a live version of the site. https://www.buslog.info
Here is the code on github. https://github.com/kdesimini/httpsprototypingtest

Service-worker.js
```

importScripts('workbox-3.6.3/workbox-sw.js');
workbox.setConfig({
  debug: false,
  modulePathPrefix: 'workbox-3.6.3/'
});
workbox.skipWaiting();
workbox.clientsClaim();
workbox.precaching.precacheAndRoute([]);

workbox.routing.registerRoute(
    /(http[s]?:\/\/)?([^\/\s]+\/)/,
    workbox.strategies.networkOnly({
      plugins: [
        new workbox.backgroundSync.Plugin('requestsQueue', {
          maxRetentionTime: 24 * 60 // Retry for max of 24 Hours
        })
      ]
    }),
    'POST'
  )

```

workbox-config.js
```
module.exports = {
    "globDirectory": "dist/testyo/",
    "globPatterns": [
      "index.html",
    "*.js",
    "*.css"
    ],
    "dontCacheBustUrlsMatching": new RegExp('.+\.[a-f0-9]{20}\..+'),
    "maximumFileSizeToCacheInBytes": 5000000,
    "swSrc": "src/service-worker.js",
    "swDest": "dist/testyo/service-worker.js"
  };
```

**Comment by philipwalton** [comment]
@kdesimini it's still not clear to me why you say it's not working?

Are you saying the `sync` event isn't firing, or are you saying the Workbox logic that responds to the `sync` event isn't running.

If it's the latter, we definitely want to look into it, but if it's the former, it's probably better to report it as a browser bug.

Also, be aware that there are some heuristics around when the `sync` event will fire. It not necessarily going to happen every time you lose and regain connectivity, but just to confirm, what happens when you do this:

1. Put your phone in airplane mode
2. Make a request (which should fail)
3. Turn off airplane mode
4. Wait for a few minutes

**Comment by kdesimini** [comment]
Well I don't have an SSL cert on that domain anymore but what was happening was:
1. I visited the webpage
2. Entered Airplane mode
3. Entered form data and made request
4. Waited 20 seconds
5. Turned off airplane mode
6. Waited 25 minutes
7. Nothing in the database
8. Went to chrome://serviceworker-internals
9. Restarted service worker
10. Database now has the data.

**Comment by philipwalton** [comment]
Hmmm, seem like 25 minutes should have been enough time. Though as I said before, for this to be a Workbox bug we'd have to know there are cases whether the `sync` event fires but the background sync logic doesn't run, and it's not clear whether that happened in this case. (It actually seems more likely that the background sync event didn't fire, which would be a Chrome/Android bug.)

**Comment by kdesimini** [comment]
I could even have my observables implemented incorrectly as well so I'll try to do some more digging into this after I get it setup with GitHub pages or something to register the worker. Should this issue stay open or should I close it? I appreciate all the help as well. I would be so lost if it wasn't for great teams like you guys.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by philipwalton** [comment]
Sounds good. Let's close it for now, but feel free to reply here or open up a new issue if you get more information that would help us reproduce the issue.

**Comment by dheerajsarwaiya** [comment]
what happened to this issue? I am having the same issue.. Background sync works perfectly in chrome on desktop. But on andorid it does not work till I reload service worker.
I used code from workbox site.

```
const queue = new workbox.backgroundSync.Queue("myQueueName");
self.addEventListener("fetch", event => {
  // Clone the request to ensure it's safe to read when
  // adding to the Queue.
  const promiseChain = fetch(event.request.clone()).catch(err => {
    return queue.pushRequest({ request: event.request });
  });

  event.waitUntil(promiseChain);
});
```

**Comment by philipwalton** [comment]
@dheerajsarwaiya as I said above, for this to be a Workbox bug we'd have to know there are cases where the sync event fires but the background sync logic doesn't run. Are you able to reproduce a case like that?

If not, then I think the best course of action would be to file a Chrome bug, as I suspect that's most likely what's happening here.
