### ISSUE TITLE
Script loading failed for a script cached with workbox strategy StaleWhileRevalidate

### ISSUE THREAD

**Issue by chestozo** [GoogleChrome/workbox#1800]
**Library Affected**:
workbox-strategies 3.6.3 (probably)

**Browser & Platform**:
I am testing on "Chrome/69.0.3497.100" based browser & Mac OS X 10.11.6

**Issue or Feature Request Description**:
I've posted a question on SO but no reaction for a week.
So I am copying it here too.

https://stackoverflow.com/questions/53707009/script-loading-failed-for-a-script-cached-with-workbox-strategy-stalewhilerevali

I am getting this error for some of my cached js files.  
Apparently for big ones.  
Also it happens kind of randomly on page refresh.

I am using workbox libs version 3.6.3.
This is my workbox setup for static files to be cached:

    workbox.routing.registerRoute(
        /.*\.js|css$/,
        workbox.strategies.staleWhileRevalidate({
            cacheName: 'my-static',
            plugins: [
                new workbox.cacheableResponse.Plugin({
                    statuses: [ 0, 200 ]
                }),
                new workbox.expiration.Plugin({
                    maxAgeSeconds: 60 * 60 * 24 * 10,
                    maxEntries: 10
                })
            ]
        }),
        'GET'
    );

Here is an example of what I am getting for one of my scripts.
[![enter image description here][2]][2]

This script is loaded by webpack generated script loader which is doing basically this:

    var head = document.getElementsByTagName('head')[0];
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.charset = 'utf-8';
    script.async = true;
    script.timeout = 120000;
    
    script.src = __webpack_require__.p + "_/" + chunkId + ".js";
    script.onerror = script.onload = onScriptComplete;

    function onScriptComplete() {
        ...
    };
    head.appendChild(script);

and I am getting `script.onerror` being called.

Does anyone have any ideas what can be possibly wrong?  
Apparently all works fine if I switch to `cacheFirst` strategy.

  [2]: https://i.stack.imgur.com/6KTmw.png

**Comment by jeffposnick** [comment]
_Apologies for the delay in getting back to you._

> and I am getting `script.onerror` being called.

Your code sets up the same callback for both `onload` and `onerror`, so I just wanted to confirm that it's actually being called due to an `error` event rather than `load`. What's the parameter that's passed in to the `onScriptComplete` callback?

Also, do you happen to have this deployed anywhere that we could test it out?

If not, the next best thing would be to include a screenshot of the Network panel traffic show the requests related to that JavaScript file. Also, could you expand the little arrow next to the failure logged in the Console to see if there is any additional context there.

**Comment by chestozo** [comment]
> Your code sets up the same callback for both `onload` and `onerror`, so I just wanted to confirm that it's actually being called due to an `error` event rather than `load`. What's the parameter that's passed in to the `onScriptComplete` callback?

yes, it is actually onerror that is being called
an `Error` object is passed with no details inside

**Comment by chestozo** [comment]
Posting created issue here too
https://bugs.chromium.org/p/chromium/issues/detail?id=934386

**Comment by jeffposnick** [comment]
Based on the details in that Chromium issue, periodic flakiness due to garbage collection is the likely culprit. There's not much we can do on the Workbox side, but it should be addressed via browser changes.

Thanks for bringing this to our attention!
