### ISSUE TITLE
workbox-range-request 3.6.2 does not load from CDN

### ISSUE THREAD

**Issue by dapetcu21** [GoogleChrome/workbox#1801]
**Library Affected**:
*workbox-range-requests*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
workbox-range-request 3.6.2 does not load from CDN

Trying to use `workbox.rangeRequests.createPartialResponse(request, cachedResponse);` results in:

```
Unable to import module 'workbox-range-requests' from 'https://storage.googleapis.com/workbox-cdn/releases/3.6.2/workbox-range-requests.dev.js' 
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://storage.googleapis.com/workbox-cdn/releases/3.6.2/workbox-range-requests.dev.js' failed to load.
    at Object.loadModule (https://storage.googleapis.com/workbox-cdn/releases/3.6.2/workbox-sw.js:1:1128)
    at Object.get (https://storage.googleapis.com/workbox-cdn/releases/3.6.2/workbox-sw.js:1:757)
    at respondFromCache (http://localhost:5000/custom-service-worker.js:6:18)
loadModule @ workbox-sw.js:1
get @ workbox-sw.js:1
respondFromCache @ custom-service-worker.js:6
```

**Comment by dapetcu21** [comment]
Nevermind. It works if I do `const createPartialResponse = workbox.rangeRequests.createPartialResponse` at the beginning of the file. Apparently it doesn't like an `importScripts` right in the middle of a `fetch` event.

**Comment by jeffposnick** [comment]
Right—please see https://developers.google.com/web/tools/workbox/modules/workbox-sw#avoid_async_imports
