### ISSUE TITLE
workbox offline, not find file index.html

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1802]
Because of the way the company and the system works, I can not add html files to the cache.

Automatically, I'm not caching the index.html file.

When I put my app offline, the error, because it can not load / find the file index.html

how can I get around this?

![deepin screenshot_selecionar area_20181219105559](https://user-images.githubusercontent.com/11314585/50221567-af192700-037c-11e9-9cbd-0bf6e512b14b.png)

**ps: my server is nginx**

**Comment by bestwestern** [comment]
I am interested in this as well.
I would like to have my app work offline.

**Comment by jeffposnick** [comment]
Do you want a custom offline HTML page that's shown when there's an offline navigation? Or are you asking about using runtime caching, rather than precaching, for your HTML?

**Comment by bestwestern** [comment]
I think I am asking for precaching :-/ 
I would like my manifest to look like this: (by default the html file is not included - I added manually)
If it looks like this the site will work even if I am offline (if I have previously visited the page)
![image](https://user-images.githubusercontent.com/3617433/51892338-da425d80-23a1-11e9-9e4e-4c16eac730a6.png)

**Comment by jeffposnick** [comment]
There's some guidance about the two topics raised here:

- [Using routing and a runtime caching strategy for HTML documents](https://developers.google.com/web/tools/workbox/guides/route-requests)
- [Providing an offline fallback page](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route)
