### ISSUE TITLE
making a file networkFirst

### ISSUE THREAD

**Issue by aprilmintacpineda** [GoogleChrome/workbox#1808]
USING: workbox-webpack-plugin.

I'm developing an SPA and I need CSRF protection. I put the csrf token in the index.html but then service worker would cache it after the first request, making the succeeding visits fail due to invalidity of csrf token provided by the client javascript.

I don't think it's good to exclude index.html from the precache manifest as that would defeat the purpose of making this app work offline.

I think what would be good is to tell the service worker to fetch the index.html on the network first, and if that fails then fallback to the cached file to make sure that it still works offline.

**Comment by jeffposnick** [comment]
> I think what would be good is to tell the service worker to fetch the `index.html` on the network first, and if that fails then fallback to the cached file to make sure that it still works offline.

You could do this by excluding the `index.html` from the precache manifest, and then implementing something like

```
workbox.routing.registerRoute(
  new workbox.routing.NavigationRoute(workbox.strategies.networkFirst())
);
```

inside of your service worker.

If you include `index.html` in the precache manifest, then you'll end up with a cache-first behavior for that HTML.
