### ISSUE TITLE
Workbox corrupt caused by IndexedDB behavior in Incognito Window

### ISSUE THREAD

**Issue by SukkaW** [GoogleChrome/workbox#1815]
**Library Affected**:

`workbox-core`, version 3.6.3

**Browser & Platform**:

Google Chrome 71.0.3578.98 for Windows

**Issue or Feature Request Description**:

@lwl12 and I were debugging a project using workbox. Both of us were in Incognito Window, to avoid caching. And then the error `Uncaught (in promise) DOMException` occurred many times after `workbox router` successfully responding to multiple requests.

![image](https://user-images.githubusercontent.com/40715044/50699345-900bdc00-1082-11e9-875a-b24af0d51619.png)

We try to close all the Incognito Window and then reopen a new one, but the errors occurred again.

Then I accidentally cleared the site data in `Chrome Dev Tools > Application > Clear Storage` and refresh the page, after that I got `Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`:

![image](https://user-images.githubusercontent.com/40715044/50699489-001a6200-1083-11e9-9072-015d709e4562.png)

Those errors only occur in Incognito Window, which make the problem even stranger.

I search those errors' outputs through StackOverFlow and Google, and thought the issue was caused by IndexedDB storage quota limit. When in Incognito Window, the limit is stricter than in Normal (I think that's why we can not reproduce the issue when we are not in Incognito Window).

**Comment by SukkaW** [comment]
I wrote a [demo](https://lab.skk.moe/WorkBox-Issue-1815-Demo/) for the issue, and the source code of the demo can be found [here](https://github.com/SukkaLab/WorkBox-Issue-1815-Demo)

**Comment by hifocus** [comment]
Have a look at your grammar before saying others' writing is Chinglish. LMAO

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/50819247-727d9180-1364-11e9-994a-a1567691d494.png)

I found out that the `workbox` was trying to react to storage quota limit by cleaning up the cache, but failed to run any callback (as logged as `about to run 0 callbacks`). I think there might be something wrong with the way the `workbox` deal with the `opaque` request.

And I have written a new demo with no `opaque` request (load tons of files from same origin) and no `DOMException` happened. I will upload that demo to [my repo](https://github.com/SukkaLab/WorkBox-Issue-1815-Demo) later.

**Comment by SukkaW** [comment]
I have deployed a [new demo](https://lab.skk.moe/WorkBox-Issue-1815-Demo/same-origin.html): The page will load 307 pictures from same-origin and it will not throw `Uncaught (in promise) DOMException`.

![image](https://user-images.githubusercontent.com/40715044/50841442-b8a41680-139f-11e9-8a92-9c73e635eef7.png)

**Comment by jeffposnick** [comment]
I'm sorry that you're running into issues—can you take a look at the guidance at https://developers.google.com/web/tools/workbox/guides/storage-quota?

Specifically, it sounds like you're running into quota issues, and adding in `workbox.expiration.Plugin` configured with `purgeOnQuotaError: true` can help by automatically clearing out runtime caches when that happens. (Automatic cleanup isn't enabled by default at the moment, but in a future release of Workbox it might be.)

**Comment by SukkaW** [comment]
@jeffposnick Hey look. I have just add the demo here.

- [demo](https://lab.skk.moe/WorkBox-Issue-1815-Demo/) will load 36 pictures (a little more than 10MB in all). If you open this demo in Normal Window, workbox will throw no error at all. But if you open this demo Incognito Window, workbox will throw `Uncaught (in promise) DOMException` after workbox router  responding about 15 requests.

So, is there any differences about quota limit between Incognito Window and Normal Window?

**Comment by jeffposnick** [comment]
Yes, there is a lower quota limit for Incognito windows: https://developers.google.com/web/tools/workbox/guides/storage-quota#special_chrome_incognito_considerations

**Comment by SukkaW** [comment]
@jeffposnick Ah, now I see why just a few pictures loaded from third-party domain will cause quota issues.

> In Chrome, for instance, even an opaque response of a few kilobytes will end up contributing around 7 megabytes towards your quota usage.

So 15 pictures means there will be more than 100MB contributing towards quota usage and exceeded the limit.

Thanks a lot!
