### ISSUE TITLE
Workbox not storing images and API responses in custom cache

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [GoogleChrome/workbox#1817]
**Browser & Platform**: All browsers

**Issue** : 
<img width="856" alt="screen shot 2019-01-05 at 3 53 16 pm" src="https://user-images.githubusercontent.com/35364381/50723341-4ebb1100-1102-11e9-956d-c6f24b58e66e.png">
I've been trying to generate service worker using workbox. I am using webpack-workbox-plugin for the same. While the js files are getting cached successfully, I cannot see the images and API response being cached. 

Exact code : https://stackoverflow.com/questions/54039961/workbox-service-worker-not-storing-images-and-api-response-in-cache

The javascript console messages are as visible in the **image attached**.

**Comment by SukkaW** [comment]
I think there are some problems with your regex. Here is my code:

```javascript
workbox.routing.registerRoute(
    // Cache API Request
    new RegExp('/api/(.*)'),
    workbox.strategies.staleWhileRevalidate({
         cacheName: 'apiCache',
         plugins : [
            new workbox.expiration.Plugin({
                maxEntries: 100,
                maxAgeSeconds: 30 * 60 // 30 Minutes
            })
        ]
    })
);

workbox.routing.registerRoute(
    // Cache Image File
    /.*\.(?:png|jpg|jpeg|svg|gif)/,
    workbox.strategies.cacheFirst({
        cacheName: 'images',
        plugins: [
            new workbox.expiration.Plugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            })
       ]
  })
);
```

And the `Uncaught (in promise) DOMException` problem might be the same with https://github.com/GoogleChrome/workbox/issues/1815

**Comment by kanishk-anand-oyo** [comment]
The regex was working fine, and yes, the problem occurs when workbox throws **Uncaught (in promise) DOMException** .

**Comment by jeffposnick** [comment]
There's some background about storage quota, and guidance for dealing with quota errors at https://developers.google.com/web/tools/workbox/guides/storage-quota

As a quick-fix, can you try adding in `purgeOnQuotaError: true` as an option when constructing `workbox.expiration.Plugin`?

**Comment by jeffposnick** [comment]
Given the error shown in the console, this is related to storage quota, and the guidance at https://developers.google.com/web/tools/workbox/guides/storage-quota is the best we can offer at this point.
