### ISSUE TITLE
Service Worker immediately becomes redundant on refresh

### ISSUE THREAD

**Issue by brad-decker** [GoogleChrome/workbox#1819]
**Library Affected**:
*workbox-sw

**Browser & Platform**:
*Chrome 71 for mac os x.

**Issue or Feature Request Description**:
My service worker works as expected while there are two tabs open, but when I have only one tab open a refresh of that tab doesn't serve anything from the service worker, the previous service worker becomes redundant immediately on refresh and a new one is registered. The result is that in a real world use case I cannot "browse offline". I am using precacheAndRoute as well as some runtimeCaching that all works with two tabs open.

I am including my service worker here for assistance:

```js
self.__precacheManifest = [
  {...} // trimmed purposefully, i can paste these if they are needed.
];

importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js");

workbox.skipWaiting();
workbox.clientsClaim();
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.routing.registerRoute(
  /.*\.(?:png|jpg|webp|webm|jpeg|svg|gif)/,
  workbox.strategies.cacheFirst({
    cacheName: 'media',
    plugins: [new workbox.cacheableResponse.Plugin({ statuses: [0, 200] })],
  }),
  'GET',
);
workbox.routing.registerRoute(
  /.*/,
  workbox.strategies.staleWhileRevalidate(),
  'GET',
);

```

**Comment by jeffposnick** [comment]
Do you have "Update on reload" checked in Chrome's DevTools, as described at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#update_on_reload?

**Comment by brad-decker** [comment]
No, it is unchecked. I am not having much luck in debugging the issue as I don't know what is going wrong or where to even log out things.

**Comment by brad-decker** [comment]
I was leaving this on in production because while it wasn't working it wasn't harming anything but found out that when a user visits the site for the first time on Firefox (latest version), the initial prefetch causes links not to load the associated bundles. Disabling the service worker fixed this problem. I have to believe that the two issues are related and that Firefox is just doing something more drastic in response to the bug. I know this is fully on my end because I have seen implementations of this library with my exact stack work correctly but do these details help at all in giving me a nudge in the right direction for debugging? 😬

**Comment by jeffposnick** [comment]
Apologies that this is still causing problems.

There are a couple of things you can do to enable additional debugging in Workbox: https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug#debugging_workbox

Here's one more thing to check in the meantime: are there any build warnings output from `webpack` due to assets being larger than the maximum default size (which is 2mb)? By default, Workbox will exclude those assets from the precache manifest, and some of what you're describing (URLs for associated bundles not loading while offline) sounds like it _could_ be caused by that.

**Comment by brad-decker** [comment]
@jeffposnick i have confirmed that this isn't the cause. Debugging info you provided yields no additional results for me, the only thing that is even a warning is that i'm not using a revision flag in my precache manifest because my file names are revisioned.

**Comment by brad-decker** [comment]
So, to confirm I removed all but one file from the precache manifest that is under 10kb. Its so peculiar though. This is what I see 90% of the time immediately after the alert that lets me know urls are cached:

![image](https://user-images.githubusercontent.com/4448075/51772081-b1278180-20b0-11e9-9107-c0b5a9598296.png)

the '- deleted' part is what I notice and then when I refresh my page this one becomes redundant and a new one is created and the whole init cycle happens again followed by the - deleted flag reappearing.

I can sometimes modify my service worker file and cause this to stop happening. The worker persists and all is good until I trigger lightbox which I have been using to validate that my solution will persist because lightbox seems more effective at clearing cached results. in all cases running lightbox causes the worker to go back into that deleted permanent cycle described above again without any changes to my service worker file.

Still no errors on the service worker or in the console.

**Comment by brad-decker** [comment]
adding one more detail i just discovered. I can "Trick" the service worker into a good state by adding an error into my service worker file and reloading. Once the error is thrown the worker isn't deleted, but instead is redundant. I then remove the error (just throwing an error with a string) and then refresh and on the next load the SW is running fine and will persist. If i click "unregister" to the right of the worker in dev tools i go back into a bad state.

**Comment by jeffposnick** [comment]
Also, if this is still an issue, could you consider upgrading to the latest v4 release candidate? If you're using, e.g., the webpack plugin, you can do so via `npm install --save-dev workbox-webpack-plugin@beta`, or just manually swap in the updated CDN URL for the `workbox-sw` loader library: `https://storage.googleapis.com/workbox-cdn/releases/4.0.0-rc.3/workbox-sw.js`

**Comment by brad-decker** [comment]
@jeffposnick sorry for the delay/lack of response here from our side. I will give the release candidate a whirl in the next few days and report back. Also just want to praise you for how helpful you've been for something that is so very clearly an implementation issue on our end. Really appreciate the extra mile you've gone.

**Comment by thebedroomprogrammer** [comment]
I am facing the same issue. Have you come across any solution?

**Comment by brad-decker** [comment]
@thebedroomprogrammer I have discovered an issue in my bundle related to how I was manually splitting out some dependencies using a regex. I am still diving into this because we still haven’t enabled our worker but have at least found that there is a silent error or two that is impacting our users without the worker. I want to fix these up before I re-enable worker because my theory is the silent error is preventing the worker from persisting

**Comment by thebedroomprogrammer** [comment]
Ok I came across this issue when we migrated our project from https://games.gamezop.com to https://www.gamezop.com we did not do any change in the script and started getting very less service worker activation. Thanks for them help though. I will update on this thread if I get any concrete solution.

**Comment by brad-decker** [comment]
@jeffposnick sorry for the long delay, finally got around to testing with version 4. I will say the version 4 experience is much better but I'm having the same result in my next.js app. I will provide the details I have gathered here to see if it sparks anything. 

### Notes
- [x] webpack set to maximum pre-gzip chunk size of < 2 mb
- [x] upgraded to latest workbox

This is my service worker file: 
```js
self.__precacheManifest = [
  {
    "url": "/_next/static/O_OckWoVTaY0N5wsWRLFw/pages/contact.js"
  },
];

importScripts("https://storage.googleapis.com/workbox-cdn/releases/4.1.1/workbox-sw.js");


workbox.precaching.precacheAndRoute(self.__precacheManifest, {});
```

I've actually trimmed this way down just to see if i could get it working with as minimal as required setup. This is the file that registers the worker in the client:

```js
export const registerWorker = async () => {
  if ('serviceWorker' in navigator) {
    const { Workbox } = await import('workbox-window');

    const wb = new Workbox('/service-worker.js');
    wb.addEventListener('activated', event => {
      // `event.isUpdate` will be true if another version of the service
      // worker was controlling the page when this version was registered.
      if (!event.isUpdate) {
        console.log('Service worker activated for the first time!');

        // If your service worker is configured to precache assets, those
        // assets should all be available now.
      }
    });

    wb.addEventListener('waiting', () => {
      console.log(
        `A new service worker has installed, but it can't activate` +
          `until all tabs running the current version have fully unloaded.`,
      );
    });

    wb.addEventListener('message', event => {
      if (event.data.type === 'CACHE_UPDATE') {
        const { updatedURL } = event.data.payload;

        console.log(`A newer version of ${updatedURL} is available!`);
      }
    });

    wb.addEventListener('installed', event => {
      if (!event.isUpdate) {
        console.log('First install');
      } else {
        console.log('updated install');
      }
    });

    wb.addEventListener('controlling', event => {
      if (!event.isUpdate) {
        console.log('First control');
      } else {
        console.log('updated control');
      }
    });

    wb.addEventListener('externalinstalled', event => {
      if (!event.isUpdate) {
        console.log('external first install');
      } else {
        console.log('external update install');
      }
    });

    wb.addEventListener('externalwaiting', event => {
      if (!event.isUpdate) {
        console.log('external first waiting');
      } else {
        console.log('external update waiting');
      }
    });

    wb.addEventListener('externalactivated', event => {
      if (!event.isUpdate) {
        console.log('external first acvtive');
      } else {
        console.log('external update acvtive');
      }
    });

    wb.addEventListener('redundant', event => {
      // `event.isUpdate` will be true if another version of the service
      // worker was controlling the page when this version was registered.
      if (!event.isUpdate) {
        console.log('Service worker redundant for the first time!');

        // If your service worker is configured to precache assets, those
        // assets should all be available now.
      }
      console.log(event);
    });

    wb.register();
  }
};
```

I've just tried to log everything out that I could to see what happens. 

### results:
![image](https://user-images.githubusercontent.com/4448075/55239010-cb422500-5203-11e9-8646-6bbddd066ac2.png)

Side note, if I use skipWaiting/clientsClaim, no redundant message ever occurs:
![image](https://user-images.githubusercontent.com/4448075/55239094-f593e280-5203-11e9-9b6a-497bbc4ee5cc.png)

![image](https://user-images.githubusercontent.com/4448075/55239112-fd538700-5203-11e9-9db8-3bb38b277b3f.png)

but that - deleted flag is there and on the next refresh i'll get the exact same console messages.

**Comment by thebedroomprogrammer** [comment]
The problem that I faced was with the precache manifest. So basically the error occurred and service worker became redundant because the links that I had in my precache manifest file was posing cors error when fetched via service workers. I resolved the CORS issue and I was able to get my service worker up and running.

**Comment by brad-decker** [comment]
How did you diagnose the issue and confirm the CORS issue? @thebedroomprogrammer thanks for sharing!

**Comment by brad-decker** [comment]
@thebedroomprogrammer I will work on confirming that I have actually fixed the issue but your feedback made me look at my script/link tags more closely and I discovered that some of the resources we are attempting to cache had an improper 'crossOrigin' attribute. It *seems* to be working but I'm going to put it through its paces and report back once I am confident it's not like the other flukes I've had :D.

**Comment by brad-decker** [comment]
@thebedroomprogrammer @jeffposnick i have confirmed that the issue is one of our third party scripts we are loading (?) When i fixed our head script tags up I added proper crossOrigin attributes in a few places they were missing and one of those scripts started not responding to our request (throwing a real error in the console about cross origin). So essentially that script was never loaded, but the service worker persisted and worked as expected. Once reverting that change and allowing the script to load the old behavior returns of the service worker immediately marking itself as deleted.

VERY OCCASIONALLY i get a Uncaught DOMException in promise with no stack trace error and always after refresh its gone. Maybe related? The script in question is under 200kb and there is no message about quota exceeded.

**Comment by brad-decker** [comment]
Also we do not have a caching strategy for that third party script/route so the service worker shouldn't be requesting it, right?

**Comment by thebedroomprogrammer** [comment]
Sorry for replying so late. I resolved my issue by mainly trial and error. On precaching files I was getting an error in my service worker like this **Uncaught (in promise) TypeError: Failed to fetch** . On examining the issue I came to know that there were some files in my precache that I was getting from AWS bucket. As both my sites and bucket URLs were different I was getting the CORS error hence the fetch request was failing. I allowed the CORS on my bucket and the error was gone. My service worker was registering and running from then on without any issue.

**Comment by philipwalton** [comment]
@brad-decker if there's an error while attempting to precaching files, Workbox should be logging that to the console. https://github.com/GoogleChrome/workbox/blob/v4.1.1/packages/workbox-precaching/PrecacheController.mjs#L191-L198

So if you're not seeing any error logged, then most likely precaching is not the issue. Do you have a demo of this hosted publicly somewhere?

**Comment by brad-decker** [comment]
@philipwalton @thebedroomprogrammer @jeffposnick - Back from paternity leave sorry for resurrecting this again. So the third party we use has enabled cors options for this script that is killing the sw. Still the same problem. The thing is we aren't even attempting to cache it or respond to it with our service worker. Removing the script makes the service worker work as expected. I don't have a public demo that I can share at this point. We are pre-launch still.

**Comment by brad-decker** [comment]
@jeffposnick @philipwalton @thebedroomprogrammer -- in this case it happens to be that the third party script was manually unregistering service workers as a workaround for a problem they were having with their own implementation. We've asked that they remove it. Thanks for all the support during this crucible of mine!

**Comment by philipwalton** [comment]
Glad you got it figured out!

**Comment by marcofranssen** [comment]
I'm facing the same issue. It only happens on Google Chrome. Already unregistered all service workers but somehow I can't get it to work in Google Chrome. In firefox the service worker works as it should.

What can I do to fix this in Google Chrome? 

I'm running on MacOS big Sur and Google Chrome 88.0.4324.96.

It seems not to be tight to a single subdomain, following urls are the same deployment.

- https://nextjs-blog-git-pwa.marcofranssen.vercel.app/
- https://nextjs-blog-f902dghv2.vercel.app/

Following info I retrieved from <chrome://serviceworker-internals/?devtools>.

```bash
Error: {"columnNumber":-1,"lineNumber":-1,"message":"Failed to register a ServiceWorker for scope ('https://nextjs-blog-f902dghv2.vercel.app/') with script ('https://nextjs-blog-f902dghv2.vercel.app/sw.js'): ServiceWorker failed to install: ServiceWorker failed to handle event (event.waitUntil Promise rejected)","sourceURL":""}
Console: {"lineNumber":0,"message":"Uncaught (in promise) TypeError: Failed to fetch","message_level":3,"sourceIdentifier":1,"sourceURL":"https://nextjs-blog-f902dghv2.vercel.app/sw.js"}
```

Running the same code on localhost works properly with having a service worker being registered.

**Comment by grigory-bogush** [comment]
On my side I have also discovered that adblock seems to block service worke registration as well. So, please keep that in mind.
Disabling it fixed the issue.

**Comment by huykon** [comment]
I have same issue with service worker when using workbox. Does anyone have the solution for this?
![image](https://user-images.githubusercontent.com/9253798/205604513-6fa2ae77-433b-4bc3-a18f-d0cd8094a59c.png)

**Comment by w8ze-devel** [comment]
Have the same issue as @huykon. Bad precaching response.

Anyone know how to solve it please ?

Thanks

**Comment by zacBkh** [comment]
Hello!

I am still having this issue on next js 14 and using next-with-workbox plugin...
My service worker is registered but I get this error : 
![image](https://github.com/GoogleChrome/workbox/assets/108217390/f6e5f28a-43ad-41ff-b215-71d587b34c52)

An error is thrown because this HTTP request failed : 
![image](https://github.com/GoogleChrome/workbox/assets/108217390/0fde948d-d025-4bd1-958b-81631faaed57)

I don't understand why this request is having /public appended.
We don't need to add "public" to the url to fetch the resource at build time.

I can access http://localhost:3000/sw.js by going on the URL but of course not http://localhost:3000/public/sw.js

I am not sure if it's a CORS issue, I don't think so since I am basically not fetching anything yet from my SW...
