### ISSUE TITLE
self.showNotification no longer works in 4.0.0 beta

### ISSUE THREAD

**Issue by andrralv** [GoogleChrome/workbox#1821]
I had been using Workbox 3.6 and I was able to do:

V3 CODE (Works):

```
const bgSyncPlugin = new workbox.backgroundSync.Plugin('myQueue', {
  maxRetentionTime: 24 * 60,
  callbacks: {
    requestWillEnqueue: (storableRequest) => {
          self.registration.showNotification('You are Offline!', {
          body: 'Requests will be put in a queue. Your application 
          will sync once you are back online',
          icon: './logo.png',
          tag: 'service-worker'
        });
      },
    requestWillReplay: (storableRequest) => {
    },
    queueDidReplay: (storableRequestArray) => {
          // show notification indicating requests were replayed
        } else {
          // show another notification with the error
          }
        }
      }
    },
  },
);
```

And it did show a notification to the user, however, this feature doesn't work when I upgraded to Workbox v4 beta. Requests are replayed but no notification is shown. Here is the a code example for reference:

V4 CODE (Doesn't work):
```
const showNotification = () => {
  self.registration.showNotification('Post Sent', {
    body: 'You are back online and your post was successfully sent!',
    icon: 'logo.png',
  });
};

const queuePlugin = new workbox.backgroundSync.Plugin('myQueue', {
  onSync: async (queue) => {
    console.log(queue);
    try {
      await queue.replayRequests();
      showNotification();
    } catch (error) {
      showNotification();
      console.log(error);
    }
  }
});

workbox.routing.registerRoute(
  "https://myapi.com/endpoint",
  workbox.strategies.networkOnly({
    plugins: [queuePlugin]
  }),
  'POST'
);
```
If I keep the showNotification code inside of the try block is the same, it is not shown, I also tried using `ServiceWorkerRegistration` instead of `self.registration`, no difference.
Am I missing something here or is it no longer supported?

**Comment by jeffposnick** [comment]
CC: @philipwalton to see if he has any ideas.

**Comment by philipwalton** [comment]
@andrralv sorry for the slow response, were you able to get this working?

Did you trying just doing a `console.log()` instead of running your `showNotification()` function? You might also trying using a `finally` block after your `try/catch` to ensure it happens regardless of whether an error is thrown.

As far as the v4 code is concerned, that looks like it should work to me.

**Comment by jeffposnick** [comment]
Closing due to lack of response. If the original poster is still running into the issue, please let us know and follow the steps outlined above to debug.
