### ISSUE TITLE
addCacheListener does not handle cross-origin <script> resources well

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1826]
**Library Affected**:
*workbox-routing*

When sending a list of URLs to cache from the window to a `Router` instance, the default behavior is to not set any mode in the request, but if the request is a cross-origin script that only works with `mode: 'no-cors'`, this will cause issues.

A few possible solutions:

- Default to `mode: 'cors'` for cross-origin requests, and (if there's an error) retry with `mode: 'no-cors'`.
- Allow the window to pass in a `requestInit` object.
- Both of the above.

**Comment by lecepin** [comment]
use plugin response

**Comment by philipwalton** [comment]
Fixed via #1851.
