### ISSUE TITLE
Add gtm.js runtime caching

### ISSUE THREAD

**Issue by xMokAx** [GoogleChrome/workbox#1836]
**Library Affected**:
*workbox-google-analytics.*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
*Support runtime caching of gtm.js.*

I would like to add runtime caching for gtm.js because it's responsible of fetching analytics.js so without caching it the offline google analytics will not work if the user starts the app with no connection.

**Comment by jeffposnick** [comment]
This was fixed by https://github.com/GoogleChrome/workbox/pull/1869
