### ISSUE TITLE
Workbox works for all browsers, Google Chrome shows: Uncaught (in promise) DOMException error 

### ISSUE THREAD

**Issue by gabrielthakid** [GoogleChrome/workbox#1840]
https://stackoverflow.com/questions/54198028/workbox-serviceworker-working-everywhere-except-chrome-uncaught-in-promise-do

**Library Affected**:
*workbox-sw, workbox-build, etc.*

**Browser & Platform**:
*Google Chrome, Chrome Canary*

I'm using the workbox-webpack-plugin
-------------------------------------------------
webpack.config.js

    const workbox = require('workbox-webpack-plugin'); 

    module.exports = {
        plugins: [
            new workbox.GenerateSW({
                swDest: './service-worker.js',
                skipWaiting: true,
                clientsClaim: true
            })
        ]  
    }

---------------------------------------
index.ts (entry)

     if ('serviceWorker' in navigator) {
          window.addEventListener('load', function() {
          navigator.serviceWorker.register('/js/app/dist/service-worker.js');
        }); 
      }

The error is thrown at 
workbox-precaching.dev.js: 1011

I attached screenshots on the stackoverflow link

**Comment by gabrielthakid** [comment]
It actually works on icognito mode, removing browser cache doesn't help

**Comment by gabrielthakid** [comment]
I attached a screenshot on my stackoverflow link.
[https://i.stack.imgur.com/dU6S1.png](url)

**Comment by jeffposnick** [comment]
Can you try updating to use Workbox v4.0.0-beta.1 and see if the issue persists? The precaching code was significantly rewritten in that release.

`npm install workbox-webpack-plugin@beta` should do it.

**Comment by gabrielthakid** [comment]
> Can you try updating to use Workbox v4.0.0-beta.1 and see if the issue persists? The precaching code was significantly rewritten in that release.
> 
> `npm install workbox-webpack-plugin@beta` should do it.

Hello, thanks a lot for taking your time to reply.
I have tried the versions 3.6.3, 3.0.0, the alpha and beta versions.

Updating to the newest beta 1, is even worse, since aside from the last errors it will show another one, however, like the other ones, this version works in Chrome's icognito mode and other browsers too.

the additional error shown says 

> Service worker installation failed. It will be retried automatically during the next navigation. 

I have attached a screenshot in the stackoverflow thread.

Again thank you.

**Comment by gabrielthakid** [comment]
> Can you try updating to use Workbox v4.0.0-beta.1 and see if the issue persists? The precaching code was significantly rewritten in that release.
> 
> `npm install workbox-webpack-plugin@beta` should do it.

The issue has been fixed for Chrome 72, it works now for me and my colleagues.
This issue is to be closed.

**Comment by gabrielthakid** [comment]
> Can you try updating to use Workbox v4.0.0-beta.1 and see if the issue persists? The precaching code was significantly rewritten in that release.
> 
> `npm install workbox-webpack-plugin@beta` should do it.

Thanks for your help

**Comment by kuangch** [comment]
> > Can you try updating to use Workbox v4.0.0-beta.1 and see if the issue persists? The precaching code was significantly rewritten in that release.
> > `npm install workbox-webpack-plugin@beta` should do it.
> 
> The issue has been fixed for Chrome 72, it works now for me and my colleagues.
> This issue is to be closed.

that same issue occur at chrome 73 , are you has same issue now
