### ISSUE TITLE
Proposal: workbox-messages module

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1848]
To accompany the new `workbox-window` library in v4, and standardize the functionality that's needed for the `skipWaiting` message handler proposed in #1753 as well as what's already implemented in https://github.com/GoogleChrome/workbox/blob/208850c1a670d0f7ec1b8647c0d7ce4319f9fa5d/packages/workbox-broadcast-cache-update/BroadcastCacheUpdate.mjs#L185-L207

I'm proposing a new set of methods on `workbox.core`:

- `registerMessageCallback({messageType, callback})` will take care of adding in a `message` event handler (if one doesn't already exist) that will in turn check for incoming `message`s whose `event.data.type === messageType`, and when found, run `await callback(event)` for each registered event. The callback mechanism will be wrapped in `event.waitUntil()` (for browsers that support it: https://github.com/w3c/ServiceWorker/issues/669#issuecomment-402779578)

- `unregisterMessageCallback({messageType, callback})` will do the opposite, and either unregister a specific `callback`, or if `callback` is `null`, unregister all callbacks for the given `messageType`.

I think that keeping track of `messageType` values can be done on a per-module basis, i.e. the constant used by `workbox-broadcast-cache-update` can be defined locally there.

One additional area for discussion is whether this proposal can end up powering the [mechanism that's already in place](https://github.com/GoogleChrome/workbox/blob/next/packages/workbox-core/_private/quota.mjs) in `workbox.core` for registering callbacks that can be run when there's a global `QUOTA_EXCEEDED` error. There's a lot of similarities, but invoking callbacks triggered by an exception is different from invoking callbacks triggered by a `message` event.

**Comment by philipwalton** [comment]
This proposal sounds great to me. And I think it definitely makes sense for the message registrations to be handled by the individual packages, not all grouped in `workbox-core`.

`workbox-window` has a small [`EventTargetShim`](https://github.com/GoogleChrome/workbox/blob/15c80c0/packages/workbox-window/utils/EventTargetShim.mjs) class that we could move into `workbox-core`. It might be easier to use this since `message` event are required to be added in the initial execution phase of the SW, whereas here we'd want the flexibility to add/remove listeners in callbacks.

**Comment by philipwalton** [comment]
As for the format, I think something like this would be fine:

```js
{
  type: 'SKIP_WAITING',
  meta: 'workbox-package-name',
}
```

We could potentially also try to standardize on using verbs for action messages and nouns for notice message, or something like that. I believe right now our only message instances are:

```js
{
  type: 'WINDOW_READY',
  meta: 'workbox-window',
  // payload: void
}
```

```js
{
  type: 'CACHE_UPDATED',
  meta: 'workbox-broadcast-cache-update',
  payload: {
    cacheName: 'the-cache-name',
    updatedURL: 'https://example.com/',
  },
}
```
 Am I missing anything?

**Comment by jeffposnick** [comment]
Oh, yeah, I forgot that adding in a `message` event listener post-`install` would break, just like the other event listeners. I'll take that into account,

**Comment by jeffposnick** [comment]
I did a quick prototype and it looks like adding in this functionality would take `workbox-core.prod.js` from 5513 to 5924 bytes. Given that `workbox-core` is always loaded, those extra bytes might not be worth it for optional functionality.

This logic could live in a new `workbox-messages` module instead.

**Comment by jeffposnick** [comment]
Moving over some thoughts from a separate conversation: if we had this module, it would be a good home for code that currently lives in `workbox-broadcast-cache-update`: https://github.com/GoogleChrome/workbox/blob/208850c1a670d0f7ec1b8647c0d7ce4319f9fa5d/packages/workbox-broadcast-cache-update/BroadcastCacheUpdate.mjs#L91-L127

**Comment by philipwalton** [comment]
Yesterday I discovered that the SW spec includes a buffering mechanism ([client message queue](https://w3c.github.io/ServiceWorker/#dfn-client-message-queue)) for when a SW calls `postMessage()` on a window client. The default behavior is messages won't be dispatched on the window until after `DOMContentLoaded`.

Unfortunately, this behavior [isn't yet implement in all browsers](https://bugs.chromium.org/p/chromium/issues/detail?id=915685), so for the moment we'll have to continue using this `WINDOW_READY` strategy, but whatever we do here should be forward compatible enough that we can remove this code at some point.

However, the buffering behavior applies to `postMessage()` calls but not `BroadcastChannel` messages. This, coupled with the fact that `BroadcastChannel` is not even implemented in all browsers makes me wonder if we should switch to using postMessage exclusively.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
