### ISSUE TITLE
Add importance: 'low' to precaching requests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1855]
[Priority Hints](https://wicg.github.io/priority-hints/) is currently being experimented with in Chrome, and may come to other browsers in the future.

We can make use of them to [mark the `fetch()` requests used for precaching](https://wicg.github.io/priority-hints/#examples-0) as being low-priority, to reduce the chance that they will consume bandwidth needed for requests made from the `window` context.

CC: @addyosmani

**Comment by jeffposnick** [comment]
Ditto for the revalidation request used in the `staleWhileRevalidate` strategy; see https://stackoverflow.com/questions/54305729

**Comment by jeffposnick** [comment]
The example from the spec for making requests is

```
<script>
 // Critical Fetch request for article content
 fetch('/api/articles.json', { importance: 'high' }).then(/*...*/)

 // Request for related content now reduced in priority
 // reducing the opportunity for contention
 fetch('/api/related.json', { importance: 'low' }).then(/*...*/)
</script>
```

i.e. it gets passed in as either `FetchOptions` when calling `fetch()`, or the underlying `RequestInit` when constructing a `Request`.

That would imply that it's exposed as `event.request.importance` inside of a `fetch` event, following the model for how the other properties used in `RequestInit` are exposed on the underlying `Request`.

**Comment by jeffposnick** [comment]
CC: @khempenius, who expressed some interest in this.

**Comment by dtruffaut** [comment]
I approve this feature :+1:

**Comment by daffinm** [comment]
I think this feature is needed to make precaching a truly progressive feature of any PWA. 

Right now, and under certain circumstances (e.g. poor mobile data connection and a few megs of assets to precache), precaching initially worsens the user experience and must be compensated for -- e.g. delayed service worker registration & loading screen upon service worker registration that is closed upon activation. 

It look forward to the days of smarter (it's already pretty good) precaching.

**Comment by jeffposnick** [comment]
I've posted this elsewhere, but just to reflect the most recent status on this issue: Priority Hints went through the [Origin Trial](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md) process in Chrome, and did not progress past that in their current incarnation.

So we're currently blocked on implemented anything in Workbox until at least one browser ships this feature.

Folks can check https://chromestatus.com/feature/5273474901737472 and ⭐️  https://bugs.chromium.org/p/chromium/issues/detail?id=821464 for updates.

**Comment by taozhou-glean** [comment]
should we revisit this given that now the `Request.init#priority` has been supported on multiple browsers:

<img width="1363" alt="image" src="https://github.com/GoogleChrome/workbox/assets/121891361/389824a4-3a91-466f-aab1-849d350e6010">

https://caniuse.com/?search=request.init%20priority
