### ISSUE TITLE
Should workbox-window use promises instead of events?

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1856]
**Library Affected**:
*workbox-window*

All service worker [lifecycle events](https://docs.google.com/document/d/16BJDNhfqMjIvJ3_kR4lklpbliCGpi1dFhCdf7kHOsL8/edit#heading=h.dciabll4y3mv) dispatched by the `Workbox` object in the `workbox-window` package are only ever dispatched once (per `Workbox` instance). This design is intentional and meant to simplify the mental model of service worker registration/updates for most developer use cases (see the [`workbox-window` design doc](https://docs.google.com/document/d/16BJDNhfqMjIvJ3_kR4lklpbliCGpi1dFhCdf7kHOsL8/edit?usp=sharing) for more details).

But based on this [thread with @jakearchibald](https://twitter.com/philwalton/status/1086392135622877185), I'm considering converting these single-fire events to promises.

In the original design of `workbox-window`, these actually *were* promises, but I switched them to events because I was concerned that, with the rising popularity of async/await, developers might `await` promises that will never resolve.

For example, if the `Workbox` object's `activated` event were instead an `.activated` promise, it would only resolve 1) on page loads that register a particular SW for the very first time, or 2) page loads where the SW has updated. **However**, that means on many page loads it will never resolve, so it could easily lead to problems like this: 

```js
const wb = new Workbox('/sw.js');
wb.register();

await wb.activated;

// This line of code is intended to run on every page load, but because
// the above will never resolve on some page loads, this won't work.
wb.messageSW(...);
```

But when using `.addEventListener()`, that mistake is much less likely to happen.

```js
const wb = new Workbox('/sw.js');
wb.register();

wb.addEventListener('activated', () => {
  // Code that should only run when a new/updated SW has activated.
});

// This line will now run on every page load.
wb.messageSW(...);
```

Granted, you could use `.activated.then(...)` in every case where you could use `.addEventListener('activated', ...)`, but my concern is that the use of `.then()` seems to be going out of fashion.

Anyway, now that the initial version of the `workbox-window` library is available to try out, I'm curious to hear whether developers like the events API or whether they'd prefer a promises API. If we do switch, I'd prefer to do it before our initial release, so I'm hoping to get feedback on this quickly.

/cc @jakearchibald, @jeffposnick, @addyosmani, @developit, @prateekbh, @westonruter,  @jadjoubran, @gauntface (in case y'all have strong opinions)

**Comment by jakearchibald** [comment]
> For example, if the Workbox object's activated event were instead an .activated promise, it would only resolve 1) on page loads that register a particular SW for the very first time, or 2) page loads where the SW has updated.

Yeah that doesn't quite seem to match promises. I'd expect `.activated` to be set to a promise that:

1. Let *reg* be the result of awaiting the service worker registration call.
1. Let *workerToAwait* be *reg*'s installing or waiting worker.
1. If *workerToAwait* is not undefined, while true:
    1. Wait for *workerToAwait*'s state to change.
    1. If *workerToAwait*'s state is redundant, reject promise & abort these steps.
    1. If *workerToAwait*'s state is activated, break.
1. Resolve promise.

That way `.activated` resolves once the newest worker in the registration reaches the activated state, but it'll also resolve if the newest worker has already activated.

**Comment by philipwalton** [comment]
This is essentially how I designed `workbox-window` in the first iteration, but I changed the design because I wanted to stick to the following guiding principle to make the developer experience more predictable:

If a developer deploys version X of their app, it'll ship with some window JS code and some service worker code that know how to work given version X. Then, if that developer deploys version Y of their app, version Y of their window code should know how to handle version Y of their SW code, and it also should know how to handle upgrading from version X to version Y. But version X of their SW code will not necessarily be able to work with version Y of their window code, so we should do what we can to prevent developers from accidentally getting themselves into this situation.

To put that another way, if version Y of an app creates a `Workbox` instance and registers version Y of a service worker, in the case where version X of the service worker is still controlling at page load, we should let version Y of the window code interact with the service worker until version Y takes over (since version X is likely not compatible with version Y).

> That way `.activated` resolves once the newest worker in the registration reaches the activated state, but it'll also resolve if the newest worker has already activated.

Correct me if I'm wrong, but in cases where there's already an active service worker running when a page calls `navigator.serviceWorker.register('/sw.js')`, there's no way to handle both of the following requirements:

- `.activated` resolves to the currently active SW in the event that **no update is found**.
- `.activated` *doesn't* resolve until the updated SW activates in the event that **an updated SW is found**.

If we had an API to determine if/when an update is *not* found (related to https://github.com/w3c/ServiceWorker/issues/1379), then I could implement this behavior, but at the moment I think the only way to get the version predictability I described above is to *not* run activation code on page loads when no update is found.

Developers who just want to defer some code until a service worker is active can already use `navigator.serviceWorker.ready`.

**Comment by philipwalton** [comment]
To provide an update here: I discussed this issue with @jakearchibald and @jeffposnick in person, and as a result of that discussion and thinking about the issue a bit more, I leaning toward the following changes:

**1. Add an `.active` and `.controlling` promise.**

These promises will resolve either (a) after registration, if the controlling service worker's script URL (and optional script version) matches the `Workbox` instance, or (b) when an update is found and these lifecycle events occur.

We currently don't have a concept of "script version" in Workbox, so my next proposed change is:

**2. Add a `scriptVersion` configuration option to the `Workbox` class.**

To address the problem I mentioned above -- that a `Workbox` instance does't know whether the controlling SW is the same version as the service worker script it's registering -- rather than depend on a bunch of heuristics, I think it makes sense to allow developers to specify an explicit version themselves.

When `scriptVersion` option is used, the `Workbox` instance will `postMessage` the controlling service worker to check its version. If the versions match, then we can resolve the `.active` and `.controlling` promises right way. If they don't match (or if the SW doesn't respond) then we can assume the registering service worker will trigger an update.

When the `scriptVersion` option is not used, we just compare the script URLs. This means the `.active` and `.controlling` promises may resolve to an outdated version in some cases, but I think those cases are unlikely to cause major problems, and in complex cases where they would, the solution would be to just use `scriptVersion`.

But in order for a controlling service worker to report its version back to the window, we'll also need to:

**3. Add a `setVersion()` method to `workbox-core`.**

This will set a service worker version in IndexedDB (or cache storage), and it will add a message listener to respond to version request messages.

An interesting feature this could also allow for is reporting the version change to the window in an `install` event. For example, using something akin to semver, the window could decide whether or not to show a notification to the user based on how "breaking" the service worker update was.

* * *

With respect to the single-fire events, I think it's OK to keep them as they are for now (they only fire when an update is found). I believe by adding the `.active` and `.controlling` promises (which should resolve each page load) it will help make it clear that the events may not fire every page load.

**Comment by philipwalton** [comment]
I have a PR of these changes (WIP) in https://github.com/GoogleChrome/workbox/pull/1861.
