### ISSUE TITLE
Improvements to grouped logging

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1858]
There are a few places in our code where we start a grouped log (via `console.groupCollapsed()`) and then we perform some async operations before filling in the additional group messages and closing the group.

The result is sometimes we get log messages from other modules incorrectly inserted into a group where they shouldn't be.

The easiest way to address this is to just avoid logging a group of messages until we have everything we want to log; then we can log it all at once. It's possible we could update the logger module to do this automatically, but I think that may end up being more complex that just following the conventions.

To discover all the places where this happens, we could add code to `logger.mjs` that queues a microtask in the `groupCollapsed()` method and throws if `groupEnd()` isn't called before that microtask runs.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
