### ISSUE TITLE
Move to service-worker-mocks 2.0.0

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1867]
Following https://github.com/pinterest/service-workers/pull/109, the 2.0.0 release of `service-worker-mock` should have all of our forked changes. We can get back on the official release train (and moving forward, contribute directly to the upstream package if we find any issues.)

**Comment by NutthaponSmart** [comment]
Issue moved to [GoogleChrome/chrome-app-codelab #10](https://github.com/GoogleChrome/chrome-app-codelab/issues/10) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jeffposnick** [comment]
Tracked in #2479
