### ISSUE TITLE
[InjectManifest] Support multiple webpack config

### ISSUE THREAD

**Issue by Heliodromel** [GoogleChrome/workbox#1872]
**Library Affected**:
*workbox-webpack-plugin#InjectManifest*

**Issue or Feature Request Description**:
*When using [multiple configurations](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) with webpack, it would be nice to have an option in InjectManifest, so that all assets generated by each webpack configuration are concatanated in the same precache-manifest file.*

Imagine the following webpack configuration :

```
const InjectManifest = new InjectManifest({
    swSrc: "path_to_service-worker.js",
    swDest: "outupt_path_to_service-worker.js",
    precacheManifestFilename: "service-worker-precache-manifest-[manifestHash].js",
    importWorkboxFrom: "local",
}),

module.exports = [{
    output: {
        filename: './appA.js',
    },
    name: 'appA',
    entry: './app.js',
    plugins: [InjectManifest],
}, {
    output: {
        filename: './appB.js',
    },
    name: 'appB',
    entry: './app.js',
    plugins: [InjectManifest]
}];
```

I would like all generated assets for appA and for appB to be added somehow to the precacheManifest file so that all those assets end up being precached by service worker. 

Is it possible ?

**Comment by jeffposnick** [comment]
I don't think that we're going to be able to accommodate that feature—we currently strive to keep each compilation separate, and not leak information between compilations.

In v5, `InjectManifest` results in creating a webpack child compilation that inherits some properties from the main compilation, and it wouldn't be clear which compilation to treat as the parent if we assumed that `InjectManifest` could be used across multiple compilations.

What I would suggest is trying to leverage the `additionManifestEntries` configuration option (https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#avoid-url-change), which will be present in the next `workbox-webpack-plugin` v5 alpha release, and use that to pull in additional manifest entries as needed.
