### ISSUE TITLE
maxAgeSeconds from Cache-Control max-age

### ISSUE THREAD

**Issue by zsolt-dev** [GoogleChrome/workbox#1880]
Feature request

**Library Affected**:
workbox-expiration-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I would like the workbox caching plugin to use Cache-Control max-age value from the http header. I have all the Cache-Control headers properly configured and I would just like to use those in workbox too.

Example configuration of maxAgeSeconds:
```js
workbox.routing.registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  workbox.strategies.cacheFirst({
    cacheName: 'images',
    plugins: [
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200],
      }),
      new workbox.expiration.Plugin({
        maxAgeSeconds: 'httpHeaderCacheControlMaxAge', <---- this setting
        purgeOnQuotaError: true,
      }),
    ],
  }),
);
```

**Comment by zsolt-dev** [comment]
It looks like this wont be possible with the current plugin, since it is storing timestamp of the creation date not the expiry timestamp. 

So it would require a completely new plugin or another setting in the current expiration plugin.

**Comment by zsolt-dev** [comment]
I would be willing to implement this, but I would first need some guidance like should I make a separate new plugin or coded to the the existing expiration plugin. Also what would be the best API/settings... 

Anyone willing to help me with this?

**Comment by philipwalton** [comment]
Hey @zsolt-dev, thanks for the feature request. The first thing I'd recommend is you take a look at the changes just released in [v4.0.0-rc.0](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-rc.0), since we updated the storage [data model](https://github.com/GoogleChrome/workbox/blob/v4.0.0-rc.0/packages/workbox-expiration/models/CacheTimestampsModel.mjs) for this plugin, and what you were looking at before is probably different now.

As for how to implement this feature, I think a good place to start would be for us to agree on a proposal for how the API would look.

Your suggestion works in cases where `max-age` is used, but for cases where other cache headers are used, it might provide more flexibility to let the `maxAge` config option accept a function that's invoked with the `Response` object being cached, and whatever it returns will be used for `maxAge`. For example:

```js
new workbox.expiration.Plugin({
  maxAgeSeconds: (response) => {
    return response.headers.get('max-age');
  }
  purgeOnQuotaError: true,
});
```

What do you think?

**Comment by zsolt-dev** [comment]
@philipwalton Yes this sounds like great and flexible way of achieving this. My suggestion was just for illustration purposes :)

Will take a look at the new codes data model tomorrow. If that could work, would you mind if create this functionality and create a PR?

Thank you for helping me

**Comment by philipwalton** [comment]
I don't mind at all! We're very open to PRs.

**Comment by zsolt-dev** [comment]
I have checked the code of v4.0.0-rc.2 and it looks like this version is storing the cache creation date, like the previous version.
```
here is the call simplified stack:
cacheDidUpdate() -> updateTimestamp() -> this._timestampModel.setTimestamp(url, Date.now());
```

As I see it we have 3 solutions for per request (variable) expiration time:

1. store expiration date, not the creation date
- big rewrite, probably will not work great with maxEntries expiring option (will not properly delete the oldest cache items. but the ones with the shortest max Age header)

2. store creation date like now, but add max Age value to the current date
- small rewrite, the same functionality and problems as solution 1. Will look weird, that cache entries are from future (Date.now() + max-age header)

3. store creation date AND max age
- probably the cleanest solution and backwards compatible. The cache purging logic would need to be rewritten.

I would appreciate if some of the lead developers of workbox would provide some feedback on this.

Thank you

**Comment by jitendra1607** [comment]
This i what i am doing in custom service worker
`
workbox.routing.registerRoute(
  /http:\/\/127\.0\.0\.1\//,
  new workbox.strategies.CacheFirst({
    cacheName: 'api-cache',
    plugins: [
      new workbox.cacheableResponse.Plugin({
        statuses: [200]
      }),
      new workbox.expiration.Plugin({
        maxAgeSeconds: (response) => {
          return parseInt(response.headers.get('X-Is-Cacheable'))
        },
        purgeOnQuotaError: true
      })
    ]
  }),
  'GET'
)
`
Following is my response headers, i would like use 'X-Is-Cacheable' header to decide cache expiration based on its value in seconds. So how can i bypass 'Date' header strategy in workbox to use 'X-Is-Cacheable' only.
`
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization, X-Fp-Header, X-Token-Header
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: http://127.0.0.1:8080
Access-Control-Expose-Headers: X-Token-Header, X-Is-Cacheable
Access-Control-Max-Age: 86400
Cache-Control: no-cache, private
Connection: closed, Keep-Alive
Content-Length: 82
Content-Type: application/json
Date: Tue, 11 Jun 2019 04:49:15 GMT
X-Is-Cacheable: 600
Accept: application/json, text/plain, */*
`

**Comment by jeffposnick** [comment]
Sorry for the delay—I wanted to revisit this proposal. I am not sure that there's enough demand to change the basic behavior of `workbox-expiration` to support the original proposal, but I did want to offer some guidance on how something like this could be accomplished via a [custom Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins), which you'd obviously be welcome to package up and release if you wanted!

The `cachedResponseWillBeUsed` callback is invoked right before a response from the cache is used to fulfill a request, and would give you the opportunity to inspect the response to see if it meets your custom freshness criteria. If it doesn't, you could then delete the underlying entry from the cache (to clean things up, so it won't be attempted to be used again) and return `null`, indicating a cache miss.

That would look something like:

```
const customExpirationPlugin = {
  cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event}) => {
    // Note that reading headers will only work for same-origin responses, or CORS responses
    // with the appropriate Access-Control-Expose-Headers setting!
    // See https://jeffy.info/2019/07/22/exposing-cors-headers.html

    // This assumes Expires: is set. Alternative, you could use
    // Date: and the max-age value in Cache-Control.
    const expiresHeader = cachedResponse.headers.get('expires');
    if (!expiresHeader) {
      return cachedResponse;
    }

    const expirationDate = new Date(expiresHeader);
    if (expirationDate.getTime() > Date.now())  {
      return cachedResponse;
    }

    // If we get here, then the response is expired.
    event.waitUntil(
      caches.open(cacheName).then(
        (cache) => cache.delete(request, matchOptions))
    );

    return null;
  },
};

registerRoute(
  // request.destination is an alternaive to checking file extensions.
  ({request}) => request.destination === 'image',

  new CacheFirst({
    cacheName: 'images',
    plugins: [
      customExpirationPlugin,
    ],
  }),
);
```

**Comment by H1D** [comment]
@zsolt-dev  If proper `Expires` header is present already why bother using SW for that? Browser will do the job isn't it? Or I'm missing something?

**Comment by yury-kozlov** [comment]
@H1D There's plenty of information about the differences between browser cache and service worker, just google it.
