### ISSUE TITLE
response from BackgroundSync when request was stored in Queue

### ISSUE THREAD

**Issue by jszczypk** [GoogleChrome/workbox#1882]
**Library Affected**:
workbox-background-sync

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I would like to have a possibility to set an option on a backgroundSync plugin to define a response used to reply back to client when request was stored in Queue. This way we will have possibility to check what happened with a request and show to user appropriate message.

**Comment by SampsonCrowley** [comment]
@jeffposnick it seems that ONLY onSync is available now. I can't get any other callbacks to fire

**Comment by jeffposnick** [comment]
That's true—there's documentation on the new v4 behavior at https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3#workbox-background-sync

**Comment by jeffposnick** [comment]
Revisiting this, I think the best course of action would be for you to create your own [`fetchDidFail` plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) that you add to the strategy's `plugins` array following the `BackgroundSyncPlugin`. That's the same plugin callback that `BackgroundSyncPlugin` implements, so both would end up being executed.

Something like:

```
const myPlugin = {
  fetchDidFail: async ({originalRequest, request, error, event}) => {
    // Do something to notify the user.
  },
};

const myStrategy = new NetworkOnly({
  plugins: [
    new BackgroundSyncPlugin({...}),
    myPlugin,
  ],
});
```
