### ISSUE TITLE
[v4.0.0-rc.0] CDN ACL issue

### ISSUE THREAD

**Issue by frlinw** [GoogleChrome/workbox#1887]
https://storage.googleapis.com/workbox-cdn/releases/4.0.0-rc.0/workbox-sw.js

![image](https://user-images.githubusercontent.com/11896237/52372161-b9d86a00-2a57-11e9-817d-edb293bc9d04.png)

cdn really needs to be more reliable.

previous issue https://github.com/GoogleChrome/workbox/issues/1332

**Comment by jeffposnick** [comment]
Thanks—we'll get it sorted shortly. @philipwalton

**Comment by philipwalton** [comment]
Thanks, the release has now been pushed to the CDN. Let me know if you're seeing any other issues!
