### ISSUE TITLE
Loading the service worker file from different domain

### ISSUE THREAD

**Issue by chetanraj** [GoogleChrome/workbox#1890]
**Library Affected**: workbox-build

**Browser & Platform**: all browsers

**Issue or Feature Request Description**: We've integrate the sw.js to a domain a.com which us buils using the workbox-build, and the a.com is included in an iframe in b.com
Can you please help i'm facing the error - **Service Worker error ::  Failed to register a ServiceWorker: The origin of the provided scriptURL ('a.com') does not match the current origin ('b.com').**

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
A page on a given origin can only register a service worker that is hosted on the same origin.

You can register a service worker inside of a page within an `<iframe>`, so it sounds like what you want to do is make sure the call to register is made from the page you have `<iframe>`d, not the host page.

(This is not a limitation in Workbox; it's how the service worker specification is designed.)
