### ISSUE TITLE
[Question] workbox-sw es import

### ISSUE THREAD

**Issue by frlinw** [GoogleChrome/workbox#1891]
**Library Affected**:
workbox-sw

**Issue or Feature Request Description**:
As workbox-webpack-plugin `importScripts` option does not accept chunk name currently, I'm trying to use `importWorkboxFrom` (which accept chunk name) with the name of my service worker chunk.
It works but I don't find a way to import workbox.
After a `npm install workbox-sw`, I tried:
```js
import workbox from 'workbox-sw'
import * as workbox from 'workbox-sw'
// @ is an alias
import workbox from '@/node_modules/workbox-sw/build/workbox-sw.js'
import precaching from '@/node_modules/workbox-precaching/build/workbox-precaching.prod.js'
import routing from '@/node_modules/workbox-routing/build/workbox-routing.prod.js'
```
As a workaround, it works with importScripts
```js
importScripts('https://unpkg.com/workbox-sw@4.0.0-rc.0/build/workbox-sw.js')
```
But I get the following error on runtime
```
Uncaught ReferenceError: importScripts is not defined
```

Is there a way to import workbox-sw ?

**Comment by philipwalton** [comment]
When using a bundler, you wouldn't ever want to import `workbox-sw`. Instead, you'd just import the individual packages you're using. For example:

```js
import * as routing from 'workbox-routing';
import * as strategies from 'workbox-strategies';
import * as expiration from 'workbox-expiration';

routing.registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  new strategies.CacheFirst({
    cacheName: 'images',
    plugins: [
      new expiration.Plugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);
```

Once v4 is release, I'm planning to publish this [draft article on using Workbox with bundlers](https://docs.google.com/document/d/1LbRxTbTKM8W6Qt0S6rGEP9V51sX8tRpGbqJ_IwoXxEQ/edit?usp=sharing), but you might find it useful now if you're already using the release candidate.

**Comment by frlinw** [comment]
@philipwalton Thank you ! Indeed it seems to work but throw an error
![image](https://user-images.githubusercontent.com/11896237/52436902-cde2a100-2b15-11e9-9eeb-c7ffc03433a3.png)
Point to
![image](https://user-images.githubusercontent.com/11896237/52437004-0d10f200-2b16-11e9-8dc2-5fdb94bf6fbe.png)

**Comment by philipwalton** [comment]
Hmmm, if `importScripts` and `self.registration` are both undefined, it sounds like you're running this in the window context and not in the service worker.

Can you check that?

**Comment by frlinw** [comment]
The stack trace show the error comes from `sw.[hash].js` which is the only file added in the sw.js
![image](https://user-images.githubusercontent.com/11896237/52441650-85c97b80-2b21-11e9-98ea-6cbfa6dff9d9.png)
so, normally, it's the service worker context

**Comment by frlinw** [comment]
@philipwalton still no clue about this error...
the error is on `cacheNameDetails.suffix` but the cache name is well formed in the devtools application tab and everything works as expected
you can check it here https://app-stg.diagfactory.com if you have an idea...
