### ISSUE TITLE
Link to relevant docs page in warning messages

### ISSUE THREAD

**Issue by sheerun** [GoogleChrome/workbox#1893]
I'm using latest Chrome and latest workbox rc.0

I'm importing Workbox as so:

```
const main = async () => {
  const wb = new Workbox('/static/service-worker.js');
  await wb.register();
}

main()
```

But it complains:

The current page is not in scope for the registered service worker. Was this a mistake?

It turns out that scopeURLBasePath is set to `/static` which prevents proper registering. I think it should not matter whether service worker is inside static directory or not.

**Comment by sheerun** [comment]
Or is it a requirement?

**Comment by philipwalton** [comment]
The warning is to help prevent lots of accidental mistakes we've seen in the past with service worker scope mismatch.

If you register your service worker at the URL `/static/service-worker.js`, then that service worker will never be able to control requests on page `/index.html`. Its scope only lets it control pages under `/static/*`. You can read more about the [scoping rules here](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope).

This is not a Workbox requirement, it's a service worker requirement. Does that help explain why the warning is there?

**Comment by sheerun** [comment]
Yes, but I have two notes:

1. The "scoping rules" page you've linked to tells "You can also set an arbitrary scope by passing in an additional parameter when registering." which can be misleading as it suggests I can override `/static` scope to `/`. A documentation update would be helpful there that for example tells instead "You can also reduce scope that service worker can control by passing in an additional parameter when registering."
2. I really like to warnings React shows in console because they link to relevant pages where I can learn more about these issues. Maybe Workbox could adopt this as well? For example you could link to the page you've just linked to directly in warning message as shortened link.

**Comment by philipwalton** [comment]
Agreed, we're planning to eventually link these warnings to documentation pages.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
