### ISSUE TITLE
[v4.0.0-rc.1] Can't copy libraries

### ISSUE THREAD

**Issue by webmaxru** [GoogleChrome/workbox#1901]
**Library Affected [v4.0.0-rc.1]**:
*workbox-cli, workbox-build*

**Browser & Platform**:
*MacOS*

**Issue or Feature Request Description**:
For the RC.1 when you copy the libraries using CLI or workbox-build there is an error:
```
workbox copyLibraries testDir

One or more of the Workbox libraries could not be copied over to the destination directory:
Error: ENOENT: no such file or directory, lstat 'packages/workbox-background-sync/build'
```

cc: @philipwalton

**Comment by jeffposnick** [comment]
This was introduced in https://github.com/GoogleChrome/workbox/pull/1895/files#diff-67f62b752408d4f9a08ce4f73718d971R51.

We need to go back to using `require.resolve()` to get the path to the directory that contains each of the published packages. Using a hardcoded relative path that includes 'packages/' will only work in a local development environment, but not for end users who are loading things from `node_modules`.
