### ISSUE TITLE
"PrecacheEntry shouldCacheBust" not exposed for use

### ISSUE THREAD

**Issue by lecepin** [GoogleChrome/workbox#1904]
The `shouldCacheBust` property is not exposed, causing caching issues with `precache`.

![image](https://user-images.githubusercontent.com/11046969/52763759-06273980-3058-11e9-9505-5bc73b7b6e53.png)

```
  class PrecacheEntry {
    /**
     * This class ensures all cache list entries are consistent and
     * adds cache busting if required.
     *
     * @param {*} originalInput
     * @param {string} url
     * @param {string} revision
     * @param {boolean} shouldCacheBust
     */
    constructor(originalInput, url, revision, shouldCacheBust) {
      this._originalInput = originalInput;
      this._entryId = url;
      this._revision = revision;
      const requestAsCacheKey = new Request(url, { credentials: 'same-origin' });
      this._cacheRequest = requestAsCacheKey;
      this._networkRequest = shouldCacheBust ? this._cacheBustRequest(requestAsCacheKey) : requestAsCacheKey;
    }
```

```
      entries.map(userEntry => {
        this._addEntryToCacheList(this._parseEntry(userEntry));
      });
```

```
    _parseEntry(input) {
      switch (typeof input) {
        case 'string':
          {
            {
              if (input.length === 0) {
                throw new WorkboxError_mjs.WorkboxError('add-to-cache-list-unexpected-type', {
                  entry: input
                });
              }
            }

            return new PrecacheEntry(input, input, input);
          }
        case 'object':
          {
            {
              if (!input || !input.url) {
                throw new WorkboxError_mjs.WorkboxError('add-to-cache-list-unexpected-type', {
                  entry: input
                });
              }
            }

            return new PrecacheEntry(input, input.url, input.revision || input.url, !!input.revision);
          }
        default:
          throw new WorkboxError_mjs.WorkboxError('add-to-cache-list-unexpected-type', {
            entry: input
          });
      }
    }
```

**Comment by jeffposnick** [comment]
Hello!

I'm a little unclear on how you're planning on using `PrecacheEntry`, but in general, the assumption is that if you're passing in a `string` to the constructor, that the URL represented by the string already includes versioning info, and therefore there's no cache-busting required. If you're passing in an object, then whether or not there's a `revision` field determines whether cache-busting is required. This is handled for your automatically if you use the `workbox.precaching` interface.

Also note that a lot of the precaching code, including this, has been update in Workbox v4. The same general principle applies, but in v4, cache-busting is handled by adding in a query parameter to URLs that need to be revisioned:

https://github.com/GoogleChrome/workbox/blob/0b3937f8abf66f6a03d01a29d247bbeb739e7a23/packages/workbox-precaching/utils/createCacheKey.mjs#L30-L63

So... could you clarify how you're using `PrecacheEntry` and what exactly is breaking for you?

**Comment by lecepin** [comment]
When the version changes, the workbox does re-acquire and update, which is fine.
However, when the workbox gets the page, there may be a cache on the page, causing the version to be updated, but the content is still old.
So I think, when the version changes, add {cache: reload} to the request.

**Comment by lecepin** [comment]
![image](https://user-images.githubusercontent.com/11046969/52841032-0eee3d00-3136-11e9-8e9f-48293e807506.png)
Make sure you get the latest

**Comment by jeffposnick** [comment]
That should already happen in this piece of code, which is responsible for creating the `precacheEntry._networkRequest` in scenarios in which cache-busting needs to happen:

https://github.com/GoogleChrome/workbox/blob/b146d8d3c2db89fa51afc322049b9795894bb4f2/packages/workbox-precaching/models/PrecacheEntry.mjs#L59-L64

`cache: 'reload'` should be just as safe as `cache: 'no-store'` when it comes to bypassing the browser's cache: https://fetch.spec.whatwg.org/#concept-request-cache-mode

Given that, are you actually experiencing a problem? The code to set `cache: 'reload'` should automatically be called by `workbox-precaching` whenever it detects an entry in the precache manifest that contains a `revision:` field.
