### ISSUE TITLE
[suggestion] Minimal workbox template for issue reproduction

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChrome/workbox#1911]
**Library Affected**:
*N/A*

**Browser & Platform**:
*N/A*

**Issue or Feature Request Description**:
I've created a [workbox-template](https://github.com/jadjoubran/workbox-template) which contains minimal code + webpack configuration that can be used to reproduce some of the issues that are reported here. 
For example, if someone reports an issue with the router, and in case the user does not have a public URL of the issue, then they can clone this repository and use the existing webpack configuration and "sample" api provided with it (it's just a JSON file) to reproduce the issue.  

Let me know what you think, if you think that will be useful, suggestions for improvements, etc.

**Comment by jeffposnick** [comment]
That's great, @jadjoubran!

How did you envision it being used? I could see us adding a link to it from https://github.com/GoogleChrome/workbox/blob/master/.github/ISSUE_TEMPLATE.md, for instance, but maybe you had something else in mind.

**Comment by jadjoubran** [comment]
yes indeed, I envision that at a minimum, we could ask people to reproduce the issue on that repo. It could be that adding it to the issue template would discourage folks from opening an issue. WDYT?

Some limitations of the repo right now:
- [ ] Missing support for wokbox-cli & workbox-build. Maybe I could fix that by creating 3 folders with different setups. One for the CLI, another one for the node module and a third one for webpack (which is the current setup)
- [ ] I'll add a `deploy` script so that folks can quickly deploy the replicated issue to a url (tracked in https://github.com/jadjoubran/workbox-template/issues/1)

Let me know if you'd rather that I transfer it to `GoogleChrome` org or `GoogleChromeLabs`

**Comment by jeffposnick** [comment]
Sorry for not getting back to you sooner—I think keeping it in your own repo should be fine for now!

If you wanted to file a PR with updates to https://github.com/GoogleChrome/workbox/blob/master/.github/ISSUE_TEMPLATE.md, that would be 👍

**Comment by jadjoubran** [comment]
no worries 👍
I will work on the 2 improvements that I noted on [workbox-template](https://github.com/jadjoubran/workbox-template) and then submit the PR
I'll close the issue here as I'm tracking the issues over there and I don't want to add noise here
Cheers!
