### ISSUE TITLE
How to turn workbox logging off while running in dev/localhost with v4.0.0-rc.4?

### ISSUE THREAD

**Issue by floydpink** [GoogleChrome/workbox#1920]
**Library Affected**:
*workbox-core*

**Browser & Platform**:
*Google Chrome v72.0.3626.119 (Official Build) (32-bit) for Windows*

**Issue**:
From the release notes, I see that `setLogLevel` and `LOG_LEVELS` are removed in v4.0.0 - but while running again localhost there is no way to completely turn off workbox logging.

We do have 3200+ files that are getting into workbox precache - and after using the log filters in Chrome, the empty group statements still remain.

Any other debug/log messages in the app is getting drowned in worbox logs.

Is there a way to turn off logging even on development/local environment?

**Comment by philipwalton** [comment]
You can run `workbox.setConfig({debug: false})` ([docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox#.setConfig)) to force the production version even on localhost. That's probably your best bet.

The group filtering issue not working is an annoying bug in DevTools that I believe is being worked on now. You can star it or add a comment to help let the team know it's important to you: https://bugs.chromium.org/p/chromium/issues/detail?id=363796

**Comment by floydpink** [comment]
Thank you @philipwalton - I have starred and commented on the Chromium issue.

The workaround of running workbox in production mode will work for us for now.

**Comment by nhoizey** [comment]
@philipwalton the `Enable 'debug' Logs` section in https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug#enable_debug_logs still says to use `workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);`, should it be removed?

**Comment by hheimbuerger** [comment]
As nhoizey said, the documentation recommends a call that is no longer valid in 4.x. Please remove that section.

**Comment by jeffposnick** [comment]
Thanks for pointing this out; I've filed https://github.com/google/WebFundamentals/pull/7567 to update that.

**Comment by tvvignesh** [comment]
@jeffposnick Hi. May I know how to switch off logging when using CLI config file: https://developers.google.com/web/tools/workbox/modules/workbox-cli

The generated sw.js explicitly says not to edit it but rather change the config file. But, I don't find any option to switch off logging in the configuration options.
