### ISSUE TITLE
JSDoc issues in v4.0.0

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1921]
We found a few issues with the JSDoc-generated HTML for v4.

- There's no longer a https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing landing page and some of the `workbox.routing` methods are mixed in with a top-level `workbox` heading.

- There's no longer a https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox landing page that lists all of the synthetic namespaces that `workbox-sw` can load, along with the `setConfig()` and `loadModule()` docs.

**Comment by jeffposnick** [comment]
Once this is resolved, we need to update the links to the landing pages in https://developers.google.com/web/tools/workbox/modules/ and the sidebar of https://developers.google.com/web/tools/workbox/reference-docs/latest/

**Comment by darkscript** [comment]
@philipwalton I see a line ```// TODO(philipwalton): add jsdoc tags to associate these with their module.``` please give us the jsdocs for easy development, thanks

**Comment by philipwalton** [comment]
@darkscript all the APIs are documented. That TODO refers to considering whether it makes sense to document them as modules or as namespaces (currently they're only documented as namespaces on the global `workbox` object).

You can see the full list of APIs here, and this should also help you see the difference between modules vs. namespaces in jsdocs: https://developers.google.com/web/tools/workbox/reference-docs/latest/index-all

**Comment by darkscript** [comment]
@philipwalton I understand, I just had issues in my ide when am working with ``'associate modules' `` like you can see on my ide its always complaining, so I believe it was related to jsdocs
![intellij(Jetbrains)workbox](https://user-images.githubusercontent.com/13992858/56785515-33cdf300-67fe-11e9-9b11-c480c6126211.png)
