### ISSUE TITLE
still on 3.6.3 but catch handler doesn't work anymore in production

### ISSUE THREAD

**Issue by jamessouth** [GoogleChrome/workbox#1923]
In my SW I have a fallback image url used in a catch handler just like in the docs, and in offline mode it has always worked, but not today, despite no changes to my code.  I'm still on 3.6.3 via the Vue-CLI.  In production, the catch handler route is not being engaged - I get a bunch of failed to fetch errors and `The FetchEvent for "<URL>" resulted in a network error response: an object that was not a Response was passed to respondWith().`  However, in dev when I serve my docs folder on localhost, offline mode works as expected - the fallback image appears.  While waiting for the Vue-CLI to update to use 4.0.0, I tried adding `getCacheKeyForURL` per the migration guide but in 3.6.3 it's not a function and it threw an error.

**Library Affected**:
![capture1](https://user-images.githubusercontent.com/25541381/53540262-67302200-3ada-11e9-9375-8edfec082016.PNG)

**Browser & Platform**:
Google Chrome Version 72.0.3626.119 (Official Build) (64-bit), Windows 10

live site is [here](https://jamessouth.github.io/Vue-Project-9/)

source [here](https://github.com/jamessouth/Vue-Project-9/blob/master/web-app-dashboard/src/service-worker.js)

I use IntersectionObserver to lazy load components, so to repro scroll all the way down until the fake users load, reload to engage SW and scroll down again, then go offline and reload and scroll down, fallback image does not appear where the fake user pics go.

**Comment by jeffposnick** [comment]
Hello James—I believe the issue is that your service worker is configured with

```
const FALLBACK_IMAGE_URL = '/img/face.69232788.jpg';
```

That's not a URL that corresponds to a cached asset. I think you need to add the `/Vue-Project-9/` prefix to your URL.

You can confirm this in the JS console directly:

```
await caches.match('/img/face.69232788.jpg') ➡
undefined

await caches.match('/Vue-Project-9/img/face.69232788.jpg') ➡
Response {type: "basic", url: "https://jamessouth.github.io/Vue-Project-9/img/face.69232788.jpg", redirected: false, status: 200, ok: true, …}
```

**Comment by jamessouth** [comment]
ok thank you Jeff
