### ISSUE TITLE
Error in the doc's for Offline GA

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1930]
I think there is an error in the doc's, see this link: https://developers.google.com/web/tools/workbox/guides/enable-offline-analytics

In the example you write:

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0/workbox-sw.js');

workbox.googleAnalytics.initialize();
```

I think you mean to write this:

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0/workbox-offline-ga.prod.js');

workbox.googleAnalytics.initialize();
```

I might be missing something, but I thought I file an issue just in case.

p.s. congrats to all the hard work and bringing out V4.

**Comment by philipwalton** [comment]
> p.s. congrats to all the hard work and bringing out V4.



Thanks!

>  I think there is an error in the doc's, see this link:

The documentation is actually correct here. The `workbox-sw.js` file is just a script loader that loads the other dependencies based on the referenced namespaces, so when you refer to `workbox.googleAnalytics`, it automatically downloads that script.

You can read more about how `workbox-sw` works here:
https://developers.google.com/web/tools/workbox/modules/workbox-sw
