### ISSUE TITLE
[broadcast-update] Plugin errors when added to precache

### ISSUE THREAD

**Issue by craigjennings11** [GoogleChrome/workbox#1931]
**Library Affected**:
workbox-broadcast-update@4.0.0

**Browser & Platform**:
Google Chrome Version 72.0.3626.119

**Issue or Feature Request Description**:
BroadcastCacheUpdate errors when I add it as a plugin to the precache. I have the following code in my service-worker:

```js
workbox.precaching.addPlugins([
  new workbox.broadcastUpdate.Plugin('precache-updates'),
]);

workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
```

When I change something in a file that is precached and refresh the page, I get the following error:

![image](https://user-images.githubusercontent.com/1683368/53668286-1256ed80-3c39-11e9-95a0-ce880b24a0c1.png)

https://github.com/GoogleChrome/workbox/blob/bd5f4114a90178476e60be549f72ddce779e3344/packages/workbox-broadcast-update/BroadcastCacheUpdate.mjs#L101

Apparently `event` exists but does not have a `request` object on it.

**Comment by jeffposnick** [comment]
Apologies for the issue—this should be fixed in https://github.com/GoogleChrome/workbox/pull/1938
