### ISSUE TITLE
items loaded through PrecacheController not resolvable

### ISSUE THREAD

**Issue by mcshaman** [GoogleChrome/workbox#1933]
**Library Affected**:
*workbox.precaching*

**Browser & Platform**:
*Google Chrome v74*

**Issue or Feature Request Description**:
When adding precache through a PrecacheController object workbox doesn't appear to be able to resolve cache items.

```javascript
importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.0.0/workbox-sw.js')

const precacheController = new workbox.precaching.PrecacheController()

precacheController.addToCacheList(['/index.html'])

self.addEventListener('install', pEvent => {
	pEvent.waitUntil(precacheController.install())
})

self.addEventListener('activate', () => {
	console.log(workbox.precaching.getCacheKeyForURL('/index.html')) // >> undefined
})
```

**Comment by jeffposnick** [comment]
`getCacheKeyForUrl()` is a method on `PrecacheController`: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheController#getCacheKeyForURL

When you call `workbox.precaching.getCacheKeyForURL()` it will end up calling the method on the "default" `PrecacheController` instance, but you're not using that instance; because you're creating your own instance, you need to call `getCacheKeyForUrl()` on that one instead:

```
const customController = new workbox.precaching.PrecacheController();
customController.addToCacheList(['/index.html']);
console.log('Cache key is', customController.getCacheKeyForURL('/index.html'));
```

**Comment by jeffposnick** [comment]
(Closing for now, but if that doesn't resolve the issue for you or if there are other questions, let us know and we can reopen.)

**Comment by Vicradon** [comment]
Library Affected:
workbox.precaching

Browser & Platform:
Google Chrome v79

Issue or Feature Request Description:
When adding precache through a PrecacheController object workbox doesn't appear to be able to resolve cache items.

```javascript
 const static = 'static-v1.1.5';
 const cache = new workbox.precaching.PrecacheController(static);

this.addEventListener('fetch', event => {
    const cacheKey = cache.getCacheKeyForURL(event.target.url);
    console.log(cacheKey)
});
```

I am getting the following error
sw.js:55 Uncaught TypeError: cache.getCacheKeyForURL is not a function
