### ISSUE TITLE
Workbox and Notifications Spam

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1934]
I'm always watching videos done by the highly skilled Google Chrome dev team. I watched a video a few weeks ago on Service Workers and Notifications Spam.

Basically the spot that came across to me was the Googler saying that if you add notifications to all your web pages on your website you are mostly likely just going to spam the User. For example, if a User comes to your home page and before they start to do anything they get bombarded with a pop-up asking them to accept Notifications. This to me is bad User experience! Plus the Notifications  that website will send at a later time will most likely be really poor quality to the User.

The Googler gave an example saying if the User has gone to a flights website and filled out the contact form and then gets a Notification to tell the User that the form has been processed that is a good User experience.

To me I like making websites with this kind of User experience! Which got me thinking and why I am writing this issue.

To be honest the way Service Workers are set up they are made to Spam the internet and I would like to see a feature in Workbox where a User could go to a home web page and not see the Notification pop-up. But only see the Notification pop-up after filling out a form and clicking on an option to receive the Notification.

So being able to whitelist certain web pages or folders etc. and turning off all the rest of the website thus not annoying Users.

I be interested to see what people suggest or how to properly set this up.

**Comment by jeffposnick** [comment]
Hello @ayumihamsaki!

I understand and share the frustration you feel when visiting websites that show Notification prompts too aggressively.

Unfortunately, sharing that feedback in the Workbox issue tracker is not likely to lead to any changes in that behavior. I do think it's outside the scope of what we can accomplish with Workbox.

I'd encourage you to share specific ideas for browser-level changes via the corresponding issue tracker for each browser, e.g. https://crbug.com for Chrome-related changes.
