### ISSUE TITLE
ignoreUrlParametersMatching seems to be not working

### ISSUE THREAD

**Issue by floydpink** [GoogleChrome/workbox#1936]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*All browsers.*

**Issue**:
I am using workbox 4.0.0 and have a gulp task that uses `injectManifest` method of `workbox-build` - and the source/template file for service-worker (`swSrc`) has this block in it:

```
workbox.precaching.precacheAndRoute(
    [],
    {
        ignoreUrlParametersMatching: [/.*/]
    });
```

This is getting updated correctly to become the built service-worker (`swDest`) that looks like this:

```
workbox.precaching.precacheAndRoute([
  {
    "url": "style.css",
    "revision": "0ba0898e1a16d9f6eeec49041da47e79"
  },
  {
    "url": "script.js",
    "revision": "e8387f082ead450d27fa5c2865ad0eec"
  },
  // ...many more such files
],
    {
        ignoreUrlParametersMatching: [/.*/]
    });
```

But precaching does not match a request in this form: `http://localhost:8080/style.css?v4.7.0`

While debugging with breakpoints set within the [`addRoute` method within `workbox-precaching.dev.js`][1], it looks like `ignoreURLParametersMatching` there still has the default value specified there: `[/^utm_/]`

What is interesting is, [the `precacheAndRoute` function][2] that calls the `addRoute` function itself seems to have the right value on the options object.

Could someone point out what I could be doing wrong?

  [1]: https://github.com/GoogleChrome/workbox/blob/bd5f4114a90178476e60be549f72ddce779e3344/packages/workbox-precaching/addRoute.mjs#L42
  [2]: https://github.com/GoogleChrome/workbox/blob/bd5f4114a90178476e60be549f72ddce779e3344/packages/workbox-precaching/precacheAndRoute.mjs#L30

**Comment by floydpink** [comment]
Looks like it is case of case mismatch - [the documentation](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#ignore_url_parameters) has the parameter specified as `ignoreUrlParametersMatching` (which is where I copy-pasted from) - and the `addRoute` function now has it as `ignoreURLParametersMatching`

Is there a way I can send a PR to update the documentation?

**Comment by jeffposnick** [comment]
Thanks for pointing this out—it's fixed in https://github.com/google/WebFundamentals/pull/7350
