### ISSUE TITLE
Handling errors in onSync causes infinite loop.

### ISSUE THREAD

**Issue by chimon2000** [GoogleChrome/workbox#1937]
**Library Affected**:
*workbox-background-sync*

**Browser & Platform**:
Google Chrome v72.0

**Issue or Feature Request Description**:
I am attempting to override the `onSync` method such that failing status codes add the request back to the queue:

```
                const response = await fetch(entry.request.clone())

                if ([504, 500].includes(response.status)) {
                    throw new Error('Cannot reach server')
                }
```

This results in an infinite loop of syncs to occur.

![image](https://user-images.githubusercontent.com/6907797/53757356-7112a600-3e89-11e9-8763-d4888b3055eb.png)

**Comment by chimon2000** [comment]
I believe this happens because adding a request back to the queue causes a new sync to be triggered.

https://github.com/GoogleChrome/workbox/blob/bd5f4114a90178476e60be549f72ddce779e3344/packages/workbox-background-sync/Queue.mjs#L182-L183

**Comment by jeffposnick** [comment]
CC: @philipwalton for visibility.
