### ISSUE TITLE
[GenerateSW] Destination paths setup 

### ISSUE THREAD

**Issue by diemate** [GoogleChrome/workbox#1940]
Hello,

I have configured a SSR React Application where I'm trying to use a service worker using the webpack plugin.
My desired output structure would be something like:

```
├── assets
│   ├── fonts
│   ├── js
│   ├── precache-manifest.dabf9f8d50f363cf5fd594a1b09ac74a.js
│   └── service-worker.js
└── server
    ├── app.js
    └── index.ejs
```
But my problem is that there is no independency between `swDest` and `importsDirectory` properties. So when I configure the plugin with both, the service-worker does not work.

```
    new GenerateSW({
      swDest: 'assets/service-worker.js',
      importsDirectory: 'assets',
      runtimeCaching: [...],
    }),
```

If I use that pattern, I achieve my goal and I have my desired output *but* the problem is the natural behaviour of service worker, because when I register it the `service-worker.js` file has an import like this `importScripts("assets/precache-manifest.dabf9f8d50f363cf5fd594a1b09ac74a.js");`
So once the service worker is loaded in my webpage, it requires for the precache manifest following the same domain pattern, because I want to load it like:
```
  if ('serviceWorker' in navigator) {
      window.addEventListener('load', function() {
          navigator.serviceWorker.register('assets/service-worker.js');
      });
  }
```
Then, it tries to request the file adding an extra `asset` part in the url `http://localhost:8080/assets/assets/precache-manifest.dabf9f8d50f363cf5fd594a1b09ac74a.js`

Knowing that I need to maintain that's structure because of architecture limitation, is there anything I can add to the webpack setup for solving the problem?

Kind regards.

**Comment by jeffposnick** [comment]
In general, serving your `service-worker.js` file from inside of an `assets/` subpath is not going to work—as per the service worker specification, you need to serve your `service-worker.js` file from your top-level path if you want its `scope` to include everything on your site. (If you serve it from `assets/`, then the maximum `scope` is also going to be `assets/`, meaning it can't control any of your pages that exist outside of `assets/`.)

There's more info about this at https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope

You should use `swDest: 'service-worker.js'`, I believe, given your setup.

I'm going to close this for now, given those restrictions imposed by the service worker specification, but let me know if that doesn't solve the issue to your satisfaction and we can revisit.

**Comment by diemate** [comment]
Hello @jeffposnick, thank you very much for your quick answer. 

Actually, according to the architecture I have, the scope I'd like to be controlled by the `service-worker` is just everything from `assets/` so that would be perfect. 
The problem with this setup is the service-worker file which Webpack creates, adds the `assets` word to the relative route in the imported scripts `importScripts("assets/precache-manifest.dabf9f8d50f363cf5fd594a1b09ac74a.js")`

What I actually need is a mix between `swDest` and `importsDirectory` Because, since both of the properties are independent, it creates the file with the wrong importScript route.

So the perfect situation for this case would be to have both files (service-worker.js and precache-manifest[hash].js) created in the same directory, as they are right now, but the import script should be 
`importScripts("precache-manifest.dabf9f8d50f363cf5fd594a1b09ac74a.js")` because, as you have said, -as per the service worker specification- then it will add the `assets` word to the precache manifest file request.

Is there anything I can do?

Thank you very much!

**Comment by peakhmr** [comment]
I'm having an issues with url generated
```
self.__precacheManifest = (self.__precacheManifest || []).concat([
  {
    "url": "/js/ExampleComponent/92c0f1db1213eb4815bb.js"
  },
  {
    "revision": "17730d9ee4d14a19a202",
    "url": "//js/vendor.js"
  },
  {
    "revision": "6d4123cac0fc5a2ec655",
    "url": "//js/manifest.js"
  },
  {
    "revision": "447b2dbb3afb3dba50d8",
    "url": "//js/app.js"
  },
  {
    "revision": "447b2dbb3afb3dba50d8",
    "url": "//css/app.css"
  }
]);
```

**Comment by jeffposnick** [comment]
@diemate, you wrote:

> Actually, according to the architecture I have, the scope I'd like to be controlled by the service-worker is just everything from assets/ so that would be perfect.

When users navigate to HTML pages on your domain, do those URLs include the prefix `/assets/`? I.e., is your home page `https://example.com/assets/index.html` or is it `https://example.com/index.html`?

I'm assuming it's the latter, in which case you need to serve your service worker from `https://example.com/service-worker.js`, not `https://example.com/assets/service-worker.js`.

By default, a service worker served from `https://example.com/assets/service-worker.js` would not be able to take control of a page with URL `https://example.com/index.html`.

When thinking about service worker scopes and control, you need to take into account the URL of your HTML, not the URLs of subresources that are loaded by that HTML.

**Comment by diemate** [comment]
Hello @jeffposnick,
Thank you so much for your answer. 
I didn't aware of this
```
I'm assuming it's the latter, in which case you need to serve your service worker from https://example.com/service-worker.js, not https://example.com/assets/service-worker.js.
```
Knowing that, there should not be any problem though, the only thing I will need to do is to move the files after the creation, because of the deployment requirements. 

Thank you so much for your help!
