### ISSUE TITLE
Debug logger duplicates logged items; increments on each tab re-opening

### ISSUE THREAD

**Issue by gctommy** [GoogleChrome/workbox#1942]
**Library Affected**:
workbox-sw.js 4.0.0

**Browser & Platform**:
Chrome 72.0.3626.121 on Windows 10

**Issue or Feature Request Description**:
Have a basic **registerRoute** using **CacheFirst** on a test page to cache 1 image only. With debug mode set to true, the logger seems to repeat the message. What's weird is that closing the tab and re-opening it again **_increases_** this log (closed the tab and reopening 3 times and got 4 “_Using CacheFirst to respond to..._” log messages.

Is this expected behavior? Please see screenshot for network trace and console logs.

![03_sw-debug](https://user-images.githubusercontent.com/3850550/53933357-f63fca00-40d8-11e9-8c73-c82243277efb.png)

**Comment by jeffposnick** [comment]
That doesn't look expected, but at the same time, I also don't expect to see those multiple entries for your `sw-v1.js` service worker file in the Network logs. It makes me think that something else might be amiss.

Can you share a live URL for a deployment that shows this behavior? If not, could you share the full code for your service worker?

**Comment by gctommy** [comment]
@jeffposnick — You can check the live URL here for the behavior:

https://zesty-wheel.glitch.me/

Refresh once the page loads, then close the tab, then open a new tab going to the same page again and you should see the logs increment. Same thing happening in Incognito Window.

**Comment by philipwalton** [comment]
Hmmm, @gctommy I don't see that when I visit your link. This is what I see:

<img width="1680" alt="screen shot 2019-03-07 at 7 11 57 pm" src="https://user-images.githubusercontent.com/326742/54005105-f954ad80-410c-11e9-8b9f-e3710e920b7f.png">

**Comment by gctommy** [comment]
Did you close your tab and load the page again? This is what I see:

![](https://user-images.githubusercontent.com/3850550/54005502-a6263d80-4194-11e9-8f37-67bdf64aaa3f.png)

**Comment by jeffposnick** [comment]
I can confirm what @philipwalton said—I'm not able to reproduce those repeated log entries when I go to your page in Chrome 72.

Do you see the same behavior if you visit in an Incognito window? How about in Safari/Firefox/Edge?

**Comment by philipwalton** [comment]
Ok, with some more testing I was able to reproduce what you're seeing.

I can try to investigate further, but as far as I can tell, I think this is a Chrome (or even DevTools) bug. I don't see this issue in Firefox, and AFAICT multiple requests aren't being made.

**Comment by gctommy** [comment]
@jeffposnick — Yes, I see the same behavior in an Incognito Window for Chrome. No issues in Firefox.

@philipwalton — Thanks for investigating this further.

**Comment by jeffposnick** [comment]
Just revisiting this now—I've updated the reproduction site to the latest Workbox v6.0.2 release, and am no longer able to reproduce the issue: https://glitch.com/edit/#!/ethereal-superficial-drain?path=sw-v1.js%3A33%3A0
