### ISSUE TITLE
ValidationError "importWorkboxFrom" for generateSWSring

### ISSUE THREAD

**Issue by kinetifex** [GoogleChrome/workbox#1951]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*N/A*

**Issue or Feature Request Description**:
* The [docs for generateSWSring][docs] state that `importWorkboxFrom` is an accepted config option, however I and getting a `ValidationError: "importWorkboxFrom" is not a supported parameter.` error.*

It seems like the [generate-sw-string-schema.js] should basically match up to [generate-sw-schema.js] with the expection of `swDest`?

```js
const {generateSWString} = require('workbox-build');

generateSWString({
  importScripts: [],  // why is this required?
  importWorkboxFrom: 'cdn'
}).then((swString) => {
  // Do something with the generated code in swString.
});
```

[docs]:https://developers.google.com/web/tools/workbox/modules/workbox-build#generateswstring_mode
[generate-sw-schema.js]:https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-build/src/entry-points/options/generate-sw-schema.js
[generate-sw-string-schema.js]:https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-build/src/entry-points/options/generate-sw-string-schema.js

**Comment by jeffposnick** [comment]
Apologies for the delay in reply—`generateSWString` is going to be removed in Workbox v5, along with its docs. I'm going to close this as it's effectively obsolete.

(`getManifest()` will still be around for folks who want to use `workbox-build` for creating a precache manifest but don't want to write anything to disk, though it's obviously a somewhat different use case.)
