### ISSUE TITLE
queue.shiftRequest() failing to construct Request

### ISSUE THREAD

**Issue by uselessnpc** [GoogleChrome/workbox#1955]
**Library Affected**:
workbox.backgroundSync.Queue. (Workbox 4.1) 

**Browser & Platform**:
Tested on Chrome 72.0.3626.121 (Windows 10 x64)

**Issue or Feature Request Description**:
I have the following line on my service-worker.js. I can get _console.log()_ messages right before this line, but never after or inside the loop.

`while (entry = await queue.shiftRequest()) {}`

It throws the following error:

> **StorableRequest.mjs:125** Uncaught (in promise) TypeError: Failed to construct 'Request': Cannot construct a Request with a RequestInit whose mode member is set as 'navigate'.
    at o.toRequest (StorableRequest.mjs:125)
    at d.R (Queue.mjs:223)

The oldest entry in the queue is removed from IndexedDB, but it's not being sent. I checked the _Value_ field in the queue and indeed _requestData_ has _mode_ set to "navigate", _credentials_ is set to "include".

I'm not doing anything special when adding failed _POST_ requests to the background sync queue:

```
let request_clone = event.request.clone();
[....]
queue.pushRequest({
            'request': request_clone
});
```

My form is not special either, just a few _input fields_ sending text and one _textarea_, and I'm not trying to post to another domain.

**Comment by philipwalton** [comment]
How are you putting requests in the queue in the first place? Can you show me that code?

I'd argue it doesn't really make sense to put navigation requests in a background sync queue (because you can't actually use them to navigate later), but I do think we could provide a better experience here than having it error. We should at least catch the error and log a warning to the console.

**Comment by uselessnpc** [comment]
Sorry if I didn't explain the issue properly. I'm sending a form, and if it fails, it goes to the background sync queue. This is the full code I'm using put the requests in the queue:

```workbox.routing.registerRoute(
        new RegExp('/suggestion/post' ),
        async ({
                event
            }) => {
                let request_clone = event.request.clone();
                try {
                    return await new workbox.strategies.NetworkOnly().handle({
                        event
                    });
                } catch (error) {
                    queue.pushRequest({
                        'request': request_clone
                    });
                }
            },
            "POST"
    );```

I still need to return something back to the app to let the user know that it will be sent later, but the request is added to the queue for testing purposes. Did I miss something? I'm new to Workbox, it took me quite some time to get so far lol

(I tried to style the comment properly but Github's markdown is not playing nice, sorry)

**Comment by philipwalton** [comment]
Hey @uselessnpc, sorry for the slow response. I believe PR #2015 should fix this for you. We'll release a new version next week that should include this fix, and then you can let us know if you're still having issues.
