### ISSUE TITLE
Enable debug on origins other than localhost

### ISSUE THREAD

**Issue by jay-almaraz** [GoogleChrome/workbox#1971]
I don't want to disable `debug` in development; Actually the **opposite**! 

Our issue is that we use specific origins when we dev, so my origin might be `http://osa-local-portal:3000` (configured to point to localhost through my `/etc/hosts` file). Here Workbox puts itself into prod mode and debug is disabled.

Below is my code, where I am using `importScripts` to load a basic file which enables debugging. But by the time the browser loads the service worker, and `importScripts` is called, `workbox` has not yet been defined for my basic file to use.

My InjectManifest config, where `isEnvProduction` is set to true:
```js
/* webpack.config.js */

  // ...
      new workboxPlugin.InjectManifest({
        swDest: 'service-worker.js',
        swSrc: './src/serviceWorker.js',
        importScripts: [isEnvProduction ? 'prod.js' : 'dev.js']
      }),
  // ...
```

and my `dev.js` file looks like:
```js
// Force development builds
workbox.setConfig({ debug: true });
```

`service-worker.js` loads in the browser with the first line:
```js
importScripts("/dev.js", "/precache-manifest.1d1974fcb7513b5891324f12d1257cbb.js", "https://storage.googleapis.com/workbox-cdn/releases/4.1.0/workbox-sw.js");
// ...
```

But my browser outputs:
```
dev.js:2 Uncaught ReferenceError: workbox is not defined
    at dev.js:2
    at service-worker.js:1
```

**Comment by jay-almaraz** [comment]
Actually this looks to be due to the fact that the service worker is under `Service workers from other domains` when I visit the app through `osa-local-portal:3000`.
The service worker doesn't even begin to install on `osa-local-portal:3000` unless I also have a `localhost` tab open.

Unsure why the service worker is so tied to `localhost`? I don't have that literal anywhere in my configurations, webpack or otherwise

**Comment by jay-almaraz** [comment]
This is an issue with the workbox service worker not being served to any domain other than `localhost` but I'll research that and open a new issue if I find anything 🤷‍♀️

**Comment by ernsheong** [comment]
Any updates on how to achieve this?
