### ISSUE TITLE
workbox-webpack-plugin hash bug

### ISSUE THREAD

**Issue by el** [GoogleChrome/workbox#1972]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
`getManifestEntriesFromCompilation` returns an unsorted list of entries. This causes unnecessary change on the hash used by `precacheManifest` file.

**Comment by jeffposnick** [comment]
Hello @el!

Thanks for reporting the issue (and for filing the associated PR).

I _think_, however, that we already address this issue via https://github.com/GoogleChrome/workbox/blob/d85aea01c867f4397e4d2d3de633490024ea1104/packages/workbox-webpack-plugin/src/lib/stringify-manifest.js#L29-L34

Are you seeing a situation in which the list _doesn't_ end up being written out sorted? If you have a reproduction case, I'd love to take a look.

**Comment by el** [comment]
Yes, I can reproduce the issue locally. The reason that fix does not work is sort expects a number as in `-1,` `0` or `1` but comparison will return `0` or `1`. So the fix can be like this:

```
  const sortedEntries = manifestEntries.sort((a, b) => a.url === b.url ? 0 : (a.url > b.url ? 1 : -1));
```

You should be able to reproduce this issue.

**Comment by el** [comment]
Here is a code snippet to reproduce the issue
```
const arr1 = ["a","b","c","d","e"];
const arr2 = ["c","a","e","b","d"];

console.log("arr1 => ", arr1.sort((a,b) => a > b))
console.log("arr2 => ", arr2.sort((a,b) => a > b))
```

**Comment by jeffposnick** [comment]
Oops! Thanks for catching this bug in the logic 👍
