### ISSUE TITLE
add ambient badge to the address bar

### ISSUE THREAD

**Issue by 2803media** [GoogleChrome/workbox#1974]
I just read that in chrome 73 they introduce an ambient badge to the address bar but I can't find a way to make it show. 

https://developers.google.com/web/updates/2019/03/nic73

Do I do something special for workbox 4.1.1 to make it work?

Thanks

**Comment by jeffposnick** [comment]
In general, the criteria for whether a web app will trigger that badging should be similar to what's outlined at https://developers.google.com/web/fundamentals/app-install-banners/

Workbox can definitely help with the service worker part of that criteria.

There are other pieces that are outside the scope of Workbox, like creating a web app manifest.
