### ISSUE TITLE
error - DOMException

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1976]
I did not modify anything and started this image error

![Captura de Tela_selecionar área_20190320150454](https://user-images.githubusercontent.com/11314585/54708195-a1ad3d80-4b21-11e9-9fc6-69dda998eeaa.png)

**Comment by jeffposnick** [comment]
Apologies for the delayed response.

If you're still able to reproduce the issue, can you let us know what stack trace is logged when you click on the little `>` arrow to expand it next to the original log message?
