### ISSUE TITLE
reload new cache version

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1977]
how to identify if it has a new version available cache and do reload after identify?

today in my html code, this is just so:
![Captura de Tela_selecionar área_20190320151514](https://user-images.githubusercontent.com/11314585/54708824-f8ffdd80-4b22-11e9-809f-b4a05475dadd.png)

in angular applications I do this way, I want this same effect

![Captura de Tela_selecionar área_20190320151551](https://user-images.githubusercontent.com/11314585/54708887-1f257d80-4b23-11e9-8999-582f04c89d1b.png)

**Comment by jeffposnick** [comment]
Please see https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users
