### ISSUE TITLE
Question: call onSync pragmatically

### ISSUE THREAD

**Issue by NoamPaz** [GoogleChrome/workbox#1979]
**Library Affected**:
workbox.backgroundSync.Queue

**Browser & Platform**:
all browsers

I need to call the queue onSync function pragmatically in some cases and not only on sync event which only chrome supports backgroundSync at the moment.
The only public function the queue exposes is the replayRequests which doesn't allow me to cancel/modify requests.
Is there any way to call onSync  instead of replayRequests?
I do have a hack for this:
`
let onSync;
Object.keys(statesAndEventsQueue).forEach((key) => {
	if (typeof statesAndEventsQueue[key] === 'function' && statesAndEventsQueue[key].name === 'onSync') {
		onSync = statesAndEventsQueue[key];
	}
});
onSync();
`
statesAndEventsQueue is a queue instance.
But I don't want to rely on this hack.
Any suggestion? do I miss something?

Thanks

**Comment by philipwalton** [comment]
The `onSync` function is user-specified. You [pass it to the constructor](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.backgroundSync.Queue#Queue) when creating the queue instance, so you should be able to call it yourself manually. Have you tried that?

**Comment by NoamPaz** [comment]
That force me to expose this function as a global or pass it as an argument to other scopes/scripts alongside the queue instance, instead only expose the queue instance itself and call to its onSync.
Anyway, this work as well if I pass it.

**Comment by philipwalton** [comment]
@NoamPaz can I see the code you're using for this? It's not clear to me why you'd need to expose it as a global function.

BTW, I'm not saying we can't add a method to call `onSync` programmatically, I'm just trying to understand the use case fully before we extend the API surface.
