### ISSUE TITLE
async fetch event runs in parallell

### ISSUE THREAD

**Issue by mech01nc01** [GoogleChrome/workbox#1993]
**Library Affected**:
"workbox-webpack-plugin": "^4.1.1",

**Browser & Platform**:
Chrome Windows 73.0.3683.86

**Issue or Feature Request Description**:
Hello,
i'm using workbox Routing and i have also an Event listener for fetch
this eventListener CAN respond, if not, workbox Routing should do ist Job.
this is working so far, but now i would like to do a check bevore i can decide what todo, and this is async, because i have to read the Cache

lookin at [this advanced receipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#make-requests) i thought i could just make the fetch-eventListener async and use await, but as soon the listener awaits, the next event-listener (workbox) will run and responds ...

my eventListener looks like this:

```
self.addEventListener("fetch", async (event) =>
{

	var requestUrl = new URL(event.request.url);
	const scope = self.registration.scope;

	// redirect index.html to service-worker-enabled page // https://github.com/AnthumChris/fetch-progress-indicators/blob/master/sw-basic/sw-simple.js
	if (requestUrl.hostname == "pwa.xy.de" && (event.request.url === scope || event.request.url === scope + 'index.html' ||
			(!requestUrl.pathname.match(/\..{2,4}$/) && !requestUrl.pathname.match(/^\/sockjs-node/) &&
				!requestUrl.pathname.match(/^\/webpack-dev-server/))))
	{
		if (await self.getCacheAktuellStatus())
		{
			const newUrl = scope + 'swenabled.html';
			console.log('respondWith', newUrl);
			event.respondWith(fetch(newUrl));
		}
		console.debug("switching to default route handler");
	}
}
```

as soon as the Code reaches the await, the next eventListener will run (seeing a workbox router log in the console)
and of Course i get
`Uncaught (in promise) DOMException: Failed to execute 'respondWith' on 'FetchEvent': The event has already been responded to.`

in your receipe it looked as i could do it this way, but it doesn't .. am i'm doing something wrong?

**Comment by jeffposnick** [comment]
It's not possible to use asynchronous logic to determine whether or not you should respond to an event. (See the **Multiple fetch Event Handlers** section of https://stackoverflow.com/a/45285119/385997 for more info.)

Your best bet would be to create a `fetch` handler that always called `respondWith()`, but inside of that logic, used either your own custom code or the [`handle` methods](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.strategies.StaleWhileRevalidate#handle) available on all the built-in strategies to generate the response.
