### ISSUE TITLE
workbox-broadcast-cache-update documentation outdated?

### ISSUE THREAD

**Issue by goyavo** [GoogleChrome/workbox#1994]
**Library Affected**:
documentation / workbox-broadcast-cache-update
using SDK /4.1.1/workbox-sw.js

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The docs @ https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-cache-update use the following syntax:
new workbox.broadcastUpdate.Plugin('api-updates')
That does not seem to work. Using the following does:
new workbox.broadcastUpdate.Plugin({channelName: 'api-updates'})

**Comment by jeffposnick** [comment]
Thanks—I'll file a PR to fix this in the repo that hosts our documentation.
