### ISSUE TITLE
Provide getter for accessing the cache name prefix

### ISSUE THREAD

**Issue by westonruter** [GoogleChrome/workbox#1998]
**Library Affected**:
*workbox-core*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:

There is a `workbox.core.setCacheNameDetails()` to supply a cache name `prefix`. However, this prefix is not readable after being set. I expected it would be available under `workbox.core.cacheNames.prefix` but it isn't. Because of this, we currently have to store the prefix in another constant to then re-use later. See https://github.com/xwp/pwa-wp/pull/147.

The use case is https://github.com/xwp/pwa-wp/issues/146 where all cache names registered for a WordPress install should get a common prefix to prevent collision with cache names for other WordPress installs that are running on the same origin (in other subdirectories).

**Comment by jeffposnick** [comment]
Sure—I think we can get that exposed pretty easily.
