### ISSUE TITLE
Documentation error in Expiration plugin

### ISSUE THREAD

**Issue by tarjei** [GoogleChrome/workbox#2002]
**Library Affected**:
workbox-sw
**Browser & Platform**:
"all browsers".*

**Issue or Feature Request Description**:
In the abstract here you state:
https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.expiration.Plugin

`When using maxEntries, the last request to be used will be the request that is removed from the Cache.`

In the options area you say:

`The maximum number of entries to cache. Entries used the least will be removed as the maximum is reached.`

I **expect** the last sentence to be true :)

**Comment by philipwalton** [comment]
Yes, this does seem contradictory, but I think it's your first quote that's actually correct.

The expiration plugin will update the timestamp of a URL any time it's requested, but it doesn't keep track of the number of times it's requested: https://github.com/GoogleChrome/workbox/blob/v4.2.0/packages/workbox-expiration/Plugin.mjs#L137-L139

The text should probably read something like:

> Entries least-recently requested will be removed first...

**Comment by tarjei** [comment]
Good point, I updated the PR.

**Comment by jeffposnick** [comment]
This was fixed in https://github.com/GoogleChrome/workbox/pull/2003
