### ISSUE TITLE
Improve visibility of workbox-window Promises in docs

### ISSUE THREAD

**Issue by humphd** [GoogleChrome/workbox#2009]
The new `workbox-window` API supports similarly named events and attributes, which return promises.  One such example is `controlling`:

- [`controlling` Promise](https://t.co/kqhKhwc3C8)
- [`controlling` event](https://t.co/ojUOcnpRsj)

However, the main entry point for most users wishing to learn about `workbox-window` is https://developers.google.com/web/tools/workbox/modules/workbox-window, which discusses the events, but never mentions the Promises.

In a recent [twitter conversation](https://twitter.com/philwalton/status/1113918308531621888) I needed help trying to solve a problem that required use of both the events and Promises, and it was only through direct help from @philipwalton that I was able to over come my lack of knowledge.

I think the docs could be more clear on this point, and provide better info on these other aspects of the API.  The fact that they are named identically to the events makes accidental discovery much harder, since you *think* you're seeing docs for things you've already learned in another context.

Filing this at the request of @philipwalton.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
