### ISSUE TITLE
Is there a way to override publicPath?

### ISSUE THREAD

**Issue by tselishev-semen** [GoogleChrome/workbox#2012]
**Library Affected**:
No libraries affected

**Browser & Platform**:
All

**Issue or Feature Request Description**:
It's a feature request.
Currently, when I'm using GenerateSW from workbox-webpack-plugin@4.2.0 

`const {GenerateSW} = require('workbox-webpack-plugin');`

it generates  precache-manifest.js with the list of assets created during the webpack build phase. It works perfect, but it uses **publicPath** property from configuration in webpack 

`  
output: {
    publicPath: publicPaths.staticServer
  },`

and there is no way to override it. 
For example, for our case we need this, because we use different static servers for different types of assets.

Do you have plans to support this feature. Or can I just  implement this feature and create a pull request for it?

**Comment by jeffposnick** [comment]
I think that the sensible default is to pretend `publicPath` from the webpack config, and that's going to stay as-is.

In Workbox v5, you'll be able to use the `modifyUrlPrefix` option to modify entry prefixes directly. Or, if you need more control, there will also be support for a `manifestTransforms` callback that you can register and make any arbitrary changes to manifest entries that you'd like.

**Comment by jeffposnick** [comment]
This should be addressed by the current Workbox v5.0.0 alpha.

**Comment by tselishev-semen** [comment]
@jeffposnick  thanks for your response, you are really doing a cool instrument, I only asked about the ability to provide the easy and declarative way to override the default **publicPath"", some plugins and loaders support that, see for example https://github.com/webpack-contrib/file-loader#publicpath, https://github.com/arthurbergmz/webpack-pwa-manifest).

**Comment by jeffposnick** [comment]
The `modifyURLPrefix ` option in v5 should allow you to accomplish that and any other prefix manipulation you want, so I don't think a separate option that only worked with the `publicPath` makes sense.
