### ISSUE TITLE
workbox-build generates incorrect channelName options

### ISSUE THREAD

**Issue by gera2ld** [GoogleChrome/workbox#2016]
workbox-build@4.1.1 generates service-worker.js with code like this:

```js
new workbox.broadcastUpdate.Plugin('api-updates')
```

which does not work. Using the following does:

```js
new workbox.broadcastUpdate.Plugin({ channelName: 'api-updates' })
```

**Library Affected**:
workbox-build@4.1.1, workbox-webpack-plugin@4.1.1

**Comment by jeffposnick** [comment]
Thanks for reporting this!
