### ISSUE TITLE
 Why is this information always printed? “No route found for:”

### ISSUE THREAD

**Issue by anderson2825** [GoogleChrome/workbox#2029]
![menu saveimg savepath20190412111245](https://user-images.githubusercontent.com/15023822/56017436-d16ef000-5d31-11e9-8193-6db6f7f5cf0a.jpg)

 
**Library Affected:**
workbox-sw 4.2.0

**Browser & Platform:**
Google Chrome 73.0.3683.103 

**Issue or Feature Request Description:**
 So much information, how to deal with not to show！
 No route found for: https://mc.yandex.ru/webvisor/45321081? logger.mjs:44 workbox

**Comment by jeffposnick** [comment]
Those log messages are `debug`-level messages logged here:

https://github.com/GoogleChrome/workbox/blob/76ba3175c5fea61a75661e1c5d2ed752a45cefdf/packages/workbox-routing/Router.mjs#L183

Are you seeing these messages logged on a website that you control? If so, you can configure Workbox not to log them via https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug#debugging_workbox

If you're seeing these messages logged on a website that you don't control, then there's not much you can do other than ignore them.

**Comment by anderson2825** [comment]
Okay thank you! I will test again!
