### ISSUE TITLE
firefox pwa issue

### ISSUE THREAD

**Issue by marmikdesai** [GoogleChrome/workbox#2032]
**Browser & Platform**:
*E.g. Firefox for Android

**Issue**:
Hi,

While implementing PWA on our mobile site, We noticed that GA tracking pixels and other third party tracking JS opening automatically in new tabs in FIREFOX. Attached a GIF of the same. Please help us resolve this issue.

![pepperfry pwa](https://user-images.githubusercontent.com/4994566/56119876-97e4f180-5f8a-11e9-86ca-7d7c62fcef2e.gif)

**Comment by jeffposnick** [comment]
Hello @marmikdesai—Apologies that you're running into this issue, but from your description and GIF, it's not clear that it's a problem related to the Workbox library.

If you're having a general issue with a web app's behavior in Firefox, your best bet would be to follow up on the [Mozilla issue tracker](https://bugzilla.mozilla.org/).

I'm going to close this issue for now, but if I'm missing something about why this is actually an issue directly related to Workbox, please let us know and we can revisit.

**Comment by Romanchuk** [comment]
@marmikdesai Struggling with same issue... Did you find a solution?

**Comment by NekR** [comment]
See this please: https://github.com/PWA-POLICE/pwa-bugs#problem-cross-origin-redirects-for-img--tag-cause-firefox-to-open-custom-tab-browser
As described there, it's fixed in Firefox 67.

**Comment by Romanchuk** [comment]
@NekR wow! You saved my day!
