### ISSUE TITLE
Service worker installation failed

### ISSUE THREAD

**Issue by farrukhsheikh248** [GoogleChrome/workbox#2033]
![image](https://user-images.githubusercontent.com/16284354/56186794-0f258e80-603a-11e9-95f2-2440970d87b5.png)

**Comment by philipwalton** [comment]
Hi @farrukhsheikh248, this is the expected behavior when a request for a precache asset fails with a 404. In this case the service worker installation should also fail.

**Comment by sourybunny** [comment]
Hey @jeffposnick  
I've migrated from v3 to v4, using the workbox-window(CDN) and workbox-webpack-plugin,
I have the same issue as above, the service worker installation is failing for some reason. Could you please help me know how to fix this.
![image](https://user-images.githubusercontent.com/38237352/62183725-eb801d00-b378-11e9-8bbf-a6d254115ffe.png)

**Comment by JayeshPunjabi728** [comment]
Any Update ?
