### ISSUE TITLE
The mini-infobar visible after installing pwa

### ISSUE THREAD

**Issue by marmikdesai** [GoogleChrome/workbox#2034]
**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

Question:- I have recently added pwa into my site. I have installed app using min-infobar. The problem is this mini-infobar visible again while app is still installed. Is this pwa behavior?

**Comment by jeffposnick** [comment]
Hello @marmikdesai—Unfortunately, the Workbox issue tracker isn't a great place to ask questions about browser UI functionality.

I *think* you're describing an issue with Chrome, so the best place to follow up would be to provide reproduction details at https://crbug.com/new
