### ISSUE TITLE
Is workbox.routing.setDefaultHandler ignoring registered routes?

### ISSUE THREAD

**Issue by bitterdev** [GoogleChrome/workbox#2036]
Hello,

i'm using workbox version 4.3.

I have a small piece of code:

```js
workbox.routing.registerRoute(
  /(\/|)(index.php\/|)(login|register|dashboard|password_login|connection_test)(.*)/gm,
  new workbox.strategies.NetworkOnly()
);

workbox.routing.setDefaultHandler(
  new workbox.strategies.StaleWhileRevalidate()
);
```

When i set default handler all other defined routes will be ignored. Is that a expected behavior? If yes is there a workaround to exclude some pathes/urls from caching?

**Comment by philipwalton** [comment]
@bitterdev to clarify, are you saying the network only route you're defining first is not being used? And only the default route (defined second) is being used?

**Comment by bitterdev** [comment]
@philipwalton Sorry my mistake! I have enabled the debug mode and find out that there was another reason for my problem. You can close this ticket. Thank you.
