### ISSUE TITLE
Failed to update a ServiceWorker

### ISSUE THREAD

**Issue by plusbpm** [GoogleChrome/workbox#2037]
**Library Affected**:
*workbox*
TypeError: Failed to update a ServiceWorker: An unknown error occurred when fetching the script

**Browser & Platform**:
Chrome Mobile 73.0.3683 on Android9
Samsung Internet 9.2.0 on Android 8.1

**Issue or Feature Request Description**:
*Is it possible to ignore network errors on serviceworker updates?*

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by philipwalton** [comment]
Sorry, I have to close this as there's not enough information to take any action. There are lots of reasons an error might occur when fetching the script (network errors, scripts errors, etc). If you can provide more information or link to a page showing the issue, then we can try to help.
