### ISSUE TITLE
Adblocker issue with Workbox Google Analytics Module

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#2038]
I'm currently was using workbox version 4.1.0 (about to update to 4.3.0)

I think my adblocker is blocking the loading for Google Analytics, see screenshot:

![adbloocker](https://user-images.githubusercontent.com/17784082/56507926-cf1f4980-651a-11e9-8edc-14a01adeb6e1.png)

Would it be possible for the Google Team to re-code Workbox so adblockers don't block GA in the Service Worker. It would be nice to monitor offline traffic and global stats say 30% of all internet traffic now use adblockers.

**Comment by philipwalton** [comment]
Sorry, there's not really anything we can do about this. If users are using ad blockers that block Google Analytics, we want to respect their choices.

If you don't feel that ad blockers should be blocking analytics by default, then I'd suggest reaching out to the ad blocker company and sending them that feedback.

**Comment by ayumihamsaki** [comment]
@philipwalton Totally understand, but would it be a good idea for Workbox to handle the error a bit better and try to not load the ga module if there is a no-response to the fetch request.
