### ISSUE TITLE
Background Sync replay request

### ISSUE THREAD

**Issue by asiermusa** [GoogleChrome/workbox#2041]
Hi,

I am trying to make a background-sync request with WorkBox, in a very simple example application with Vue. I revised my codes for a long time but I did not find the solution.

The service worker is well registered and when I make the ajax request, background-sync works properly.

This is my code in the sw.js:

```
const queue = new workbox.backgroundSync.Queue('asierrrna');
workbox.routing.registerRoute(
  RegExp('^MY_URL'),
  workbox.strategies.networkOnly({
    plugins: [{
      fetchDidFail: async ({request}) => {
        await queue.addRequest(request);
      },
    }],
  }),
  'GET'
);
```

Background-sync is registered in indexedDB tab:

<img width="1280" alt="Captura de pantalla 2019-04-24 a las 11 25 00" src="https://user-images.githubusercontent.com/32843723/56648439-a1a1df80-6683-11e9-8284-6721a9d7fec5.png">
.

Finally the network tab. There we see that the API call is well, because when the network returns it makes the call, but nothing else happens in the app, and the old data is not replaced by the new one :/

<img width="1276" alt="Captura de pantalla 2019-04-24 a las 11 25 50" src="https://user-images.githubusercontent.com/32843723/56648621-f5acc400-6683-11e9-9fcf-35bebc464e60.png">

Thanks :)

**Comment by philipwalton** [comment]
The sync event isn't necessarily going to fire right away after network is restored. The browser is free to fire it whenever it thinks is best. What do you see if you trigger a sync event from DevTools?

<img width="1391" alt="Screen Shot 2019-04-25 at 6 42 13 PM" src="https://user-images.githubusercontent.com/326742/56778207-06dff880-678a-11e9-9563-6f4c93bac0ed.png">

You can read more about how to test and debug background sync here: https://developers.google.com/web/tools/workbox/modules/workbox-background-sync#testing_workbox_background_sync

**Comment by asiermusa** [comment]
Hi @philipwalton, 

The sync event works properly. As you can see in the picture above, when ajax petition fail and internet connection is restored, the sync event is well triggered and in the network tab I can see the API response. 

My problem is related with how I can replace the old query with the new one in my app. I was looking to do with callbacks in the Queue like that (it doesn't work for me with the new onSync callback):

```
queueDidReplay: async (storableRequestArray) => {
     let message = {
          'data' : storableRequestArray
     };
     let clients = await self.clients.matchAll();
     for (const client of clients) {
         client.postMessage(message)
     }
}
```

Then in my SPA app I listen for a "message", and I use my app logic to restore the failed request.

```
navigator.serviceWorker.addEventListener('message', (e) => {
  const message = e.data
  doSomething() //my app logic here
});
```

Is this the right way?

Thanks

**Comment by d33pak-singh** [comment]
Hi @asiermusa 

I have come across same issue in my vue app. Once the connection is restored, the sync event gets triggered and I can check that in my n/w tab, but the response which I get from the API response that is not getting consumed! 

Also your second response on this thread has this queueDidReplay. What's the usage for this? I haven't added the EventListener for message as you have added in the 2nd message of your thread.
Help me please.

**Comment by asiermusa** [comment]
Hi @d33pak-singh!

I used `queueDidReplay` to restore a new query, via `postMessage` event.

In your `Service Worker`:
```
const vbSyncPost = new workbox.backgroundSync.Plugin('request_name', {
    maxRetentionTime: 24 * 60, // Retry for max of 24 Hours
    callbacks: {
        queueDidReplay: async(storableRequestArray) => {
            let data = storableRequestArray[0].request.referrer;
            let message = {
                'status': 'exec',
                'id': "postQueueAPI",
                'data' : data
            };
            // emit to the client
            let clients = await self.clients.matchAll();
            for (const client of clients) {
                client.postMessage(message);
            }
        }
    }
});
```

In your `Vue app` component you must add something like this:

```
mounted () {
    window.addEventListener('message', this.onMessage, false)
},
methods: {
   onMessage (e) {
      //here use your logic to restore the request...
      console.log('on message event triggered', e)
   },
```

I hope it will help you!

**Comment by subashdbc** [comment]
@asiermusa 
I see that we need to register background sync like this,
```
const bgSyncPlugin = new workbox.backgroundSync.Plugin('myQueueName', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

workbox.routing.registerRoute(
  /\/api\/.*\/*.json/,
  new workbox.strategies.NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);
```

but here how can we add form data for POST request and as well as adding headers for a sync event
Can you anyone help?

**Comment by asiermusa** [comment]
I am not so sure what do you want to do. Can you explain it by some example, please?

**Comment by subashdbc** [comment]
@asiermusa I was not sure about how Background Sync work on workbox. 
After doing some research and experiments I was able to catch how things were working. 
Sorry for that comment
