### ISSUE TITLE
BackgroundSync - suggestion of improvement

### ISSUE THREAD

**Issue by bligny** [GoogleChrome/workbox#2042]
Following my recent request to be able to know `Queue` lengths, a new `getAll()` method has just been added in version 4.3.0 (cfr #2018).
Very nice...but the fact is that the created `Queue` object is currently fully private and not exposed at all to the outside world:

```js
class Plugin {
  
  constructor(...queueArgs) {
    this._queue = new Queue(...queueArgs);
  }
```

In particular, I would like to be able to also access any (public) queue method outside the Plugin (or outside possible queue callbacks/hooks).

Therefore, I'm suggesting the following changes.

1) Either expose the `_queue` using a new `getQueue()` method on `Plugin` object

2) Or enrich the Plugin constructor in order to accept
- [as now] the same arguments as the Queue constructor
- [new]  **OR** a pre-populated queue object

That is to say something like (sorry, I'm not a js guru):

```js
class Plugin {
  
  constructor(...queueArgs) {
    this( new Queue(...queueArgs) );
  }

  constructor(myqueue: Queue) {
    this._queue = myqueue;
  }
```

Which would make it possible to have this kind of WB initialisation:

```js
const myQueue =  new workbox.backgroundSync.Queue('my-queue', {
  maxRetentionTime: Infinity
});

const myPlugin = new workbox.backgroundSync.Plugin(myQueue);

workbox.routing.registerRoute(
  new RegExp(...),
  new workbox.strategies.NetworkOnly({
    fetchOptions: {},
    plugins: [myPlugin]
  }),
  'PUT'
);
```
And then later on, be able to invoke queue methods, e.g.  : 
```js
// With option 1)
myPlugin.getQueue().getAll().then( (data) => {       
     console.log('The queue still contains', data.length, 'items !');
});  
// With option 2)
myQueue.getAll().then( (data) => {       
     console.log('The queue still contains', data.length, 'items !');
});  
```

**Comment by bligny** [comment]
I've suggested another feature into a separate issue: #2044

**Comment by l3d00m** [comment]
Hi, is there a status update on this feature request?

Without it, it's not possible to get a list of pending requests. For that it's currently necessary to implement it with `Queue` directly, which is a lot more work.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
