### ISSUE TITLE
Upgrade joi due to deprecation warning

### ISSUE THREAD

**Issue by Pajn** [GoogleChrome/workbox#2043]
**Library Affected**:
*workbox-webpack-plugin*, *workbox-build*, probably others.

**Browser & Platform**:
n/a

**Issue or Feature Request Description**:
When I install packages today I get:
```
warning workbox-webpack-plugin > workbox-build > joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning workbox-webpack-plugin > workbox-build > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning workbox-webpack-plugin > workbox-build > joi > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning workbox-webpack-plugin > workbox-build > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by philipwalton** [comment]
Thanks, @jeffposnick when you're back can you take a look and make sure `workbox-build` is compatible with the new version?

**Comment by jeffposnick** [comment]
Unfortunately, I can't find any [release notes](https://github.com/hapijs/joi/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22release+notes%22+) for v15, so I'm going to assume it was mainly a breaking semver change due to the renamed `npm` package.
