### ISSUE TITLE
workbox.precaching.suppressWarnings is not a function

### ISSUE THREAD

**Issue by Mostafasaffari** [GoogleChrome/workbox#2048]
Hi 
I've migrated from v 3.6.0 to 4.3.0 and this error rise in my service-worker.js
"workbox.precaching.suppressWarnings is not a function".

what function should I use instead of "suppressWarnings"  in version 4.3.0?

**Comment by jeffposnick** [comment]
Sorry about that—you can just remove the call entirely. The exact warning messages that v3.6.0 would print out weren't carried over to v4.3.0, so it's no longer needed.
