### ISSUE TITLE
Unexpected token < error after redeploy (InjectManifest Mode)

### ISSUE THREAD

**Issue by sourybunny** [GoogleChrome/workbox#2053]
Library Affected:
"@vue/cli-plugin-pwa": "^3.6.0",

Browser & Platform:
Google Chrome for Android

Issue or Feature Request Description:
I bundle my website/PWA, where I use a couple of Web Components, using the workbox-webpack-plugin.

Everything works smooth and well till I redeploy the project (hosted on Netlify).
On my phone/desktop, if I clean my cache and access the website/pwa, all good, worker works correctly.
Later on, once I release a new version, where I did several changes, and deploy it to the hosting and if I try to access the website/pwa , then I'll face the following error:
Uncaught SyntaxError: Unexpected token <

On checking network requests, I see that a request is made to an older app.[hash].js file which belonged to previous deploy. It is unable to find this file as it is getting deleted when new sw is activated. 

`
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
module.exports = {
  configureWebpack: {
    plugins: [
      new VuetifyLoaderPlugin()
    ]
  },
  devServer: {
    disableHostCheck: true,
  },
  lintOnSave: false,
  pwa: {
    workboxPluginMode: 'InjectManifest',
    workboxOptions: {
      swSrc: 'src/service-worker.js'
    }
  }
}
`

_**A similar issue is raised #1528 , #1783**_ 

Please help.

**Comment by sourybunny** [comment]
First deploy-

![previous deploy](https://user-images.githubusercontent.com/38237352/57350738-e138f300-717c-11e9-9dad-4e6f2b8583c5.png)

latest deploy- after service worker activation (on reloading the page)

![current deploy](https://user-images.githubusercontent.com/38237352/57350751-e9912e00-717c-11e9-8f2b-7926f14ada4c.png)

Why is it requesting older files  while the hash for app.[hash].js has changed after latest deploy. This is breaking the app.

![network request](https://user-images.githubusercontent.com/38237352/57350782-075e9300-717d-11e9-8e75-8dd1bce4b5e8.png)

**Comment by jeffposnick** [comment]
It sounds like you're running into described in [this section](https://developers.google.com/web/tools/workbox/modules/workbox-core#skip_waiting_and_clients_claim) of the docs:

> Note: If your web app lazy-loads resources that are uniquely versioned with, e.g., hashes in their URLs, it's recommended that you avoid using skip waiting. Enabling it could [lead to failures](https://stackoverflow.com/questions/51715127/what-are-the-downsides-to-using-skipwaiting-and-clientsclaim-with-workbox) when lazily-loading URLs that were previously precached and were purged during an updated service worker's activation.

Can you make sure that you're not unconditionally calling `skipWaiting()`? The best way to handle this is to follow a [recipe like this](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users), and call `skipWaiting()` when a user opt-ins, immediately followed by a page refresh once the new service worker activates.

**Comment by sourybunny** [comment]
Hey @jeffposnick , thanks for the resources, I've gone through them and looks like "refreshing" is a complicated thing to do.

```import { Events } from './events'
import { register } from 'register-service-worker'

if (process.env.NODE_ENV === 'production') {
  register(`${process.env.BASE_URL}service-worker.js`, {
    ready () {
      console.log(
        'App is being served from cache by a service worker.\n' +
        'For more details, visit https://goo.gl/AFskqB'
      )
    },
    registered () {
      console.log('Service worker has been registered.')
    },
    cached () {
      console.log('Content has been cached for offline use.')
    },
    updatefound () {
      console.log('New content is downloading.[update found]')
    },
    updated (registration) {
      console.log('New content is available; please refresh.');
      let worker = registration.waiting
      Events.$emit("showStatus", {text: "New Content is available. Please Reload the page.",timeout: 0})
      
      worker.postMessage({action: 'skipWaiting'})
    },
    offline () {
      console.log('No internet connection found. App is running in offline mode.')
      Events.$emit("showStatus", {text: "You are viewing content offline."})
    },
    error (error) {
      console.error('Error during service worker registration:', error)
    }
  })
  }
```

We are using vue-cli3-pwa-plugin and this is the boilerplate kind of thing for **registration** code.
As you can see, I'm sending the postMessage after the update( checking if registration.waiting)  which then does skipWaiting 
```
self.addEventListener("message", (e)=>{
  if (e.data.action=='skipWaiting') {
    self.skipWaiting()
  }
})
```
This is an approach that is suggested by workbox too. But it just breaks my app when I reload the page after a new service worker is activated, since it tries to find an old cached html file that  is not updated well in sw activation phase. The app breaks because it still uses an old html file from the cache that  has links to old js files that can't be found anymore.
What am I missing here? Is there a way to use workbox advanced recipe for refreshing using this vue-pwa boilerplate?

In another case, I just deleted the code for skipWaiting and tried to activate new sw after closing all the tabs and opening in new tab. While activation has been successful, after a page reload it's still fetching the old html file and js files that do not exist anymore.

Can you explain me the order of these events for a bug free pwa while using workbox webpack plugin:

1.  A new code change happens, we redeploy.
     1.**Registration and Installation happen first.**
     2. Cache cleanup and new precache manifest are generated during activation which should remove 
         my old html and js and replace with newer ones.
     3.  If we call skipWaiting it activates immediately  so chances are that it breaks the existing clients 
         using old version
     4. If I don't deal with skipWaiting, then I need to close all tabs and reopen in new tab to see it 
         activated.
     5. We refresh the page to see the new content.

This is what I understood about the life cycle, correct me if I'm wrong I would love to understand it better. But I would be glad if you could help me know why my app is using old html file after a page refresh while sw has been activated correctly.

Thanks

**Comment by philipwalton** [comment]
It's possible that your service worker is still waiting to activate after the update is found and even after you refresh. Sometimes refreshing the page won't skip the waiting phase if there are other tasks pending or other clients still open.

You could try using [`workbox-window`](https://developers.google.com/web/tools/workbox/modules/workbox-window) to register your service worker, as that library adds some nice logging beyond what `register-service-worker` has. It'll log a warning to the console if the installing service worker gets stuck in the waiting phase.

**Comment by sourybunny** [comment]
Hey @philipwalton && @jeffposnick   I have tested it thoroughly and I don't have any issues with service worker activation, It works very fine, I send a refresh prompt while new sw is in waiting phase and on accepting it, it skips waiting and gets activated, I even tested it by closing all tabs and reopening to get it activated and I can see all that happening correctly in dev tools. 

**There is no issue I see with how my service worker is activating, it works great.** but the problem could have been during the cache cleanup phase, something is wrong with it.

Also I see that there is precache-manifest-temp along with pecache-manifest cache in cache API which could be messing up things while I'm still unsure about it. 
I've documented the whole flow from first deploy onwards by un-registering existing sw's and cleaning up all caches.

1. First fresh deploy:

![first deploy](https://user-images.githubusercontent.com/38237352/57831264-48385680-77d2-11e9-9cbe-4200f07d68d8.jpg)

2. First deploy precache-temp:

![deploy-1-emptytemp](https://user-images.githubusercontent.com/38237352/57831275-538b8200-77d2-11e9-86b0-ec3523906d4d.jpg)

3. First deploy precache:

![app 9d909086 js-cached](https://user-images.githubusercontent.com/38237352/57831310-6900ac00-77d2-11e9-8cd2-8310a6f9fdc8.jpg)

4. I did some code changes to my app and redeloyed now

![redeploy-installing](https://user-images.githubusercontent.com/38237352/57831358-87ff3e00-77d2-11e9-9879-dbb85e01782d.jpg)

5. Service worker in waiting state

![waitingsw](https://user-images.githubusercontent.com/38237352/57831429-ba10a000-77d2-11e9-94c5-7e959a19d4f3.jpg)

6. precache-temp while still waiting:

![waiting-temp](https://user-images.githubusercontent.com/38237352/57831460-d14f8d80-77d2-11e9-8eaf-9a7553dc6c13.jpg)

7. precache while still waiting:

![redeploy-precache-waiting](https://user-images.githubusercontent.com/38237352/57831497-ec220200-77d2-11e9-8e83-122aa0802a45.jpg)

8. Right after I click Refresh button which does skipWaiting and activates new sw.

![right-after-skipwaiting](https://user-images.githubusercontent.com/38237352/57831533-065be000-77d3-11e9-8fe9-a9f00249e8d8.jpg)

9. I do a window.location.reload() after clicking refresh.

![breaks-after-reload](https://user-images.githubusercontent.com/38237352/57831592-2d1a1680-77d3-11e9-975c-2209c2991608.jpg)

10. The app breaks trying to fetch old app file which already got deleted. But I see my new app.hash.js file cached in precache and precahe-temp empty again now. My index.html still points to old app.hash.js file. Why is this happening?

![app 7f29243e js-cached](https://user-images.githubusercontent.com/38237352/57831754-9e59c980-77d3-11e9-925a-3dc392ff41ad.jpg)


 **If I add code to delete caches in registration phase like this:** 
```   
 registered (registration) {
      console.log('Service worker has been registered.')
      caches.keys().then(cacheNames => {
        cacheNames.forEach(cacheName => {
          caches.delete(cacheName);
        });
      });
      registration.update();
    },
```
 **only then does it fetch my new html and app.js files otherwise if it's normal like this**
```
registered (registration) {
      console.log('Service worker has been registered.')
      registration.update();
    },
```
 **it always tries to fetch old files.** But I don't want to delete caches everytime during registration, this just means my caching is useless. Our app is in production already and redeploying has become a nightmare for us. Deleting the caches in registration is the only hack I found so far to not break the app while redeploying. May be you can help me understand why it works fine after I delete previous caches, I have no idea about it. Please help me know what I'm doing wrong here.

Thanks

**Comment by jeffposnick** [comment]
If you're specifically seeing issues that are tied to the `-temp` cache and cleanup, then the changes introduced in Workbox v4, detailed in #1793, might be relevant to you.

Migrating to the latest Workbox release is definitely worth trying here.

**Comment by sharanan-sarvsutra** [comment]
I am on v4 and facing similar issue (there are no temp caches). Have tried following (as suggested remedies), but to no avail:-

1. Avoid using skipWaiting()
2. If using skipWaiting() then use [this](https://developers.google.com/web/tools/workbox/guides/advanced-recipes) recipe 

All my hashed cache files use StaleWhileRevalidate strategy. Wondering if the cause of this issue could be a **conflict between the strategy (staleWhileRevalidate) I am using and the way Workbox handles cache refresh**? I could try NetworkFirst, but that'll go against my app's preferred behaviour. Seconding @sourybunny - deleting old caches on register is also not a solution.

Ensuring smooth redeployments is absolutely critical for a PWA to compete with Native apps. Arguably, native apps have improved a lot when it comes to managing user experience during app updates. I really think there has to be a better, more straightforward way to deal with this issue. The default doesn't seem to be working for me.

**Comment by sourybunny** [comment]
@sharanan-sarvsutra 
Glad that I found someone facing similar issue, but it's really disappointing that there is no solution to this issue so far. It works with networkFirst but that's not intended for caching resources. Deleting old caches just saved me from the redeploy bug. But I'm still looking for a solution to this. :(

**Comment by sharanan-sarvsutra** [comment]
Just clarifying a gap in my understanding of workbox caching  - I am using CRA's build tool that auto-hashes the build files. Unlike precached files, it seems files cached via a strategy (such as StaleWhileRevalidate) require manual refresh when modified. Workbox's waiting event callback seems like a good place to do this. Couldn't find a plugin to avoid doing this from scratch. 

A few observations:-
1) 'waiting' callback reliably fires each time service worker updates
2) 'skipWaiting' handler is called immediately after
3) 'controlling' handler should be next if service worker updates properly - this not working in my case, still debugging

Interestingly, I am no longer getting the 'Unexpected token <' error because workbox is able to handle updates to the cached files. Although, workbox is also keeping the old files (which should be removed whenever sw update is available), but it has now stopped referring to old files (the cause of 'Unexpected token <' error). 

I simply followed the advanced recipe as prescribed on [this](https://developers.google.com/web/tools/workbox/guides/advanced-recipes) page, with the prompts removed. Apparently removing the prompts had an effect on workbox properly loading the updates.

**Comment by sharanan-sarvsutra** [comment]
Sharing an update - redeployments are not breaking any service worker logic now. Followed the advanced recipe as suggested in Workbox guides (minus the prompts) + manually handled cache refresh inside workbox's 'waiting' handler.

**Comment by sourybunny** [comment]
Hey @sharanan-sarvsutra , can you share a gist/code of how you are doing the manual cache refresh and service worker updating logic. 

Thanks.

**Comment by sharanan-sarvsutra** [comment]
**workbox sw config**:-
`self.addEventListener('message', (event) => {
        if (event.data && event.data.type === 'SKIP_WAITING') {
            self.skipWaiting();
        }
    });`

**to refresh cache**:-
`import { Workbox } from 'workbox-window';
export default function workboxRefresh() {
    if ('serviceWorker' in navigator) {
        const wb = new Workbox('/service-worker.js');
        wb.addEventListener('waiting', async (event) => {
            await caches.delete('js-cache');
            await caches.delete('css-cache');
            window.location.reload();
            wb.addEventListener('controlling', (event) => {
                window.location.reload();
            });
            wb.messageSW({ type: 'SKIP_WAITING' });
        });
        wb.register();
    }
}`

**Comment by alexeigs** [comment]
@jeffposnick @sharanan-sarvsutra 
I managed to make it work, currently with the following process (first step two steps needed for iOS)

1. Listening to a server version string
2. Trigger a `window.location.reload()` if server version changes
3. New SW is received and registered
4. In the `updated` hook, I `registration.waiting.postMessage({ type: 'SKIP_WAITING`})` and `window.location.reload()` again
5. Everything works fine

But I wonder, Is there another way than reloading again after the SW updated in order to prevent the error occurring when precached resources mismatch due to hashes in their url.

   - First, what does the `window.location.reload()` after the SW update actually do in this case, does it update those precached urls?
   - Could we manually clean some cache that's relevant instead?
   - What are the advantages/disadvantages of `ignoreURLParametersMatching: [/./]` in order to prevent the very same error without doing either of the two measures above?

Thanks for some clarification.

**Comment by rosslavery** [comment]
@sourybunny were you able to find a solution here? We're encountering identical behaviour here.

**Comment by vksco** [comment]
This issue still exists,
after debugging for hours i find out that the largets file like `app.js` and `chunk.vendor.js` not caching in cache store. Thats why server is throwing 404 for this files because the default caching file is 2MB.

So the solution is to add `maximumFileSizeToCacheInBytes: Bytes` under `workboxOptions` .
this work for both `GenerateSW` and `InjectManifest` modes.

```
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  pwa: {
    workboxPluginMode: "GenerateSW",
    workboxOptions: {
      exclude: ['.htaccess'],
      maximumFileSizeToCacheInBytes: 5000000 // 5MB
    }
  }
})
```
