### ISSUE TITLE
no CACHE_UPDATE message event fired at Workbox Window

### ISSUE THREAD

**Issue by henrylearn2rock** [GoogleChrome/workbox#2055]
**Library Affected**:
workbox: 4.3.1
workbox window: 4.3.1

**Browser & Platform**:
Google Chrome 74

**Issue or Feature Request Description**:

workbox message event is not triggered by `new workbox.broadcastUpdate.Plugin()` for `StaleWhileRevalidate` strategy

I followed https://developers.google.com/web/tools/workbox/modules/workbox-window#examples under "Notify the user of cache updates from the workbox-broadcast-update package" but nothing's triggered

```js
if ('serviceWorker' in navigator) {
  const wb = new Workbox('/sw.js')
  wb.addEventListener('message', event => {
     if (event.data.type === 'CACHE_UPDATE') {
       // NOTHING'S FIRED HERE, BUG?
     }
  })
...
```

but if I tap into broadcast api myself, it's there

```js
const updatesChannel = new BroadcastChannel('workbox')
updatesChannel.addEventListener('message', event => {
    console.log('here', event)  // THIS WORKS
})
```

the event.data is 
```js
{
  data:
  meta: "workbox-broadcast-update"
  payload: {
    cacheName: "workbox-runtime-http://localhost:8080/",
    updatedURL: "http://localhost:8080/file_changed.json"
  },
  type: "CACHE_UPDATED"
}
```

FYI in my service worker:
```js
workbox.routing.registerRoute(
    /\.json$/,
    new workbox.strategies.StaleWhileRevalidate({
        plugins: [new workbox.broadcastUpdate.Plugin()]
    })
)
```

**Comment by philipwalton** [comment]
Ahh, looks like our documentation has a small bug. The `event.type` value it's checking for should be `CACHE_UPDATED` not `CACHE_UPDATE`.

**Comment by philipwalton** [comment]
This PR should update the docs: https://github.com/google/WebFundamentals/pull/7607
