### ISSUE TITLE
Wrong quota in Google DevTools?

### ISSUE THREAD

**Issue by bitterdev** [GoogleChrome/workbox#2056]
Hello together,

I noticed a strange behavior in Google Dev Tools when using Workbox. The quota in the Google DevTools will not be updated if you remove the caches in DevTools. Also the quota bloats up if you reload the page. Here is a video which is showing the behavior:

[https://owncloud.bitter.de/index.php/s/RZHNq0k7O01c3cr](https://owncloud.bitter.de/index.php/s/RZHNq0k7O01c3cr)

In my project i use Workbox in version 4.3.0, but the problem seems to exist already longer (if it is a workbox problem!). As an example, i refer to www.tinder.com, which uses Workbox in version 3.6.3.

**Steps to reproduce:**

- refresh page
- remove individual caches (right-click > delete)
- check quota
- repeat…

I don't know if it is just a display error, a calculation error related to DevTools. When removing caches it seems to not wipes all data. However, the page bloats up and if it is not just a display error, it can quickly run into problems e.g. for iOS devices where the storage limit is just 50MB.

I have posted that issue here because i was not able to reproduce it with "native service workers" or with the predecessor "sw-precache". I checked multiple websites and before i was using Workbox i didn't had that issue...

**My Environment informations:**

Mac OS X 10.14.5 Beta (latest)
Chrome Version 74.0.3729.131 (latest)

**Comment by philipwalton** [comment]
This looks like a Chrome bug to me, and I can reproduce similar behavior on sites that don't use Workbox (e.g. [jakearchibald.com](https://jakearchibald.com)). Interestingly, on Jake's site I saw the donut chart update the first time I manually removed the caches, but when I unregistered the service worker and refreshed the page, I started seeing the behavior you described.

Can you file this on crbug.com?

**Comment by bitterdev** [comment]
fyi: i have created a ticket on crbug.com.

Here is the url: https://bugs.chromium.org/p/chromium/issues/detail?id=962240

**Comment by philipwalton** [comment]
Thanks! I'll follow along there.
