### ISSUE TITLE
warmRuntimeCache() and cacheRevisionedAssets()

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#206]
[Feedback from @prateekbh] It's not clear that cacheRevisionedAssets() adds routes for this. It's also not clear that warmRuntimeCache() requires routes to be defined as none of the demo's include it.

Naming is also not clear.

**Comment by addyosmani** [comment]
Was there any feedback from Ewa on either of these methods? My two cents are that the names definitely don't capture route generation or necessity. `cacheRevisionedAssetsAndScaffold()`, `cacheRevisionedAssetsAndAddRoutes()`? These start to get a little verbose. Would it make sense for `cacheRevisionedAssets()` to not add routes and instead defer to a separate method to add routes directly? This loses a user convenience but might be more clear.

**Comment by gauntface** [comment]
@prateekbh and @devnook do you have any comments on this?

Feels a bit verbose to have:

    self.goog.swlib.cacheRevisionedAssets(self.__cacheList);
    self.goog.swlib.addRevisionedAssetsRoute();

Was also kicking around the idea of a catchall route (IF the router allows the request to fall through if it doesn't match - which I don't think it does).

    self.goog.swlib.cacheRevisionedAssets(self.__cacheList);
    self.goog.swlib.router.registerRoute('*', self.goog.swlib.cacheOnly());

**Comment by gauntface** [comment]
We ended up dropping warmRuntimeCache because it just caused confusion :(
