### ISSUE TITLE
SyntaxError: Unexpected token ... with v4+

### ISSUE THREAD

**Issue by nico-martin** [GoogleChrome/workbox#2061]
**Library Affected**:
workbox-webpack-plugin v4.3.1

**Browser & Platform**:
- npm v5.3.0
- node v8.0.0
- webpack v4.32.0
- webpack-cli v3.3.2

**Issue or Feature Request Description**:
Im getting the following error when I run webpack (dev and prod) with the version 4.3.1.
```
options = { prototype: true, ...options };
                                 ^^^
SyntaxError: Unexpected token ...
```
After a downgrade to workbox-webpack-plugin v3.6.3 it works as expected.
Is this a known issue?

**Comment by jeffposnick** [comment]
[Spread in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals) is supported natively in some browsers, but not everywhere.

The "official" bundles for the Workbox runtime (i.e. those hosted on the CDN, or that get copied over via a build process) are transpiled via `@babel/preset-env`, and shouldn't end up using that syntax.

If you're [bundling the Workbox libraries yourself](https://developers.google.com/web/tools/workbox/guides/using-bundlers), then you may need to add in `@babel/preset-env` (or another tool for transpilation) to ensure that your final bundle uses JavaScript syntax compatible with the browsers you want to target.

**Comment by nico-martin** [comment]
It happens on the webpack build process. So it's not the browser, but the node process.

**Comment by jeffposnick** [comment]
Hmmm... you mention that you're using node v8.0.0. Can you confirm that you're actually on that version, and not something earlier?

As per https://node.green/#ES2015-syntax-spread-syntax-for-iterable-objects, that syntax should be supported going back to node v5.12.0.

I just tried the following experiment, and it worked fine:

```sh
$ node -v
v8.16.0

$ node
> options = {1: 2}
{ '1': 2 }
> options = { prototype: true, ...options }
{ '1': 2, prototype: true }
```

**Comment by nico-martin** [comment]
Ok, that's strange. Node v8.0.0 throws the `SyntaxError: Unexpected token ...` Error, but Node v8.10.0 seems to work. I switched multiple times to make sure that's the problem.

Then I tried your experiment `> options = { prototype: true, ...options }` and that works with Node 8.10.0 AND Node 8.0.0. So it's not the spread syntax (that works with both) but something else.

In the end I'm fine with 8.10.0. Thank for your help!

**Comment by omokehinde** [comment]
Am having this same issue and am using node v8.2.1

**Comment by nico-martin** [comment]
Did you try node 8.10.0?

**Comment by omokehinde** [comment]
> Did you try node 8.10.0?
nope...I didn't I started building the react project with v8.2.1 and after installing react-router-dom I am having this error. What exactly can I do to find my way around this issue?
