### ISSUE TITLE
[feature] make it work with dotenv-webpack

### ISSUE THREAD

**Issue by sibelius** [GoogleChrome/workbox#2062]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
it should work with dotenv-webpack or other way to inject environment variables

Use case:
I'd like to change firebase config based on .env

```jsx
const config = {
  messagingSenderId: process.env.FIREBASE_MESSAGING_SEND_ID,
};

firebase.initializeApp(config);
```

but `process` is undefined on sw.js

I'm using `workboxPlugin.InjectManifest`

**Comment by jeffposnick** [comment]
This should be addressed by https://github.com/GoogleChrome/workbox/releases/tag/v5.0.0-alpha.0

It will compile you `swSrc`, and if you need to pass in specific plugins to configure the webpack compilation (like a plugin to handle that replacement), you should be able to do that via the new `webpackCompilationPlugins ` configuration option.

Please reopen if I'm misinterpreting your use case, and you're still unable to accomplish that.

**Comment by bhumit070** [comment]
SO like how do i use environment variables in my service worker file

**Comment by jeffposnick** [comment]
You should be able to pass in whichever `webpack` plugin you want to use to perform the replacement to the `plugins` option of `InjectManifest`.

**Comment by bhumit070** [comment]
How to use it without webpack 🙂🙂

**Comment by jeffposnick** [comment]
You'll need some sort of build tool to replace the environment variable placeholders with their actual values. If you don't use `webpack`, you'll have to use something else, most likely something from https://bundlers.tooling.report/

**Comment by bhumit070** [comment]
Ok will look into it
