### ISSUE TITLE
TypeError: workbox.core.LOG_LEVELS is undefined

### ISSUE THREAD

**Issue by BernardA** [GoogleChrome/workbox#2066]
**Library Affected**:
*workbox-sw

**Browser & Platform**:
Firefox and Chrome both latest, on Mac

**Issue or Feature Request Description**:
I did a general update on my npm dependencies today, and have the above error when running the app.

     `TypeError: workbox.core.LOG_LEVELS is undefined`

The sw-src.js file correponding code is:

    workbox.setConfig({
         debug: true
      });
     workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);

On webpack.config.js the workbox code:

            new ManifestPlugin(),
            new InjectManifest({
                swSrc: './client/sw-src.js',
                swDest: '../sw.js',
                exclude: [/\.twig$/, /\.DS*/],
            }),

**Comment by jeffposnick** [comment]
Hello @BernardA!

This is an expected change when moving from v3 to v4: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3#workbox-core

Removing the call to `workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);` and then just using the built-in filtering present in your browser's DevTools should get you similar behavior.
