### ISSUE TITLE
index.html NOT served from ServiceWorker when Request URL doesn't end with / i.e. trailing slash

### ISSUE THREAD

**Issue by nuragic** [GoogleChrome/workbox#2067]
Hi,

I'm using `workbox-webpack-plugin` with a very similar config to `create-react-app`.

```
// … 
// publicUrl === '/myapp';
isEnvProduction &&
        new WorkboxWebpackPlugin.GenerateSW({
          clientsClaim: true,
          skipWaiting: false,
          cleanupOutdatedCaches: true,
          exclude: [/\.map$/, /asset-manifest\.json$/],
          cacheId: `myapp-${process.env.MY_APP_VERSION}`,
          importWorkboxFrom: 'cdn',
          importScripts: [`${publicUrl}/service-worker-custom-logic.js`],
          navigateFallback: `${publicUrl}/index.html`,
        }),
// …
```

The app is a SPA/PWA, the entry point is `https://example.com/myapp`; the server is correctly configured to serve `index.html`, the client router is ok too.

Everything is working great, except one important thing: suppose that I do already have a precache and an active SW; when users open a new tab/window and go to `https://example.com/myapp`, the `index.html` request always hit the network. 😕 

However, if I do the same but with a trailing slash i.e. `https://example.com/myapp/` everything works as expected! 😱 Now the `index.html` request is _(from ServiceWorker)_, as shown in Chrome DevTools.

So far, I found the following in the docs:

> Requests ending in a / will, by default, be matched against entries with an index.html appended to the end. This means an incoming request for / can automatically be handled with the precached entry /index.html.

https://developers.google.com/web/tools/workbox/modules/workbox-precaching#directory_index

> If a request fails to match the precache, we'll add .html to end to support "clean" URLs (a.k.a "pretty" URLs). This means a request like /about will be handled by the precached entry for /about.html.

https://developers.google.com/web/tools/workbox/modules/workbox-precaching#clean_urls

So, given the above config, there's anything wrong? Is this a bug? If this is expected, why? How we're supposed to handle this common case? i.e. What is missing to have `https://example.com/myapp` to match `/myapp/index.html` in the cache? 🤔 

Many thanks in advance and thanks for your time! 💛

**Comment by nuragic** [comment]
Thanks for the quick reply!

Well, I'm using v4… from CDN.

The generated SW file (using the config above) is the following:

```js
/**
 * Welcome to your Workbox-powered service worker!
 *
 * You'll need to register this file in your web app and you should
 * disable HTTP caching for this file too.
 * See https://goo.gl/nhQhGp
 *
 * The rest of the code is auto-generated. Please don't update this file
 * directly; instead, make changes to your Workbox build configuration
 * and re-run your build process.
 * See https://goo.gl/2aRDsh
 */

importScripts("https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");

importScripts(
  "/myapp/service-worker-custom-logic.js",
  "/myapp/precache-manifest.5e8e1857eba7bc93e70096be52e6ddc8.js"
);

workbox.core.setCacheNameDetails({prefix: "myapp-1.0.0"});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

workbox.core.clientsClaim();

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.precaching.cleanupOutdatedCaches();
workbox.routing.registerNavigationRoute(workbox.precaching.getCacheKeyForURL("/myapp/index.html"));
```

Regarding incognito: yes, I can reproduce the same behaviour. Moreover, I have the debug enabled but I don't even see the console log for this line:

```js
logger.warn(`The precached response for ` + 
     `${getFriendlyURL(precachedURL)} in ${cacheName} was not found. ` + 
     `Falling back to the network instead.`); 
```

And regarding sharing the app URL... I'd love to do so, but it isn't public right now. I'd indeed very happy to share it with you in private, I'm 100% available to schedule a quick call if you want (you could reach me via twitter PM). Then we will post the eventual resolution here. Sounds legit? Thanks!

**Comment by nuragic** [comment]
I’ve been able to finally identify the issue, and it’s not related to workbox. 😅 

The problem was… 🥁 **the service worker scope!** 🤦‍♂️

I just found out that by default, the scope is set to `/myapp/` (yeah, that trailing slash matters). 

In order to make the SW control `/myapp` (without the trailing slash), I did the following:

- Specify the `{ scope: '/app' }` in the SW registration options
- Add the HTTP Header 'Service-Worker-Allowed: /myapp’ in the server config, for the request serving the SW script

Doing so it solved the issue. 🎉 

I found the information related to the SW registration scope that made me try this solution here: https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope

Already opened https://github.com/google/WebFundamentals/pull/7734 to update that info.

Thanks @jeffposnick!

**Comment by philipwalton** [comment]
In case it's helpful, the [`workbox-window` library](https://developers.google.com/web/tools/workbox/modules/workbox-window) will warn you if you register a service worker that's out of scope for the current page.
