### ISSUE TITLE
Subresource Integrity via Request.integrity for Pre-Caching

### ISSUE THREAD

**Issue by josephliccini** [GoogleChrome/workbox#2073]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*All Browsers*

**Issue or Feature Request Description**:
We have ended rolling our own pre-caching implementation, but are contemplating moving back into the Workbox mechanism, now that v4 has fixed up a few bugs.

One feature we have added that I don't see supported in Workbox Precaching is Subresource Integrity enforcement.

It wouldn't be too hard to generate the SRI hashes since you already are doing some hashing for Workbox Build anyways.

I think this would be a useful feature for Workbox Precaching, as it would prevent corrupt or compromised CDN Assets from being served and stored offline for PWAs to run on subsequent activation.

The implementation we rolled utilized: https://developer.mozilla.org/en-US/docs/Web/API/Request/integrity

On an unrelated note, it would be awesome to get SRI support into `importScripts()` too, but I think that's out of the scope of this package.

**Comment by jeffposnick** [comment]
Thanks for the suggestion!

I could imagine opening up the precache manifest format to add in an `integrity` field, and if present, use that value as the `integrity` field in the precaching `Request`:

```
[{
  url: '/style/a.css',
  revision: 'feab4399...',
  integrity: 'sha384-abcd1234...',
}, {
  ...
}]
```

It's going to be easier in v5 in particular to manipulate manifest entries beyond what the build tools will spit out automatically, and I could see it being fairly straightforward to add in those `integrity` values via a custom callback function that you can implement.

Alternatively, Workbox could add in those values itself via a new opt-in parameter, but I could imagine that being a little messier to configure if there are some items in the manifest that you want to set `integrity` for, and others that you don't.

What are your thoughts in terms of Workbox handling that vs. adding those properties yourself via a callback?

My open question is how the `revision` and `integrity` fields would interact—there's definitely an overlap between the information that both contain. But `workbox-precaching` has some specific logic in place to disable cache-busting the network request when `revision` is empty, on the assumption that the URL is uniquely versioned. That assumption around cache-busting could not be made based on the presence of the `integrity` property. That makes me think we'd want to treat those both as independent properties.

**Comment by josephliccini** [comment]
Definitely there will be assets that don't need to include integrity.  (For example, an App Shell that comes from a Web Service, instead of a staticly-built one)

Custom callback ability would suit our purposes, but I think having integrity checks for assets should still be built-in, so all consumers of this library are secured by default.

Maybe `workbox-build` can perform the integrity hashing optionally, and in conjunction with a user including a workbox-provided or custom callback to enable it.

As for `revision` and `integrity`, I think the assumption about being uniquely versioned by URL for those without a `revision` should continue to hold.  `integrity` is just a security check for that uniquely versioned URL, and shouldn't be included in cache busting logic.  

But maybe there's an edge case that I'm missing..
