### ISSUE TITLE
Adding CDN scripts (e.g. jQuery) to precaching with webpack-workbox-plugin

### ISSUE THREAD

**Issue by jlchereau** [GoogleChrome/workbox#2074]
> Not sure whether this qualifies a defect, a feature request or simply a bad understanding on my part.

**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
nodeJS 12
webpack v4.33.0
workbox-webpack-plugin v4.3.1
"all browsers"

**Use Case**:
I need to precache jQuery from https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js (among other CDN resources) considering in webpack.config.js it is configured as follows:

```
module.exports = {
    ...
    externals: {
        jquery: 'jQuery'
    },
    ...
}
```

**Issue or Feature Request Description**:
After reading the guide at https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin, #604, #626 and #664, I have opted for using manifestTransforms as follows:

```
manifestTransforms: [
    originalManifest => {
        const manifest = originalManifest.concat([
            {
                url:
                    'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'
            }
        ]);
        // Optionally, set warning messages.
        const warnings = [];
        return { manifest, warnings };
    }
],
```

## The warning:

Nevertheless when building, I get the following warning, noting that I have not set globPatterns and originalManifest is an empty array in the above manifestTransorms:

```
WARNING in You're using the following Workbox configuration options: [manifestTransforms].
This will not have any effect, as it will only modify files that are matched via 'globPatterns'.
You can remove them from your config, and learn more
at https://goo.gl/EQ4Rhm
```

As far as I have tested, this configuration aloows precaching jQuery:

![image](https://user-images.githubusercontent.com/2556751/59281719-a46e8900-8c5f-11e9-94ab-b0c600527760.png)

Am I doing this right?
Can this warning be safely ignored?
Is this a warning you might want to improve?

Besides, I have a question: although not necessary in this case considering jQuery versioning in the URL, how can I compute and add a revision? What is the hashing algorithm used?

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/workbox/issues/1571 will make this more straightforward in v5.

In the meantime, using `manifestTransforms` will roughly give you the behavior you want in v4, but somewhat indirectly—you can ignore that warning if you're seeing the results you expect.

**Comment by jlchereau** [comment]
`additionalManifestEntries` in #1571 is the feature needed, so I guess this is a feature request for v5. Thx.
