### ISSUE TITLE
Multiple errors in console when setting offlineGoogleAnalytics in webpack-workbox-plugin configuration with GA loaded as a GTM tag

### ISSUE THREAD

**Issue by jlchereau** [GoogleChrome/workbox#2075]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
nodeJS 12
webpack v4.33.0
workbox-webpack-plugin v4.3.1
"all browsers"

**Use Case**:
My web page head includes the google tag manager script as shown here below, so webpack has absolutely no knowledge of it:

```
<head>
     ....
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<%- config.google.tagManager.web %>');</script>
    ....
</head>
```

GTM has a universal analytics tag that is properly configured and loaded on all pages:

![image](https://user-images.githubusercontent.com/2556751/59282585-0ed3f900-8c61-11e9-9b43-a774d81d133d.png)

Then webpack-workbox-plugin is configured with:

```
{
    ...
    offlineGoogleAnalytics: true,
    ...
}
```

**Issue or Feature Request Description**:

In online mode, everything works as expected. When going into offline mode, I get numerous console errors but the application works as expected:

![image](https://user-images.githubusercontent.com/2556751/59331248-61f28e00-8ceb-11e9-982c-b341c0ad6c91.png)

GTM seems to have been cached twice (different sizes):

![image](https://user-images.githubusercontent.com/2556751/59283102-ea2c5100-8c61-11e9-8028-7df59398611a.png)

GA requests seem to be properly queued

![image](https://user-images.githubusercontent.com/2556751/59283196-13e57800-8c62-11e9-8732-257e463539bc.png)

Am I doing this right?
Can these errors be safely ignored?
Is this something you might want to improve?

**Comment by jeffposnick** [comment]
The errors can be safely ignored. They are what Chrome logs automatically when there are network failures. Under the hood, using `offlineGoogleAnalytics: true` sets up a configuration that uses `workbox-background-sync` to retry those network failures, but the failures do take place.

As for the two `/gtm.js` entries, I'm assuming that they each have different `id=` parameters. Chrome's DevTools was recently updated to start showing the URL query parameter portion of each entry, which would differentiate them, but my guess is that you're using a version of Chrome that doesn't yet have https://bugs.chromium.org/p/chromium/issues/detail?id=951414 deployed yet.
