### ISSUE TITLE
SUGGESTION: resolve urls

### ISSUE THREAD

**Issue by jlchereau** [GoogleChrome/workbox#2076]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
nodeJS 12
webpack v4.33.0
workbox-webpack-plugin v4.3.1
"all browsers"

**Issue or Feature Request Description**:

I use nodeJs and expressJS and webpack is configured with an output directory that builds scripts in `public/build/`. `public` is the expressJS static directory.

In order for the scope of the service worker to work at the root of my ExpressJS project, I need to generate sw.js into `public` and I have therefore configured workbox-webpack-plugin in webpack.config.js as follows:

```
{
  ...
  swDest: '../sw.js',
  ...
}
```

In the precache manifest that is automatically generated, the URL is concatenated, not resolved:

```
self.__precacheManifest = (self.__precacheManifest || []).concat([
  {
    "revision": "ee12cafec03eeff3b96a754e343c26d2",
    "url": "https://localhost:3000/build/../sw.js"
  },
  ...
]);
```

I would have expected a resolved URL as in:

```
self.__precacheManifest = (self.__precacheManifest || []).concat([
  {
    "revision": "ee12cafec03eeff3b96a754e343c26d2",
    "url": "https://localhost:3000/sw.js"
  },
  ...
]);
```

**Comment by jeffposnick** [comment]
Please try the `workbox-webpack-plugin@next` [alpha release](https://github.com/GoogleChrome/workbox/releases).

There is: a) no more external manifest and b) more control over manipulating manifest entries if you need it.
