### ISSUE TITLE
workbox-window - wb.messageSW(message) returns just true and not the object I expect

### ISSUE THREAD

**Issue by bill-decisiontime** [GoogleChrome/workbox#2077]
**Library Affected**:
*workbox-window*

**Browser & Platform**:
*Google Chrome Version 75.0.3770.80 (Official Build) (64-bit).*

**Issue or Feature Request Description**:
When using `let response = await wb.messageSW(message);` the return value is just `true` as opposed to the object I want to send back using `port.postMessage({ success: true, msg: 'All URLs added to cache' });`

**Code from `sw.js`**
``` js
let port = event.ports[0];
switch (event.data.type) {
  case 'CACHE_URLS':
    const cache = await caches.open(event.data.payload.cache_name);
    try {
      cache.addAll(event.data.payload.urlsToCache).then(() => {
        port.postMessage({ success: true, msg: 'All URLs added to cache' });
      }).catch((error) => {
        port.postMessage({ success: false, msg: error.message });
      }); 
    } catch (error) {
      port.postMessage({ success: false, msg: error.message });
    }
    break;
  case 'GET_VERSION':
    port.postMessage(SW_VERSION);
    break;
}
```

**Code from `window`**
``` js
let message = {
	type: 'CACHE_URLS',
	payload: { cache_name: cache_name, urlsToCache: cache_urls_uniq},
};

let response = await wb.messageSW(message);

if ( ! response.success)
{
	$(document).trigger('offline_sync:add_all_to_cache:error', response);
}
```

**Comment by philipwalton** [comment]
Hmmm, are you sure? I can't reproduce this, and we have a [test for the message reply behavior](https://github.com/GoogleChrome/workbox/blob/v4.3.1/test/workbox-window/window/test-Workbox.mjs#L475-L481) that's passing in all browsers.

Can put together a demo (Glitch is usually good for SW demos) that shows the behavior you're seeing?

**Comment by bill-decisiontime** [comment]
@philipwalton tried this on [glitch](https://glitch.com/~petalite-height) and works as expected, so must be something else in our code.  Thanks.
