### ISSUE TITLE
Primitive return value from matchCb not passed as 'params' into handlerCb

### ISSUE THREAD

**Issue by emillundstrm** [GoogleChrome/workbox#2079]
**Library Affected**:
workbox-sw

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

The documentation of [workbox-routing](https://developers.google.com/web/tools/workbox/modules/workbox-routing) indicates 

> The params value is the value returned by the "match" function.

This does not work if the match function returns non-Object and non-Array values.

E.g.:

```
workbox.routing.registerRoute(
    ({event}) => event.request.headers.get('x-cache-name'),
    ({event, params}) => {
        const strategy = new workbox.strategies.NetworkFirst({cacheName: CACHE_PREFIX + params});
        return strategy.makeRequest({request: event.request});
    }
);
```

Passes `undefined` as params into the handler function even though x-cache-name is present on the request - since it is a string.

If you instead return `{cacheName: event.request.headers.get('x-cache-name')}` from matchCb, it is passed to handlerCb as expected.

**Comment by jeffposnick** [comment]
Thanks for pointing this out; I think we're too restrictive with this logic: https://github.com/GoogleChrome/workbox/blob/e33e8dcb2e207d97de07a4df9a013be341d58f7b/packages/workbox-routing/Router.mjs#L268-L282
