### ISSUE TITLE
 Reload, when it does not have a new cache version

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#2082]
version workbox: 4.3.1

Not my html index, I have the following code to identify when there is a new cache version and if it does it reload the page.
But sometimes it is reloading when there is no new cache version.
Based on that code, how should I adjust to 100%?

@philipwalton 
@jeffposnick 

```javascript
   if ( ('serviceWorker' in navigator) && (window.location.origin != 'http://localhost:3000') ) {

        window.addEventListener('load', function() {

            navigator.serviceWorker
                .register('sw-vimbo.js')
                .then(function(reg) {
                    console.log('[Vimbo APP | OK] - Service worker Registered', reg);

					if (navigator.serviceWorker.controller) {
						console.log('[sw controler]')

						// teve alteração service worker
						var refreshing = false;
						navigator.serviceWorker.addEventListener('controllerchange', function () {
							console.log('serv controllerchange')

							// refresh uma vez
							if (!refreshing) {

								// limpa cache storage da máquina
								caches.keys().then(function(keyList) {
									return Promise.all(keyList.map(function(key) {
										return caches.delete(key);
									}));
								});

								window.location.reload();
								refreshing = true;
							} else {
								return;
							}

						});
					}

                })
                .catch(function(err) {
                    console.log('[Vimbo APP | FALHOU] - Service worker not Registered', err);
                });
		});

    }
```

**Comment by jeffposnick** [comment]
It's possible that there's a race condition, in which the `controllerchange` event is fired before you add in your event listener. The service worker update check happens automatically, as soon as you navigate to a page, and if you're calling `skipWaiting()` inside your service worker, the new one could end up taking control at any point.

The recommended guidance for developers who want more control over the update is https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users
