### ISSUE TITLE
Dealing with HTTP errors on NetworkFirst

### ISSUE THREAD

**Issue by nuragic** [GoogleChrome/workbox#2084]
**Library Affected**:
*workbox-strategies*

**Issue or Feature Request Description**:

As far as I can tell, when using NetworkFirst strategy, if the response of the request is an error (I mean any HTTP error code), workbox isn't serving the cached response (if there's any, indeed)... is there any reason why this behaviour? It would be possible to do so without extending the NetworkFirst class?

Thanks!

**Comment by jeffposnick** [comment]
That's correct—a 4xx or 5xx response from the network isn't consider a failure, so falling back to the cache won't happen automatically. (This matches the general behavior you get from using `fetch()` directly.)

If you wanted to customize this behavior, you could accomplish that by writing a [Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins). Here's an (untested) example; let me know if it works for you:

```js
const myPlugin = {
  fetchDidSucceed: async ({request, response}) => {
    // response.ok means there was a 2xx response code.
    if (response.ok) {
      return response;
    }
    // Throwing here should make it roughly equivalent to a network failure.
    throw new Error(`${response.status} ${response.statusText}`);
  },
};

const myStrategy = new workbox.strategies.networkFirst({
  plugins: [myPlugin],
  // Configure other options here.
});

workbox.routing.registerRoute(
  ...,
  myStrategy
);
```

**Comment by nuragic** [comment]
Ok got it! I'll try this way and let you know if it works 👍

**Comment by nuragic** [comment]
It worked! Many thanks! 🤗 Those hooks are awesome! 🙌 

My use case is that I have a SPA with a server rendered `index.html` (different content depending on the user). So I need to cache `index.html`, but the precache isn't a viable option here. As the app is a single page app, every navigation route must serve the `index.html` in order to work... thus I also need to have a single cache entry for every navigation route. This is what I did in my `service-worker.js`:

```js
const navMatcher = ({ url, request }) => {
  return (request.mode === "navigate");
};

const navHandler = new workbox.strategies.NetworkFirst({
  networkTimeoutSeconds: 5,
  matchOptions: { ignoreSearch: true },
  plugins: [
    new workbox.cacheableResponse.Plugin({ statuses: [0, 200] }),
    {
      // respond with cached content if there's an HTTP error
      fetchDidSucceed: async ({ request, response }) => {
        if (response.ok) {
          return response;
        }
        throw new Error(`${response.status} ${response.statusText}`);
      },
      // cache the index.html under the same key
      cacheKeyWillBeUsed: async function({ request, mode }) {
        return "/";
      }
    }
  ]
});

workbox.routing.registerRoute(navMatcher, navHandler, "GET");
```

Dunno if it's the best approach but _it works®_. 😗👌

**Comment by rationalthinker1** [comment]
> That's correct—a 4xx or 5xx response from the network isn't consider a failure, so falling back to the cache won't happen automatically. (This matches the general behavior you get from using `fetch()` directly.)
> 
> If you wanted to customize this behavior, you could accomplish that by writing a [Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins). Here's an (untested) example; let me know if it works for you:
> 
> ```js
> const myPlugin = {
>   fetchDidSucceed: async ({request, response}) => {
>     // response.ok means there was a 2xx response code.
>     if (response.ok) {
>       return response;
>     }
>     // Throwing here should make it roughly equivalent to a network failure.
>     throw new Error(`${response.status} ${response.statusText}`);
>   },
> };
> 
> const myStrategy = new workbox.strategies.networkFirst({
>   plugins: [myPlugin],
>   // Configure other options here.
> });
> 
> workbox.routing.registerRoute(
>   ...,
>   myStrategy
> );
> ```

I had to modify this to cover other statuses. mainly 0 and 304.
