### ISSUE TITLE
setCatchHandler only works offline

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#2090]
Using Workbox version: 4.3.1

I'm testing out the code snippet found here: https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route

I have a test web page that has several 404 missing images.

When I load the web page (online) I see the image alt-text and an  error.

When I load the web page (offline) I see the fallback image.

Is there a way to display the fallback images both online and offline using the `setCatchHandler`.

Thanks.

**Comment by jeffposnick** [comment]
Hello!

I think that the advice at https://github.com/GoogleChrome/workbox/issues/2084#issuecomment-506457979 should apply to your situation.

Please let us know if that's not the case and we can investigate further.

**Comment by ayumihamsaki** [comment]
@jeffposnick Thanks for your reply, yes that fixes the issue.

Would it be a good idea to add your comment to the doc's (to the fallback image):

> A 4xx or 5xx response from the network isn't consider a failure, so falling back to the cache won't happen automatically. (This matches the general behavior you get from using `fetch()` directly).

**Comment by ayumihamsaki** [comment]
@jeffposnick Thanks for your comment, I did the following, but it doesn't seem to work, here is my code:

```javascript
 workbox.routing.registerRoute(
   /\.(?:png|jpg|jpeg|webp)$/,
   new workbox.strategies.CacheFirst({
     cacheName: 'images',		
     plugins: [
       new workbox.expiration.Plugin({
         maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
       }),
       new workbox.cacheableResponse.Plugin({
         statuses: [0, 200],
       }),
       /* Handle 4xx or 5xx response from the network */
       {
         // respond with cached content if there's an HTTP error
         fetchDidSucceed: async ({ request, response }) => {
           if (response.ok) {
             return response;
           }
           throw new Error(`${response.status} ${response.statusText}`);
         },
         // Add a Fallback Image
         cacheKeyWillBeUsed: async function({ request, mode }) {
           return "/storage/app/media/fallback.png";
         }
       }
     ],
   }),
 );
```

**Comment by ayumihamsaki** [comment]
Thanks for your help.

**Comment by ayumihamsaki** [comment]
Thanks for your help. 😃
