### ISSUE TITLE
Deprecate workbox-routing's registerNavigationRoute()

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2095]
`workbox.routing.registerNavigationRoute()` is a recurring source of confusion for developers (c.f. https://github.com/GoogleChrome/workbox/issues/1988 recently, as well as this [archive of past issues](https://github.com/GoogleChrome/workbox/issues?utf8=✓&q=is%3Aissue+registerNavigationRoute) in general).

`workbox.routing.registerNavigationRoute()` appears to be a general-purpose method of registering a route that matches navigation requests, when in fact, it's implemented as a way of bridging the gap between `workbox-routing` and `workbox-precaching`, making it easier to handle navigations using precached URLs.

Not everyone _wants_ to handle navigations with precached URLs, though.

I think in v5, we might be able to get away with moving most of the logic in `registerNavigationRoute()` from `workbox-routing` to `workbox-precaching`, and have it just return logic that could be used as a `handler` callback. This `handler` callback could then be used when constructing a route.

If we moved this logic to `workbox-precaching`  we could also avoid having to explicitly call `workbox.precaching.getCacheKeyForURL()`, which has been _another_ source of confusion in Workbox v4.

```
// v4:
workbox.routing.registerNavigationRoute(
  workbox.precaching.getCacheKeyForURL('/app-shell.html')
);

// v5:
const handler = workbox.precaching.createHandlerForURL('/app-shell.html');
const navigationRoute = new workbox.routing.NavigationRoute(handler);
workbox.routing.regsiterRoute(navigationRoute);
```

CC: @philipwalton who was looking into the feasibility of using `workbox-strategies` under the hood for the handler logic in `workbox-precaching`, as this proposed change might impact that plan.

**Comment by frlinw** [comment]
> If we moved this logic to workbox-precaching we could also avoid having to explicitly call workbox.precaching.getCacheKeyForURL(), which has been another source of confusion in Workbox v4.

In which way
```js
workbox.routing.registerNavigationRoute(
  workbox.precaching.getCacheKeyForURL('/app-shell.html')
)
```
is more confusing than
```js
workbox.routing.registerRoute(
  new workbox.routing.NavigationRoute(
    workbox.precaching.createHandlerForURL('/app-shell.html')
  )
)
```
?

I'm already using it
![image](https://user-images.githubusercontent.com/11896237/60995878-c9841380-a353-11e9-9091-aadeea00a23c.png)
But it'is a basic use-case and as a user I just want an easy  way to do it. Workbox could provide a sugar method with the URL as a param which abstract this common boilerplate.

**Comment by jeffposnick** [comment]
The main source of confusion has to do with:

> `workbox.routing.registerNavigationRoute()` appears to be a general-purpose method of registering a route that matches navigation requests, when in fact, it's implemented as a way of bridging the gap between `workbox-routing` and `workbox-precaching`, making it easier to handle navigations using precached URLs.

`workbox-routing` includes a class that has implementation details that are pretty specific to `workbox-precaching`, and it would be cleaner/less confusing to put those details inside of `workbox-precaching`. That's my thinking, at least—if folks disagree, we can reconsider.

**Comment by frlinw** [comment]
@jeffposnick I don't question the "where things should be" part. Just the dev experience part.

If I could do
```js
import { routeToShell } from 'workbox-routing/routeToShell.mjs' // or workbox-precaching/

routeToShell('app-shell.html')
```
instead of
```js
import { registerRoute } from 'workbox-routing/registerRoute.mjs'
import { NavigationRoute } from 'workbox-routing/navigationRoute.mjs'
import { createHandlerForURL } from 'workbox-precaching/createHandlerForURL .mjs'

registerRoute(
  new NavigationRoute(
    createHandlerForURL('/app-shell.html')
  )
)
```
I'll be happy !

**Comment by philipwalton** [comment]
FWIW I'm a big fan of deprecating `registerNavigationRoute()`, as I know I've been one of the people confused by the name in the past. I also agree the right place for the new logic is in the `workbox-precaching` package.

I also think something like `precaching.createHandlerForURL()` is a good low-level primitive to make more complex strategy/plugin/route matching options possible.

If it's always going to only match navigation routes, do you think it's worth calling it createNavigationHandlerForURL()` instead? Another possible name is `createNavigationHandlerForPath()`.

**Comment by jeffposnick** [comment]
> If it's always going to only match navigation routes, do you think it's worth calling it `createNavigationHandlerForURL()` instead? Another possible name is `createNavigationHandlerForPath()`.

My thinking is that the new method wouldn't do anything related to matching. It would just be a method in `workbox-precaching` that took care of the `handlerCallback` implementation. You'd still need to combine it with something that took care of the `matchCallback` side of things, like wrap it in a `NavigationRoute` (if you wanted it to only match navigations):

```
const handler = workbox.precaching.createHandlerForURL('/app-shell.html');
const navigationRoute = new workbox.routing.NavigationRoute(handler);
workbox.routing.regsiterRoute(navigationRoute);
```

**Comment by philipwalton** [comment]
> My thinking is that the new method wouldn't do anything related to matching. It would just be a method in `workbox-precaching` that returned something which followed the `handlerCallback` interface.
> 
> You'd still need to combine it with something that took care of the `matchCallback` side of things, like wrap it in a `NavigationRoute` (if you wanted it to only match navigations):

Ahh, right, I overlooked that part. `createHandlerForURL()` SGTM then.

**Comment by hanjeahwan** [comment]
> `workbox.routing.registerNavigationRoute()` is a recurring source of confusion for developers (c.f. #1988 recently, as well as this [archive of past issues](https://github.com/GoogleChrome/workbox/issues?utf8=%E2%9C%93&q=is%3Aissue+registerNavigationRoute) in general).
> 
> `workbox.routing.registerNavigationRoute()` appears to be a general-purpose method of registering a route that matches navigation requests, when in fact, it's implemented as a way of bridging the gap between `workbox-routing` and `workbox-precaching`, making it easier to handle navigations using precached URLs.
> 
> Not everyone _wants_ to handle navigations with precached URLs, though.
> 
> I think in v5, we might be able to get away with moving most of the logic in `registerNavigationRoute()` from `workbox-routing` to `workbox-precaching`, and have it just return logic that could be used as a `handler` callback. This `handler` callback could then be used when constructing a route.
> 
> If we moved this logic to `workbox-precaching` we could also avoid having to explicitly call `workbox.precaching.getCacheKeyForURL()`, which has been _another_ source of confusion in Workbox v4.
> 
> ```
> // v4:
> workbox.routing.registerNavigationRoute(
>   workbox.precaching.getCacheKeyForURL('/app-shell.html')
> );
> 
> // v5:
> const handler = workbox.precaching.createHandlerForURL('/app-shell.html');
> const navigationRoute = new workbox.routing.NavigationRoute(handler);
> workbox.routing.regsiterRoute(navigationRoute);
> ```
> 
> CC: @philipwalton who was looking into the feasibility of using `workbox-strategies` under the hood for the handler logic in `workbox-precaching`, as this proposed change might impact that plan.

i use the v5 solution u write is not work, below this one is work fine not sure why
```
const handler = workbox.precaching.createHandlerBoundToURL("/index.html");
const navigationRoute = new workbox.routing.NavigationRoute(handler);

workbox.routing.registerRoute(navigationRoute);
```
