### ISSUE TITLE
[workbox-window] Missing isUpdate property of controlling event

### ISSUE THREAD

**Issue by lainazy** [GoogleChrome/workbox#2101]
**Library Affected**:
*workbox-window*

**Issue or Feature Request Description**:
The [Document](https://developers.google.com/web/tools/workbox/modules/workbox-window) said:
> When a new service worker starts installing but an existing version is currently controlling the page, the isUpdate property of all the following (installed, waiting, controlling, activated) events will be true.

But in fact, there is no `isUpdate` property of controlling event.

**Comment by philipwalton** [comment]
Ahh, you're right! https://github.com/GoogleChrome/workbox/pull/2114 should fix this, and we'll probably release the fix in `v5.alpha.1` next week.

If you need that flag now though and can't updated to v5 yet (for whatever reason), you can just check the private `isUpdate` flag of the `Workbox` instance itself.

**Comment by pscheit** [comment]
it's difficult to access the _isUpdate property.
but you can check it the same way workbox does check it:
```
this.isUpdate = !!navigator.serviceWorker.controller
```
when page is initialy loaded
