### ISSUE TITLE
Scope out subdirectories for caching

### ISSUE THREAD

**Issue by stoneshower** [GoogleChrome/workbox#2104]
Hello,

I am trying to cache files with using WorkboxCLI and facing a problem.
Basically, I don't want to cache any files under subdirectories but all the files under parent directory. So, my question is, does Workbox provides a method to restrict scope of caching files?

```
parent_dir
├── index.html
├── style.css
├── script.js
└── child_dir
	├── index.html
	├── style.css
	└── script.js
```

For example, if I implement a Service Worker in `parent_dir`, with `scope: /`, `child_dir` will be under the scope. However, for some situation, I need to set caching implementation only the files under `parent_dir` and exclude `child_dir` for any caching implementation.

I saw a solution as below, to add the lines in service-worker.js.
```
self.addEventListener('fetch', event => {
  if (event.request.url.includes('child_dir')) {
    event.respondWith();
  }
});
```

However, I am generating service-worker.js by WorkboxCLI, and I think it is not the best way since every time I run WorkboxCLI, I need to add the line manually.

It would be great if Workbox provides the feature.

**Comment by jeffposnick** [comment]
For the files that are in scope, what behavior are you looking for? Do you want them to be precached, and for all other files, not be cached at all?

If that's the case, then just use the `generateSW` mode of `workbox-cli`, and configure the `globPatterns` options with something like `['parent_dir/*']`. That should only pick up the files in the top-level `parent_dir` when generating the precache manifest, and not any of the files in subdirectories.

Then, when you deploy your service worker, it will by default only serve those precached files from the cache. Anything not in the precache manifest will just be served from the network, as if there were no service worker involvement.

**Comment by stoneshower** [comment]
I'm sorry for my lack of explanation. I'm expecting only the files in top-level directory to be cached. This means the files in subdirectories should not be cached.

Thank you for sharing how to with pre-cache. In my case, I actually need to use runtime cache not pre-cache. I would like to know whether `globPatterns` would work with runtime cache.

**Comment by jeffposnick** [comment]
If you're using runtime caching, then using a regular expression along the lines of `new RegExp('^/[^/]*$')` should work.

That will match a URL path that starts with `/`, and then is followed by zero or more other characters that are not `/`. If the path includes a subdirectory, then it won't match.
