### ISSUE TITLE
Allow handlerCallback instances to report when they're fully done

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2115]
**Library Affected**:
*workbox-routing, workbox-strategies*

While trying to address https://github.com/GoogleChrome/workbox/issues/1857, I discovered it's not fully possible to implement precaching (at least as it works today) with just `workbox-strategies` and `workbox-routing` primitives because the [`handlerCallback` type](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~handlerCallback) returns a `Promise<Response>` object, but it doesn't return anything that indicates when all it's work is complete (e.g. storing the response in the cache, updating IndexedDB, etc).

Since `workbox-precaching` needs the install event to wait until all caching is complete, it can't really reuse `handlerCallback` instances (either custom or the ones defined in `workbox-strategies`) and still ensure precaching either fully completes or fails if any individual request fails.

**Proposed changes:**

Instead of returning a `Promise<Response>` object, `handlerCallback()` instances could return an object with the following type:

```typescript
Promise<{
  response: Response,
  done: Promise,
}>
```

The `done` promise would typically be the same promised passed to `event.waitUntil()` to keep the service worker alive.

In addition to making precaching possible via `handlerCallbacks()`, I think this change would also have the side benefit of allowing use to call `event.waitUntil()` at the top level of the event listener in many cases where we cannot today. This would potentially allow us to remove a lot of `try/catch` blocks from our code while browsers add support for async `waitUntil()`.

**Alternative:**

As a convenience option, we could potentially allow `handlerCallbacks()` functions to return a promise that resolves to either a response (as they do today) or the `{response, done}` object as proposed here. If the returned promise resolves to just a response, then it'll be assumed that the `done` promise doesn't extend beyond the lifetime of the response.

While it may be nice to add this convenience option (and accept both return types), I am a bit concerned that giving the option might lead to people accidentally omitting the `done` promise when they really do need it.

What do folks think? /cc @jeffposnick

**Comment by jeffposnick** [comment]
As discussed in person, I'm in favor of an overload approach, where either `Promise<{response: Response, done: Promise}>` or the existing `Promise<Response>` could be returned.

I feel like there are enough very common use cases of creating custom handlers in which it feels natural to just return a `Response` inside of an `async` function, and asking everyone to switch to returning an object instead is likely to be too much of a pain.

**Comment by kdesimini** [comment]
I see no harm in offering both, provided the documentation to follow 😁

**Comment by philipwalton** [comment]
Fixed via #2455.
