### ISSUE TITLE
Workbox background sync demo is not working

### ISSUE THREAD

**Issue by zeriss** [GoogleChrome/workbox#2125]
**Library Affected**:
*workbox-background-sync*

**Browser & Platform**:
*Google Chrome 71.0.3578.98*

**Issue or Feature Request Description**:
The demo visible at https://workbox-demos.firebaseapp.com/demo/workbox-background-sync/ doesn't work

```
sw.js:17 Uncaught TypeError: workbox.skipWaiting is not a function
    at sw.js:17
(anonymous) @ sw.js:17
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
(index):77 GET https://workbox-demos.firebaseapp.com/demo/workbox-background-sync/example.txt net::ERR_NAME_NOT_RESOLVED
document.querySelector.addEventListener @ (index):77
(index):1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by philipwalton** [comment]
Sorry, we haven't been doing the best job of keeping the demos up to date with the latest Workbox changes.

I've updated the demo for Workbox v4, and you should see it working now. Let me know if you see any more issues.

**Comment by zeriss** [comment]
It works now, but it's stil a 5.0.0-alpha version.

**Comment by philipwalton** [comment]
Our deployment system uses whatever version is current at the time. Since the background sync code didn't change in v5, this shouldn't be a problem.
