### ISSUE TITLE
Workbox in Electron App - Not able to set Cache Storage

### ISSUE THREAD

**Issue by DataHippo93** [GoogleChrome/workbox#2137]
I have been trying to get this to work for some time now to no avail. I am building a PWA inside electron using Workbox as a service worker. 

The Workbox functions great when in Chrome Browser. 

In Electron I cannot get it to work. I am able to register the service worker in Electron successfully and everything appears to work except no cache storage is created. Am I missing some fundamental incompatibility between Electron and Workbox? My assumption is that once service worker is registered is should work without any issue. There is no error message on startup to debug. 

Any smackerel of knowledge would be greatly appreciated here. 

Fixed... The issue was related to manifest.json not being in the correct directory bad the name of our app.html page not being index.html.

**Comment by JinJieTan** [comment]
How did it work out? I had the same problem

**Comment by stanleynik** [comment]
Same problem
