### ISSUE TITLE
swDest with relative folder prefix not supported.

### ISSUE THREAD

**Issue by derekdowling** [GoogleChrome/workbox#2138]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
OSX

**Issue or Feature Request Description**:
As part of upgrading next-offline to v5 Alpha, we [noticed](https://github.com/hanford/next-offline/pull/158#issuecomment-513893814) that specifying a folder prefixed `swDest` value such as `/static/service-worker.js` is ignored and the SW file is output at the default `service-worker.js` destination.

It appears that [this line](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/bundle.js#L30) in workbox-build/src/lib/bundle.js causes this due to its use of `path.basename` which ignores the provided folder prefix. For example:
```
path.basename('/foo/bar/baz/asdf/quux.html');
// Returns: 'quux.html'

path.basename('/foo/bar/baz/asdf/quux.html', '.html');
// Returns: 'quux'
```

Reproduction Steps:
See https://github.com/hanford/next-offline/pull/158#issuecomment-513647451 and use the code from that Pull Request.

**Comment by jeffposnick** [comment]
Thanks for testing this out! I'll take a look.
