### ISSUE TITLE
StaleWhileRevalidate test failure

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2139]
```sh
Name     :  StaleWhileRevalidate handle() should return the cached response and update the cache when the network request succeeds
Message  :  expected 'response body 1' to equal '22'
Error    :  AssertionError: expected 'response body 1' to equal '22'
    at compareResponses (http://localhost:3004/test/workbox-strategies/sw/sw-bundle.js:1157:30)
    at async Context.<anonymous> (http://localhost:3004/test/workbox-strategies/sw/sw-bundle.js:2768:11)
```

from https://github.com/GoogleChrome/workbox/blob/b0825d74d81264e7b4537ed170dd60de638561ba/test/workbox-strategies/sw/test-StaleWhileRevalidate.mjs#L91-L115

C.f. https://travis-ci.org/GoogleChrome/workbox/builds/562400283#L2887

@philipwalton, I've never seen flakiness in that test before—do you think it's due to #2123?

**Comment by philipwalton** [comment]
I've tried a few times to reproduce this locally, and I can't seem to do it. Jeff, can you reproduce it outside of CI?

**Comment by jeffposnick** [comment]
Here's what looks to be going on. Some of these conditions that might be less likely to occur in the real world seem more likely to occur in our test suite, where methods like `fetch()` are mocked out to resolve immediately.

https://github.com/GoogleChrome/workbox/blob/cd993b3f02ab84a10426e466938402780cdc679b/packages/workbox-strategies/src/StaleWhileRevalidate.ts#L107-L117

If `fetchAndCachePromise()` is able to perform both the `fetch()` and the `cacheWrapper.put()` before `cacheWrapper.match()` has a chance to do its cache lookup, then `cacheWrapper.match()` will end up returning the newly `fetch()`ed response instead of the stale response instead.

In other words, the "stale" part of "stale-while-revalidate" will be skipped if the revalidation has already completed by the time the cache lookup happens.

I took a peek back through the implementation in previous Workbox releases, and it looks like we've always gone with that approach, so I guess it was intentional? (I know that we previously had a `fastest` method in `sw-toolbox` that uses a similar approach, and I had *thought* that we had gone with a more deterministic, always use the stale cached result approach in Workbox, but that doesn't seem to be the case.)

So... that's what seems to be going on. We could:

- Change the underlying `StaleWhileRevalidate` class so that it calls `await cacheWrapper.match()` before starting `this._getFromNetwork()` if we want things to be deterministic.
- Keep things as-is, and account for the non-determinism properly in this test, presumably via the mocked behavior.

**Comment by philipwalton** [comment]
Thanks for looking into this. Seems like another option would be for us to wait to put the network response in the cache until after the initial `cache.match()` finishes. That would take a bit more refactoring, but it would let us keep the deterministic behavior without having to delay the network request.

**Comment by jeffposnick** [comment]
I believe this is cleared up in `v6` as part of the strategy class rewrite.
