### ISSUE TITLE
How to add prerendered files to precache-manifest?

### ISSUE THREAD

**Issue by zheeeng** [GoogleChrome/workbox#2147]
After generated sw files, the build processing starts executing prerendering but these files aren't listed in precache-manifest.

I want to solve this problem by using `manifestTransforms`, append the routes to precache-manifest, but be warned that it is unnecessary to use `manifestTransforms` in webpack plugin mode.

I tried combines `globalDirectory`, `globalPattern` and `manifestTransforms` together, but before executing prerendering, there are no corresponding prerendered routes files.

**Comment by zheeeng** [comment]
I searched the solution for a lot of time and seem there is not an introduction to using workbox-webpack-plugin and prerender-spa-plugin together.

If there is a no-limitation way to modify the precache-manifest, it is very appreciated.

**Comment by jeffposnick** [comment]
The current `workbox-webpack-plugin@alpha` allows you to modify the generated precache manifest via `manifestTransforms`: https://github.com/GoogleChrome/workbox/releases/tag/v5.0.0-alpha.0

That being said, if you're adding in entries to the precache manifest, make sure that either
- The `url` field contains a versioned URL, like `/index.abcd1234.js`
- You add in a `revision` field, and it's a value that uniquely identifies the contents of the `url`, and changes whenever the contents change.

Doing that will ensure that the precached copies of the entries you add in will be properly kept up to date.
