### ISSUE TITLE
Service worker failing to install while migrating from V3 to V4.

### ISSUE THREAD

**Issue by sourybunny** [GoogleChrome/workbox#2155]
**Library Affected**:
*workbox-window, workbox-webpack-plugin*

**Browser & Platform**:
*All Browsers*

**Issue or Feature Request Description**:
I'm trying to migrate from v3 to v4.
It works fine locally with http-server but after deploying, I get a `bad precaching response` error and the service worker fails to install.

![image](https://user-images.githubusercontent.com/38237352/62194573-c222b980-b397-11e9-891d-6d10ce30eee6.png)

_A basic part of my code for service-worker.js_

`  workbox.setConfig({
    debug: true
  });
  workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
  workbox.routing.registerNavigationRoute('./index.html')
  workbox.precaching.cleanupOutdatedCaches()`

How do I fix this?
Please help.

**Comment by jeffposnick** [comment]
What you're describing is due to a [breaking change](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0) in how `workbox-precaching` handles HTTP 404 responses:

> `workbox-precaching` will default to confirming that all Responses cached during installation have a non-error (less than 400) HTTP status code. If any Responses have an error code, the install phase will now fail. (The next time the service worker starts up, installation will be re-attempted.) Developers who need to precache Responses that have a 4xx or 5xx status code (e.g., precaching a /not-found.html URL that is served with a status code of 404) can opt-in to allowing that by [passing in](https://github.com/GoogleChrome/workbox/blob/39881c539643f1347fc3860543cbc97a10b8a96a/test/workbox-precaching/node/controllers/test-PrecacheController.mjs#L527-L543) a custom `cacheWillUpdate` plugin to the `workbox.precaching.PrecacheController`'s `install` method.
