### ISSUE TITLE
workbox-webpack-plugin: importScriptsViaChunks also imports the sourcemap

### ISSUE THREAD

**Issue by Fabian-K** [GoogleChrome/workbox#2161]
Hi,

i´m using the new `importScriptsViaChunks` feature of the GenerateSW plugin in 5.0.0-alpha.2. 

```
new GenerateSW({
            swDest: join(OUTPUT_PATH, 'service-worker.js'),
            importScriptsViaChunks: ["sw"],
            inlineWorkboxRuntime: true
        }),
```

This results in the following snippet in the generated service worker. The chunk import looks fine, however the source map is also imported.
```
importScripts("js/sw.61bca7cccf48f0bfc891.js", "js/sw.61bca7cccf48f0bfc891.js.map");
```

Because of the source map is also imported, it fails during runtime with
```
service-worker.js:4144 Refused to execute script from '.../js/sw.8bea19874efa62089cab.js.map' because its MIME type ('application/octet-stream') is not executable
```

**Comment by jeffposnick** [comment]
Thanks for reporting that!

I'm thinking that a simple test for a `.js` extension on each asset in the chunk would probably make the most sense for the next release—I can imagine other, non-JavaScript assets being included in a chunk as well.

**Comment by Andreychikov-Vasiliy** [comment]
```js
        console.log(file) \\ myworker.bundle.js?v=f35a26f7b9767f5a80c0
        console.log(upath.extname(file)) \\ .js?v=f35a26f7b9767f5a80c0
```
I don't now yet why i have *v=f35a26f7b9767f5a80c0* in file name, but option not working

P.S. Maybe `        if (upath.extname(file).match(/\.js\??.*$/)) { ` will be good?
