### ISSUE TITLE
[workbox-window] Waiting event does not trigger sometimes.

### ISSUE THREAD

**Issue by azizhk** [GoogleChrome/workbox#2165]
**Library Affected**: workbox-window
*workbox-sw, workbox-build, etc.*

**Browser & Platform**: Google Chrome Version 75.0.3770.142

**Issue or Feature Request Description**:
*Your request here.* Issue
Steps to reproduce (sometimes)
1. Open tab and register service worker
```js
const wb = new Workbox('/sw.js')
this.wb = wb
this.registration = await wb.register()
wb.addEventListener('waiting', this.onSWWaiting)
```

2. Keep tab open for an hour, lock screen, switch to another tab.
3. Build your service worker again, open your website in a new tab.
4. In the new tab it shows that a new version is available, but it does not trigger in the long open tab.

![Screenshot 2019-08-05 at 3 51 08 PM](https://user-images.githubusercontent.com/5094296/62457773-16170f00-b799-11e9-9881-f005afd0e0c0.png)

I have the following Chrome extensions, I don't think any of Chrome apps are suspending the tab. (The js in the long running tab is still running)
![Screenshot 2019-08-05 at 3 55 30 PM](https://user-images.githubusercontent.com/5094296/62458030-96d60b00-b799-11e9-99e9-1e151c4306ab.png)

**Comment by azizhk** [comment]
Reproducing Repo: https://github.com/azizhk/next-workbox/
Can be deployed on Netlify. (Demo: https://mystifying-almeida-8880f8.netlify.com/)
So you can fork and deploy, open a tab, the run deploy again.

Netlify Commands:
- Build Command: `yarn build`
- Publish Directory: `out`

**Comment by jeffposnick** [comment]
CC: @philipwalton to confirm.

This sounds to me like the scenario described at https://developers.google.com/web/tools/workbox/modules/workbox-window#when_an_unexpected_version_of_the_service_worker_is_found

There's an `externalwaiting` event that `workbox-window` fires when the updated service worker originated from a different tab.

Does that address your issue?

**Comment by azizhk** [comment]
Yup, I guess this must be it.
Is there some heuristic which determines whether `waiting` or `externalwaiting` gets triggered.
Because I had `waiting` triggered on me for some cases even when I installed the SW in a different tab.

**Comment by philipwalton** [comment]
Yeah, the heuristic is here. You can see the comments in the code: https://github.com/GoogleChrome/workbox/blob/4e770a6ad2a95db6d7195defcbc34b2636dc7f84/packages/workbox-window/src/Workbox.ts#L343-L374

If you were able to deploy a new version of the service worker in less than a minute, you'd get a false positive on the heuristic.
