### ISSUE TITLE
Install of workbox-webpack-plugin@next is failing with a rollup error

### ISSUE THREAD

**Issue by calinoracation** [GoogleChrome/workbox#2170]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
webpack / node (8.9.1) / npm (6.9.0)

**Issue or Feature Request Description**:
Attempting to install workbox-webpack-plugin@next or workbox-webpack-plugin@5.0.0-alpha.2 is failing with the following error. After first release this worked at one point but is now failing for both me locally, on a AWS machine and a co-worker's machine.

**_Edit: Verified the failure on CI builds as well_**

```
npm ERR! path /mnt/airlab/repos/hyperloop/node_modules/rollup/dist/bin/rollup.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/mnt/airlab/repos/hyperloop/node_modules/rollup/dist/bin/rollup.js'
npm ERR! enoent This is related to npm not being able to find a file.
```

**Comment by calinoracation** [comment]
https://github.com/rollup/rollup/issues/3029

**Comment by jeffposnick** [comment]
Thanks for flagging this—looks like it's fixed on the Rollup side of things now.

**Comment by calinoracation** [comment]
Yep, confirmed CI and all is resolved now.
