### ISSUE TITLE
The service worker navigation preload request was cancelled before 'preloadResponse' settled

### ISSUE THREAD

**Issue by kevmittal** [GoogleChrome/workbox#2178]
**Library Affected**:
workbox-navigation-preload (4.3.1)

**Browser & Platform**:
Google Chrome 75.0.3770.142 on macOS 10.14.6

**Error Description**:

When using `workbox.navigationPreload.enable()`, it throws this error in the console.

```
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
```

**service-worker.js:**

```javascript
workbox.navigationPreload.enable()

var route = new workbox.routing.NavigationRoute(new workbox.strategies.StaleWhileRevalidate({
  cacheName: 'test',
  plugins: [
    new workbox.expiration.Plugin({
      maxEntries: 1
    })
  ]
})

workbox.routing.registerRoute(route)
```

Am I doing anything wrong?

**Comment by MaxAst** [comment]
having the same issue

**Comment by astrinxit66** [comment]
Hi @kevmittal,
Into `BLACKLIST` you probably have some regexp that match some urls that lead to a navigation request. As you stated those requests to not be handled by workbox's NavigationRoute, you need to handle their preloadResponse somehow. Otherwise they are cancelled.

**Comment by MaxAst** [comment]
Hi, little update from this on our site. This is our current setup, with which we still experience the error:

**Comment by smolnikov** [comment]
Hi,
I've got workbox updated to 5.0.0, and still getting the "The service worker navigation preload request was cancelled" error even with navigationPreload switched off in `GenerateSW` with the following config:
```javascript
return new GenerateSW({
  include: [],
  skipWaiting: false,
  cleanupOutdatedCaches: true,
  navigationPreload: false,
  sourcemap: false,
  runtimeCaching: [
    {
      urlPattern: /\/i18n\/.*\.json$/,
      handler: 'CacheFirst',
      options: {
        expiration: {
          maxEntries: 1,
          maxAgeSeconds: PERIOD_1_DAY_IN_SEC * 30
        },
        cacheName: 'dynamic',
        cacheableResponse: {
          statuses: [0, 200]
        }
      }
    }
  ]
});
```
Does this mean the issue still reproducible in 5.0.0? Are there any workarounds?

**Comment by jeffposnick** [comment]
@smolnikov, I can't think of any reason why you'd see that message if you don't have navigation preload enabled in the current version of your service worker. Are you sure that the new service worker has taken control of the current navigation when you see it? Can you reproduce it when you visit your web app in an Incognito window?

(FWIW, @philipwalton has been going through the `workbox-core` `fetch()` implementation and has, I believe, found a possible reason why this error might be cropping up when using the `StaleWhileRevalidate` strategy for navigation requests.)

**Comment by nitzanashi** [comment]
happens to me as well with this configuration followed by https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offline_page_only
```
const CACHE_NAME = 'offline-app';
const FALLBACK_HTML_URL = '/index.html';

precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', async (event) => {
    await event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.add(
                new Request(FALLBACK_HTML_URL, {credentials: 'same-origin'}),
            )),
    );
});

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        skipWaiting();
    }
});

navigationPreload.enable();

const navigationHandler = async (params) => {
    try {
        return await new NetworkFirst().handle(params);
    } catch (error) {
        return caches.match(FALLBACK_HTML_URL, {
            cacheName: CACHE_NAME,
        });
    }
};

registerRoute(
    new NavigationRoute(navigationHandler, {
        denylist: [
            /token-[^-]*\.json/,
            /\.(?:map)$/,
        ],
    }),
);
```

**Comment by rockeynebhwani** [comment]
@philipwalton is there any update on this? We are also facing same issue

**Comment by laukstein** [comment]
This is a bug in Chrome or in spec. You would see this not only when used Workbox, but in any website using ServiceWorkers Preloaded Response feature, like examples provided by spec, Google and Mozilla. For example https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager and https://developers.google.com/web/updates/2017/02/navigation-preload will fail into same error.

Have anyone seen Chrome open issue for this? @jakearchibald?

Here chromium code pointing to this error message
https://chromium.googlesource.com/chromium/src/+/d894710be3b56a15871376c5979615053dddcd70/content/browser/service_worker/service_worker_browsertest.cc#418

```
const std::string kNavigationPreloadAbortError =
--
  | "The service worker navigation preload request was cancelled before "
  | "'preloadResponse' settled. If you intend to use 'preloadResponse', use "
  | "waitUntil() or respondWith() to wait for the promise to settle.";
```

**Comment by laukstein** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=1031950#c5
> It finds out that the error was caused when skipped event.preloadResponse, for example
> 
> ```
> addEventListener("fetch", event =>
>     event.request.mode === "navigate" &&
>     new URL(event.request.url, location.origin).pathname !== "/test" &&
>     event.respondWith(event.preloadResponse)
> );
> ```
> 
> will result error every time when accessing page /test

Maybe this helps to solve this workbox issue too.

**Comment by nitzanashi** [comment]
Hey @jeffposnick, do you know if this issue has been solved with the new version of workbox, v6?

**Comment by jeffposnick** [comment]
The change alluded to in https://github.com/GoogleChrome/workbox/issues/2178#issuecomment-592030941 has been implemented in [Workbox v6.0.0](https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0) (when using `StaleWhileRevalidate`).

I'm not sure that it will resolve the issue in all its possible manifestations, but it is worth checking to see if you can reproduce it.

**Comment by lizryzhko** [comment]
Hi! I ran into the same issue in workbox-webpack-plugin 6.0.2. Navigation preload never works.
sw.js:

```
import { precacheAndRoute, cleanupOutdatedCaches, addPlugins } from 'workbox-precaching';
import { skipWaiting, clientsClaim, setCacheNameDetails } from 'workbox-core';
import * as navigationPreload from 'workbox-navigation-preload';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { getClientConfig } from './utils/sentry.js';

navigationPreload.enable();

setCacheNameDetails({
    prefix: 'mav-sw'
});

skipWaiting();
clientsClaim();

addPlugins([
    new CacheableResponsePlugin({
        statuses: [200]
    }),
    new ExpirationPlugin({
        purgeOnQuotaError: true,
        maxAgeSeconds: 30 * 24 * 60 * 60
    })
]);

// eslint-disable-next-line no-underscore-dangle
const mainfest = self.__WB_MANIFEST;

precacheAndRoute(mainfest, { cleanURLs: false });

cleanupOutdatedCaches();
```

**Comment by jeffposnick** [comment]
@lizryzhko, I think the issue with your setup is that you're enabling navigation preload but you don't have a runtime route setup that will actually end up using that preloaded response.

The example in the [documentation](https://developers.google.com/web/tools/workbox/modules/workbox-navigation-preload#basic_usage) shows the minimal usage scenario, where navigation preload is enabled **and** a route is registered that match navigation requests and response using a strategy that will read the preloaded response.

(Also, I would really suggest against using `ExpirationPlugin` alongside `workbox-precaching`. I don't think you're going to get the experience you expect, as `workbox-precaching` has its own mechanism for expiring entries. This makes me think we should prioritize https://github.com/GoogleChrome/workbox/issues/2600.)

**Comment by jeffposnick** [comment]
I'm closing this issue for now, as I don't believe there are any reports of this recurring with Workbox v6.x.

**Comment by dflorey** [comment]
I'm still getting this issue when using the `generateSW` plugin most likely due wrong config (?).
`    generateSW({
      swDest: 'dist/edit/sw.js',
      globDirectory: 'dist/',
      mode: "production",
      sourcemap: false,
      navigationPreload: true,
      navigateFallback: "/edit/index.html"
`
I think the plugin takes care to pre-caching the resouces (they show up in workbox-precache), but still geting
`The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle`

**Comment by jeffposnick** [comment]
@dflorey, you'll get that error if you're setting `navigationPreload: true` but not actually creating a route in `runtimeCaching` that will match your navigations and use a strategy like `NetworkFirst` or `NetworkOnly` to consume the navigation preload response.

The workaround would be to not set `navigationPreload: true` unless you explicitly use it via `runtimeCaching`.

**Comment by jeffposnick** [comment]
...and that is actually something that is supposed to be required, if you're using a recent version of `workbox-build`:

https://github.com/GoogleChrome/workbox/blob/2ddef47bbd8a44d3e1ce5e8b13598e022b0b99c7/packages/workbox-build/src/options/partials/generate.js#L82-L85

I'm kind of curious as to how you were able to use `navigationPreload` without `runtimeCaching`.

**Comment by dflorey** [comment]
All I need is a way to make the app available when offline. I've tried
https://github.com/GoogleChrome/workbox/issues/2816
but still get the error (and I guess I need navigationPreload for working offline?).
I've to say it's pretty hard to debug especially when using generateSW I guess.

**Comment by jeffposnick** [comment]
The example in #2816 includes `runtimeCaching`:

```
generateSW({
  // ... other generateSW config options...
  navigationPreload: true,
  runtimeCaching: [{
    urlPattern: ({request}) => request.mode === 'navigate',
    handler: 'NetworkOnly',
    options: {
      precacheFallback: {
        // This URL needs to be included in your precache manifest.
        fallbackURL: '/offline.html',
      },
    },
  }],
});
```

Taking a step back, using navigation preload really isn't the same thing as making your app available when offline.

Could you open a new issue describing the application architecture you're using, along with your desired caching behavior (cache-first for your HTML, fallback to previously cached when offline, a custom offline page, etc.)? Apologies as there are a _lot_ of different ways to configure this behavior, and coming up with the right service worker logic is very dependent on what you actually want to accomplish and how your web app is architected.

**Comment by dflorey** [comment]
Thanks a lot for taking the time. I'll open a different issue describing my app.

**Comment by igdev116** [comment]
If you are working with React JS, seem like you forgot useEffect  :D

**Comment by fisherspoon** [comment]
Hello, I have this trouble on version 6.2.0
<img width="1407" alt="Снимок экрана 2021-09-10 в 13 35 53" src="https://user-images.githubusercontent.com/17007495/132841044-7d5d679a-05c8-447e-ad6a-76f298da66f3.png">


`importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.2.0/workbox-sw.js');
const HTML_CACHE = "html";
const JS_CACHE = "javascript";
const STYLE_CACHE = "stylesheets";
const IMAGE_CACHE = "images";
const FONT_CACHE = "fonts";
const OFFLINE_CACHE_NAME = "offline-html";
const FALLBACK_HTML_URL = "/offline.html";

self.addEventListener('install', async (event) => {
    event.waitUntil(
        caches.open(OFFLINE_CACHE_NAME)
            .then((cache) => {
                cache.add(FALLBACK_HTML_URL)
            })
    );
});

workbox.navigationPreload.enable();

const navigationHandler = async (params) => {
    try {
        // Attempt a network request.
        return await new workbox.strategies.NetworkFirst({
            cacheName: "navigation-and-route",
            plugins: [
                new workbox.expiration.ExpirationPlugin({
                    maxEntries: 20,
                    maxAgeSeconds: 7 * 24 * 60 * 60, // 1 week
                    purgeOnQuotaError: true,
                }),
            ],
        }).handle(params);
    } catch (error) {
        // If it fails, return the cached HTML.
        return caches.match(FALLBACK_HTML_URL, {
            cacheName: OFFLINE_CACHE_NAME,
        });
    }
};

// Register this strategy to handle all navigations.
workbox.routing.registerRoute(
    new workbox.routing.NavigationRoute(navigationHandler, {
        denylist: [
            new RegExp('/admin/'),
        ],
    })
);


self.addEventListener("message", (event) => {
    if (event.data.action === "skipWaiting") {
        self.skipWaiting();
    }
});



// Clean Up Old Precaches
workbox.precaching.cleanupOutdatedCaches();

workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);


workbox.routing.registerRoute(
    ({request, url}) =>
        request.destination === "script" &&
        (url.pathname.startsWith("/assetic/") || url.pathname.startsWith("/sites/") || url.origin === "https://polyfill.io") &&
        !(new RegExp("^https?:\\/\\/.+\\/admin\\/.*").test(request.referrer)),
    new workbox.strategies.StaleWhileRevalidate({
        cacheName: JS_CACHE,
        plugins: [
            new workbox.expiration.ExpirationPlugin({
                maxEntries: 15,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                purgeOnQuotaError: true,
            }),
        ],
    })
);


workbox.routing.registerRoute(
    ({request, url}) =>
        request.destination === "style" &&
        (url.pathname.startsWith("/assetic/")) &&
        !(new RegExp("^https?:\\/\\/.+\\/admin\\/.*").test(request.referrer)),
    new workbox.strategies.StaleWhileRevalidate({
        cacheName: STYLE_CACHE,
        plugins: [
            new workbox.expiration.ExpirationPlugin({
                maxEntries: 15,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                purgeOnQuotaError: true,
            }),
        ],
    })
);



workbox.routing.registerRoute(
    ({request}) =>
        request.destination === "font" &&
        !(new RegExp("^https?:\\/\\/.*\googleapis.*\\/.*").test(request.referrer) ||
            new RegExp("^https?:\\/\\/.+\\/admin\\/.*").test(request.referrer) ||
            new RegExp("^https?:\\/\\/.+\\/bundles\\/.*").test(request.referrer)),
    new workbox.strategies.CacheFirst({
        cacheName: FONT_CACHE,
        plugins: [
            new workbox.expiration.ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
                maxEntries: 10,
                purgeOnQuotaError: true,
            }),
        ],
    })
);


workbox.routing.registerRoute(
    ({request}) => request.destination === "image",
    new workbox.strategies.CacheFirst({
        cacheName: IMAGE_CACHE,
        plugins: [
            // new workbox.cacheableResponse.CacheableResponsePlugin({
            //     statuses: [0, 200]
            // }),
            new workbox.expiration.ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                purgeOnQuotaError: true,
            }),
        ],
    })
);`
