### ISSUE TITLE
Typescript: registerRoute not accepting CacheFirst or StaleWhileRevalidate

### ISSUE THREAD

**Issue by calinoracation** [GoogleChrome/workbox#2180]
**Library Affected**:
workbox-routing

**Browser & Platform**:
developer environment / types

**Issue or Feature Request Description**:
I've converted my service worker to typescript with the proper webworker compilerOption, and am getting the issue below saying the types don't match. The code on the documentation for the alpha release also seems to trigger this as well if it's copied line for line.

```
Argument of type 'CacheFirst' is not assignable to parameter of type 'RouteHandlerCallback'.ts(2345)
```

```ts
// my usage
import { CacheFirst } from 'workbox-strategies/CacheFirst';
import { Plugin as ExpirationPlugin } from 'workbox-expiration/Plugin';
import { registerRoute } from 'workbox-routing/registerRoute';

registerRoute(
  REGEX_FONTS,
  new CacheFirst({
    cacheName: `fonts_${CACHE_CURRENT_VERSION}`,
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: MAX_CACHE_AGE,
      }),
    ],
  }),
);

// from release documentation
registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);
```

**Comment by jeffposnick** [comment]
Do you have any ideas, @philipwalton?

**Comment by philipwalton** [comment]
Looks like this is probably related to this issue: https://github.com/GoogleChrome/workbox/issues/2171#issuecomment-518621911
