### ISSUE TITLE
Confusing/swapped precache manifest using multiple InjectManifest plugins

### ISSUE THREAD

**Issue by calinoracation** [GoogleChrome/workbox#2181]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
build

**Issue or Feature Request Description**:
I'm working on migrating Airbnb's service workers to v5, and we do tons of experiments to test new performance and features and such. We want to do the same for service workers where we A/B test 2 different service worker configurations.

I can create multiple InjectManifest plugins in our webpack config and have them build just fine, but the precache manifest results seem to be swapped to me when that happens. For example, if I have the following 2 InjectManifest entries:

```js
// ...basically noop entry and minimal webpack config
plugins: [
  new InjectManifest({
    swSrc: 'serviceWorker1.ts',
    swDest: '<a_path>/serviceWorker1.js',
  }),
  new InjectManifest({
    swSrc: 'serviceWorker2.ts',
    swDest: '<another_path>/serviceWorker2.js',
  }),
]
```

**Then I can request serviceWorker1.js, and the precache manifest looks like the following, which references serviceWorker2.js, even though it was defined in a different InjectManifest configuration.** Requesting serviceWorker2.js does the inverse and lists serviceWorker1.js in its' precache manifest. If I only have a single InjectManifest, neither one is included in it, which is what I would of expected.

```js
self.__WB_MANIFEST = [
  {
    "revision": "636ffa3ecce445b6bc4354d4cd562cb1",
    "url": "/pwa-guest-loop/static/packages/precheck-6b0df1c6.js"
  },
  {
    "revision": "d2926306946a4a16c44db2854d475566",
    "url": "/pwa-guest-loop/static/packages/serviceWorker2.js"
  }
];
```

**Comment by jeffposnick** [comment]
Thanks for testing out this scenario—I'll look into a fix.

**Comment by jeffposnick** [comment]
(A quick-fix in the meantime would be to add something like `exclude: [/serviceWorker\d.js/]` to each of your `InjectManifest` configs.)

**Comment by calinoracation** [comment]
Thanks for the quick-fix, I'll give that a shot!
