### ISSUE TITLE
Case-sensitivity of header names in cacheableResponse-plugin

### ISSUE THREAD

**Issue by larrifax** [GoogleChrome/workbox#2188]
**Library Affected**:
*workbox.cacheableResponse*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
According to the [HTTP 1.1 standard](https://tools.ietf.org/html/rfc7230#section-3.2), header names are case-insensitive:

> Each header field consists of a case-insensitive field name ...

 The `cacheableResponse` plugin, however, treats header names case sensitive when determining if a response is cacheable:
https://github.com/GoogleChrome/workbox/blob/ccc77b91fd214a47f4421f05980136d23c31b147/packages/workbox-cacheable-response/src/CacheableResponse.ts#L105-L109

It would be nice if the plugin would normalize the configured header name as well as the response header when doing the comparison.

I stumbled across this problem when a change to my backend server's configuration suddenly caused all headers names to be lowercased. My `GenerateSW`'s configuration assumed that the names would be identical to the names used in my backend code:
`                        cacheableResponse: {
                            statuses: [200],
                            headers: { "X-Is-Cacheable": "true" }
                        }`

The workaround is obviously to lowercase the header name in the `cacheableResponse` configuration, but I thought it would be nice if the plugin didn't rely on the casing.

**Comment by jeffposnick** [comment]
Hmmm, so that's weird. The `get()` method on the `Headers` object is supposed to ignore case, so the code in question should work. You can test this out by visiting any web apge and then entering

```
(await fetch('/')).headers.get('cOnTenT-TyPe')
```

in the DevTool's console; the value of the `Content-Type` header should be returned regardless of what case you use.

Are you sure that the failure you saw was due to capitalization?

**Comment by larrifax** [comment]
I've debugged my problem and found that the issue I was seeing originated from a coding error on my side. Seems like I pulled the trigger too early on this one. Sorry about that :) Thanks for responding so quickly!

**Comment by jeffposnick** [comment]
No worries! Glad you got it sorted.
