### ISSUE TITLE
v4 webpack injectmanifest on build generates assets (css, fonts) but next sw.js update assets disappears from precache

### ISSUE THREAD

**Issue by Syrou** [GoogleChrome/workbox#2190]
*workbox-webpack-plugin.^4.3.1

Browser & Platform:
chrome,"webpack": "^4.39.1",

Using v4 webpack injectmanifest, on build webpack, generates scripts and assets (css, fonts) and adds it to the precache-manifest and when loading the page with `webpack-dev-server` the files are visible in the workbox-preache-v2

Using `webpack-dev-server` to serve the content, next sw.js code update (With Live Reload), assets (css, fonts) disappears from workbox-precache-v2 while scripts remain

It feels like it has something to do with https://github.com/GoogleChrome/workbox/issues/1428 but it seems like it should be in, so it does not make any sense

Does anyone have any idea why some assets gets removed from workbox-precache-v2
 when sw.js recompiles/updates while js and html files remains?

**Comment by jeffposnick** [comment]
Can you give things a try with our current alpha release, via `install --save-dev workbox-webpack-plugin@next`? (Check out the [release notes here](https://github.com/GoogleChrome/workbox/releases).)

The webpack plugin has been rewritten substantially, and my hope is that it will either work as expected, or we'll have an easier time debugging what's going wrong. It's not likely that we'll be making substantial changes to the v4 codebase at this time.
