### ISSUE TITLE
Service worker update delayed 60 seconds if Firestore used

### ISSUE THREAD

**Issue by CaptainCodeman** [GoogleChrome/workbox#2192]
**Library Affected**:
workbox-window 5.0.0-alpha.2
firebase-sdk-js 6.4.0

**Browser & Platform**:
Chrome 76

**Issue or Feature Request Description**:
Given a perfectly working workbox setup which displays a prompt to update before reloading the page, adding firestore and making a call to load some data causes the page reload to be delayed by exactly 60 seconds.

Here's an output of the log which shows the 60 second delay occuring:
<img width="1099" alt="Screen Shot 2019-08-19 at 1 12 13 PM" src="https://user-images.githubusercontent.com/304910/63306950-df1d1f00-c2a9-11e9-9921-7fc39d6804aa.png">

Here's the workbox code in index.html
```
<script type="module">
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', async () => {
      const { Workbox } = await import('https://storage.googleapis.com/workbox-cdn/releases/5.0.0-alpha.2/workbox-window.dev.mjs')
      const wb = new Workbox('/sw.js')

      function activateUpdate() {
        wb.addEventListener('controlling', _ => window.location.reload())
        wb.messageSW({type: 'SKIP_WAITING'})
      }

      function promptToUpdate() {
        if (window.confirm('update available')) activateUpdate()
      }

      wb.addEventListener('waiting', promptToUpdate)

      wb.register()
    })
  }
</script>
```

Code also added to index.html to trigger the 60 second reload delay:
```
<script src="https://www.gstatic.com/firebasejs/6.4.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.4.0/firebase-firestore.js"></script>
<script>
  const firebaseConfig = {
    // some firebase config
  };
  firebase.initializeApp(firebaseConfig);

  const fs = firebase.firestore()
  fs.doc(`/collection/id`).get().then(doc => console.log(doc.data()))
</script>
```

Without that data loading the service worker update happens immediately as expected. The delay happens with the `controlling` event being raised.

The service worker script is _not_ being renamed (seemed to be the cause of similar issues).

**Comment by jeffposnick** [comment]
There's some specific timeout-related code at

https://github.com/GoogleChrome/workbox/blob/5a8b0315b3a219ceecec61c78c7790332bb57854/packages/workbox-window/src/Workbox.ts#L407-L432

that *might* explain some of what you're seeing.

@philipwalton, do you have any insight as to what specifically might be causing the delay?

**Comment by CaptainCodeman** [comment]
I wonder if the firebase sdk is swallowing some message, so then the sw update falls back to detecting the timeout? That was as far as I got once I'd stripped the app down to it being firestore triggering the behavior.

**Comment by philipwalton** [comment]
@CaptainCodeman can you make a demo of this, including your service worker? I think it'd be helpful to just test it out and see if that reveals anything I may be missing now.

**Comment by CaptainCodeman** [comment]
This should demonstrate it:
https://captaincodeman-experiment.firebaseapp.com/

It even stops the "skipWaiting" link in chrome dev-tools from doing anything

**Comment by CaptainCodeman** [comment]
I figured it out...

I had caching for `fonts.googleapis.com` and `storage.googleapis.com` using the URL pattern: `/^https:\/\/\w+\.googleapis\.com\//`

But this also included `firestore.googleapis.com` which is what was causing it to have to wait for a timeout. I don't know if this means it's something in the workbox caching that needs to handle whatever firestore is doing - possibly some long-polling connection?

Changing the pattern to the more specific `/^https:\/\/(fonts|storage)\.googleapis\.com\//` which excluded firestore fixed it.

**Comment by philipwalton** [comment]
I'm glad you figured it out. Note we do have a [`networkTimeoutSeconds`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.strategies.NetworkFirst) option on the `NetworkFirst` strategy, though I'm not sure if that would have made sense to use here anyway.

If a route is matching a URL you're not intending it to, I'm not sure if it makes sense for Workbox to add code to handle that. I understand you're just asking for something that would have made this easier to debug, but we already do log what routes are being matched to the console in dev mode, and I think that's about as much as we'd reasonably want to do.
