### ISSUE TITLE
Cannot read property 'add' of undefined on workbox-webpack-plugin v5

### ISSUE THREAD

**Issue by lukas2005** [GoogleChrome/workbox#2194]
**Library Affected**:
workbox-webpack-plugin v5.0.0-alpha.0 & 1 & 2

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
When building I get the error:
```
 ERROR  Failed to compile with 1 errors2:48:35 PM

Cannot read property 'add' of undefined

 ERROR  Build failed with errors.
```
This only happens when I include any of the workbox plugins
I'm using Vue CLI but not the PWA plugin because I need some of the features/fixes from v5.0.0-alpha.2

**Comment by jeffposnick** [comment]
Can you provide some more info? The easiest approach would be if you could upload a reproduction of your failing build to GitHub, or zip it into an archive and link to it.

If you can't do that for some reason, can you provide the full logged output of the `webpack` build command, and let me know which version of `webpack` you're using?

**Comment by lukas2005** [comment]
```
> Executing task: npm run build:web <


> anchor-chat@0.1.0 build:web /home/lukas2005/Dokumenty/Projects/Anchor/web
> vue-cli-service build --mode production.web

starting webConfig

⠙  Building for production.web...clean-webpack-plugin: /home/lukas2005/Dokumenty/Projects/Anchor/web/dist/**/* has been removed.
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
⠇  Building for production.web...

 ERROR  Failed to compile with 1 errors                                                                                                                                            10:30:56 PM

 error  

Cannot read property 'add' of undefined

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anchor-chat@0.1.0 build:web: `vue-cli-service build --mode production.web`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anchor-chat@0.1.0 build:web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lukas2005/.npm/_logs/2019-08-21T20_30_57_100Z-debug.log
The terminal process terminated with exit code: 1
```
I'm using Vue CLI 3.10.0 which appears to be using Webpack 4.28.4

**Comment by jeffposnick** [comment]
How are you extending/overriding the `webpack.config.js` that `vue-cli-service build` ends up using to include the v5 version of `workbox-webpack-plugin`?

**Comment by lukas2005** [comment]
I just added the plugin in the `vue.config.js` file:
```js
const workbox = require("workbox-webpack-plugin");

const path = require("path")

module.exports = {
	configureWebpack: {
		plugins: [
			new workbox.GenerateSW({
				//importWorkboxFrom: 'disabled',
				//swSrc: path.join("src", "sw.ts"),
				swDest: "service-worker.js"
			})
		]
	}
}

**Comment by jeffposnick** [comment]
Thanks—I can reproduce the issue now.

The code that fails is https://github.com/GoogleChrome/workbox/blob/f36e6bdc8859fed77ea59adab439d00d8e48cc90/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L67-L71, and it fails when `assetName` is `css/app.e2713bb0.css.map`.

I'm not 100% sure why this failure happens, but I'm assuming it's because of something having to do with how the CSS sourcemaps are generated, and how that interacts with the list of assets that webpack knows about.

I'll just put in an additional check to guard against this condition.
