### ISSUE TITLE
There are any plans to create a Rollup plugin?

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/workbox#2196]
Simple question: There are any plans to create a Rollup plugin?

Thanks in advance!

**Comment by jeffposnick** [comment]
No specific plans, but using the `workbox-build` module or `workbox-cli` after running a Rollup build is fairly straightforward. We've got some examples of doing that if you'd like a pointer.

The main reason I'm not sure that a Rollup plugin makes sense is that, unlike with `webpack`, I don't think it's common to have Rollup process your *entire* set of local files, including HTML, images, etc. And if Rollup doesn't know about some of your local files, it wouldn't be clear how to get a Workbox Rollup plugin to precache those files for you.

I'm going to close this for now, but we can revisit if you have a specific use case for a Rollup plugin a) can't be solved by just running Workbox after your Rollup build and b) addresses the issue of Rollup not knowing about all your files.

**Comment by abdonrd** [comment]
Got it, thanks for the quick answer @jeffposnick!
