### ISSUE TITLE
The workbox-window message listener can report the wrong service worker

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2201]
**Library Affected**:
*workbox-window*

The current logic that dispatches `message` events makes the assumption that the service worker sending the message is the same as the instances "own" service worker, but that's not necessarily the case since the listener is added to the `ServiceWorkerContainer`: https://github.com/GoogleChrome/workbox/blob/ae80e3958c79cb93f4c21bca63cd6e81f7878536/packages/workbox-window/src/Workbox.ts#L493-L504

At minimum we should update the code to set the `.sw` property to `originalEvent.source`, but it might also be worth considering whether we want to restrict messages to be just those sent via the instances registered service worker.

We could potentially even introduce an `externalmessage` event to be consistent with the other `external*` lifecycle events, but I'm not sure this is really necessary.

Thoughts?

**Comment by jeffposnick** [comment]
Fixing the value in `sw`, and allowing developers to use that to filter if needed, seems like a reasonable approach with minimal downside.

My intuition is that there may be more scenarios in which the `window` client doesn't care about which SW the message comes from, and that creating a brand new event that they had to opt-in to listening to seems like overkill (unless actual developers let us know that they want that behavior).
