### ISSUE TITLE
Expiration not working - no way to ignore vary header

### ISSUE THREAD

**Issue by jazdw** [GoogleChrome/workbox#2206]
**Library Affected**:
workbox-sw I think

**Browser & Platform**:
Chrome 76.0.3809.100

**Issue or Feature Request Description**:
I'm not sure if this is an issue with my configuration.

I am seeing a message like `Expired 1 entry and removed it from the 'module-resources' cache.` in my console indicating that the entry should be removed from the cache. However it seem that `CacheExpiration.mjs` is calling `cache.delete()` with the absolute URL (with https and domain name) whereas the cache key is the relative URL (without the https and domain name).

Service worker (generated/injected by Webpack plugin):

```js
importScripts("/ui/vendor/precache-manifest.0bda9a9248d013fd973b8db7b30cc6ef.js", "/ui/vendor/workbox-v4.3.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "/ui/vendor/workbox-v4.3.1"});

workbox.setConfig({
    debug: true
});

workbox.core.skipWaiting();
workbox.core.clientsClaim();

const moduleResourcesCacheName = 'module-resources';

workbox.routing.registerRoute(
    /\/modules\/[\w-]+\/web\/.*\?v=.+/,
    new workbox.strategies.CacheFirst({
        cacheName: moduleResourcesCacheName,
        plugins: [
            new workbox.expiration.Plugin({
                maxEntries: 100
            })
        ]
    })
);

workbox.precaching.precacheAndRoute(self.__precacheManifest, {
    directoryIndex: null,
    cleanUrls: false
});

workbox.routing.registerNavigationRoute(
    workbox.precaching.getCacheKeyForURL('/ui/index.html')
);
```

The `cache-entries` DB contains the absolute URLs. The names in the `module-resources` cache storage are all relative URLs.

Is this user error or a bug? I have also noticed that adding a `^` to the start of the RegExp makes it not match, which seems contrary to [what the documentation says](https://developers.google.com/web/tools/workbox/modules/workbox-routing#how_to_register_a_regular_expression_route) for same origins.

**Comment by philipwalton** [comment]
Thanks for the suggestion. I think it may make sense to add this as a configuration option on the expiration plugin. Perhaps something like:

```js
new ExpirationPlugin({
  maxEntries: 100,
  deleteOptions: {
    ignoreVary: true,
  },
});
```

@jeffposnick what do you think? And in terms of naming, would you prefer `deleteOptions` or `matchOptions` (for consistency)?

**Comment by jeffposnick** [comment]
Sure, that makes sense.

The [underlying](https://w3c.github.io/ServiceWorker/#dictdef-cachequeryoptions) web platform `dictionary` name is `CacheQueryOptions`, but since we went with `matchOptions` elsewhere in Workbox already, I'd say we should just stick with that name here.

I'm not sure if this would make the cut for v5.0.0, or whether it would be something we'd add in the following minor/patch release.
