### ISSUE TITLE
Add support for deferred/conditional registration in workbox-window

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2216]
**Library Affected**:
*workbox-window*

After discussion with @azizhk in https://github.com/GoogleChrome/workbox/pull/2209#issuecomment-527223148 and then with @jeffposnick. We think it makes sense to update `workbox-window` to better support use cases around deferred or conditional registration.

Currently, the library runs most of its initialization logic in the `register()` method (including adding lifecycle event listeners), so if a developer doesn't call `register()` right away, they may miss lifecycle events when an updated version of the service worker is found.

With a slight refactoring and putting most of the initialization logic in the constructor, we should be able to support this.

**Comment by azizhk** [comment]
I don't think moving the logic from register to constructor would help.
In my example I would create the workbox instance also quite late.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
