### ISSUE TITLE
Allow dynamic matching in NavigationRoute

### ISSUE THREAD

**Issue by ezzatron** [GoogleChrome/workbox#2224]
**Library Affected**:
*workbox-routing v5*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:

I'd like to submit a PR for adding a new `match` option to [`NavigationRoute`]'s `options` parameter.

The use case for this feature is integration with existing routing libraries. It can be quite difficult to reduce routing library configurations to a static list of regular expressions in order to utilize the existing `whitelist` option.

By allowing users to pass in their own [`matchCallback`] via a `match` option, the decision about whether the `NavigationRoute` should respond to the request could be controlled by the user's existing routing solution.

As an example, this would become possible:

```js
import {createHandlerForURL} from 'workbox-precaching'
import {NavigationRoute, registerRoute} from 'workbox-routing'

// assume a router5 router, for the sake of example
import router from './path/to/router.js'

const handler = createHandlerForURL('/app-shell.html');
const navigationRoute = new NavigationRoute(handler, {
  match ({url}) {
    return router.matchPath(url.pathname);
  },
});
registerRoute(navigationRoute);
```

In terms of actual implementation, I'd probably expect such an option to apply only after the application of the `whitelist` and `blacklist` options.

[`NavigationRoute`]: https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.NavigationRoute
[`matchCallback`]: https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~matchCallback

**Comment by jeffposnick** [comment]
`NavigationRoute` is [primarily a shorthand](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-routing/src/NavigationRoute.ts#L91-L94) for checking whether `event.request.mode === 'navigate'` (along with some extra logic for the allow/blocklist). You can accomplish what you describe without using `NavigationRoute`, and instead using a custom [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route.html#~matchCallback):

```
const customNavigationMatch = ({event, request, url}) => {
  // Bail early if this isn't a navigation.
  if (request.mode !== 'navigate') {
    return false;
  }

  // Examine url and return true/false based on routing rules:
  return router.matchPath(url.pathname);
};

const appShellHandler = createHandlerForURL('/app-shell.html');

registerRoute(customNavigationMatch, appShellHandler);
```
