### ISSUE TITLE
Webpack-compiled InjectManifest service worker balloons from 8K to 28K when HotModuleReplacementPlugin is also in use

### ISSUE THREAD

**Issue by ezzatron** [GoogleChrome/workbox#2225]
**Library Affected**:
*workbox-webpack-plugin v5 beta*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:

When using the v5 beta version of `workbox-webpack-plugin` to compile a service worker using the `InjectManifest` Webpack plugin, a significant amount of bloat (around 20KB) is added to the service worker when the [`HotModuleReplacementPlugin`] is also in use.

The cause of this seems to be that HMR changes Webpack's "chunk template". The template change can be stopped by setting `compilation.hotUpdateChunkTemplate = false` inside a Webpack plugin:

```js
new InjectManifest({
  swSrc: './path/to/sw.js',
  webpackCompilationPlugins: [
    {
      apply (compiler) {
        compiler.hooks.thisCompilation.tap('InjectManifest', compilation => {
          compilation.hotUpdateChunkTemplate = false
        })
      },
    },
  ],
})
```

I don't actually know whether it's feasible to support hot module replacement in a service worker. But assuming that it's not, or at least that Workbox has no intention of implementing support for HMR, perhaps this is something that `workbox-webpack-plugin` should handle automatically?

I've put together a gist demonstrating the output both with and without the hot update chunk template: https://gist.github.com/ezzatron/2a38b49306599228c3d07bc272d681c5

In my case, the (development mode) output shrunk from 28KB to 8KB with the above "fix".

[`HotModuleReplacementPlugin`]: https://webpack.js.org/plugins/hot-module-replacement-plugin/

**Comment by jeffposnick** [comment]
Hello!

I am concerned that I can't find any reference to that internal `hotUpdateChunkTemplate` property in the public `webpack` documentation, and additionally https://github.com/webpack/webpack/pull/8525 makes me think that it might be going away in a future release.

So setting `compilation.hotUpdateChunkTemplate = false;` doesn't sound like it's future-proof.

How important is this change, do you think? HMR by definition is not meant to be used in production deployment scenarios, and an optimization to remove `webpack` cruft from development builds doesn't sound like it would make much of an impact.

(If you were  able to find some guidance about an officially documented API that could accomplish something similar, I'd be happy to reconsider.)

**Comment by ezzatron** [comment]
You're right, unless this actually causes an error it's probably not a significant issue. I'll have to fire up my project and make sure it runs smoothly with HMR enabled, and without this "fix".

This came about because I was tossing up between using `workbox-webpack-plugin` v5 and `service-worker-loader`, and I noticed in their README they have [this section](https://github.com/mohsen1/service-worker-loader#hot-module-replacement):

> ## Hot Module Replacement
>
> Webpack's HMR did not designed for ServiceWorkers, so need to disable HMR for ServiceWorkers. You can do it with [`hmr-filter-webpack-plugin` plugin](https://github.com/TrigenSoftware/hmr-filter-webpack-plugin#usage).

Then when I was poking around the compiled output from `workbox-webpack-plugin` and saw a whole bunch of HMR code that's just sitting there dormant, it seemed like a good idea to remove it.

**Comment by jeffposnick** [comment]
Thanks for the context—we can revisit if there's buggy behavior or an otherwise serious issue introduced by the HMR cruft.
