### ISSUE TITLE
Use workbox in a custom instant messaging protocol 

### ISSUE THREAD

**Issue by JinJieTan** [GoogleChrome/workbox#2227]
Use workbox in a custom instant messaging protocol

in Electron ,

![image](https://user-images.githubusercontent.com/47209029/65219905-2c302300-daec-11e9-9e8e-1154d4b8ea08.png)

```
const WorkboxPlugin = require('workbox-webpack-plugin');

    new WorkboxPlugin.GenerateSW({
        clientsClaim: true,
        skipWaiting: true,
        importWorkboxFrom: 'local',
        include: [/\.js$/, /\.css$/, /\.html$/, /\.jpg/, /\.jpeg/, /\.svg/, /\.webp/, /\.png/],
      }),
```

'workbox' has been successfully used. The file appears after packaging, but serverce worker is not installed
![image](https://user-images.githubusercontent.com/47209029/65220009-66012980-daec-11e9-814c-10e45fde7b02.png)

We are using our own defined instant messaging protocol. Can we use workbox in Electron?

**Comment by philipwalton** [comment]
Can you provide more details around what's not working? How do you know the service worker isn't being installed? I are you registering it from in your main page code? Are you getting an error when registering it?

**Comment by JinJieTan** [comment]
I usually use workbox-webpack-plugin, which will be registered, but this time  not . The packaged file has workbox, I am very confused, is it my communication protocol

**Comment by jeffposnick** [comment]
In general, if you're loading `index.html` using a `file:///` URL scheme (inside of Electron), I wouldn't expect anything related to service workers to be functional. A service worker can only be registered if the page performing the registration is accessed via a [secure origin](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features).
