### ISSUE TITLE
[Request] Cache expiration based on a time of the day.

### ISSUE THREAD

**Issue by laurentdebricon** [GoogleChrome/workbox#2238]
Hello,
i have data that is invalid everyday at 9am. So far i have setup a 1 day cache first, but it is not perfect, because if a user came at 23:00 the day before, he will have the invalid data from 9 to 23:00 the next day.

Is it possible to do ?

**Comment by jeffposnick** [comment]
I'm not 100% sure what the time-related logic would look like for your specific use case, but in general, the [`cachedResponseWillBeUsed` lifecycle callback](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) gives you a chance to inspect a cached response prior to its use, and return `null` if it should be considered invalid.

You can use this like:

```js
const customExpirationPlugin = {
  cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event}) => {
    // I'm assuming that this is what you want? Customize as needed.
    const dateHeader = cachedResponse.headers.get('date');
    if (dateHeader) {
      const parsedDate = new Date(dateHeader);
      // Check whether parsedDate meets some criteria?
      if (...) {
        // If whatever your criteria for expiration is met, return null.
        return null;
      }
    }

    // Otherwise, consider the cached response "fresh" and return it.
    return cachedResponse;
  },
};

const cacheFirstStrategy = new CacheFirst({
  cacheName: '...',
  plugins: [customExpirationPlugin],
  ...
});
```
