### ISSUE TITLE
Missing manifest entries with webpack watch mode recompilations

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2240]
@arackaf noted an issue that could roughly be reprduced by:

- Cloning https://github.com/arackaf/booklist/
- From the `react/` subdirectory, running `npm run watch`.
- Checking out the `temp-sw` branch, triggering a recompilation.

At that point, at least the `index.html` (generated by `html-webpack-plugin`), and maybe some other assets are missing from the re-generated precache manifest.

**Comment by jeffposnick** [comment]
(This is actually #1790, which unfortunately was overlooked leading up to the v5 release, but which should get some attention soon.)

**Comment by arackaf** [comment]
In the outside chance anyone needs those repro steps above, use `special/pre-temp-sw` instead of master, above, for the "before" step, then switch to temp-sw to trigger the rebuild.
