### ISSUE TITLE
Unable to cache a POST request

### ISSUE THREAD

**Issue by magicry** [GoogleChrome/workbox#2258]
Hi, please excuse my lack of knowledge as just starting mycoding journey. 

I am having the same error occur in my console relating to the above 

the error is - 

```
cacheWrapper.mjs:97 Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at Object.put (cacheWrapper.mjs:97)
put @ cacheWrapper.mjs:97
```

I have read that background sync might solve this but cant get it to work, i have the following code in my SW file 

```
const bgSyncPlugin = new workbox.backgroundSync.Plugin('myQueueName', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

workbox.routing.registerRoute(
  /\/api\/.*\/*.json/,
  new workbox.strategies.NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);
```

**Comment by jeffposnick** [comment]
That code looks fine. (There's more context in https://github.com/GoogleChrome/workbox/issues/1584)

If you are using `new workbox.strategies.NetworkOnly` as the handler for your route, there should not be any attempt to call `put()`, so I think your error is coming from another portion of your service worker file.

Can you share your entire service worker, and confirm which URL is being requested when you encounter this error message?

**Comment by magicry** [comment]
Hi Jeff, thank you.

SW is attached.  URL is - https://storage.googleapis.com/workbox-cdn/releases/_private/cacheWrapper.mjs 

[sw.txt](https://github.com/GoogleChrome/workbox/files/3756120/sw.txt)

**Comment by magicry** [comment]
say error comes in line 97 or cacheWrapper URL

**Comment by jeffposnick** [comment]
Any of those routes which use `NetworkFirst` might be triggering this error. `NetworkFirst` will, under the hood, attempt to store the request/response combination in a local cache, and that attempt will fail if your request has a `mode` of `POST`.

If you could say which URL your web app is `POST`ing to, I could give some advice as to which route to change.

(Also, your 

```
workbox.routing.registerRoute(
  '/application/templates/sidebar.php',
  '/application/templates/admin-header.php',
  '/application/templates/admin-footer.php',
  '/application/templates/frontend-footer.php',
  '/application/templates/frontend-footer.php',
  '/application/index.php',
  new workbox.strategies.NetworkFirst()
  );
```

route is invalid, as you can only list one parameter as the `matchHandler` when calling `registerRoute`. Listing a whole bunch of strings won't work.)

**Comment by magicry** [comment]
ok, i believe the error is coming from the  "importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js');"    line

with regards to the register route, so i need a handler for each string?

**Comment by jeffposnick** [comment]
It's not coming from that line—that line is responsible for importing the Workbox runtime code, which in turn allows you to use Workbox to define your routes and caching behavior.

An error like that would only come from once you actually start running your service worker and it intercepts a `POST` request. What I'd need from you is the URL of that `POST` request. You should be able to see it from, e.g., the [Network panel in Chrome's DevTools](https://developers.google.com/web/tools/chrome-devtools/network).

You can use a [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) in place of that array of strings. For example, `new RegExp('/application/.*\\.php')` seems like it may work for you, if you really want to match all of those URLs.

**Comment by magicry** [comment]
apologies for my lack of knowledge on this.   See screenshot of the console and network panel. 

what are you looking for on here?   

URL's i can see are 
https://babsdemo.co.uk/application/message-popup.php
https://babsdemo.co.uk/application/ajax/counter.php

![image](https://user-images.githubusercontent.com/56658576/67300811-7d19a980-f4e6-11e9-8bc9-a3d0808c8fa8.png)

**Comment by jeffposnick** [comment]
There's a "Method" option that you could check to get the `method` logged in DevTools:

<img width="243" alt="Screen Shot 2019-10-22 at 11 52 42 AM" src="https://user-images.githubusercontent.com/1749548/67304892-82fd9380-f4c2-11e9-9c68-d09df9c1642e.png">

If I had to guess, based on your traffic, which of those requests were a `POST` I'd say it's likely for `counter.php` (since doing things that involve changing state, like incrementing a counter, are usually done via a `POST`).

**Comment by magicry** [comment]
ok, so both are POST

![image](https://user-images.githubusercontent.com/56658576/67316709-db538600-f500-11e9-976a-9a7bd5a9de15.png)

**Comment by magicry** [comment]
Its starting to cause network failures now - 

![image](https://user-images.githubusercontent.com/56658576/67372719-3e333480-f576-11e9-99ec-ead0d0f61ad6.png)

**Comment by jeffposnick** [comment]
I would recommend removing

```
workbox.routing.setDefaultHandler(
  new workbox.strategies.NetworkFirst()
);
```

That ends up picking up your `POST` requests as well and caching them, and you don't want that.

If you want to set up a route that specifically does match the `POST` requests and uses the background sync plugin, that's possible... but I don't really think it's necessary for your use case. You wouldn't want to sync a failed login `POST` request, for instance.

**Comment by MrCsabaToth** [comment]
@jeffposnick in my case I have a Jekyll based AMP website so my hands are really tied when fixing this. I identified that the only POST request going out to Google Tag Manager (`https://www.googletagmanager.com/gtag/amp?__amp_source_origin=https%3A%2F%2Fcsaba.page`) and even that is indirectly generated by the `amp-analytics` component. My plan was to apply a `networkOnly` strategy for that domain, but I still get the error:
```
workbox.routing.registerRoute(
  /^https?:\/\/www\.googletagmanager\.com/,
  workbox.strategies.networkOnly()
)
```
What could be still a reason for the service worker to try to cache a POST request? I thought networkOnly will disable any caching. Ref: https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/-/issues/26
