### ISSUE TITLE
webpack plugin's InjectManifest breaks when mode: 'development"

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2263]
**Library Affected**:
*workbox-webpack-plugin*

In v5's `InjectManifest` plugin, we're doing string injection of the serialized manifest, and the presence of `"` characters in the JSON-ified manifest runs amuck with the `"` characters used in the webpack-bundled source code when `mode: 'development'`. (There are a bunch of `eval("...")` statements.)

I *think* that just swapping the `"` for `'` should be a reasonable fix, as webpack seems to use `"` pretty consistently. An alternatively approach would be to swap `"` for `\"`, but I'm less happy with that, because then the code would be invalid when it's not wrapped in `eval("...")`.

We also need a test specifically of `mode: 'development'` for the `InjectManifest` plugin to confirm the output is valid JavaScript.

**Comment by undermuz** [comment]
I have an error because of this fix: 
`Uncaught SyntaxError: missing ) after argument list`

When i set devtool = "nosources-cheap-module-source-map" and disable optimization.minimize, this no error occurs
