### ISSUE TITLE
Make it possible to define the full path in copyLibraries

### ISSUE THREAD

**Issue by hosv1018** [GoogleChrome/workbox#2265]
**Library Affected**:
*workbox-cli*, *(workbox-build)*

**Browser & Platform**:
*all browsers*

**Issue**:
I am using workbox for precaching in a business web application with React and AngularJS. We have many customers for our software, that run it via intranet, so I have to serve the workbox libraries from local files. 

I use _workbox-build_ with _injectManifest_ to create the service-worker in our Gulp-build-process. The workbox-library files are generated during the build-process by using _copyLibraries_ from _workbox-cli._ 

The problem is, that the output folder of copyLibraries mandatorily contains the version number of workbox, e.g. “workbox-v4.3.1”. Which means, I can’t reference the workbox-folder in the _modulePathPrefix_-configuration of my service-worker without committing to a specific version number, that has to be manually changed when upgrading to a new version of workbox.

Currently we use a workaround for this issue is by copying the files with two Gulp-tasks.

1) Execute the command “workbox copyLibraries build/“ to copy the workbox-files to a temporary folder, that is deleted at the end of the build-process. This copies the workbox-files to “build/workbox-v4.3.1”.

2) Copy the files from “build/workbox-v4.3.1” to the final folder “dist/app/workbox”.
```
gulp
.src('build/workbox-*/*')
.pipe(flatten()) // extracts the files from the folder "workbox-v4.3.1"
.pipe(gulp.dest('dist/app/workbox'))
```

**Possible Solution:** To avoid this workaround, it would be great, if there was an option to define the full path for the copyLibraries-command of workbox-cli, instead of just the path where the “workbox-vX.Y.Z”-folder will be copied to.

For example, there could be an additional flag that can be set in the command, that specifies that you are defining the full path, that points directly to the library-files. 

_Example:_ “workbox copyLibraries build/workbox/ --fullpath”.
This will copy the library-files directly into the folder “build/workbox”.

Is there already some easy solution to achieve this behaviour, that I somehow missed or is it intended to bind developers stronger to a certain version of workbox?

**Comment by Schleichmarder** [comment]
The problem is based in:
[https://github.com/GoogleChrome/workbox/blob/ecb987fedeb90954012f17791afe6829b1989d10/packages/workbox-build/src/lib/copy-workbox-libraries.js#L39]

`module.exports = async (destDirectory) => {
  const thisPkg = require('../../package.json');
  // Use the version string from workbox-build in the name of the parent
  // directory. This should be safe, because lerna will bump workbox-build's
  // pkg.version whenever one of the dependent libraries gets bumped, and we
  // care about versioning the dependent libraries.
  const workboxDirectoryName = `workbox-v${thisPkg.version}`;
  const workboxDirectoryPath = upath.join(destDirectory, workboxDirectoryName);
  await fse.ensureDir(workboxDirectoryPath);
...`

by replacing the section with: 
`module.exports = async (workboxDirectoryPath) => {
  await fse.ensureDir(workboxDirectoryPath);
...`

the issue could be solved.

**Comment by jeffposnick** [comment]
The underlying reason for this was that, until very recently, not all browsers would check `importScripts()` resources for updates and trigger the service worker update flow. (Chrome didn't until [last month](https://developers.google.com/web/updates/2019/09/fresher-sw) with Chrome 78.) So if the URL that you used with `importScripts()` didn't contain any versioning info that would be bumped each time you upgraded your Workbox deployment, users of your service worker would be stuck on older versions of Workbox indefinitely.

So I really would not attempt to work around the versioning info in the `importScripts()` URL.

That being said, if you update to Workbox v5 (currently in [release candidate](https://github.com/GoogleChrome/workbox/releases)), the default behavior in `generateSW` mode is to create custom, local bundles of the Workbox (and those bundles contain hashes as part of their URLs for versioning info). If you use it in `importScripts` mode it's up to you to create your own local bundles, but you can do that by bundling the JavaScript/TypeScript modules directly using [Rollup/webpack/etc](https://developers.google.com/web/tools/workbox/guides/using-bundlers).

Local bundles are the direction we're going with moving forward, so there's not going to be any changes to the `copyLibraries` flow in the v4 branch.
