### ISSUE TITLE
Bundling workbox via webpack

### ISSUE THREAD

**Issue by gknapp** [GoogleChrome/workbox#2266]
**Library Affected**:
workbox-build

**Browser & Platform**:
Google Chrome v77 on Windows 10.

I'm using create-react-app 3.2.0 (which bundles webpack 4.41.0).

Up to this point I've been pull workbox from the Google CDN using `importScripts()`. However, this is no use when my PWA is offline. I'd like to bundle workbox using webpack. I've worked through your docs but can't see where I'm supposed to import workbox modules (import isn't supported in a service worker?).

https://developers.google.com/web/tools/workbox/guides/using-bundlers

![image](https://user-images.githubusercontent.com/143027/67782602-ebb7b380-fa60-11e9-9ffe-a1b765ba86c8.png)

However, these import statements run in Service Worker scope?

![image](https://user-images.githubusercontent.com/143027/67782068-371d9200-fa60-11e9-8952-4747e30dc92c.png)

I'm using `workbox-build` and placing the `import ... from` statements in my `template.js`.

![image](https://user-images.githubusercontent.com/143027/67782227-6cc27b00-fa60-11e9-8a87-2e4221f061f3.png)

My `build.js`:

```js
const workbox = require("workbox-build");
  workbox.injectManifest({
    swSrc: "src/ServiceWorker/template.js",
    swDest: "build/sw.js",
    globDirectory: "build",
    globPatterns: [
      "**\/*.{css,html,ico,png,svg,xml}",
      "static\/**\/*.chunk.{js,css}",
      "static\/js\/*.js"
    ]
  }).then(({ count, size, warnings }) => {
    warnings.forEach(console.warn);
    console.log(
      `${count} files will be precached (${Math.floor(size / 1024)} KB)`
    );
  });
```

Where am I supposed to import functions from `workbox-*` packages?

**Comment by jeffposnick** [comment]
> Up to this point I've been pull workbox from the Google CDN using importScripts(). However, this is no use when my PWA is offline.

That not the case—all service workers implicitly store a copy of scripts that are loaded via `importScripts()` during the `install` process and they will always be available while offline.

So... using a bundler is definitely an option, and it's going to be more prevalent starting in Workbox v5 ([here's an example](https://github.com/GoogleChrome/samples/blob/86b6e436aba13aadddba1c775fc078a2ee676f52/web-share/rollup.config.js#L37-L53)), but at the same time, it's not necessary to achieve what you're trying to do.

**Comment by gknapp** [comment]
What I've run into is an error on install then, where `importScripts()` fails to retrieve workbox first time around. The app I'm working on is companion to a larger product that it's installed alongside. I can't guarantee internet access is available.

Thanks for the rollup example, is there one for webpack also?

**Comment by jeffposnick** [comment]
The webpack example involves using the `InjectManifest` mode of the `workbox-webpack-plugin` and configuring its `swSrc` to use ES module imports to pull in the pieces of Workbox that you need.

This is an example of an equivalent `swSrc` file in v4 and v5 (written in TypeScript): https://gist.github.com/jeffposnick/8b3465e933275f15e6cb1ce6737403c0

We'll have more official examples in the final v5 docs.

**Comment by dsebastien** [comment]
Hello,

I'm trying to migrate to Workbox 5 with Webpack + TypeScript to generate my service worker.
Is there a canonical example somewhere? I have trouble understanding the steps.

In my case, here's what I have in mind for my app:
* The Angular build generates the app output is dist/ (no service worker at all)
* I execute a dedicated webpack configuration that should:
  * use the TS loader to compiler my service-worker.ts file to JS
  * use the CopyWebpackPlugin to copy all the assets generated by Angular so that Webpack is aware of those and thus the InjectManifest plugin as well (I'm not sure about this but it's the impression that the release notes gave me)
  * use the InjectManifest plugin to modify the generated service-worker.js file
  * have the service-worker.js file be put along with all the rest of the assets under the dist folder

I just have trouble with the two last points.

**Comment by jeffposnick** [comment]
Are you sure you want to use `webpack` for that?

[Here's an example](https://github.com/jeffposnick/jeffposnick.github.io) that uses Rollup + the `workbox-cli` in a two-step process to bundle the service worker (translating from TypeScript in the process) and then inject the manifest (generaated via `glob` pattern matching) in the resulting service worker.

- [Rollup config](https://github.com/jeffposnick/jeffposnick.github.io/blob/d730ae6344da4875649cbdda60406a9ad79a329c/rollup.config.js)
- [Workbox config](https://github.com/jeffposnick/jeffposnick.github.io/blob/d730ae6344da4875649cbdda60406a9ad79a329c/workbox-config.js)
- [npm scripts](https://github.com/jeffposnick/jeffposnick.github.io/blob/active/package.json#L31-L41)

You could do this with `webpack`, using the `workbox-webpack-plugin`'s `InjectManifest` mode, but I'm not 100% sure what the `entry` config would be in that sort of setup. `webpack`, as far as I know, makes it difficult to just run some plugins to get their side effects without actually having a main compilation, with one or more `entry`s, configured. You might need to create a dummy `entry`.

**Comment by dsebastien** [comment]
Indeed, it seems quite annoying to do it all within a single pass with Webpack. Too bad, as it would've limited the mental overhead for my project ;-)

I'll give the rollup approach a try. But I'll need to figure out how to inject the assets list in the transpiled service worker js file. Weren't the glob pattern options removed in v5 final?
I just saw that there is a rollup-plugin-workbox-inject plugin but it seems to refer to the glob options still.

**Comment by jeffposnick** [comment]
`workbox-webpack-plugin` removed `glob` options, since `webpack` has its own asset pipeline and reading files from disk didn't really match well with that.

`workbox-build` and `workbox-cli` (which wraps `workbox-build`) both still support `glob` patterns and generating the precache manifest based on the contents of the local filesystem.

**Comment by dsebastien** [comment]
Ok, thanks a ton @jeffposnick. I was making my life harder than needs be.

Here's what I did to fix this:
* Angular: build as usual
* service worker TS to JS using Webpack + TS loader (basic config)
* workbuild-build with a simple config/globs to inject the list of assets

Time to enjoy some more TypeScript goodness ;-)

**Comment by SaravgiYash** [comment]
@jeffposnick Sorry for asking here but can you please guide me on what should I do:
I am currently using workbox CDN for my sw.js
But now I want to move away from CDN, the project also uses webpack but when I try to use the workbox-webpack plugin it works but the generated file static/build/sw.js contain 10248 lines of code so is it normal? or I am missing something.
And How can I only precache few selected files and not precache any files generated by webpack? 
webpack.config.js
```
/* eslint-env node, es6 */
// https://webpack.js.org/configuration
const
    webpack = require('webpack'),
    path = require('path'),
    {InjectManifest} = require('workbox-webpack-plugin'),
    prod = process.env.NODE_ENV === 'production',
    // The output directory for all build artifacts. Only absolute paths are accepted by
    // output.path.
    distDir = path.resolve(__dirname, 'static/build');

module.exports = {
    // Apply the rule of silence: https://wikipedia.org/wiki/Unix_philosophy.
    stats: {
        all: false,
        // Output a timestamp when a build completes. Useful when watching files.
        builtAt: true,
        errors: true,
        warnings: true
    },

    // Fail on the first build error instead of tolerating it for prod builds. This seems to
    // correspond to optimization.noEmitOnErrors.
    bail: prod,

    // Specify that all paths are relative the Webpack configuration directory not the current
    // working directory.
    context: __dirname,

    // A map of ResourceLoader module / entry chunk names to JavaScript files to pack.
    entry: {
        all: './openlibrary/plugins/openlibrary/js/index.js',
        vue: './openlibrary/plugins/openlibrary/js/vue.js',
    },

    resolve: {
        alias: {}
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
       new InjectManifest({
            swSrc: path.resolve(__dirname, 'static', 'src-sw.js'),
            swDest: 'sw.js',
        })
    ],
    module: {
        rules: [{
            test: /\.js$/,
            use: {
                loader: 'babel-loader',
                options: {
                    // Beware of https://github.com/babel/babel-loader/issues/690.
                    // Changes to browsers require manual invalidation.
                    cacheDirectory: true
                }
            }
        }, {
            test: /\.less$/,
            use: [
                {
                    loader: 'style-loader'
                },
                {
                    loader: 'css-loader',
                    options: {
                        url: false
                    }
                },
                {
                    // compiles Less to CSS
                    loader: 'less-loader'
                }
            ]
        }]
    },
    optimization: {
        splitChunks: {
            cacheGroups: {
                // Turn off webpack's default 'vendors' cache group. If this is desired
                // later on, we can explicitly turn this on for clarity.
                // https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks
                vendors: false,

            }
        },
        // Don't produce production output when a build error occurs.
        noEmitOnErrors: prod
    },

    output: {
        // Specify the destination of all build products.
        path: distDir,
        // base path for build products when referenced from production
        // (see https://webpack.js.org/guides/public-path/)
        publicPath: '/static/build/',

        // Store outputs per module in files named after the modules. For the JavaScript entry
        // itself, append .js to each ResourceLoader module entry name.
        filename: '[name].js',

        // This option determines the name of **non-entry** chunk files.
        chunkFilename: '[name].[contenthash].js',

        // Expose the module.exports of each module entry chunk through the global
        // ol (open library)
        library: ['ol'],
        libraryTarget: 'this'
    },

    // Accurate source maps at the expense of build time.
    // The source map is intentionally exposed
    // to users via sourceMapFilename for prod debugging.
    devtool: 'source-map',
    mode: prod,

    performance: {
        maxAssetSize: 703 * 1024,
        maxEntrypointSize: 703 * 1024,
        // Size violations for prod builds fail; development builds are unchecked.
        hints: prod ? 'error' : false
    }
};
```
