### ISSUE TITLE
End-to-end test of sw-build's writeFileManifest()

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#227]
**Library Affected**:
`sw-build`

There are some unit tests to confirm the low-level functionality of `sw-build`'s `writeFileManifest()`, but currently are not any higher level, end-to-end tests, confirming that it will output a valid manifest file in the specified format`.

See https://github.com/GoogleChrome/sw-helpers/pull/225#issuecomment-281494962

**Comment by gauntface** [comment]
I added a test to generate-manifest-e2e.js in sw-cli. This is a fairly clean test of sw-cli & sw-build in that it's taking expected results from sw-cli, calling sw-build with those values, performing an actual scan of the file directory and then parsing the file-manifest.js file to a node VM and checking the results.

The only thing this doesn't cover is the 'es2015' file format, not sure what would be best for this.

Build it - run it through rollup, test the result in the same process as the iife version?

**Comment by gauntface** [comment]
Thoughts on this @jeffposnick ?

**Comment by jeffposnick** [comment]
Running things through Rollup does sound like the best way to test the `es2015` version without pulling in additional dependencies, though it might not be the highest of priorities given that there's already test coverage for the other outputs.

**Comment by gauntface** [comment]
@jeffposnick is this still needed do you think?

**Comment by jeffposnick** [comment]
No, there are enough end-to-end tests of common use cases, and using `es2015` manifest generation is not likely to be as common as I initially thought.
