### ISSUE TITLE
Docs: broken link to definition of 'external service worker'

### ISSUE THREAD

**Issue by daffinm** [GoogleChrome/workbox#2270]
Following locations all contain links to definition of 'external service worker' that are broken:

* https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox.html#event:externalactivated
* https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox.html#event:externalinstalled
* https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox.html#event:externalwaiting

The link: https://developers.google.com/web/tools/workbox/modules/workbox-precaching#def-external-sw

**Comment by jeffposnick** [comment]
@philipwalton Can you take a look at what the target of those links should actually be?

**Comment by jeffposnick** [comment]
This should be fixed by https://github.com/GoogleChrome/workbox/pull/2283
