### ISSUE TITLE
Multicharacter paths not whitelisted by default by registerNavigationRoute()

### ISSUE THREAD

**Issue by j-mew-s** [GoogleChrome/workbox#2271]
**Library Affected**:
workbox-routing

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
Whitelist all navigation requests by default, rather than only single-character paths.

We use `registerNavigationRoute()` in an SPA, supplying a blacklist only. It currently intercepts `/` but not `/events`. Some digging turned up that the default whitelist consists only of the regex `/./`, where I would have expected `/.*/`.

https://github.com/GoogleChrome/workbox/blob/a068fa668335278fab0dde4a5771a5b5718315e1/packages/workbox-routing/src/NavigationRoute.ts#L54

**Example URL**: https://app.glean.co/events
This navigation request is not intercepted by workbox and falls back to browser cache or network. This has caused us issues after deploying since old index.html in browser cache may reference files (with cache busters) that no longer exist.

**Comment by jeffposnick** [comment]
The relevant code is https://github.com/GoogleChrome/workbox/blob/ecc18673aab127c532168e4dafee65f6e47931b1/packages/workbox-routing/src/NavigationRoute.ts#L109-L115

If the default RegExp `/./` ends up being used, the statement is equivalent to

```
/./.test('/path/to/test')
```

which will always be `true`, as long as you pass in a string with _at least_ one character. (`/^.$/` is a RegExp that _only_ matches a single character, but that's not the pattern that's used by default.)

I would recommend running [Workbox's development bundles](https://developers.google.com/web/tools/workbox/guides/configure-workbox#configure_debug_builds_vs_production_builds), which include additional logging information, and checking out the JS console logs to figure out why your configuration isn't working as expected.

**Comment by j-mew-s** [comment]
Thank you @jeffposnick for the quick response. Looks like it might be something we didn't do when upgrading to v4 after all.
