### ISSUE TITLE
Add handleFetch back in for development

### ISSUE THREAD

**Issue by bnikom** [GoogleChrome/workbox#2272]
**Library Affected**:
_workbox-build, workbox-sw_

Is it possible to add the `handleFetch` option back into `WorkboxSW` and `workbox-build`? It's a convenient part of the build chain that helps separate development and production builds. I understand there's a feature in the Dev Tools application tab that easily mimics this option, but having it built into the build process is a fail-safe if a developer forgets, is unused to using the Dev Tools feature, or just doesn't totally understand how service workers work.

I'm open to discussing it, but in the previous thread (where this feature was removed)
https://github.com/GoogleChrome/workbox/issues/1002
it was mentioned that the discussion can be re-opened if people ask for it.

**Comment by jeffposnick** [comment]
At this point, especially as we move away from `workbox-sw` for our "recommended" developer experience, I don't think we're going to add this back.

It can, to some extent, be replicated by using `process.env.NODE_ENV` inside of `if()` statements prior to bundling your service worker.
