### ISSUE TITLE
typo on website - modules - backgroundSync - if/is

### ISSUE THREAD

**Issue by rtpHarry** [GoogleChrome/workbox#2286]
Can't find a way to edit the page so I'm submitting it here in case it can make its way to the right people.

https://developers.google.com/web/tools/workbox/modules

## Typo: if / is

workbox.backgroundSync
Use background sync to reliably make a network request even if the user **if** offline.

![image](https://user-images.githubusercontent.com/1038062/69441491-c0b03f00-0d42-11ea-9a38-e73b01c7c7f0.png)

**Comment by jeffposnick** [comment]
Thanks for letting us know! I've fixed it in https://github.com/google/WebFundamentals/pull/8343
