### ISSUE TITLE
Runtime caching for custom url pattern does not work in Safari

### ISSUE THREAD

**Issue by alexeigs** [GoogleChrome/workbox#2289]
**Issue**
Custom cached url (image from firebase storage) does not work in Safari. While Chrome and Firefox get the image from cache and therefore also work in offline mode, Safari (desktop/mobile) keeps downloading the image every time and if offline, not find anything anymore obviously.

**Library Affected**:
*workbox-sw, workbox-build, workbox-webpack-plugin etc. (default vue quasar workbox plugin)*

**Browser & Platform**:
*Safari (desktop Version 13.0.3 (15608.3.10.1.4) / mobile iOS 13.1.3)*

I'm using the workbox plugin for quasar. The following is a snippet from `quasar.conf` file managing the pwa and workbox options. Anyway, I don't think my issue is related to quasar or the plugin specifically but to the compatibility between workbox and safari.

```
  pwa: {
      workboxPluginMode: 'GenerateSW',
      workboxOptions:  {
        clientsClaim: true,
        navigateFallback: '/index.html',
        runtimeCaching: [
          {
            urlPattern: new RegExp('media&token'),
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'brochures-cache',
              cacheableResponse: {
                statuses: [0, 200]
              },
              fetchOptions: {
                mode: 'no-cors'
              }
            }
          },
          {
            urlPattern: '/',
            handler: 'NetworkFirst'
          }
        ],
      },
  }
```

**Comment by alexeigs** [comment]
Hello? Nobody there from the Workbox team?

**Comment by alexeigs** [comment]
@jeffposnick In case it was me doing something substantially wrong here, I would highly appreciate a hint where to continue debugging; I feel somewhat lost not having found a lot on this topic so far. Anyway, would be cool to have some discussion here to know at least if I'm the only one or not facing this issue. Many thanks!

**Comment by jeffposnick** [comment]
Hello!

In general, the way that I'd recommend debugging this is to follow the steps at https://developers.google.com/web/tools/workbox/guides/troubleshoot-and-debug#debugging_workbox to enable the debug builds of Workbox, and check out the JS console logs in Safari. Since you're using `GenerateSW`, you'd want  to edit your generated service worker file after generation to add in `workbox.setConfig({debug: true})` immediately after the call to `importScripts()` near the top of the file.

If I had to _guess_ at what's going on, I'd say that your RegExp (`/media&token/`) isn't matching in Safari due to some difference in how the subresource URLs end up being constructed there. If you could pass along steps on reproducing the issue on a publicly accessible website, I could take a look myself. Otherwise, you can check out the additional debugging info and see if that helps.

**Comment by alexeigs** [comment]
@jeffposnick Thanks for the explanation and hints. Although Safari lists its files with a name instead of the actual URL, the URL is still there and includes the same pattern. For debugging I switched to `/avatar/` which is included everywhere, both in the URL and in the name listed. Still, while chrome works, safari doesn't. I have reproduced it here: https://github.com/alexeigs/debugging, cd into client-a where you'll find everything setup (repo is also just to debug Webstorm using a multi-app structure).

Having the expert on board, I'm struggling also with an issue visible in `register-service-worker.js` inside `src-pwa`. I cannot make listening to events/chaining different sw's state work... Thankful for any tip, although the caching issue should be the focus here. :-)

**Comment by jeffposnick** [comment]
Hello!

The following log in the JS console when running your example explains what's happening:

`The regular expression '/avatar/' only partially matched against the cross-origin URL 'https://firebasestorage.googleapis.com/v0/b/sample-project-abcd.appspot.com/o/users%2F7vAA1IkAgxXdWvdM9adm4PA19br1%2Favatar.png?alt=media&token=e13cb44b-ea5d-433d-8975-bea9ff686eda'. RegExpRoute's will only handle cross-origin requests if they match the entire URL.`

This behavior is explained in more detail in the Workbox documentation, e.g. at https://developers.google.com/web/tools/workbox/guides/route-requests#matching_a_route_with_a_regular_expression

(Basically, Workbox will not match third-party URLs with RegExps unless you provide a RegExp that matches the full URL. This is to avoid accidentally caching third-party traffic that you didn't anticipate.)

I'm not 100% sure why you'd see different behavior in Safari here, as Workbox behaves the same regardless of browser. I'd say that what you _might_ be seeing is an aggressive usage of the HTTP cache in Chrome and Firefox, bypassing the service worker, but those images seem to be served with HTTP caching disabled.

What I'd suggest doing is adjusting your RegExp to something like: `RegExp('^https://firebasestorage\.googleapis\.com/.*media&token')` and see if that helps.

**Comment by alexeigs** [comment]
@jeffposnick I see. Unfortunately also the RegExp you suggested does not have any impact on caching. I guess it hasn't worked for you either, right? From the little experience I have so far I wouldn't be surprised if there are still some compatibility issues with Safari... Let's nail it down - any more ideas?

**Comment by jeffposnick** [comment]
Following the steps that you provided with the https://github.com/alexeigs/debugging repo and swapping in `RegExp('^https://firebasestorage\.googleapis\.com/.*media&token')` as the `RegExp` in your `GenerateSW` config leads to something that works fine offline across all browsers, in my local testing.

I took these screenshots of Safari's DevTools (both the SW version and the main page version) while offline, and the PNG response successfully comes from the SW from the perspective of the main page:

<img width="1094" alt="Screen Shot 2019-12-03 at 3 40 25 PM" src="https://user-images.githubusercontent.com/1749548/70088097-95034380-15e3-11ea-9766-dafacea2816f.png">

The logging in the SW DevTools shows that the `StaleWhileRevalidate` strategy is being used to handle the request and it successfully generates a response from the cache (even though "revalidate" step via the network fails):

<img width="1081" alt="Screen Shot 2019-12-03 at 3 40 34 PM" src="https://user-images.githubusercontent.com/1749548/70088172-bcf2a700-15e3-11ea-82f6-d6c18b69f6a1.png">

So... I'm not actually able to reproduce any issues, and I do think that switching the `RegExp` to ensure that it matches the start of the third-party URLs is necessary.

**Comment by alexeigs** [comment]
@jeffposnick It was on my end obviously, I forgot to manually clean Safari's cache and without it the changes were not effective. Jeff, thanks again for your help, such support is invaluable and keeps (small) dev teams like us going where otherwise we'd just feel stuck.  🙏

**Comment by jeffposnick** [comment]
Happy that you got things sorted! (And apologies that the cross-origin routing behavior can be less than intuitive without logging enabled.)
