### ISSUE TITLE
Custom precache plugin.cacheWillUpdate gets called twice per file during installation

### ISSUE THREAD

**Issue by prichey** [GoogleChrome/workbox#2294]
**Libraries Affected**:
*workbox-precaching, workbox-core*

**Issue**:
Passing a plugin with `cacheWillUpdate` to the `PrecacheController` leads to that function getting called twice per file during installation: first, in `_addURLToCache` (called by `PrecacheController` [here](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-precaching/src/PrecacheController.ts#L265)), then second, inside of `_isResponseSafeToCache` (called by `cacheWrapper.put` [here](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-core/src/_private/cacheWrapper.ts#L232)).

I initially thought this was caused by https://github.com/GoogleChrome/workbox/issues/2285, but I traced the code and realized that awaiting the response didn't actually change the result because an unfulfilled promise is still truthy (woo JavaScript!).

Here are some reconstructed logs that might be helpful:
```
Installing the PrecacheController...
Network request for '/foo.js' returned a response with status '200'.
customPlugin.cacheWillUpdate called for '/foo.js'. // from PrecacheController
customPlugin.cacheWillUpdate called for '/foo.js'. // from cacheWrapper.put
Updating the 'mock' cache with a new Response for /foo.js.
Successfully installed the PrecacheController
```

**Comment by jeffposnick** [comment]
CC: @philipwalton, as this relates to https://github.com/GoogleChrome/workbox/issues/1767, in that there's currently a lot of logic in `workbox-precaching` that duplicates things that are normally handled via a `workbox-strategy`, and the implicit dependency on `workbox-core`. (Calling `cacheWillUpdate` directly in `workbox-precaching` dates  back to #1716.)

The first time the `cacheWillUpdate` callback is called, the truthiness of its return value is examined and then discarded, but the second time it's called, inside of `cacheWrapper.put()`, the return value should actually be used as the `Response` that's cached. It should be called with the same parameters each time.

So... while invoking the callback twice might not be efficient, perhaps the actual behavior means that you'll end up with the logic you expect? If not, and you could share some more details about what your custom callback is meant to accomplish, perhaps we can suggest some additional workarounds.

**Comment by jeffposnick** [comment]
I'm fairly sure that #2459, included as part of [Workbox v6](https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0-alpha.1) should address this.

Please give our alpha release a try. If you're still seeing issues, we can revisit this issue.
