### ISSUE TITLE
Firebase auth plugin?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2295]
Forking @evdama's request from https://github.com/GoogleChrome/workbox/issues/2122#issuecomment-559451615, there's some docs for using Firebase auth with service workers at https://firebase.google.com/docs/auth/web/service-worker-sessions

This might make for a good [Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins). We should reach out to some folks from the Firebase team to gauge their interest.

**Comment by evdama** [comment]
Have you gotten any feedback from the firebase team yet, maybe @davideast has any opinion on this matter?

**Comment by mentAl-maZe** [comment]
Just created a workbox plugin that does exactly that.

Check it out and let me know what you think:
https://github.com/m2sd/workbox-plugin-firebase-auth

**Comment by evdama** [comment]
> Just created a workbox plugin that does exactly that.
> 
> Check it out and let me know what you think:
> https://github.com/m2sd/workbox-plugin-firebase-auth

@mentAl-maZe @m2sd
Just to make sure: using your pluging I'll also need to take care of the [server-side changes](https://firebase.google.com/docs/auth/web/service-worker-sessions#server_side_changes) right? Your plugin only handles the client-side changes to authenticate firebase users via the service worker correct?

**Comment by mentAl-maZe** [comment]
@evdama 
Sry for the late response, I've been crazy busy the last few weeks...
Yes, exactly, the plugin is a plugin solution for workbox which takes care of sending the ID Token to the server

**Comment by jeffposnick** [comment]
Thanks for creating this!
