### ISSUE TITLE
No longer compatible with Node 8 after upgrading strip-comments

### ISSUE THREAD

**Issue by calinoracation** [GoogleChrome/workbox#2297]
We recently started getting CI failures when the package change in https://github.com/GoogleChrome/workbox/pull/2280 got pulled in indirectly for us, which then resulted in failures with a message like below:

> Invalid regular expression: /^(?<!(?:<!-))-->/: Invalid group

If you install the same npm packages on node 10, this works, and we use node 10 locally so we only saw it on CI for Node v8.9.1.

**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
On build

**Issue or Feature Request Description**:
Downgrade strip-comments until we're sure it is compatible with Node v8.

**Comment by calinoracation** [comment]
FWIW, on strip-comments, they assert on the page that they are only node 10+ compatible.

> Install with npm (requires Node.js >=10):

**Comment by jeffposnick** [comment]
Sorry about that—we do [test against Node.js v8](https://github.com/GoogleChrome/workbox/blob/5824a9a0cb32d97e5e7752fff8b6ddf8ca7ed83e/.travis.yml#L16-L17) in our automated suite, but I guess that particular code in the third-party module isn't being exercised 😦

Our intention is to support Node.js v8 in the Workbox v5 release, so I'll drop back down to the earlier version of `strip-comments`.

**Comment by codler** [comment]
Node 8 will have end of life this year end. https://nodejs.org/en/about/releases/ , wouldn't it be better to upgrade to newer node??

**Comment by jeffposnick** [comment]
Given that it's not Dec. 31 yet, supporting Node v8 for the Workbox v5 release remains our goal.
