### ISSUE TITLE
capture service worker error and send to server

### ISSUE THREAD

**Issue by marmikdesai** [GoogleChrome/workbox#2306]
Hi @jeffposnick 

I want to capture service worker error and need to send server. Can you please tell me how can I get this error?

![image](https://user-images.githubusercontent.com/4994566/70614706-028d2080-1c31-11ea-8e25-6b3338658044.png)

Marmik

**Comment by jeffposnick** [comment]
There are two options (none of which are specific to Workbox):

1) Add `.reject()` to a promise chain that might throw an error, or a `try/catch` combo to an `await`ed promise, and send a message to report the error like you would code that fails anywhere else. Here's an example with `await`:

```
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      await doSomethingThatMightFail();
    } catch (error) {
      reportTheError(error);
      // Make sure to re-throw the error.
      throw error;
    }
  })());
});
```

2) Register a [`unhandledrejection` event listener](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) in the `ServiceWorkerGlobalScope` (i.e. `self`):

```
self.addEventListener('unhandledrejection', ({promise, reason}) => {
  // promise is the promise that rejected, and reason is the rejection reason.
  reportTheError(reason);
});
```

The second approach will let you standardize your failure logging in a single location, but doesn't give you as much control over recovering from individual failures like the first approach does.

**Comment by marmikdesai** [comment]
Hi,

I have tried below code but it never throw error while precache file missing.
```
workbox.precaching.precacheAndRoute([
    'offline.html',
]);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      await self.skipWaiting().then(function() {
        console.log("service worker installed") //service worker log this
      }).catch((err) => {
        console.log("service worker installing error ->" + err); //service worker didn't log this
      });
    } catch (error) {
      console.log(error) //service worker didn't log this
      throw error;
    }
  })());
});
```

**Comment by jeffposnick** [comment]
It's the call to `workbox.precaching.precacheAndRoute()` that's rejecting, and therefore thee error handling needs to be associated with that, not with your call to `skipWaiting()`.

It's honestly probably easier to go with the `unhandledrejection` for this use case.
