### ISSUE TITLE
Issue using workbox with Firebase Cloud Messaging

### ISSUE THREAD

**Issue by Ggayane** [GoogleChrome/workbox#2307]
Hi all,
I'm using firebase messaging service which has its service worker, and I use workbox.GenerateSW class to create my workbox service worker.

The problem is these two seems can't work together, as after any refresh my workbox service worker becomes "redundant".

I know this cause firebase sw, because whenever I don't register it workbox works perfect, as expected.

Does anyone have any idea what can I do in such situation?

P.S. I'm new in service workers world :)

**Comment by jeffposnick** [comment]
Hello! 👋 

I think your best bet is not to use `GenerateSW` but instead use `InjectManifest`, as this will give you more control over your service worker. You can then include the references to the Firebase Messaging service worker in your `importScripts()`.

I don't have a project of my own that demonstrates this, but I did find, e.g., https://github.com/wreszelewski/firebase-messaging-example/blob/master/public/sw.js

Searching for "[firebase messaging workbox](https://www.google.com/search?q=firebase+messaging+workbox&oq=firebase+messaging+workbox&aqs=chrome..69i57j0j69i64.2951j1j9&sourceid=chrome&ie=UTF-8)" has a few other examples as well.

Hope that helps!

**Comment by Ggayane** [comment]
Thank you so much for you help!
