### ISSUE TITLE
Workbox Cache Expiration

### ISSUE THREAD

**Issue by ishu-koundal** [GoogleChrome/workbox#2309]
workbox.routing.registerRoute(
      new RegExp('\.(png|svg|jpg|jpeg)$'),
      workbox.strategies.cacheFirst({
        cacheName: 'Images-cache',
        plugins: [
          new workbox.expiration.Plugin({
            maxAgeSeconds: 24 * 60 * 60, // cache for 1 days
            maxEntries: 50,
            purgeOnQuotaError: true
          })
        ]
      })
    );

I am creating images cache for 1 day. i have some confusion not clear yet. anyone please explain .

Q1:-  is cache deleted automatically after 1 day.
Q2:- if i using PWA app offline till 4 or 5 hours  ? will it work because cache will not there (maxAgeSeconds)
@3:-  how new cache updated

**Comment by jeffposnick** [comment]
When using `workbox-expiration`, cleanup happens after a request is read/written to the cache.

So what would happen if your web app starts up after a period of inactivity is that after the first request is made for something that matches that route, Workbox would check all entries in the cache, delete the least-recently used ones if there are more than 50, and also delete any that were used more than 1 day ago.
