### ISSUE TITLE
automatically ban the script that is responsible for registering the service worker from the captured files by set up strategies 

### ISSUE THREAD

**Issue by khalyomede** [GoogleChrome/workbox#2313]
**Library Affected**:
workbox-routing

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

Is it possible to tell Workbox to blacklist a file from being capture by any further network strategies at all?

My use case is I have 2 files, one for registering my service worker (`/assets/js/service-worker.js`) and the service worker itself (at the root of my web server, `/service-worker.js`).

The file that is responsible for registering my service worker contains this code.

```javascript
import { Workbox } from "workbox-window";

if ("serviceWorker" in navigator) {
  const workbox = new Workbox("/service-worker.js");

  workbox.register();
}
```

And my actual service worker contains this code.

```javascript
import { registerRoute } from "workbox-routing";
import { CacheOnly } from "workbox-strategies";

registerRoute(/\.js$/, new CacheOnly);
```

The issue is that my service worker registration file (`/assets/js/service-worker.js`) will be captured by the cache-only strategy, and I would like it would not be captured at all by any strategies.

A workaround I found is write the following code.

```javascript
registerRoute(/^(?!\/assets\/js\/service-worker).*\.js/, new CacheOnly);
```

However, I would like to be able to specify, or let us say blacklist, this particular route apart from inside my registerRoute call. I was thinking of something like this (if this is not possible for the moment).

```javascript
import { blacklist } from "workbox-routing";

blacklist(["/assets/js/service-worker.js", /\.json$/]); // could accept regexp as well as regular strings
```

I am actually making a plugin that let the user configure which routes to cache (using all the available network strategies), and I would like to offer the opportunity for the user to not think about the fact that they should constantly take care of not capturing the specific `/assets/js/service-worker.js` file each time they are capturing Javascript assets (plus the fact that the plugin make the user not to have to know the existance of this file because everything is black boxed for him).

Is there any way to do it with the available libraries?

**Comment by jeffposnick** [comment]
You've got a number of different approaches.

I don't think we'd go with a `blacklist` method like you describe, but you could accomplish something similar via a "whitelist" that is registered before your other route, and uses the `NetworkOnly` strategy:

```
import { registerRoute } from 'workbox-routing';
import { CacheOnly, NetworkOnly } from 'workbox-strategies';

registerRoute(/service-worker\.js$/, new NetworkOnly());
registerRoute(/\.js$/, new CacheOnly());
```

Alternatively, you could use a [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.Route#~matchCallback) rather than a RegExp for routing, and explicitly add in the logic you want in that function:

```
import { registerRoute } from 'workbox-routing';
import { CacheOnly } from 'workbox-strategies';

function jsMatchCb({url}) {
  if (url.pathname === '/assets/js/service-worker.js') {
    return false;
  }

  if (url.pathname.endsWith('.js')) {
    return true;
  }

  return false;
}

registerRoute(jsMatchCb, new CacheOnly());
```
