### ISSUE TITLE
How to handle friendly URLs

### ISSUE THREAD

**Issue by Stanzilla** [GoogleChrome/workbox#2316]
**Library Affected**:
workbox-sw, workbox-build

**Browser & Platform**:
Google Chrome 80

**Issue or Feature Request Description**:
I'm using https://github.com/mkdocs/mkdocs/ with friendly URLs enabled (https://www.mkdocs.org/user-guide/configuration/#use_directory_urls) and I want to cache every page on the first visit with a NetworkFirst strategy. I don't know how to create a correct route for that though.

I don't want to use precaching because I don't have a way to invalidate atm.

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
If you need to support both types of URLs, one approach would be to write a custom `cacheKeyWillBeUsed` plugin, and add it to your `NetworkFirst` strategy. That will let you manipulate the cache key used for reads and/or writes.

https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins

Something like (untested):

```
function cacheKeyWillBeUsed({request}) {
  const url = new URL(request.url);
  url.pathname = url.pathname.replace(/\/index\.html$/, '/');
  url.pathname = url.pathname.replace(/\.html$/, '/');
  return url.href;
}

const networkFirstStrategy = new NetworkFirst({
  cacheName: 'html',
  plugins: [{cacheKeyWillBeUsed}],
});

const navigationRoute = new NavigationRoute(networkFirstStrategy);
registerRoute(navigationRoute);
```

**Comment by Stanzilla** [comment]
Awesome, will test, thank you! I feel like that's a common enough use-case to be in the examples though?

**Comment by jeffposnick** [comment]
You can handle fallbacks by either by explicitly calling the strategy's `handle()` method and wrapping it in `try`/`catch`, or (preferably, I think) following the recipe from https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route

```
setCatchHandler({event}) => {
  switch (event.request.destination) {
    case 'document':
      return caches.match('/offline.html');
    break;

    // Handle other failures here as needed.

    default:
      // If we don't have a fallback, just return an error response.
      return Response.error();
  }
});

**Comment by Stanzilla** [comment]
That gets me `resulted in a network error response: the promise was resolved with an error response object.`

**Comment by jeffposnick** [comment]
The `setCatchHandler` approach does? Is `caches.match()` called with a valid, already cached URL? (I just threw `/offline.html` there as a placeholder.)

If you wanted to try the other approach, it's something like:

```
function cacheKeyWillBeUsed({request}) {
  const url = new URL(request.url);
  url.pathname = url.pathname.replace(/\/index\.html$/, '/');
  url.pathname = url.pathname.replace(/\.html$/, '/');
  return url.href;
}

const networkFirst = new NetworkFirst({
  cacheName: 'html',
  plugins: [{cacheKeyWillBeUsed}],
});

const networkFirstWithFallback = async (params) => {
  try {
    return await networkFirstStrategy.handle(params);
  } catch (error) {
    return caches.match('/offline.html'); 
  } 
}

const navigationRoute = new NavigationRoute(networkFirstWithFallback);
registerRoute(navigationRoute);
```

**Comment by Stanzilla** [comment]
Yeah, the name in the cache is `/offline.html?__WB_REVISION__=fd1733f8c158a3369899c2a0d907ec76` and I used 

```js
workbox.routing.setCatchHandler(({ event }) => {
  switch (event.request.destination) {
    case "document":
      return caches.match(/\/offline\.html.*\S/)

    default:
      // If we don't have a fallback, just return an error response.
      return Response.error()
  }
})
```

**Comment by jeffposnick** [comment]
`caches.match()` doesn't support regular expressions. (It's a [standard call](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match) from the Cache Storage API, not part of Workbox.)

As per the comment in the recipe docs, you can use `caches.match(workbox.precaching.getCacheKeyForURL('/offline.html'))` to make sure you have the correct URL, including the `__WB_REVISION` parameter.

**Comment by Stanzilla** [comment]
Oh my bad. Well that loads the offline page but all the relative URLs on it are now wrong. But that's probably a me problem and not a you problem. Thank you!
