### ISSUE TITLE
Unable to import some files from node_modules in SwSrc file.   While trying to import the file serviceWroker donot work.

### ISSUE THREAD

**Issue by Bitha007** [GoogleChrome/workbox#2322]
Unable to import some files from node_modules in SwSrc file.  
While trying to import the file serviceWroker donot work.

**Comment by Bitha007** [comment]
```
InjectManifest({
        swSrc: "./src/sw.js",
        swDest: "service-worker.js"
 });
```

**Comment by jeffposnick** [comment]
Can you try again using `workbox-webpack-plugin` v5? Prior to that, the `swSrc` file was not compiled by `webpack`, meaning that any `require` or `import` statements in the `swSrc` would lead to an invalid service worker.
