### ISSUE TITLE
type declaration files for 'workbox-build'

### ISSUE THREAD

**Issue by Mister-Hope** [GoogleChrome/workbox#2324]
Is there a type declaration files for 'workbox-build'? 
I can only find these

![image](https://user-images.githubusercontent.com/33315834/72237729-777bbd80-3616-11ea-9170-c433fbbf0085.png)

**Comment by jeffposnick** [comment]
There isn't, no.

In Workbox v5, we migrated the runtime codebase to TypeScript, so there are native types for all of those interfaces.

The v5 build tools were not migrated to TypeScript, though. (This might happen in a future release.)

Something that might help is that https://github.com/GoogleChrome/workbox/pull/2320 adds proper JSDoc info for all of the options supported by the build tools in v5. Once that's merged, I think it's a fairly straightforward process to either consume the JSDoc from an IDE, or generate standalone TypeScript typings from the JSDoc.

**Comment by Mister-Hope** [comment]
> There isn't, no.
> 
> In Workbox v5, we migrated the runtime codebase to TypeScript, so there are native types for all of those interfaces.
> 
> The v5 build tools were not migrated to TypeScript, though. (This might happen in a future release.)
> 
> Something that might help is that #2320 adds proper JSDoc info for all of the options supported by the build tools in v5. Once that's merged, I think it's a fairly straightforward process to either consume the JSDoc from an IDE, or generate standalone TypeScript typings from the JSDoc.

Glad you merged that PR and release V5, hope you can make the type declaration files for it soon.

**Comment by IlCallo** [comment]
Are `workbox-webpack-plugin` options the same of `workbox-build`? Are their TS types still missing too? [Quasar framework](https://github.com/quasarframework/quasar) uses workbox under the hood to power it's PWA mode and we hoped v5 would bring types for `workbox-webpack-plugin` configuration object too

**Comment by jeffposnick** [comment]
There are some differences in the options between `workbox-webpack-plugin` and `workbox-build`.

What's new in v5 is that there is [proper JSDoc](https://github.com/GoogleChrome/workbox/blob/7eb0a51d09d0d11b7bf79b8e70cc4f9297e42494/packages/workbox-webpack-plugin/src/generate-sw.js#L26-L187) for both of those interfaces.

Hopefully the JSDoc can help with autocompletion in IDEs, and I believe there are some tools for generating unofficial typing info from JSDoc as well.

Rewriting the build tools in TypeScript may happen at some point, but for v5, we focused on rewriting the runtime libraries.

**Comment by jeffposnick** [comment]
`workbox-build` TypeScript migration is tracked in #2477. I'm closing this in favor of that.
