### ISSUE TITLE
Clarify "lifecycle" plugin vs. standalone usage of some packages

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#233]
**Library Affected**:
`sw-cache-expiration`, and others

A few of the packages we're shipping contain code that can either be used as a standalone library or is auto-invoked as a "plugin" that gets triggered by the `RequestWrapper` lifecycle callback methods.

There's a lot of intermingling of that code right now, and it's not clear from looking at the documentation or the way the classes are structured what code is meant for reuse and what code is meant for the plugin.

We might just want to create a `Plugin` subclass or factory-like method in each of the classes that encapsulates the plugin-specific code. Or something along those lines—I'm open to ideas.

**Comment by addyosmani** [comment]
I'm in favor of us creating a `Plugin` subclass for classes that encapsulate plugin-specific code. I'm also wondering to what extent better naming artifacts in the repo that are plugin specific with that a suitable prefix (or breaking down using `plugins` subdirectories) might help with being able to more easily reason about the codebase.

**Comment by gauntface** [comment]
We ended up creating a plugin class for the relevant pieces and I think this cleaned up a lot of these questions.
