### ISSUE TITLE
"importsDirectory" is not a supported parameter.

### ISSUE THREAD

**Issue by noahehall** [GoogleChrome/workbox#2339]
throws in v5

**Comment by noahehall** [comment]
nvm - should have red the dox

A number of workbox-build, workbox-cli, and workbox-webpack-plugin configuration parameters are no longer supported, following the general outlines of the changes described above. For instance, generateSW will always create a local Workbox runtime bundle for you, so the importWorkboxFrom option no longer makes sense.

**Comment by novaknole** [comment]
@noahehall 

could you help me with this? Thanks in advance.

**Comment by noahehall** [comment]
@novaknole 

see
[inject manifest schema](https://github.com/GoogleChrome/workbox/blob/v5/packages/workbox-webpack-plugin/src/inject-manifest.js)

[how its used in the webpack compilation](https://github.com/GoogleChrome/workbox/blob/v5/packages/workbox-webpack-plugin/src/inject-manifest.js#L136)
