### ISSUE TITLE
If injectManifest does not find one of the globPatterns in workboxConfig, none of the files are cached

### ISSUE THREAD

**Issue by paulooliveirapd** [GoogleChrome/workbox#2340]
**Library Affected**:
*workbox-sw, workbox-build*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
When one of the paths in glob patterns does not match, any files are injected in the service-worker.

-- I know there is a `warning` parameter in the `injectManifest`, and it does tell me that `One of the glob patterns doesn\'t match any files`. But the others patterns does match and should be cached properly, as the `count` and `size` parameters are zero even though there are many files that match the patterns

**Comment by jeffposnick** [comment]
Hmm... I'm not able to reproduce this locally when trying to add to our `workbox-build` v5 integration tests for `injectManifest`.

Can you help with the following:
- Are you using `workbox-build`/`workbox-cli` v5? If not, could you [upgrade](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4) and try again?
- Could you pass along your full Workbox configuration?
- Can you confirm that the injected manifest is completely empty? I think that's what you're saying, but I'm not sure.

FWIW, here's the new test case that I just tried locally, and it does work as expected (at least with Workbox v5). Those `count` and `size` values are what I'd expect, and there is a populated manifest.

```
it(`should return a warning, but otherwise work if one globPattern doesn't match anything`, async function() {
  const swDest = tempy.file({extension: 'js'});
  const options = Object.assign({}, BASE_OPTIONS, {
    swDest,
    globPatterns: [
      '*.html',
      'does-not-match',
    ],
  });

  const {count, filePaths, size, warnings} = await injectManifest(options);
  expect(warnings).to.have.lengthOf(1);
  expect(warnings[0]).to.contain('does-not-match');
  expect(count).to.eql(3);
  expect(size).to.eql(2352);
  expect(filePaths).to.have.members([swDest]);

  await validateServiceWorkerRuntime({
    entryPoint: 'injectManifest',
    swFile: swDest,
    expectedMethodCalls: {
      precacheAndRoute: [[[{
        url: 'index.html',
        revision: '32_CHARACTER_HASH',
      }, {
        url: 'page-1.html',
        revision: '32_CHARACTER_HASH',
      }, {
        url: 'page-2.html',
        revision: '32_CHARACTER_HASH',
      }]]],
    },
  });
});
```

**Comment by paulooliveirapd** [comment]
Hi, thanks for the reply.
I opened this issue one or two days before V5 was released, and i didn't have time yet to try the new version. 
I will close this issue and when i do the upgrade i will test it again.

**Comment by jeffposnick** [comment]
Okay, thanks for confirming. I believe that the behavior in v5 should be along the lines of what you want.
