### ISSUE TITLE
Workbox should depend on a released version of jsdoc-baseline

### ISSUE THREAD

**Issue by prichey** [GoogleChrome/workbox#2341]
Currently `jsdoc-baseline` is the only dependency in the project that depends on a git URL pinned to a certain commit (`git://github.com/hegemonic/baseline.git#c492ee1717f4`) rather than a specific release. There have been several patch releases since the referenced commit. Would it be possible to update the dependency to `jsdoc-baseline@0.1.5`?

**Comment by jeffposnick** [comment]
CC: @philipwalton, as I'm not sure why that's the case.

**Comment by philipwalton** [comment]
We pinned to that version due to build failures, though I don't remember the details of those failures now. We could try to update and see if the new versions have fixed our issue.

**Comment by prichey** [comment]
I'm happy to submit a PR if that's helpful. I was running into some weird firewall issues running `npm install` in the project so thought I'd see if there was a reason for this.

**Comment by philipwalton** [comment]
I just checked and the docs seem to build fine (both here and when using [WebFundamentals](https://github.com/google/WebFundamentals/pull/8426)), so I filed https://github.com/GoogleChrome/workbox/pull/2342 to fix.

**Comment by prichey** [comment]
Thanks for getting on this so quick!
