### ISSUE TITLE
Latest webpack plugin(v5.0.0) is still using workbox version 4.3.1 

### ISSUE THREAD

**Issue by tkeer** [GoogleChrome/workbox#2346]
**Library Affected**:
*workbox-webpack-plugin*

I have installed workbox-webpack-plugin v5.0.0 and using inject-manifest option. The workbox's link generated is "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js".

**Comment by philipwalton** [comment]
`InjectManifest` mode does not add any `importScripts()` calls to the service worker, so if you're seeing an `importScripts()` call to load version 4.3.1, my assumption is that it's hard-coded into your service worker source file.

I'm going to close this issue, but feel free to comment here if my above assumption is not correct.
