### ISSUE TITLE
custom fetch listener not working

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2351]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
Google chrome latest

**Issue or Feature Request Description**:
I am using workbox with prefetchmanifest. 

 This is my service-worker

```precacheAndRoute(self.__WB_MANIFEST);```

I know that this creates install,activate, fetch listener for the those. 

Now,  I want to add custom fetch listener. 

```
self.addEventListener('fetch', function(event){
    console.log("url ==  123 45444446", event.request.url);          
})
```

The strange thing happens now: For the urls, that are saved in workbox-cache, my custom fetch listener never executes. but for those, that are  NOT in workbox-cache,  my custom event listener executes. I wanted to test something so I changed the src code of the ``` precacheAndRoute``` and found the fetch listener and put there ```console.log("test", event.request.url)```. Now,  this gets printed for any url that is in precache or not. 

**Can't I have my custom fetch listener which gets executed for any url at all?**

**Comment by philipwalton** [comment]
Fetch listeners are executed in the order they're added, and as soon as one calls `event.respondWith()`, then that's the last listener that will be run.

In your example above, calling `precacheAndRoute()` before you've added your own listener will result in your listener *not* running for fetches that match any of our precached URLs, which explains the outcome you're seeing.

> Can't I have my custom fetch listener which gets executed for any url at all?

Yes, you just have to add them first, and then you have to make sure *not* to call `event.respondWith()` if you want the precached route to _also_ run (which I assume you do).
