### ISSUE TITLE
workbox-webpack-plugin documentation not complete

### ISSUE THREAD

**Issue by sorinpav** [GoogleChrome/workbox#2352]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
Chrome Version 79.0.3945.130 (Official Build) (64-bit), Windows x64
**Issue or Feature Request Description**:
[This](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin-InjectManifest.html#InjectManifest) previously had a full list of all the parameters that we could use in the injectManifest. I'm only seeing 
![image](https://user-images.githubusercontent.com/50046459/73764943-b8757680-476b-11ea-8f33-dccf08aaf388.png)

**Comment by pmochine** [comment]
Weird I see everything here

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest.html

 But it's for version 5.

**Comment by sorinpav** [comment]
I see! I'll have a look and since mine was for a previous version, I'll try to update. 
However, when I tried to access it, I went straight from the main website, to get to that page. 
I'll leave the issue open to see if any staff from workbox respond to it.

**Comment by jeffposnick** [comment]
Sorry about that—we had some issues with old documentation lingering on under the `/latest/` URL.

https://github.com/google/WebFundamentals/pull/8434 should address it, and there should only be v5.0.0 documentation under that URL prefix as soon as that change is deployed.
