### ISSUE TITLE
clientsClaim() not seems to work.

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2354]
**Library Affected**:
*workbox-webpack-plugin, workbox-core*

**Browser & Platform**:
Chrome latest

**Issue or Feature Request Description**:

The code here:

```js
skipWaiting();
clientsClaim();
precacheAndRoute(self.__WB_MANIFEST);
```

You sure this is how clientsClaim is supposed to work? even If I register my service worker instantly without 'load' event on window, clientsClaim doesn't seem to work. How do I know? I put my console logs in workbox's fetch listener and they don't get logged in the console for the first page load. 

Could it be due to the fact that install and activate event takes some huge time somehow from workbox and that's why my requests for js/css and assets get initiated faster than them which concludes that fetch event will not be called?

**Comment by philipwalton** [comment]
> I put my console logs in workbox's fetch listener and they don't get logged in the console for the first page load.

Can you clarify what's not happening here? Are you talking about fetch listeners for the navigation request to the page? Fetch listeners for sub-resources for the page? Fetch listeners for dynamic fetches that happen after the `activate` event fires?

For context, `clientsClaim()` will only claim clients after the service worker successfully installs and activates, so any fetches that occur before that are not expected to be intercepted by the service worker. Does that explain what you're seeing?

In case you're not familiar with where `clientsClaim()` fits into the service worker lifecycle, here's a good summary: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#clientsclaim

**Comment by novaknole** [comment]
As I said, I have the following code in my SW.

```js
skipWaiting();
clientsClaim();
precacheAndRoute(self.__WB_MANIFEST);
```

I register my SW instantly . not in ```load``` event or any event.

AND I found workbox's fetchlistener and put there
```js
console.log("IT comes here", event.request.url);
```

Now, when I open my website for the first time,  what I should be able to see is those console.log-s which state "IT comes here". I don't see any of them at all. When I removed workbox and used my custom ```install/activate/fetch``` listener,  and put ```self.clients.claim()``` in activate event and put ```console.log``` in fetch listener,  now it prints (not all the urls, but at least 3 of them). but for workbox, it doesn't print any console logs which would tell me that fetch listener is called at least once for the first page load.


My assumption is your install/activate event with clients claim take a really good amount of time and before it takes effect, all of my requests get done and that's why fetch listener never gets called.  But for my case, in install/activate, i only have 1 line of code and looks like it's faster and that's why i can see at least 3 of the urls in fetch listener.

Agree?

**Comment by philipwalton** [comment]
> My assumption is your install/activate event with clients claim take a really good amount of time and before it takes effect.

This is what `clientsClaim()` does: https://github.com/GoogleChrome/workbox/blob/7eb0a51d09d0d11b7bf79b8e70cc4f9297e42494/packages/workbox-core/src/clientsClaim.ts#L22

I think there must be some other explanation for what you're seeing, because as far as I can tell, Workbox isn't doing anything differently from what you're doing. I suspect the reason you're seeing what you are is that when you're testing your service worker, a previously active service worker is still controlling the page (or something like that).

Regardless, what would be helpful is if you could create a demo of both cases so we could compare, but in general I don't think you can reliably expect the service worker to install before your fetch events complete.
