### ISSUE TITLE
Typo in Workbox Strategies documentation ( "{f" -> "{" )

### ISSUE THREAD

**Issue by drytt** [GoogleChrome/workbox#2367]
**Library Affected**:
Workbox Strategies (documentation)

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I think there are unnecessary characters `f` left. 

Workbox Strategies > Advanced Usage
(https://developers.google.com/web/tools/workbox/modules/workbox-strategies)

AS-IS:
```
...
  if (url.origin === location.origin && url.pathname === '/') {f
...
```
TO-BE:
```
...
  if (url.origin === location.origin && url.pathname === '/') {
...
```

**Comment by jeffposnick** [comment]
Thanks for pointing this out. (I blame my Macbook Pro's keyboard...)

It'll be addressed in https://github.com/google/WebFundamentals/pull/8474
