### ISSUE TITLE
webpackCompilationPlugins doesn't seem to work

### ISSUE THREAD

**Issue by gabiseabra** [GoogleChrome/workbox#2376]
**Library Affected**:
workbox-webpack-plugin@5.0.0

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

`webpackCompilationPlugins` doesn't apply `webpack.DefinePlugin` and `webpack.EnvironmentPlugin` to the output bundle.   

The following does not replace `__REVISION__` in sw.js:

```js
new InjectManifest({
  swSrc: './src/sw/index.js',
  swDest: 'sw.js',
  webpackCompilationPlugins: [
    new webpack.DefinePlugin({
      __REVISION__: JSON.stringify(process.env.COMMIT_SHA1)
    })
  ]
})
```

**Comment by jeffposnick** [comment]
Thanks for reporting; I'll take a look.

**Comment by jeffposnick** [comment]
Sorry that there's no progress to report; based on some local debugging, I can see that `DefinePlugin` does get added to the `childCompilation` that `workbox-webpack-plugin` creates, and I can see it being called during that compilation, but it doesn't appear to have the intended effect.

https://github.com/webpack/webpack/issues/2978 and https://github.com/webpack/webpack/issues/9240 seem related.
