### ISSUE TITLE
registerRoute match third-party

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2378]
**Library Affected**:

**Browser & Platform**:
Latest

**Issue or Feature Request Description**:

I want to registerRoute which would match third-party urls. As you know, ordinary regex doesn't work for this case .  

`However, for cross-origin requests, regular expressions must match the beginning of the URL. The reason for this is that it’s unlikely that with a regular expression new RegExp('/styles/.*\\.css') you intended to match third-party CSS files.`

The thing is what you recommend is to put the starting url of that third-party. But what if i don't know what the starting url of that third-party is and i don't want to import that variable in service worker? any way to still make this work via regex? 

`If you wanted to match both local and third parties you can use a wildcard at the start of your regular expression, but this should be done with caution to ensure it doesn’t cause unexpected behaviors in you web app.`

Here is my regex: **`new RegExp('/.*publish/gi')`**, (There should be `publish` in the url) but this doesn't work. Could you change this regex to make it work?

**Comment by jeffposnick** [comment]
Hello!

When you pass in a string to the `new RegExp()` constructor, any `/` characters are treated as literal `'/'` slashes, and not as the special delimiters for starting/ending a regular expression.

I think what you're sayin is that you'd like to use a regular expression that will match any URL, even those on third-party origins, that contains `publish` anywhere in it.

You could do that via `new RegExp('.+publish')`
