### ISSUE TITLE
Better documentation for mode as a replacement for setConfig()

### ISSUE THREAD

**Issue by ashrith-kulai** [GoogleChrome/workbox#2379]
**Library Affected**:
*workbox-cli 5.0.0* - generateSW command

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
I am migrating from 4.3.1 to 5.0.0 and tried the inlineWorkboxRuntime option.
However I am getting **Uncaught (in promise) ReferenceError: workbox is not defined.** for v5 cli. 
Facing this error inside the file mentioned under importScripts option.

*Workbox 4.3.1*
 `importWorkboxFrom: "local",
 importScripts: ["sw-custom.js"]`

*Workbox 5.0.0*
`inlineWorkboxRuntime: true,
importScripts: ["sw-custom.js"]`

**Content of sw-custom.js**
`workbox.setConfig({
	debug: true
});`

This is because workbox is being minified and workbox as a variable is not available. 
I can see some minified variables like G,g,B,T etc in the debugger for the ServiceWorkerGlobalScope. 

**Possible Fix**
I think the inlineWorkboxRuntime option also needs to minify contents of importScripts option. 

Please let me know if you need any further inputs from my end.

**Comment by 9r1nc3w1ll** [comment]
I am having the same issue and just downgraded to 4.3.1.

and the documentation here https://developers.google.com/web/tools/workbox/guides/codelabs/webpack has not been updated for version 5

**Comment by jeffposnick** [comment]
You can set `mode: 'development'` or `mode: 'production'` in the v5 [`generateSW` configuration](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW) to toggle between the Workbox runtime that has extra logging enabled and disabled.

Sorry about that not being clear; we should add something to https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4 to call this change out explicitly.

**Comment by jeffposnick** [comment]
(And to get to the original question: we don't have any plans to include the `importScripts` URLs as part of the generated service worker bundle; for one thing, you can provide a third-party origin URL as the script value, and it doesn't make sense to bundle a remote URL. You can continue using `importScripts` with `generateSW` in v5, but you should not make any assumptions about symbols that might be available in the global scope.)

**Comment by ashrith-kulai** [comment]
@jeffposnick  - I have a few follow up questions
1. If the importScripts URL is local to my project and not a third party url then people would expect it to get inserted inline to the generated SW file.
Can this be taken as a feature request? 

2. Also you mentioned that "You can continue using importScripts with generateSW in v5, but you should not make any assumptions about symbols that might be available in the global scope". If that is the case, I think we would not be able to write any code which would require Workbox reference. At max may be we could refer to global service worker context and write some code around that.
To me it sounds like importScripts is practically not useful when inlineWorkboxRuntime: true option is set. 
So I think the library could throw a error of unsupported config combination error in this case or
at least a warning that this combination would not yield desired results.

**Comment by jeffposnick** [comment]
1. I'm not sure that that's a reasonable assumption. If you want to use Workbox in that fashion, I'd recommend switching to the `injectManifest` mode. In that mode, you have full control over the contents of your service worker file (including inlining whatever code you want), and Workbox just handles replacing the `self.__WB_MANIFEST` variable with the actual precache manifest based on your build config.

2. Folks have historically used `importScripts` for pulling in non-Workbox code, like code for push notifications. They can continue doing that in v5 with `inlineWorkboxRuntime: true` if they want. Disallowing that entirely would be too strict.

For your particular use case, I think you're going to have a better time switching to `injectManifest` and following the info at https://developers.google.com/web/tools/workbox/guides/using-bundlers to create a bundle of your service worker file using ES imports.
