### ISSUE TITLE
Runtime caching. Getting error "start_url does not respond with a 200 when offlineThe start_url did respond, but not via a service worker."

### ISSUE THREAD

**Issue by coolemur** [GoogleChrome/workbox#2380]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*Google Chrome Version 80.0.3987.116 (Official Build) (64-bit)*

**Description**:

*I have cached all website pages using runtimeCaching:*

```
        {
          urlPattern: new RegExp('/'),
          handler: 'StaleWhileRevalidate'
        },
        {
          urlPattern: new RegExp('/page-1'),
          handler: 'StaleWhileRevalidate'
        },
        {
          urlPattern: new RegExp('/page-2'),
          handler: 'StaleWhileRevalidate'
        },
       ...
```

* - All pages seems to be cached when I'm inspecting website with Chrome Dev Tools.

*When website is tested with Lighthouse, only main page / is shown as available offline.*
*When other pages is being tested with Lighthouse I am getting an error:*

```start_url does not respond with a 200 when offlineThe start_url did respond, but not via a service worker.```

*Also I've tried to add cache expiration in seconds with no success - getting same result.*

*Is there something I am missing?*
*Or Runtime cached pages can't be validated using Lighthouse?*

**Comment by coolemur** [comment]
I have created a test repository to reproduce this issue:

https://github.com/coolemur/workbox-test

Reproduce:

1. Run workbox-test on MAMP or other Web server.
2. Run Lighthouse audit on base url (/).
3. Result - base url is fully PWA as expected.
4. Go to page 1 or page 2.
5. Inspect with Dev tools - it shows that base url and page url are cached (as expected).
6. Run Lighthouse audit on page url (/page1.html or /page2.html).
7. Result - Lighthouse audit throws 200 error.

**Comment by coolemur** [comment]
Seems like I've found a solution. (Going to investigate this further)
Looks like each page must have its own manifest.json with start_url.

Created Dynamic manifest (commit, named "Dynamic manifest" in https://github.com/coolemur/workbox-test).

Correct me if there is another cleaner solution.

**Comment by iamlinkus** [comment]
Anyone found a solution for this issue?

**Comment by jeffposnick** [comment]
Hey all—I'd recommend following up with the Lighthouse project if you've got questions specific to how they detect the `start_url` behavior.

If you're running into any issues with functionality separate from Lighthouse audits, we can reopen and dig in further.
