### ISSUE TITLE
workbox-streams returns 404

### ISSUE THREAD

**Issue by anoblet** [GoogleChrome/workbox#2387]
**Library Affected**:
docs

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The link for workbox-streams returns a 404 (https://developers.google.com/web/tools/workbox/modules/workbox-streams)

The link is available in the nav when viewing other modules

**Comment by jeffposnick** [comment]
Thanks! This will be fixed in https://github.com/google/WebFundamentals/pull/8523
