### ISSUE TITLE
excludeChunks parameter should allow regex

### ISSUE THREAD

**Issue by EtienneT** [GoogleChrome/workbox#2388]
**Library Affected**:
*workboxPlugin.InjectManifest*

**Issue or Feature Request Description**:
The parameter excludeChunks in workboxPlugin.InjectManifest should allow to pass in regex.

**Comment by jeffposnick** [comment]
My intuition was that `chunks` usually have predictable names.

Can you share an example `webpack` configuration that would benefit from being able to provide a regex configuration?

**Comment by EtienneT** [comment]
We have a chunks that are desktop only and chunks that are mobile only.  All our desktop chunks name start with Desktop.  We only want to cache mobile chunks.

**Comment by jeffposnick** [comment]
Are all of these chunks available as properties in your `entry` configuration?

One workaround would be to do something like:

```
const entry = {
 DestkopChunk1: './src/blah.js',
 DestkopChunk2: './src/foo.js',
 MobileChunk: './src/baz.js',
};

module.exports = {
  // ...other webpack config...
  entry,
  plugins: [
    new InjectManifest({
      // ...other Workbox config...
      excludeChunks: Object.keys(entry).filter((e) => e.startsWith('Desktop')),
    }),
  ]
};
```

If there's enough demand and workarounds aren't sufficient, we can extend `excludeChunks` to take `RegExp`s. But I'd rather keep things simpler if existing functionality can satisfy the use case.

**Comment by EtienneT** [comment]
Interesting, I think this could work!

Thanks,
