### ISSUE TITLE
Better documentation for gtag in workbox-google-analytics

### ISSUE THREAD

**Issue by lc3t35** [GoogleChrome/workbox#2389]
The current document for workbox-google-analytics (https://developers.google.com/web/tools/workbox/modules/workbox-google-analytics) has only example with former GA not gtag.

The migrate documentation (https://developers.google.com/analytics/devguides/collection/gtagjs/migration#send_custom_dimensions_and_metrics) and gtag documentation on dimensions and metrics (https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets)  is not precise enough to clearly implement gtag with workbox-google-analytics.

When you create the dimension and metric, the code example states (in French) : 
````
JavaScript (gtag.js)
Pour obtenir des instructions sur la configuration de dimensions personnalisées à l'aide de gtag.js, reportez-vous à la documentation pour les développeurs gtag.js. (https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets)
`````

An additional example with gtag would really help.

If GA's created dimension is "dimension1" and "metric1" for metric, does workbox-google-analytics uses the same code for gtag with cd1 for dimension1 and cm1 for metric1 ?
  
````
googleAnalytics.initialize({
  parameterOverrides: {
    cd1: 'offline',
  },
  hitFilter: (params) => {
    const queueTimeInSeconds = Math.round(params.get('qt') / 1000);
    params.set('cm1', queueTimeInSeconds);
  },
});
````

**Comment by jeffposnick** [comment]
CC: @philipwalton for feedback.

**Comment by moos** [comment]
I never got the "cd1" thing to work with GA4.  I changed it to "up.network" and defined a user prop "network" in GA to track it.  The documentation is annoyingly behind Google's change pace.

**Comment by jeffposnick** [comment]
FYI: we have some thoughts on how to deal with offline analytics moving forward in the Workbox project at https://github.com/GoogleChrome/workbox/issues/3055

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
