### ISSUE TITLE
 Why are there two requests when I use "network only"

### ISSUE THREAD

**Issue by z008hy** [GoogleChrome/workbox#2390]
when i use "network only" to get a picture. I find there are two request in Chrome dev tool.
![image](https://user-images.githubusercontent.com/20768496/75691058-bce76d80-5cde-11ea-895f-4de48ab6199e.png)
Will this take up network？
I think Just need a network request

**Comment by jeffposnick** [comment]
This is normal and does not represent an additional network request.

There's background explaining what you see at https://stackoverflow.com/a/33655173/385997
