### ISSUE TITLE
workbox-google-analytics : Cannot use 'in' operator to search for 'sync' in undefined

### ISSUE THREAD

**Issue by lc3t35** [GoogleChrome/workbox#2392]
**Library Affected**:
workbox-google-analytics

**Browser & Platform**:
Chrome Version 80.0.3987.122

**Issue or Feature Request Description**:

I've added the plugin with the following configuration in my index.js: 

```
import * as googleAnalytics from 'workbox-google-analytics';

googleAnalytics.initialize({
  parameterOverrides: {
    cd1: 'offline'
  },
  hitFilter: params => {
    const queueTimeInSeconds = Math.round(params.get('qt') / 1000);
    params.set('cm1', queueTimeInSeconds);
  }
});
```

It generates the following error in console : 

```
Queue.js:289 Uncaught TypeError: Cannot use 'in' operator to search for 'sync' in undefined
    at Queue._addSyncListener (Queue.js:289)
    at new Queue (Queue.js:59)
    at new BackgroundSyncPlugin (BackgroundSyncPlugin.js:33)
    at Module.initialize (initialize.js:166)
    at Object../app/index.jsx (index.jsx:12)
    at __webpack_require__ (bootstrap:725)
    at fn (bootstrap:100)
    at Object.0 (index.js:68)
    at __webpack_require__ (bootstrap:725)
    at bootstrap:792
```

I'm trying to setup the plugin with gtag (despite #2389), here is the init in index.html

```
<script
      async
      src="https://www.googletagmanager.com/gtag/js?id=UA-xxxx-1"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());

      gtag('config', 'UA-xxxx-1');

      gtag('set', 'dimension1', 'online');
    </script>
```

On Analytics, I have 1 personalized dimension `dimension1` for Network Status and 1 metric `metric1` for Offline Queue Time

**Comment by lc3t35** [comment]
I found the error, one need to run googleAnalytics.initialize() after the service worker is registered (so self.registration exists)

````
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('service-worker.js', {
        scope: '/'
      })
      .then(registration => {
        console.log('SW registered: ', registration);
        googleAnalytics.initialize();
      })
      .catch(registrationError => {
        console.log('SW registration failed: ', registrationError);
      });
  });
}
`````
This way it works fine.

**Comment by jeffposnick** [comment]
Hello!

`googleAnalytics.initialize()` is not meant to be called from your web page—it's code that needs to live inside of your service worker script.

Based on at least the second comment, it looks like you're calling it from your web page.

Can you include all references to `googleAnalytics.initialize()` inside of `service-worker.js` instead?

CC: @philipwalton

**Comment by lc3t35** [comment]
Thank you ! Nice catch.
No more error. 
Maybe the [documentation](https://developers.google.com/web/tools/workbox/guides/enable-offline-analytics) could be more precise and clearly state that the code should be added inside service worker script ;)
