### ISSUE TITLE
workbox-webpack-plugin: workbox source dependency injection

### ISSUE THREAD

**Issue by jayaddison** [GoogleChrome/workbox#2396]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
After an [upgrade](https://github.com/openculinary/frontend/pull/63) from `workbox-webpack-plugin` 4.3.1 -> 5.0.0, a workbox-enabled service-worker script generated via `InjectManifest` fails evaluation during loading.

The Google Chrome developer console contains two error entries:

```
sw.js:1 Uncaught ReferenceError: workbox is not defined
    at Object.<anonymous> (sw.js:1)
    at r (sw.js:1)
    at sw.js:1
    at sw.js:1
(anonymous) @ sw.js:1
r @ sw.js:1
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
-------
localhost/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost/') with script ('http://localhost/sw.js'): ServiceWorker script evaluation failed
```

The first entry seems to describe the evaluation failure (the `workbox` object is unavailable), and the second entry is the service worker loader (ref: [source code](https://github.com/openculinary/frontend/blob/d30dd6623fa7245532f5b8395d659b54a2400701/src/sw/loader.js)) reporting the failure.

It **does** look like injection succeeded at least partially, since the `self.__WB_MANIFEST` placeholder in the [source code](https://github.com/openculinary/frontend/blob/d30dd6623fa7245532f5b8395d659b54a2400701/src/sw/sw.js#L31) has been correctly populated).

```
# sw.js snippet from Chrome file browser
... NetworkFirst),workbox.precaching.precacheAndRoute([{'revision':null,'url':' ...
```
**Notes / Findings**
The only [change](https://github.com/openculinary/frontend/compare/master..d30dd6623fa7245532f5b8395d659b54a2400701#diff-11e9f7f953edc64ba14b0cc350ae7b9dL48) to the `InjectManifest` module used via webpack is to remove the `importWorkboxFrom` configuration entry.

There is no `importScripts` statement in the [service-worker source code](https://github.com/openculinary/frontend/blob/d30dd6623fa7245532f5b8395d659b54a2400701/src/sw/sw.js); could that be related?  This seemed fine with `workbox-webpack-plugin@4.3.1` but perhaps something has changed there.

Webpack version [4.42.0](https://github.com/openculinary/frontend/blob/d30dd6623fa7245532f5b8395d659b54a2400701/package.json#L43)

Behaviour confirmed in Google Chrome 80.0.3987.132 and Firefox 73.0.1

**Comment by jayaddison** [comment]
After some more experimentation, it looks like this can be solved by adding [explicit import statements](https://github.com/openculinary/frontend/pull/63/commits/b6039bc6e51b0d424948ee31af32eb653cb489a8) to ensure that the required `workbox` dependencies are present.

That's explicit-rather-than-implicit module context, and that seems like a good thing overall.  The only surprise / concern remaining is that it was an unexpected change during the upgrade.

If I'd spent more time reading the migration guide's [module import](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4) notes and docs on [using bundlers](https://developers.google.com/web/tools/workbox/guides/using-bundlers) I might have figured this out before opening the issue. 

This issue could perhaps be closed as a non-bug / invalid - I'll leave it open for a little while just in case anyone from the `workbox` project has feedback.

**Comment by jayaddison** [comment]
Broadly speaking I think this was user integration error on my behalf; the upgrade to workbox 5.0.0 exposed a webpack configuration which worked previously, but was not following best practices.

**Comment by jitendra1607** [comment]
i am also having the same issue. Any proper solution?
