### ISSUE TITLE
Use target: 'webworker' in the InjectManifest compilation

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2399]
**Library Affected**:
*workbox-webpack-plugin*

See https://webpack.js.org/configuration/target/#string

CC: @prateekbh

**Comment by jeffposnick** [comment]
I don't think setting `target: 'webworker'` when configuring the child compilation will work.

https://github.com/webpack-contrib/worker-loader/blob/b82585a1ddb8ae295fd4b1c302bca6b162665de2/src/index.js#L50-L71 seems to be the "canonical" example of doing this (based on https://github.com/webpack/webpack/issues/9240#issuecomment-500702163), and it instantiates `WebWorkerTemplatePlugin` explicitly. We should probably just do that.

**Comment by prateekbh** [comment]
probably yes
