### ISSUE TITLE
how to have `default` cache mode for revision files too?

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2403]
**Library Affected**:
*Workbox-Precaching*

**Browser & Platform**:
Latest chrome

**Issue or Feature Request Description**:
Really Interesting. @jeffposnick  @philipwalton 

I use `InjectManifest`. The generated manifest is put in `service-worker.js` and also I made some hack to put it into `app.js` too.

in `app.js` , i loop through the manifest and load all of the files via `axios` by myself. After this is done,  That's when I register service worker. Now, let's say in a manifest, there was an entry such as:

{url: '/android-chrome-png', revision:'blablahdaf'}.  Now, even though I made a request to this file via `axios` first, when service worker kicks off, it's gonna make a request for that file again, even though ajax already had made it. So, I looked in the src code

```js
const cacheMode = (typeof entry !== 'string' && entry.revision) ?
                'reload' : 'default';
```

So, is there any way I can have `default` for those files? I don't understand if the file has a revision, why you got `reload` cache control option as it's always gonna download a new version.  `revision` is like a hash so:

 if my file didn't change, `revision` would be the same and I'd need it to be fetched from the cache. (network request doesn't make sense - it's wasted). 

If the file changed, revision would be different and `default` cache control would check in HTTP cache , wouldn't find it and still grab this from the network.

Makes sense?

**Comment by jeffposnick** [comment]
Your specific use case is outside of how we expect most folks to interact with `workbox-precaching`, and the assumption is that any URL that needs out-of-band `revision` info needs to bypass the HTTP cache in order to guarantee that the version currently deployed on your web server is the version that is stored by `workbox-precaching`.

I understand why you'd rather not have that behavior, but the focus is on keeping the `workbox-precaching` behavior "safe" for the average use case, and we have no plans to change this behavior.

**Comment by novaknole** [comment]
So, I understand your reason why it's like this. I'd really appreciate if you could give me any other solution to this and if it doesn't take you much time.

So, when the page loads, that's when I initiate service worker which also starts precaching things. Now, precaching manifest has some images, let's say 7 images and their overal size is 10mb. Now, because of the fact that these images will have `revisions` and requests will be made again from the service worker, There's still a problem.  Imagine this scenario that after the page load, service worker started precaching. and after that, i make `axios request` in the app somewhere.

What's gonna happen is because browser only has the ability of making 6 requests in parallel, my `axios request` is gonna be pending until 6 images of those 7 are downloaded. and if the network is slow, I end up in a big problem because I have to wait for the service worker to be done until my request from the app gets started.  What would you do in this case? basically, I need service worker to run after page starts loading and i might need axios requests after the page gets loaded and before the service worker is even done.


Thanks for your help ! REALLY !

**Comment by jeffposnick** [comment]
I'd recommend waiting to register your service worker until you're sure that your client web page has finished downloading whatever data it needs.

While many of the examples for service worker registration show it triggered during the `window`'s `load` event, that's just general advice, and you can customize things for your own situation. You can delay service worker registration until after your `axios` requests complete, for instance.

Additionally, you can look into using `webpack`'s support for versioning images via hashes and then loading them via `file-loader`: https://webpack.js.org/guides/asset-management/#loading-images

If you go with that approach, and your image URLs have hashes in them, then they won't need to be separately revisioned by `workbox-precaching`, and you will not have an additional download (assuming the HTTP cache is already populated). Just make sure that you set the [`dontCacheBustURLsMatching` option](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#InjectManifest) in `InjectManifest` to a RegExp that matches your hashes, which is what tells `workbox-precaching` not to add in its own `revision` info. E.g.:

```
InjectManifest({
  // This assumes that you've set up webpack to add in hashes like .[hash:8].
  dontCacheBustURLsMatching: /\.[0-9a-f]{8}\./,
  // ...other config here...
});
