### ISSUE TITLE
Recommended dev configuration for webpack

### ISSUE THREAD

**Issue by EtienneT** [GoogleChrome/workbox#2405]
What is the recommended way of developing while having workbox setuped?

For example, you change a styling in a css file included in webpack and also included in the pre-cached resources.  Then next time you refresh the page the SW will update, but the styling wont get downloaded right away.  You have to reload the page again for the new styling to be applied.

Any tricks for having to deal with this?

Thanks,

**Comment by jeffposnick** [comment]
You've got a few options:

- Don't register a service worker at all. You can surround your call to `navigator.serviceWorker.register()` with an `if (process.env.NODE_ENV === 'production')` clause, which will evaluate to `false` whenever your `webpack` `mode` is `'development'`.

- Alternatively, register a "no-op" service worker, consisting of an empty file, when you're in development. You can again use `process.env.NODE_ENV` to determine this, like

```
const swURL = process.env.NODE_ENV === 'production' ? '/service-worker.js' : '/no-op-sw.js';
navigator.serviceWorker.register(swURL);
```

This has the advantage of replacing any previously registered SW with a no-op variant, which could be useful if you have multiple projects that all share the same `localhost:port` combination.

There are other approaches too, I'm sure. I personally just use Chrome Incognito windows heavily when testing, but that doesn't help much when you want a `webpack` live reload.
