### ISSUE TITLE
Tracking the progress of Precached Assets

### ISSUE THREAD

**Issue by sinemacula** [GoogleChrome/workbox#2406]
**Library Affected**:
*workbox-precaching, workbox-webpack-plugin*

**Browser & Platform**:
*All browsers*

Hi Jeff,

I am currently in the process of implementing a progress bar on the initial load step of our PWA and  whilst the implementation is 99% complete, the final 1% is proving to be a bit of a nightmare...

In short, this is our logic:

1. Inject the `WB_MANIFEST` into our own JS source (not the service worker)
2. Utilise the `WB_MANIFEST` to preload each of the assets using our custom JS class and in turn, show a progress bar to the user
3. Once the preloading is complete, initiate the service worker (and run `precacheAndRoute`)

The issue with the above is that when the service worker initiates (and runs `precacheAndRoute`), it requests each of the items in `WB_MANIFEST` from the network, not the cache i.e. duplicate requests. We were hoping that the `precacheAndRoute` function would notice that all of the `WB_MANIFEST` items are already in the disk cache, and would therefore retrieve them from there instead of initiating new `fetch` requests over the network.

I have noticed the following line in the PrecacheController:

https://github.com/GoogleChrome/workbox/blob/a284beedb84f7e5d36694fce60bb4267000b1d5a/packages/workbox-precaching/src/PrecacheController.ts#L79-L80

This indicates that if I remove `revision` from each of the manifest entries then it will use `default` for `cacheMode` and _should_ fix the problem.

However, I don't believe this is an option as removing the revision information will trick Workbox into believing that the file has not changed. We currently use hashes on our CSS and JS filenames, but not on our images. In addition, all of our files are served by a CDN so our paths defined in source are absolute URLs not relative URLS, which, I believe, makes using `file-loader` much more complex, if not impossible (I may be wrong).

With all of the above in mind, can you suggest a solution as to either, how we can tell the workbox precache to check the cache first, OR, can you suggest a different/better way of obtaining and displaying the progress of `precacheAndRoute` as it runs?

**Comment by jeffposnick** [comment]
I really am not sure that you should be using `workbox-precaching` given that overall flow. [Runtime caching](https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy) might be more appropriate.

That being said, I think the comment in https://github.com/GoogleChrome/workbox/issues/2403#issuecomment-598840103 applies to your situation as well. We don't have any plans to make it "easy" to use the HTTP cache to fulfill precaching requests unless `revision: null`. And you shouldn't set `revision: null` unless you're using properly hashed URLs.

(With your proposed setup, if you deploy a new version of your web app in the interval in between your web app's `window` context finishing the download and before your service worker's `install` handler starts precaching, you'll end up with the "wrong" version of assets stored in your precache indefinitely.)

**Comment by sinemacula** [comment]
Thank you so much for your response Jeff, I really appreciate you looking into this.

We have managed to get the `file-loader` to work in the way that I thought was impossible, and as such, am able to hash the assets as well as the JS and CSS files, despite serving them from a separate CDN. This means that I can remove the `revision` and the service worker will subsequently check the cache first. I have tested this and it works :-D

In regards to your final point; this is a very good point! However, I don't think it will be an issue as what I think will happen is the following (correct me if I am wrong):

- User loads app
- App runs `preload`
- _New App is deployed to CDN_
- App registers service worker (this technically runs *immediately* after the preload)
- Service worker then begins precaching the files listed in the NEW app version manifest - in other words, preload downloaded `xyz`, and now the service worker is downloading `abc`

This would be annoying because it would lead to bad UX i.e. the browser would technically not be ready once the progress bar has disappeared as the service worker is still precaching from the network. However, I don't think it would lead to anything other than bad UX as the service worker would still have cached the correct files. It just means that the initial preloader did absolutely nothing other than delay the user from getting into the app and show them some pointless progress bar...

In addition, in order to further reduce the risk of this happening, I have already implemented something that will prevent the preload completing if ONE file fails to preload and given our deployment process cleans our CDN directories, if a new deployment occured, then this would prevent the preload from completing, thus prevent the service worker from registering.

I may have misunderstood what you meant by your final point, and if so, please let me know if I am walking into potentially a big issue...

**Comment by sinemacula** [comment]
Hi Jeff,

I have just re-read your final paragraph and realised that I completely misunderstood what you were saying, hence my long message talking about something completely irrelevant...

All sorted :-D

Thanks again
