### ISSUE TITLE
modifyUrlPrefix for Wordpress setup not working

### ISSUE THREAD

**Issue by Treast** [GoogleChrome/workbox#2408]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
I'm trying to include workbox-webpack-plugin into my Webpack configuration for Wordpress themes. 
I want to have a full scope caching, so my `swDest` looks like that :
`swDest: path.resolve(__dirname, '..', '..', '..', 'sw.js'),`
But then the URL generated are located to the root of Wordpress, so I tried to use `modifyURL` to fix this :
```
      modifyUrlPrefix: {
        '': '/wp-content/themes/mytheme/assets',
      },
```
But the URL generated aren't updated. I also tried the `manifestTransforms` callback, not working either. Also note that the URL containing `hot` are not excluded.

Here my full webpack configuration : 
```const webpack = require('webpack');
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const WorkboxPlugin = require('workbox-webpack-plugin');

let optimization = {
  minimizer: [],
};

let outputFileName = 'app.js';
let mode = 'development';

if (process.env.NODE_ENV === 'production') {
  optimization.minimizer.push(
    new TerserPlugin({
      parallel: true,
      terserOptions: {
        ecma: 6,
      },
    }),
  );
  mode = 'production';
}

const config = {
  entry: path.resolve(__dirname, 'src', 'js', 'app.js'),
  output: {
    path: path.resolve(__dirname, 'assets'),
    filename: outputFileName,
    libraryTarget: 'umd',
    // hotUpdateChunkFilename: 'hot/[hash].hot-update.js',
    // hotUpdateMainFilename: 'hot/[hash].hot-update.json',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.m?js$/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env'],
        },
        exclude: /(node_modules|bower_components)/,
      },
      {
        test: /\.s?css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              reloadAll: true,
            },
          },
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: path.resolve(__dirname),
              },
            },
          },
          'sass-loader',
        ],
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]?[hash]',
            },
          },
        ],
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: 'url-loader',
          },
        ],
      },
    ],
  },
  resolve: {
    extensions: ['.js'],
  },
  optimization,
  mode,
  // devServer: {
  //   contentBase: path.join(__dirname, 'src'),
  //   compress: true,
  //   port: 8100,
  //   watchContentBase: true,
  //   hot: true,
  //   inline: true,
  //   noInfo: true,
  //   open: true,
  //   publicPath: '/',
  //   proxy: {
  //     '/': {
  //       target: 'http://wordpress.localhost/',
  //       changeOrigin: true,
  //     },
  //   },
  // },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'styles.css',
      ignoreOrder: false,
    }),
    new BrowserSyncPlugin({
      proxy: 'http://www.wordpress.localhost/',
      files: ['**/*.php', '**/*.js', '**/*.css'],
      reloadDelay: 0,
    }),
    new WorkboxPlugin.GenerateSW({
      swDest: path.resolve(__dirname, '..', '..', '..', 'sw.js'),
      clientsClaim: true,
      skipWaiting: true,
      exclude: /hot/,
      modifyUrlPrefix: {
        '': '/wp-content/themes/journal/assets',
      },
      runtimeCaching: [
        {
          urlPattern: /\.(?:png|jpg|jpeg|svg)$/,
          handler: 'NetworkFirst',
          options: {
            cacheName: 'images',
            expiration: {
              maxEntries: 10,
            },
          },
        },
      ],
    }),
  ],
};

module.exports = config;
```
And the `sw.js` generated : 
```
workbox.precacheAndRoute([{
    "url": "app.js",
    "revision": "d3ae54e6f99b072ec5047865f0a13a51"
  }, {
    "url": "hot/eb4b41f194d34485c0fb.hot-update.js",
    "revision": "a0a568a2f242bf3de745e8ab6a38802f"
  }, {
    "url": "hot/eb4b41f194d34485c0fb.hot-update.json",
    "revision": "d0d70e47cc854b3817a473620350e9dd"
  }, {
    "url": "styles.css",
    "revision": "0d1aee6f9e0cc3b68664cb1abc6bf536"
  }], {});
  workbox.registerRoute(/\.(?:png|jpg|jpeg|svg)$/, new workbox.NetworkFirst({
    "cacheName": "images",
    plugins: [new workbox.ExpirationPlugin({
      maxEntries: 10,
      purgeOnQuotaError: true
    })]
  }), 'GET');
```

**Comment by jeffposnick** [comment]
Quick check before I debug further—are you using `workbox-webpack-plugin` v5.0.0, or an earlier version?

If you're using an earlier version, could you please [upgrade](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4) to v5 first? There are some changes in v5 that should enable this use case, as confirmed by our test suite:

https://github.com/GoogleChrome/workbox/blob/a284beedb84f7e5d36694fce60bb4267000b1d5a/test/workbox-webpack-plugin/node/generate-sw.js#L1339-L1380

**Comment by Treast** [comment]
Thanks for feedback. Yeah, I confirm I'm using v5.0.0.

**Comment by jeffposnick** [comment]
When I try this locally—e.g. by modifying the test case to confirm that using `''` will cause `modifyURLPrefix` to prepend the replacement string—everything works fine.

The fact that you're also seeing the `hot` URLs show up in your generated manifest, and that `manifestTransforms` doesn't run, really sounds strange.

One thing that I noticed is that you're using `exclude: /hot/,`, which should not actually be allowed by our validation rules for the `webpack` plugin; that value needs to be an array:

https://github.com/GoogleChrome/workbox/blob/a284beedb84f7e5d36694fce60bb4267000b1d5a/packages/workbox-build/src/options/partials/webpack.js#L16-L17

That all makes me thing that somehow you might be picking up a different instance of the `workbox-webpack-plugin` from somewhere else in your `webpack` configuration...

Can you, as a sanity check, try starting from a mostly empty `webpack` config, with freshly installed `node_modules/`, and just add in a new instance of the `GenerateSW` plugin with a straightforward `swDest` does a really basic `modifyURLPrefix: {'/': '/test/'}`? Does that work?

**Comment by jeffposnick** [comment]
I'm closing this issue as a couple of months have passed, but if it's still something you're puzzling with and you could take those debugging steps, we can reopen.
