### ISSUE TITLE
Make workbox-webpack-plugin work with typescript(?) or just in general.. 

### ISSUE THREAD

**Issue by changyeamoon** [GoogleChrome/workbox#2409]
**Library Affected**:
_workbox-webpack-plugin_

**Browser & Platform**:
_latest_

**Issue or Feature Request Description**:
I can't build my project without some errors about workbox-routing and workbox-strategies types not being found. I've attempted to add every type dependency that y'all have with no luck. I am sometimes able to build the project if I try multiple times (which seems very brittle and don't understand why). I have also tried other things although the PR does not show the attempts. Any direction will be greatly appreciated! 

![Screen Shot 2020-03-15 at 9 09 58 PM](https://user-images.githubusercontent.com/30943398/76723026-18642300-6703-11ea-8d14-739d91aa8a85.png)

Here is the PR with the latest webpack changes - https://github.com/changyeamoon/recall/pull/3

**Comment by jeffposnick** [comment]
Can you please make sure that you're not using `@types/workbox-sw` (it's listed in your `package.json`)?

The service worker libraries Workbox v5 are written as native TypeScript code, and you should be able to pull in all the correct references if you follow [the guidance](https://developers.google.com/web/tools/workbox/guides/using-bundlers) and reference the exported TypeScript functions and classes directly from their `npm` packages.
