### ISSUE TITLE
Write Documentation for sw-build

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox#241]
**Library Affected**:
*sw-build*

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Issue or Feature Request Description**:
*Write Documentation for sw-build*

**Comment by addyosmani** [comment]
When you get a chance, it would be great to expand on what the initial docs for sw-build might look like from an IA perspective.

**Comment by jpmedley** [comment]
I'm still missing my cut-and-paste code samples.

**Comment by jeffposnick** [comment]
There are two code samples of using `sw-build` in https://github.com/GoogleChrome/sw-helpers/blob/master/docs/recipes/rollup.md, and that page could be deprecated entirely if you put together more official documentation.

The code on that page uses out-of-date parameter names for some of the `sw-build` methods, though, as `dest` needs to be `swDest` and `rootDirectory` needs to be `globDirectory`.
