### ISSUE TITLE
new service worker gets installed immediatelly

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2411]
Hi @jeffposnick @philipwalton 

This post is not about Workbox, but i'd highly appreciate if you can take a look at this really strange behaviour or maybe it's me and I've never had the possiblity of this case.

My sw.js
```
console.log("good");
```

my index.html

```html
<html>
<head>
    <button onclick="updatesw()">Update</button>
</head>
<body>
    <script>
        var registration;
        navigator.serviceWorker.register('/sw.js').then((reg)=>{
            
        })
        function updatesw(){
            navigator.serviceWorker.ready.then((sw) => {
                sw.update();
            })
        }
        
    </script>
</body>
</html>

```

If you clear the browsing data and go to this website,  service worker installs successfully. Now, let's update `sw.js` to ```console.log("good change sw")```.  Now, if you click `update` button in `html`, it's going to execute `sw.update()` code and what it does is it installs new service worker which is fine, but it also activates it. why does it activate it? 

**My assumption:** This only happens for the first page load. If you refresh the page 2nd time and repeat the above process, new service worker after changing `sw.js` doesn't get activated and goes into waiting phase. The thing I decided to do is add `clientsClaim` in `sw.js's activate listener`. Now, all starts working and even for the first page time load and changing `sw.js`, it doesn't activate new sw and takes it into waiting phase. So , could this be related to `navigator.serviceWorker.controller ? `, maybe because this is not set for the first page load, when I click update , `sw.update() thinks` that because of `navigator.serviceWorker.controller` is still null, it decides to install new one.

What do you think? does this mean I have to use `clientsClaim` to avoid this behaviour? 

Thank you.

**Comment by daffinm** [comment]
I have also seen cases of spontaneous activation of new service workers where there is already an active service worker, and so you would expect the new one to go get stuck in the waiting state. I rebuild the app (which updates timestamps used by the log causing the precache list to get updated and therefore the sw.js file to change), press the 'hunt for updates' button, see the new service worker appear in Chrome dev tools and then go straight through all the phases until it activates. 

Browser is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4083.0 Safari/537.36`.

I cannot reproduce this reliably. Just when I think I have the steps nailed it stops happening... 

It feels like, in Chrome at least, the 'have we got a real update?' algorithm has been refined a bit. It's not just a case of 'did this file change by at least 1 byte?' but 'is this change significant?'

**Comment by novaknole** [comment]
Follow my scenario/case and you will see this behaviour every single time. 

a) build the code and run website. Don't refresh it. Just go to it for the first time.
b) change something in sw and rebuild the code. Don't refresh the page.
c) on the page, you should have a button which calls `reg.update` . When you click this, new service worker is identified which gets installed and also activated.(shouldn't be getting activated).
d) if you want to repeat the process, remove browsing data (all Time data) and run the steps again above.

**Comment by jeffposnick** [comment]
_I'd recommend reading through [The Service Worker Lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle), as it gives an easy-to-digest summary of the various states a service worker can be in._

When you call `registration.update()` and there's a change detected to your previously registered service worker, the new service worker will always going through the installation process immediately.

The relevant section of that doc is the description of the [`waiting` state](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#waiting):

> After it's successfully installed, the updated service worker delays activating until the existing service worker is **no longer controlling clients**. This state is called "waiting", and it's how the browser ensures that only one version of your service worker is running at a time.

So once your updated service worker is installed, one of two things will happen:

- If there are any clients that the previously installed service worker is still controlling, the updated service worker will going into the `waiting` state.
- If there are no clients that the previously installed service worker is still controlling, the updated service worker will not going into `waiting`, and instead immediately go into the `active` state. (Once the new service worker is `active`, the old service worker becomes `redundant`.)

The value of `navigator.serviceWorker.controller` on a web page reflects whether the current page is a client under control of a service worker or not, so as you observe, the value can be used to determine which of those two things will end up happening.

Similarly, calling `clients.claim()` inside of your service worker will cause that service worker to take control of any open web pages under its scope once it finishes activating. If you don't call `clients.claim()`, then open pages won't end up under the control of a newly activated service worker. Reloading the pages will cause them to end up under control, though.

So... yeah, I think I'm basically confirming all of your assumptions.

**Comment by daffinm** [comment]
@novaknole Is facebook ok? https://www.facebook.com/miles.daffin.
(If only there were a github backchannel...)

**Comment by novaknole** [comment]
Check the PM. I messaged you.

**Comment by daffinm** [comment]
@novaknole  Where? I don't see anything.

**Comment by novaknole** [comment]
@daffinm  check the friend request list and when you see Giorgi Lagidze, send a message to it and add me.
