### ISSUE TITLE
Cannot plugins in webpack if configuration is written in TypeScript

### ISSUE THREAD

**Issue by kirinnee** [GoogleChrome/workbox#2420]
**Library Affected**:
*workbox-cacheable-response*

**Browser & Platform**:
*Webpack configuration written  in typescript*

**Issue or Feature Request Description**:
*Cannot import plugin, due to it being an  es6 module*

```
import {CacheableResponse} from './CacheableResponse.js';
       ^

SyntaxError: Unexpected token {
```

When attempting to import into webpack.config.ts

**Comment by jeffposnick** [comment]
The `workbox-cacheable-response` package contains code that's meant to be run inside of a service worker. It's not meant to be imported directly into your `webpack.config.ts` file.

You should add the `InjectManifest` plugin to your `webpack.config.ts` and use that to add precaching information to your `swSrc` file, which contains your actual service worker code.

Something like:

**webpack.config.ts**:
```
import {InjectManifest} from 'workbox-webpack-plugin';

// Inside your webpack configuration:
{
  plugins: [new InjectManifest({
    swSrc: 'service-worker.ts',
    // ...other Workbox config options...
  })],
}
```

**service-worker.ts**
```
// List whatever Workbox imports you want:
import {CacheableResponsePlugin} from 'workbox-cacheable-response';
import {precacheAndRoute} from 'workbox-precaching';

// InjectManifest will add in the precache manifest here:
precacheAndRoute(self.__WB_MANIFEST);

// Now use CacheableResponsePlugin, etc. to write your own service worker logic.
```

**Comment by kirinnee** [comment]
Oops, this is embarrassing. Thank you very much.
