### ISSUE TITLE
PWA Workbox mxentries 50 limitation

### ISSUE THREAD

**Issue by Kulkanilesh** [GoogleChrome/workbox#2421]
Problem:- Using below code snippet we have increased maxEntries to 100, Only 50 entries are getting cached.Is there any other workbox strategies which will help us to store/cache more than 50 entries of API (Currently we have requirement to store approx 450-500 entries)

```
workbox.routing.registerRoute(
  new RegExp('.+\/api\/'),
      workbox.strategies.networkFirst({
      cacheName: 'myapp-apiCache',
          plugins : [
             new workbox.expiration.Plugin({
                 maxEntries: 100,
                 maxAgeSeconds: 30 * 24 * 60 * 60 // 30 days
              })
         ]
 })
 ```

**Comment by jeffposnick** [comment]
It sounds like the DevTools user interface might be confusing you: https://github.com/GoogleChrome/workbox/issues/1189#issuecomment-358683185

There's nothing in Workbox itself that would limit the number of items cached to 50.
