### ISSUE TITLE
[workbox-build] getManifest should return filePaths instead of manifestEntries

### ISSUE THREAD

**Issue by apascal** [GoogleChrome/workbox#2422]
Hi,

**Library Affected**:
*workbox-build*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
Since `5.0.0`, [docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.getManifest) indicate that `getManifest()`'s return type is:
```
{count: number, filePaths: Array of string, size: number, warnings: Array of string}
```
That is, `filePaths`, instead of the old `manifestEntries` from `v4`.

However, as of `5.1.2`, the [source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/workbox-build/get-manifest.d.ts) still returns the result of `getFileManifestEntries` without changing the `manifestEntries` to `filePaths`.

The actual behavior does not match the documentation.

Furthermore, [@types/worbox-build](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/workbox-build/get-manifest.d.ts) include `filePaths` in `getManifest()`'s return type, and therefore are incompatible with the library.

**Comment by jeffposnick** [comment]
Thanks for pointing this out! The `getManifest()` JSDoc was inaccurate, and will  be updated to reflect that the return value of `getManifest()` is an object with a `manifestEntries` property, not `filePaths`.

We don't publish `@types/worbox-build`, but I'm assuming that they're generated based on our JSDoc, so presumably fixing the JSDoc will propagate that fix forward.
