### ISSUE TITLE
Current documentation/getting started is very focused on precaching

### ISSUE THREAD

**Issue by stephanvierkant** [GoogleChrome/workbox#2423]
Not really a support question or a feature request, but some feedback about the documentation. TL;DR: I don't care about offline support. How to support Web Push?

I've just started using Workbox to create a service worker to support Web Push and some other API's. Since I'm using Webpack, using [Workbox's webpack Plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) seemed a good idea. On the 'Which Plugin to Use' part, for both plugins (GenerateSW/InjectManifest) 'You want to precache files' is mentioned. With both strategies, all static files are being cached. But what if I don't want to use precache?

I don't want to precache files because my HTTP cache strategy is working fine. That's even one of the [Key Points](https://youtu.be/25aCD5XL1Jk?t=1783) in the talk about service workers at the Chrome Dev Summit 2018: Don't just re-invent HTTP cache. While precaching can be great, just precaching all files generated by Webpack doesn't seem to be a good idea. Webpack generates static files and supports file versioning.

When looking at some [common recipes](https://developers.google.com/web/tools/workbox/guides/common-recipes) I see that Google Fonts are being (pre)cached from a CDN. To me, that looks like violating "don't re-invent HTTP cache', especially when reading about the [idea behind Google Fonts](https://fonts.google.com/about):

> Google Fonts makes product and web pages run faster by safely caching fonts without compromising users’ privacy or security. Our cross-site caching is designed so that you only need to load a font once, with any website, and we'll use that same cached font on any other website that uses Google Fonts.

I can understand you'll want to cache Google Fonts when adding offline support, but there isn't any need to cache Google Fonts from a performance perspective, isn't it?

I'd like to see a way of using Workbox without the focus on precaching. It's documentation on GitHub says "Workbox is a collection of JavaScript libraries for Progressive Web Apps",  but the website states "JavaScript Libraries for adding offline support to web apps".

I'm a bit confused right now. Should I use Workbox if I don't care about precache/offline support but want to offer Web Push? Is Workbox about PWA in general, or just about offline support?

edit: change the title, because the Web Push/Notification API isn't supported by Workbox, but the runtime cache and background sync are.

**Comment by novaknole** [comment]
It's all about what you want to cache and what not. 

First of all, I'd say that if you use workbox, its main power is how it handles precaching and adding runtime caching for other routes.  If you use `workbox-webpack-plugin` ,  it has one of the parameters: `exclude` and you pass array of regexes which mean they won't be put in the precache. If you don't want to precache anything at all, then you don't need to use any `workbox-webpack-plugin` at all. Push Notifications have nothing to do with workbox at all. I might add that workbox doesn't provide `push notification` which means you have to write it by yourself.


in service-worker.js,

```js
self.addEventListener('push', function(e){

})
```

Your final question: If you don't care about offline support, you shouldn't use workbox. Workbox provides offline support and also easier background sync. I guess you don't need it too. So , don't use it.

**Comment by stephanvierkant** [comment]
> It's all about what you want to cache and what not.

I want to cache all static assets generated by Webpack (js, css, woff, png, etc.), but I don't need a service worker for that. 

> If you don't care about offline support, you shouldn't use workbox. Workbox provides offline support and also easier background sync.

While I don't care about (full) offline support (yet), I want to take advantage of service workers. As I understand, it can improve performance of web apps, even if they don't have fully offline support. While static files are cached by HTTP cache, but for something like API calls, both runtime caching strategies and background sync would help improving the performance of my web app. 

> Workbox provides offline support and also easier background sync. I guess you don't need it too.

I don't need offline support, but I do like background sync. And nobody really needs a library, but they make a developers' job easier. And in this case, adding a service worker with Workbox was very easy. I haven't seen an easier to create a service worker with Webpack.

To me, it looks like Workbox is too focused on offline support, while there are use cases where other service worker API's can improve web apps. Are there any plans to support these use cases with Workbox?

**Comment by novaknole** [comment]
What other use cases do you mean other than offline support and background sync? I think you mean `PushAPI` ? @jeffposnick  would help here, but i think the reason they don't have any simpler way to handle it is because `push` is so easy with service workers. you just have to listen events and do stuff.

**Comment by stephanvierkant** [comment]
Caching Strategies, Background Sync but no precache. To me, that seems a legit use case. Or am I wrong?

Let's describe my use case:
- Webpack/Symfony Encore.
- Static assets (Webpack generated files, images) have versioned file names and long cache headers applied. Some asset files are sent to the user by HTTP/2 server push. So when it comes to performance, no need to use precache.
- Full stack Symfony web application. Hard to name a Symfony Component that isn't used. Using PHP/Twig/jQuery, but slightly moving towards using more Vue components. So no JS framework/routing, no app shell.
- 98% desktop users, but sometimes on locations where the internet connection can be flaky.
- Using API Platform. Here's where I think Caching Strategies and Background Sync can play an important role. For most GET-requests I'd like to use a stale response first, then update the Vue component if there's new content. For some POST-/PATCH-requests, background sync can improve performance. Am

I agree push is very easy, I don't need workbox for that. The only think is that I'd like to use Webpack to generate it, because of some parameters from Dotenv, but I could even work around that.

**Comment by novaknole** [comment]
`Caching Strategies, Background Sync, but no precache. To me, that seems a legit use case. Or am I wrong?`.

If that's what you want, then in service worker, don't call `precacheAndRoute(self.__WB_MANIFEST)` function at all and nothing will be precached.

**Comment by jeffposnick** [comment]
In general, support for web push is outside of the scope of Workbox, and it's not something that we attempt to cover in our documentation.

(https://firebase.google.com/docs/cloud-messaging/js/client is one option for web push notifications, if you're looking for a service to use. It should work as part of a larger service worker that uses Workbox.)

You're correct that a significant portion of our "getting started" type material ends up covering precaching, and not everyone actually can or should use precaching. That's feedback that will factor in to our next documentation overhaul.

Using runtime caching along with specific Workbox plugins is definitely a valid use case for Workbox, and I think the various Guides, starting with https://developers.google.com/web/tools/workbox/guides/route-requests, cover those possibilities.

In general, you can write your service worker like any other "modern" JavaScript/TypeScript project, consuming Workbox's libraries as ES modules, and then [bundle](https://developers.google.com/web/tools/workbox/guides/using-bundlers) it using Rollup/webpack/the bundler or your choice, without using precaching.

**Comment by jeffposnick** [comment]
This should be addressed by https://github.com/google/WebFundamentals/pull/9093
