### ISSUE TITLE
stalewhilerevalidate

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2424]
**Library Affected**:
*workbox-webpack-plugin*

I am really wondering about something if workbox has the feature or something for this.

Let's say I have a `registerRoute` function for one of the route. and I use `staleWhileRevalidate` cache strategy.  Let's say I updated the code and deployed. Now,  If user refreshes the page, he won't be able to see the latest changes because the item would be returned from the cache even though network is still made. So user has to refresh second time to see the changes.

Does workbox provide any practice for this case? maybe after newtork request is made, if it's stale, then update dom instead of making user refresh the page 2nd times. I know it's not possible to update DOM from SW , but still...

**Comment by jeffposnick** [comment]
`workbox-broadcast-update` can be used to notify a client page about changes between the previously cached response and the freshly revalidated response.

There are more details at https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-update
