### ISSUE TITLE
cache api ios device for workbox

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2426]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*E.g. IOS device (Safari)

**Issue or Feature Request Description**:

I've found some issues , haven't test it on all browsers . I am trying to test all this on Macos safari and ios safari. @jeffposnick  @philipwalton 

1)  Is it finally resolved that workbox precache and runtime cache will work on IOS safari devices? If you look into browser support for cache API, ios safari doesn't support it. it also means that because all browsers in ios are just wrappers around safari, it shouldn't work for those browsers too on safari device. 

 **What does workbox do to prevent this and make offline support work for IOS device ?** I tried it and it didn't work for Safari. I checked compatibility on canIuse and mozilla page and it's not supported. what does workbox do to make it work ? 

2) 
```js
self.addEventListener('install', function(e){
    console.log(self.__WB_MANIFEST, " manifest");
})
precacheAndRoute(self.__WB_MANIFEST);
```

This doesn't work, because of the fact that i log `manifest` in `install event`. if I remove logging it from `install`  listener, It starts working. Basically, what happens is because of I log it in install, `precacheAndRoute` now gets argument as undefined. I have no idea why.

3) I tried this on Macos and realized that after sw got isntalled and refresh the browser, 90% of my assets in network tab in safari say that they come back from `memory` and only 10% percent say they come back from `serviceworker`. Doesn't matter how many times I refresh the tab. Why does this happen at all? I have no idea. why don't they all come back from `service worker` ?

**Comment by jeffposnick** [comment]
The Workbox issue tracker isn't the place to ask general questions about service worker support on iOS.

The `InjectManifest` plugin works by replacing the first occurrence of `self.__WB_MANIFEST` in your `swSrc` file with the a precache manifest based on your `webpack` compilation. Your first occurrence is inside of the `install` handler, and that's what's being swapped out. The second occurrence doesn't get replaced, so nothing ends up being precached (you're passing an `undefined` value to `precacheAndRoute()`). You should be able to confirm this by looking at the contents of the `swDest` file created by the plugin.

If you want to use the precaching manifest value in multiple places, you can assign it to a variable, and then use that variable multiple times, like:

```
const manifest = self.__WB_MANIFEST;

self.addEventListener('install', function(e){
    console.log(manifest, " manifest");
})
precacheAndRoute(manifest);
```

**Comment by novaknole** [comment]
@jeffposnick I know this is not a place for ios support, but my question is something different.

1) As we can see, on caniuse.com page or mozilla page, safari ios doesn't support cache api. Because of that i am curious if you do some kind of fallback to navigate from this issue . 

2) didn't other people open any issues as far as you know? does workbox work on ios safari because of cache api?

**Comment by jeffposnick** [comment]
https://caniuse.com/#feat=mdn-api_cachestorage and https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage#Browser_compatibility both show that the current version of Safari on iOS supports the Cache Storage API.

<img width="1027" alt="Screen Shot 2020-03-30 at 3 58 44 PM" src="https://user-images.githubusercontent.com/1749548/77956169-6baba900-729f-11ea-9eca-38649bff409c.png">

We don't do anything specific in Workbox to accommodate Safari on iOS with regard to the Cache Storage API, because it's natively supported.

**Comment by novaknole** [comment]
Yeah, but Let's check this: https://developer.mozilla.org/en-US/docs/Web/API/Cache. If you check the compatibility, it says that ios safari not supports it. Any idea? what's the difference between those?

**Comment by jeffposnick** [comment]
The Workbox issue tracker really isn't the right forum to continue this discussion.

As I've said, there's nothing in Workbox that treats the Cache Storage API differently when used on Safari for iOS.

If you've found inaccurate information on one of the MDN web pages, one option is to take the steps to report the content issue there. The page you linked to has a "Update compatibility data on GitHub" link, which points to https://github.com/mdn/browser-compat-data#mdn-browser-compat-data
