### ISSUE TITLE
Thoughts around new onboarding experience

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2432]
(Capturing some thoughts from a conversation that @philipwalton and I had with @slightlyoff in a more permanent/actionable form.)

Currently, the Workbox getting started experience (for a new developer who just stumbles across our [docs](https://developers.google.com/web/tools/workbox/)) has most of the focus on using one of our build tools to generate an entire service worker file, with precaching and optionally some runtime caching routes.

This focus is very much on the technical integration of Workbox with a build process, and it does not do very much to motivate

- the reasons _why_ you should consider adding a service worker to your web app
- the various steps you should take prior to shipping a service worker to production, to ensure that you have a good rollback plan and metrics for measuring impact
- the UX considerations that you should make to account for the caching and offline capabilities that your service worker enables
- ...other topics here...

Some of this material applies equally to any service worker deployment, whether it's using Workbox or not, but it would be good for developers to think about before they start the journey of using Workbox.

I kind of feel like maybe we should flesh out some of these topics with an authoritative set of guide on https://web.dev/, and then create a more focused Workbox getting started experience that points people to the https://web.dev/ guidance first, and then provides the technical details of integrating with Workbox as a secondary step.

Some of the UX considerations might also be best solved by referring folks to the resources that the [PWA Builder](https://www.pwabuilder.com/) team is creating.

CC: @petele

**Comment by tpscrpt** [comment]
>     * to ensure that you have a good rollback plan and metrics for measuring impact

@jeffposnick Any general recommendations for rollback? I've just heard about the horror stories...

**Comment by jeffposnick** [comment]
https://stackoverflow.com/questions/33986976/how-can-i-remove-a-buggy-service-worker-or-implement-a-kill-switch/38980776 are the general best practices and things to consider.

**Comment by jeffposnick** [comment]
The changes in https://github.com/google/WebFundamentals/pull/9093 are intended to address this.
