### ISSUE TITLE
What is the signature for a custom route handler?

### ISSUE THREAD

**Issue by daffinm** [GoogleChrome/workbox#2439]
**Library Affected**:
https://developers.google.com/web/tools/workbox/modules/workbox-routing#matching_and_handling_in_routes

**Issue or Feature Request Description**:
The handler callback method in the docs has the following signature:
```javascript
const handlerCb = ({url, event, params})
```
But the handle method in all of the workbox strategies seems to have the following signature;
```javascript
async handle({ event, request }) 
```
I see from the debugger that the object passed to the handle method has the following properties:
```javascript
{
   url: URL, 
   request: Request, 
   event: FetchEvent, 
   params: undefined
}
````
Could these docs be updated? Or could they point to the API docs for Workbox? (Sorry. I am a java programmer struggling to adjust to this crazy javascript stuff.)

**Comment by jeffposnick** [comment]
The relevant TypeScript definitions are at https://github.com/GoogleChrome/workbox/blob/3ac095656354157eb4b58c93d3b1e390a5ba34dd/packages/workbox-core/src/types.ts#L36-L56

Ultimately, that's the intended "source of truth".

I'm not sure which docs you were looking at, but if anything doesn't match that (which is unfortunately possible; our docs are generated from JSDocs, not the TypeScript signature) then it's an issue with the docs that we'll resolve.

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~handlerCallback is the "official" docs—is that what you were looking at? If not, what's the URL of the page?

**Comment by philipwalton** [comment]
> But the handle method in all of the workbox strategies seems to have the following signature;
> 
> ```js
> async handle({ event, request }) 
> ```

@daffinm note that, in JavaScript, you generally only list the parameters a given method is using—not all the parameters it's invoked with.

In the case of Workbox strategies, they all only use the `request` and `event` params, but since Workbox's routing interface accepts handlers that may also use `url` and/or `params`, every invocation of a handler function (which all strategy classes `handle()` method is) from a `Router` object needs to be invoked with all four object params, even if the function doesn't end up using them.

**Comment by philipwalton** [comment]
@jeffposnick looking at the docs and TypeScript typings, I think everything is correct (though it is the case that strategy classes don't use the `url` or `params` options, which is OK since they're marked as optional).

**Comment by daffinm** [comment]
OK. I guess this is a PEBKEC error, in a sense. That said, you might direct people to the official docs from pages like this. I see the link to [the link to the reference docs](https://developers.google.com/web/tools/workbox/reference-docs/latest) right at the bottom of [the page I originally linked to](https://developers.google.com/web/tools/workbox/modules/workbox-routing#matching_and_handling_in_routes). It would have been handy to find it further up, in context, perhaps with [a link to the relevant section](https://developers.google.com/web/tools/workbox/reference-docs/latest#workbox-routing).

**Comment by jeffposnick** [comment]
I've filed https://github.com/google/WebFundamentals/pull/8671 to update some of that documentation, and hopefully prevent future confusion.

Thanks for the feedback!
