### ISSUE TITLE
Offline Analytics V2

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#244]
**Library Affected**:
sw-offline-google-analytics

**Browser & Platform**:
Google Chrome v51.0.1 for Android, or "all browsers".

**Issue or Feature Request Description**:
With @prateekbh's work on the background sync library being further along, it's worth chatting about whether we want to refresh offline-google-analytics in the beta timeline or after it. I do think we'll want to rewrite it to use this work (and sw-lib) before I/O.

Any takers? :)

**Comment by jeffposnick** [comment]
Pinging @prateekbh, who had expressed interest in working on this.

**Comment by gauntface** [comment]
Would anyone object to this including the Measure Protocol API?

This would allow a stronger value proposition for using the library and could be a nice entry point to "add plugins" - i.e. add web push plugin.

**Comment by philipwalton** [comment]
I've actually started working on a basic Measurement Protocol wrapper library than can run in a browser, worker, or node. @gauntface, I'd be happy to collaborate if you want.

**Comment by addyosmani** [comment]
@philipwalton Per the team meeting the other day, adding you as the owner for the offline analytics migration if that's okay. @prateekbh will be a collaborator on it helping you through questions on how the background sync implem works.

**Comment by addyosmani** [comment]
@philipwalton @prateekbh Could we post a public status on where we're at with the offline analytics V2 work? If we're low on cycles to complete the rewrite, could you let us know so we can reassign as needed?

**Comment by prateekbh** [comment]
I am definitely out of bandwidth to take this up. I can help if @philipwalton, but a major contribution would be really tough

**Comment by addyosmani** [comment]
Call from the meeting today is we're dropping this to P1 given we don't yet have a prototype ready. If this changes, we'll raise it up.

**Comment by addyosmani** [comment]
@philipwalton has been taking a renewed look at both background sync and the offline-analytics library lately. We're going to keep this at a P1 for now, but work has definitely started on it.

**Comment by gauntface** [comment]
I'm going to close this since we've landed the renewed background sync and the analytics library to match and this will be what is launched in V3.
