### ISSUE TITLE
The wizard validation procedure not corresponds to the error message

### ISSUE THREAD

**Issue by WangLeto** [GoogleChrome/workbox#2447]
https://github.com/GoogleChrome/workbox/blob/43406c78aa541b4a713181f16dc738c543a8ef22/packages/workbox-cli/src/lib/assert-valid-sw-src.js#L14
In this `assert-valid-sw-src.js`, `/\.precacheAndRoute\(\s*\[\s*\]\s*\)/` is used to check sw file content, while the errors show `self.__WB_MANIFEST` should be contained.

https://github.com/GoogleChrome/workbox/blob/43406c78aa541b4a713181f16dc738c543a8ef22/packages/workbox-cli/src/lib/errors.js#L30

**Comment by jeffposnick** [comment]
Thanks for pointing that out! I'll get that fixed.

**Comment by jeffposnick** [comment]
This is fixed in the `v5.1.3` release: https://github.com/GoogleChrome/workbox/releases/tag/v5.1.3
