### ISSUE TITLE
Firefox: Fetch event handlers must be added during the worker script’s initial evaluation

### ISSUE THREAD

**Issue by peter-stoyanov** [GoogleChrome/workbox#2448]
I have a jhipster generated angular app. I want to add service worker. 

The main idea is to listen for new service worker installations and inform the user that a new version is available.

**Library Affected**:
*"workbox-window": "5.1.2", "workbox-webpack-plugin": "5.1.2"*

**Browser & Platform**:
*Firefox 74.0.1.*

**Issue or Feature Request Description**:
It all works in Chrome Version 80.0.3987.149, but I get the following error in Firefox 74.0.1: 

**Fetch event handlers must be added during the worker script’s initial evaluation.**

My webpack plugin config:
```
ew WorkboxPlugin.GenerateSW({
            clientsClaim: true,
            skipWaiting: true,
            exclude: [/swagger-ui/],
            runtimeCaching: [
                {
                    urlPattern: /\.(?:css|js|html|json)$/,
                    handler: 'StaleWhileRevalidate',
                    options: {
                        cacheName: 'appCache',
                        expiration: {
                            maxAgeSeconds: 60 * 60 * 24
                        },
                        broadcastUpdate: {
                            channelName: 'update-appCache'
                        }
                    }
                },
                {
                    urlPattern: /\.(?:png|jpg|jpeg|svg|gif|eot|ttf|woff|woff2)$/,
                    handler: 'StaleWhileRevalidate',
                    options: {
                        cacheName: 'assetCache',
                        broadcastUpdate: {
                            channelName: 'update-assetCache'
                        }
                    }
                },
                {
                    urlPattern: /^https:\/\/fonts\.googleapis\.com/,
                    handler: 'StaleWhileRevalidate',
                    options: {
                        cacheName: 'google-fonts-stylesheets',
                        broadcastUpdate: {
                            channelName: 'update-googleFontsCache'
                        }
                    }
                },
                {
                    urlPattern: /^https:\/\/fonts\.gstatic\.com/,
                    handler: 'CacheFirst',
                    options: {
                        cacheName: 'google-fonts-webfonts',
                        broadcastUpdate: {
                            channelName: 'update-googleFontsCache'
                        },
                        cacheableResponse: {
                            statuses: [0, 200],
                        },
                        expiration: {
                            maxAgeSeconds: 60 * 60 * 24 * 365,
                            maxEntries: 30,
                        }
                    }
                }
            ]
        })
```

I am registering the service worker in ngOnInit hook of my root angular component:
```
import { Workbox } from 'workbox-window';

if ('serviceWorker' in navigator) {
            const wb = new Workbox('/service-worker.js');

            // THIS EVENT IS LOGGED JUST FOR DEBUGGING PURPOSES
            wb.addEventListener('activated', event => {

                if (!event.isUpdate) {
                    console.log('Service worker activated for the first time!', { event });

                } else {
                    console.log('Service worker activated!', { event });
                }
            });

            wb.addEventListener('installed', event => {
                console.log('Service worker installed!', { event });

                if (event.isUpdate) {
                    this.confirmationService.confirm({
                        key: 'session',
                        message: `New version is available!. Click OK to refresh.`,
                        acceptLabel: 'OK',
                        accept: () => {
                            this.windowRef.getNativeWindow().location.reload();
                        }
                    });
                }
            });

            // Register the service worker after event listeners have been added.
            wb.register()
                .then(registered => console.log({ registered }))
                .catch(error => console.log({ error }));
        }
```
		
I thought that by connecting the event handlers to the Workbox object before calling register() in the end is exactly what is meant by the error message, but apparently I'm wrong.

**Comment by jeffposnick** [comment]
(This doesn't have to do with your `workbox-window` code.)

I can reproduce the logged message in Firefox 74 when visiting any site that uses `rollup-plugin-off-main-thread` to load a script in a service worker via `importScripts()` inside of a `Promise`, when that script contains an `addEventListener('fetch', ...);`. The default `WorkboxPlugin.GenerateSW()` output will produce a service worker that behaves that way. (Yes, the `webpack` plugin uses Rollup under the hood...)

Here's a few things:

- As far as I can tell, this warning message in Firefox doesn't actually affect the behavior of the service worker. (I.e. it's noise, but things should still work.) Let me know if you see actual breakage in Firefox 74.

- You can set `inlineWorkboxRuntime: true` in your `GenerateSW()` config to cause all the service worker code to be included in a single output file, in which case the `addEventListener()` call should definitely be made as part of the initial service worker script evaluation.

- I looked into this in the past (https://github.com/GoogleChromeLabs/proxx/issues/470), and was told that this `rollup-plugin-off-main-thread` was spec compliant, so my assumption is that Firefox is mistaken by logging a warning here. 

In any case, I'm going to follow up with the `rollup-plugin-off-main-thread` authors and pull in some folks familiar with Firefox to see what's up.

**Comment by jeffposnick** [comment]
(See https://github.com/surma/rollup-plugin-off-main-thread/issues/24 for follow-ups.)

**Comment by jeffposnick** [comment]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1629125, the logged message is due to a bug in Firefox, and no changes are necessary on the Workbox side of things.

**Comment by peter-stoyanov** [comment]
With the suggested inlineWorkboxRuntime: true in the GenerateSW() config the error messages disappeared.

I also started seeing the 'activated' and 'installed' event handlers in my sample code triggered on initial service worker registration.

The only issue I still have is that after the first service worker registration, when I have an updated version of it I'm not getting the event handlers triggered - and at the same time they are triggered in Chrome. But I need to investigate further first in order to be sure that something else is not interfering.

Thanks a bunch.
