### ISSUE TITLE
0   I got a error; the worbox precaching my Static files，for example js or css；At this time I setted workbox.routing.registerRoute is don't work；

### ISSUE THREAD

**Issue by liusu0913** [GoogleChrome/workbox#2450]
I had a problem with this bag; The address of the question is https://stackoverflow.com/questions/61189799/why-my-setted-workbox-routing-registerroute-is-not-work-when-i-setted-workbox-pr

**Comment by jeffposnick** [comment]
I've responded at https://stackoverflow.com/questions/61189799/using-runtime-caching-and-precaching-together-in-workbox/61191059#61191059
