### ISSUE TITLE
Bad pre-caching response: manifest.webapp - 404

### ISSUE THREAD

**Issue by Legends** [GoogleChrome/workbox#2454]
I basically want my web app also to be a PWA (offline usable), so instead of doing it on my own I use the `workbox-webpack-plugin v5.1.2` .
The error appears on page load of the web app.

**Library Affected**:
`const {GenerateSW} = require('workbox-webpack-plugin');`

**Browser & Platform**:
Google Chrome is up to date
Version 81.0.4044.92 (Official Build) (64-bit)

**Issue or Feature Request Description**:
*Your request here.*
![image](https://user-images.githubusercontent.com/966368/79263807-d2ca7f80-7e93-11ea-84ab-2e2b65649c2b.png)

**webpack.config:**
```
 new GenerateSW({
            swDest: 'sw.js',
            clientsClaim: true,
            skipWaiting: true,
          })

```
It gives me a 404, but the manifest is there!

I have also added the mime-type to my IIS Server:

![image](https://user-images.githubusercontent.com/966368/79264239-86cc0a80-7e94-11ea-8f88-6f6f4567472c.png)

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
If you're able to point us to a public URL where this is reproducible, that would be great.

If not, could you try running `fetch('/assets/manifest.webapp').then(console.dir)` in the JS console when you have your web app open, and expand the logged `Response`, then copy the properties set on it?

**Comment by Legends** [comment]
I've registered a wrong `mime-type`. Sorry for the noise !

Thank you!
