### ISSUE TITLE
How to precache hashed files (/build/static) at the time of service worker installation using workbox in react application

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [GoogleChrome/workbox#2458]
I have created a react application in which I trying to make it a progressive web app for that I am using workbox. Using that I am able to precache images but I also want to precache all the hashed files inside /build/static/js,/build/static/CSS and entire build folder at the time of service worker installation but I am unable to achieve that. When I visit a particular page then only it is caching the hashed files otherwise not. How do I cache all the hashed files and images at the time of service worker installation. Please suggest any solution to this.

**Comment by jeffposnick** [comment]
The specific steps to follow depend on what type of build system you're using. You mentioned that you're using React, so I'm assuming you're using `webpack` for your build.

There's a `workbox-webpack-plugin` that can create a service worker for you that automatically precaches assets created by `webpack`.

You can read more about it at https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generatesw_plugin

The basic idea is to add the following to your `webpack` config:

```
const {GenerateSW} = require('workbox-webpack-pluguin');

module.exports = {
  // ...your webpack config goes here...
  plugins: [
    // ...your other plugin config goes here...
    new GenerateSW({
      // Customize options as needed. See:
      // https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW
    }),
  ],
};
```

You'll end up with a service worker file generated in your output directory. You can then [register](https://developers.google.com/web/fundamentals/primers/service-workers#register_a_service_worker) that service worker and it will precache your assets and keep them up to date.

**Comment by anchal-chouvhan-altius** [comment]
Thank you jeffposnick. Will try this solution.

**Comment by anchal-chouvhan-altius** [comment]
Thank you Jeff. It worked. One more thing I would like to ask is that the application works fine on google chrome but the install button doesn't comes up on firefox. Do I need to make additional settings for install button to appear on firefox(assets are there in cache)?

**Comment by jeffposnick** [comment]
If you're talking about installation as described at https://web.dev/promote-install/, that's browser-specific and Firefox may be different from Chrome in that regard. I'm afraid dealing with those differences is outside of the scope of what Workbox can help with.
