### ISSUE TITLE
How to detect a service worker installation failure?

### ISSUE THREAD

**Issue by PeteCoward** [GoogleChrome/workbox#2460]
**Library Affected**:
*workbox-precache* *workbox-window*

**Browser & Platform**:
*all browsers*

**Issue**:
I use InjectManifest through webpack to build a serviceworker that precaches my assets and I use workbox-window to register that serviceworker.
I would like to know if there is any approved way to detect the failure of `Workbox.register()`

My specific need is to detect when one of the assets I am pre-caching fails, due to bad network.
I'd like to know to show a retry button, or some kind of indication of failure in the interface.

I delete one of my assets from the server, and try a fresh service worker install. The dev logs give me good indication what is happening, and I am happy it fails to install, I just want to reliably detect it happening in code.

A `WorkboxError('bad-precaching-response')` is raised but I do not know where to listen for it!

I tried
1. wrapping `wb.register()` in a try catch 
2. listening to all documented events on Workbox. 
3. wrapping the call to precacheAndRoute in the service worker in try catch. 
4. logging in `self.addEventListener('error',...` in the service worker

https://plnkr.co/edit/jymNXaeLvsZU1OJx?preview

**Comment by jeffposnick** [comment]
In the scenario you describe, where there's an error thrown while performing precaching, registration is successful, but the installation process fails.

When that happens, the `ServiceWorker` object associated with the registration will transition from the `installing` state to the terminal error state, which is `redundant`.

You can detect this failure using `workbox-window` by listening for the [`redundant` state change](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox#event:redundant) event:

```
wb.addEventListener('redundant', (event) => {
  // Handle installation failure here.
});
```
