### ISSUE TITLE
Typo in the "Using Bundler" guide

### ISSUE THREAD

**Issue by AdrienPoupa** [GoogleChrome/workbox#2465]
There is a typo on this page: https://developers.google.com/web/tools/workbox/guides/using-bundlers

Instead of

```js
import {Plugin as ExpirationPlugin} from 'workbox-expiration/Plugin.mjs';
```
it should read
```js
import {ExpirationPlugin} from 'workbox-expiration/ExpirationPlugin.mjs';
```

Sorry if this is not the right place to report this, I saw nothing on the page itself

**Comment by philipwalton** [comment]
Thanks! I filed https://github.com/google/WebFundamentals/pull/8650 to fix this.
