### ISSUE TITLE
[FEATURE REQUEST] Logging integration

### ISSUE THREAD

**Issue by Sominemo** [GoogleChrome/workbox#2467]
**Library Affected**:
workbox-core

**Feature Request Description**:
I propose dispatching custom events for log messages for any env mode, so it's possible to collect and process them by own logger. 
Currently, Workbox uses internal logger for outputting info and errors into dev console. Also, before logging it checks every time if the app was built not in production mode.

**Comment by jeffposnick** [comment]
Hello @Sominemo!

The expectation is that most users will end up with the conditional logging checks removed during the process of either bundling their service worker for production/development (if they're consuming Workbox via the ES modules we provide) or end up using either the pre-built production or development bundles loaded by `workbox-sw` (if they're using Workbox from the CDN). Either way, the `if(process.env.NODE_ENV === 'production')` conditional statements end up being removed.

It's not very likely that we'll support arbitrary logging via some abstract mechanism, but hearing more about your use case—what's the interface that you would expect Workbox's logging code to talk to?—could help determine whether it's feasible or not.

**Comment by Sominemo** [comment]
I am using my own logging wrapper and some `onerror` listeners, so I can collect console output and errors to be easily sent and analyzed if needed. In this time, there's no possibility to watch Workbox's logging messages programmatically. I would suggest using [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) with `detail` field as a cross-browser solution for broadcasting debug info to be collected.

**Comment by philipwalton** [comment]
Hey @Sominemo, as Jeff said, we strip out all logging code in our productions builds, and we strongly encourage all Workbox users to do the same. The logging code increases the size of Workbox quite a bit, and for the vast majority of the logs, there's no end-user value.

For your own logging, however, I suspect you might be able to get most of what you need via a custom plugin. Could you take a look at the proposal in https://github.com/GoogleChrome/workbox/issues/2446 and let me know what you think? For context, we're likely going to switch all of our strategy logging code to use custom plugins in the future.

**Comment by Sominemo** [comment]
@philipwalton, Looks good! Will be waiting for release and documentation.
