### ISSUE TITLE
Broken skip waiting process when service worker gets updated multiple times

### ISSUE THREAD

**Issue by andreme** [GoogleChrome/workbox#2470]
**Library Affected**:
*workbox-window*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
I'm basically following this recipe: https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users
The prompt that is offered to the user is not blocking, so the user can keep working without updating immediately.

The problem I encounter is that after the service worker has been updated 2 times without the user reloading my app, I'm not receiving an event when the service worker is updated for the 3rd time, and hence I don't know where to send the skip waiting event to.

Scenario:
1. App is running, only open in 1 tab
2. Service worker is updated
App receives the waiting event and handle to new SW
App displays non blocking reload prompt
User does not reload
3. Service worker is updated again
App receives the externalwaiting event and handle to new SW
App is still displaying non blocking reload prompt
User does not reload
4. Service worker is updated again
App does **not** receive waiting or externalwaiting event, and of course **not** the handle to the new SW
App is still displaying non blocking reload prompt
5. User tries to reload through prompt
Since the app does not have the handle for the most recent SW, nothing happens

The change from waiting to externalwaiting event is caused by _updateFoundCount.
Not a problem, but it doesn't make sense to me, looks like the code only ever expects 1 waiting update.
https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-window/src/Workbox.ts#L347

The reason for the missing externalwaiting event on the 3rd update is that the updatefound event listener is removed when the first "external" event is encountered:
https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-window/src/Workbox.ts#L363
Commenting out that line fixed my problem.

**Comment by andreme** [comment]
I've found a workaround that works for me reliably. Storing the registration object from register and then sending the message to the registration.waiting SW.
```js
registration = await wb.register();

navigator.serviceWorker.addEventListener('controllerchange', () => {
	window.location.reload();
});

// ...

function updateServiceWorker() {
	if (registration?.waiting) {
		messageSW(registration.waiting, {type: 'SKIP_WAITING'});
	}
}
```

**Comment by jeffposnick** [comment]
I feel like https://github.com/GoogleChrome/workbox/issues/2394 might take care of this—if so, let's close this in favor of prioritizing that issue.

**Comment by freshlymadebread** [comment]
I had the same problem.
The key issue is that the waiting message is not received in app ，not messageSW  does not work.

messageSkipWaiting cant help me.
