### ISSUE TITLE
navigation preload not for anything other than html

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2472]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

Hi @jeffposnick , I wanted to make sure of something that I've read on workbox's website. 

`
Developers who are already handling navigations by responding with precached HTML (potentially configured with an App Shell fallback) do not need to enable navigation preload! This feature is intended to reduce navigation latency for developers who can't precache their HTML, but still want to use Workbox to handle caching of other assets on their sites.
`

So, If we look at my case, I have a single page app. I precache `index.html` and lots of other assets(images, css, js) and so on.  There're routes for which I have different cache strategies, but I am sure this thing is most related to `networkFirst` strategy. I have 5 `json` files which I use `networkFirst` strategy.

When user comes back to my app after some other website, service worker boot time takes some time, which means `navigation request` (index.html - even though it's gonna come back from cache still has to wait until boot time is done) will start after the boot time which means that my `networkFirst` routes for those 5 `json` files won't get made(at least this is what the article of jake archibald's says) until boot time + time for fetching index.html(from cache, but still boot time is there) are done. So if `navigationPreload` was there, what would happen is `index.html` request wouldn't have to wait for boot-up time which means that requests for those `5 json` files would be made quicker.

Don't we need to have `navigationPreload` for this scenario? or am I missing something?

**Comment by jeffposnick** [comment]
If you're serving `index.html` cache-first as part of a SPA, you don't need navigation preload.

Navigation preload will start making a network request for the URL being navigated to, which might not actually be `index.html`, in the case of a SPA—it would be the actual URL in the address bar. Even if the network were to return a response for that URL before the service worker actually starts up, the response won't be passed from the service worker to the browser (via `event.respondWith()`) until the service worker does start up.

Navigation preload gives you a "head start" when you have to go to the network anyway, but it does not allow a navigation response to be used until the service worker has started up. The request for the hypothetical five JSON files still won't happen much sooner.

**Comment by novaknole** [comment]
@jeffposnick Just a little bit of observation.

I might argue with this as I have little experience with `navigation preload` . The whole idea with that feature is that it starts making the requests in parallel .before service worker starts up. 

Let's say that I use `networkFirst` for all routes in my app.

Assumption 1)

Let's assume the following then:
* start up of service worker takes `250ms`. 
*  `index.html` response takes `100ms`.
* my `json` file (which lives on other server) takes `150`ms.

Now it looks to me that before service worker start up is done, with navigation preload, `index.html` and `json` would already be downloaded. So I'd get the final resonse with `index.html` and `json` in `250ms` overal. Isn't that right?

Assumption 2)

Okay, now, let's say that `index.html` is cacheFirst. Even if that's the case, my `json` file would still be downloaded before service worker start up is done. So I don't see any issues with it. Isn't that right?

Assumption 3)

Maybe what you're referring is that `navigation preload` is only for the `navigation url` request  and it doesn't work for plain `GET` requests other than navigation. In this case, because I use `axios` to return my `json` , maybe navigation preload doesn't get activated for these kind of requests? is that right?

**Comment by jeffposnick** [comment]
Your assumption 3 is basically right. The navigation preload request is only made for the URL that you're actually navigating to, which will be an HTML document.

The browser has no way of knowing that it should also fetch those JSON files until the service worker has called `event.respondWith()` and provided the HTML to the process that's responsible for rendering the HTML. It's only at that point that the browser would act on any `<link rel="preload">` or JavaScript calls to `axios`, or however else you're loading your JSON.

(There is a concept called [HTTP/2 server push](https://www.smashingmagazine.com/2017/04/guide-http2-server-push/) that allows a web server to start sending additional responses for resources the browser hasn't even asked for yet, but it's [problematic](https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/), and not widely used.)
