### ISSUE TITLE
Upgrade "stuck" devDependencies

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2479]
This is a meta-issue to track some `devDependecies` in our top-level `package.json` that I can't find a way to upgrade cleanly.

- [x] `@octokit/rest`: The API changed fairly significantly, and the last time I tried updating it, our GitHub publish process broke.
- [ ] `service-worker-mock`: There are additional mocks that ended up breaking our unit tests.
- [x] `rollup`: When I tried updating it, our "hack" to include the versioning info in the final bundles broke.

**Comment by philipwalton** [comment]
> * `rollup`: When I tried updating it, our "hack" to include the versioning info in the final bundles broke.

My guess is this is because we mark our modules as "pure", which technically the version modules are not.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
