### ISSUE TITLE
Typos in jsdoc

### ISSUE THREAD

**Issue by Mister-Hope** [GoogleChrome/workbox#2482]
See https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/generate-sw.js#L50-L52

```js
 /* @param {boolean} [config.cleanupOutdatedCaches=false] Whether or not Workbox
 * should attempt to identify an delete any precaches created by older,
 * incompatible versions.
 */
```

I am not a native English speaker BTW, but what is `identify an delete any precaches`, why do we use `an`, and what's the structure of this?

**Comment by philipwalton** [comment]
Thanks for letting us know. That should read: "...identify **and** delete...".

**Comment by Mister-Hope** [comment]
Mind fixing it so I can close the issue? Just a simple commit.

**Comment by jeffposnick** [comment]
It's fixed in https://github.com/GoogleChrome/workbox/pull/2504
