### ISSUE TITLE
Inject Manifest exclude and NavigationRoute exclude

### ISSUE THREAD

**Issue by nitzanashi** [GoogleChrome/workbox#2491]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers.

**Issue or Feature Request Description**:
I hope I'm not wrong with the configuration and it's rather a feature request then miss-config.
When using `exclude` in `InjectManifest`, I still need to define `exclude` for `NavigationRoute` in the service worker file, the suggestion is to make `exclude` in `injectManifest` global on all route Registration inside service worker file

my current setup for example:

webpack.config.js
```
                new WorkboxPlugin.InjectManifest({
                    swSrc: './projects/app/config/service-worker.js',
                    swDest: 'service-worker.js',
                    exclude: [
                        /token-[^-]*\.json/,
                        /\.(?:map)$/,
                    ],
                }),
```

serivce-worker.js
```
const CACHE_NAME = 'offline-app';
const FALLBACK_HTML_URL = '/index.html';

precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', async (event) => {
    // @ts-ignore
    await event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.add(
                new Request(FALLBACK_HTML_URL, {credentials: 'same-origin'}),
            )),
    );
});

navigationPreload.enable();

/** @param {import('workbox-core/types.js').RouteHandlerCallbackOptions} params */
const navigationHandler = async (params) => {
    try {
        // Attempt a network request.
        return await new NetworkFirst().handle(params);
    } catch (error) {
        // If it fails, return the cached HTML.
        return caches.match(FALLBACK_HTML_URL, {
            cacheName: CACHE_NAME,
        });
    }
};

// Register this strategy to handle all navigations.
registerRoute(
    new NavigationRoute(navigationHandler, {
        denylist: [
            /token-[^-]*\.json/,
            /\.(?:map)$/,
        ],
    }),
);
```

Thanks a lot guys keep up the good work! 🖤

**Comment by jeffposnick** [comment]
I think we need to keep those as separate configuration options.

The `exclude` option in the `webpack` config applies a predicate to the list of `webpack` assets.

The `denylist` option in the `NavigationRoute` constructor applies a predicate to the URL being navigated to.

A `webpack` asset may or may not correspond to an actual URL on a web server. Additionally, the set of URLs that you want to exclude from your navigation route matching won't necessarily correspond to the set of `webpack` assets that you want to exclude from precaching.
