### ISSUE TITLE
setCatchHandler is not being triggered offline

### ISSUE THREAD

**Issue by olso** [GoogleChrome/workbox#2492]
**Library Affected**:
workbox-routing/setCatchHandler 5.1.3

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
<img width="1792" alt="Screenshot 2020-05-04 at 14 05 22" src="https://user-images.githubusercontent.com/7975158/80964082-89c17780-8e10-11ea-8d41-11e50ea34c25.png">

**Comment by olso** [comment]
Okay, I found https://stackoverflow.com/questions/57437835/service-worker-serve-offline-html-instead-when-offline

But, how do I registerRoute if I don't have `.html` extension?

My url is coming from SSR like `https://localhost/`

**Comment by olso** [comment]
Okay, so now I have

```js
registerRoute(
  /^https:\/\/res\.cloudinary\.com/,
  new CacheFirst({
    cacheName: "images-cloudinary",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: THREE_MONTHS_IN_SECONDS,
        purgeOnQuotaError: true,
      }),
    ],
  }),
  "GET",
);

setDefaultHandler(new NetworkOnly());

// https://developers.google.com/web/tools/workbox/guides/advanced-recipes#comprehensive_fallbacks
setCatchHandler(({ event }) => {
  switch (event.request.destination) {
    case "document": {
      return matchPrecache("/pwa-offline.html");
    }

    default:
      return Response.error();
  }
});
```

which seems to work, but how do I know if

```js
registerRoute(
  /^https:\/\/res\.cloudinary\.com/,
```

is still in effect? @jeffposnick

**Comment by olso** [comment]
This seems to work

```js
registerRoute(
  /^https:\/\/res\.cloudinary\.com/,
  new CacheFirst({
    cacheName: "images-cloudinary",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: THREE_MONTHS_IN_SECONDS,
        purgeOnQuotaError: true,
      }),
    ],
  }),
  "GET",
);

setDefaultHandler(new NetworkOnly());

// https://developers.google.com/web/tools/workbox/guides/advanced-recipes#comprehensive_fallbacks
setCatchHandler(({ event }) => {
  switch (event.request.destination) {
    case "document": {
      return matchPrecache("/pwa-offline.html");
    }

    default:
      return Response.error();
  }
});
```

Even tho, it's not really clear if

```js
registerRoute(
  /^https:\/\/res\.cloudinary\.com/,
```

is being overriden by

```js
setDefaultHandler(new NetworkOnly());
```

@jeffposnick Could you clear it up for me please? 😌

Also, thanks for all the great work!

**Comment by jeffposnick** [comment]
The strategy registered with `setDefaultHandler()` will only be invoked if there are no other matches for `Route`s registered with the same `Router`. If your `registerRoute()` call for your Cloudinary assets does match, then that route will take precedence over your default.

It also worth noting that you can just leave out `setDefaultHandler(new NetworkOnly())`. If Workbox's `Router` doesn't match the request at all, then that's equivalent to the service worker's `fetch` handler not calling `respondWith()`. In that situation, the browser will just make the request against the network, like it would if there were no service worker involvement at all. That's effectively the same behavior you'd get from registering a default handler of `NetworkOnly`.
