### ISSUE TITLE
Can't find workbox-precaching or workbox-background-sync in Typescript

### ISSUE THREAD

**Issue by DaveShuckerow** [GoogleChrome/workbox#2494]
In my tsconfig, if I set
```
  "module": "es6",
```
Then I can't import workbox-background-sync or workbox-precaching.

If I set `  "module": "commonjs",`, then those packages work.

workbox-routing and workbox-strategy work correctly regardless of the module setting.

**Comment by jeffposnick** [comment]
CC: @philipwalton who knows more about this sort of thing.

This might be due to https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies?

> Module Resolution Strategies 
> There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. If not specified, the default is Classic for --module AMD | System | ES2015 or Node otherwise.

Does setting `moduleResolution` to `node` help?

**Comment by DaveShuckerow** [comment]
> Does setting `moduleResolution` to `node` help?

Yes.  I can use 

```
  "module": "es6",
  "moduleResolution": "node"
```

Thanks for the workaround Jeff, and let me know if you need additional input to create a repro case.

**Comment by jeffposnick** [comment]
To revisit this, I think this might have been due to https://github.com/GoogleChrome/workbox/pull/2544

Can you try things again after updating to the latest Workbox release, v6.0.2?

**Comment by tropicadri** [comment]
Given the workaround, and that we've released new updates to Workbox, I'm going to close this issue.

If you're still running into this issue with the current version we can reopen at that point.
