### ISSUE TITLE
workbox get jwt token in service worker.

### ISSUE THREAD

**Issue by nnikka** [GoogleChrome/workbox#2495]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

Hi @jeffposnick,

I've been struggling to find anything that helps a little bit for my scenario... I've posted a question on stackoverflow and have given it bounty of +350, but still no luck. So I thought, I would ask here... 

you have to read this to completely grasp the idea of what i am trying to accomplish.  Sorry for this huge question..

https://stackoverflow.com/questions/61559039/how-to-get-jwt-token-in-service-worker

Is there any workbox way that gives me the best option to proceed? i know that workbox doesn't have `push` notifications implemented as a plugin, but still, maybe what i am asking can still be done with workbox's way. I've posted this question many places, but with no response(looks like folks haven't experienced this one). 

I am using workbox for `caching` , `background sync`,  and many advanced stuff (such as `workbox-window`). I thought you might be familiar with what i am asking and what you'd recommend from your experience.

Thanks in advance.

**Comment by jeffposnick** [comment]
I'm sorry, but no, this isn't an area where Workbox comes into play.

Also, I don't personally have any experience with best practices related to securing JWTs and I can't speak with authority about how you should proceed.
