### ISSUE TITLE
How to set PrecacheController's  fetch fallback

### ISSUE THREAD

**Issue by bailnl** [GoogleChrome/workbox#2502]
**Library Affected**:
*workbox-precaching*

**Issue or Feature Request Description**:
How to set PrecacheController's  fetch fallback

**Comment by jeffposnick** [comment]
That's not something you have control over in v5. The hardcoded behavior is to always fail back to the network if for some reason there's a cache miss when attempting to retrieve a precached response.

In v6, this should theoretically be possible once https://github.com/GoogleChrome/workbox/pull/2459 is finalized.
