### ISSUE TITLE
Multiple errors - cannot register service worker

### ISSUE THREAD

**Issue by joetidee** [GoogleChrome/workbox#2506]
We recently released the workbox service worker into production only to receive a lot of errors in our monitoring application saying that the service worker failed to register. This was across multiple browsers and platforms:

Safari 12.4.6 (Mobile)
Safari 12.4.5 (Mobile)
Safari 12.1.2 (Mobile)
Safari 12.4.1 (Tablet)
Safari 13.1 (Desktop)
Safari 13.0 (Desktop)
Edge 18 (Desktop)
Safari 12.3.1 (Tablet)
Chrome 80 (Tablet)
Chrome 81 (Desktop)
Chrome 60 (Desktop)
Chrome 44 (Tablet)
etc...

Some errors contained `at promiseReactionJob in [native code]`, others no message.

Locations of the errors within the transpiled `sw.js` file varied:
Line 203 : Column 34
Line 599 : Column 34
Line 606 : Column 34
Line 607 : Column 13
Line 613 : Column 34
Line 623 : Column 34
Line 627 : Column 34
Line 629 : Column 34
Line 737 : Column 25
Line 780 : Column 34
Line 1240 : Column 34
etc...

Unfortunately, with this release we did not have source maps generated.

Here is the code that raised the error:
```
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function serviceWorker() {
        navigator.serviceWorker.register('/sw.js').catch(function logServiceWorkerError(registrationError) {
            const err = new Error('Service Worker registration failed.');
            // Send error to monitoring application.
        });
    });
}
```

Here is the plugin setup:
```
new GenerateSW({
            babelPresetEnvTargets: ["> 2%"],
            cacheId: 'osp',
            cleanupOutdatedCaches: true,
            clientsClaim: true,
            exclude: [/\.map$/, /stats\.json$/],
            inlineWorkboxRuntime: true,
            runtimeCaching: [
                {
                    urlPattern: /^https:\/\/fonts\.googleapis\.com.*/,
                    handler: 'StaleWhileRevalidate',
                },
            ],
            skipWaiting: true,
            sourcemap: false,
            swDest: 'sw.js',
        }),
```

**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*Lots, see above.*

**Comment by jeffposnick** [comment]
This sounds like it might be the same thing as https://github.com/GoogleChrome/workbox/issues/2493? I'm going to close this one with the assumption that it is. If for some reason it's not, we can reopen and investigate further.

**Comment by joetidee** [comment]
Not sure that I follow. #2493 was to do with the `regeneratorRuntime` not being present in a bundle that was being served to 'legacy' browsers (?). Whereas, this is about seems to be about the service worker not able to register in modern browsers.
