### ISSUE TITLE
cachedResponseWillBeUsed should return null if 'expire-custom-caches-only' is thrown

### ISSUE THREAD

**Issue by jketcham** [GoogleChrome/workbox#2507]
**Library Affected**:
*workbox-expiration*

**Browser & Platform**:
*all browsers*

---

I ran into this issue recently when I upgraded from 5.0.0-rc.1 to 5.1.3.

In my service worker, I had tried to use `setCacheNameDetails` from workbox-core to set custom names for my caches, but for some reason it never worked.

Until I upgraded to 5.1.3.

Unfortunately, I had just left the custom cache names in and didn't think about it. So when the new cache name's were set, and a request was matched to the old cache name, an [`expire-custom-caches-only`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-expiration/src/ExpirationPlugin.ts#L107) error was thrown when called from the [`cachedResponseWillBeUsed`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-expiration/src/ExpirationPlugin.ts#L149) method, which doesn't get handled.

Given that the name for this method is `cachedResponseWillBeUsed`, it doesn't seem to me like this method should fail if there's a cache name mismatch. In that situation, I'd expect the cached response to just not be used.

Does it seem like a reasonable change to catch the `expire-custom-caches-only` error in this method and just return null?

---

Regarding the error message itself, it seems a little opaque to me (this is what is shown in the console for a production build):
```
expire-custom-caches-only: expire-custom-caches-only :: [null]
```

I'm not familiar with how workbox handles these logging details, but maybe something more description could be included here.

---

And for those who do want to move their cache names over to something new, I'm guessing the correct way to handle that is to explicitly clear the old cache objects in the service worker on install? Using something like [deleteCacheAndMetadata](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-expiration.ExpirationPlugin)? Maybe there could be another helper that does this only for specific cache objects in the future?

I didn't see anything in the workbox-expiration docs call this situation out (where changing cache names can throw an error like this), so that might be nice to include as well. I could have missed where that is mentioned though.

Thanks!

**Comment by jketcham** [comment]
Well I did some more digging and I see that a custom cache name needs to be set when used with the ExpirationPlugin (wasn't the case in v5-rc.1), so setting that has now fixed this issue from occurring for me. I thought it was purely related to the new custom cache names.

And I can confirm the error message in development is much more clear as well.

**Comment by jeffposnick** [comment]
Hmmm... the custom cache name requirement has been around since [at least Workbox `v3.0.0`](https://github.com/GoogleChrome/workbox/blob/v3.0.0/packages/workbox-cache-expiration/Plugin.mjs#L91), so I'm not sure why it wasn't triggered for you prior to updating to `v5.1.3`. The determination as to whether the expiration applies to a default cache name or not might have been muddled by your usage of different values passed to `setCacheNameDetails()` over time, though.

Could you distill your experience into a takeaway for the Workbox team? Our production error messages are deliberately more concise to reduce the overall bundle size, but I'm not 100% sure about that `[null]` that was logged. Would better documentation for the `workbox-expiration` library have helped?

**Comment by jketcham** [comment]
The main takeaway would be confusion over requiring a custom cache-name to be set when using the ExpirationPlugin, and when one isn't set, all of the requests using an expiration policy will fail. This is made a little more confusing because if there is not a cached response, the request will succeed at first, but subsequent requests will fail because it doesn't find a custom cache-name.

It doesn't look like the documentation for `workbox-expiration` mentions the cache-name requirement from what I've read on either the ['modules' page](https://developers.google.com/web/tools/workbox/modules/workbox-expiration) or the [api reference page](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-expiration.ExpirationPlugin).

I see this is the error message in development:
> expire-custom-caches-only: You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.

That would be helpful to have in the docs.
