### ISSUE TITLE
"DOMException: Quota exceeded" thrown even with "purgeOnQuotaError" enabled

### ISSUE THREAD

**Issue by mmazzarolo** [GoogleChrome/workbox#2509]
**Library Affected**:
`workbox-expiration@5.1.3`

**Browser & Platform**:
* Google Chrome  v81.0.4044.138 (Official Build) (64-bit) on MacOS*

**Issue or Feature Request Description**:
  Not sure if this is actually an issue or just the expected behaviour, but even when `purgeOnQuotaError` is enabled there's an uncaught thrown DOMException.  
Everything works fine on my side (cache is cleared correctly), so I'm wondering if bubbling the error is just a design choice. 
I tested it on Chrome (in incognito mode) and I can reproduce it consistently. 

<img width="521" alt="Screenshot 2020-05-13 at 19 09 53" src="https://user-images.githubusercontent.com/9536354/81843652-31941f00-954e-11ea-8c6f-3b1ddd279191.png">

P.S.: The 5 callbacks come from 4 strategies with `purgeOnQuotaError` + a custom `registerQuotaErrorCallback`.

**Comment by jeffposnick** [comment]
Yes, that DevTools console logging is expected. The code that automatically triggers the quota purges re-throws the underlying `DOMException` after they're run, so you'll end up seeing it logged if it's not caught elsewhere.

https://github.com/GoogleChrome/workbox/blob/04ba6442c466d2e8197fe586672143d201af3a61/packages/workbox-core/src/_private/cacheWrapper.ts#L301-L309
