### ISSUE TITLE
How to exclude files gerneated from a particular child compiler from __WB_MANIFEST

### ISSUE THREAD

**Issue by wood1986** [GoogleChrome/workbox#2510]
I wrote a webpack plugin which will generate js files for SSR in the child compiler. But I do not want `workbox-webpack-plugin` to precache these js files generated from this child compiler. The actual behaviour is these js files get injected into `self.__WB_MANIFEST`. I try to avoid the injection by not specifying `self.__WB_MANIFEST` in the src. But it shows `ERROR in Can't find self.__WB_MANIFEST in your SW source.`

you may suggest I could use regex to filter the chunks that I do not want. This is not scalable. But I want to filter a set of js files genreated from a child compiler.

The second question is why it is a must to have `self.__WB_MANIFEST` in src? If I understand correctly, I can use [this](https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_css_and_javascript_files) to do a on demand precache

**Comment by jeffposnick** [comment]
I don't think you need to use the `InjectManifest` plugin at all. Or the `GenerateSW` one.

Just write your service worker with the logic you'd like, using the Workbox ES module imports [as described here](https://developers.google.com/web/tools/workbox/guides/using-bundlers), and add your unbundled service worker as a new entry that will be compiled by `webpack` alongside your other entries.

The plugins are useful when you want to either generate an entire service worker automatically (`GenerateSW`) or when you want to use `workbox-precaching` to cache a bunch of assets in your compilation (`InjectManifest`). It sounds like you want more control than that, so just don't use them.
