### ISSUE TITLE
RouteHandlerCallbackOptions type is not conform to the doc

### ISSUE THREAD

**Issue by CircleCode** [GoogleChrome/workbox#2511]
**Library Affected**:
workbox-core (types exported)

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
According to the doc (https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~handlerCallback), options should be:

```js
export interface RouteHandlerCallbackOptions {
  request: Request;
  url?: URL;
  event?: FetchEvent;
  params?: string[] | {[paramName: string]: string};
}
```

but the type exported by workbox-core are https://github.com/GoogleChrome/workbox/blob/04ba6442c466d2e8197fe586672143d201af3a61/packages/workbox-core/src/types.ts#L36-L44

This type is too loose (`ExtendableEvent` instead of `FetchEvent` and `Request | string` instead of `Request`).

This makes it hard to use for example :

```js
const saveHandler: RouteHandler = ({ url, event, params }) => {
    let initid = params[1];
    let viewId = params[2];
    const workingRequest = event.request.clone();
```

which triggers `TS2339: Property 'request' does not exist on type 'ExtendableEvent'.`

neither

```js
  const saveHandler: RouteHandler = ({ url, event, params , request}) => {
    let initid = params[1];
    let viewId = params[2];
    const workingRequest = request.clone();
```

which triggers `TS2339: Property 'clone' does not exist on type 'string | Request'.   Property 'clone' does not exist on type 'string'.`

**Comment by jeffposnick** [comment]
CC: @philipwalton as I believe he was working on making this better for v6.
