### ISSUE TITLE
how to use `ignoreURLParametersMatching` for run-time caching?

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2512]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

Hi @jeffposnick 

I know it's possible to pass `ignoreURLParametersMatching` to precache so that it can ignore patterns in query string. I want to do the same thing, but for the run-time caching.

```js
registerRoute(
    new RegExp('test'),
    new NetworkFirst({
        cacheName: config.app.cache_names.app_flags
    })
)
```

where do I put `ignoreURLParametersMatching` ? is it even possible ?

**Comment by jeffposnick** [comment]
It's not possible to use `ignoreURLParametersMatching` directly as part of `workbox-routing`, but you can accomplish the same thing by using a [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~matchCallback) instead of a `RegExp` when defining your routes.

For example:

```
registerRoute(
  // This will match any request for /test?notIgnored=foo
  // with any other URL parameters effectively ignored.
  ({url, request}) => url.pathname === '/test' &&
                      url.searchParams.get('notIgnored') === 'foo',
  new NetworkFirst({cacheName: ...})
)
```

It's worth noting that we've [recently updated](https://github.com/google/WebFundamentals/pull/8680) our public documentation to prefer `matchCallback`s instead of `RegExp`s pretty much everywhere, as they're arguably simpler to think about. `RegExp`s haven't been deprecated, though, so you're free to continue to use either.

**Comment by novaknole** [comment]
@jeffposnick 

So, my url looks like this.

`https://example.com/insights?dateMin=484182831` . `dateMin` is gonna change for each time user refreshes the page. What happens now is everytime user refreshes the page, new entry gets added to the cache. If user goes offline, and refreshes the page, it won't find anything in cache since `dateMin` would be different timestamp each time..


With your proposed solution, I don't think it's gonna work..

**Comment by jeffposnick** [comment]
In that case, don't check for `dateMin` in your `matchCallback`. The point of the example is that you can include a check for anything that you care about, and leave out a check for anything you don't care about. You have complete control.

You're also asking about something separate from routing, which is how to remove a URL parameter from a cache key before it's read/written to the cache.

Workbox has a [`cacheKeyWillBeUsed` plugin callback](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) that do that for you.

Taking both parts together, here's what you could go with:

```
async function cacheKeyWillBeUsed({request, mode}) {
  const url = new URL(request.url);
  return url.origin + url.pathname;
  // Any search params or hash will be left out.
}

registerRoute(
  // This will match any request for /test?notIgnored=foo
  // with any other URL parameters effectively ignored.
  ({url}) => url.origin === 'https://example.com' &&
             url.pathname === '/insights',
  new NetworkFirst({
    cacheName: 'my-cache-name',
    plugins: [{cacheKeyWillBeUsed}],
  }),
)
```

See https://github.com/GoogleChrome/workbox/issues/2316 and https://github.com/GoogleChrome/workbox/issues/2084 for similar discussions.

**Comment by novaknole** [comment]
@jeffposnick  your example works like a charm.

One note BTW. I am using this for cross-origin request.

1) The line `return url.origin + url.pathname;` in `cacheKeyWillBeUsed` still results in only `url.pathname`.  Not the whole path with `url.origin` too. Any way I can achieve to make `return url.origin + url.pathname;` work too ? 

2) my request url has two params in the url. I want to store data in cache with `origin+pathname+one search param`. Is there a way (any passed parameter which contains search params) or i should just use `url.search` ? `url.searchParams` is empty.

**Comment by jeffposnick** [comment]
Oh, hmm. I forgot that the `request` parameter passed to `cacheKeyWillBeUsed` might be a string, and isn't always a `Request` object, depending on how the underlying call to `match()` or `put()` ends up being made.

Try this:

```
async function cacheKeyWillBeUsed({request, mode}) {
  // Hardcode your cross-origin 'https://example.com' URL.
  const url = new URL(request.url || request, 'https://example.com');

  // Remove only paramToBeIgnored and keep other URL parameters.
  url.searchParams.delete('paramToBeIgnored');

  // Return the full remaining href.
  return url.href;
}
```
