### ISSUE TITLE
Ensure that only the /latest/ docs are in search indices

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2513]
Results like https://developers.google.com/web/tools/workbox/reference-docs/v4/workbox.routing.Route end up fairly highly ranked in search results for terms like "matchcallback workbox". Finding the v4 syntax is arguably not useful for most developers, as opposed to https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~matchCallback

Ideally, only the latest version of our docs would be included in search indices. We should look into using https://support.google.com/webmasters/answer/93710?hl=en to prevent our legacy docs from being indexed.

We're going to keep at least one versioned set of our docs published for each major version (v2, v3, v4, etc.) so this would just involve indexing, not breaking versioned URLs.

**Comment by FossPrime** [comment]
Removing the old guides entirely is a really poor experience for people on Vue/React who can't update easily as Workbox is preconfigured and the benefit of going rogue does not outweigh the benefit of having the framework preconfigure things.

I'll rely on unofficial documentation for now, then upgrade once the new versions of the frameworks and components come out of alpha

**Comment by jeffposnick** [comment]
The old guides are still available for each major version, by swapping out `/latest/` for `/v4/`, etc. in our URLs:

E.g. https://developers.google.com/web/tools/workbox/reference-docs/v4/

(We don't retain every minor version release of the generated docs, just the "last" one for a given major version.)

Prior to making this change, if you were to search for, e.g., `workbox-routing`, you'd likely end up with very out of date generated docs as the first result. That was not a great experience for folks.

**Comment by FossPrime** [comment]
I'm aware that the old API docs can be accessed with the URL trick, but **the guides and recipes** cannot. I got everything I needed piecemealing third party recipes and the API reference.

I learned SW by messing around in glitch. The Workbox API is very different, but really well thought out. Thanks!

**Comment by jeffposnick** [comment]
Yes, unfortunately we don't have a good model for dealing with incompatible changes to our unversioned guides and recipes. Apologies, but I'm glad you've been able to get up to speed!
