### ISSUE TITLE
Webpack encore compiler warning

### ISSUE THREAD

**Issue by ph1823** [GoogleChrome/workbox#2514]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:
*I still use webpack, with my symfony 4 application. I already had trouble installing it, but since I succeeded, a warning message "invisile" appears during compilation, whether it is in the dev, or production environment. Here is a screenshot illustrating the problem:*

![Image of warning](https://zupimages.net/up/20/21/ll0p.png)

Webpack configuration:
```javascript
const Encore = require('@symfony/webpack-encore');
const CompressionPlugin = require('compression-webpack-plugin');
const {GenerateSW, InjectManifest} = require('workbox-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const path = require('path')
Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .addEntry('app', './assets/js/app.js')
    .addEntry('cart', './assets/js/cart.js')
    .addEntry('site', './assets/js/site.js')
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableSassLoader()
    .enableVueLoader(() => {}, { runtimeCompilerBuild: true })
    .addLoader({
        test: /\.exec\.js$/,
        loader: 'script-loader'
    })
    .autoProvidejQuery()
    .autoProvideVariables({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
    })
    .enableSingleRuntimeChunk()
    .addPlugin(new CompressionPlugin())
    .addPlugin(    new OptimizeCssAssetsPlugin({
        assetNameRegExp: /\.optimize\.css$/g,
        cssProcessor: require('cssnano'),
        cssProcessorPluginOptions: {
            preset: ['default', { discardComments: { removeAll: true } }],
        },
        canPrint: true
    }))
    .addPlugin(new InjectManifest({
        swSrc: './assets/js/service-worker.js'
    }))
    /*.addPlugin(new GenerateSW({swDest: 'sw.js'}))/*
    .addPlugin(new InjectManifest({
        swSrc: path.resolve(__dirname, 'sw.js'),
        exclude: [
            /\.map$/,
            /manifest$/,
            /\.htaccess$/,
            /service-worker\.js$/,
            /sw\.js$/,
        ],
    }))*/;



module.exports = Encore.getWebpackConfig();
```
./assets/js/service-worker.js file:
```javascript
import {precacheAndRoute} from 'workbox-precaching';
// Your other import statements go here.

precacheAndRoute(self.__WB_MANIFEST);
// Your other SW code goes here.
```

and in addition I can't get the service worker to work I have to be bad  :(
Thank for you help !

**Comment by jeffposnick** [comment]
If you're using `webpack` in a watch-like scenario, where it might compile things multiple times, there's a logged warning when using `InjectManifest` which might be the source of the mysterious warning you're seeing.

There's more detail on that warning message at https://github.com/GoogleChrome/workbox/pull/2245

Basically, it's telling you that the contents of the precache manifest are likely to be unreliable, and that you should avoid using `InjectManifest` in a watch-like scenario.

As for why the message isn't actually being display, I think that has more to do with the `symfony` wrapper.
