### ISSUE TITLE
`waiting` event is missing `wasWaitingBeforeRegister` property in Chrome

### ISSUE THREAD

**Issue by zdila** [GoogleChrome/workbox#2526]
**Library Affected**:
workbox-window

**Browser & Platform**:
Chrome 83.0.4103.61, Linux

**Issue or Feature Request Description**:
Event in `waiting` event handler (`wb.addEventListener('waiting', (event) => { ...`) in Google Chrome is missing `wasWaitingBeforeRegister` property but has `isUpdate`. In Firefox it has only `wasWaitingBeforeRegister`.

Also in case of Chrome if I reload the page without calling `skipWaiting` in sw then I see two `waiting` events. One has `wasWaitingBeforeRegister` property and *redundent* SW and other has `isUpdate` property and *installed* SW.

I am not sure if #2525 is related as I am encountering both issues even I followed instructions from https://developers.google.com/web/tools/workbox/guides/get-started.

Code:
```javascript
const wb = new Workbox('/sw.js');

wb.addEventListener('waiting', (event) => {
  console.log('waiting', event);

  if (event.isUpdate || event.wasWaitingBeforeRegister) { // I must use both conditions
    showSkipWaitingPrompt();
  }
});

**Comment by jeffposnick** [comment]
I think setting `eventProps.wasWaitingBeforeRegister = false` prior to this would address at least the missing value:

https://github.com/GoogleChrome/workbox/blob/682d04cc8bd5a6beb3b689c91fa51b04c55dc25d/packages/workbox-window/src/Workbox.ts#L445-L446

Can you confirm, @philipwalton?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
