### ISSUE TITLE
Inconsistent handling of swSrc when enabling/disabling compileSrc option

### ISSUE THREAD

**Issue by axibyte** [GoogleChrome/workbox#2527]
**Library Affected**:
*workbox-webpack-plugin, InjectManifest*

**Browser & Platform**:
"all browsers", Windows 10

**Issue or Feature Request Description**:
When compileSrc is set to false, the context of the parent compiler is not taken into consideration, leading to "no such file or directory, open './sw.js'". When compileSrc is set to true, the context will be correct and there will be no errors.

compileSrc: false, the swSrc should be set as "./src/sw.js"
compileSrc: true, the swSrc should be set as "./sw.js"

I believe the swSrc value should be consistent regardless of the value of compileSrc

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
