### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by gabriel-vasile-envision** [GoogleChrome/workbox#2531]
On this [Using Bundlers page](https://developers.google.com/web/tools/workbox/guides/using-bundlers#es2015_syntax) a wrong statement is made.

"Keep in mind that every browser that supports service workers also supports most ES2015 features (the primary exception being import statements), so there's usually no need to transpile your code.

This means you can freely use features like classes and syntax like async/await when writing service worker code, which is fantastic as most service worker APIs are promise-based."

async/await was introduces in ES2017, not ES2015

**Comment by jeffposnick** [comment]
We removed that bit from the latest version of that page.
