### ISSUE TITLE
cacheKeyWillBeUsed - advanced usage 

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2543]
Hi @jeffposnick 

I have a couple of questions/issues that I think you might be able to help..

**ISSUE 1)** 

When user logs in, I make a request to third-party API - `https://example.com/insight?userId=123&minDateCreated=12949129`. If user refreshes the page, I make this call again. So every refresh causes this url to get called via `axios`. Of course, `minDateCreated` parameter changes in the url depending on what time it is.

Now, if user logs out,  and other user logs in, what's gonna happen is the url is gonna get called with different `userId`.

Here is how I use workbox for this.

```js
async function cacheKeyWillBeUsed({request, mode}) {
    const url = new URL(request.url || request,  config.api.url);
    // Remove only paramToBeIgnored and keep other URL parameters.
    url.searchParams.delete('minDateCreated');
    // Return the full remaining href.
    return url.href;
}

registerRoute(
    new RegExp(`${config.api.url.replace(/\./g,'\\.')}.*/insight`),
    new NetworkFirst({
      cacheName: 'my-cache-name',
      plugins: [{ cacheKeyWillBeUsed }],
    }),
)
```

So, this code makes sure that urls get cached looks like this: `https://example.com/insight/?userId=123` without `minDateCreated`. Now, if user logs out and some other user logs in, the new entry is gonna be added here. if 10 users use the same phone, 10 entries. Each entry might be a little bit big and it's of course would be a much better practice to remove the entries that no longer are needed.

Do you think It will be a good idea if in the function above `cacheKeyWillBeUsed`, I will check what url request is being made and remove all the other entries that don't match the currently requested on via the help of `caches.delete`.  As this function(cacheKeyWillBeUsed) gets called each time, maybe you have a better idea than calling `caches.delete` each time due to performance. Of course, there's also a way to remove that cache when user logs out. but i am looking for other ideas by using simply workbox.

**Issue 2)**

My first project uses my second project from which it fetches url at run-time. My second project contains:

* main.hash123.js
* time-reveal.hash456.js
* phaser.hash123.js
* manifest.json

When my project loads, it fetches `manifest.json` from the 3rd party via `axios` and whatever is in `manifest.json`, it takes all those and makes requests and loads them. So in above case, by the help of `manifest.json`, we would load all of those.  Now, of course, my second project might change which will cause the hashes to change of those above files and new ones(because of new hashes) will also be cached alongside the old ones. So, what could be done in this case to remove old ones? The big problem is that we have more than 1 file(as you can see , 4) and the requests for 2 files happen after some time then the requests for other 2 files.  So, i can't just use `cacheKeyWillBeUsed` to loop through the `caches` and delete the old ones since i have no way of knowing which one to remove at that point.

I appreciate your answers in advance....

**Comment by novaknole** [comment]
@jeffposnick 

Just a kind reminder if you've missed this.

I kind of need this ASAP if you don't mind taking some time to answer 

Thanks in advance.

**Comment by jeffposnick** [comment]
For your first question, I think an approach similar to what's described in the hypothetical `cacheDidUpdate` plugin in https://github.com/GoogleChrome/workbox/issues/2534#issue-635754570

Cleaning up entries in `cacheDidUpdate` is a better approach that doing that in `cacheKeyWillBeUsed`, because `cacheDidUpdate` will happen after the `Response` has been returned to the page, so it is less likely to block anything important.

I am fairly sure that same issue (which deals with eventually cleaning up old hashed URLs that are cached at runtime) will also address you second question.

**Comment by novaknole** [comment]
@jeffposnick Thanks for this ..

It's exactly what I was looking for... 

Do you plan on putting this(already written plugin) into v6 release ?

**Comment by jeffposnick** [comment]
I would just try using a copy of it as-is in your own code for now. It's unlikely that the `workbox-expiration` changes would land in v6.
