### ISSUE TITLE
UMD version workbox-window getSW() does not always return a Promise 

### ISSUE THREAD

**Issue by mjakobis** [GoogleChrome/workbox#2545]
**Library Affected**:
*workbox-window*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
In Workbox.ts, getSW() is defined as async:
```javascript
 async getSW(): Promise<ServiceWorker> {
    // If `this._sw` is set, resolve with that as we want `getSW()` to
    // return the correct (new) service worker if an update is found.
    return this._sw !== undefined ? this._sw : this._swDeferred.promise;
  }
}
```
UMD version is as follows:
```javascript
  _proto.getSW = function getSW() {
        try {
          var _this7 = this;

          // If `this._sw` is set, resolve with that as we want `getSW()` to
          // return the correct (new) service worker if an update is found.
          return _this7._sw !== undefined ? _this7._sw : _this7._swDeferred.promise;
        } catch (e) {
          return Promise.reject(e);
        }
      }
```
(from https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-window.dev.umd.js)
So when __sw_ is set to a ServiceWorker object, it is just returned and not wrapped in a Promise.
This causes calling code to fail with:
 _Uncaught TypeError: wb.getSW(...).then is not a function_

**Comment by jeffposnick** [comment]
That's rather odd, as I can't think of why the `async`-behavior of always wrapping the return value in a promise is getting dropped. (CC: @philipwalton)

If you could work around it by using `Promise.resolve(wb.getSW).then(...)` in v5, that would probably be easiest.

I'll make a change in v6 that explicitly uses `Promise.resolve(this._sw)` as the return value.

**Comment by mjakobis** [comment]
Thank you, @jeffposnick! You're absolutely right, there is an easy workaround, but I wasted some time before I realized what was going on so trying to make sure others don't.

**Comment by philipwalton** [comment]
The UMD version uses [babel-plugin-transform-async-to-promises](https://www.npmjs.com/package/babel-plugin-transform-async-to-promises) to convert the code to ES5, so there's probably a bug somewhere in that transform.
