### ISSUE TITLE
macos/ios safari networkfirst returns wrong response

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2549]
Hey @jeffposnick 

I've noticed this too often and I think this deserves your attention as you're the one who can answer this .. Thanks in advance btw..

In my app, I make a request to `manifest.json` .  

That file contains the entry called - `main: main.hash123.js` . After I get that file,  I make a request to `main.hash123.js`.  Both files reside on the separate domain from my main app. Let's call this `https://example.com/manifest.json` and `https://example.com/main.hash123.js`.

```js
registerRoute(new RegExp(`${config.app.urls.example.replace(/\./g,'\\.')}`), new NetworkFirst({
            cacheName: config.app.cache.games,
            plugins: [ HashExpirationCachePlugin ]
 })
```

Let's say that on `example.com` , I updated `main` file and its hash changed from `main.hash123.js` to `main.hash456.js`. This will also cause to change `manifest.json` on example.com because now it will contain `main: main.hash456.js`.  (all part of the build process).

In my app, if I refresh the page, which should first make a request to `manifest.json`, what happens is it takes that `manifest.json` from `memory cache`, grabs `main.hash123.js` from it and  makes request for : `main.hash123.js`  which results in an error as it no longer exists on `example.com` . If I refresh the page for the second time, everything gets back to normal, it fetches `manifest.json` from network and grabs `main.hash456.js`. 

Why is there second refresh needed ? and why does it fail for the first refresh ? 

**MORE INFO 1)** Without service worker at all, everything works fine since `manifest.json`'s request's response has `ETAG` set. so If I don't change it and refresh the page, it says `304` Not Modified. if I change it, it fetches new `manifest.json` and all seems fine.

What do you think could be the case ? I can't reproduce this on Chrome, because I think Chrome doesn't store contents in memory cache if there's a service worker activated. But in safari, even though content is stored in service worker's cache, after multiple refresh it gets also stored in memory cache.

**Comment by jeffposnick** [comment]
Please see https://github.com/GoogleChrome/workbox/issues/2540#issuecomment-643422473 for some context on the memory cache.

In general, the only reason why the memory cache would be used is if the `Cache-Control` headers that you set when serving `https://example.com/manifest.json` allow it to be. It sounds like you should be stricter about what headers you set there, and go with something like `Cache-Control: no-cache` (to always force revalidation).

If you have `Cache-Control: no-cache` configured for the responses to `https://example.com/manifest.json` and you're still seeing the memory cache being used without a server revalidation step, then that would be a bug in Chrome that you'd need to follow up on separately.
