### ISSUE TITLE
Overriding fetch for strategies

### ISSUE THREAD

**Issue by rikonor** [GoogleChrome/workbox#2550]
**Library Affected**:
workbox-strategies

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

We are working on a plugin framework for the use-case of sharing multiple service workers on a single domain.
An example plugin in our framework has the following layout:
```js
export const pluginDefinition = {
  name: "plugin",
  fn: (fetch, request) => {
    return fetch(request);
  },
};
```
Notice the above relies on an injected `fetch` function.

Many of our plugins require the use of certain Workbox features, specifically `workbox-strategies`. Since we rely on an injected `fetch`, we would need to inject this same `fetch` into the workbox strategy.

As far as we've been able to tell, it's possible to set custom `fetchOptions` on a strategy, but it does not seem possible to specify a `fetch` dependency for the strategy to use, as it always uses the global `fetch` function.

We were hoping to ask whether we might be missing how to do this, or whether its a feature you'd be willing to consider.

**Comment by jeffposnick** [comment]
I'm curious to learn more about what your injected `fetch()` does that differs from the built-in `fetch()`.

It's possible that whatever it's doing might be achievable just by writing your own custom strategy classes, which will be easier to do in an upcoming Workbox release that includes https://github.com/GoogleChrome/workbox/pull/2455, based on the changes outlined in https://github.com/GoogleChrome/workbox/issues/2446.

If the changes in that PR don't help, though, hearing more about what your underlying motivation is might help up come up with a possible solution.

**Comment by rikonor** [comment]
Hi @jeffposnick, thanks for the quick reply!

> I'm curious to learn more about what your injected fetch() does that differs from the built-in fetch().

The `fetch` function that is injected into the plugin serves two purposes. It allows the plugin to fetch the response it needs to give back to the client, but under the hood, it also triggers the next plugin in line.

I hope this diagram helps clarify it a little as well.

In the below case, when `plugin-1` calls `fetch(request)`, it will actually invoke `plugin-2`. Since `plugin-2` is the last one, when it calls `fetch`, it _will_ use the global fetch.

<img width="500" alt="Screen Shot 2020-06-23 at 4 17 54 PM" src="https://user-images.githubusercontent.com/3395638/85456616-24b31400-b56d-11ea-94ef-65864c9a5143.png">

I hope this explains why we need to inject a `fetch` function to the strategy - because otherwise the strategy will skip our entire plugin chain.

**Comment by jeffposnick** [comment]
Would writing a [custom Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) that hooked into the lifecycle events that Workbox already exposes allow you to accomplish what you want?

`requestWillFetch` allows you to do manipulate the outgoing `Request` before it hits the network, and it seems like you could implement your architecture by adding one or more custom ``requestWillFetch` callbacks to any of the built-in Workbox strategies.

There's also a `fetchDidSucceed`/`fetchDidFail` pair of events that let you take action after the underlying `fetch()` is made.

**Comment by rikonor** [comment]
Hi @jeffposnick,

If I'm understanding correctly, the issue with utilizing `requestWillFetch` would be that it would only allow us to alter the request, but not actually pass it through a custom `fetch` function.

Perhaps if `requestWillFetch` allowed "aborting" and returning a custom response, we could potentially call our `fetch` in it and return the response. That said, from the docs it would seem that's not supported at the moment.

**Comment by jeffposnick** [comment]
My suggestion was based on the assumption that the only difference between the global `fetch()` and your custom `fetch()` was that your `fetch()` had the ability to run your own custom code in a chain prior to calling the global `fetch()`.

If that's the case, then why not just implement your custom code inside of a Workbox lifecycle callback?

I really don't think that we're going to allow folks to "swap" in their own `fetch()` implementation under the hood in Workbox, at least not via some sort of official interface. So finding a way to adapt your custom code to run in a Workbox lifecycle callback, or checking the new v6 changes outlined in #2446, would be the path forward.

If you suggested a new lifecycle callback added to Workbox in order to implement what you're trying to do, we could consider that as a feature request.

**Comment by rikonor** [comment]
Hi @jeffposnick,

As long as the lifecycle callback doesn't allow overriding the "final" `fetch` in some way, I think we might be stuck waiting for #2446 to be pushed out. We'll most likely implement our own version of the strategies and revisit once #2446 is out, as allowing our clients to use Workbox directly would be much more preferable.

Thanks for the feedback and advice!

**Comment by jeffposnick** [comment]
As long as #2446 gives you what you need to move forward, that sounds good.
