### ISSUE TITLE
Errors in the doc's

### ISSUE THREAD

**Issue by summercms** [GoogleChrome/workbox#2551]
Location 1: https://developers.google.com/web/tools/workbox/modules/workbox-cacheable-response#caching_based_on_headers

Location 2: https://developers.google.com/web/tools/workbox/modules/workbox-cacheable-response#caching_based_on_headers_and_status_codes

Has the code line: 

```
import {CacheFirst} from 'workbox-strategies';
```

Yet the code is calling: `StaleWhileRevalidate`

I think you need to replace the code line with:

```
import {StaleWhileRevalidate} from 'workbox-strategies';
```

Same error in both code snippets.

**Comment by jeffposnick** [comment]
Thanks for letting us know!

**Comment by summercms** [comment]
closing as merged
