### ISSUE TITLE
"importsDirectory" is not a supported parameter.. "importWorkboxFrom" is not a supported parameter.

### ISSUE THREAD

**Issue by SatoshiKawabata** [GoogleChrome/workbox#2554]
Hi. I'm migrating to v5. How can I migrate to `v5`?

**Library Affected**:
workbox-webpack-plugin v5.1.3

**Browser & Platform**:
Webpack

**Issue or Feature Request Description**:
I updated `workbox-webpack-plugin` from `v4.3.1` to `v5.1.3`. I got this error.
```
    ERROR in Please check your InjectManifest plugin configuration:
    "importsDirectory" is not a supported parameter.. "importWorkboxFrom" is not a supported parameter.
```

I use InjectManifest like below. `importsDirectory` and `importWorkboxFrom` are not supported in `v5`.
```js
                new InjectManifest({
                    swSrc: "./src/editor-sw.js",
                    swDest: "editor-sw.js",
                    importsDirectory: "wb-assets",
                    importWorkboxFrom: "local"
                })
```

How can I migrate to `v5`?

**Comment by jeffposnick** [comment]
In [Workbox v5](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4#using_module_imports), `workbox-webpack-plugin` [compiles](https://developers.google.com/web/tools/workbox/guides/using-bundlers) your `swSrc` file using `webpack`.

Your easiest approach would be to use ES module in your `swSrc` for all the pieces of Workbox that you plan on using, and then your `swDest` will include the relevant code without needing to import anything external:

```
import {precacheAndRoute} from 'workbox-precaching';
// any other imports here.

precacheAndRoute(self.__WB_MANIFEST);

// Any other SW code here.
```

**Comment by SatoshiKawabata** [comment]
I rewrote this. Maybe this problem was resolved. Thanks!

webpack.config.js
```js
plugins: [
    new InjectManifest({
        swSrc: "./src/editor-sw.js",
        swDest: "editor-sw.js",
    }),
]
```

sw.js
```js
import { skipWaiting, clientsClaim } from "workbox-core";
import { StaleWhileRevalidate } from "workbox-strategies";
import { registerRoute } from "workbox-routing";
import { precacheAndRoute } from "workbox-precaching";

skipWaiting();
clientsClaim();

registerRoute(
    new RegExp("^.*(/some-request-.+/).*$"),
    new StaleWhileRevalidate({
        cacheName: "api-cache",
    })
);

precacheAndRoute(self.__WB_MANIFEST);
```
