### ISSUE TITLE
Error: "Service worker installation failed. It will be retried automatically during the next navigation."

### ISSUE THREAD

**Issue by SatoshiKawabata** [GoogleChrome/workbox#2556]
I got errors on browser console after migrating workbox-webpack-plugin from v4.3.1 to v5.1.3. Please help me.

**Library Affected**:
workbox-webpack-plugin v5.1.3

**Browser & Platform**:
- Webpack
- Chrome on Mac
- Edge on Mac

**Issue or Feature Request Description**:
I updated workbox-webpack-plugin from v4.3.1 to v5.1.3. I got these errors on browser console in the local environment.
```
workbox Service worker installation failed. It will be retried automatically during the next navigation.
print @ editor-sw.js:1438
(anonymous) @ editor-sw.js:1451
(anonymous) @ editor-sw.js:3198
Promise.catch (async)
installListener @ editor-sw.js:3196
```
```
Uncaught (in promise) bad-precaching-response: The precaching request for 'http://localhost:8888/asset-en@2x.js' failed with an HTTP status of 404.
    at PrecacheController._addURLToCache (http://localhost:8888/editor-sw.js:2554:19)
    at async Promise.all (index 0)
    at async PrecacheController.install (http://localhost:8888/editor-sw.js:2471:9)
WorkboxError @ editor-sw.js:531
_addURLToCache @ editor-sw.js:2554
```

My `editor-sw.js` is this. I refered to #2554 and I rewrote the code.
```js
import { skipWaiting, clientsClaim } from "workbox-core";
import { StaleWhileRevalidate } from "workbox-strategies";
import { registerRoute } from "workbox-routing";
import { precacheAndRoute } from "workbox-precaching";

skipWaiting();
clientsClaim();

registerRoute(
    new RegExp("^.*(/some-request-.+/).*$"),
    new StaleWhileRevalidate({
        cacheName: "api-cache",
    })
);

precacheAndRoute(self.__WB_MANIFEST);
```

My webpack config's plugin is this.
```
plugins: [
    new InjectManifest({
        swSrc: "./src/editor-sw.js",
        swDest: "editor-sw.js",
    }),
]
```

Thanks.

**Comment by jeffposnick** [comment]
`asset-en@2x.js` must be listed in your precache manifest, and it doesn't correspond to a URL that exists on your local web server.

`workbox-webpack-plugin` v5 creates its precache manifest based on the assets in your `webpack` compilation. (This is different than `workbox-webpack-plugin` v4, which used `glob` patterns to generate the precache manifest.)

If you need to remove certain assets from the final precache manifest, you can use the `exclude` parameter, or `manifestTransforms`. The documentation for both can be found at https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest
