### ISSUE TITLE
ManifestEntry["integrity"] ValidationError

### ISSUE THREAD

**Issue by zhansingsong** [GoogleChrome/workbox#2558]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*node*

**Issue or Feature Request Description**:

[**ManifestEntry** in Reference Docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestEntry)

> **Parameter**
> 
> - **url**：stringThe URL to the asset in the manifest.
> - **revision**: OptionalstringThe revision details for the file. This is a hash generated by node based on the file contents.
> - **integrity**: OptionalstringIntegrity metadata that will be used when making the network request for the URL.
> 

but [`manifest-entry.js`](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/src/options/objects/manifest-entry.js)

```
"use strict";

/*
  Copyright 2019 Google LLC

  Use of this source code is governed by an MIT-style
  license that can be found in the LICENSE file or at
  https://opensource.org/licenses/MIT.
*/
const joi = require('@hapi/joi');

module.exports = joi.object().keys({
  revision: joi.string().required().allow(null),
  url: joi.string().required()
});
```
not `"integrity"` property in `manifest-entry.js`.

If `"integrity"` property  is used in the code, cause the following error：

> (node:1142) UnhandledPromiseRejectionWarning: ValidationError: child "additionalManifestEntries" fails because ["additionalManifestEntries" at position 0 does not match any of the allowed types]
>     at Object.exports.process (/Users/github/workbox-example/node_modules/@hapi/joi/lib/errors.js:202:19)
>     at internals.Object._validateWithOptions (/Users/github/workbox-example/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
>     at internals.Object.validate (/Users/github/workbox-example/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
>     at module.exports (/Users/github/workbox-example/node_modules/workbox-build/build/lib/validate-options.js:14:14)
>     at generateSW (/Users/github/workbox-example/node_modules/workbox-build/build/generate-sw.js:202:19)
>     at Object.<anonymous> (/Users/github/workbox-example/index.js:8:1)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
> (node:1142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:1142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jeffposnick** [comment]
Sorry about that; we'll get it fixed for the v6 release.

In the meantime, you should be able to accomplish the same thing via [`manifestTransforms`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestTransform), e.g.:

```
const addEntriesTransform = async (manifest) => {
  manifest.push({url: ..., revision: ..., integrity: ...}, {...});
  return {manifest, warnings: []};
};

// In your build config:
{
  manifestTransforms: [addEntriesTransform],
  ...
}
```
