### ISSUE TITLE
Fallback on fetch when both network and cache not available

### ISSUE THREAD

**Issue by shadowwalker** [GoogleChrome/workbox#2566]
# Summary

I'm using `workbox-webpack-plugin` to generate `service-worker.js` and `workbox-xxxxxx.js` runtime code. Using current implementation, there is no way to fallback when fetch in service worker throws an error due to network offline. What's worse is that when there is no pre-caches or runtime caches hit, the web app would show the browser's network offline error page. Which is not ideal from the user experience perspective. Besides, fallback image could help to workout a placeholder image scenario.

**NOTE**
This is totally different requirement from `navigationFallback` , which assuming all the web app resources are pre-cached. And when a navigate to a route that is not pre-cached, the navigation fallback url will be responded, even the network is online.

# Propose Changes

There is solution to implement comprehensive fallback:

> All of the built-in caching strategies reject in a consistent manner when there's a network failure and/or a cache miss. This promotes the pattern of setting a global "catch" handler to deal with any failures in a single handler function.
>
> Reference: https://developers.google.com/web/tools/workbox/guides/advanced-recipes#comprehensive_fallbacks

However the global [setCatchHandler](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#.setCatchHandler) API is not exposed in the generated workbox runtime. Hence there is no way to utilized this so far.

The ideas here are:

1. Add a configuration option for fetch fallback
2. Add comprehensive fallback solution into the service worker template
3. Generate related code

Generate service worker with extra following code:

![image](https://user-images.githubusercontent.com/9603375/86545323-f3c6cd80-bee2-11ea-82d9-cd2286edc26d.png)

**Library Affected**:
*workbox-build, workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Comment by jeffposnick** [comment]
Thanks for the feature request, @shadowwalker! I agree that it could be useful.

I have been thinking about this topic as well, and honestly, the "big `switch` statement" in a global `setCatchHandler` is something that I think Workbox can improve.

I filed https://github.com/GoogleChrome/workbox/issues/2569 with some ideas for v6, and if we move forward with that, I think what might make more sense is to change your proposal so that you could configure `setCatchHandler` on an individual-handler level via generate SW.

Something like this with support for precached URLs:

```
runtimeCaching: [{
  urlPattern: /\.jpg$/,
  handler: 'CacheFirst',
  catchHandler: {
    url: '/fallback.jpg',
    precached: true,
  }
}],
```

Or with support for a function:

```
runtimeCaching: [{
  urlPattern: /\.jpg$/,
  handler: 'CacheFirst',
  catchHandler: () => caches.match('/fallback.jpg'),
}],
```

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/workbox/issues/2569#issuecomment-656867032
