### ISSUE TITLE
Chrome 47 error: set of undefined

### ISSUE THREAD

**Issue by bansalvks** [GoogleChrome/workbox#2568]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
Google Chrome v47.0.25 for Samsung Tizen
<img width="365" alt="Screenshot 2020-07-07 at 5 03 18 PM" src="https://user-images.githubusercontent.com/8565993/86776941-3d93ed00-c076-11ea-93a6-7b014830af64.png">

**Issue Description**:
getting error that the set is of undefined
<img width="1068" alt="Screenshot 2020-07-07 at 5 02 54 PM" src="https://user-images.githubusercontent.com/8565993/86777098-5f8d6f80-c076-11ea-8143-783cb2f69baf.png">

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*
unable to provide as our dev servers are hosted on intranet. however I am attaching the service woker output file

the following zip has 2 files
1. *sw.js*  which is output by workbox itself
2. *sw.bundle*js* which I have transpiled using babel to support the chrome 47
[sw files.zip](https://github.com/GoogleChrome/workbox/files/4884642/sw.files.zip)

Any help or guidence is hearly appriciated.

**Comment by yellheah** [comment]
We can confirm this. We are getting the same error on a Samsung Tizen screen (which is based on Chrome 47) and Chrome 47 on Windows 10. Seems to be working in Chrome 51+

**Comment by vikas-bansal-DisneyPH** [comment]
is there any possible solution that workbox team may suggest?

@yellheah

**Comment by yellheah** [comment]
See browser support: https://github.com/GoogleChrome/workbox/wiki/Browser-Support

**Comment by jeffposnick** [comment]
Yes, our [browser support story](https://github.com/GoogleChrome/workbox/wiki/Browser-Support) is that Chromium prior to 50 is "officially" unsupported.

In practice, what that means is that it's up to you to manually run something like `@babel/preset-env` and import additional polyfills as needed on your service worker file.

It's possible to get things working, but it requires explicit transpilation on your part.

**Comment by jeffposnick** [comment]
(Specifically, following the steps at https://developers.google.com/web/tools/workbox/guides/using-bundlers to produce a standalone service worker script file with Workbox bundled in should give you something that you could then transpile.)

**Comment by vikas-bansal-DisneyPH** [comment]
Hi @jeffposnick @yellheah 

is there a way to find if the browser supports workbox or not before the service worker registration?

also, I tried using webpack to transpile the output file by workbox for the older browser however it did't work. 😢 

this is something that i tried

```JavaScript 
// Node in-built packages:
const path = require('path');

// NPM Package imports:
const webpack = require('webpack');

// Constants:
const PATHS = {
	DIST: path.resolve(__dirname, '../dist'),
};

module.exports = env => {
	const { mode = 'development', platform = 'web' } = env || {};
	return {
		mode,
		entry: ['babel-polyfill', path.join(PATHS.DIST, 'sw.js')],
		output: {
			path: PATHS.DIST,
			publicPath: '/',
			filename: 'sw.bundle.js',
		},
		module: {
			rules: [
				{
					test: /\.(js)$/,
					// exclude: /node_modules/,
					use: {
						loader: 'babel-loader',
						options: {
							presets: ['env', 'stage-2'],
						},
					},
				},
			],
		},
	};
};

```
