### ISSUE TITLE
Use cleanupOutdatedCaches and clientsClaim at the same time

### ISSUE THREAD

**Issue by MrPropre** [GoogleChrome/workbox#2575]
**Library Affected**:
*workbox-core, workbox-precaching*

**Issue or Feature Request Description**:
Is it possible to use `workbox.core.clientsClaim()` and `workbox.precaching.cleanupOutdatedCaches()` at the same time ? I wonder if it will not create two `activate` event listeners, and one could override the other. This would be an unwanted result.
```js
const { clientsClaim } = workbox.core;
const { cleanupOutdatedCaches } = workbox.precaching;

/* ... */

cleanupOutdatedCaches();
clientsClaim();
```

**Comment by MrPropre** [comment]
Ok, this should not be a problem. I thought `cleanupOutdatedCaches` wasn't working because of `clientsClaim`, but `cleanupOutdatedCaches` just clean up precache caches, not old runtime caches or any other cache. It's strange that there is no function to globally clean up caches.

A code like this should do the trick :
```js
const { cacheNames } = workbox.core;

self.addEventListener('activate', event => {
    event.waitUntil(async function() {
        const userCacheNames = await caches.keys();
        await Promise.all(userCacheNames.map(async cacheName => {
            if (!Object.values(cacheNames).includes(cacheName)) {
                return await caches.delete(cacheName);
            }
            return await Promise.resolve();
        }));
    }());
});
```

**Comment by jeffposnick** [comment]
Yeah, deleting a cache is something that can be done using the Cache Storage API directly (as you're doing in that example), so wrapping it in a Workbox method didn't seem necessary.
