### ISSUE TITLE
 error TS2304: Cannot find name 'ExtendableEvent'.

### ISSUE THREAD

**Issue by KevinMendes** [GoogleChrome/workbox#2584]
Hello everyone, it is my first use of WorkBox, so it's probably an obvious problem...

**Library Affected**:
workbox-background-sync
workbox-routing
workbox-strategies

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I'm getting those errors when trying to build : 

```
node_modules/workbox-core/types.d.ts:8:13 - error TS2304: Cannot find name 'ExtendableEvent'.

8     event?: ExtendableEvent;
              ~~~~~~~~~~~~~~~

node_modules/workbox-core/types.d.ts:30:13 - error TS2304: Cannot find name 'ExtendableEvent'.

30     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

node_modules/workbox-core/types.d.ts:81:13 - error TS2304: Cannot find name 'ExtendableEvent'.

81     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

node_modules/workbox-core/types.d.ts:91:13 - error TS2304: Cannot find name 'ExtendableEvent'.

91     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

node_modules/workbox-core/types.d.ts:100:13 - error TS2304: Cannot find name 'ExtendableEvent'.

100     event?: ExtendableEvent;
                ~~~~~~~~~~~~~~~

node_modules/workbox-routing/Router.d.ts:79:17 - error TS2304: Cannot find name 'ExtendableEvent'.

79         event?: ExtendableEvent;
                   ~~~~~~~~~~~~~~~

node_modules/workbox-routing/Router.d.ts:97:17 - error TS2304: Cannot find name 'ExtendableEvent'.

97         event?: ExtendableEvent;
                   ~~~~~~~~~~~~~~~

node_modules/workbox-strategies/CacheFirst.d.ts:60:47 - error TS2304: Cannot find name 'ExtendableEvent'.

60     _getFromNetwork(request: Request, event?: ExtendableEvent): Promise<any>;
                                                 ~~~~~~~~~~~~~~~

node_modules/workbox-strategies/NetworkFirst.d.ts:85:17 - error TS2304: Cannot find name 'ExtendableEvent'.

85         event?: ExtendableEvent;
                   ~~~~~~~~~~~~~~~

node_modules/workbox-strategies/StaleWhileRevalidate.d.ts:68:17 - error TS2304: Cannot find name 'ExtendableEvent'.

68         event?: ExtendableEvent;
                   ~~~~~~~~~~~~~~~


Found 10 errors.

```
Here is my tsconfig : 

``` typescript
{
    "compilerOptions": {
        "outDir": "build/dist",
        "module": "esnext",
        "target": "es5",
        "lib": [
          "es2017",
          "dom",
          "dom.iterable",
          "webworker"
        ],
        "sourceMap": true,
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "moduleResolution": "node",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true,
        "allowJs": true,
        "experimentalDecorators": true,
        "skipLibCheck": true
    },
    "include": [
        "./src",
        "./utils",
        "./mock"
    ],
    "exclude": [
        "node_modules",
        "build"
    ]
}
```

And I add in my project those 4 libs from workbox :    
 "workbox-background-sync": "^5.1.3",
   "workbox-core": "^5.1.3",
   "workbox-routing": "^5.1.3",
   "workbox-strategies": "^5.1.3"

Thanks you

**Comment by jeffposnick** [comment]
That's unexpected, as including `webworker` in your `lib` settings [should be sufficient](https://stackoverflow.com/questions/56356655/structuring-a-typescript-project-with-workers/56374158#56374158).

I wonder if your `tsconfig.json` isn't being recognized for some reason?

As a quick sanity check, do things work if you use a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-) to add the reference directly to your service worker source file?

```
/// <reference lib="webworker" />
```

**Comment by KevinMendes** [comment]
It was a nice idea, but unfortunetly it didn't works

EDIT : 

I change my import to :

```
import {BackgroundSyncPlugin} from 'workbox-background-sync/BackgroundSyncPlugin';
import {registerRoute} from 'workbox-routing/registerRoute';
import {NetworkOnly} from 'workbox-strategies/NetworkOnly';
```

as I do before, and with this, your solution of /// solve 5 on 10 errors. I now have those 5 : 

```
../../../node_modules/workbox-core/types.d.ts:8:13 - error TS2304: Cannot find name 'ExtendableEvent'.

8     event?: ExtendableEvent;
              ~~~~~~~~~~~~~~~

../../../node_modules/workbox-core/types.d.ts:30:13 - error TS2304: Cannot find name 'ExtendableEvent'.

30     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

../../../node_modules/workbox-core/types.d.ts:81:13 - error TS2304: Cannot find name 'ExtendableEvent'.

81     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

../../../node_modules/workbox-core/types.d.ts:91:13 - error TS2304: Cannot find name 'ExtendableEvent'.

91     event?: ExtendableEvent;
               ~~~~~~~~~~~~~~~

../../../node_modules/workbox-core/types.d.ts:100:13 - error TS2304: Cannot find name 'ExtendableEvent'.

100     event?: ExtendableEvent;
                ~~~~~~~~~~~~~~~


Found 5 errors.

```

**Comment by TheForsakenSpirit** [comment]
@KevinMendes where you use this ExtendableEvent? Can you provide code of your service worker?
Depend on your import, you must use FetchEvent form webworker lib.

**Comment by veikkoeeva** [comment]
It seems to be I have a similar problem. I wrote about it in SO at https://stackoverflow.com/questions/63310207/a-type-error-in-workbox-routing-when-defining-headersinit-value already and shared the worker and configuration.

**Comment by jeffposnick** [comment]
Here's an example of a CodeSandbox project that shows this working: https://codesandbox.io/s/divine-pine-hh0ww?file=/src/sw.ts

The IDE's TypeScript integration shows that the code compiles without error. Maybe comparing that setup with your project's config will give some clues?

The main thing I had to do was add "webworker" to the list of libraries, as mentioned above.

I did not need to add

```
declare let self: ServiceWorkerGlobalScope;
```

but for some scenarios (where `self` might otherwise be inferred to be something else) I've seen that help.

**Comment by Haprog** [comment]
I just ran into this same issue in a project where I get:
```
ERROR in [at-loader] ./node_modules/workbox-core/types.d.ts:8:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/types.d.ts:30:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/types.d.ts:81:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/types.d.ts:91:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/types.d.ts:100:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/_private/fetchWrapper.d.ts:5:13 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-core/_private/resultingClientExists.d.ts:12:84 
    TS2304: Cannot find name 'Client'.

ERROR in [at-loader] ./node_modules/workbox-precaching/PrecacheController.d.ts:42:17 
    TS2304: Cannot find name 'ExtendableEvent'.

ERROR in [at-loader] ./node_modules/workbox-precaching/PrecacheController.d.ts:81:17 
    TS2304: Cannot find name 'ExtendableEvent'.
```
But the weird thing is this happens only randomly (maybe 20-50% of the time) when I run `webpack` multiple times in a row.

This is with webpack 4.42.0, typescript 3.8.3 and workbox 5.1.4.

But thanks for the hint about "lib". In this project we were not specifying "lib" atm. so I'm now trying with:
```json
    "lib": [
      "es2017",
      "dom",
      "dom.iterable",
      "webworker"
    ],
```

So far it seems like this is the solution for me (but I'll need to see if this problem still occurs randomly), but I can't really understand why it would randomly succeed and randomly fail without having the `webworker` lib declared, I would expect it to fail consistently if that lib is required when any dependency uses types defined in https://github.com/microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts. I guess it might be a typescript issue.

**Comment by jeffposnick** [comment]
As of now, I'm going to chalk up what's been described in this thread as flakiness due to TypeScript's integrations with IDEs and various build tools, where edge cases might prevent configurations that include the `webworker` and other dependent libraries not being picked up 100% of the time.

I'm not sure that there are any takeaways from the Workbox point of view. If there are any suggestions about how we could improve the experience, though, please let me know.
