### ISSUE TITLE
Workbox Single HTML File

### ISSUE THREAD

**Issue by Seems2Legit** [GoogleChrome/workbox#2585]
Is there a way to redirect all HTML requests to one entry?

![image](https://user-images.githubusercontent.com/24620002/87972068-9af05b00-cac6-11ea-9c20-bacfaeec172c.png)

I'm using react and redirecting multiple endpoints to one HTML file which does not vary in content.

Can I somehow redirect /leaderboard e.g. to the entry / in the cache?

I need the file to be updated as soon as you load any of those URLs but I don't want multiple different instances of the HTML file in the cache.

**Comment by jeffposnick** [comment]
Yes, that's what the [`NavigationRoute`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing.NavigationRoute) class lets you do.

If you're using [`GenerateSW`](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generatesw_plugin) to create your service worker and you're precaching your `/` URL, using [`navigateFallback: '/'`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#parameter_1:~:text=provide.-,navigateFallback) in your configuration will create the `NavigationRoute` for you in the generated service worker.

If you're just using runtime caching and not precaching, then something like the following would work instead:



```
const networkFirst = new NetworkFirst({cacheName: 'html'});
registerRoute(
  // If it's a navigation request...
  ({request}) => request.mode === 'navigate',

  // Fulfill it with a network-first strategy that always uses the URL '/'
  () => networkFirst.handle({request: '/'}),
);
```
