### ISSUE TITLE
How to apply yup validation in "react-select" multiselect dropdown

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [GoogleChrome/workbox#2589]
I want to apply yup validation on a multiselect  dropdown which is created using "react-select" library. The form is created using formik.

 <FormGroup>
                                                        <Label htmlFor="businessFunctions">{i18n.t('static.role.businessfunction')}<span className="red Reqasterisk">*</span> </Label>
                                                        <Select
                                                            valid={!errors.businessFunctions}
                                                            bsSize="sm"
                                                            invalid={touched.businessFunctions && !!errors.businessFunctions}
                                                            onChange={(e) => { handleChange(e); this.businessFunctionChange(e) }}
                                                            onBlur={handleBlur}
                                                            name="businessFunctions"
                                                            id="businessFunctions"
                                                            multi
                                                            required
                                                            min={1}
                                                            options={this.state.businessFunctionList}
                                                            value={this.state.businessFunctionId}
                                                            error={errors.businessFunctions}
                                                            touched={touched.businessFunctions}
                                                        />
                                                        <FormFeedback className="red">{errors.businessFunctions}</FormFeedback>
                                                    </FormGroup>

**Comment by anchal-chouvhan-altius** [comment]
<FormGroup>
                                                        <Label htmlFor="businessFunctions">{i18n.t('static.role.businessfunction')}<span className="red Reqasterisk">*</span> </Label>
                                                        <Select
                                                            valid={!errors.businessFunctions}
                                                            bsSize="sm"
                                                            invalid={touched.businessFunctions && !!errors.businessFunctions}
                                                            onChange={(e) => { handleChange(e); this.businessFunctionChange(e) }}
                                                            onBlur={handleBlur}
                                                            name="businessFunctions"
                                                            id="businessFunctions"
                                                            multi
                                                            required
                                                            min={1}
                                                            options={this.state.businessFunctionList}
                                                            value={this.state.businessFunctionId}
                                                            error={errors.businessFunctions}
                                                            touched={touched.businessFunctions}
                                                        />
                                                        <FormFeedback className="red">{errors.businessFunctions}</FormFeedback>
                                                    </FormGroup>

**Comment by jeffposnick** [comment]
This question is, unfortunately, unrelated to Workbox. I'm sorry that we can't be of help.

**Comment by anchal-chouvhan-altius** [comment]
Sorry by mistake I added this question here.
