### ISSUE TITLE
Provide way of calling unregisterRoute when using default router 

### ISSUE THREAD

**Issue by maport** [GoogleChrome/workbox#2592]
**Library Affected**:
workbox-routing

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
`Router` instances have an `unregisterRoute` method, but, as far as I can tell, if you are using the default Router, there is no way of obtaining the `Router` instance and hence no way of calling this method.

Would it be possible to either provide access to the `workbox-routing.utils.getOrCreateDefaultRouter` function or add an `unregisterRoute` function alongside the existing `workbox-routing.registerRoute` function that uses the default router?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
