### ISSUE TITLE
define is not a function & ServiceWorker script evaluation failed

### ISSUE THREAD

**Issue by nish17** [GoogleChrome/workbox#2595]
**Library Affected**:
*workbox-cli*

**Browser & Platform**:
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
node version: v14.7.0
npm version: v6.14.6

**Issue or Feature Request Description**:
after executing the following commands:
1. npx workbox wizard
2. npx workbox generateSW workbox-cofing.js

while checking service worker in the browser, it throws the following errors in the chrome dev tools

```
1
sw.js:168 Uncaught TypeError: define is not a function
    at Object.<anonymous> (sw.js:168)
    at newRequire (sw.js:47)
    at sw.js:81
    at sw.js:120
(anonymous) @ sw.js:168
newRequire @ sw.js:47
(anonymous) @ sw.js:81
(anonymous) @ sw.js:120
```
for the above error, while viewing the exact location where the error is,
it shows the following:

`define('./sw.js', ['./workbox-1bbb3e0e'], function (e) {`

```
2
(index):32 Service worker registration failed: TypeError: Failed to register a ServiceWorker for scope ('http://localhost:1234/') with script ('http://localhost:1234/sw.js'): ServiceWorker script evaluation failed
```

**Comment by urautkx** [comment]
I am getting the same error. Did you find a solution to this issue?

**Comment by nish17** [comment]
@urautkx changing the node version to v14.7.0 solved the issue

**Comment by jeffposnick** [comment]
Apologies for the delay in getting back to you.

Are you able to reproduce this error following our latest Workbox v6 release? I just attempted to reproduce, and was not able to.

If you can reproduce the issue, could you either deploy the generated service worker to a publicly accessible URL, or alternatively save everything in a `.zip` archive and share a link to that? I'd like to examine it further.

**Comment by nish17** [comment]
by just upgrading the node version fixes the issue.
