### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by kc97ble** [GoogleChrome/workbox#2596]
**Library Affected**:
Documentation

**Browser & Platform**:
None

**Issue or Feature Request Description**:

This document has been outdated since v5.0.0. To be specific, `self.__precacheManifest` has no longer available since v5.0.0.

https://developers.google.com/web/tools/workbox/guides/precache-files/webpack

**Comment by simonh1000** [comment]
OMG - I've lost hours wondering what was wrong with my code

**Comment by jeffposnick** [comment]
This outdated documentation has since been removed. Apologies for any confusion it caused in the meantime.
