### ISSUE TITLE
message: '"exclude" is not a supported parameter.',

### ISSUE THREAD

**Issue by sheub** [GoogleChrome/workbox#2598]
Hi, 
I'm using the *workbox-build* with *generateSW* strategy, and wanted to bypass the SW for some urls (e.g. auth).
The doc of the *generateSW* strategy given [here](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW) describes the *exclude* config, however I get a build error:
_message: '"exclude" is not a supported parameter._,

**Library Affected**:
workbox-build 5.1.3

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Comment by jeffposnick** [comment]
Your link was for the `workbox-webpack-plugin` docs, and there's a different set of parameters for the `webpack` use case.

Instead, take a look at the docs for `workbox-build`'s [`generateSW` mode](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW). In particular, you'll want to use `globPatterns` (and potentially `globIgnores`) to customize the precache manifest based on files that match those patterns in your local filesystem.
