### ISSUE TITLE
Use Google Analytics' /batch endpoint for replaying

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#26]
**Library Affected**:
sw-google-offline-analytics

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The Google Analytics API supports a [`/batch` endpoint](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch), allowing you to send up to 20 payloads at once in a single HTTP POST. It would be more efficient to use that for replaying failed requests than just sending individual HTTP GETs.

**Comment by addyosmani** [comment]
Closing this one SGTM

**Comment by jeffposnick** [comment]
Happy to close this as there hasn't been developer demand, and replaying one at a time works better with the current background-sync-queue behavior.
