### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/workbox#2606]
Wanted to create this ticket so it's easy to find if other folks bump into this issue.

This issue may occur if you're using a bundler with workbox. Some bundlers (Rollup, in particular) do not include a shim for `process.env.NODE_ENV` and this causes a reference error when workbox tries to access it.

You can read more about [how to resolve the issue for your specific bundler in the workbox docs](https://developers.google.com/web/tools/workbox/guides/using-bundlers).

Here's an example which shows how to resolve the issue with Rollup (note: this requires installing [@rollup/plugin-replace](https://www.npmjs.com/package/@rollup/plugin-replace))

```node
import replace from '@rollup/plugin-replace';

const isProduction = process.env.NODE_ENV === 'production';

export default {
  input: ['src/sw.js'],
  output: {
    format: 'amd',
    dir: 'dist',
  },
  plugins: [
    // This variable is defined by webpack (and some other tooling), but not by Rollup.
    // Set it to "production" if we're in prod, which will hide all of Workbox's log messages.
    replace({
      'process.env.NODE_ENV': JSON.stringify(isProduction ? 'production' : 'development'),
    }),
    ...
  ]
}
```

**Comment by tvvignesh** [comment]
@robdodson Thanks 🙂 Bumped into this today. Spent an entire day trying to setup workbox with rollup and finally got it right. One correction though is that I had to add extra quotes on both sides else it would become a variable.

Not having ES6 modules on Serviceworkers is a pain. Had to use OMT to get it working.

**Comment by jeffposnick** [comment]
I'll update Rob's example to include `JSON.stringify()` to get the quotes.
