### ISSUE TITLE
workbox-webpack-plugin getting webpack entry to run instead of swSrc

### ISSUE THREAD

**Issue by mh-alahdadian** [GoogleChrome/workbox#2607]
**Library Affected**:
*workbox-webpack-plugin*

**Issue or Feature Request Description**:
Hi 
I think that it's a good idea to get a webpack entry name like many of webpack plugins to use for `swSrc` in `InjectManifest`

**Comment by jeffposnick** [comment]
Could you share a use case that demonstrates why using `swSrc` doesn't meet your needs? Note that the `InjectManifest` plugin will trigger a child compilation, using the settings from your main `webpack` compilation, so I'm not aware of major differences between providing the service worker code as a file via `swSrc` and using a named `entry`.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
