### ISSUE TITLE
Migrate from deprecated `@hapi/joi` to `joi`

### ISSUE THREAD

**Issue by JoshRobertson** [GoogleChrome/workbox#2609]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:

`@hapi/joi` is deprecated and moving back to the `joi` repository: https://github.com/sideway/joi/

`"@hapi/joi": "^16.1.8",` should be replaced with `"joi": "^17.20"`

**Comment by jeffposnick** [comment]
👋 @JoshRobertson 

We have to stick with v16.x for the time being, as `joi` v17.x [removed support](https://github.com/sideway/joi/issues/2262) for Node v10.x. Workbox still plans on supporting Node v10.x.

This is being tracked via

https://github.com/GoogleChrome/workbox/blob/0f52e63616888bb6b568ed8dba0ec049654529c5/packages/workbox-build/.ncurc.js#L9-L19

**Comment by lucsoft** [comment]
Are there plans to drop support for Node v10 because the LTS only holds until 30. April 2021

**Comment by jeffposnick** [comment]
Yeah, potentially. But not until Workbox v7.

(To the point of this original issue, my goal is to migrate off of `joi` and onto https://github.com/rhys-vdw/ts-auto-guard soon, probably as part of Workbox v6, along with `workbox-build` TypeScript declarations that would be the source of truth.)
