### ISSUE TITLE
Regression in lerna versioning in the new gulp publish

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2610]
Hey @philipwalton—hopefully you can remember how you fixed this in the v5 branch, but unfortunately the v6 releases with the new `gulp publish` pipeline aren't getting the `lerna` version bump prior to the `npm` publish and `git` tag.

Do you happen to recall? Or if you could event just point me to the PR I could try to use that as the basis for re-adding it to the `gulp publish` pipeline.

**Comment by philipwalton** [comment]
I think it was these two PRs:

- https://github.com/GoogleChrome/workbox/pull/2335
- https://github.com/GoogleChrome/workbox/pull/2336

**Comment by jeffposnick** [comment]
Hmm, the code from those two PRs did carry over:

https://github.com/GoogleChrome/workbox/blob/d966d798a5e6ef4c16f090fa17a016d6060f9740/gulp-tasks/publish-lerna.js#L14-L15

and

https://github.com/GoogleChrome/workbox/blob/d966d798a5e6ef4c16f090fa17a016d6060f9740/gulp-tasks/build.js#L16-L50

I guess I'll poke around a bit.
