### ISSUE TITLE
Vulnerability in current version of serialize-javascript

### ISSUE THREAD

**Issue by longrunningprocess** [GoogleChrome/workbox#2611]
**Library Affected**:
workbox-build

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:
Please update to `rollup-plugin-terser 7.0.0` in order to resolve https://www.npmjs.com/advisories/1548

![image](https://user-images.githubusercontent.com/4412848/90520173-03b70b80-e137-11ea-84af-443c0e08c58b.png)

**Comment by jeffposnick** [comment]
Please see https://github.com/GoogleChrome/workbox/issues/2601#issuecomment-674084452

**Comment by longrunningprocess** [comment]
oh gosh, I thought I had searched for refs prior to creating but I either didn't or didn't use good search criteria :-(  I am so sorry
