### ISSUE TITLE
Basic stuff - how to install it!

### ISSUE THREAD

**Issue by blakemcbride** [GoogleChrome/workbox#2612]
Basic stuff, man.  Your page https://developers.google.com/web/tools/workbox/guides/get-started talks about how to use the system.  The first thing I need is how to install it!  Wasn't a problem in the past.  Not so easy to hunt down now.

First section in "Get Started" should be "How to install Workbox".

**Comment by Snugug** [comment]
Thanks for the feedback! We're taking a look at how to improve our documentation and yah, how to install it definitely should be at the top of getting started!

**Comment by simonh1000** [comment]
IT feels like if you use Webpack the installation process is completely different as well

**Comment by jeffposnick** [comment]
This is addressed by https://github.com/google/WebFundamentals/pull/9093
