### ISSUE TITLE
Confusion about additionalManifestEntries

### ISSUE THREAD

**Issue by joshkel** [GoogleChrome/workbox#2621]
**Library Affected**:

workbox-webpack-plugin 5.1.3

**Browser & Platform**:

All browsers

**Issue or Feature Request Description**:

I have some JSON assets, part of my `create-react-app`-and-ejected `public` directory, that are copied into my web directory. Since some of these are needed for the software to run, I'd like to precache them with Workbox. I'm using InjectManifest, so `additionalManifestEntries` seemed like a good approach to doing this. However, I'm having some problems:

1. If I pass an array of strings, I get a warning:

    > Some items were passed to additionalManifestEntries without revisioning info. This is generally NOT safe. Learn more at https://bit.ly/wb-precache.

    However, if I look at the generated service worker, the entries include revisions (presumably generated by InjectManifest), so it actually _is_ safe, and the warning is incorrect?

2. The [docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestEntry) state that the revision property is optional, so I tried passing objects with just a `url` property, in hopes of silencing the warning. However, that fails:

    > Please check your InjectManifest plugin configuration: child "additionalManifestEntries" fails because ["additionalManifestEntries" at position 0 does not match any of the allowed types]

    I saw where the [schema](https://github.com/GoogleChrome/workbox/blob/v5.1.3/packages/workbox-build/src/options/objects/manifest-entry.js) requires the revision property; can either the docs or schema be updated to clarify "required but may be null" versus "optional" (which I assumed meant "could be omitted")?

3. The behavior described in item 1 - where workbox-webpack-plugin adds entries to the manifest and generates revision hashes for them itself - is what I want, but I see in the docs that passing an array of strings is deprecated and will no longer be supported in Workbox v6. Is there a supported way of getting the behavior that I want? Or is additionalManifestEntries not the correct way of doing this?

Thank you.

**Comment by jeffposnick** [comment]
Apologies for the confusion. We've been a bit wishy-washy about enforcing the presence of the `revision` property over time; the current idea is that it should always be present, but can be set to `null` to explicitly indicate that the URL itself includes revision information (in the form of a hash, etc.).

I'll make sure our docs are updated for v6 to reflect that.

In terms of the easiest approach for your use case, using [`copy-webpack-plugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) to turn your files that exist on disk into `webpack` assets is probably the easiest approach. `workbox-webpack-plugin` will just include them in your normally generated precache manifest in that case.

**Comment by openscript** [comment]
Where can I file a PR on this issue?

It took me quite a while to figure out that the documentation is wrong and the `revision` property isn't optional as stated.

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestEntry

**Comment by jeffposnick** [comment]
Sorry, again. I've filed https://github.com/GoogleChrome/workbox/compare/revision-jsdoc-fix
