### ISSUE TITLE
Make BackgroundSyncPlugin._queue, Queue._onSync, Queue._queueStore public

### ISSUE THREAD

**Issue by jszczypk** [GoogleChrome/workbox#2623]
**Library Affected**:
workbox-background-sync

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
It would be useful in some situation to have possibility to access BackgroundSyncPlugin._queue. For example in browsers that do not support BackgroundSync API to force Queue to replay after user action or after window.online event.
It would be sufficient to expose Queue._onSync as BackgroundSyncPlugin public method.

There could also be a way to access QueueStore contents to show user number of stored requests or even show contents of the requests.

**Comment by TheForsakenSpirit** [comment]
@jszczypk  Hmm. But, why you don`t use [Queue](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync#advanced_usage) directly?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
