### ISSUE TITLE
Chrome Storage Quota 

### ISSUE THREAD

**Issue by Seems2Legit** [GoogleChrome/workbox#2624]
Hello,

I'm having an issue with the quota shown by Chrome. 

Firstly: After every reload the IndexedDB size increases by around 100 kB (clears itself at around 2.5 MB).

Secondly: The shown storage space taken is WAY too high. All our assets (css, images, js, html etc.) are combined around 25 MB but Chrome is showing the following:
![image](https://user-images.githubusercontent.com/24620002/91661550-189f8180-eadd-11ea-9138-346ca5e87bdc.png)

After deleting a file which is 14.8 kB in size
![image](https://user-images.githubusercontent.com/24620002/91661578-340a8c80-eadd-11ea-9d96-5b7db6d9805d.png)
the size shown by Chrome is decreased by more than 5 MB.

Why does this happen? Do I need to worry about it? And is it my fault this is happening or a Chrome bug?

Thanks in advance,
Seems2Legit

**Comment by Seems2Legit** [comment]
(Content-Length headers are not present due to Cloudflare minifying the files (probably not important))

**Comment by TheForsakenSpirit** [comment]
@Seems2Legit can you provide code of your service worker? (And place where image called)
I think you try to cache [opaque](https://developers.google.com/web/updates/2015/03/introduction-to-fetch#response_types) response. Each opaque response get about 7mb space independent of original size of response.

**Comment by jeffposnick** [comment]
Yes, [opaque responses](https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses#answer-39109790:~:text=Opaque%20Responses%20%26%20the%20navigator.storage%20API) are almost definitely responsible for what you're seeing, as @TheForsakenSpirit mentioned.

I'm going to close this issue, but if that somehow is *not* the underlying cause, please let us know.
