### ISSUE TITLE
webpack v5 compatibility

### ISSUE THREAD

**Issue by chenxsan** [GoogleChrome/workbox#2630]
**Library Affected**:

- workbox-webpack-plugin

**Browser & Platform**:

None

**Issue or Feature Request Description**:

webpack 5 [exposes `webpack-sources`](https://github.com/webpack/webpack/pull/11345) via `webpack.sources`, and it's advised to use it instead of `require('webpack-sources')`, if you agree to do it, I can submit a pull request.

**Comment by jeffposnick** [comment]
There's a number of non-trivial changes that are needed for webpack v5 compatibility. (C.f. https://github.com/webpack/webpack/issues/11425)

I'm working on implemented all of those changes in the Workbox v6 branch, hopefully in time for the next Workbox pre-release.

**Comment by chaffeqa** [comment]
great to hear! we just moved to webpack 5 and had to remove workbox since it was causing the build to error out.

**Comment by chaffeqa** [comment]
the WP5 branch is looking really good! would love to give it a test drive for you!

**Comment by jeffposnick** [comment]
This is now live as part of the v6.0.0-alpha.3 release: https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0-alpha.3
