### ISSUE TITLE
Google closure compiler warnings

### ISSUE THREAD

**Issue by simonh1000** [GoogleChrome/workbox#2631]
from package.json

        "google-closure-compiler": "^20200830.0.0",
        "workbox-strategies": "^5.1.4",
        "workbox-precaching": "^5.1.4",
        "workbox-routing": "^5.1.4",
        "workbox-webpack-plugin": "^5.1.4",
        "workbox-window": "^5.1.4"

I'm using webpack and run the closure compiler in STANDARD mode.

> WARNING in closure-compiler: Failed to resolve sourcemap at workbox-window.prod.es5.mjs.map: workbox-window.prod.es5.mjs.map

> WARNING in main-7b4cd7ddbc4d00c76990.js:10723 from closure-compiler: Left operand of && operator is always truthy.
> try{self["workbox:window:5.1.4"]&&_()}catch(n){}function n(n,t){return new Prom......

and 

> WARNING in main-7b4cd7ddbc4d00c76990.js:10723 from closure-compiler: Suspicious code. This code lacks side-effects. Is there a bug?
> try{self["workbox:window:5.1.4"]&&_()}catch(n){}function n(n,t){r

**Comment by jeffposnick** [comment]
My recommendation would be to ignore those warnings, as that's code is there intentionally, but if there's something we could do to get Closure Compiler not to complain by default, we can investigate doing that.

CC: @philipwalton who worked on that versioning string (and who also happens to know a decent amount about closure compiler).

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
