### ISSUE TITLE
optimize assets caches

### ISSUE THREAD

**Issue by behnam-maqsudi** [GoogleChrome/workbox#2635]
before cache media 
app size look like that 

<img width="622" alt="Screen Shot 1399-06-27 at 11 45 17" src="https://user-images.githubusercontent.com/40948849/93432862-596c0880-f8db-11ea-8d43-fba26ac4f566.png">

but after cache media (4 image) with 19KB size, application size look like that

<img width="622" alt="Screen Shot 1399-06-27 at 11 49 31" src="https://user-images.githubusercontent.com/40948849/93433327-e616c680-f8db-11ea-92f9-8c7fb1b7b013.png">

how optimize cache size?

**Comment by TheForsakenSpirit** [comment]
@benamm can you provide code of your service worker?
But I think you have problem with opaque responses. Check [this](https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses).
Quick fix - don`t cache response with '0' status code.
Or configure your cors to make request not opaque.

**Comment by behnam-maqsudi** [comment]
@TheForsakenSpirit i use next-pwa.

my configuration codes 
```
    const withPWA = require('next-pwa');
    module.exports = withPWA({
         pwa: {
         dest: 'public',
         },
   });
```
i don't write code for service workers
and this configuration i think use generatorSw workbox method and handled automatic

**Comment by TheForsakenSpirit** [comment]
@benamm I am not common with next-pwa, but I think it must have way to configure CachableResponsePlugin. Or, if you wont cache media from third party domain called from html try to use `crossorigin=anonymous` attributes.

**Comment by jeffposnick** [comment]
> Or, if you wont cache media from third party domain called from html try to use crossorigin=anonymous attributes.

Yes, that's what you would need to add to an `<img>` tag with a cross-origin URL if you want the browser to make a CORS request for that image.

If the browser makes CORS requests for your images, you don't need to change anything in your service worker, as the responses won't end up being opaque.

Just make sure that the CDN that hosts your images supports CORS. If it doesn't, then you don't have much choice here, and you'll end up consuming additional storage quota for your opaque responses—but it won't actually use additional disk space.

**Comment by behnam-maqsudi** [comment]
configure your cors to make request not opaque
@TheForsakenSpirit how do that? i try generate sw methods but i can't block opaque caches

**Comment by behnam-maqsudi** [comment]
@jeffposnick  i need store images bro but i want store in indexed..
now i read all methods in https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build
but i cant find solution for block opaque caches

**Comment by TheForsakenSpirit** [comment]
@benamm in [generateSW](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW) you can configure runtimeCaching with adding [RuntimeCachingEntry](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry) where you can set `cacheableResponse.statuses` as `[200]` (or another codes without '0')

PS. If you wont store images in indexedDB create your custom image handling with saving to DB inside app and add ignore in service worker.

**Comment by benamm** [comment]
@TheForsakenSpirit 
for save data to indexd db i have solution thanks bro.

but for example i request to https://picsum.photos/200/300 for get some data which one method in generateSW can be help block cache this url ?

**Comment by jeffposnick** [comment]
> configure your cors to make request not opaque
@TheForsakenSpirit how do that? i try generate sw methods but i can't block opaque caches

You need to add the attribute `crossorigin="anonymous"` to your DOM elements that trigger network requests.

For example,

```
<img src="https://third-party-cdn.com/image.png" crossorigin="anonymous">
```

Again, this is something you change in your web page, not your service worker. And again, make sure that your image CDN actually supports CORS, as it won't work otherwise.

**Comment by benamm** [comment]
@jeffposnick  l see bro .i understand you
i want to save this request with another way(indexed db).when i use crossorigin image not downloadable for me...
actually i mean to remove this cache name to generate sw
```
runtimeCaching: [
      {
        urlPattern: /.*/i,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'others',
          expiration: {
            maxEntries: 32,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          },
          networkTimeoutSeconds: 10,
        },
      },
    ],
``` 

this cached all data when i call third party domain.

when i add this code to config i have this error
```Error: [PWA] Fisrt item in runtimeCaching array is not "start-url"```

and i want use generate sw default config + remove this cache name 
I hope I was able to convey what I meant.
