### ISSUE TITLE
Allow the workbox runtime file to have a different name when using GenerateSW 

### ISSUE THREAD

**Issue by StephanBijzitter** [GoogleChrome/workbox#2637]
**Library Affected**:
Not sure....? It's regarding `workbox-webpack-plugin.GenerateSW`
https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW

**Browser & Platform**:
Not relevant

**Issue or Feature Request Description**:
We can change the name of the service worker itself using `swDest`, but we cannot change the name of the runtime chunk. Currently, this is `workbox-[contenthash:8].js` but all my other files use a full content hash (20 characters) and include `.min` in front of the file extension.

This results in my `dontCacheBustURLsMatching` options to be `/-([a-z0-9]{8}|[a-z0-9]{20})\./g`, which is quite ugly.

If I were to be able to change the name of the workbox runtime chunk, I could just let it have a 20-digit content hash and reduce my regular expression to `/-|[a-z0-9]{20}\./g`. Ideally, I'd also want to add `.min` to the name, but that (in my case) would just be visually more consistent.

Perhaps a `swRuntimeDest` option could be added?

**Comment by jeffposnick** [comment]
That's non-trivial to do, unfortunately. The code that produces the `workbox-...` runtime file is shared with `workbox-build`. It's actually not produced by `webpack`.

You should not need to include a pattern for the `workbox-...` runtime file in `dontCacheBustURLsMatching`, as that file shouldn't be included in your precache manifest: https://github.com/GoogleChrome/workbox/blob/bb21e8208ec093dd66fb61b5fbcdfd67314eb2bc/packages/workbox-webpack-plugin/src/generate-sw.js#L251-L253

If you're seeing the current `workbox-...` runtime file in your precache manifest, that sounds like a bug, and I'd like to take a look at your `webpack` configuration to figure out why it's happening.

**Comment by StephanBijzitter** [comment]
`workbox-*.js` is not in the precache manifest.

As I now (think I) understand from your message, `dontCacheBustURLsMatching` only applies to urls from the precache manifest. If that is indeed so, then yes, everything is fine just the way it is and I would have no reason for my feature request anymore. I initially thought `dontCacheBustURLsMatching` would also be applied to urls in the runtime cache.

**Comment by jeffposnick** [comment]
Right, `dontCacheBustURLsMatching` only applies to requests made by `workbox-precaching` to populate the precache.
