### ISSUE TITLE
Problem with serviceWorker.register and subDir

### ISSUE THREAD

**Issue by emilfrolov** [GoogleChrome/workbox#2646]
When I use `navigator.serviceWorker.register('/main/app-worker.js') ` registerRoute does not work, but when i change the path to `navigator.serviceWorker.register('/app-worker.js')` its work good. Help please.

###  app-worker.js

```javascript
registerRoute(
  ({ request }) => request.url.match(/\/widgets-static\/((?!meta).)*\.js/),
  new CacheFirst({
    cacheName: 'widgets',
    plugins: [
      new ExpirationPlugin({
        // Cache only 20 urls.
        maxEntries: 10,
        // Cache for a maximum of a week.
        maxAgeSeconds: 7 * 24 * 60 * 60,
      })
    ],
  }),
);
```

###  index.js

```javascript
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/main/app-worker.js').then((registration) => {
      // eslint-disable-next-line no-console
      console.log('SW registered: ', registration);
    }).catch((registrationError) => {
      // eslint-disable-next-line no-console
      console.log('SW registration failed: ', registrationError);
    });
  });
}
```

### webpack

```javascritp
module.exports = {
 ...
  output: {
    publicPath: '/main/'
  },
  ...
  plugins: [
    ...
    new WorkboxPlugin.InjectManifest({
      swSrc: path.resolve(PATHS.src, 'sw/app-worker.js')
    }),
    ...
});

**Comment by TheForsakenSpirit** [comment]
@emilfrolov when you register your service worker with routing `/main/` it will work only for `main` scope pages.

Check [this](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope)  link for more details.
And as I see from this [answer](https://stackoverflow.com/questions/53185323/service-worker-scope-and-spa-navigation) it don't work correctly with SPA and related routing imitation.
