### ISSUE TITLE
importScriptsViaChunks not supported with InjectManifest

### ISSUE THREAD

**Issue by Tomburgs** [GoogleChrome/workbox#2647]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Node

**Issue or Feature Request Description**:
Hello, I was attempting to use the `importScriptsViaChunks` parameter on the InjectManifest constructor, but got the following error:
```
Please check your InjectManifest plugin configuration:
"importScriptsViaChunks" is not a supported parameter.
```

According to the [documentation](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#InjectManifest) this should be possible, but perhaps this is just a documentation issue as the code doesn't seem to indicate any such functionality with InjectManifest?

**Comment by jeffposnick** [comment]
Apologies, the JSDoc is in fact incorrect.

In `InjectManifest` mode, you should be able to just pull in any code you want added to your service worker via ES module imports, without having to use `importScriptsViaChunks`. `webpack` will compile your `swSrc` file and translate the ES module imports into the ready-to-use `swDest` file.

**Comment by Tomburgs** [comment]
Thank you for your response, @jeffposnick.

My issue was that I wanted to pull in NextJS' build manifest file which is generated at compilation time, and I thought that it might've been possible with `importScriptsViaChunks`.

What I ended up doing was defining build id via webpack's DefinePlugin and calling `importScripts` inside the service worker file to get NextJS' build manifest definition. [Can have a look here.](https://github.com/Tomburgs/pwa-boilerplate/commit/14f2525d58f1bd1d23c8dbe6c673bf4f3c28f8ab)
