### ISSUE TITLE
Name too long when injecting serviceWorker manifest

### ISSUE THREAD

**Issue by blephy** [GoogleChrome/workbox#2648]
**Library Affected**:
*workbox-build 5.1.4*

**Issue or Feature Request Description**:
When i'm bundling my service-worker with webpack, in development mode to get a local production debugging, injectManifest is throwing to me this error :

> An error occured while injecting manifest in service worker. The swSrc file refers to a sourcemap that can't be opened: ENAMETOOLONG: name too long

I saw a PR which should fixe this error, but i'm still getting it 🤣 

```ts
const config = {
  globDirectory: 'build/',
  globPatterns: [
    '**/*.{html,css,js}',
    '**/*.{json,xml}',
    '**/*.{woff,woff2,eot,ttf,otf}',
    '**/*.{webp,ico,jpg,jpeg,png,svg,gif,txt,webmanifest,webm}'
  ],
  globFollow: true,
  globStrict: true,
  globIgnores: ['humans.txt', 'robots.txt', '.well-known/*'],
  maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
  swSrc: 'build/service-worker.js',
  swDest: 'build/service-worker.js'
}

export default config
```

```ts
/* eslint-disable no-console */
import { injectManifest } from 'workbox-build'

import workboxConfig from './workbox.config'

console.info('*****************************************************')
console.info('**     Injecting manifest into service worker      **')
console.info('*****************************************************')
console.info('')
console.info('Workbox configuration: ', workboxConfig)
console.info('')

injectManifest(workboxConfig).then(
  ({ count, size }) => {
    console.info(
      `Generated ${workboxConfig.swDest}, which will precache ${count} files (${size} bytes or ${size / 1000} Ko)`
    )
  },
  ({ message }) => {
    console.error('An error occured while injecting manifest in service worker.', message)
  }
)
```

**Comment by jeffposnick** [comment]
Hmm, I wonder if the code that parses out the expected filename for your `swSrc`'s sourcemap is confused by something like an inline sourcemap: https://github.com/GoogleChrome/workbox/blob/00ba07467b253751e874f53f424f2adb1c06e176/packages/workbox-build/src/inject-manifest.js#L158-L173

Could you share what the last line of your `swSrc` file looks like? That's the line that would normally have the [sourcemap comment](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map).

**Comment by blephy** [comment]
Yeah it's something with source map.

In webpack config, with devTools: false it's working

My error appears with eval-source-map

**Comment by blephy** [comment]
Yeah it's something with source map.

In webpack config, with `devTools: false` it's working.

My error appears with `devTools: 'eval-source-map'`

Reproductible repository : https://github.com/blephy/reactjs-typescript-pwa

bundled service-worker : https://gist.github.com/blephy/aa50238a1410e05075a2d24b995b6d2e

**Comment by jeffposnick** [comment]
Thanks. I've got a PR out for a fix.

In the meantime, if you use the `InjectManifest` plugin from `workbox-webpack-plugin` instead of doing a two-step, `webpack` compilation followed by `injectManifest` from `workbox-build`, I think it would be more straightforward and things would "just work".

**Comment by blephy** [comment]
I would be glad to use `workbox-webpack-plugin` but i can't with typescript...

**Comment by jeffposnick** [comment]
You should be able to. I can investigate that as a separate issue if that's the case.

We have a [test case](https://github.com/GoogleChrome/workbox/blob/v6/test/workbox-webpack-plugin/node/v5/inject-manifest.js#L1331-L1362) for this scenario. `InjectManifest` from `workbox-webpack-plugin` runs the `swSrc` file through a child compilation that should inherit the settings from the parent compilation, including any TypeScript transpilation.
