### ISSUE TITLE
Using fetch in SW causes reload error in chrome only (with devtools closed), not FF or Safari

### ISSUE THREAD

**Issue by ssuess** [GoogleChrome/workbox#2652]
I have discovered a bug in chrome or workbox or possibly with [register service worker](https://github.com/yyx990803/register-service-worker) package. After painstakingly dissecting the actions in my `register-service-worker.js` file, I have found an error with reload/update in chrome (only when console is closed!) that is related to making an axios (or fetch, I tried both) call in the updated hook. If I leave out that call, it updates fine, even when console is closed. Here is an always working updated hook:
```
updated (registration) {
    console.log('New content is available; please refresh.')
    const r = confirm('There is a new version available. Your version will be updated, alright? ')
    if (r === true) {
      localforage.clear().then(function () {
        // Run this code once the database has been entirely deleted.
        console.log('Database is now empty. so there now.')
        location.reload(true)
      }).catch(function (err) {
        // This code runs if there were any errors
        console.log(err)
      })
    } else {
      console.log('You pressed Cancel!')
    }
  },
```
And here is one that WONT work (in chrome with devtools closed), but works everywhere else:
```
updated (registration) {
    console.log('New content is available; please refresh.')
    fetch('https://pwatest.mydomain.com/av.json?t=' + Date.now())
      .then(response => {
        response.json().then(function (data) {
          const r = confirm('There is a new version (' + data.version + ') available. Your version will be updated, alright? ' + data.message)
          if (r === true) {
            if (data.clearStorage === true) {
              localforage.clear().then(function () {
                // Run this code once the database has been entirely deleted.
                console.log('Database is now empty. so there now.')
                location.reload(true)
              }).catch(function (err) {
                // This code runs if there were any errors
                console.log(err)
              })
            }
          } else {
            console.log('You pressed Cancel!')
          }
        })
        console.log('response:', response)
      })
      .catch(error => {
        console.error(error)
      })
  }
```
And just so we are crystal clear: the fetch works fine, and the alert contains the data from the fetch. But whenever using fetch (or axios) in ANY way in the service worker file in the updated hook, it causes a reload failure (in chrome only with devtools window closed).

The reload failure is a white screen of death btw, and when the console is opened at that point, there is always a ` Uncaught SyntaxError: Unexpected token '<'` error. Manual reloading after that recovers the site, but obviously this is terrible UI.

**Config:**
webpack - 4.44.2
workbox-webpack-plugin - 5.1.4
register-service-worker - 1.7.1
chrome - 87.0.xxxx (very important: devtools CLOSED. If open, update always completes normally. Checking/unchecking disable cache makes no difference).
workboxOptions: { skipWaiting: true, clientsClaim: true, ignoreURLParametersMatching: [/.*/] } // tried with and without ignoreURLParametersMatching, no difference

**Comment by ssuess** [comment]
Has no one else run into this problem? Does anyone else have a suggestion for being able to make axios/fetch calls from updated hook and reload without chrome browser failing?

**Comment by jeffposnick** [comment]
Your mention of different behavior with DevTools open or close sounds similar to https://github.com/GoogleChrome/workbox/issues/2632, but your specific setup isn't something that I'm familiar enough with to diagnose the root cause offhand.

**Comment by ssuess** [comment]
Thanks for your reply, I am curious, have you tried a fetch and reload from within the updated hook in a service worker and had it function correctly in chrome (with devtools CLOSED)? fetch (or axios take your pick) is the only thing that prevents reload from taking place, and ONLY in chrome (with devlools closed)

**Comment by ssuess** [comment]
I have been testing a fix which involves moving my fetch and update dialog and reload code to the `updatefound` hook instead of the `updated` hook. It has been working but I still need to do more testing. Fingers crossed!

**Comment by ssuess** [comment]
After several tests, I think this actually fixes this! (or at least works around this nasty chrome/workbox bug). Hope this helps someone else! Here is the code difference in my `register-service-worker.js` file:
```
import localforage from 'localforage'

register(process.env.SERVICE_WORKER_FILE, {
  ready () {
    console.log('App is being served from cache by a service worker.')
  },
  registered (registration) { // registration -> a ServiceWorkerRegistration instance
    console.log('Service worker has been registered.')
    // console.log('scope: ' + registration.scope)
  },
  cached (registration) { // registration -> a ServiceWorkerRegistration instance
    console.log('Content has been cached for offline use.')
  },
  updatefound (registration) {
      console.log('New content is available; please refresh.')
      fetch('https://pwatest.mydomain.com/av.json?t=' + Date.now())
        .then(response => {
          response.json().then(function (data) {
            const r = confirm('There is a new version (' + data.version + ') available. Your version will be updated, alright? ' + data.message)
            if (r === true) {
              if (data.clearStorage === true) {
                localforage.clear().then(function () {
                  // Run this code once the database has been entirely deleted.
                  console.log('Database is now empty. so there now.')
                  location.reload(true)
                }).catch(function (err) {
                  // This code runs if there were any errors
                  console.log(err)
                })
              }
            } else {
              console.log('You pressed Cancel!')
            }
          })
          console.log('response:', response)
        })
        .catch(error => {
          console.error(error)
        })
    },
    updated (registration) { // registration -> a ServiceWorkerRegistration instance
      console.log('New content is available; please refresh.')
      // console.log('is this stupid thing working?')
    },
    offline () {
      console.log('No internet connection found. App is running in offline mode.')
    },
    error (err) {
      console.error('Error during service worker registration:', err)
    }
})

**Comment by ssuess** [comment]
UGH, I REALLY hate to have to revisit this, but wouldn't you know it, this fix made all the OTHER browsers break! I ended up having to do this in the end, which really sucks:
```
 updatefound (registration) { // registration -> a ServiceWorkerRegistration instance
    console.log('New content is downloading.')
    /* eslint-disable no-extra-boolean-cast */
    if (!!window.chrome) {
      // all my checking and clearing localstorage stuff here for stupid chrome browsers (Chrome, Edge, etc)
    }
  },
  updated (registration) { // registration -> a ServiceWorkerRegistration instance
    console.log('New content is available; please refresh.')
    if (!window.chrome) {
      // all my checking and clearing localstorage stuff here for non chrome browsers (FF, Safari)
      }
    }
  },
```
