### ISSUE TITLE
PWA Install(plus) icon takes time to appear on browser

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [GoogleChrome/workbox#2661]
Hi,

I am using workbox GenerateSW to generate the service worker.When I run the project the plus icon takes 2-3 minutes or longer to appear on browser. I tried to find the solution but did not find any solution for that. What could be the possible reason for the delay. Does the size of the cache matters? If the cache size is bigger will it take time to show the plus icon?

**Comment by jeffposnick** [comment]
I don't think there are any guarantees about the timing for the Add to Homescreen icon's appearance in Chrome, and the heuristics used may vary depending on, e.g., how you interact with the origin.

Ultimately, if Workbox were generating a service worker that failed to register or something like that, then it would be something that we could investigate. Issues related to Chrome detecting a valid service worker, but delaying the Add to Homescreen icon, that's outside the scope of what we could investigate in this issue tracker. Sorry!

**Comment by anchal-chouvhan-altius** [comment]
How do we improve the performance of the service worker generated by
workbox generateSW? I have 103 MB of cache storage.

**Comment by jeffposnick** [comment]
You can precache fewer assets by excluding certain items from the precache manifest generation process. Configuration options, like [`exclude` and `include`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW), can help.

Additionally, if you're using runtime caching and some of your assets are loaded from third-party origins without CORS, that [could artificially inflate](https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests) the reported cache storage usage.

**Comment by anchal-chouvhan-altius** [comment]
Thank you Jeff.I will try this.
