### ISSUE TITLE
[Feature Request] swDest file name extension - how to change extension `.js` to other

### ISSUE THREAD

**Issue by wjureczka** [GoogleChrome/workbox#2662]
**Feature Request Description**:
I would like to change not only file name with option swDest, but also a extension from .js to other, for example to .mjs. How can I achieve that properly?

**Comment by jeffposnick** [comment]
That should already be supported—just add in a value like `swDest: 'service-worker.mjs'` into your `InjectManifest` config.

I just tried that out and it appeared to work fine in our test suite.

Do you have an example of a configuration in which it does not work? If so, let me know and we can revisit.
