### ISSUE TITLE
When browser blocks Google Analytics uncaught error is thrown in console

### ISSUE THREAD

**Issue by garygreen** [GoogleChrome/workbox#2663]
**Library Affected**:
workbox-sw, workbox-google-analytics

**Browser & Platform**:
Chrome v86.0.4240.111
Workbox v4.3.1

**Issue or Feature Request Description**:
When using `workbox.googleAnalytics.initialize()` if the browser blocked loading of Google analytics (e.g. as Firefox does for privacy reasons/or using Brave, or extensions such as ublock), an uncaught error is thrown in the console:

> Uncaught (in promise) no-response: The strategy could not generate a response for 'https://www.google-analytics.com/j/collect?v=1&_.....'. The underlying error is TypeError: Failed to fetch.  at NetworkOnly.makeRequest (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-strategies.dev.js:829:15)

![image](https://user-images.githubusercontent.com/1702638/98011618-01885300-1df0-11eb-8bae-a3eeaddfc71a.png)

This is understandable because it was blocked but it means this error is reported to console every single request.

Is there a way to configure Workbox to silently ignore errors when trying to post to Google analytics? Or an easy way to catch/swallow the exception that workbox throws?

As a side note - is workbox loading analytics js twice, if we also load it in our main app via standard script tag?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
