### ISSUE TITLE
Used ungeneric error type in `workbox-webpack-plugin`

### ISSUE THREAD

**Issue by shirohana** [GoogleChrome/workbox#2674]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*in Node.js, or whereever that can run webpack with workbox-webpack-plugin*

**Issue or Feature Request Description**:
As webpack plugin input, `compilation.warnings` is an array and preferred `WebpackError` as items, but `workbox-webpack-plugin` pushed some string into it, it may breaks some error reporting plugins or prints nothing.

##### [workbox-webpack-plugin/src/inject-manifest.js#L274-L282](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-webpack-plugin/src/inject-manifest.js#L274-L282)
```js
const warningMessage = `${this.constructor.name} has been called ` +
  `multiple times, perhaps due to running webpack in --watch mode. The ` +
  `precache manifest generated after the first call may be inaccurate! ` +
  `Please see https://github.com/GoogleChrome/workbox/issues/1790 for ` +
  `more information.`;

if (!compilation.warnings.includes(warningMessage)) {
  compilation.warnings.push(warningMessage); // <-- Unexpected push raw string here, about 5 places in total
}
```

##### [webpack/types.d.ts#L1313](https://github.com/webpack/webpack/blob/master/types.d.ts#L1313)
```js
declare class Compilation {
  ...
  errors: WebpackError[];
  warnings: WebpackError[];
  ...
}
```

##### [webpack/types.d.ts#L9673-L9682](https://github.com/webpack/webpack/blob/master/types.d.ts#L9673-L9682), [WebpackError.js](https://github.com/webpack/webpack/blob/master/lib/WebpackError.js)
```js
declare interface WebpackError extends Error {
  details: any;
  module: Module;
  loc: SyntheticDependencyLocation | RealDependencyLocation;
  hideStack: boolean;
  chunk: Chunk;
  file: string;
  serialize(__0: { write: any }): void;
  deserialize(__0: { read: any }): void;
}
```

I expect pushing *real* Error objects that it can keep the consistency and work well again with third-party reporters.

```sh
src/generate-sw.js|254 col 19| compilation.warnings.push(`${this.constructor.name} has been called ` +
src/lib/get-script-files-for-chunks.js|28 col 19| compilation.warnings.push(`${chunkName} was provided to ` +
src/lib/get-script-files-for-chunks.js|34 col 17| compilation.warnings.push(`There were no assets matching ` +
src/lib/get-manifest-entries-from-compilation.js|87 col 21| compilation.warnings.push(`The chunk '${chunkName}' was ` +
src/inject-manifest.js|281 col 21| compilation.warnings.push(warningMessage);
```

**Comment by jeffposnick** [comment]
Thanks for flagging this.

As far as I can tell, `WebpackError` isn't exported as part of the [`webpack` module interface](https://github.com/webpack/webpack/blob/master/lib/index.js). I'm assuming that means it's not meant to be used by third-party plugins.

I am happy to switch over to creating `Error` objects instead of using strings, though. Would that solve your issue?

And if you have an example of a third-party reporter that doesn't work well with error strings, could you tell me which one? I'd like to include it in our test suite to make sure that we don't regress in the future.

**Comment by shirohana** [comment]
Hello ٩(｡・ω・｡)

Changing plain text to `Error` can solve my problem, thank you for that!

The reporter I mentioned is [friendly-error-webpack-plugin](https://www.npmjs.com/package/friendly-errors-webpack-plugin), although this plugin was last released 3 years ago, but still be downloaded million times per month.

https://github.com/geowarin/friendly-errors-webpack-plugin/blob/master/src/core/extractWebpackError.js#L16

![image](https://user-images.githubusercontent.com/11359892/99136471-f3dc9400-265f-11eb-8dca-454cb4404136.png)
