### ISSUE TITLE
Upgrade strip-comments

### ISSUE THREAD

**Issue by sergey-v9** [GoogleChrome/workbox#2678]
**Library Affected**:
workbox-build

**Browser & Platform**:
webpack ([react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts))

**Issue or Feature Request Description**:
Is possible to upgrade `strip-comments` to 2.0.1 again?
It was done before in #2280, but was reverted in #2300 due to incompatibility with Node 8 (#2415, #2297)
Maybe its time to go forward with this?

**Comment by jeffposnick** [comment]
It's upgraded to 2.0.1 in the v6 (pre)releases: https://github.com/GoogleChrome/workbox/blob/f2ef9126f36cbf1219e9c27997ac0c4d873a0ca8/packages/workbox-build/package.json#L42
