### ISSUE TITLE
Suggestion for docs/comment: returning `undefined` from route handler to bypass service worker

### ISSUE THREAD

**Issue by teggno** [GoogleChrome/workbox#2680]
## Suggestion
When the handler function passed to `registerRoute()` returns something false-y instead of a `Promise` we essentially get a route that bypasses the service worker which is quite helpful sometimes. My suggestion is to mention this in the code comments and/or in the docs.

### Why I think the would be helpful:
One could explicitly exclude the route from all other route definitions to achieve the same thing but this would mean that`setDefaultHandler()` couldn't be used any more. Also it would make the other route definitions more difficult to interpret and tedious to write.

### Why I want to bypass the service worker for the route:
The route is `({ request }) => request.destination === "audio"` and I only want that to be served directly from the network. If I register it as `NetworkOnly` I get some CORS issues because of redirect server responses. If I totally bypass the service worker I don't have to deal with that.

**Comment by jeffposnick** [comment]
I'm not sure that's behavior we want to encourage, and the specifics of what happens when a `handlerCallback` returns something other than a promise might change in the future.

If it would help, we could try to figure out why `NetworkOnly` isn't working out for you, because I think it should handle redirects.

Alternatively, something like the following that just uses `fetch()` directly _should_ work:

```
registerRoute(
  ({request}) => request.destination === 'audio',
  ({request}) => fetch(request),
);
```

**Comment by teggno** [comment]
I get that you don't want to encourage this behavior given it might not be stable.

I've tried with `fetch()` but it failed in the same way as using `NetworkOnly()`. So I went on analyzing and have found a solution. Here's what I have and how I think I solved it:

### Set up
``` html
<!-- 
   src is set using JavaScript. It's not known at build time 
   because it's provided by the user 
-->
<audio crossorigin="anonymous" />
```

``` JavaScript
// service worker

registerRoute(
  ({ request }) => request.destination === "audio",
  new NetworkOnly()
);
```
### Issue
When setting the `src` of `<audio>` to an url that results in a `302` redirect, the dev tools show an error when the request is sent by the service worker.
> Access to fetch at 'https://traffic.libsyn.com/secure/syntax/Syntax298.mp3?dest-id=532671' from origin 'https://my-dev-machine.dev:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

### Cause
It appears that the issue is caused by the `range` request header and the request being sent by the service worker using `fetch()` (i.e. no error if there's no service worker).

### Solution
Adding `access-control-request-headers = range` to the headers of the request seems to fix the issue. This is the case for the url that's returning the `302` but also works for an url that doesn't.

### Remarks
The behavior including the error message is the same for:
* Using `fetch()` in `registerRoute()` instead of using `new NetworkOnly()`
* Not using workbox but just handling the `fetch` event with a vanilla handler that's using `fetch()`.
* There's no issue if there's no redirect.

**Comment by jeffposnick** [comment]
Glad you figured things out; that makes sense.

I wrote a little more about this at https://jeffy.info/2019/07/22/exposing-cors-headers.html, by the way, as it's something that comes up from time to time.
