### ISSUE TITLE
webpack plugin loads the previous tag - 

### ISSUE THREAD

**Issue by zerdos** [GoogleChrome/workbox#2684]
The 6.0.0 plugin should load the 6.0.0 instead of 6.0.0-rc.0 
(The 6.0.0-rc.0 was loading the 6.0.0-alpha3)

The issues is with the lerna script, with ```lerna publish``` it bumps up everything, and pushes the versions without build.

Solution: do ```lerna version``` first, then build, then publish.

Library Affected:
workbox-webpack-plugin

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Issue or Feature Request Description**:
*Your request here.*

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
Thanks. We're tracking it in https://github.com/GoogleChrome/workbox/issues/2610 and should get it resolved in an upcoming release. (This shouldn't actually affect any functionality, as far as I can tell.)

**Comment by jeffposnick** [comment]
(Hopefully this will be fixed with https://github.com/GoogleChrome/workbox/pull/2690, in time for the `6.0.2` release.)
