### ISSUE TITLE
Add hooks to GenerateSW

### ISSUE THREAD

**Issue by hypernova7** [GoogleChrome/workbox#2688]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*"all browsers"*

**Issue or Feature Request Description**:
I don't know if it is a good idea or if it is possible to add the **swHooks** option to the GenerateSW of workbox-webpack-plugin. So in every event that is executed in the sw file, new custom functions can be added. something like an API.

For example, inject an object into the sw.js file with all the hooks that are added to the **swHooks** option.

**webpack.config.js**
~~~javascript
import { GenerateSW } from 'workbox-webpack-plugin'
// ...
plugins: [
  new GenerateSW({
    swDest: 'sw.js',
    cacheId: 'workbox-v1',
    swHooks: {
      install: (event, api) => {
        event.waitUntil(async () => {
          const cache = await caches.open(api.cacheId)
          await cache.add('https://example.com/offline-page.html', {
            cache: 'reload'
          })
        })
      },
      active: (event, api) => {
      },
      fetch: (event, api) => {
        if (event.request.mode === 'navigate') {
          event.respondWith((async () => {
            try {
              const preloadResponse = await event.preloadResponse
              if (preloadResponse) {
                return preloadResponse
              }
              const networkResponse = await fetch(event.request)
              return networkResponse
            } catch (e) {
              const cache = await caches.open(api.cacheId)
              const cachedResponse = await cache.match('https://example.com/offline-page.html')
              return cachedResponse
            }
          })())
        }
      }
    }
  })
]
~~~

**sw.js**
~~~javascript
const swHooks = {
  install: (event, api) => {
    event.waitUntil(async () => {
      const cache = await caches.open(api.cacheId) // <-- access to cacheId 'workbox-v1'
      await cache.add('https://example.com/offline-page.html', {
        cache: 'reload'
      })
    })
  },
  active: (event, api) => {
  },
  fetch: (event, api) => {
    if (event.request.mode === 'navigate') {
      event.respondWith((async () => {
        try {
          const preloadResponse = await event.preloadResponse
          if (preloadResponse) {
            return preloadResponse
          }
          const networkResponse = await fetch(event.request)
          return networkResponse
        } catch (e) {
          const cache = await caches.open(api.cacheId) // <-- access to cacheId 'workbox-v1'
          const cachedResponse = await cache.match('https://example.com/offline-page.html')
          return cachedResponse
        }
      })())
    }
  }
}
const emitHook = (hook, ...args) => {
  if (swHooks && swHooks[hook]) {
    swHooks[hook](...args)
  }
}
self.addEventListener('install', (e) => {
  // here would go the configuration or default code that adds GenerateSW
  // in the sw file, and at the end would go the function that executes the hook
  emitHook('install', e, api)
})
self.addEventListener('fetch', (e) => {
  // here would go the configuration or default code that adds GenerateSW
  // in the sw file, and at the end would go the function that executes the hook
  emitHook('fetch', e, api)
})
~~~
It would also be nice if one of the arguments passed to the hook allowed access to the name or prefix of each of the different cacheIds or cacheNames registered by runtimeCaching(*As show above*). In order to add more items to the cache record, be it an offline page or something else

*Hope it's a good idea*

**Comment by jeffposnick** [comment]
My inclination is to not add in support for that amount of imperative code within the `GenerateSW` declarative configuration.

If you'd like to have explicit control over the imperative code run in your service worker, then writing your service worker "by hand" and pulling in the bits of Workbox that you need via ES modules is the supported path for that. The `InjectManifest` build tool allows you to do that while still precaching based on your asset pipeline.

The most recent updates to our [Getting Started guide](https://developers.google.com/web/tools/workbox/guides/get-started#using_workbox) encourage that type of usage.

We're going to continue supporting the `GenerateSW` use case, because there are some folks who _don't_ need that level of customization and could get away with just using declarative options. But we're not likely to greatly increase the scope of what you could do with `GenerateSW`.

**Comment by jeffposnick** [comment]
One more thing to note: if you do need to pull in some additional imperative code and you want to continue using `GenerateSW`, then the [`importScripts`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#parameter_1:~:text=traffic.-,importScripts) (or `importScriptsViaChunks`, in the `workbox-webpack-plugin`) option is a clean way to do that.
