### ISSUE TITLE
The condition that detects webpack 4 is broken

### ISSUE THREAD

**Issue by momakes2** [GoogleChrome/workbox#2689]
**Library Affected**:
workbox-webpack-plugin@6.0.0

**Browser & Platform**:
macOS, webpack 4.44, in a yarn 1 monorepo with nextjs

**Issue or Feature Request Description**:
I use Webpack ^4.44 and I noticed this condition doesn't work as expected:

File: `workbox-webpack-plugin/build/generate-sw.js:242`

```
apply(compiler) {
    this.propagateWebpackConfig(compiler); // webpack v4/v5 compatibility:
    // https://github.com/webpack/webpack/issues/11425#issuecomment-690387207

    if (webpack.version.startsWith('4.')) { // <<<<<<<<<<<<<<<< THIS
      compiler.hooks.emit.tapPromise(this.constructor.name, compilation => this.addAssets(compilation).catch(error => compilation.errors.push(error)));
    } else {
```
I was getting a weird error which did not happen with webpack 5, so figured to patch it to be always true for webpack 4 and it worked! So I think the if is broken in some cases.

**Comment by jeffposnick** [comment]
That's very strange; based on the [`webpack@4.44.2` source code](https://unpkg.com/browse/webpack@4.44.2/lib/webpack.js#LC16:~:text=const%20version%20%3D%20require(%22..%2Fpackage.json%22).version%3B), as well as our test suite, I'm not sure why that wouldn't work.

What version of `node` are you using? If you patch the code to add a `console.log(webpack.version)` before that statement, what is logged? And is there any exception thrown?

**Comment by jeffposnick** [comment]
I'm going to close this for now, as it's not something that we can reproduce. If you can still reproduce the issue, and can get back to me with those additional details, we can revisit.
