### ISSUE TITLE
PrecacheController: need .install and .activate methods that don't call event.waitUntil internally

### ISSUE THREAD

**Issue by ItalyPaleAle** [GoogleChrome/workbox#2694]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
For PrecacheController objects, the methods `install` and `activate` call `event.waitUntil` internally. While this is convenient for most people, for my application I need to have more granular control over what gets initialized and when. In fact, I need to perform multiple operations, some in sequence and some in parallel.

Ideally, the lambda function used inside those methods would be exported as a separate method.

For example, for the `activate` function.... Current:

```js
activate(event) {
    return waitUntil(event, async () => {
        const cache = await self.caches.open(this.strategy.cacheName);
        const currentlyCachedRequests = await cache.keys();
        const expectedCacheKeys = new Set(this._urlsToCacheKeys.values());
        const deletedURLs = [];
        for (const request of currentlyCachedRequests) {
            if (!expectedCacheKeys.has(request.url)) {
                await cache.delete(request);
                deletedURLs.push(request.url);
            }
        }
        if (process.env.NODE_ENV !== 'production') {
            printCleanupDetails(deletedURLs);
        }
        return { deletedURLs };
    });
}
```

An idea could be to replace it with:

```js
activate(event) {
    return waitUntil(event, this.activateMethod);
}

async activateMethod() {
    const cache = await self.caches.open(this.strategy.cacheName);
    const currentlyCachedRequests = await cache.keys();
    const expectedCacheKeys = new Set(this._urlsToCacheKeys.values());
    const deletedURLs = [];
    for (const request of currentlyCachedRequests) {
        if (!expectedCacheKeys.has(request.url)) {
            await cache.delete(request);
            deletedURLs.push(request.url);
        }
    }
    if (process.env.NODE_ENV !== 'production') {
        printCleanupDetails(deletedURLs);
    }
    return { deletedURLs };
}
```

(Similar thing for the `install` method)

This way, people who want the convenience of having `event.waitUntil` called for them can continue using the first method. For people who need more control over the initialization like me, the second method would allow me to call `event.waitUntil` with my own init sequence.

**Comment by jeffposnick** [comment]
CC: @philipwalton, who worked on this code most recently.

I just wanted to clarify something—apologies if you're already aware of this, but [`waitUntil()`](https://w3c.github.io/ServiceWorker/#wait-until-method) does not cause the service worker to pause or delay other asynchronous tasks. It ensures that the service worker thread isn't killed prematurely, but doesn't fundamentally change the order of operations.

**Comment by ItalyPaleAle** [comment]
Thanks @jeffposnick ! Yes, that is precisely my problem: I actually need the service worker to pause until the precaching is done.

I have 3 async tasks that I need to run in the `activate` event handler. Two need to run in parallel (including `precacheController.activate`) and the third needs to wait for the first two. 

Code is here:

https://github.com/ItalyPaleAle/prvt/blob/v0.6.0-beta.1/ui/src/sw/sw.ts#L49-L67

I did a workaround by passing a mock `event` object that does nothing but satisfied the contract of the workbox-precaching APIs, as you can see there. But that is very hacky :)

**Comment by jeffposnick** [comment]
I'll defer to @philipwalton on what your options are.

**Comment by jeffposnick** [comment]
...so it's been a while, and I think this described use case is uncommon enough, and the code in the `PrecacheController` is "important" enough, that we don't want to fundamentally change anything if we could avoid it.

If your "hacky" approach accomplishes what you need, then that might be as good as it will get.

Alternatively, the `PrecacheController` will call any Workbox plugins you add to it, and will call `await` on each `async` callback, which can delay the caching process. So using a [custom Workbox plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins) that performed whatever work you needed and didn't resolve until it was complete might be another, cleaner approach.
