### ISSUE TITLE
Add a build-tool option to generate subresource integrity metadata

### ISSUE THREAD

**Issue by pimterry** [GoogleChrome/workbox#2697]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Everywhere

**Issue or Feature Request Description**:
SRI works really well with precaching. It's easy to implement (see https://github.com/google/WebFundamentals/pull/9165) and I think with a generated manifest it's _always_ preferable. I.e. I don't see any plausible use cases where you want to generate a manifest of content to precache, but you don't know for sure what content you're expecting.

Given that it's preferable, it has a huge upside, both in security but also reliability: I've seen real production situations where CDN response bodies were truncated, and the default precaching settings broke my app (persistently!) by caching syntactically invalid scripts.

Is there a clear argument for why including integrity checks with precache manifests isn't the default?

**Comment by jeffposnick** [comment]
Hello @pimterry!

`workbox-precaching` allows you to precache opaque responses by default, i.e. there is no requirement that cross-origin URLs in your precache list are served with CORS.

Using SRI with cross-origin URLs [only works](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#Cross-Origin_Resource_Sharing_and_Subresource_Integrity) if the remote server supports CORS.

If generating SRI info is straightforward via a `node` module, as you illustrate in your example, then I'd be in favor of making it easier for folks to do that via, say, an opt-in configuration option, with documentation that warns folks not to turn it on if there are cross-origin, non-CORS URLs in their precache list.

Making this opt-in also has the advantage of not being a breaking change.

**Comment by pimterry** [comment]
Interesting! That makes sense, that's a solid case where precaching in general can't use this.

That said, for manifest generation I'm surprised that that's supported - I'm only suggesting enabling this in the manifest generation step, rather than for all precaching. Is it expected that you'd generate a manifest for a site and generate a service worker in the same build from that manifest, but then serve some of the build content from a different origin? Aren't all paths in manifests relative to the origin of the service worker?

An easy option to enable this would be nice to have anyway imo. Doesn't affect me much at this stage since I've set it up myself now anyway, but I would've saved a bunch of time debugging and then digging through webpack docs yesterday if this more easily available :smile:

**Comment by jeffposnick** [comment]
Over the years, I've found that there's a non-trivial number of folks who deploy all their locally-built subresources to a CDN, and then use the [`modifyURLPrefix`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#parameter_1:~:text=used.-,modifyURLPrefix) option to prepend the CDN's URL in the manifest. So that's a use case we need to continue supporting.

I'll leave this issue open to track adding in an opt-in configuration option for SRI.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
