### ISSUE TITLE
No response found in the 'my-cache' cache.

### ISSUE THREAD

**Issue by davidmaxwaterman** [GoogleChrome/workbox#2698]
**Library Affected**:
    "workbox-cli": "^3.6.2"
    "workbox-range-requests": "^3.6.2",
    "workbox-sw": "^3.6.2"

**Browser & Platform**:
Google Chrome | 87.0.4280.88 (Official Build) unknown (64-bit)
Ubuntu 20.04.1 LTS

**Issue or Feature Request Description**:
The issue is during development on localhost:8000.
It seems workbox is claiming my cache has no entry matching the request:

```workbox-core.dev.js:132 workbox No response found in the 'build-media' cache```

due to:
```
The FetchEvent for "http://localhost:8000/manifest/media/e460e3d099bfa7c4538825ce705bf75f-57904.m4a" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) | @ | workbox-routing.dev.js:837
````
I can see from dev tools Application/Cache that it is in the cache, and I don't see any such problems running on a non-localhost server.

The oddity that is worth mentioning is that I am using cacheOnly in my sw, and my app is fetch()ing the files manually and cache.put()ing the files into the cache with a key that is the pathname prepended with '/manifest'. The app then requests the 'fake' paths as seen above. The main reason I do this so that I can get fine grained loading progress. I do clone the response and cache.put() the cloned response.

It also seems to only be a problem for the m4a files - my jpg files in the same cache seem to work 'just fine'. However, both types seem to work fine on non-localhost server.

Any ideas?

**Comment by davidmaxwaterman** [comment]
I see to get the same problem if I add a `background-image: url("/manifest....")` in dev tools...I get no 'hit' in the service worker 'match' callback :/

**Comment by jeffposnick** [comment]
Is there a `Vary:` header on your responses, perhaps? C.f. https://github.com/GoogleChrome/workbox/issues/1550

**Comment by davidmaxwaterman** [comment]
Yes, the localhost responses do have a Vary header, and the ones on the real server do not:

```Vary: Accept-Encoding```

I followed the link you gave, and the links in that, but it's not entirely clear what I need to change.

This seemed a better link than the ones in #1550:

https://w3c.github.io/ServiceWorker/#dictdef-cachequeryoptions

IE, somehow I need to set `ignoreVary` to true.

I see `matchOptions` here:

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-strategies.CacheOnly#matchOptions

and...

https://developer.mozilla.org/en-US/docs/Web/API/Cache/match

So, I tried this:

```
workbox.routing.registerRoute(
  ({url}) => {
    const {pathname} = url;
    const retVal = !!pathname.match(mediaRegExp);

    if (retVal) {
      console.log(`SW: resolving ${pathname} from ${mediaCacheName}.`);
    } else {
      console.log(`SW: ${pathname} not in ${mediaCacheName}.`);
    }

    return retVal;
  },
  workbox.strategies.cacheOnly({
    cacheName: mediaCacheName,
    matchOptions: {
      ignoreVary: true,
    },
    plugins: [
      new workbox.rangeRequests.Plugin(),
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200, 304]
      })
    ]
  })
);
```

I also attempt a cache.match() when I decide to fetch() the real file in the first place, so I also added the option there:

```
        await myCache.match(file, {ignoreVary: true})
```

I did have an unrelated problem (snafu) that was confusing matters, but all-in-all...seems to be working now, so thanks :D
