### ISSUE TITLE
I need some help upgrading from v5 to v6

### ISSUE THREAD

**Issue by sugarcanehyena** [GoogleChrome/workbox#2702]
Hello, today I'm upgrading my code from v5 to v6.

My v5 Code was this:

```js
    const OFFLINE_URL = "/offline";

    var mainPages = new workbox.strategies.StaleWhileRevalidate({
        cacheName: "document",
    });

    const matcher = ({ event }) => event.request.mode === "navigate";

    const customHandler = async (args) => {
        try {
            const response = await mainPages.handle(args);
            return response || (await caches.match(OFFLINE_URL));
        } catch (error) {
            return await caches.match(OFFLINE_URL);
        }
    };
    
    workbox.routing.registerRoute(matcher, customHandler);
```

The above code caches a new `document` navigation and does a fallback to the `offline` page.

I saw in the Migration docs from v5 to v6 it suggests to use this:

```js
    workbox.routing.registerRoute(
        ({ request }) => request.mode === 'navigate',
        new workbox.strategies.NetworkOnly({
            plugins: [
                new workbox.precaching.PrecacheFallbackPlugin({
                    fallbackURL: '/offline',
                }),
            ],
        })
    );
```

The above code only does a fallback to the `offline` page.

One big issue I got with that code is that I want to create this pattern:

1. A user navigates to a new web page and the service worker checks the cache to see if a cached version exists and displays the cached version.

2. If no cached version of the web page exists then the service worker tries to get the `document` from the network and then stores the `document` in the cache.

3. If no cached version exists and no network then the service worker loads the fallback page.

(hope I make sense)

I'm stuck on how to modify your v6 code suggestion to also **cache the navigated** `document` and wondered if you could help, please.

Also I think it would be useful to add the code example to the v6 docs as well.

**Comment by jeffposnick** [comment]
You should be able to handle that via something very similar to what you're already doing, with some logic simplified by taking advantage of the new `handlerDidError` plugin callback:

```
// You need to add /offline to the cache at some point,
// i.e. during an install handler.
const OFFLINE_URL = "/offline";

workbox.routing.registerRoute(
  ({request}) => request.mode === 'navigate',
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: 'document',
    plugins: [
      {handlerDidError: () => caches.match(OFFLINE_URL)},
    ],
  })
);
```

There's more information about writing your own Workbox plugins at https://web.dev/extending-workbox/#custom-plugins

**Comment by sugarcanehyena** [comment]
@jeffposnick 

Thank you! One issue though, my precache was saving it as:

```
/offline?__WB_REVISION__=383676
```

and Workbox wasn't working when I was doing:

```js
const OFFLINE_URL = "/offline";
```

I had to use this:

```js
const OFFLINE_URL = "/offline?__WB_REVISION__=383676";
```

I was expecting Workbox to cut off the query string.

**Comment by jeffposnick** [comment]
In that case, you can switch to `caches.match(OFFLINE_URL, {ignoreSearch: true})`, or actually you could just use `PrecacheFallbackPlugin`. Based on your original question, I assumed you _weren't_ precaching `OFFLINE_URL`.
