### ISSUE TITLE
Upgrade to v6 produces "Uncaught non-precached-url, index.html"

### ISSUE THREAD

**Issue by bhollis** [GoogleChrome/workbox#2706]
**Library Affected**:

workbox-webpack-plugin, workbox-precaching

**Browser & Platform**:

All browsers

**Issue or Feature Request Description**:

Hi there, we've been using Workbox for quite a long time! Recently we upgraded from v5.1.1 to v6.0.2, without changing our [service worker script](https://github.com/DestinyItemManager/DIM/blob/master/src/service-worker.ts) or [Webpack configs](https://github.com/DestinyItemManager/DIM/blob/master/config/webpack.js#L473-L488), and all of a sudden started seeing `Uncaught non-precached-url` referring to `index.html`. 

Our `index.html` is *NOT* in the generated list there in `__precacheManifest` - in fact none of our HTML is. All our HTML is generated from the latest HtmlWebpackPlugin 4.5.0 (We're also on Webpack 5.11.0). I also notice that all of the entries in `__precacheManifest` have `revision: null`, e.g.: `{ revision: null, url: '/107-5b5f29.js' },`

This prevented our service worker from installing at all. As far as I could tell, everything had been working fine before this (after reverting, I see `index.html` in the cache).

Relevant webpack configs extracted from [the full config](https://github.com/DestinyItemManager/DIM/blob/master/config/webpack.js):

```
      new HtmlWebpackPlugin({
        inject: true,
        filename: 'index.html',
        template: 'src/index.html',
        chunks: ['main', 'browsercheck'],
        templateParameters: {
          version,
          date: new Date(buildTime).toString(),
          splash,
        },
      }),

      // Generate a service worker
      new InjectManifest({
        include: [/\.(html|js|css|woff2|json|wasm)$/, /static\/.*\.(png|gif|jpg|svg)$/],
        exclude: [
          /version\.json/,
          /extension-dist/,
          /\.map$/,
          // Ignore both the webapp manifest and the d1-manifest files
          /data\/d1\/manifests/,
          /manifest-webapp/,
          // Android manifest
          /\.well-known/,
        ],
        swSrc: './src/service-worker.ts',
        swDest: 'service-worker.js',
      })
```

Our service worker in its entirety:

```
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import {
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
} from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

self.__precacheManifest = self.__WB_MANIFEST.concat(self.__precacheManifest || []);

precacheAndRoute(self.__precacheManifest, {});
cleanupOutdatedCaches();

// Once this activates, start handling requests through the service worker immediately.
// No need to wait for a refresh.
clientsClaim();

registerRoute(
  /https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,
  new CacheFirst({
    cacheName: 'googleapis',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, purgeOnQuotaError: false }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
  'GET'
);

// Since we're a single page app, route all navigations to /index.html
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  // These have their own pages (return.html)
  // This regex matches on query string too, so no anchors!
  denylist: [/return\.html/, /\.well-known/, /\.(json|wasm|js|css|png|jpg|map)(\.(gz|br))?$/],
});
registerRoute(navigationRoute);

self.addEventListener('message', (event) => {
  if (!event.data) {
    return;
  }

  switch (event.data) {
    case 'skipWaiting':
      self.skipWaiting();
      break;
    default:
      // NOOP
      break;
  }
});
```

**Comment by jeffposnick** [comment]
The current stable release of `html-webpack-plugin` has some issues with changes introduced in `webpack` v5. It can produce assets that other plugins, like `workbox-webpack-plugin`, can't process.

As per https://github.com/jantimon/html-webpack-plugin/issues/1527#issuecomment-747944268, `html-webpack-plugin@5.0.0-beta.1` should be working. I'd suggest updating to that if you're using `webpack` v5.

Regarding the `revision: null` set for so many entries in the precache manifest, that's an expected optimization; we now (#2673) take advantage of metadata from the `webpack` build indicating that a given asset is immutable, meaning that we don't have to keep track of revision information for it.

Given that this appears to be due to a known issue with `html-webpack-plugin`, I'm going to close this, but please let us know if you still run into any issues after upgrading.

**Comment by bhollis** [comment]
Awesome, thanks. It'd be great to have that info in the upgrade guide or 6.0.0 release notes.

**Comment by jeffposnick** [comment]
(FWIW, we do [call out](https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0#tag-select-menu-76f59f90-4603-11eb-9244-5f78c5428ec6:~:text=workbox%2Dwebpack%2Dplugin%20will%20also%20now%20take%20advantage,webpack%20automatically%20adds%20to%20hashed%20assets.) that we're now using the `immutable` metadata in the "webpack improvements" section of https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0.)
