### ISSUE TITLE
self.__WB_MANIFEST is undefined

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/workbox#2710]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
- Webpack: v4.44.2
- Workbox: v6.0.2 (also replicated on v5.1.4)

**Issue Description**:
When debugging inside my service worker I noticed that `self.__WB_MANIFEST` is undefined and unless defaulting to an empty array (`precacheAndRoute(self.__WB_MANIFEST || [])`), it throws an exception:

![Screenshot from 2020-12-28 19-36-23](https://user-images.githubusercontent.com/8075326/103241002-3b8a5700-4952-11eb-8920-7b72b7e33d27.png)

**webpack.config.js**
```
plugins: [
    new WorkboxPlugin.InjectManifest({
      swSrc: './service-worker.js',
      swDest: 'sw.js',
      include: [/\.js$/, /\.css$/]
    }),
  ]
```

**service-worker.js**
```
import { precacheAndRoute } from 'workbox-precaching/precacheAndRoute';

precacheAndRoute(self.__WB_MANIFEST);
```

I am not sure how I am able to debug this further and any pointers would be helpful. I am not sure if it is related to a particular Webpack configuration or an issue with `InjectManifest`. If helpful, here's the full [webpack.config.js](https://github.com/kevinfarrugia/performance-first-react-template/blob/master/scripts/webpack.config.js).

Thank you

**Comment by jeffposnick** [comment]
If you're getting that error, it would imply that the `InjectManifest` plugin isn't actually being executed as part of your build, as the job of the `InjectManifest` plugin is to replace `self.__WB_MANIFEST` with an array of entries to precache. Could you check whether your configuration is actually leading to the plugin being applied? You should see an entry created by `InjectManifest` corresponding to your `swDest` as part of the `webpack` post-build stats.

**Comment by kevinfarrugia** [comment]
Thank you for following up.

I can confirm that it is now loading the `self.__WB_MANIFEST` correctly and it contains the expected array of entries to precache. I have not done any changes to the webpack configuration (or anything else related to this) so I cannot understand why this issue appeared and now disappeared by itself. If it re-occurs I will debug as you have suggested.
