### ISSUE TITLE
Default values at the docs

### ISSUE THREAD

**Issue by rrd108** [GoogleChrome/workbox#2711]
**Issue or Feature Request Description**:
*request: list the default values in the docs of GenerateSW*

**Comment by jeffposnick** [comment]
Thanks for raising this–we do have the default values in the JSDocs, from which our documentation is derived, but the JSDoc to HTML publishing flow that we're currently using ends up dropping them.

We have some updates to this flow planned, and I think we can get it addressed.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
