### ISSUE TITLE
get response with backgroundsync

### ISSUE THREAD

**Issue by rrd108** [GoogleChrome/workbox#2714]
**Library Affected**:
workbox-background-sync

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
How can I get the server response when the backgroundsync was successfull?
I am posting a task and I need the id from the API response.

**Comment by rrd108** [comment]
I made a plugin for this: https://www.npmjs.com/package/@rrd/workbox-backgroundsync-message

At the moment it is for vue apps.

I think the easiest way to do it is to fire `fetchDidSucceed` event in the `replayRequest()` method. By that we would be able to hook in.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
