### ISSUE TITLE
Workbox throws warning but still caches it (was provided in your Workbox chunks config, but was not found in the compilation.)

### ISSUE THREAD

**Issue by pmochine** [GoogleChrome/workbox#2717]
**Library Affected**:
workbox-webpack-plugin: ^6.0.2

**Issue or Feature Request Description**:
Currently, I'm upgrading from workbox-webpack-plugin: ^4.3.1 to ^6.0.2, but I noticed a warning that I'm not sure how I should solve it.

It says: `WARNING in The chunk '/js/manifest' was provided in your Workbox chunks config, but was not found in the compilation``

The weird part is that the `manifest.js` file is still cached by the SW (this same warning happens for `vendor.js` as well and is cached too)

![image](https://user-images.githubusercontent.com/25006691/104040289-bf0c3980-51d7-11eb-9083-f806a4f2869b.png)

Why does it still cache it when it says it couldn't find it?

Besides that, I'm struggling to find out what exactly my chunk name for manifest is. I know this is an issue from another plugin, however since using Laravel Mix v6.*, I cannot see the chunk names. It only outputs this in the terminal:

```
Laravel Mix v6.0.8   
                        

✔ Compiled Successfully in 38735ms
┌───────────────────────────────────┬────────────┐
│ File                              │ Size       │
├───────────────────────────────────┼────────────┤
│ /js/vendor.js                     │ 4.05 MiB   │
├───────────────────────────────────┼────────────┤
│ css/app.css                       │ 246 KiB    │
├───────────────────────────────────┼────────────┤
│ /js/app.js                        │ 104 KiB    │
├───────────────────────────────────┼────────────┤
│ images/vendor/intl-tel-input/bui… │ 69.2 KiB   │
├───────────────────────────────────┼────────────┤
│ service-worker.js                 │ 22.8 KiB   │
├───────────────────────────────────┼────────────┤
│ js/6231.9b6787592e9af06465aa.js   │ 6.46 KiB   │
├───────────────────────────────────┼────────────┤
│ js/1901.f3d670a3cfb776389054.js   │ 6.17 KiB   │
├───────────────────────────────────┼────────────┤
│ /js/manifest.js                   │ 6.15 KiB   │
```

But this clearly shows how `/js/manifest.js` is written.

In the `webpack.mix.js` file I wrote this:

 ```
       new InjectManifest({
            swSrc: './resources/js/sw.js',
            swDest: 'service-worker.js',
            // precaching only these.
            chunks: [
                'routes-settings', 'routes-sell-food', 'routes-checkout',
                '/js/app', '/js/moment', '/js/canvas', '/js/manifest',
                '/js/vendor',
            ],
            maximumFileSizeToCacheInBytes: 5000000,
        }),
```

Everything in the chunks array worked well besides the `/js/manifest` and `/js/vendor`. 

p.S. I hope there are no misunderstandings, I want to cache those two files, but I'm just curious why the warnings are still there

**Comment by jeffposnick** [comment]
The `chunks` option allows you to say "only precache the `webpack` chunks with matching [_chunk_ names](https://webpack.js.org/glossary/#c)".

Based on that error message, `'/js/manifest'` isn't a _chunk_ name that matches any of the chunks in your `webpack` configuration. `'/js/manifest.js'` looks like it's an [_asset_ name](https://webpack.js.org/glossary/#a).

That warning message is logged to let you know that you're providing values that are effectively being ignored. If you're happy with what's being cached already—if the `'/js/manifest.js'` asset is precached by virtue of membership in one of the valid chunks that you listed–then you should just remove those invalid chunk names from the `chunks` array.

If you want asset-level allow/deny filtering in your configuration, you could switch from using the `chunks` configuration option to the [`include`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#:~:text=manifest.-,include,-Optional)/[`exclude`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#:~:text=not.)-,exclude,-Optional) options instead. Those will match against asset names when determining what to include or exclude.

**Comment by pmochine** [comment]
@jeffposnick ok thanks and I tried to put your tips into practice. However, it would be cool if you use chunks and include at the same time.
Like:

            chunks: [
                'routes-settings', 'routes-sell-food', 'routes-checkout',
                '/js/app', '/js/moment', '/js/canvas',
            ],
            include: [
                '/js/vendor.js',
                '/js/manifest.js',
            ],

The problem is that now it's ignoring the chunk array and I'm not able to move everything else to the include array, because my assets names are dynamically build. Like: `js/routes-settings.06b4e2da0d151…`

Any idea what I could do?

Thanks nonetheless :)

**Comment by jeffposnick** [comment]
The underlying code in question is https://github.com/GoogleChrome/workbox/blob/2df5ce58bd74abd8da4ec90e427f0e4431a0cff2/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L62-L141

That code should add an asset to the precache manifest if both of these compound conditions are true:

- The asset is a member of a chunk that's allowed via the `chunks` config, **or** the asset matches the criteria in `include`.
- The asset is **NOT** a member of a chunk that's listed in the `excludeChunks` config, **and** the asset does not match the criteria in `exclude`.

So yes, both `chunks` and `include` can be used at the same time.

If you're still seeing warnings like _The chunk '/js/app' was provided in your Workbox chunks config, but was not found in the compilation_, it's because those aren't the names of chunks that exist in your `webpack` configuration. Workbox can't do much else beyond warn if you provide an name for a chunk that doesn't exist.

Based on your elaboration of the problem, if you're looking for more flexibility to support asset names that include hashes, your best bet would be to use `include` and pass in something other than strings as the parameters. `include`, as mentioned in the Workbox docs, supports any [`webpack` condition](https://webpack.js.org/configuration/module/#condition), and those conditions could be RegExps or predicate functions. Under the hood, Workbox actually just calls the same code that `webpack` uses:

https://github.com/GoogleChrome/workbox/blob/2df5ce58bd74abd8da4ec90e427f0e4431a0cff2/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L15-L41

**Comment by pmochine** [comment]
@jeffposnick I love you effort and support. You are really the best! <3

Nonetheless, I would love to update my first comment.  You are saying:

> The `chunks` option allows you to say "only precache the `webpack` chunks with matching [_chunk_ names](https://webpack.js.org/glossary/#c)".
> 
> Based on that error message, `'/js/manifest'` isn't a _chunk_ name that matches any of the chunks in your `webpack` configuration. `'/js/manifest.js'` looks like it's an [_asset_ name](https://webpack.js.org/glossary/#a).

However, now with the updated knowledge of getting the [chunk names back](https://github.com/JeffreyWay/laravel-mix/issues/2762), 
this still is an issue that should work but is not working in my case.

Have a look at my shortened output table. This time with the given chunk names:

```

┌─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┐
│ (index) │                                                   name                                                    │       chunks       │
├─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│    0    │                                              '/js/vendor.js'                                              │    '/js/vendor'    │
│    1    │                               'js/routes-sell-food.ee6e0be44b06c89b924d.js'                               │ 'routes-sell-food' │
│    2    │            'js/resources_js_pages_display-offer_food_FoodWrapper_vue.e94dc467e9c848a49e03.js'             │         ''         │
│    3    │                               'js/routes-settings.852ab7f8e4eb92b7afbe.js'                                │ 'routes-settings'  │
│    4    │                                               '/js/app.js'                                                │     '/js/app'      │
│    5    │                               'js/routes-checkout.da638b66167b33d22137.js'                                │ 'routes-checkout'  │
│    6    │                                            'service-worker.js'                                            │         ''         │
│   17    │                                               'css/app.css'                                               │     'css/app'      │
│   72    │                                             '/js/manifest.js'                                             │   '/js/manifest'   │
```

And in my first comment, I showed you my chunks array:

```
      new InjectManifest({
           swSrc: './resources/js/sw.js',
           swDest: 'service-worker.js',
           // precaching only these.
           chunks: [
               'routes-settings', 'routes-sell-food', 'routes-checkout',
               '/js/app', '/js/moment', '/js/canvas', '/js/manifest',
               '/js/vendor',
           ],
           maximumFileSizeToCacheInBytes: 5000000,
       }),
```

But still I'm getting the warning of:

![image](https://user-images.githubusercontent.com/25006691/104495473-1a736880-55d8-11eb-82ec-a7e36ec2bfaa.png)

(Ignore the last warning obviously)

This shouldn't happen, I wonder what the problem is. I'm going to try out a dummy project, so you can check what the real problem is.

**Comment by pmochine** [comment]
@jeffposnick here is a basic laravel package with workbox. This results in the same two warnings.

https://github.com/pmochine/workbox-laravel-mix

Thank you for your help

**Comment by jeffposnick** [comment]
Thanks for that clean reproduction!

From examining that while debugging, I can see that `compilation.namedChunkgroups`, which is what Workbox is currently using, only has one entry (for the `/js/app` chunk). `compilation.namedChunks`, however, has four entries, including the chunks that you're trying to use.

<img width="1559" alt="Screen Shot 2021-01-14 at 12 50 30 PM" src="https://user-images.githubusercontent.com/1749548/104629348-61f50580-5667-11eb-8cb7-163e20044477.png">

I'm going to have to do a little research into `webpack`'s innards to see what the difference is between `compilation.namedChunkgroups` and `compilation.namedChunks`, and we can potentially switich to using `compilation.namedChunks` in this part of the `workbox-webpack-plugin` code if it seems like the right thing to do.
