### ISSUE TITLE
example in docs doesn't work for iframe

### ISSUE THREAD

**Issue by davidmaxwaterman** [GoogleChrome/workbox#2722]
**Library Affected**:
workbox-sw

**Browser & Platform**:
chrome: 87.0.4280.141 (Official Build) unknown (64-bit)

**Issue or Feature Request Description**:
https://developers.google.com/web/tools/workbox/modules/workbox-routing

```
const handlerCb = async ({url, request, event, params}) => {
  const response = await fetch(request);
  const responseBody = await response.text();
  return new Response(`${responseBody} <!-- Look Ma. Added Content. -->`); 
};
```

I have a service worker which uses workbox 3.6.3, and my PWA have an iframe that loads an html file and the sw attempts to manipulate the html on-the-fly using the above techique; but it seems to be added to the iframe wrapped in `<pre>...</pre>`:

```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;!DOCTYPE html&gt;
<!-- the contents of the html file is here -->
&lt;/script&gt;
</pre></body></html>
```

Perhaps I'm misinterpreting the example, but it seems to be applicable to what I'm trying, but it doesn't work.
Is there some way to do what I want?

**Comment by davidmaxwaterman** [comment]
Turns out I needed to copy the response.headers into the new response's options:

```
return new Response(`${responseBody} <!-- Look Ma. Added Content. -->`, {headers: response.headers});
```

I suggest that is added to the example to prevent more people like me ;)

**Comment by jeffposnick** [comment]
Sure, that sounds like a reasonable change to the docs.
