### ISSUE TITLE
WorkboxWebpackPlugin.GenerateSW: "non-precached-url" error after updating from v5 to v6

### ISSUE THREAD

**Issue by sshrshnv** [GoogleChrome/workbox#2732]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:

I have an error in the console after updating workbox-webpack-plugin from v5.1.4 to v6.0.2:

![Screenshot 2021-01-19 113946](https://user-images.githubusercontent.com/7159528/105009892-1d44e200-5a4c-11eb-830e-f43bbb518853.png)

And offline lighthouse test is broken now.

My config:

```
cacheId: 'rentalreport',
navigateFallback: '/index.html',
navigateFallbackAllowlist: [/^(?!\/__)/],
swDest: 'sw.js',
clientsClaim: true,
skipWaiting: true,
cleanupOutdatedCaches: true,
exclude: [/\.mp4$/, /\.map$/, /\.cache$/],
runtimeCaching: [{
  urlPattern: /\.(?:jpe?g|png|svg|css|js)$/,
  handler: 'NetworkFirst'
}]
```

I didn't find how update config for v6.0.2.
What do I need to change?

**Comment by jeffposnick** [comment]
What does you precache manifest (the array that's passed in to `precacheAndRoute()`) look like in your generated service worker? Are you manually editing that list in some way, like by adding in `'index.html'`?

**Comment by jeffposnick** [comment]
You'll get that error if you use `navigateFallback` and pass in the URL of an HTML document that isn't precached.

If you want to use `navigateFallback: 'index.html'`, then make sure that your `index.html` document is included in your precache manifest.

Are you usinig `html-webpack-plugin` (if so, which version?) to generate your `index.html`, or some other approach? And what version of webpack are you using?

**Comment by sshrshnv** [comment]
`index.html` is not included in the precache manifest

`GenerateSW v6.0.2` generates `sw.js` which includes only:
`e.registerRoute(new e.NavigationRoute(e.createHandlerBoundToURL("/index.html")`

`GenerateSW v5.1.4` generates `sw.js` which includes:
`e.precacheAndRoute([{url:"/index.html",revision:"5cb3ce05c54e0ab0fe42583e6b65801a"},...])`
and
`e.registerRoute(new e.NavigationRoute(e.createHandlerBoundToURL("/index.html")`

Yes, I use `html-webpack-plugin v4.5.1` and `webpack v5.15.0`.

**Comment by jeffposnick** [comment]
Thanks for that info. I believe what's going on is that you're using a version of `html-webpack-plugin` that isn't fully compatible with `webpack` v5. Your generated `index.html` ends up not being visible to `workbox-webpack-plugin` when using `webpack` v5, so it can't be precached.

As per the current [`html-webpack-plugin` docs](https://github.com/jantimon/html-webpack-plugin#webpack-5), you need to use the `next` release for `webpack` v5 compatibility:

```
npm i --save-dev html-webpack-plugin@next
```

**Comment by meliceanu** [comment]
https://github.com/vite-pwa/vite-plugin-pwa/issues/731
