### ISSUE TITLE
Please document, that fetchOptions is ignored when request.mode is 'navigate'

### ISSUE THREAD

**Issue by rubas** [GoogleChrome/workbox#2741]
**Library Affected**:
workbox-strategies

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

Please mention in the documentation that `fetchOptions` for a `workbox-strategies` is ignored when `request.mode === 'navigate'`. One might spend hours chasing 👻 ...

This behaviour was introduced with https://github.com/GoogleChrome/workbox/pull/1862 and still exists today in [v6](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-strategies/src/StrategyHandler.ts#L193).

Original issue is still open: https://github.com/GoogleChrome/workbox/issues/1796

**Comment by jeffposnick** [comment]
Sorry about that 😦 . We can get this added to the docs, since I'm still not sure how we're going to resolve #1796. (Implementing in Workbox v7 the work around that broke older versions of Edge is one option, since Edge is now using Chromium under the hood.)
