### ISSUE TITLE
Cannot read property '_db' of undefined

### ISSUE THREAD

**Issue by teodragovic** [GoogleChrome/workbox#2742]
**Library Affected**:
*workbox-expiration*

**Browser & Platform**:
*Chrome 88.0.4324.146, Windows 10 build 21296.1010*

**Issue or Feature Request Description**:
Hi, I'm getting `TypeError: Cannot read property '_db' of undefined` repeatedly in console when running service worker in production. Locally, with debug on, it doesn't happen. 

The error points to [this line](https://github.com/GoogleChrome/workbox/blob/ae29e1748bb976351db8e0c64a9ea9fc8ba2583f/packages/workbox-core/src/_private/DBWrapper.ts#L244) in `DBWrapper` and I managed to pinpoint it to `ExpirationPlugin`. Error is thrown for every asset that matches route where I use expiration plugin with given strategy (I tested with `CacheFirst` and `StaleWhileRevalidate` with same results). When I remove `ExpirationPlugin`, no errors. Except for the console log errors, the service worker seems to work fine.

This is offending code on my end (mostly copied from recipes with minor adjustments)
```
registerRoute(
    ({ request, url }) => request.destination === 'image' && url.origin === process.env.APP_URL,
    new CacheFirst({
        cacheName: 'app-images',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [ 0, 200 ],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 30,
                maxEntries: 60,
            }),
        ],
    })
);

registerRoute(
    ({ url }) => url.origin === process.env.STATIC_URL,
    new CacheFirst({
        cacheName: 'app-fonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [ 0, 200 ],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365,
                maxEntries: 10,
            }),
        ],
    })
);
```

**Comment by jeffposnick** [comment]
Thanks for reporting this—I'll look into reproducing it locally, but if you did happen to have a public URL that you could share at which I could access your site, that would speed things up. (Feel free to DM `@jeffposnick` on Twitter if you can't post it here.)

Also, what version of Workbox are you seeing this with? And i assume you're generating your own bundled service worker using something like Rollup or webpack?

**Comment by teodragovic** [comment]
Sorry, forgot to mention it - I use workbox 6.1.0 via `preact-cli` (webpack under the hood). Custom sw is generated using [this guidelines](https://preactjs.com/cli/service-worker).

Dev link is sent on twitter DM.

**Comment by teodragovic** [comment]
closing this as it seems to be transpilation issue on my end
