### ISSUE TITLE
[Feature] Allow navigateFallback to be passed as null

### ISSUE THREAD

**Issue by ElMassimo** [GoogleChrome/workbox#2743]
### Feature Request ✨ 

I would like to propose adding [`allow(null)`](https://github.com/GoogleChrome/workbox/compare/v6...ElMassimo:v6) to the schema definition for [`navigateFallback`](https://github.com/GoogleChrome/workbox/compare/v6...ElMassimo:v6).

That would allow for simpler [merging of options](https://github.com/antfu/vite-plugin-pwa/blob/720d28f7d2caeb3127096045791004ac3651169e/src/config.ts#L62) when using a library that [provides a default](https://github.com/antfu/vite-plugin-pwa/blob/720d28f7d2caeb3127096045791004ac3651169e/src/config.ts#L43) for `navigateFallback`, and is also consistent with the TypeScript `string?` typing.

**Comment by jeffposnick** [comment]
👋 

I'm in the middle of rewriting the validation logic in `workbox-build` to rely on TypeScript definitions, enforced at runtime with https://github.com/rhys-vdw/ts-auto-guard

I was planning on using:  https://github.com/GoogleChrome/workbox/blob/1e946bffad4bdb7cd620b45c5833fd4c8f0ee353/packages/workbox-build/src/types.ts#L79

but I can switch that over to `navigateFallback?: string | null`.

Are there other options that you think would benefit from that as well? It seems like it would potentially be needed for a lot of them...

**Comment by ElMassimo** [comment]
That sounds great!

I think it makes sense for any `string` options that are optional, like `cacheId` and `directoryIndex`, where passing `null` explicitly allows to opt-out from any [defaults](https://github.com/ElMassimo/workbox/blob/v6/packages/workbox-precaching/src/utils/generateURLVariations.ts#L26-L26).

Edit: On a closer look, `globDirectory` could also benefit from the same approach.

**Comment by jeffposnick** [comment]
Okay, I've added it to https://github.com/GoogleChrome/workbox/commit/1c2df4ff17cf58ea5bf1f4caa0997f0cf12de4c4
