### ISSUE TITLE
InjectManifest is not minified

### ISSUE THREAD

**Issue by mycolaos** [GoogleChrome/workbox#2746]
I'm using workbox with `https://github.com/shadowwalker/next-pwa`, and it's not clear at all if the file in output should be minified by the `InjectManifest` plugin or not. I get a huge 5k+ line file with a lot of comments in output.
https://developers.google.com/web/tools/workbox/guides/using-bundlers#configure_your_bundler_for_a_development_or_production_build here I can read that this is minifiable, not that it's minified. I'm not even sure if it's a bug or lack in documentation.

The question is, how should I get an optimized `sw.js`? Minifying? Tree shaking? Is there an exhausting doc?

**Comment by jeffposnick** [comment]
The `InjectManifest` build tool helps generate a list of URLs and revisions to be precached, and replaces a placeholder (`self.__WB_MANIFEST` by default) in the `swSrc` file with that information.

It doesn't attempt to do bundling, or minification. It's focused on that specific task of generating and injecting the manifest.

https://github.com/terser/terser is a good, modern tool for minifying JavaScript, and if you're looking for a recommendation, I'd suggest that.
