### ISSUE TITLE
The workbox-google-analytics package does not support Google Analytics 4

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2759]
**Library Affected**:
*workbox-google-analytics*

The current version `workbox-google-analytics` supports catching and replying failed beacons sent to the [Measurement Protocol v1](https://developers.google.com/analytics/devguides/collection/protocol/v1). However, for [Google Analytics 4 properties using gtag.js](https://developers.google.com/analytics/devguides/collection/ga4), beacons are now sent to a new, currently undocumented endpoint.

<img width="988" alt="Screen Shot 2021-02-17 at 9 08 10 AM" src="https://user-images.githubusercontent.com/326742/108241303-89287200-7100-11eb-8d0f-eab7ef6a723a.png">

GA4 beacons can be distinguished from prior version beacons by looking at the `v=2` param (previously it was `v=1`).

In v1, replayed hits would use the [`qt`](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#qt) (queue time), but based on internal conversations, this param is no longer supported in GA4. The v2 version (again, currently undocumented) now uses the `ht` param (hit time) which represents the timestamp (in ms, epoch time) that the event occurred.

This should actually make it easier to support GA4 (as long as the param isn't changed in the future). The logic should be to add or update the `ht` param in the URL path (not the POST body) based on when the beacon was originally sent.

**Comment by jeffposnick** [comment]
We've moved our thoughts on the future of offline analytics to https://github.com/GoogleChrome/workbox/issues/3055

(After further discussion, we don't feel comfortable coding against undocumented GA4 parameters in an official library.)
