### ISSUE TITLE
Allow navigateFallback option for GenerateSW to be an array of multiple routes

### ISSUE THREAD

**Issue by StephanBijzitter** [GoogleChrome/workbox#2760]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Irrelevant.

**Issue or Feature Request Description**:
I generate an app shell for every language my SPA supports, essentially: I have as many SPAs as languages. They all use the same service worker, the only difference is just that each index.html contains a reference to a specific translation file.

So my URLs look like this:
```
/en/some/page
/nl/some/page
/de/some/page
```

Currently, I can only set `navigateFallback` to a single fallback value.... which in my case means forcing a single language onto my users if they happen to lose their network connection.

For example, I've currently set it to `/en/index.html`, which means if the user is on a page `/nl/some/page`, they actually get an English page rather than a Dutch page. This is not exactly ideal.

Essentially, I'd like to be able to change this:
```
// slightly beautiful minified output
        i.registerRoute(new i.NavigationRoute(i.createHandlerBoundToURL('/en/index.html'))),
```

into this:
```
// slightly beautiful minified output
        i.registerRoute(/\/en\/.*/, i.createHandlerBoundToURL('/en/index.html')),
        i.registerRoute(/\/nl\/.*/, i.createHandlerBoundToURL('/nl/index.html')),
```

Perhaps there's a better way of doing it, but this should also be easy enough for the option while preserving backward compatibility:
```
    navigateFallback: [
        {urlPattern: /\/en\/.*/, fallback: '/en/index.html'},
        {urlPattern: /\/nl\/.*/, fallback: '/nl/index.html'}
    ],
```

**Comment by StephanBijzitter** [comment]
I'd definitely be willing to create a pull request for this, provided someone gives me the go-ahead :-)

**Comment by jeffposnick** [comment]
First, to clarify, `navigateFallback` isn't an option that's intended for "users if they happen to lose their network connection." The route that it sets up will use a cached response whenever there's any navigation request for any URL that isn't explicitly precached. It's meant for SPA-style routing, like you say, but I just to make sure you were aware that it's not really an offline-specific thing.

But to get to your actual question, I think the best course of action would be for you to switch to using the `InjectManifest` mode of the build tool instead of `GenerateSW`, which will give you more control over the logic in your service worker. Then, assuming you're using Workbox v6, you could explicitly write code along the lines of:

```
import {precacheAndRoute, matchPrecache} from 'workbox-precaching';
import {registerRoute} from 'workbox-routing';

// The InjectManifest build tool will replace self.__WB_MANIFEST with your
// actual list of URL and revisions.
precacheAndRoute(self.__WB_MANIFEST);

// See https://developers.google.com/web/tools/workbox/modules/workbox-routing#matching_and_handling_in_routes
// for info on matchCallbacks and handlerCallbacks.
registerRoute(
  // If this is a navigation request, return the language code,
  // assuming it's the first part of the path.
  // Otherwise, return null, which won't trigger the route.
  ({request, url}) => request.mode === 'navigate' ? url.pathname.split('/')[1] : null,

  // Use a custom handlerCallback that has access to the params returned by
  // the previous matchCallback function.
  async ({request, params}) => {
    const response = await matchPrecache(`/${params}/index.html`);
    if (response) {
      return response;
    }
    // If you get here, the expected /LANGUGE/index.html file was not included in your precache manifest.
    // It's up to you what to do—maybe return matchPrecache('/en/index.html') as the default?
  }
);
```

I think that kind of imperative logic is a lot more scalable that trying to capture all the possibilities into something that could be expressed in a declarative config file.

If you have any other `runtimeCaching` rules in your configuration file, you would translate those into `registerRoute()` calls, using the strategies from `workbox-strategies`.

There's more info about this approach in our current [Getting Started guide](https://developers.google.com/web/tools/workbox/guides/get-started). Let me know if this approach sounds reasonable, and we can close this issue.

**Comment by StephanBijzitter** [comment]
Alright, I just got around to changing my configuration.

I appreciate the thorough comment! I was probably going to need `InjectManifest` at one point either way, so I guess this was the needed motivation to do it now rather than later.

There's just one option I couldn't figure out and that's how I can split the `workbox-*` dependencies into a different file, much like `GenerateSW` does by default. But assuming browsers respect 304s when downloading service workers, that's not too much of a problem really.

Before:
```js
new GenerateSW({
    mode,
    sourcemap: true,
    clientsClaim: true,
    skipWaiting: true,
    directoryIndex: 'index.html',
    offlineGoogleAnalytics: mode === 'production',
    dontCacheBustURLsMatching: /-[a-z0-9]{20}\./,
    navigateFallback: '/en/index.html',
    exclude: [
        // Images don't need to be pre-cached (cache only if in use)
        /\.(png|jpg|jpeg|webm|gif|svg|map)$/,
        // Translations don't need to be pre-cached (cache only if in use)
        /[a-z]{2}(?:-[A-Z]{2})?-[a-z0-9]{20}\.min\.js/
    ],
    runtimeCaching: [{
        urlPattern: /./,
        handler: mode === 'production' ? 'StaleWhileRevalidate' : 'NetworkFirst'
    }]
})
```

After:
```js
new InjectManifest({
    mode,
    swSrc: resolve('src/frontend/service-worker.ts'),
    swDest: 'service-worker.js',
    injectionPoint: 'self.__WB_MANIFEST',
    dontCacheBustURLsMatching: /-[a-z0-9]{20}\./,
    exclude: [
        // Images don't need to be pre-cached (cache only if in use)
        /\.(png|jpg|jpeg|webm|gif|svg|map)$/,
        // Translations don't need to be pre-cached (cache only if in use)
        /[a-z]{2}(?:-[A-Z]{2})?-[a-z0-9]{20}\.min\.js/
    ]
})
```

Service Worker file:
```ts
import {initialize as initializeGoogleAnalytics} from 'workbox-google-analytics';
import {precacheAndRoute, matchPrecache} from 'workbox-precaching';
import {registerRoute} from 'workbox-routing';
import {StaleWhileRevalidate, NetworkFirst} from 'workbox-strategies';
import {defaultLocale, getLocale} from '../helpers/locales';

declare var self: ServiceWorkerGlobalScope;

self.addEventListener('install', () => {
    void self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

precacheAndRoute(self.__WB_MANIFEST);

registerRoute(({request, url}) => {
    if (request.mode !== 'navigate') {
        return false;
    }

    if (url.pathname === '/') {
        for (const language of self.navigator.languages) {
            const locale = getLocale(language);

            if (locale) {
                return locale.iso;
            }
        }

        return defaultLocale.iso;
    }

    return getLocale(url.pathname.split('/')[1])?.iso ?? defaultLocale.iso;
}, async ({params}) => {
    return await matchPrecache(`/${params as unknown as string}/index.html`)
        || await matchPrecache(`/${defaultLocale.iso}/index.html`)
        || Response.error();
});

registerRoute(/./, process.env.NODE_ENV === 'production' ? new StaleWhileRevalidate() : new NetworkFirst());

if (process.env.NODE_ENV === 'production') {
    initializeGoogleAnalytics();
}
```

**Comment by jeffposnick** [comment]
Under the hood, `workbox-webpack-plugin`'s `GenerateSW` mode uses Rollup, which sounds surprising, but we really want to keep the core code consistent between all the different build tools. Splitting out the dependencies, like the Workbox runtime libraries, into separate chunks is handled via https://github.com/surma/rollup-plugin-off-main-thread:

https://github.com/GoogleChrome/workbox/blob/80be8b16aba62fa927e5c3c19e55f8d16a78e808/packages/workbox-build/src/lib/bundle.js#L69-L76

I've never successfully done something similar when using `webpack` for bundling, though. https://github.com/webpack/webpack/issues/10520 and https://github.com/webpack/webpack/issues/6472 are related issues.
