### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch in Strategy

### ISSUE THREAD

**Issue by gfoidl** [GoogleChrome/workbox#2761]
**Library Affected**:
*workbox-strategies* 6.1.0
(webpack v4 with inject plugin) 

**Browser & Platform**:
*Gooble Chrome Version 88.0.4324.182*

**Issue or Feature Request Description**:
The error should not be uncaught, as the strategy delivers a result.

It's not a public web-app, so sorry that I can't share an url.
Basically it's just a backend-server with a REST-based API, and the frontend witht the service-worker.

The service-worker registers for the API's GET a route with network-first strategy:
```ts
const apiGetHandler = new NetworkFirst({
    cacheName: "Foo-Web-api-get",
    plugins  : [
        new ExpirationPlugin({
            purgeOnQuotaError: true,
            maxEntries       : 500
        })
    ]
});
registerRoute(/\/api\//, apiGetHandler, "GET");
```

<details>
  <summary>service worker code (full)</summary>

```ts
import { clientsClaim, setCacheNameDetails }                                from "workbox-core";
import { BackgroundSyncPlugin }                                             from "workbox-background-sync";
import { ExpirationPlugin }                                                 from "workbox-expiration";
import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { NavigationRoute, registerRoute }                                   from "workbox-routing";
import { NetworkFirst, NetworkOnly }                                        from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

setCacheNameDetails({
    prefix: "Foo-Web",
    suffix: ""
});

const networkFirstStrategy = new NetworkFirst();
registerRoute(/^\/(index.html)?$/, networkFirstStrategy);

const apiGetHandler = new NetworkFirst({
    cacheName: "Foo-Web-api-get",
    plugins  : [
        new ExpirationPlugin({
            purgeOnQuotaError: true,
            maxEntries       : 500
        })
    ]
});
registerRoute(/\/api\//, apiGetHandler, "GET");

const backgroundSync = new BackgroundSyncPlugin("Foo-Web_BG_Sync", {
    maxRetentionTime: 24 * 60
});
const apiPostAndPutHandler = new NetworkOnly({
    plugins: [
        backgroundSync
    ]
});
registerRoute(/\/api\//, apiPostAndPutHandler, "POST");
registerRoute(/\/api\//, apiPostAndPutHandler, "PUT");

cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// SPA-route
const spaHandler      = createHandlerBoundToURL("/index.html");
const navigationRoute = new NavigationRoute(spaHandler);
registerRoute(navigationRoute);
```
</details>

Making a call to the API while being _online_ looks in the logs like:

![grafik](https://user-images.githubusercontent.com/5755834/108610505-646d1c80-73d6-11eb-9ef8-fdcaa76324d3.png)

So the response gets cached.
Then going _offline_ and making the call again logs:

![grafik](https://user-images.githubusercontent.com/5755834/108610528-849cdb80-73d6-11eb-907e-4bfd5c6c5903.png)

workbox retrieves the response from the cache (as expected)

![grafik](https://user-images.githubusercontent.com/5755834/108610694-05100c00-73d8-11eb-81f8-d2cbdbd1b283.png)

but the uncaught error shouldn't happen.

In workbox v5 the uncaught error didn't occur.
I saw the release-notes and the part about precaching being a real route now, so I tried moving the registrations around, but nothing mitigated the uncaught error.

**Comment by jeffposnick** [comment]
What you're seeing is expected, especially when using the development bundles of Workbox that includes extra logging. Hopefully the next few lines of logging where Workbox says that it was unable to get the response from the network and is therefore falling back to the cache makes it clear what's going on.

It's that exception during the `fetch()` that triggers the fallback to the cache, and we explicitly re-throw it when we encounter it, so I don't think we want to change that logic: https://github.com/GoogleChrome/workbox/blob/80be8b16aba62fa927e5c3c19e55f8d16a78e808/packages/workbox-strategies/src/Strategy.ts#L193-L195

**Comment by gfoidl** [comment]
> we explicitly re-throw it when we encounter it

Thanks for clarification!

**Comment by huykon** [comment]
I am still facing with issue like this, could anyone can take a look to help me
![image](https://user-images.githubusercontent.com/9253798/205848599-672a732f-3598-422a-b2cc-6b15c1b97cab.png)
