### ISSUE TITLE
provide workbox version (v6) without npm modules like in the versions before (v4 and v5)

### ISSUE THREAD

**Issue by smaltzahn** [GoogleChrome/workbox#2762]
**Library Affected**:
Irrelevant.

**Browser & Platform**:
Irrelevant.

**Issue or Feature Request Description**:
In our current Project we don't use any bundlers. So we don't want to use npm modules. In previous Versions (v4 and v5), you provide more Versions to download. Is this possible for the current Versions to? (v6)

**Comment by jeffposnick** [comment]
The one thing that's changed recently is that we stopped posted a `.zip` archive of all the bundled modules along with each GitHub release.

You can obtain a local copy of the equivalent by running `workbox-cli`:

```
npx workbox-cli copyLibraries yourDirectory
```
