### ISSUE TITLE
[Workbox wizard] (rood directory question) Not allowing to manually set the path

### ISSUE THREAD

**Issue by ognjenjevremovic** [GoogleChrome/workbox#2764]
**Library Affected**:
*workbox-cli*

**Browser & Platform**:
*Node v15.3.0.*

**Issue or Feature Request Description**:
While working on #2758 and testing the changes locally I saw there is an issue with the workbox wizard when prompted with the question for _root directory of your web app_.
I tested this behavior both with the _v6_ working git branch as well as with the *@latest* stable (npm published) version of workbox-cli package *v6.1.0*; the bug is present on both versions.

When prompted for the root directory of web application, based on the current working directory the user is given *n+2* options:
 * *n* - number of directories in the project (current working directory, from which the `workbox wizard` command was executed),
 * *n+1* - separator (that shouldn't be a valid option to select from the list - which isn't the case and might be confusing for the user),
 * *n+2* - _Manually enter path_ option which always results in error - *The path you entered isn't a valid directory.*, as the user is never given an input to manually enter the path (as per question).

You can see the described behavior in the attachment below:
![workbox wizard (root dir question bug)](https://user-images.githubusercontent.com/14274816/109220404-2ba7bb80-77b9-11eb-8308-48749974651b.gif)

*Steps to reproduce the issue :*
 * Create a blank directory and navigating to it - you can do so by running `mkdir test-workbox-wizard && cd test-workbox-wizard`,
 * Create a few sub-directories inside your newly created directory (i.e. `test-workbox-wizard`) - by running `mkdir src && mkdir dist`,
 * Run the workbox wizard with a command (if installed globally as an npm package) - by running `workbox wizard`,
 * By choosing _Manually enter path_ option, wizard always results in an error.

**Comment by ognjenjevremovic** [comment]
I'll be able to address this issue on my own and provide a PR in the upcoming days, as I'm somewhat familiar with the `workbox-cli` package (after making my first PR today).

I'll be more than glad to provide further contributions to the `workbox` project.
Please, do feel free to assign this issue to me after performing the necessary triage 🙂 .

Thanks!

**Comment by jeffposnick** [comment]
Thank you!

**Comment by jeffposnick** [comment]
Thanks again! You changes are released as part of https://github.com/GoogleChrome/workbox/releases/tag/v6.1.2

**Comment by ognjenjevremovic** [comment]
Thank you so much for the attribution and the opportunity to contribute back to the amazing *workbox* project 🙂 .
