### ISSUE TITLE
Add createHandlerBoundToURL response to the cache if it is missing

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2765]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:
We use to code to precache navigation route "app-shell.html" as

```
const handler = createHandlerBoundToURL('/app-shell.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);
```

but if the item, for some reasons and with someone (buggy code, extension or by user), is deleted from the cache - we have not have offline mode in the future
requests will be made to the server but the result will not be stored in the cache

Please add an ability to put the response in the cache if it's absent in it in `createHandlerBoundToURL` code

the same problem occurs with `precacheAndRoute` when deleting the entire cache the application will work online but will never work offline

**Comment by jeffposnick** [comment]
One of the key principles for `workbox-precaching` is that the precache manifest associated with a given service worker uniquely determines the state of the cached responses that the service worker will use. Allowing updates to the cache "at runtime," without a corresponding change in a manifest, works against that principle.

We do understand that users could open up DevTools and accidentally delete cache entries (although this really happens more often when developers are testing things out), and for that reason, we do provide that `fallbackToNetwork` functionality in `workbox-precaching`, where returning a network response is considered preferable to just failing. But I would argue that when this happens, it's an error state, and attempting to "heal" the cache at runtime by re-populating it with an entry that doesn't necessarily correspond to the correct `revision` would be dangerous. It means that the possibly incorrectly versioned entry may never get updated in the future, papering over an error state with a persistent mismatch.

If you feel strongly that re-populating the cache at runtime is preferable, you should be able to accomplish it by [adding](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-precaching#.addPlugins) a custom [plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins) to `workbox-precaching` in the v6.x releases. The cleanest approach would probably be via a [`cachedResponseWillBeUsed `](https://developers.google.com/web/tools/workbox/guides/using-plugins) plugin, along the lines of this (untested) code:

```
const repopulatePrecachePlugin = {
  cachedResponseWillBeUsed: async ({cacheName, request, cachedResponse}) => {
    // If there's a cache hit, we're good.
    if (cachedResponse) {
      return cachedResponse;
    }
    
    // Otherwise, repopulate the precache.
    const cache = await caches.open(cacheName);
    const response = await fetch(request);

    // Optional: check the responses status as appropriate.
    if (!response.ok) {
      return null;
    }

    await cache.put(request, response.clone());
    return response;
  },
};
```

**Comment by budarin** [comment]
@jeffposnick 

Thanks for the explanation!

I'm not sure that repopulating the cache with entries from the manifest is wrong in case when all the entries have long term cache hash in their names 

how can we use the plugin with the code ?
```
const handler = createHandlerBoundToURL('/app-shell.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);
```
and with the code ?
```
precacheAndRoute(self.__WB_MANIFEST);
```

**Comment by jeffposnick** [comment]
Something like the following _should_ work (again, untested):

```js
import {addPlugins, createHandlerBoundToURL, precacheAndRoute} from 'workbox-precaching';
import {NavigationRoute, registerRoute} from 'workbox-routing';

// Use the plugin definition from above.
addPlugins([repopulatePrecachePlugin]);

precacheAndRoute(self.__WB_MANIFEST);

const handler = createHandlerBoundToURL('/app-shell.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);
```

**Comment by budarin** [comment]
@jeffposnick  Thanks!

**Comment by budarin** [comment]
My success story with Workbox !:)
https://vadim-budarin.medium.com/pwa-для-ssr-приложения-в-5-строк-на-workbox-6-dc89fc513361

thank you for your work!

**Comment by webmaxru** [comment]
Thanks for this article and for your kind words about my recent Workbox tech talk there, @budarin!

To make this content available for the global audience, let's also post an English version? (I can help with the translation)
