### ISSUE TITLE
@rollup/plugin-replace 'preventAssignment' warning

### ISSUE THREAD

**Issue by jameelmoses** [GoogleChrome/workbox#2769]
**Library Affected**:
workbox-build

**Browser & Platform**:
node

**Issue**:
Get a warning in my terminal every time `workbox-build` is run.

```@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.```

https://github.com/rollup/plugins/blob/6bee5980155df7b73cfbd9746556517c8d7f0ad7/packages/replace/test/snapshots/misc.js.md#no-explicit-setting-of-preventassignment

**Comment by jeffposnick** [comment]
Thanks for letting us know. We can address this in the next release.

**Comment by jeffposnick** [comment]
This is resolved in https://github.com/GoogleChrome/workbox/releases/tag/v6.1.2
