### ISSUE TITLE
Export all public types directly from workbox-window

### ISSUE THREAD

**Issue by StephanBijzitter** [GoogleChrome/workbox#2770]
As a follow-up on https://github.com/GoogleChrome/workbox/pull/2255

**Library Affected**:
*workbox-window.*

**Browser & Platform**:
*TypeScript*

**Issue or Feature Request Description**:
While a lot of the types can currently be imported, they do use the source filepaths, which could break at any point as SemVer does not (and should not) handle things like that.

So this, while currently valid, is prone to break:
```
import {WorkboxMessageEvent} from 'workbox-window/src/utils/WorkboxEvent';
```

The pull request above allows us to import types for `workbox-core` directly, but sadly this is not the case for `workbox-window`.

**Comment by jeffposnick** [comment]
Sounds reasonable!

Feel free to file a PR to accomplish this if you're comfortable doing so—otherwise, someone from the core team will pick it up.

**Comment by sahilcode17** [comment]
Hi I would like to contribute to this issue

**Comment by jeffposnick** [comment]
Thanks! I think the PR at https://github.com/GoogleChrome/workbox/pull/2919 already addresses it,  though.

**Comment by jeffposnick** [comment]
This is now live in https://github.com/GoogleChrome/workbox/releases/tag/v6.3.0
