### ISSUE TITLE
Undocumented v6 breaking change: PrecacheController.install/active

### ISSUE THREAD

**Issue by slorber** [GoogleChrome/workbox#2774]
Hi,

Not 100% sure but it seems like in the code and TS typedefs, the PrecacheController install/activate methods now take the event as param, while it wasn't the case before.

Not passing the event lead to console errors after an upgrade:

![image](https://user-images.githubusercontent.com/749374/110649263-baed9f80-81b9-11eb-9038-754ad9da7942.png)

```
Uncaught TypeError: Cannot read property 'waitUntil' of undefined
``` 

FYI the doc seems wrong to me and this is also not mentioned on the v5-v6 breaking changes, and might be useful to add/fix ;)

https://developers.google.com/web/tools/workbox/modules/workbox-precaching

**Comment by jeffposnick** [comment]
Thank you for pointing this out—yes, `PrecacheController` does require an `ExtendableEvent` to be passed in as a parameter to both its `install()` and `activate()` methods in v6.

I'll get the JSDoc and other guidance updated to make it clear that this changed, and is a breaking change.

**Comment by slorber** [comment]
thanks :)
