### ISSUE TITLE
New offline check of Chrome always logs an error

### ISSUE THREAD

**Issue by joker-777** [GoogleChrome/workbox#2776]
**Library Affected**:
workbox-routing, workbox-strategies, workbox-precaching

**Browser & Platform**:
Chrome Version 89.0.4389.82 (Official Build) (64-bit) and Arch Linux

**Issue or Feature Request Description**:
It looks like [Chrome now always does an offline check](https://developer.chrome.com/blog/improved-pwa-offline-detection/) with the `start_url` from `manifest.json` when loading a page. This will then always log an error

```
Network request for '/' threw an error. TypeError: Failed to fetch
```
and
```
Uncaught (in promise) TypeError: Failed to fetch
```
or when the offline case isn't cought
```
WorkboxError.js:31 Uncaught (in promise) no-response: The strategy could not generate a response for 'https://your.domain.com/'. The underlying error is TypeError: Failed to fetch.
```

Here is how my service worker look like

```js
import {setCatchHandler, setDefaultHandler} from "workbox-routing"
import {NetworkOnly} from "workbox-strategies"
import {precacheAndRoute, matchPrecache} from "workbox-precaching"

precacheAndRoute(self.__WB_MANIFEST)

setCatchHandler(async ({event, url}) => {
  // Return the precached offline page if a document is being requested
    return matchPrecache("/offline.html")
  }
  return Response.error()
});


setDefaultHandler(new NetworkOnly())

```

**Comment by jeffposnick** [comment]
Please see the discussion in #2749

**Comment by joker-777** [comment]
Thanks for pointing to it. I wasn't able to find this issue when I did my investigation for this error, unfortunately.
