### ISSUE TITLE
@jeffposnick I face the same issue as faced by  @qqilihq , in my case i am call periodically workbox update method to check for update, but in my case new service get activated but controlling event never gets fired.

### ISSUE THREAD

**Issue by hannandesai** [GoogleChrome/workbox#2779]
@jeffposnick I face the same issue as faced by  @qqilihq , in my case i am calling periodically workbox update method to check for update, but in my case new service get activated but controlling event never gets fired.

Is there somethinng i am missing please guide me.

Thanks in Advance!

_Originally posted by @hannandesai in https://github.com/GoogleChrome/workbox/issues/2070#issuecomment-798845662_

**Comment by jeffposnick** [comment]
There isn't enough context here to create a new issue. I'm going to reply in the old issue thread and we can reopen that if needed.
