### ISSUE TITLE
Firefox: Refreshing Page or Loading New Page Causes Javascript Function to Return Undefined

### ISSUE THREAD

**Issue by PostAlmostAnything** [GoogleChrome/workbox#2780]
The following is a snippet of code I just wrote to select a random affiliate ad from an array containing URL pairs for landing pages and banner ad images. It works fine in Chromium browsers, but  in Firefox it only works when the page is first loaded unless I unregister my Workbox service worker. If I fail to do that the results return as "undefined" and the log entries are not written in the console. How I do I fix this?

`var leaderboards = [['link', 'image'],
        ['link', 'image'],
        ['link', 'image'],
        ['link', 'image'],
        ['link', 'image'],
        ['link', 'image']
    ];
    var randAd = leaderboards[Math.floor(Math.random() * leaderboards.length - 1)];
    console.log('randAd= ' + randAd);
    var splitLeaderboards = randAd.toString().split(',');
    console.log('splitLeaderboards= ' + splitLeaderboards);
    var randLink = splitLeaderboards[0];
    console.log('randLink= ' + randLink);
    var randImage = splitLeaderboards[1];
    console.log('randImage= ' + randImage);`

**Comment by jeffposnick** [comment]
Hello! Unfortunately, I'm having a hard time understanding how the code snippet you provided relates to Workbox or service workers.

If you have a live reproduction of a site that reproduces the issue, then could you share the URL? Without that, just that code snippet isn't enough to go on, unfortuantely.

**Comment by PostAlmostAnything** [comment]
It has to do with Workbox because like I said I need to unregister the service worker for the script to work after the first page is loaded. That service worker is a Workbox service worker.

**Comment by jeffposnick** [comment]
I understand that you need to unregister the service worker, but unfortunately that doesn't provide enough of a clue to understand what's going on.

As mentioned, the best way to get help for this would be to provide a URL at which a live version of your web app can be accessed. I'll take a look at what's going on. If you can't share the URL publicly, you can send a DM to https://twitter.com/jeffposnick

**Comment by PostAlmostAnything** [comment]
I would love to post a link, but due to the content at that link I fear that GitHub will either suspend my account or limit my posting abilities if I post it.

**Comment by dryabov** [comment]
1. Why do you use `leaderboards[Math.floor(Math.random() * leaderboards.length - 1)]`? There should be no `-1`, as `Math.random` generates real numbers between 0 (including) and 1 (excluding), otherwise you can try to access `leaderboards[-1]`.
2. The next point is `randAd.toString().split(',')`, where `randAd` is already an array of 2 elements, and such a code looks weird.

**Comment by PostAlmostAnything** [comment]
> 1. Why do you use `leaderboards[Math.floor(Math.random() * leaderboards.length - 1)]`? There should be no `-1`, as `Math.random` generates real numbers between 0 (including) and 1 (excluding), otherwise you can try to access `leaderboards[-1]`.
> 2. The next point is `randAd.toString().split(',')`, where `randAd` is already an array of 2 elements, and such a code looks weird.

I used "- 1" because of an example on StackOverflow that said that was how to do it in cases like this one. I used string split because I don't work with javascript much and was not sure how to access the second column by itself, so I took the whole row, converted it to a string, and split it at the comma.

**Comment by jeffposnick** [comment]
I don't believe that this issue describes anything actionable that we can address, so I'm going to close it. If you are still having problems and can provide more details about reproducing, please let us know and we can revisit.
