### ISSUE TITLE
What is the maximum number of maxEntries?

### ISSUE THREAD

**Issue by niwatoliver** [GoogleChrome/workbox#2781]
Workbox has a variety of features that have been very helpful.

However, there is a behavior that is bothering me. It is about the value of `maxEntries` in `ExpirationPlugin`.
The maximum value here is 50, as described in https://developers.google.com/web/tools/workbox/guides/storage-quota#what_configuration_options_are_supported I thought so.
In fact, I have confirmed that the number of entries stored by Workbox in `workbox-expiration` and `timestamp` of IndexdDB is 50.

However, in some recipes, such as this one https://developers.google.com/web/tools/workbox/guides/common-recipes  the value of `maxEntries` is 60. Is this a problem?

Also, if this is not a problem, if I want to cache more than 100 images in a real use case, is it okay if I specify a value of `maxEntries` greater than 100?

**Comment by jeffposnick** [comment]
There is no hardcoded limit on the value of `maxEntries`. Workbox should support values over than 100 without a problem. At some point, the algorithm used to find and expire old entries might start slowing down if the values get very, very large—we haven't really tuned it specifically for performance. Additionally, browsers might impose some limits on storage that are separate from Workbox, and which Workbox doesn't have control over.

**Comment by niwatoliver** [comment]
thanks.
