### ISSUE TITLE
workbox-webpack-plugin generates a different sourcemap in every build run.

### ISSUE THREAD

**Issue by weiwei-lin** [GoogleChrome/workbox#2784]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The generated sourcemap is unstable (changes on every build).
This breaks our CI.

Reproduce:
webpack.config.ts
```
const config: webpack.Configuration = {
  ...
  plugins: [
     ...,
    new Workbox.GenerateSW({
      clientsClaim: true,
      navigateFallback: '/ui/index.html',
      sourcemap: true,
    }),
  ],
};
```
run the build script.
service-worker.js.map
```
{
  "version":3,
  "file":"service-worker.js",
  "sources": [
    "../../../../../../../private/var/folders/3w/n5rh6_7d7gzgzb0lydk2jsmr00d7lq/T/8deb86f7178c88825eafab226c7b7981/service-worker.js"
  ],
  ...
}
```
run the build script again.
service-worker.js.map
```
{
  "version":3,
  "file":"service-worker.js",
  "sources": [
    "../../../../../../../private/var/folders/3w/n5rh6_7d7gzgzb0lydk2jsmr00d7lq/T/0264c1085ff3257ccdf94e25d5443242/service-worker.js"
  ],
  ...
}
```
Notice that the hash has changed.

**Comment by jeffposnick** [comment]
Hmmm... the relevant code is https://github.com/GoogleChrome/workbox/blob/27080cccfbc360b121083bb47e20429997051a6f/packages/workbox-build/src/lib/bundle.js#L28-L33

(`workbox-build` and `workbox-webpack-plugin` both use this module.)

I'll take a look to see whether that path can be cleaned up to something more meaningful/stable, as that obviously doesn't seem like a valid URL to include as one of the `sources` in general.

**Comment by jeffposnick** [comment]
After thinking about this a bit more, I don't know that it's something we should change.

`GenerateSW` needs to create an "unbundled" service worker file somewhere on disk. This file's path is what ends up being included in the sourcemap. I don't think that this file should be written anywhere prominent, like in the current directory, as including it there would lead to more confusion.

One alternative would be to hardcode a "fake" relative path, like `'unbundled-service-worker.js'`, for this unbundled code. This would lead to consistent output after each build, but at the expense of including the path to a file that doesn't exist at all on disk, which could in itself be confusing and "break" the sourcemap.

Another alternative would be to always write the unbundled code to a stable filename, like `path.join(os.tmpdir(), 'workbox', 'unbundled-service-worker.js')`. This would lead to sourcemaps that wouldn't vary from build to build. Unfortuantely, this would also mean that if you had multiple instances of `GenerateSW` running concurrently (maybe you have a multi-compilation build), you could overwrite one instance's unbundled file with another's. I don't think this race condition is likely, but I also don't want to introduce the possibility.

For those reasons, I think leaving things as-is is the best approach. I would encourage you to exclude the sourcemap file from the list of resources you check after each CI build. Alternatively, if you can't do that, you should consider post-processing the sourcemap file to hardcode a stable path, like:

```
const path = require('path');
const fs = require('fs');

const sourcemapFile = 'path/to/service-worker.js.map';
const sourcemapJSON = require(sourcemapFile);
sourcemapJSON.sources = sourcemapJSON.sources.map((source) => path.basename(source));
fs.writeFileSync(sourcemapFile, JSON.stringify(sourcemapJSON));
```
