### ISSUE TITLE
request.formdata will fail if request is issued by a fetch in page

### ISSUE THREAD

**Issue by planeth44** [GoogleChrome/workbox#2789]
**Library Affected**:
background-sync

**Browser & Platform**:
 Google Chrome for Linux

I have a page with a form. This form is submitted via a fetch() in the page. 
This fetch is captured by the SW and if the page is offline the catch will trigger, and the request will be queued.
All is well until now.
But, if I want to use ```request.clone().formData()```, while offline, this will fail.

Now, if the form is submitted directly (without using a fetch) ```request.clone().formData()``` will work.

```javascript
self.addEventListener('fetch', (event) => {
  // Clone the request to ensure it's safe to read when adding to the Queue.
  const promiseChain = fetch(event.request.clone()).catch(async(err) => {
    const formdata = await event.request.clone().formData()
     // will fail if the fetch is first issued from a page fetch
     // the request will fail with a 'Fail to fetch' error
    console.log(...formdata)
    return queue.pushRequest({request: event.request})
  });

  event.waitUntil(promiseChain);
});
```
The only difference is that in the first case (form submitted through fetch), the request.mode is "cors", and in the second case (form submitted directly) the request.mode is "navigate", which makes sense.

Is there a way to get the content of formData when request.mode is "cors" ?

Thank you for any insight. I know this happens _before_ the call to ```pushRequest```

**Comment by jeffposnick** [comment]
Hello @planeth44!

Can you clarify a few things to help us investigate further?

First, and you seeing this in all web browsers, or just one of them? I know that Safari has [some issues](https://bugs.webkit.org/show_bug.cgi?id=212858) with `FormData`, though I haven't heard of a known bug that specific matches what you're describing here.

Second, are there any exceptions thrown when you call `await event.request.clone().formData()`? If you wrap it in a `try`/`catch` and `console.log()` the exception inside the `catch` handler, does that point to a specific error?

And finally, is this issue something that's directly related to `workbox-background-sync`? You say that it happens in your code before you call `queue.pushRequest()`, so I'm wondering if it's reproducible without any Workbox involvement at all. (We can still help debug even if it is.)

**Comment by planeth44** [comment]
Hello @jeffposnick 
For now, I've tried with both Chrome and Firefox on Linux(Ubuntu 20) 
I know about Safari issues on formData, but I don't think this is the case here.

I've re-run the code below: 

```javascript
self.addEventListener('fetch', async (event) => {
 // Clone the request to ensure it's safe to read when adding to the Queue.
 const req1 = await event.request.clone()
 const req2 = await event.request.clone()

 const promiseChain = fetch(req1).catch(async(err) => {

  try{
   const fd = await req2.formData()
   console.log(...formdata)
  }
  catch (err){
    console.log(err)
  }

   // return queueObjects.mixedBinData.pushRequest({request: event.request})
 });
 event.waitUntil(promiseChain);
});
```
As you suspect the issue is not related to ```workbox-background-sync```. The above code runs without any call to workbox

The catch block in Chrome returns: ```TypeError: Failed to fetch``` and interestingly, in Firefox the catch block returns ```TypeError: Could not parse content as FormData.```

**Comment by jeffposnick** [comment]
Thanks, @planeth44. And one more thing: can you share the code that runs in your web page which handles the form submission via `fetch()`? Ideally both the HTML for the form and the JavaScript for the submission process, if possible.

It sounds like something about the process of serializing the form into an HTTP request might be causing the issue you're seeing.

**Comment by planeth44** [comment]
@jeffposnick 
see the HTML and the js below. 
Just to be clear: if I submit the form while online, the code runs as intended. It only failed if I try to submit when offline. 

the HTML page is just a form:
```html
<html><head>
  <meta charset="UTF-8">
  <script src="./libs/config.js"> </script>
    <script type="module" src="./pwa-components/input-files-multiple/script.js"></script>
  <title> Object Form </title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body >
<form method="POST" enctype="multipart/form-data" id="flPwaComponentsForm" data-flpwa-components-form="" action="/api/multiFiles">
  <fieldset>
    <div class="flpwa-control">
      <label>
        textOnlyWithValue
        <input type="text" name="textOnlyWithValue" value="textOnlyWithValue">
      </label>
    </div>
    <div class="flpwa-control">
      <label>
        textOnlyWithoutValue
        <input type="text" name="textOnlyWithoutValue">
      </label>
    </div>
   
    <div class="flpwa-control">
      <label>
        <input type="radio" name="radioCheckedAndNotChecked" value="value4">
        radioCheckedAndNotChecked4
      </label>
    </div>
  </fieldset>

  <fieldset>
    <div class="flpwa-control">
      <label>slectSimple
        <select name="slectSimple">
          <option></option>
          <option>value1</option>
          <option selected="">value2</option>
          <option>value3</option>
        </select>
      </label>
    </div>
  </fieldset>
  <fieldset>
    <div class="flpwa-multiple-files-component">
      <div data-flpwa-input-multiple-files="">
        <div data-img-preview=""> </div>
        <div>
          <label class="flpwa-label-multiple-files">Choose photos
          <input class="flpwa-input-multiple-files" type="file" name="photoFiles[]" multiple="" accept="image/*">
          </label>
        </div>
      </div>
    </div>
  </fieldset>

  <div data-flpwa-submit-area="">
    <button type="reset" title="Nah…">Cancel</button>
    <button type="submit" title="send form">Done</button>
  </div>
</form>
  </main>

  <script type="module" src="./js/app.js"> </script>
 
</body></html>
```

//app.js
```javascript
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('sw.js')
      .then((reg) => {
        console.log('Registration succeeded.');
      }).catch((error) => {
        console.log('Registration failed with ' + error);
      });
  });
}
```
//pwa-components/input-files-multiple/script.js
```javascript
document.addEventListener('submit', handleSubmit)
async function handleSubmit(e)
{
    e.preventDefault()
    const formDataToSubmit = buildFormData(e)
    const url              = e.target.action

    try {
        await postFormdata(url, formDataToSubmit)
    }catch(err) {
      console.error(err)
      throw new Error(err) // rethrowing to be caught at higher level
    }
}
async function postFormdata(url, formData)
{

  const postResponse = await fetch(url, {
      method: 'post',
      body: formData
  })

  if (postResponse.status < 400) { // redirecting to a result page
      window.location.href = postResponse.url
  } 
  else {
    handleResponse(postResponse)
  }
}

async function buildFormData(e)
{
   // we need to rebuild formdata to support adding multiple files with only one file input
    const formdata       = new FormData(e.target)
    const newformdata    = new FormData()
    const inputfilesname = _d.qs('input[type="file"][multiple]').name

    for (var [name, value] of formdata.entries()) {
        if (name != inputfilesname) {
            newformdata.append(name, value)
        }
    }

    pendingFiles.forEach(entry => {
        newformdata.append(entry[0], entry[1], entry[1].name)
    })

    return newformdata
}

```

**Comment by planeth44** [comment]
I think I solved this : 
```javascript
async function handleSubmit(e)
{
    e.preventDefault()
    const formDataToSubmit = await buildFormData(e)
   // more code
}
```

**Comment by sakurawald** [comment]
> I think I solved this :
> 
> ```js
> async function handleSubmit(e)
> {
>     e.preventDefault()
>     const formDataToSubmit = await buildFormData(e)
>    // more code
> }
> ```

This works.
