### ISSUE TITLE
Improve the UX/DX of the demos

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#279]
**Library Affected**:
all

There are a number of demos that pull in the minified versions of libraries via `importScripts()`. We should do a pass through the existing demos and switch them all over to use the unminified libraries. Although the source maps should theoretically paper over the difference, we might as well make it as easy as possible to figure out what's going on in the demo.

**Comment by gauntface** [comment]
Would be good to just do a sweep of the demos:

- [ ] Add some basic styling to demos (presumably to match a workbox microsite.
- [ ] Focus on how to demonstrate what the libraries do and how to demonstrate that to developers
- [ ] Make it easy to view the relevant code for the demo, in the demo
- [ ] Host the demos publicly.
- [ ] Ensure each demo inherits from a base template for index page
- [ ] Ensure each demo uses unminified code.

**Comment by jeffposnick** [comment]
I think https://github.com/GoogleChrome/workbox-microsite/issues/60 and other work to enhance https://workboxjs.org/examples/ takes priority over this.
