### ISSUE TITLE
The parameter 'options.event' passed into 'workbox-strategies.StrategyHandler.constructor()' must be an instance of class ExtendableEvent.

### ISSUE THREAD

**Issue by boraturant** [GoogleChrome/workbox#2791]
**Library Affected**:
*workbox-strategies, workbox-routing.*

**Browser & Platform**:
*Google Chrome*

I am using the advanced Router.register/handle pattern as documented in https://developers.google.com/web/tools/workbox/modules/workbox-routing#advanced_usage

Registering a ne route with router object.

```
const router = new Router();
router.registerRoute(
	new Route(
		// Check to see if the request is a navigation to a new page
		({ request }) => request.mode === 'navigate',
		// Use a Network First caching strategy
		new NetworkFirst({
			// Put all cached files in a cache named 'pages'
			cacheName: 'pages'
		})
	)
);
```

Then handing it in fetch:

```
self.addEventListener('fetch', (event) => {
	const responsePromise = router.handleRequest(event);
	if (responsePromise) 
		event.respondWith(responsePromise);
}
```

The fetch event throws the below error:

Uncaught (in promise) incorrect-class: The parameter 'options.event' passed into 'workbox-strategies.StrategyHandler.constructor()' must be an instance of class ExtendableEvent.
    at Object.isInstance (http://localhost:8080/service-worker.js:1780:15)
    at new StrategyHandler (http://localhost:8080/service-worker.js:8117:83)
    at NetworkFirst.handleAll (http://localhost:8080/service-worker.js:7916:25)
    at NetworkFirst.handle (http://localhost:8080/service-worker.js:7878:37)
    at Router.handleRequest (http://localhost:8080/service-worker.js:6466:39)
    at http://localhost:8080/service-worker.js:8981:32

**Comment by jeffposnick** [comment]
Apologies; the documentation needs to be updated to reflect the changes in the latest Workbox releases.

We'll update the recipe to read:

```js
const router = new Router();
// ...

self.addEventListener('fetch', (event) => {
  const {request} = event;
  const responsePromise = router.handleRequest({request, event});
  if (responsePromise) {
    event.respondWith(responsePromise);
  }
});
```

**Comment by boraturant** [comment]
Thanks!
