### ISSUE TITLE
Uncaught (in promise) no-response: no-response :: [{"url":"http://127.0.0.1:8080/index.html","error":{}}]

### ISSUE THREAD

**Issue by ChildishGiant** [GoogleChrome/workbox#2792]
```
sw.js:formatted:16 Uncaught (in promise) no-response: no-response :: [{"url":"http://127.0.0.1:8080/index.html","error":{}}]
    at y._handle (http://127.0.0.1:8080/sw.js:1:5815)
    at async y._getResponse (http://127.0.0.1:8080/sw.js:1:5078)
```

<details>
<summary>Here is my sw.js</summary>

```js
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies'
import { registerRoute, setDefaultHandler, setCatchHandler } from 'workbox-routing'

// Stale while revalidate for js and css
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate()
)

// Network first for HTML
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst()
)

// Cache first for fonts and logos
registerRoute(
  ({ request }) => request.destination === 'font' || request.destination === 'image',
  new CacheFirst()
)

setDefaultHandler(new CacheFirst())

// This "catch" handler is triggered when any of the other routes fail to
// generate a response.
setCatchHandler(({ event }) => {
  console.log(event)
})
```
</details>

I have a catch handler and default handler but neither seem to be triggered.

**Comment by jeffposnick** [comment]
Hello @ChildishGiant!

Which version of Workbox are you using? This sounds somewhat similar to (but not exactly the same as) what was reported in #2749. If you're using Workbox v6, could you update to Workbox v6.1.2 and confirm that you're still seeing the same behavior?

**Comment by ChildishGiant** [comment]
I'm using `"workbox-recipes": "^6.1.2"` yea.

**Comment by jeffposnick** [comment]
Hello!

You mention `workbox-recipes` v6.1.2, but from your service worker code, I see that you're using `workbox-strategies` and `workbox-routing`. Are those also v6.1.2?

If you have your code deployed somewhere at a public URL, we can take a look there and potentially debug things quicker.

**Comment by ChildishGiant** [comment]
I installed through `workbox-recipes`, just checked the package lock and everything's 6.1.2. I've been having some other build issues and now cannot reproduce this. I'll close this issue and reopen if I run into this again
