### ISSUE TITLE
Incorrect format of "ignoreURLParametersMatching" values generated via `workbox wizard` cli command

### ISSUE THREAD

**Issue by anuragl94** [GoogleChrome/workbox#2796]
**Library Affected**:
workbox-cli

**Browser & Platform**:
Windows

**Issue or Feature Request Description**:
Running `workbox wizard` resulted in the following config file:
```
module.exports = {
  "globDirectory": "dist/",
  "globPatterns": [
    "**/*.{js,webmanifest,html,png,css}"
  ],
  "swDest": "dist/sw.js",
  "ignoreURLParametersMatching": [
    "/^utm_/",
    "/^fbclid$/"
  ]
};
```

Running `workbox generateSW` on this config file results in this error:
```
[1] "ignoreURLParametersMatching[0]" must be of type object
```

From the docs, it is clear that `ignoreURLParametersMatching` expects an array of Regular Expressions, not strings.
The wizard script should be fixed to reflect this.

**Comment by JSebastianOspina** [comment]
Same here

**Comment by jeffposnick** [comment]
Thanks for reporting this; we have a PR out to fix it, but in the meantime, feel free to manually edit the config file to remove the `"` around the RegExps.
