### ISSUE TITLE
Release ES module dev/prod bundles of all packages

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2797]
Right now, we only produce ES module dev/prod bundles for the `workbox-window` package, since using ES imports has, until recently, only been viable from the `window` context of a web page.

At some point in the near future, [ES imports inside of the `ServiceWorkerGlobalScope`](https://chromestatus.com/feature/4609574738853888) may be supported in Chrome/Edge.

Sooner than that, the [Deno Deploy](https://deno.com/deploy/docs/hello-world) runtime environment (and potentially Cloudflare Workers, but I've explored that less) could theoretically use bits of Workbox, but only if they could be consumed as ES modules.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
