### ISSUE TITLE
Make range requests available in GenerateSW webpack plugin

### ISSUE THREAD

**Issue by shadowwalker** [GoogleChrome/workbox#2809]
Can we make range requests plugins available in GenerateSW config here?

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry

**Comment by jeffposnick** [comment]
Hello @shadowwalker!

Yes, I think we should be able to include support for it in `GenerateSW` in a future release.

**Comment by cawa-93** [comment]
I'm looking forward to it! And not just for the webpack.

**Comment by jeffposnick** [comment]
The feature is now deployed in a pre-release of Workbox v6.2.0: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0
