### ISSUE TITLE
worbox-window: 'externalwaiting' missing in 'keyof WorkboxEventMap' in typescipt definitions

### ISSUE THREAD

**Issue by radulle** [GoogleChrome/workbox#2810]
**Library Affected**:
*workbox-window*

**Issue or Feature Request Description**:
'externalwaiting' missing in 'keyof WorkboxEventMap' in typescipt definitions

![image](https://user-images.githubusercontent.com/46776951/114375126-a7e93900-9b84-11eb-98d9-d7910d57dc1f.png)

**Comment by jeffposnick** [comment]
Hello @radulle!

Assuming you're using Workbox v6, this is to be expected, as the "external" flavors of `workbox-window` events [were removed](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v5#removal_of_external_events_in_favor_of_an_isexternal_property).

**Comment by radulle** [comment]
@jeffposnick than [advanced recepies](https://developers.google.com/web/tools/workbox/guides/advanced-recipes) on dev.google are missleading. Also "Offer a page reload for users" when accepted in one tab will not work properly in other tabs (they will not get reloaded).

**Comment by jeffposnick** [comment]
Apologies; there's a PR out to address that (https://github.com/google/WebFundamentals/pull/9316), but some of the folks responsible for reviewing it have been out of the office. It'll be taken care of in the near future!
