### ISSUE TITLE
Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by yinxiL** [GoogleChrome/workbox#2815]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected 1 vulnerable regex(es) from your repository.

1: `['|"]workbox:((?:[^:'"]*|:)*)['|"]` in workbox/test/all/node/test-package.js

Please try the following:

	var pattern = "['|\"]workbox:((?:[^:'\"]*|:)*)['|\"]";
	var input = "\"workbox:\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by jeffposnick** [comment]
This is a test-only harness script that isn't passed user-defined input. I don't believe it needs to be addressed.
