### ISSUE TITLE
"Generate offline fallback SW" mode in build tools

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2816]
Many developers would like to use a service worker for an offline fallback page, e.g. to [meet the minimal offline support criteria](https://developer.chrome.com/blog/improved-pwa-offline-detection/), without integrating Workbox's build tools into their site deployment, which is otherwise necessary in order to use precaching-based solutions.

We can automate this process in Workbox's build tools via a new `generateOfflineFallback` mode, along the lines of:

```
npx workbox-cli generateOfflineFallback path/to/local/offline.html
```

(or run via the equivalent `workbox-build` or `workbox-webpack-plugin` interface).

The input could be a local HTML file, and the output could be a service worker that combined `workbox-strategies`, `workbox-routing`, and `workbox-navigation-preload` to cache and serve the HTML file as well as any subresources it depends on (using [`jsdom`](https://github.com/jsdom/jsdom) or a similar library to determine this as a best-effort).

Instead of using a precache manifest, which would require re-running this `generateOfflineFallback` command each time a given site is rebuilt, it would use best-effort versioning by including a time stamp as part of the generated service worker. It would be the responsibility of each site owner to re-run the command if they want to ensure that changes to their offline HTML or subresources get picked up by existing clients.

This new mode would be aimed at developers who do not want to integrate Workbox's build tools into their site's build process, which is required when using precaching. It would offer a one-off service worker generation mode

### Alternatives

Developers who want to use precaching and are using the existing `generateSW` mode can already do all this with a configuration along the lines of:

```js
generateSW({
  // ... other generateSW config options...
  navigationPreload: true,
  runtimeCaching: [{
    urlPattern: ({request}) => request.mode === 'navigate',
    handler: 'NetworkOnly',
    options: {
      precacheFallback: {
        // This URL needs to be included in your precache manifest.
        fallbackURL: '/offline.html',
      },
    },
  }],
});
```

CC: @andreban

**Comment by tomayac** [comment]
Especially like the idea that this would take care of sub resources. 👍

**Comment by fteotini** [comment]
I tried with the example you provided but I cannot manage to make it work. It seems that index.html gets loaded regardless of this.
The only requests tha I can see passing through the urlPattern func are the one made by the html to load external fonts etc

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
