### ISSUE TITLE
Refactor Plugin classes

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#282]
**Library Affected**:
many

For many of the packages (e.g., `sw-cache-expiration`), the `Plugin` class that exposes `RequestWrapper` lifecycle callbacks (e.g. `cacheDidUpdate`) is currently the same place that implements the core functionality, which is reusable outside of the `RequestWrapper` context.

It would be cleaner to break that up so that there's a base class which implements the core functionality, and then a subclass that exposes the addition lifecycle callbacks.

Additionally, it would be better to use a more descriptive name than `Plugin` for each of those classes, since our assertion libraries will log the class name if there are bad parameters passed to the constructor. So `Plugin` inside of the `sw-cache-expiration` project would be better named `CacheExpirationPlugin`.

**Comment by gauntface** [comment]
I think I get what you are saying and big plus one for this.

Seperating the plugin callbacks from methods should make it easier to use as standalone module.

**Comment by jeffposnick** [comment]
Modules to refactor:
- [ ] `sw-background-sync-queue`
- [ ] `sw-broad-cache-update`
- [ ] `sw-cache-expiration`
- [ ] `sw-cacheable-response`

**Comment by jeffposnick** [comment]
Three of the items from https://github.com/GoogleChrome/sw-helpers/issues/282#issuecomment-285520914 are complete, with `sw-background-sync-queue` not yet updated.

@prateekbh, are you okay with me assigning this issue to you? You can follow the model used in the other PRs. I'd do it myself, but I know there's a bit of an ongoing discussion about the exported interface and namespace for the `sw-background-sync-queue` module, and that should probably be addressed prior to/at the same time as the plugin refactoring is performed.

**Comment by prateekbh** [comment]
> For many of the packages (e.g., sw-cache-expiration), the Plugin class that exposes RequestWrapper lifecycle callbacks (e.g. cacheDidUpdate) is currently the same place that implements the core functionality

@jeffposnick  in background-sync-queue all the core functionality is already abstracted behind a proxy class, which just calls the core methods. This was done so that this lib can be used with or without `sw-helpers`.

https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-background-sync-queue/src/lib/background-sync-queue.js#L119-L121

If I read your description right, this shouldn't be a problem

**Comment by jeffposnick** [comment]
We discussed this at our last meeting and I think @prateekbh is on board with following the model we're using with, e.g., [`sw-cacheable-response`](https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-cacheable-response/src/lib), where there's a separate `CacheableResponsePlugin` class that extends the base `CacheableResponse` and just exposes an additional method with a slightly different signature, matching the lifecycle callbacks that `RequestWrapper` expects.

That way, the base class can use an interface that doesn't have to adhere to what `RequestWrapper` expects and which might be more natural for developers who use it outside the context of `RequestWrapper`.

**Comment by jeffposnick** [comment]
This is all done.
