### ISSUE TITLE
Video on iOS Safari not playing

### ISSUE THREAD

**Issue by artola** [GoogleChrome/workbox#2821]
**Library Affected**:
*workbox v6.1.5*

**Browser & Platform**:
*iOS Safari (only)*

**Issue or Feature Request Description**:
This is my config and the video is working in all browsers, except iOS Safari (without SW the video plays well, or just excluding with `exclude: [/\.mp4$/]`.

```
        new WorkboxPlugin.GenerateSW({
          swDest: 'sw.js',
          cleanupOutdatedCaches: true,
          inlineWorkboxRuntime: true,
          clientsClaim: true,
          skipWaiting: true,
        }),
```

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
Hello @artola!

There's guidance at https://developers.google.com/web/tools/workbox/guides/advanced-recipes#cached-av for playing back cached media. It's a little more involved than what you could accomplish with your basic `GenerateSW` config that uses the default precaching behavior.

Switching to using the `InjectManifest` plugin along with a [handwritten `swSrc`](https://developers.google.com/web/tools/workbox/guides/get-started#using_workbox), and adding in the code specific to your media playback route would be your best best.

Let us know if that doesn't put you in the right direction.
