### ISSUE TITLE
OfflineFallback Recipe is not working

### ISSUE THREAD

**Issue by NicoSerranoP** [GoogleChrome/workbox#2824]
**Library Affected**:
*workbox*

**Browser & Platform**:
*Chrome, Firefox, Edge*

**Issue or Feature Request Description**:

The Offline Fallback recipe described here: [https://developers.google.com/web/tools/workbox/modules/workbox-recipes#offline_fallback](https://developers.google.com/web/tools/workbox/modules/workbox-recipes#offline_fallback) is not working. I am writing a simple service worker using some of the amazing tools in Workbox but the ```workbox.recipes.offlineFallback``` is not working. When I block a specific network request (ex: an image) or activate the offline mode, I am still getting broken images and network errors. My code looks like this:

``` 
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-sw.js');

self.addEventListener('install', async function(event) {
  caches.delete('innomaps-pwa-precache-cache-v1').then(() => {
    console.log('A new service worker has been received');
    self.skipWaiting();
  });
});

workbox.core.setCacheNameDetails({
  prefix: 'innomaps-pwa',
  suffix: 'v1',
  precache: 'precache-cache',
  runtime: 'runtime-cache'
});

workbox.recipes.offlineFallback({
  pageFallback: '/offline',
  imageFallback: 'assets/img/InnomapsWhite.png'
});
```

I looked at the ```workbox.recipes.offlineFallback``` and I believe it has something to do with the ```workbox.routing.setCatchHandler``` function. When I tried to used, nothing happened (not even in offline mode). My testing code looked like:

```
workbox.routing.setCatchHandler( async ({event}) => {
  console.log('You should be able to see this message in the console if setCatchHandler is called');
  return Response.error();
});
```

I already posted a question here [https://stackoverflow.com/questions/66646514/offlinefallback-from-workbox-is-not-working-when-going-offline](https://stackoverflow.com/questions/66646514/offlinefallback-from-workbox-is-not-working-when-going-offline) but haven't receive any answers.

Thank you very much for your time! :)

*The first time I load my page*
![image](https://user-images.githubusercontent.com/38594836/115817567-b6bfbf00-a3c0-11eb-98fc-df75f6d03a8e.png)

*After activating the offline mode*
![image](https://user-images.githubusercontent.com/38594836/115817646-d951d800-a3c0-11eb-80c1-a0821063b2ec.png)

**Comment by jeffposnick** [comment]
You're correct, in that the current documentation will steer folks towards a service worker that sets up the global `catch` handler, but that handler never gets used unless there's a matching route that intercepts the (potentially failing) request.

Using `setDefaultHandler()` to establish a network-only route that's used by default should be enough to get the code working, without fundamentally changing anything about the behavior while online (since network-only is basically the same as the default behavior when there isn't a service worker.)

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-sw.js');

workbox.routing.setDefaultHandler(
  new workbox.strategies.NetworkOnly()
);

// Replace with your URLs.
workbox.recipes.offlineFallback({
  pageFallback: '/offline.html',
  imageFallback: '/offline.png'
});
```

Apologies for the frustration that this might have caused while debugging. We'll get the `workbox-recipes` documentation updated to reflect this.

**Comment by NicoSerranoP** [comment]
Thank you @jeffposnick it is working now! :)

**Comment by jeffposnick** [comment]
Great! Sorry again for the frustration.
