### ISSUE TITLE
WARNING in InjectManifest has been called multiple times

### ISSUE THREAD

**Issue by developdeez** [GoogleChrome/workbox#2826]
Hi Im using the receipes accroding to the example and injecting my sw using the webpack plugin (InjectManifest).

Everything seems fine but I noticed this error (below). Should I be concerned? If so how do I fix it?

`WARNING in InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.`

**Comment by jeffposnick** [comment]
You don't have to be worried in general—especially if you're using `--watch` as the error message assumes. There's more context in #1790, but it's not something that would affect your production deployments.

**Comment by hyfydistro** [comment]
@jeffposnick If it isn't something to worry about, how do we go about ignoring the message?
