### ISSUE TITLE
Updating Cache on new changes

### ISSUE THREAD

**Issue by developdeez** [GoogleChrome/workbox#2827]
I recently started using WorkBox reciepes.
I noticed when I cached 'everything' during development, it didn't update the site with my changes. 
I thought WorkBox automatically updated to latest.
If it's supposed to this is a bug.

**My big concern is when I make an update to the app, users wont get it until the cache expires. The update could be critical.**

My setup:

```
import { pageCache, imageCache, staticResourceCache, googleFontsCache, offlineFallback } from 'workbox-recipes';
import { precacheAndRoute } from 'workbox-precaching';

// Include offline.html in the manifest
precacheAndRoute(self.__WB_MANIFEST);

pageCache();

googleFontsCache();

staticResourceCache();

imageCache();

offlineFallback();
```

**Comment by jeffposnick** [comment]
If you're serving _all_ of your site's assets via `workbox-precaching`, then the "[How workbox-precaching Works](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#how_workbox-precaching_works)" information is relevant; it explains how the service worker updates previously precached URLs after each re-deployment, but will not actually use those updated resources until after the `activate` event of the newly updated service worker has been triggered.

If you would prefer for some of your web app, like your HTML, _not_ to be precached, then those URLs can be excluded from the precache manifest by configuring your build tool (the thing that replaces `self.__WB_MANIFEST` with the list of URLs) to exclude `.html` files. The other code you're using, like `pageCache()`, will handle caching your HTML instead.

CC: @Snugug in case he has any thoughts about how this is currently presented in the guide. I'm closing for now, but we can revisit as needed.

**Comment by Snugug** [comment]
As Jeff says, if you're precaching all of your site's content they'll be picked up by `workbox-precaching`, not recipes, so they'll follow the precaching flow described in the link. If, instead, you'd like to download new versions of assets when your service worker installs and still have your strategies be in charge of incremental updates, Workbox Recipe's [warm strategy cache](https://developers.google.com/web/tools/workbox/modules/workbox-recipes#warm_strategy_cache) functionality, or the `warmCache` options for `pageCache`, `staticResourceCache`, and `imageCache` can be used, but it's not a 1:1 replacement of precaching/the precaching injection.

@jeffposnick I'm not sure how best to make this distinction in the docs without a longer conversation about how and when precaching should be recommended and used

**Comment by developdeez** [comment]
> If you would prefer for some of your web app, like your HTML, _not_ to be precached

Ok. So Im working on a PWA so I assume I would set it to ignore the js files. And staticResourceCache would take care of caching my js and scss, while updating if there's a new version.

Latest attept based on answers:

```
import { pageCache, imageCache, staticResourceCache, googleFontsCache, offlineFallback } from 'workbox-recipes';
import { precacheAndRoute } from 'workbox-precaching';

// Include offline.html in the manifest
precacheAndRoute(self.__WB_MANIFEST, { ignoreURLParametersMatching: ['/.*.js', '/.*.css', '/.*.scss'] });

pageCache();

googleFontsCache();

staticResourceCache({ warmCache: ['.js', '.scss', '.css'] });

imageCache();

offlineFallback();
```

Is this correct to get the newest js and styles of my PWA. Also do you recommend adding html for PWAs? Any example of best practice using WorkBox in a PWA, possibly?

**Comment by jeffposnick** [comment]
After chatting with @Snugug, I think some of the confusion might be that the "[Quick Usage](https://developers.google.com/web/tools/workbox/modules/workbox-recipes#quick_usage)" section of the `workbox-recipes` guide currently tells folks to use `precacheAndRoute()`, but not everyone actually needs to use `workbox-precaching` as part of their service worker, and it can be confusing as to how precaching and runtime caching interact.

https://github.com/google/WebFundamentals/pull/9344 will remove that bit from the guide.

Do you have better luck using it without trying to get precaching set up, @developdeez?

```
import {
  pageCache,
  imageCache,
  staticResourceCache,
  googleFontsCache,
  offlineFallback,
} from 'workbox-recipes';

pageCache();
googleFontsCache();
staticResourceCache();
imageCache();
offlineFallback();
```

**Comment by developdeez** [comment]
@jeffposnick that causes an error when building (Im using webpack):
`ERROR in Can't find self.__WB_MANIFEST in your SW source.`

**Comment by jeffposnick** [comment]
You'd get that error if you're using the `InjectManifest` plugin, which attempts to locate `self.__WB_MANIFEST` in your service worker file and replace it with a list of assets to precache.

If you're not using precaching anymore, you don't have to use `InjectManifest`. You can just add your service worker in as an entry and have webpack bundle it directly like any other entry.

There's more guidance on this at https://developers.google.com/web/tools/workbox/guides/using-bundlers

**Comment by developdeez** [comment]
@jeffposnick I made that change now I get
`TypeError: ServiceWorker script at https://foxtailapp.com/service-worker.js for scope https://foxtailapp.com/ encountered an error during installation.`
Where would I find this error or is this because Im not using the Inject now

**Comment by jeffposnick** [comment]
You should see a description of what the underlying error is in the Chrome console, around the same place as that log message. Unfortunately, the log message you shared is very generic and it's not clear from it what's causing it.

**Comment by SaravgiYash** [comment]
@jeffposnick I was wondering how can I warm the cache if the URL is something like this: `/people/{username}/books/want-to-read`?
