### ISSUE TITLE
Rename workbox-precache when using generateSW plugin

### ISSUE THREAD

**Issue by dflorey** [GoogleChrome/workbox#2828]
**Library Affected**:
*generateSW*

**Issue or Feature Request Description**:
Unable to find a way to rename the workbox-precache name (probably just needs some documentation). I tried with cacheName on top level, but got an error.

**Comment by jeffposnick** [comment]
The `cacheId` configuration option will let you set a global cache prefix, which will apply to both the precaching cache name as well as the default runtime cache:

https://github.com/GoogleChrome/workbox/blob/2ddef47bbd8a44d3e1ce5e8b13598e022b0b99c7/packages/workbox-build/src/templates/sw-template.js#L29

Beyond that, if you need further configuration options, [switching to `injectManifest`](https://developers.google.com/web/tools/workbox/guides/get-started) will give you more control over your service worker file.
