### ISSUE TITLE
Make __WB_MANIFEST not mandatory

### ISSUE THREAD

**Issue by joker-777** [GoogleChrome/workbox#2833]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
any

**Issue or Feature Request Description**:
We don't want to cache any assets yet. we just want to show an offline page for now. Can you make the existence of `__WB_MANIFEST` not mandatory?

**Comment by jeffposnick** [comment]
Hello @joker-777. If you don't want to precache anything, you don't need to use the `InjectManifest` plugin. The purpose of that plugin is, as the name suggests, to derive a precache manifest from your `webpack` assets and inject it into your service worker.

You can pick and choose the pieces of Workbox's runtime libraries that you want to use, and follow the guide at https://developers.google.com/web/tools/workbox/guides/using-bundlers to bundle them into a usable service worker. In this case, the service worker source file would just be listed in the [`entry` configuration](https://webpack.js.org/concepts/entry-points/) for `webpack`, like any other JavaScript resource that needed to be bundled.

**Comment by joker-777** [comment]
@jeffposnick Thanks for your response. I was already thinking about adding the service-worker as another entry file but then it would be transpiled into a different destination folder which is not `public`. I liked on this plugin that it allowed me to specify a separate destination path only for service worker.

**Comment by jeffposnick** [comment]
I don't recommend using `InjectManifest` just for that side effect.

One alternative is to create multiple webpack compilations, each with different `path` configurations, and put the service worker entry in a separate compilation that writes to the desired location.

I believe this is referred to as "multi-compiler": https://github.com/webpack/webpack/blob/master/examples/multi-compiler/webpack.config.js

**Comment by joker-777** [comment]
@jeffposnick Thanks a lot for your recommendation. That's very helpful.
