### ISSUE TITLE
Repeated description on a different property and a misleading type

### ISSUE THREAD

**Issue by hyfydistro** [GoogleChrome/workbox#2835]
**Library Affected**:
workbox-build.

**Browser & Platform**:
Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (32-bit)

**Issue or Feature Request Description**:
At Google Web, Node Packages > workbox-build > RuntimeCachingEntry, under "Properties" > Options > Parameter. I found the following properties questionable.

- `precacheFallback.fallbackURL`
It describe its syntax should be a `number` instead of a `string`.

- `expiration.maxEntries`
It has the same description as `expiration.maxAgeSeconds`.

```
The maxAgeSeconds property to use when creating the ExpirationPlugin.
```

[Google Web > Tools > Reference Docs > Node Packages > workbox-build > RuntimeCachingEntry](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry)

**Comment by jeffposnick** [comment]
Thanks—this is fixed in https://github.com/GoogleChrome/workbox/commit/d67213424fb5f57cb0342c2a0dec5d257c21230c, which will be merged into the main `v6` branch in the near future.
