### ISSUE TITLE
Could we see default values on properties in the Documentation?

### ISSUE THREAD

**Issue by hyfydistro** [GoogleChrome/workbox#2839]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Issue or Feature Request Description**:
Could we see default values on properties in the Documentation? I think it would be easier to read the documentation with an example below it too. 

At [runtimeCachingEntry](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry), under 'Parameter', at 'options', I see 'backgroundSync'.
```
Parameter
--
backgroundSync

Optional

Object
```

... then there's no link to offer where this comes from or what module it is based on. This does not really give me a clue how to use it. The search bar isn't helpful either. It does a google search. **I want to see the word used in the documentation.**

I think it would be more welcoming to newcomers.

- see default values of properties if exist, otherwise say none assigned
- examples of properties
- list of properties' properties
- links to the properties
- better search result

I know there's some links to properties but it's really only a few.

**Comment by jeffposnick** [comment]
I do apologize about the lack of default values—that data is in our JSDocs, but the current JSDoc to HTML generation pipeline does not carry them over. Our current plan is to revise our HTML generation process, using the TypeScript definitions as the source of truth, and as part of that process, it's a priority to ensure that the default values are reflected in the generation docs.

CC: @tropicadri and @samthor

**Comment by hyfydistro** [comment]
Oh, I am not a season TypeScript user. I hope in the future, you find an alternative to update the doc besides the exclusivity with TypeScript.

Thank you.

**Comment by jeffposnick** [comment]
Closing this in favor of https://github.com/GoogleChrome/workbox/issues/2711, which I realize is already tracking the same thing.
