### ISSUE TITLE
Another mismatch between Docs and Types

### ISSUE THREAD

**Issue by SimonSiefke** [GoogleChrome/workbox#2845]
**Issue or Feature Request Description**:
In the Docs, setCatchHandler is called like this https://developers.google.com/web/tools/workbox/guides/advanced-recipes

```js
setCatchHandler(({event}) => {
  switch (event.request.destination) {
    case 'document':
      // If using precached URLs:
      // return matchPrecache(FALLBACK_HTML_URL);
      return caches.match(FALLBACK_HTML_URL);
    break;

    case 'image':
      // If using precached URLs:
      // return matchPrecache(FALLBACK_IMAGE_URL);
      return caches.match(FALLBACK_IMAGE_URL);
    break;

    case 'font':
      // If using precached URLs:
      // return matchPrecache(FALLBACK_FONT_URL);
      return caches.match(FALLBACK_FONT_URL);
    break;

    default:
      // If we don't have a fallback, just return an error response.
      return Response.error();
  }
}
```

This gives a type checking error with the TypeScript compiler, because `Response.error()` is not of type `Promise<Response>`: 

![type-checking-error-2](https://user-images.githubusercontent.com/23744935/118454628-df558300-b6f8-11eb-876a-aa22c448234f.png)

Possible solution 1: Update types to be `Response | Promise<Response>`

```ts
export interface RouteHandlerCallback {
    (options: RouteHandlerCallbackOptions): Response | Promise<Response>;
}
```

Possible solution 2: Making the callback function in docs async 

```ts
setCatchHandler(async ({event}) => {
  switch (event.request.destination) {
    default:
      // If we don't have a fallback, just return an error response.
      return Response.error();
  }
}
```

**Comment by jeffposnick** [comment]
Thanks—we'll update the docs to use an `async` function there, as we don't want to change the underlying `RouteHandlerCallback` type.
