### ISSUE TITLE
addEventListener fetch gives Typescript errors

### ISSUE THREAD

**Issue by kb-coder** [GoogleChrome/workbox#2848]
**Library Affected**:
*workbox-window v6.1.5*

**Issue or Feature Request Description**:
When trying to add a listener to the workbox instance for `fetch`, I get Typescript error "Argument of type 'fetch' is not assignable to parameter of type 'keyof WorkboxEventMap' ts(2345)"
![image](https://user-images.githubusercontent.com/11179251/118855902-2c695e80-b88b-11eb-8e61-b189e45726a1.png)

```
import { Workbox } from 'workbox-window'

const register = async () : Promise<void> => {
  if ('serviceWorker' in navigator) {
    const wb = new Workbox(`${process.env.BASE_URL}service-worker.js`)

    // wire up instance of registration so we can take further action on it.
    const registration = await wb.register()

    // This works and so does 'waiting', 'installed', activated'
    wb.addEventListener('controlling', () => {
      console.log('sw: controlling event listener hit.')
    })

    // This does not:
    wb.addEventListener('fetch', () => {
      console.log('sw: fetch event listener hit.')
    })
  }
}

export default register
```

**Comment by jeffposnick** [comment]
Hello @kb-coder!

`fetch` events are only fired within the `ServiceWorkerGlobalScope`, i.e. within the code that lives in your service worker file. The `workbox-window` library contains code that is meant to run in the `window` global scope, i.e. within the context of your main page.

To handle `fetch` events, make sure the code is in the service worker file that you register (`service-worker.js` in your example), and follow the guidance in the [Getting Started](https://developers.google.com/web/tools/workbox/guides/get-started) guide to use some combination of routing and response strategy libraries to perform the caching operations you expect.
