### ISSUE TITLE
Convert "Import" to "Const" when using WorkBox from Local

### ISSUE THREAD

**Issue by ErfanMHDi** [GoogleChrome/workbox#2851]
**Library Affected**:
*workbox-navigation-preload*

**Browser & Platform**:
*"all browsers"*

**Issue or Feature Request Description**:
Hello, im trying to use workbox from my localhost instead of CDN, i understand that in this case i have to use and convert "Import" to "Const" as it's been mentioned here: [LINK](https://developers.google.com/web/tools/workbox/modules/workbox-sw#convert_code_using_import_statements_to_use_workbox-sw). 
when i convert this line of code : 
`import {CacheableResponse} from 'workbox-cacheable-response';`
to this : 
`const {CacheableResponse} = workbox.cacheableResponse;`
at it seems to be correct with no error. 

but i have some trouble converting this line to Const:
`import * as navigationPreload from 'workbox-navigation-preload';`
as it been mentioned here : [LINK](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route)  (creating an offline page fallback).
i've tried : 
`const {navigationPreload} = workbox.navigationPreload;`
but it's not working and it drops an Error in Console : 
`Uncaught TypeError: Cannot read property 'enable' of undefined`

can any of you guys give me a hint on how can i convert the codes like that (mentioned in WorkBox Documentation) when i'm using workbox locally ?

i appreciate it 😉

**Comment by jeffposnick** [comment]
The equivalent statement would be

```js
const {enable} = workbox.navigationPreload;

// The call enable() to turn on navigation preload.
```

**Comment by ErfanMHDi** [comment]
@jeffposnick Thanks for your reply, 
but i think there is a still problem with `navigationPreload.enable();`
i'm trying to use this code [here](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route). 
and here is my Service worker file content: 
```
importScripts('../workbox/workbox-sw.js');

workbox.setConfig({
  modulePathPrefix: '../workbox/',
  debug: true,
});


//import * as navigationPreload from 'workbox-navigation-preload';
//const {navigationPreload} = workbox.navigationPreload;

const {enable} = workbox.navigationPreload;

const {registerRoute, NavigationRoute} = workbox.routing;
const {NetworkOnly} = workbox.strategies;

const CACHE_NAME = 'OfflinePage';
// This assumes /offline.html is a URL for your self-contained
// (no external images or styles) offline page.
const FALLBACK_HTML_URL = 'offline/index.htmll';
// Populate the cache with the offline HTML page when the
// service worker is installed.
self.addEventListener('install', async (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.add(FALLBACK_HTML_URL))
  );
});

navigationPreload.enable();

const networkOnly = new NetworkOnly();
const navigationHandler = async (params) => {
  try {
    // Attempt a network request.
    return await networkOnly.handle(params);
  } catch (error) {
    // If it fails, return the cached HTML.
    return caches.match(FALLBACK_HTML_URL, {
      cacheName: CACHE_NAME,
    });
  }
};

// Register this strategy to handle all navigations.
registerRoute(
  new NavigationRoute(navigationHandler)
);
```


the result is this error in console: 
`Uncaught TypeError: Cannot read property 'enable' of undefined at service-worker.js:30`

what i'm trying to do is preCache my offline page folder ( containing .css, .html, .png files) so when my pwa goes offline i can callback offline page with it's css and png. if there is another or better way of doing it please do.

**Comment by jeffposnick** [comment]
Your code currently has:

```js
navigationPreload.enable();
```

You should switch this to:

```js
enable();`
```

**Comment by ErfanMHDi** [comment]
Thank you for your response, 
That fixes the problem. 


The last thing i'm trying to fix here is having a css with some fonts and png file in offline page. 
using this content in service worker file loads the offline page but it fails to load it's assets. 
of course it was mentioned in the documents that 

> This assumes /offline.html is a URL for your self-contained (no external images or styles) offline page.

 but what if offline page need an image or some fonts inside? 
i've tried precache the assets of offline page in my service worker (named as "PreCache") and and rename the cache name inside navigation Preload function to "PreCache" so maybe when offline page falls back it loads the content of "PreCache" but no chance. 

can you please give me a help on this too ?

this is my current service worker content : 

```
precacheAndRoute([
  {url: '../fonts/fonts.css', revision: null},
  {url: 'offline/index.html', revision: null},
  {url: 'offline/style.css', revision: null},
  {url: 'offline/logo.png', revision: null},
]);
// the above files will be stored inside a Cache named "PreCache"

const {enable} = workbox.navigationPreload;

const CACHE_NAME = 'PreCache';
const FALLBACK_HTML_URL = 'offline/index.html';
self.addEventListener('install', async (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.add(FALLBACK_HTML_URL))
  );
});

enable();

const networkOnly = new NetworkOnly();
const navigationHandler = async (params) => {
  try {
    return await networkOnly.handle(params);
  } catch (error) {
    return caches.match(FALLBACK_HTML_URL, {
      cacheName: CACHE_NAME,
    });
  }
};

// Register this strategy to handle all navigations.
registerRoute(
  new NavigationRoute(navigationHandler)
);
```

![Screen Shot 2021-05-25 at 18 53 07](https://user-images.githubusercontent.com/74935638/119514781-8d60cd00-bd8a-11eb-901f-0dd7a8425b24.png)

**Comment by jeffposnick** [comment]
I don't think that's the right approach for what you describe. Using `workbox-precaching` implies that you have a build process set up to generate the list of assets to precache, and that doesn't appear to be the case based on your example.

The easiest approach would probably be to follow the examples from [`workbox-recipes`](https://developers.google.com/web/tools/workbox/modules/workbox-recipes), along the lines of:

```js
const {NetworkOnly, CacheOnly} = workbox.strategies;
const {registerRoute} = workbox.routing;
const {offlineFallback, warmStrategyCache} = workbox.recipes;
const {enable} = workbox.navigationPreload;

enable();

offlineFallback({
  pageFallback: '/offline/index.html',
});

// This route will make use of the navigation preload if online.
// If offline, the offlineFallback logic will kick in.
registerRoute(
  ({request}) => request.mode === 'navigate',
  new NetworkOnly(),
);

const offlineResourcesStrategy = new CacheFirst({
  cacheName: 'offline-resources',
});
// This will populate the cache of offline resources.
warmStrategyCache({
  strategy: offlineResourcesStrategy,
  urls: [
    '/offline/style.css',
    '/offline/logo.png',
    // Add any other URLs that are referenced in /offline/index.html
  ],
})

// This route will match all of the resource requests that start with /offline/
// and fulfill them from the cache.
registerRoute(
  ({url}) => url.pathname.startsWith('/offline/'),
  offlineResourcesStrategy
);
```

**Comment by ErfanMHDi** [comment]
Thank you for your answer.
it's perfectly working, 
except there is an error for logo.png looks like it's something wrong with file type and cacheFirst strategy 

`workbox Network request for '/wp-assets/store/offline/logo.png' threw an error. TypeError: Failed to fetch`

and another thing is that `offlineFallback()` is creating its own cache named as "workbox-offline-fallback" with only offline/index.html inside it, is it possible to cache the offline/index.html file inside "offline-resources" cache or some how prevent `offlineFallback()` from creating its own cache folder ?


here is my sw file : 
```js
const {enable} = workbox.navigationPreload;

enable();

offlineFallback({
  pageFallback: 'offline/index.html',
});

// This route will make use of the navigation preload if online.
// If offline, the offlineFallback logic will kick in.
registerRoute(
  ({request}) => request.mode === 'navigate',
  new NetworkOnly(),
);

const offlineResourcesStrategy = new CacheFirst({
  cacheName: 'offline-resources',
});
// This will populate the cache of offline resources.
warmStrategyCache({
  strategy: offlineResourcesStrategy,
  urls: [
    'offline/index.html',
    'offline/style.css',
    'offline/logo.png',
    // Add any other URLs that are referenced in /offline/index.html
  ],
})

// This route will match all of the resource requests that start with /offline/
// and fulfill them from the cache.
registerRoute(
  ({url}) => url.pathname.startsWith('/wp-assets/store/offline/'),
  offlineResourcesStrategy
);
```

**Comment by jeffposnick** [comment]
Are you getting the `workbox Network request for '/wp-assets/store/offline/logo.png' threw an error. TypeError: Failed to fetch` message during service worker installation, or after installation, when you attempt to simulate what happens when you're offline?

I also recommend testing this in a fresh Chrome Incognito window so that you can ensure you're not see the after effects of the previous attempted service worker.

**Comment by ErfanMHDi** [comment]
it happens when i reload the page in offline mode, 
im doing all in Chrome Incognito every time. 

this is WorkBox Log when first page loads: 
```
logger.js:44 workbox Using CacheFirst to respond to '/wp-assets/store/offline/index.html'
logger.js:44 workbox Using CacheFirst to respond to '/wp-assets/store/offline/style.css'
logger.js:44 workbox Using CacheFirst to respond to '/wp-assets/store/offline/logo.png'
```

and this when page goes offline and i hit refresh : 

```
logger.js:44 workbox Router is responding to: /store/accessories/
logger.js:44 workbox Using NetworkFirst to respond to '/store/accessories/'
logger.js:44 workbox Error thrown when responding to:  /store/accessories/. Falling back to global Catch Handler.
logger.js:44 workbox Router is responding to: /wp-assets/store/offline/style.css
logger.js:44 workbox Router is responding to: /wp-assets/store/offline/logo.png
logger.js:44 workbox Using CacheFirst to respond to '/wp-assets/store/offline/style.css'
logger.js:44 workbox Using CacheFirst to respond to '/wp-assets/store/offline/logo.png'
logger.js:44 workbox Error thrown when responding to:  /wp-assets/store/offline/logo.png. Falling back to global Catch Handler.
```
![Screen Shot 2021-05-26 at 00 05 53](https://user-images.githubusercontent.com/74935638/119558031-2bb65800-bdb6-11eb-88b7-5b3c04a97532.png)

**Comment by ErfanMHDi** [comment]
it looks like the png file is loading without any problem if i refresh the page. 
when i open a page in an Incognito mode in chrome and then go offline after the initial load the png file gets the above error and won't show up. 
but if i open an Incognito window and open a page and then reload the page (or visit another page of domain) and then go offline then the png file is loading without any problem. 

what am i missing here ? 
how can i logo the png in initial first page load ?

**Comment by jeffposnick** [comment]
There might be a `Vary:` header that's causing your explicit caching during `install` to not match the runtime request, but for the request to match when the cache is populated at runtime? It's rather hard to say without actually accessing the site with Chrome's DevTools open an taking a look at the actual network traffic, unfortunately.

**Comment by ErfanMHDi** [comment]
okay, Thanks for your help, i've decided to remove the png logo from offline page after all, 
so i just have some font, css and html file. and every thing works great thanks to the code snippet you kindly shared with me. 
just one last question as i'm trying to organize storage cache in browser is there any way i can remove the cache folder named "workbox-offline-fallbacks" (it only has offline/index.html) created by this line: 
```js
offlineFallback({
  pageFallback: '/wp-assets/sw/offline/index.html',
});
```
and serve the offline/index.html from "Offline" Cache folder cause we have the offline/index.html in that folder too. 

here is my current sw.js file: 
```js

const {enable} = workbox.navigationPreload;

enable();

offlineFallback({
  pageFallback: '/wp-assets/sw/offline/index.html',
});

registerRoute(
  ({request}) => request.mode === 'navigate',
  new NetworkOnly(),
);

const OfflinePageAssets = new CacheFirst({
  cacheName: 'Offline',
});
// This will populate the cache of offline resources.
warmStrategyCache({
  strategy: OfflinePageAssets,
  urls: [
	'/wp-assets/sw/offline/index.html',
	'/wp-assets/sw/offline/style.css',
	'/wp-assets/fonts/MiConSet/eot/MiConSet.eot',
	'/wp-assets/fonts/MiConSet/svg/MiConSet.svg',
	'/wp-assets/fonts/MiConSet/ttf/MiConSet.ttf',
	'/wp-assets/fonts/MiConSet/woff/MiConSet.woff',
	'/wp-assets/fonts/MiConSet/woff2/MiConSet.woff2'
  ],
})

// This route will match all of the resource requests that start with /offline/
// and fulfill them from the cache.
registerRoute(
  ({url}) => url.pathname.startsWith('/wp-assets/sw/offline/'),
  OfflinePageAssets
);

```

**Comment by jeffposnick** [comment]
I'm sorry, but if you're using `offlineFallback()`, that cache name isn't customizable.

**Comment by ErfanMHDi** [comment]
Okay, is there any other method to serve offline/index.html from its “Offline” cache folder ?! 
i have done it like this without workBox: 

```js
addEventListener('install', (event) => {
	event.waitUntil(async function() {
		const cache = await caches.open('OfflinePage');
		await cache.addAll([
			'/wp-assets/sw/offline/index.html',
			'/wp-assets/sw/offline/style.css',
			'/wp-assets/fonts/MiConSet/eot/MiConSet.eot',
			'/wp-assets/fonts/MiConSet/svg/MiConSet.svg',
			'/wp-assets/fonts/MiConSet/ttf/MiConSet.ttf',
			'/wp-assets/fonts/MiConSet/woff/MiConSet.woff',
			'/wp-assets/fonts/MiConSet/woff2/MiConSet.woff2'
		]);
	}());
});

addEventListener('activate', event => {
	event.waitUntil(async function() {
		if (self.registration.navigationPreload) {
			await self.registration.navigationPreload.enable();
		}
	}());
});

addEventListener('fetch', (event) => {
	const { request } = event;
	if (request.headers.has('range')) return;
	event.respondWith(async function() {
		const cachedResponse = await caches.match(request);
		if (cachedResponse) return cachedResponse;
		try {
			const response = await event.preloadResponse;
			if (response) return response;
			return await fetch(request);
		} catch (err) {
			if (request.mode === 'navigate') {
				return caches.match('/wp-assets/sw/offline/index.html');
			}
			throw err;
		}
	}());
}
);
```

it creates only one folder named ‘OfflinePage’ and saved the offline/index.html with fonts and css file and then serve the html file when there is no network! 

Would you please help me recreate something like this with WorkBox ? 

Thanks!
