### ISSUE TITLE
webpackCompilationPlugins option of InjectManifest seems to be ignored

### ISSUE THREAD

**Issue by crubier** [GoogleChrome/workbox#2859]
**Library Affected**:
workbox-build

**Browser & Platform**:
NA

**Issue or Feature Request Description**:

webpackCompilationPlugins Option of InjectManifest seems to be totally ignored in my setup. 

When looking at the codebase of workbox, the name of this option is only mentionned in 4 places: twice in docs, once in input validation, and once in a test file, nowhere is it used in actual code. 

So I don’t understand how this option is taken into account, and it does not seem to be taken into account in my setup.

Any input on this ?

**Comment by jeffposnick** [comment]
Hello @crubier—the option is used in https://github.com/GoogleChrome/workbox/blob/f6fb94a9d8b922fdcb758129d94e6d2a959f2167/packages/workbox-webpack-plugin/src/inject-manifest.js#L205-L209

Working with `webpack`'s child compiler is [notoriously difficult](https://medium.com/@prateekbh/my-experience-writing-a-webpacks-child-compiler-plugin-a1237c175947), but my understanding is that the code above should successfully apply any plugins you provide to the compilation that is applied to your `swSrc` file.

If you have an example of a setup in which a plugin doesn't behave as expected, could you share that configuration?

**Comment by crubier** [comment]
Hi @jeffposnick ,

Ok well, sorry, I think I found a bug in Github code search feature then aha. 

My Github code search gave these result, but indeed the code you are talking about exists (and should have been visible in the search result I expect)

<img width="798" alt="Screenshot 2021-06-02 at 23 28 52" src="https://user-images.githubusercontent.com/2954572/120560337-70677200-c3fa-11eb-9dd4-08061b7794e0.png">


On another topic, after moving my setup to Webpack 5, the problem is solved on workbox side I think (The plugin gets applied, as expected). But the plugins seems to have no effect on the compilation / some hooks of the plugin seems to not be called. I'll keep investigating...

**Comment by jeffposnick** [comment]
If you have any follow-ups, feel free to post details. I'm going to close this for now, though.
