### ISSUE TITLE
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.

### ISSUE THREAD

**Issue by samgermain** [GoogleChrome/workbox#2861]
**Library Affected**:
*webpack-workbox-plugin*

**Browser & Platform**:
*Google Chrome*

I include `new GenerateSW(),` in the plugins of my webpack config but receive this warning when running lighthouse on my website

```
Web app manifest or service worker do not meet the installability requirements 1 reason

Service worker is the technology that enables your app to use many Progressive Web App features, such as offline, add to homescreen, and push notifications. With proper service worker and manifest implementations, browsers can proactively prompt users to add your app to their homescreen, which can lead to higher engagement

Failure reason
--
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.


Does not register a service worker that controls page and start_url
The service worker is the technology that enables your app to use many Progressive Web App features, such as offline, add to homescreen, and push notifications.
```

I can see that the service worker is running in my console, because it prints

LOG from GenerateSW
<i> The service worker at service-worker.js will precache
<i>         107 URLs, totaling 5.25 MB

---------------------------------

I am also using `WebpackPWAManifest`

```
    new WebpackPwaManifest({
      icons: [
        {
          src: Icon192,
          sizes: "192x192",
          type: "image/png",
          purpose: "any maskable",
        },
        {
          src: Icon512,
          sizes: "512x512",
          type: "image/png",
        },
      ],
      name: "Example",
      short_name: "Example",
      orientation: "portrait",
      start_url: "/",
      scope: "/",
      theme_color: "#ffffff",
      background_color: "#ffffff",
      description: "Example",
      display: "standalone", 
      prefer_related_applications: false, 
    }),
```

**Comment by jeffposnick** [comment]
Hello @samgermain!

You might be seeing that error if you are registering a service worker that is located at a subpath of your site (e.g. `/static/service-worker.js`), rather than served at a top-level URL (e.g. `/service-worker.js`). Your service worker needs to be registered as `/service-worker.js` in order to control the `start_url` of `/`, as per the service worker [scoping rules](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope).

Hopefully that's the issue. If not, let us know and we can reopen to investigate further.

**Comment by samgermain** [comment]
@jeffposnick 
So then I would change `new GenerateSW()` to something like `new GenerateSW({scope: "/"})`?

**Comment by jeffposnick** [comment]
This isn't directly related to options passed to `GenerateSW()` (though you _may_ need to configure [`modifyUrlPrefix`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#:~:text=used-,modifyurlprefix,-Optional) to adjust the URL paths).

It's related to where you host your service worker file on your web server and the URL used when you register it. You'd need

```
navigator.serviceWorker.register('/service-worker.js');
```

**Comment by samgermain** [comment]
Where would I put this line of code?
I'm using React and webpack, and tried adding it to my main App.js file before anything is rendered

I still get the warning, but I also recceive a lot of 

`workbox Router is responding to: /main/main.js`

in the console now from `logger.js`

-----------
Also I get these when I try to visit these domains

`Cannot GET /static/service_worker.js` and `Cannot GET /service_worker.js`

**Comment by jeffposnick** [comment]
https://developers.google.com/web/fundamentals/primers/service-workers/registration has some general guidance about _when_ to call `navigator.serviceWorker.register('/service-worker.js');`. That would be translatable into code that would go in `App.js` in all likelihood.

If you're seeing a request for `/static/service_worker.js` then it means that something, like an older version of your site, must still be referencing your service worker from that URL (instead of from `/service_worker.js`). And if you're seeing `Cannot GET /service_worker.js` logged on a specific domain, that would imply that you haven't successfully deployed the service worker to that web server at that URL.

**Comment by samgermain** [comment]
I'm getting those cannot get when I specifically visit those urls

**Comment by jeffposnick** [comment]
I'd recommend making sure that you're explicitly including the `service-worker.js` file that's generated by `GenerateSW()` in your deployment process when you update your site's content, and ensure that it's located at the top-level of your content, so that it's reachable from `/service-worker.js`. Unfortunately, the specifics of how to do that are very dependent on what you're using for web hosting and deployment, and are outside of the scope of what the Workbox project can help with.

**Comment by samgermain** [comment]
So it's working now, I'm a lot of lines of 

`Router is responding to: /images/image.webp`

Is there a way to turn this off for images, I feel like it's too much

**Comment by samgermain** [comment]
How do I find out what the service-worker src is? I figure I can just specify them in my `WebpackPwaManifest`. I figure the dest woul d just be `service-worker.js`.

------------

I can visit /service-worker.js now by the way, I was getting the get before I added that code from earlier in this comment

**Comment by samgermain** [comment]
So when I add 

```
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('/service-worker.js');
    });
  }
```

to my App.js, then hot reload no longer works, the lighthouse warning still shows up, but the weird thing is that I'm able to still visit `localhost:8080/service-worker.js` and it shows the service worker

**Comment by samgermain** [comment]
There was also an issue that when new updates for the site were pushed to netlify, a user's browser wouldn't show the updated website version unless their cache/history were cleared

I wouldn't say this issue is closed, this is still something that I want to figure out how to fix. 
I created a [boiler plate](https://github.com/samgermain/react-boiler-plate) that I want to fix this issue on

I removed this from the `App.js` because I didn't want to deal with the problems that were happening

```
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('/service-worker.js');
    });
  }
```

**Comment by jeffposnick** [comment]
Hello @samgermain—apologies that all of this isn't as spelled out as clearly as it should be in the Workbox documentation. We have a project that's getting underway to overhaul our guides significantly.

https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle provides a good background on how the service worker lifecycle works.

When using a service worker created by `GenerateSW`, you end up with all of your `webpack` assets [precached](https://developers.google.com/web/tools/workbox/modules/workbox-precaching), and served using a cache-first strategy. Browsers will continue using the cached assets associated with the service worker that's in control of the page indefinitely, until and updated service worker moves from the [`waiting` to `active` state](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#waiting) and takes control.

Reloading an open page isn't sufficient to activate a waiting service worker; you have to close all open tabs before that happens, or alternatively, call [`skipWaiting()`](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_the_waiting_phase) from within the updated service worker. This can often cause confusion as developers testing things out believe that they are permanently stuck on an old version of their precached assets.

I'd recommend a few things:

First, don't register a precaching service worker in development, as aggressively caching resources very much goes against the "hot reload" philosophy.

Second, if you want to see some approaches to programmatically triggering the `skipWaiting()` call, the "[Offer a page reload for users](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users)" recipe is one approach.

Third, a lot of these best practices have been baked in to the [PWA template](https://create-react-app.dev/docs/making-a-progressive-web-app/) for the `create-react-app` framework already, with the code at https://github.com/cra-template/pwa/tree/master/packages/cra-template-pwa/template/src You can draw inspiration from how it avoids registering a service worker on localhost, as well as offers callbacks for triggering `skipWaiting()` programmatically.

I hope that helps! If you're still stuck, you could consider a less aggressive caching strategy than what `GenerateSW` implements by default. You can follow the guide at https://developers.google.com/web/tools/workbox/guides/get-started to write a service worker that just uses a network-first strategy if that's more appropriate for your use case.

**Comment by samgermain** [comment]
> Third, a lot of these best practices have been baked in to the [PWA template](https://create-react-app.dev/docs/making-a-progressive-web-app/) for the `create-react-app` framework already, with the code at https://github.com/cra-template/pwa/tree/master/packages/cra-template-pwa/template/src You can draw inspiration from how it avoids registering a service worker on localhost, as well as offers callbacks for triggering `skipWaiting()` programmatically.

Hey sorry, I'm not that smart. I ditched `GenerateSW` and tried using `create-react-app` to create that template for `cra-template-pwa` and tried copying these files to my `src` folder and the following config over to my project

-  reportWebVitals.js
- service-worker.js
- serviceWorkerRegistration.js
- setupTests.js 

```
//TODO: Most of this code is probably unnecessary, remove most of it
const path = require("path");
const { InjectManifest } = require("workbox-webpack-plugin");
const moduleFileExtensions = [
  "web.mjs",
  "mjs",
  "web.js",
  "js",
  "web.ts",
  "ts",
  "web.tsx",
  "tsx",
  "json",
  "web.jsx",
  "jsx",
];
const fs = require("fs");
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = (relativePath) => path.resolve(appDirectory, relativePath);
const resolveModule = (resolveFn, filePath) => {
  const extension = moduleFileExtensions.find((extension) =>
    fs.existsSync(resolveFn(`${filePath}.${extension}`))
  );

  if (extension) {
    return resolveFn(`${filePath}.${extension}`);
  }

  return resolveFn(`${filePath}.js`);
};
const swSrc = resolveModule(resolveApp, "src/service-worker");

module.exports = [
  fs.existsSync(swSrc) &&
    new InjectManifest({
      swSrc,
      dontCacheBustURLsMatching: /\.[0-9a-f]{8}\./,
      exclude: [/\.map$/, /asset-manifest\.json$/],
      // Bump up the default maximum size (2mb) that's precached,
      // to make lazy-loading failure scenarios less likely.
      // See https://github.com/cra-template/pwa/issues/13#issuecomment-722667270
      maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
    }),
];
```

Here's the result with [chrome dev tools](https://i.imgur.com/OJq4fR2.png)  and here's the result with a [firefox lighthouse extension](https://i.imgur.com/iwYubc7.png)

both are getting ` Does not register a service worker that controls page and start_url ` and chrome is getting 

```
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.
```

---------------

I pushed the changes about a week ago and am still getting these results today

## Github Repo
This is the github repo for a project I'm trying to get the service worker on
https://github.com/samgermain/react-boiler-plate/tree/workbox

-------------

I forgot the mention that the build is failing

`ERROR in Can't find self.__WB_MANIFEST in your SW source.`

another issue I can't fix

**Comment by jeffposnick** [comment]
The build is failing because [this line](https://github.com/samgermain/react-boiler-plate/blob/36c97e0677671e7e2ffceabee67747a83a4874bd/build_config/webpack.prod.config.js#L24) should be

```
        PUBLIC_URL: JSON.stringify("https://react-boiler-plate.netlify.app"),
```

Without the extra `JSON.stringify()`, you end up with missing quotes around the string.

Once I fixed that locally, your build succeeded, including the `InjectManifest()`.

**Comment by samgermain** [comment]
> The build is failing because [this line](https://github.com/samgermain/react-boiler-plate/blob/36c97e0677671e7e2ffceabee67747a83a4874bd/build_config/webpack.prod.config.js#L24) should be
> 
> ```
>         PUBLIC_URL: JSON.stringify("https://react-boiler-plate.netlify.app"),
> ```
> 
> Without the extra `JSON.stringify()`, you end up with missing quotes around the string.
> 
> Once I fixed that locally, your build succeeded, including the `InjectManifest()`.

Thanks, that fixed the build.

I'm still getting these warnings when I run lighthouse though

```
 Web app manifest and service worker meet the installability requirements 

 Does not register a service worker that controls page and start_url
The service worker is the technology that enables your app to use many Progressive Web App features, such as offline, add to homescreen, and push notifications
```

**Comment by jeffposnick** [comment]
Your web app's code doesn't register the generated service worker. In fact, it actively unregisters a service worker if it detects one:

```js
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://cra.link/PWA
serviceWorkerRegistration.unregister();
```

You need to change that at https://github.com/samgermain/react-boiler-plate/blob/36c97e0677671e7e2ffceabee67747a83a4874bd/src/index.js#L16-L19 if you want the service worker to be registered.
