### ISSUE TITLE
Production build of workbox-window used in development by default

### ISSUE THREAD

**Issue by mattixiv** [GoogleChrome/workbox#2866]
**Library Affected**:
workbox-window

**Browser & Platform**:
Webpack v5, maybe other bundlers

**Issue or Feature Request Description**:
One gets an impression when reading [this part](https://developers.google.com/web/tools/workbox/modules/workbox-window#avoiding_common_mistakes) of documentation that you get a nice situation report in the console regarding the service worker lifecycle by just importing workbox-window and using that to register the service worker. However, when using Webpack Dev Server I didn't see any logging from workbox-window.

The reason is that Webpack resolves workbox-window to the production build regardless of the Webpack mode or `NODE_ENV`. I had to add
```
  resolve: {
    alias: {
      'workbox-window': 'workbox-window/Workbox.mjs',
    },
  },
```
to the Webpack config for dev mode to get this logging to work.

It would be nice if mode could be autodetected and logging enabled or disabled accordingly. But at least it would be a good idea to mention this in the documentation.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
