### ISSUE TITLE
Provide build-time variables for conditional code compilation

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2873]
We need to use wokbox in dev mode without some code and plugins, but now we are forced to maintain 2 copies of sw.js - development and production

It would be nice to have build time webpack's variables like `__PROD__` to have an ability conditional code compilation

**Comment by jeffposnick** [comment]
I'm not exactly sure how Workbox could help with this—we do take advantage of [`process.env.NODE_ENV` inside of our own codebase](https://developers.google.com/web/tools/workbox/guides/using-bundlers#configure_your_bundler_for_a_development_or_production_build) to conditionally include/omit debug logging if you're creating your own custom bundle based on our source code, but the assumption is that whichever bundler you're using will handle substituting `process.env.NODE_ENV` with the appropriate value.

Have you considered just using `process.env.NODE_ENV` in your own code as well, along the lines of:

```
import {registerRoute} from 'workbox-routing';
import {NetworkFirst, StaleWhileRevalidate} from 'workbox-strategies';

const strategy = process.env.NODE_ENV === 'production' ?
                 new StaleWhileRevalidate() :
                 new NetworkFirst();

registerRoute(
  ({request}) => request.mode === 'navigate',
  strategy
);
```

**Comment by budarin** [comment]
`process.env.NODE_ENV` is usless in runtime when sw is in the browser )

Please, have a look at [define-plugin](https://webpack.js.org/plugins/define-plugin/)

it defines build time variables which are used with minimizers to add/remove code in transpiling and bundling stage

webpack.config
```js
const config = {
    mode: 'production',
    ...
    plugins: {
        new webpack.DefinePlugin({
            __PROD__: true,
        }),
```
using in code
```js
if (__PROD__) {
   // this code will stay here after compilation
}

if (!__PROD__) {
   //but  this code will be removed after compilation
}
```

**Comment by jeffposnick** [comment]
Under the hood, `webpack` [automatically creates an instance of `DefinePlugin`](https://webpack.js.org/guides/production/#specify-the-mode) based on compilation `mode`, and that does the `process.env.NODE_ENV` replacement for you.

```
if (__PROD__) {
   // this code will stay here after compilation
}

if (!__PROD__) {
   //but  this code will be removed after compilation
}
```

seems equivalent to

```
if (process.env.NODE_ENV === 'production') {
   // this code will stay here after compilation
}

if (!process.env.NODE_ENV === 'production') {
   //but  this code will be removed after compilation
}
```

I'm sorry if I'm misunderstanding your request. What exactly would you like Workbox (presumably `workbox-webpack-plugin`) to do that you don't already get via the default `webpack` behavior?

**Comment by budarin** [comment]
in browser when service worker starts there is no `process.env.NODE_ENV` (

**Comment by jeffposnick** [comment]
Right, but the idea is that your build tool will replace `process.env.NODE_ENV` with the string `'production'` or `'development'` for you during compilation. `webpack` does this automatically. After this happens, the code at runtime looks like

```
if ('production' === 'production') {
   // this code will stay here after compilation
}
```

If you're asking about how to use Workbox without any compilation step, then that's what [`workbox-sw` allows you to do](https://developers.google.com/web/tools/workbox/modules/workbox-sw), using pre-built development or production bundles of Workbox. Is that what you're trying to do?

**Comment by budarin** [comment]
you are right!!

but the code
```js
if (process.env.NODE_ENV === 'production') {
   // this code will stay here after compilation
}

if (!process.env.NODE_ENV === 'production') {
   //but  this code will be removed after compilation
}
```
will stay in the sw code and when it run in a browser `process.env.NODE_ENV` will be undefined

but the code
```js
if (__PROD__) {
   // this code will stay here after compilation
}

if (!__PROD__) {
   //but  this code will be removed after compilation
}
```
 will be transpiled into 
 ```js
    // this code will stay here after compilation
```

webpack does not automatically replace `process.env.NODE_ENV` with its value - only the plugin does replase variable with its value

**Comment by budarin** [comment]
I'm sorry - I was wrong!
Really, webpack replaces `process.env.NODE_ENV` for web project - I didn't know that

I usually develop backend on node.js and there webpack does not replace `process. env. NODE_ENV` with its value automatically-so I thought that it was everywhere :)
