### ISSUE TITLE
Use separately Workbox Background Sync

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#2875]
I have an application built in Angular and in this application I use the cache system provided by the @angular/pwa package.
However, I have a demand for the application that the standard angular package doesn't provide, which is Workbox Background Sync.

I would like to know if I can only use the `Workbox Background Sync` package, without having to use the Workbox configuration files, knowing that I have a cache system.
How would I do this?

**Comment by jeffposnick** [comment]
This should be possible, as there's nothing in `workbox-background-sync` that requires using Workbox's caching or routing methods. The main challenge would be to ensure that you can write your own `fetch` handler that executes before the `@angular/pwa`-provided one responds to incoming requests.

The general code to follow, [adapted from the docs](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync#adding_a_request_to_the_queue), would be:

```js
import {Queue} from 'workbox-background-sync';

const queue = new Queue('myQueueName');

// This fetch handler needs to execute before Angular's fetch handlers run...
// I'm not sure how to ensure that happens, though.
self.addEventListener('fetch', (event) => {
  // Change this criteria as needed to return early unless it's a request that should
  // be handled with background sync.
  // This assumes you want it to handle POSTs for URLs ending in /path/to/api
  if (event.request.method !== 'POST' ||
      !event.request.url.endsWith('/path/to/api')) {
    return;
  }

  const bgSyncLogic = async () => {
    try {
      const response = await fetch(event.request.clone());
      return response;
    } catch (error) {
      await queue.pushRequest({request: event.request});
      return error;
    }
  };

  event.respondWith(bgSyncLogic());
});
```
