### ISSUE TITLE
handlerDidError callback parameter is not exported

### ISSUE THREAD

**Issue by ivandotv** [GoogleChrome/workbox#2876]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
"all browsers".*

**Issue or Feature Request Description**:
I'm trying to create a custom plugin, and I can't get a hold on on `HandlerDidErrorCallbackParam` 
Other callback params are exported (`HandlerWillStartCallbackParam` etc..).

```ts
export class OfflineFallbackWithLocale implements WorkboxPlugin {

  // @ts-expect-error - HandlerDidErrorCallbackParam is not exported
  async handlerDidError(param: any) {
    //custom logic for offline page
    return this._precacheController.matchPrecache(this._fallbackURL)
  }
}
```
Although we could do object destructuring immediately
```ts
  async handlerDidError({ request }: { request: Request }) {}
```

**Comment by jeffposnick** [comment]
Thanks—that's an oversight which we'll fix in an upcoming release.

**Comment by jeffposnick** [comment]
The fix is now deployed in a pre-release of Workbox v6.2.0: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0
