### ISSUE TITLE
Example of defining BlackList for Wordpress MultiSite

### ISSUE THREAD

**Issue by ErfanMHDi** [GoogleChrome/workbox#2877]
**Library Affected**:
workbox-sw, workbox-navigation, workbox.routing

**Browser & Platform**:
All Browsers

**Issue or Feature Request Description**:
i'm using WorkBox without any Production Build, on my Wordpress MultiSite installation, and i wanted to define a black list to make service worker skip specific urls from any cache strategy defined in my sw.js file. 
the urls i'm trying to define are in a format like this : 

1. mainsite.com/**wp-admin/***
2. mainsite.com/***&preview=true**
3. mainsite.com/**subsite1/wp-admin/***
4. mainsite.com/**subsite1/*&preview=true**

right now i'm caching the pages this way: 

```js
registerRoute(
	({request, url}) => 
		request.mode === 'navigate' &&
		!url.pathname.startsWith('/store/wp-admin') &&
		!url.pathname.startsWith('/store/wp-login') &&
		!url.pathname.startsWith('/store/account') &&
		!url.pathname.startsWith('/store/bag') &&
		!url.pathname.startsWith('/store/checkout') &&
		
		!url.pathname.startsWith('/blog/wp-admin') &&
		!url.pathname.startsWith('/blog/wp-login') &&
		!url.pathname.startsWith('/blog/account'),
	new NetworkFirst({
		cacheName: 'Pages',
		plugins: [
			new CacheableResponsePlugin({
				statuses: [200],
			}),
		],
	}),
);
```

but there is lot's of sub site and lots of urls i have to define manually one by one, and for each "registerRoute" i have defined. 
(for example for "Pages", "CSS, JS", "Fonts" and etc ...)
is it possible to define a list of url using regex or some method to skip all urls that contains "wp-admin" for all  my defined "registerRoute" in my sw.js file ?!

i appreciate any help or hint on this case.
Thanks in Advance.

**Comment by jeffposnick** [comment]
I think roughly speaking this is the same request as https://github.com/GoogleChrome/workbox/issues/2330

We can prioritize implementing this in an upcoming release, and use that original issue for tracking.
