### ISSUE TITLE
workbox-window "bad-precaching-response" error and "redundant" service worker

### ISSUE THREAD

**Issue by GustavoSD** [GoogleChrome/workbox#2879]
**Library Affected**:
*workbox-window*

**Browser & Platform**:
*chromium-based browser*

**Issue or Feature Request Description**:
I'm having this problem only when trying to implement workbox-window. If I remove the implementation, the errors disappear.

My goal is to show the service worker version. For that, I followed the instructions from the docs, and despite I can get the service worker version, it is causing a couple of troubles.

**Workbox Docs reference:**
[https://developers.google.com/web/tools/workbox/modules/workbox-window?hl=es#window_to_service_worker_communication](https://developers.google.com/web/tools/workbox/modules/workbox-window?hl=es#window_to_service_worker_communication)

**Issues**
1. It shows a *bad-precaching-response* error in the console: 
![bad-precaching-response](https://user-images.githubusercontent.com/45019081/123860319-9e958000-d8da-11eb-8f50-ae8fc68495a1.png)
2. It generates *redundant* service workers:
![service worker](https://user-images.githubusercontent.com/45019081/123860661-08158e80-d8db-11eb-8949-b90cf465b6d2.png)

I repeat: Once I remove the workbox-window implementation, the bad-precaching-response disappears and it stops generating redundant service workers

**SW registration**
```javascript
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function() {
        navigator.serviceWorker.register('/clock-service-worker.js?clock_uri=' + clock_uri, { scope: '/clock/' }).then(function(registration) {
            console.log('ServiceWorker registration successful: ', registration)
        }, function(err) {
            console.log('ServiceWorker registration failed: ', err)
        })
    })
}
```

**clock-service-worker.js (SW file)**
```javascript
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-sw.js');

const SW_VERSION = '2.0.0'
const CLOCK_URI = new URL(location).searchParams.get('clock_uri')

const precacheResources = [
    { url: `/clock/index/${CLOCK_URI}`, revision: null },
    { url: `/clock/directory/${CLOCK_URI}`, revision: null },
    { url: `/clock/passcode/${CLOCK_URI}`, revision: null },
    { url: `/clock/home/${CLOCK_URI}`, revision: null },
    { url: `/clock/punch/${CLOCK_URI}`, revision: null },
    { url: `/clock/offline_punch/${CLOCK_URI}?status=in`, revision: null },
    { url: `/clock/offline_punch/${CLOCK_URI}?status=out`, revision: null },
    { url: '/css/clock.css', revision: null },
    { url: '/js/js.cookie-2.2.1.min.js', revision: null },
    { url: '/js/jquery-3.2.1.min.js', revision: null },
    { url: '/js/bootstrap.min.js', revision: null },
    { url: '/js/moment/moment.js', revision: null },
    { url: '/js/moment/locale/es.js', revision: null },
    { url: '/js/webcam/webcam.min.js', revision: null },
    { url: '/js/clock/clock-scripts.js', revision: null },
    { url: '/fonts/Material_Icons/MaterialIcons-Regular.woff2', revision: null },
    { url: '/fonts/Barlow_Condensed/barlow-condensed-v4-latin-600.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-600.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-700.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-regular.woff2', revision: null },
    { url: '/images/employee/placeholder.png', revision: null },
    { url: '/audio/punch-error.mp3', revision: null },
    { url: '/audio/punch-in.mp3', revision: null },
    { url: '/audio/punch-out.mp3', revision: null }
]

workbox.setConfig({ debug: true })

workbox.core.setCacheNameDetails({
    prefix: 'clock',
    suffix: 'v2',
    precache: 'precache',
    runtime: 'runtime'
})

const ignoreQueryStringPlugin = {
    cacheKeyWillBeUsed: async ({ request, mode, params, event, state }) => {
        curl = new URL(request.url)
        return curl.pathname  
    }
}

const cacheName = workbox.core.cacheNames.precache
const options = {
    cacheName,
    plugins: [ignoreQueryStringPlugin]
}

// pages
workbox.routing.registerRoute(
    new RegExp(`\/clock\/index\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    new RegExp(`\/clock\/directory\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    new RegExp(`\/clock\/passcode\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    new RegExp(`\/clock\/home\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    new RegExp(`\/clock\/punch\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    new RegExp(`\/clock\/offline_punch\/${CLOCK_URI}`),
    new workbox.strategies.NetworkFirst(options)
)

// main css and js files
workbox.routing.registerRoute(
    /\/css\/clock.css/,
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    /\/js\/clock\/clock-scripts.js/,
    new workbox.strategies.NetworkFirst(options)
)

// static files
workbox.routing.registerRoute(
    /\.(?:js|css)$/,
    new workbox.strategies.CacheFirst({ cacheName })
)
workbox.routing.registerRoute(
    /\.(?:woff2|png|mp3)$/,
    new workbox.strategies.CacheFirst({ cacheName })
)

workbox.precaching.precacheAndRoute(precacheResources)

addEventListener('message', (event) => {
    if (event.data.type === 'GET_VERSION') {
        event.ports[0].postMessage(SW_VERSION)
    }
})

self.skipWaiting()
workbox.core.clientsClaim()
```

**workbox-window implementation**
```html
<script type="module">
        import { Workbox } from 'https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-window.prod.mjs'

        if ('serviceWorker' in navigator) {
            const wb = new Workbox(`${window.location.origin}/clock-service-worker.js`)
            wb.register()

            const getSWVersion = async () => {
                const swVersion = await wb.messageSW({ type: 'GET_VERSION' })
                console.log('Service Worker version: ', swVersion)
            }

            getSWVersion()
        }
</script>
```

**Comment by jeffposnick** [comment]
Constructing a `Workbox` instance and calling `wb.register()` while also calling `navigator.serviceWorker.register('...')` on another service worker is likely to confuse things; under the hood, `wb.register()` also calls `navigator.serviceWorker.register('...')`, so you're ending up with multiple registrations each time your page loads.

It seems like you really don't need `workbox-window` for your use case, which is communicating from a page to your service worker, and get a response.

You could do this without using `workbox-window` with the current code inside of your service worker with:

```
function getSWVersion() {
  const channel = new MessageChannel();
  return new Promise((resolve) => {
    channel.port1.onmessage = (event) => {
      resolve(event.data);
    };
    navigator.serviceWorker.controller.postMessage
      {type: 'GET_VERSION'}, [channel.port2]);
  });
});

// const version = await getSWVersion();
// console.log(version);
```

**Comment by GustavoSD** [comment]
> Constructing a `Workbox` instance and calling `wb.register()` while also calling `navigator.serviceWorker.register('...')` on another service worker is likely to confuse things; under the hood, `wb.register()` also calls `navigator.serviceWorker.register('...')`, so you're ending up with multiple registrations each time your page loads.
> 
> It seems like you really don't need `workbox-window` for your use case, which is communicating from a page to your service worker, and get a response.
> 
> You could do this without using `workbox-window` with the current code inside of your service worker with:
> 
> ```
> function getSWVersion() {
>   const channel = new MessageChannel();
>   return new Promise((resolve) => {
>     channel.port1.onmessage = (event) => {
>       resolve(event.data);
>     };
>     navigator.serviceWorker.controller.postMessage
>       {type: 'GET_VERSION'}, [channel.port2]);
>   });
> });
> 
> // const version = await getSWVersion();
> // console.log(version);
> ```

Thanks for the quick response.
And what if I want to show the version somewhere in the DOM?

**Comment by GustavoSD** [comment]
@jeffposnick You gave me a huge hint

> Constructing a Workbox instance and calling wb.register() while also calling navigator.serviceWorker.register('...') on another service worker is likely to confuse things; under the hood, wb.register() also calls navigator.serviceWorker.register('...'), so you're ending up with multiple registrations each time your page loads.

So I just removed the first sw registration and replaced the workbox-window implementation like this
```javascript
 <script type="module">
        import { Workbox } from 'https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-window.prod.mjs'

        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                const wb = new Workbox(`${window.location.origin}/clock-service-worker.js?clock_uri=${clock_uri}`, { scope: '/clock/' })
                wb.register().then((registration) => {
                    console.log('ServiceWorker registration successful: ', registration)
                }, (err) => {
                    console.log('ServiceWorker registration failed: ', err)
                })

                const getSWVersion = async () => {
                    const swVersion = await wb.messageSW({ type: 'GET_VERSION' })
                    console.log('Service Worker version: ', swVersion)
                }

                getSWVersion()
            })
        }
    </script>
```

I'm still implementing workbox-window, so the sw file remains the same.

Thanks so much for your help.

**Comment by jscheel** [comment]
So, I've run into this issue. I had one specific resource that was throwing an uncaught error when precaching, which would prevent the service worker from registering properly. I tracked it down to my ad blocker blocking the image (it was a twitter logo). it seems like failed requests should be caught, right?

**Comment by jscheel** [comment]
Specifically, this seems a bit of a trade-off here: https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-precaching/src/PrecacheStrategy.ts#L162. I understand wanting to throw an error if things are not working right, but shouldn't bad cache entries just fall back to using the network, instead of killing the install?

**Comment by jeffposnick** [comment]
> shouldn't bad cache entries just fall back to using the network, instead of killing the install?

That would constitute a significant breaking change. The guarantee that `workbox-precaching` offers is that if `install` succeeds, everything in the precache manifest was successfully added to the cache.

That can definitely be less than ideal if it never completes due to an extension intercepting the request, but using runtime caching is an alternative if your web app doesn't actually need the resources to be cached during installation.

**Comment by jscheel** [comment]
@jeffposnick that's a good point. It's definitely a wonky situation when an extension is causing the problem. I'll have to look at the runtime caching. Thanks!
