### ISSUE TITLE
Reassess scoping + naming of classes

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#288]
**Library Affected**:
Primarily the modules that expose a Plugin interface, but I'm writing about `sw-broadcast-cache-update` for now.

This came up in the context of @gauntface's comment at https://github.com/GoogleChrome/sw-helpers/pull/287#discussion_r105302593, where a change was made to expose two classes, `BroadcastCacheUpdate` and `BroadcastCacheUpdatePlugin`. When consumed via `importScripts()`, these are exposed in the `goog.broadcastUpdate` scope, leading to clumsy `goog.broadcastUpdate.BroadcastCacheUpdatePlugin` usage.

(This is not a problem when using the classes via ES2015 imports.)

Some options:

1. Drop the package-level scoping for classes, leading to `goog.BroadcastCacheUpdate` and `goog.BroadcastCacheUpdatePlugin`. If we did that, we would probably still want to add in that extra level of scoping for the non-class exports, like [`goog.broadcastCacheUpdate.cachedUpdatedMessageType`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-broadcast-cache-update/src/index.js#L68).

2. Keep the package-level scoping, but simplify the class names, leading to less redundancy. We might have `goog.broadcastUpdate.Base` for the standalone class, and `goog.broadcastUpdate.Plugin` for the subclass that acts as a `RequestWrapper` plugin. One drawback of this approach is degrading the ES2015 import experience, as folks would probably need to alias the exported names to make them less ambiguous (e.g. `import {Plugin as BroadcastCacheUpdatePlugin} from 'sw-broadcast-cache-update';`).

3. ??? I'm sure there are other suggestions.

**Comment by gauntface** [comment]
Personally in favor of option 1.

**Comment by jeffposnick** [comment]
We're going to go with:

`WorkboxSW` as the exported name from the `workbox-sw` bundle.

`workbox.<pkg>.<symbol>` for everything else.
