### ISSUE TITLE
Request headers are lost by PrecacheCacheKeyPlugin

### ISSUE THREAD

**Issue by henryso** [GoogleChrome/workbox#2884]
**Library Affected**: workbox-precaching

**Browser & Platform**: all browsers

**Issue or Feature Request Description**:
The headers of the original request are lost when `PrecacheCacheKeyPlugin.cacheKeyWillBeUsed` creates  a `new Request(cacheKey)`.  If the headers are passed as the second argument as `new Request(cacheKey, { headers : request.headers })` then they would be preserved.  If the headers are lost, then the `RangeRequestsPlugin` from the workbox-range-requests library is unable to handle ranged requests on precached data.  This is necessary to handle precached media destined for HTML5 audio and video elements.

**Comment by jeffposnick** [comment]
Thank you for reporting this!

**Comment by jeffposnick** [comment]
This is now fixed in https://github.com/GoogleChrome/workbox/releases/tag/v6.3.0
