### ISSUE TITLE
Aggregate es6 modules in workbox cli and build

### ISSUE THREAD

**Issue by mayeedwin** [GoogleChrome/workbox#2889]
For example;

```js
import {a, b , c,  d } from './lib'
```

by re-exporting modules in an `index.ts` in a root folder with many modules.

**Comment by jeffposnick** [comment]
Hello @mayeedwin!

The public entry point for `workbox-build` already does this: https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/src/index.ts

(There is no public interface for `workbox-cli`, as it's meant to be run from the command line and doesn't export anything.)

The modules within the `src/lib/` subfolders for each project are just imported internally, and are effectively "private". Could you explain the advantage of restructuring them in the manner you propose?

**Comment by mayeedwin** [comment]
For the `src/lib`, no significant perf or related improvement but it's more of a formatting improvement. Thanks.

**Comment by jeffposnick** [comment]
I'd prefer not to go ahead with this change, as we've just focused on exporting from and `index` for our public interfaces.

Thanks for the suggestion, though!

**Comment by mayeedwin** [comment]
Sounds good! Thanks!
