### ISSUE TITLE
@hapi/joi is deprecated, use joi

### ISSUE THREAD

**Issue by gempain** [GoogleChrome/workbox#2891]
**Library Affected**:
- workbox-build

**Browser & Platform**:

**Issue or Feature Request Description**:
It would be good to use `joi` instead of `@hapi/joi` which is deprecated.

Keep up the great work !

**Comment by jeffposnick** [comment]
We've migrated off of all flavors of `joi` in `v6.2.0-alpha.0`, and are instead using TypeScript type definitions to generate JSON schema and build time, which are then validated at runtime via https://ajv.js.org/

https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0

**Comment by gempain** [comment]
Awesome, thanks a lot for the feeback.
