### ISSUE TITLE
networkTimeoutSeconds: Slow loading of cached page.

### ISSUE THREAD

**Issue by GustavoSD** [GoogleChrome/workbox#2892]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*chromium-based browser*

**Issue or Feature Request Description**:
When the network request fails to respond within the time set in networkTimeoutSeconds and then it fallbacks to the cache, the cached file loads slower than when the app is offline and returns the same file from the cache.  I'll explain better:

This is my SW file

```javascript
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-sw.js');

const SW_VERSION = '2.0.0'
const CLOCK_URI = new URL(location).searchParams.get('clock_uri')

const precacheResources = [
    { url: `/clock/index/${CLOCK_URI}`, revision: null },
    { url: `/clock/directory/${CLOCK_URI}`, revision: null },
    { url: `/clock/passcode/${CLOCK_URI}`, revision: null },
    { url: `/clock/home/${CLOCK_URI}`, revision: null },
    { url: `/clock/punch/${CLOCK_URI}`, revision: null },
    { url: `/clock/offline_punch/${CLOCK_URI}`, revision: null },
    { url: '/css/clock.css', revision: null },
    { url: '/js/js.cookie-2.2.1.min.js', revision: null },
    { url: '/js/jquery-3.2.1.min.js', revision: null },
    { url: '/js/bootstrap.min.js', revision: null },
    { url: '/js/moment/moment.js', revision: null },
    { url: '/js/moment/locale/es.js', revision: null },
    { url: '/js/webcam/webcam.min.js', revision: null },
    { url: '/js/clock/clock-scripts.js', revision: null },
    { url: '/fonts/Material_Icons/MaterialIcons-Regular.woff2', revision: null },
    { url: '/fonts/Barlow_Condensed/barlow-condensed-v4-latin-600.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-600.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-700.woff2', revision: null },
    { url: '/fonts/Titillium_Web/titillium-web-v8-latin-regular.woff2', revision: null },
    { url: '/images/employee/placeholder.png', revision: null },
    { url: '/images/clock/turtle-connection.png', revision: null },
    { url: '/audio/punch-error.mp3', revision: null },
    { url: '/audio/punch-in.mp3', revision: null },
    { url: '/audio/punch-out.mp3', revision: null }
]

workbox.setConfig({ debug: true })

workbox.core.setCacheNameDetails({
    prefix: 'clock',
    suffix: 'v2',
    precache: 'precache',
    runtime: 'runtime'
})

const ignoreQueryStringPlugin = {
    cacheKeyWillBeUsed: async ({ request, mode, params, event, state }) => {
        curl = new URL(request.url)
        return curl.pathname
    }
}

const cacheName = workbox.core.cacheNames.precache
const options = {
    networkTimeoutSeconds: 1,
    cacheName,
    plugins: [ignoreQueryStringPlugin]
}

workbox.routing.registerRoute(
    ({ request }) => request.mode === 'navigate',
    new workbox.strategies.NetworkFirst(options)
)

// main css and js files
workbox.routing.registerRoute(
    /\/css\/clock.css/,
    new workbox.strategies.NetworkFirst(options)
)
workbox.routing.registerRoute(
    /\/js\/clock\/clock-scripts.js/,
    new workbox.strategies.NetworkFirst(options)
)

// static files
workbox.routing.registerRoute(
    /\.(?:js|css)$/,
    new workbox.strategies.CacheFirst({ cacheName })
)
workbox.routing.registerRoute(
    /\.(?:woff2|png|mp3)$/,
    new workbox.strategies.CacheFirst({ cacheName })
)

workbox.precaching.precacheAndRoute(precacheResources)

addEventListener('message', (event) => {
    if (event.data.type === 'GET_VERSION') {
        event.ports[0].postMessage(SW_VERSION)
    }
})

self.skipWaiting()
workbox.core.clientsClaim()
```

As you can see I'm using NetworkFirst with networkTimeoutSeconds (set to 1 second) for pages and specific CSS and JS files.

and I have a PHP file with HTML and JS, something like this (I won't paste the real content since I think it is not relevant, we just have to know that there's HTML and JS):

```HTML
<div>
HTML content
</div>
<script>
console.log('Hello World!')
// the rest of the script
</script>
```

Here's when I start describing the problem:

If I emulate a slow 3G connection with devtools, workbox says that the request timed out. So the timeout is working, it is in fact redirecting faster to the next page and returning a cached version of the page.
![timed out](https://user-images.githubusercontent.com/45019081/125862125-6bd364f9-b328-43c6-91e1-3130ce3aed6b.png)

But the problem is that when the page is returned from the cache, the console log in the script takes three seconds to display. I can see the page properly styled immediately, but it takes like three seconds to load the <script>.

When I go to the same page while offline, the <script> loads immediately at the same time as the rest of the content.

I don't understand why it takes more time for the script to be loaded when using networkTimeoutSeconds if the file is already cached, it does not have to be downloaded.

Is there something that I don't fully understand about cache and networkTimeoutSeconds?

**Comment by jeffposnick** [comment]
When the `networkTimeoutSeconds` elapses, the underlying `fetch()` request is not actually cancelled; it's just a signal to the service worker's code that the cached response should be passed to `event.respondWith()` as soon as possible, instead of waiting for the `fetch()` to resolve. If, during the time that the cached response is being asynchronously read the `fetch()` request **does** resolve, then there are various things that Workbox does under the hood (logging, running callbacks, updating the cache) that will start happening, and any of those might explain the slight delay in getting the cached response passed to `event.respondWith()`.

When you're completely offline, the `fetch()` will fail immediately, and the code that runs when the `fetch()` resolves will never run.

That would be my guess as to what you're seeing.
