### ISSUE TITLE
cacheName Property not available for NetworkOnly Strategy

### ISSUE THREAD

**Issue by Rainson12** [GoogleChrome/workbox#2898]
**Library Affected**: workbox-sw

**Browser & Platform**: all browsers

**Issue or Feature Request Description**:
According to the documentation there should be a property for NetworkOnly called `cacheName` (see https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-strategies.NetworkOnly#cacheName) in one of the previous versions it also seemed to be available however I cant access the property anymore. The error message the ide is throwing: 
``` 
{
	"resource": "/C:/develop/tmp/my-app/src/service-worker.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{ cacheName: string; plugins: BackgroundSyncPlugin[]; }' is not assignable to parameter of type 'NetworkFirstOptions'.\n  Object literal may only specify known properties, and 'cacheName' does not exist in type 'NetworkFirstOptions'.",
	"source": "ts",
	"startLineNumber": 37,
	"startColumn": 5,
	"endLineNumber": 37,
	"endColumn": 18
} 
```

For other strategies like Network First or Cache first this is available. Common sense would make the cacheName for NetworkOnly redundant but then I think the documentation on the website should be updated?

**Comment by jeffposnick** [comment]
Sorry about that—we fixed this in https://github.com/GoogleChrome/workbox/pull/2747 but were delayed in republishing the JSDocs. We'll get that taken care of.
