### ISSUE TITLE
Optional chaining issue with Node v10/v12 builds in release 6.2.0

### ISSUE THREAD

**Issue by kalbukov4265** [GoogleChrome/workbox#2902]
Library Affected:**workbox-expiration**

Browser & Platform:**all browsers**

Issue or Feature Request Description
When I start running build workbox got an error :

```
ERROR in ./node_modules/workbox-recipes/node_modules/workbox-expiration/models/CacheTimestampsModel.js 96:21
Module parse failed: Unexpected token (96:21)
You may need an appropriate loader to handle this file type.
|         const db = await this.getDb();
|         const entry = await db.get(CACHE_OBJECT_STORE, this._getId(url));
>         return entry?.timestamp;
|     }
|     /**
```

Can you fix optional chaining in "entry?.timestamp;" ?

**Comment by jeffposnick** [comment]
Thanks for pointing this out. Our intention wasn't to change the minimum required version of Node with the v6.2.0 release, so we'll likely get v6.2.1 out in the near future. (You should be fine sticking with v6.1.5 until then.)

Can you help us by sharing some more information about your build process? We use Babel to transpile our source code down to [Node v10.x compatibility](https://github.com/GoogleChrome/workbox/blob/6ec515276226de76594d58ed9909afe433cdf136/gulp-tasks/utils/node-projects-babel.config.json), but that only applies to our bundled releases. We might have a blind spot when it comes to transpiling code that is read unbundled via cross-dependencies in our monorepo, and if you shared your build process that would help us understand how to avoid this in the future.

**Comment by jeffposnick** [comment]
After a closer look at where this untranspiled code might have appeared, I believe that changing our project-level `tsc` configuration to use a more conservative `target` should resolve the issue.

**Comment by jeffposnick** [comment]
This should now be fixed in https://github.com/GoogleChrome/workbox/releases/tag/v6.2.2
