### ISSUE TITLE
Generating SW without having to write it to a file

### ISSUE THREAD

**Issue by cawa-93** [GoogleChrome/workbox#2915]
**Library Affected**:
workbox-build/generateSW

**Browser & Platform**:
NodeJS

**Issue or Feature Request Description**:
Please be able to receive the code of the generated Service Worker directly in runtime, without having to write it to a file.
```js
import {generateSW} from 'workbox-build'

devServer.onRequest('sw.js', () => {

  const code = await generateSW(...)
  return code

})
```
This is very useful when working with a dev server such as Vite or Snowpack.

**Comment by jeffposnick** [comment]
Could you clarify what the actual benefit would be? Are you hoping that this would lead to better performance, or developer ergonomics, or something else?

You should note that using a service worker with precaching tends not to work well with development environments, especially "live-reload" ones, as serving previously precached assets with a cache-first strategy defeats the purpose of live-reload. My general recommendation is to not enable service workers at all during day-to-day web app development, and only turn them on when you are specifically working on the caching functionality or are deploying to a staging environment.

Also, you can approximate your workflow right now by writing to a temporary file, along the lines of:

```js
// See https://github.com/sindresorhus/tempy
import tempy from 'tempy';
import {generateSW} from 'workbox-build'
import {readFileSync} from 'fs';

devServer.onRequest('sw.js', () => {
  const swDest = tempy.file({extension: 'js'});
  const code = await generateSW({
    swDest,
    // other options,
  });
  return readFileSync(swDest, {encoding: 'utf8'});
})
```

**Comment by cawa-93** [comment]
> turn them on when you are specifically working on the caching functionality 

Actually, this is one of the usage scenarios.

In my last project (this is an electron program) no precaching is used. The ServiceWorker work exclusively with runtime caching of requests to API and media streams.

Debugging this causes some pain, and all existing solutions what I know are "production-only". Like you, no one recommends using caching in a developer environment, but in some cases it is necessary.

I would like to write a simple plugin for a workbox that will generate an ServiceWorker in development runtime.

**Comment by jeffposnick** [comment]
If you're only using runtime caching, there's no **need** to use `generateSW`.

All of the config options in `generateSW` map directly to calls to the underlying Workbox runtime modules. If you're unsure about any mapping, you could take a look at [`sw-template.ts`](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/src/templates/sw-template.ts) and [`runtime-caching-converter.ts`](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/src/lib/runtime-caching-converter.ts).

For instance, if you're passing the following in:

```
generateSW({
  runtimeCaching: [{
    urlPattern: /api/,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'api-cache',
    },
  }, {
    urlPattern: ({request}) => request.mode ===  'navigate',
    handler: 'StaleWhileRevalidate',
  }],
  // ...other options...
});
```

then you could get the equivalent functionality with a hand-coded service worker:

```
import {registerRoute} from 'workbox-routing';
import {NetworkFirst, StaleWhileRevalidate} from 'workbox-strategies';

registerRoute(
  /api/,
  new NetworkFirst({cacheName: 'api-cache'})
);

registerRoute(
  ({request}) => request.mode = 'navigate',
  new StaleWhileRevalidate({cacheName: 'api-cache'})
);
```

If having to bundle that code prior to using it (which is something that `generateSW` would handle for you) is a stopper for you, then using the CDN copy of the pre-bundled Workbox runtime via [`workbox-sw`](https://developers.google.com/web/tools/workbox/modules/workbox-sw) is another alternative.
