### ISSUE TITLE
How to disable sourcemap using workbox-precaching?

### ISSUE THREAD

**Issue by frederikhors** [GoogleChrome/workbox#2925]
**Library Affected**:
*workbox-precaching*

**Issue or Feature Request Description**:
Using the below code:

```ts
import { precacheAndRoute } from 'workbox-precaching';

const files = [...]

precacheAndRoute([
	...files.map((f) => ({ url: f, revision: null })),
	{ url: '/index.html', revision: null }
]);
```

it works and creates a `service-worker.js` file correctly.

Is there a way to **disable** sourcemap creation?

I was using `workbox-cli` in another project and there was an option for this:

```js
module.exports = {
  // ...
  // skipWaiting: true,
  // clientsClaim: true,
  sourcemap: false // <-----
}
```

Can I do this with `workbox-precaching`?

**Comment by jeffposnick** [comment]
`workbox-precaching` is the runtime library that handles routing and caching for all of the URLs passed in to `precacheAndRoute()`. It is not involved in the compilation process at all, and therefore has no direct interaction with sourcemap creation.

Only the build tools (`workbox-build`, `workbox-webpack-plugin`, and `workbox-cli`) might create a sourcemap, depending on which one you're using and how it's configured.

(Also, as an aside, your `...files.map((f) => ({ url: f, revision: null }))` makes me a bit uneasy. It means that all of the items in your `files` array will be cached once by each client following the initial installation, and then reused indefinitely, with no checks for updates. Unless you're sure that the each URLs in `files` will never be updated, that's probably not the behavior you want.)

**Comment by frederikhors** [comment]
> Unless you're sure that the each URLs in files will never be updated

I have hash in file name.
