### ISSUE TITLE
Recommend workbox-cli for retrieving a local copy of the built libraries

### ISSUE THREAD

**Issue by FlyveHest** [GoogleChrome/workbox#2926]
It looks like there hasn't been posted any built versions of workbox since the 6.x branch was started?

The documentation specifies that if you should want to run from a local installation and not CDN, you can download from the releases page, but I can't find any built versions since 5.1.4, only source downloads.

**Comment by jeffposnick** [comment]
Sorry about that—the pipeline that uploaded the bundles to GitHub was a bit flaky, and the same functionality is available from `workbox-cli` via:

```sh
npx workbox-cli copyLibraries /path/to/parent/dir 
```

Can you tell me where we still refer to the GitHub release downloads in the docs? I'll get it updated to refer to `workbox-cli` instead.

**Comment by FlyveHest** [comment]
I found the references here, https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn
