### ISSUE TITLE
Webpack InjectManifest prod build Terser error.

### ISSUE THREAD

**Issue by muradsofi** [GoogleChrome/workbox#2930]
**Library Affected**:
InjectManifest

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:
When I build my ServiceWorker via Webpack in development mode everything works fine but when I want to build for a prod  I saw a Terser error in my console. (Unexpected token: punc (:))

I use i18n in my ServiceWorker when I comment i18n import everything works fine. 

Any idea why this compile error happens?

**Comment by jeffposnick** [comment]
I'm sorry, but I'm not familiar with that specific build setup.

Can you share a link to a GitHub repo with a project that reproduces the problem? Or alternatively, reproduce the issue in an environment like https://codesandbox.io/?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
