### ISSUE TITLE
workbox-background-sync should allow SyncManager.register options to be set

### ISSUE THREAD

**Issue by StephanBijzitter** [GoogleChrome/workbox#2937]
**Library Affected**:
workbox-background-sync

**Browser & Platform**:
All supporting browsers (currently only Chromium-based)

**Issue or Feature Request Description**:
The [options](https://developer.mozilla.org/en-US/docs/Web/API/SyncManager/register) for `SyncManager.register` used by `workbox-background-sync` are currently left to defaults. However, I would like to be be able to change these options. 

The interface could look like this:
```ts
export interface QueueOptions {
  onSync?: OnSyncCallback;
  maxRetentionTime?: number;
  syncRegistrationOptions?: {
      id?: never;
      allowOnBattery?: boolean;
      idleRequired?: boolean;
      maxDelay?: number;
      minDelay?: number;
      minPeriod?: number;
      minRequiredNetwork?: 'network-any' | 'network-offline' | 'network-online' | 'network-non-mobile';
  };
}
```

Where `id` is forced by the plugin to be ``${TAG_PREFIX}:${this._name}``, as is the current tag value. I'd re-use the typings from `lib.dom.ts` but it doesn't include the types for these options yet.

**Comment by jeffposnick** [comment]
I am not sure that the MDN documentation is correct; the [specification](https://wicg.github.io/background-sync/spec/#syncmanager) says that the `register()` method of a `SyncManager` only takes a single `string` parameter representing the `tag`, which is what `workbox-background-sync` passes:

https://github.com/GoogleChrome/workbox/blob/03055e64014a46f6cc977a3a50ad814c6409d36a/packages/workbox-background-sync/src/Queue.ts#L352-L354

Given that some of those options look like they're associated with `PeriodicSyncManager`, I think there was a mix-up when these MDN docs were created. I'll follow up with the MDN folks.

**Comment by jeffposnick** [comment]
C.f. https://github.com/mdn/content/issues/8893

**Comment by StephanBijzitter** [comment]
O wow, guess there's a first time for everything :-D

Thanks for looking into it!
