### ISSUE TITLE
Large size in cache storage

### ISSUE THREAD

**Issue by fisherspoons** [GoogleChrome/workbox#2938]
**Library Affected**:
workbox-cli

**Browser & Platform**:
Mac os / Chrome 93.0.4577.63

**Issue or Feature Request Description**:
Hello I have a problem, why the size of the cache storage does not match the real size of the cached files? That's all that I have from the created cache and if you count it, the size will be equal to half of the total storage, I checked it in incognito mode.

<img width="850" alt="Снимок экрана 2021-09-07 в 20 31 28" src="https://user-images.githubusercontent.com/54633510/132386852-3c2eec9d-f8b5-4a10-bd2b-6dd41e4c27bd.png">
<img width="842" alt="Снимок экрана 2021-09-07 в 20 31 50" src="https://user-images.githubusercontent.com/54633510/132386884-61ea0d29-b130-43bf-bf6f-4930e39ba110.png">

and total
<img width="400" alt="Снимок экрана 2021-09-07 в 20 32 20" src="https://user-images.githubusercontent.com/54633510/132386954-7df0d90a-ccdc-47b9-82b5-2113f8a4c05c.png">

**Comment by coderyyx** [comment]
Have the same problem

**Comment by fisherspoons** [comment]
And I noticed a problem, I commented out everything except the strategy for fonts, while everything works fine even when the page is reloaded, but if, for example, I turn on the strategy for images and start reloading the page, then the cache size in the storage starts to grow.

It's fonts

```
workbox.routing.registerRoute(
    ({request}) => request.destination === "font",
    new workbox.strategies.CacheFirst({
        cacheName: FONT_CACHE,
        plugins: [
            new workbox.expiration.ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
                maxEntries: 10,
                purgeOnQuotaError: true,
            }),
        ],
    })
);
```

It's styles

```
workbox.routing.registerRoute(
    ({request, url}) => request.destination === 'style' && !(url.pathname.startsWith('/bundles/') || url.pathname.startsWith('/assets/vendor/') || url.pathname.startsWith('/admin/')),
    new workbox.strategies.StaleWhileRevalidate({
        cacheName: STYLE_CACHE,
        plugins: [
            new workbox.cacheableResponse.CacheableResponsePlugin({
                statuses: [0, 200]
            }),
            new workbox.expiration.ExpirationPlugin({
                maxEntries: 15,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
                purgeOnQuotaError: true,
            }),
        ],
    })
);
```

fonts  and styles
<img width="857" alt="Снимок экрана 2021-09-08 в 10 12 26" src="https://user-images.githubusercontent.com/54633510/132463183-61806017-53ac-4c2d-83bd-00daba9fbde4.png">

<img width="853" alt="Снимок экрана 2021-09-08 в 10 11 40" src="https://user-images.githubusercontent.com/54633510/132463064-afb03204-0369-4bb6-a55e-a7e577207d3f.png">

fonts: 52,616 + 53,716 = 106,332
styles: 132,822 + 73,819 + 10,078 = 216,719
total: 106,332 + 216,719 = 323,051
It's first load storage
<img width="398" alt="Снимок экрана 2021-09-08 в 10 12 58" src="https://user-images.githubusercontent.com/54633510/132463250-45862bd7-a593-4616-93c1-28a2fc389f5c.png">


But if I reload this page
total: 323,051 + previous styles weight 216,719 = 539,77
<img width="497" alt="Снимок экрана 2021-09-08 в 10 14 18" src="https://user-images.githubusercontent.com/54633510/132463421-ab69c743-954e-4aa7-9e77-34407c5ab118.png">

**Comment by jeffposnick** [comment]
Thanks for letting us know—I can reproduce this by, for example, visiting https://jeffy.info/2021/07/26/precaching-vs-runtime-caching.html in an Incognito window and repeatedly reloading the page, with the "Cache storage" value increasing by around 15kb each time I reload, despite the fact that there aren't any additional assets being cached.

My guess is that it's a cosmetic bug affecting Chrome's DevTools interface, where overwriting a previously cached entry just adds the new size of the entry to the running total, without also decreasing the total by the size of the previous entry.

I'll file a bug with the DevTools team to investigate.

**Comment by jeffposnick** [comment]
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1247750

You should "Star" that bug for updates. I don't think there's anything we can do on the Workbox side of things, so I'm going to close this issue.
