### ISSUE TITLE
Workbox.update() may fail to return a promise

### ISSUE THREAD

**Issue by joshkel** [GoogleChrome/workbox#2939]
**Library Affected**:

workbox-window

**Browser & Platform**:

All browsers

**Issue or Feature Request Description**:

The `Workbox.update()` method may fail to return a promise if registering the service worker had failed. The cause appears to be https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues/71.

A workaround is to add an extra `await` (e.g., `await true;`) within the [`if (!this._registration)` block](https://github.com/GoogleChrome/workbox/blob/669df5824286462de9baa9cc19162c067291bd15/packages/workbox-window/src/Workbox.ts#L209). The bug only manifests if Babel's @babel/plugin-transform-classes is enabled.

Alternatively, since babel-plugin-transform-async-to-promises has some open correctness issues and hasn't received updates for a couple of years, I wonder if it would be better to switch to a different async plugin ([like Babel's?](https://babeljs.io/docs/en/babel-plugin-proposal-async-generator-functions)).

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
