### ISSUE TITLE
Why is PrecacheEntry interface not exported?

### ISSUE THREAD

**Issue by RandomEngy** [GoogleChrome/workbox#2952]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The "precache" function takes this type as a parameter: `entries: Array<PrecacheEntry | string>`. However the PrecacheEntry interface [doesn't seem to be exported from the workbox-precaching package](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-precaching/src/index.ts).

When I try to run

`import { PrecacheEntry } from "workbox-precaching";`

It tells me:

> Module '"workbox-precaching"' has no exported member 'PrecacheEntry'.

**Comment by jeffposnick** [comment]
Sorry about that—similar to https://github.com/GoogleChrome/workbox/issues/2770, I think we need to re-export our interfaces from https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-precaching/src/_types.ts

**Comment by RandomEngy** [comment]
Same for NetworkFirstOptions in workbox-strategies . Might be worth it to just go over all the interfaces that are on exported functions.

(edit) It's available when importing from `"workbox-strategies/NetworkFirst"` but not when importing from `"workbox-strategies"`
