### ISSUE TITLE
How to change the precache name via the WorkboxPlugin?

### ISSUE THREAD

**Issue by clickwithclark** [GoogleChrome/workbox#2953]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
Google Chrome 

I have the following set up for the plugin in my webpack config file and it works great except I was looking for a way to change the precache name, the runtime change name was straight from the docs but I can't seem to find a way with the plugin. If there is an alternative method please let me know. I can't seem to on my own.

Thanks

```js
  new WorkboxPlugin.GenerateSW({
  
      clientsClaim: true,
      skipWaiting: true,
      maximumFileSizeToCacheInBytes: 5242880,
      cleanupOutdatedCaches: true,
      mode: 'production',
  
      runtimeCaching: [
        {
          // Match any request ends with .png, .jpg, .jpeg or .svg.
          urlPattern: /.(?:png|jpg|jpeg|svg)$/,

      
          handler: 'StaleWhileRevalidate',

          options: {
       
            cacheName: 'images',

            // Only cache 10 images.
            expiration: {
              maxEntries: 10,
            },
          },
        },
      ],
    }),
  ],
```
trying to change the workbox-precache part
![precachename](https://user-images.githubusercontent.com/20617584/136176277-d00c3086-8ffc-44da-a374-26bc136f5e8c.png)

**Comment by jeffposnick** [comment]
You can control the prefix of the precache name via the `cacheId: 'my-prefix'` [parameter](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#:~:text=service%20worker%20bundle.-,cacheId,-Optional).

The `GenerateSW` build tool does not allow you to change the entire precache name, though.

If there's a use case that requires letting you control the full precache name while using `GenerateSW`, please provide more details and we can reopen this issue and evaluate the request.
