### ISSUE TITLE
Precache is always reloaded completely, although assets have not changed

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2954]
**Library Affected**:
"workbox-precaching": "^6.3.0",

**Browser & Platform**:
any

**Issue or Feature Request Description**:
Every time the service worker is updated, absolutely all precache elements are re-requested again, although they have not changed and their hash sum too

webpac.config.js

```js
const integrityManifestTransform = (originalManifest, compilation) => {
    const warnings = [];
    const manifest = originalManifest.map((entry) => {
        const asset = compilation.getAsset(entry.url.replace(ASSETS_PATH, ''));
        entry.integrity = ssri.fromData(asset.source.source(), { algorithms: ['sha1'] }).toString();
        return entry;
    });

    return { warnings, manifest };
};

new InjectManifest({
    swSrc: './src/sw/sw.ts',
    swDest: 'sw.js',
    manifestTransforms: [integrityManifestTransform],
}),
```

Service worker
```js
self.VERSION = APP_VERSION;

setCacheNameDetails({
    prefix: 'myApp',
    suffix: 'my_app',
    precache: 'assets',
    runtime: 'runtime',
});

precacheAndRoute(self.__WB_MANIFEST);

void self.skipWaiting();
clientsClaim();
```

![image](https://user-images.githubusercontent.com/8055157/136400800-fc506a0e-3cce-44eb-b6fe-80fd9c3f2e4a.png)

change only `self.VERSION = APP_VERSION;`

![image](https://user-images.githubusercontent.com/8055157/136401295-84efc84a-5419-480e-a45f-7ffa9d367ac0.png)

as you can see - hash-sums in assets name are the same

**Comment by jeffposnick** [comment]
Hello @budarin—the URLs that are shown being precached in each screenshot are different.

The prefix of each URL in the first screenshot is `https://web_app.localhost/1.0.508/` and the prefix of each URL in the second screenshot is `https://web_app.localhost/1.0.509/`.

When `workbox-precaching` sees a different set of URLs from what was previously precached, it will download the new URLs during installation, and then delete the old cached entries once the new service worker activates.

**Comment by budarin** [comment]
Sorry, its my false
