### ISSUE TITLE
Missing 'exclude' option in workbox-config

### ISSUE THREAD

**Issue by lukeromanowicz** [GoogleChrome/workbox#2956]
**Library Affected**:
workbox-build

**Browser & Platform**:
all platforms

**Issue or Feature Request Description**:
`exclude` is not supported by [workbox-config](https://github.com/GoogleChrome/workbox/blob/74f01e3710de8d862caf35c4d1b5e605fbc8d3c4/packages/workbox-build/src/schema/GenerateSWOptions.json).

According to the [docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW?hl=en) I should be able to use it.

**Comment by jeffposnick** [comment]
`exclude` is a supported option in `workbox-webpack-plugin`'s `GenerateSW` mode:

https://github.com/GoogleChrome/workbox/blob/74f01e3710de8d862caf35c4d1b5e605fbc8d3c4/packages/workbox-build/src/schema/WebpackGenerateSWOptions.json#L41-L44

It's not supported in `workbox-build`'s `generateSW` mode, though. You linked to the `workbox-webpack-plugin` docs.

`workbox-build` gets its list of files to include or exclude via `glob` patterns, and `include`/`exclude` via RegExps is a `webpack`-ism.
