### ISSUE TITLE
The swSrc file refers to a sourcemap that can't be opened

### ISSUE THREAD

**Issue by RandomEngy** [GoogleChrome/workbox#2957]
**Library Affected**:
workbox-build

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

I'm running injectManifest in development mode, but it's erroring out:

> The swSrc file refers to a sourcemap that can't be opened: ENOENT: no such file or directory, open 'D:\a\_work\1\s\CacheStatus.js.map'

I checked the swSrc file and the first sourcemap is indeed `//# sourceMappingURL=CacheStatus.js.map` . However the file being injected is output to a folder without the sourcemaps beside them. This was working fine in v4, but is broken in v6. Can we update the behavior to ignore the invalid sourcemap and continue with the manifest injection? Or add an option to do so?

https://github.com/GoogleChrome/workbox/blob/8afb37210d8f4fe62847f4e80e42fc95bced4895/packages/workbox-build/src/inject-manifest.ts#L185

**Comment by jeffposnick** [comment]
I'm not entirely sure why that logic would have changed between v4 and v6, but if you have a development set up that's broken by this exception, I think we can "demote" it to be a warning instead.

**Comment by RandomEngy** [comment]
Awesome! If I submitted a PR would it help make it happen faster?

**Comment by jeffposnick** [comment]
The logic is a little funky, so I'm fine with writing the PR. Stay tuned.
