### ISSUE TITLE
ERROR in Multiple instances of self.__WB_MANIFEST were found in your SW source. Include it only once

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2958]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
any

**Issue or Feature Request Description**:
 I'm trying to post message the cache update status to clients in the `cacheDidUpdate` plugin. To do this, I need to know the total number of items in the cache.
When trying to get it using `self.__WB_MANIFEST.length`  - I get this error

```js
let i = 0;

export const cacheDidUpdate: CacheDidUpdateCallback = async (params: CacheDidUpdateCallbackParam): Promise<void> => {
    i++;
    const count = self.__WB_MANIFEST.length;
    params.event.waitUntil(async () => {
        await self.clients
            .matchAll({
                includeUncontrolled: true,
                type: 'window',
            })
            .then((clients) => {
                // eslint-disable-next-line fp/no-loops
                for (const client of clients) {
                    client.postMessage({
                        type: SW_CACHE_UPDATE_PROGRESS,
                        count: (i / count) * 100,
                    });
                }
            });
    });
};
```

**Comment by jeffposnick** [comment]
Right, there's only meant to be a single instance of `self.__WB_MANIFEST` in your `swSrc`, and the `injectManifest` build tool replaces that symbol with an array containing the manifest. The injected precache manifest can potentially be large, and storing multiple copies of the same large array inside the same script isn't necessary.

If you want to reference the precache manifest from multiple places in your code, you can do something like:

```js
const precacheManifest = self.__WB_MANIFEST;

precacheAndRoute(precacheManifest);

const manifestLength = precacheManifest.length;
// Do something with manifestLength.
```

**Comment by budarin** [comment]
@jeffposnick thanks!
