### ISSUE TITLE
Recipe for adding COEP/COOP headers

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2963]
Low-priority, but it might be useful to have this documented for Workbox users. CC: @malchata 

C.f. https://stackoverflow.com/questions/69468591/using-service-worker-to-enable-coop-coep-headers-security-concerns

This would look something like:

```js
import {registerRoute} from "workbox-routing";
import {NetworkOnly} from "workbox-strategies";
import * as navigationPreload from "workbox-navigation-preload";

navigationPreload.enable();

const headersPlugin = {
  handlerWillRespond: async ({response}) => {
    const headers = new Headers(response.headers);
    headers.set("Cross-Origin-Embedder-Policy", "require-corp");
    headers.set("Cross-Origin-Opener-Policy", "same-origin");

    return new Response(response.body, {
      headers,
      status: response.status,
      statusText: response.statusText,
    });
  },
};

// Swap in NetworkOnly, StaleWhileRevalidate, etc. as needed.
const strategy = new NetworkOnly({
  plugins: [headersPlugin],
});

registerRoute(
  ({request}) => ["document", "iframe", "worker"].includes(request.destination),
  strategy
);

```

**Comment by leopsidom** [comment]
Is it possible to set up the interception via the `generateSW` option ? I'm trying to use https://github.com/antfu/vite-plugin-pwa to generate the service worker which provides a workbox configuration option, but having an issue figuring out how to configure the plugin via the `GenerateSWOptions` object.

**Comment by jeffposnick** [comment]
I personally like using `injectManifest` mode for this sort of customization ([here's an example](https://github.com/jeffposnick/yt-playlist-notifier/blob/9c805c5da33f674ce3f187d30f5505616e6610d4/vite.config.ts) with `vite-plugin-pwa`), but if you wanted to do something similar using `generateSW`, you can with the following Vite config:

```js
const headersPlugin = {
  handlerWillRespond: async ({response}) => {
    const headers = new Headers(response.headers);
    headers.set("Cross-Origin-Embedder-Policy", "require-corp");
    headers.set("Cross-Origin-Opener-Policy", "same-origin");

    return new Response(response.body, {
      headers,
      status: response.status,
      statusText: response.statusText,
    });
  },
};

export default defineConfig({
  plugins: [
    VitePWA({
      workbox: {
        runtimeCaching: [
          {
            urlPattern: ({request}) =>
              ['document', 'iframe', 'worker'].includes(request.destination),
            handler: 'NetworkOnly',
            options: {
              plugins: [headersPlugin],
            },
          },
        ],
      },
    }),

    // Other config goes here.
```

**Comment by leopsidom** [comment]
Nice, this seems to work. Thanks for the suggestion.  But I'm having one issue with my web worker script, i.e the script that gets loaded via `new Worker('./webworker.js')`. From my network tab it appears that the request is served by service worker. However, the response headers do not seem to be modified. It seems the request is not going through the plugin either, as when I add a log in `urlPattern` like below:

```
urlPattern: ({request}) => {
  console.log(request)
  return ['document', 'iframe', 'worker'].includes(request.destination)
}
```
I don't see `.../webworker.js` in the log entry. Do you know how worker script is treated differently in service worker ?

**Comment by leopsidom** [comment]
I think I figured it out. `webworker.js` was precached and serving it with a different header like `Cross-Origin-Embedder-Policy` did not trigger an update. After manually deleting the precache and reinstalling the service worker, it now worked..

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
