### ISSUE TITLE
workbox-cli copyLibraries downloads old versions

### ISSUE THREAD

**Issue by DrJume** [GoogleChrome/workbox#2964]
**Library Affected**:
`workbox-cli`

**Browser & Platform**:
Node.js v14.18.1

**Issue or Feature Request Description**:
When using `workbox-cli copyLibraries`, some files are not the latest workbox version.

**Comment by jeffposnick** [comment]
`workbox-cli` has a version number, and it will copy over the libraries with the matching version number to a local directory. If you're seeing that the latest Workbox libraries aren't copied over, make sure that you've updated your copy of `workbox-cli` to the latest release, and try again.

Alternatively, you can run `workbox-cli` via `npx`, and it will execute the latest release automatically:

```sh
[/tmp]$ npx workbox-cli copyLibraries .
The Workbox libraries were copied to /private/tmp/workbox-v6.3.0
```

**Comment by DrJume** [comment]
Sadly that's not the case. Running `npx workbox-cli copyLibraries dist/pwa/` creates a workbox folder containing scripts, which are still annotated with i.e. "workbox:precaching:6.2.4" in the source.

**Comment by DrJume** [comment]
The only script whose source contains the current `6.3.0` version tag is `workbox-sw.js`.

**Comment by jeffposnick** [comment]
Sorry about that confusion—there might be a bit of a race condition in our `lerna` setup between when that inline versioning info gets updated via our release process and when the libraries are published to `npm`.

Those inline strings (unlike the `package.json` fields) are not used for semver and are purely informative, and I just double-checked the files pulled in by `npx workbox-cli copyLibraries` to confirm that they include the expected code for the `6.3.0` release.
