### ISSUE TITLE
Support for Targeted Cache-Control and Cache-Status

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2965]
"[New HTTP standards for caching on the modern web](https://httptoolkit.tech/blog/status-targeted-caching-headers/)" describes two new HTTP headers related to caching that are on the path towards standardization. I wanted to open this issue to brainstorm about those response headers could be used within the context of a service worker, and how Workbox could best support them via [plugins and custom strategies](https://web.dev/extending-workbox/) if they catch on.

Feel free to add your thoughts—this is just based on my initial reading of the blog post describing them.

## Targeted Cache-Control
[Targeted `Cache-Control`](https://httptoolkit.tech/blog/status-targeted-caching-headers/#how-does-targeted-cache-control-work), perhaps via `SW-Cache-Control`, is a response header that seems like it could be a useful signal for configuring Workbox's caching behavior via server-side logic, as opposed to hardcoded options inside the service worker.

Folks have made [related](https://github.com/GoogleChrome/workbox/issues/131) [requests](https://github.com/GoogleChrome/workbox/issues/1880) around Workbox auto-configuring its behavior based on the `Cache-Control` header in the past, but we have decided not to do that, since developer intent when setting `Cache-Control` is ambiguous when it comes to service worker caching. `SW-Cache-Control` removes this ambiguity.

### Reading SW-Cache-Control
The fields inside a hypothetical `SW-Cache-Control` header could be parsed and used to configure the behavior of a custom `Strategy` subclass. The implementation of that `Strategy` would mirror some of the logic that's currently in place via our "standard" `Strategy` classes, like `NetworkFirst` or `StaleWhileRevalidate`, along with the behavior of our plugins like `ExpirationPlugin`, but not necessarily use them directly.

I think that instead of using, e.g., `ExpirationPlugin` (which relies on `IndexedDB` for storing out-of-band state information related to expiration) we instead just relied on fields present in the HTTP response headers, like `Date:` and `SW-Cache-Control`, to determine how the `Strategy` behaved. (This would mean that the strategy wouldn't be useful for `no-cors` requests that lead to [opaque responses](https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses).)

The main complication I can think of is that we're talking about `SW-Cache-Control` as a _response_ header, so it's not something that could be used as criteria for routing requests to the hypothetical custom strategy. So there would need to be some routing coordination between the service worker and servers in place to ensure that if a request is handled by `SWCacheControlStrategy`, the eventual response will actually have `SW-Cache-Control` set. `SWCacheControlStrategy` would need to have some fallback logic in place where, e.g., if there isn't already a locally cached response with `SW-Cache-Control` set, it would just unconditionally do the equivalent of `fetch(event.request)`.

### Writing SW-Cache-Control
I _think_ that targeted `Cache-Control` can also be set on outgoing requests, but it's not clear how useful that would be. Most of the discussion in the [blog post](https://httptoolkit.tech/blog/status-targeted-caching-headers/#how-will-targeted-cache-control-help) is around using it as a response header.

## Cache-Status
`Cache-Status` is used to report back which caching proxies a response has passed through, and a hop along the way can add some metadata to the header to reflect how a response was cached.

### Reading Cache-Status
A `cacheKeyWillBeUsed` plugin could check for the presence of a `key` in `Cache-Status` set by a previous hop in the caching chain, and use that as a signal to use a different URL as a cache key when saving the response to cache storage.

This might be a compelling use case, but would depend on how common it is to configure caching proxies to use different keys, and whether the same logic that determines whether a CDN uses a different cache key should also apply to a service worker.

### Writing Cache-Status
It would be straightforward to create a Workbox plugin that implemented `cacheWillUpdate` and added in an entry to `Cache-Status` that reflected the operation that Workbox was about to perform. There are some standard metadata fields, like `key`, that could be set to reflect the actual URL that's being used as the cache key for a given response (in the case where a `cacheKeyWillBeUsed` plugin changes that key).

I'm not sure that this information would be _useful_, though, as the service worker is always the "last hop" in the caching chain, and there's nothing downstream that would end up reading this metadata that Workbox added.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
