### ISSUE TITLE
Delayed revalidation in StaleWhileRevalidate

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2966]
**Library Affected**:
_workbox-strategies_

When using `StaleWhileRevalidate`, some developers might want to delay the revalidation, perhaps on the order of a few seconds, to attempt to minimize contention with any other strategies that need to hit the network immediately afterward. (This might happen when, e.g., using `workbox-streams` and a `StaleWhileRevalidate` => `NetworkFirst` sequence.)

We could add an optional `revalidationDelayInSeconds` parameter that could be passed as an option to the `StaleWhileRevalidate` constructor to accomplish this.

[Priority hints](https://developers.google.com/web/updates/2019/02/priority-hints), if they're ever widely supported, might also be useful in this context.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
