### ISSUE TITLE
Is there any type definition for workbox-sw v6

### ISSUE THREAD

**Issue by shmilyoo** [GoogleChrome/workbox#2967]
I noticed that the highest version of type definition in @types is 4.3.2.
When developing, it is troublesome that the api in the code hint and the actual version do not match

**Comment by jeffposnick** [comment]
There isn't, no. We haven't converted `workbox-sw` to TypeScript, and folks from the community who publish those unofficial types have apparently not updated it.

What I'd recommend, if you're using TypeScript, is not to use `workbox-sw` at all. Instead, import whatever Workbox bits you're using as ES modules, and then bundle up your code into a production-ready service worker.

This is the model described at https://developers.google.com/web/tools/workbox/guides/using-bundlers and it works equally well with TypeScript.

**Comment by shmilyoo** [comment]
It works, thank you!

My original scenario was to use cdn to reduce the package size. I provide sw scripts for my multiple business systems, and the scripts are not necessarily the same for each system, so the package products are stored in the database for the business systems to call.
After using npm to bring it in, I had to store each packaged product in our static resource service and then write just one line in each business system's sw script : 
```
 importScripts(codeUrl) 
```

Still hoping for an official work-sw definition later. 
Thanks

**Comment by jeffposnick** [comment]
Using `workbox-sw` will increase total runtime size vs. using ES module imports and producing a tree-shaken final bundle.

When using `workbox-sw` and referencing, e.g., `workbox.strategies.NetworkFirst`, you'll end up downloading the entire `workbox-strategies` bundle in the background, including code for strategies that you are not using. When using ES modules and an optimizing bundler, your final bundle will only include the code for `NetworkFirst` and a minimal set of common code used throughout Workbox.
