### ISSUE TITLE
workbox-broadcast-update does not work inside android webview

### ISSUE THREAD

**Issue by heitorpr** [GoogleChrome/workbox#2968]
**Library Affected**:
workbox-broadcast-update (v6.3.0)

**Browser & Platform**:
Webview for Android

**Issue Description**:
I have a PWA application that is also inside an android webview in my app, and the broadcast update plugin does not send the update event with the StaleWhileRevalidate strategy. The exactly same build of PWA app with react performs diferently inside the webview and directly on chrome (on Chrome it works just fine).

```javascript
    navigator?.serviceWorker?.addEventListener('message', async event => {
      if (event.data.meta === 'workbox-broadcast-update') {

        /* eslint-disable */
        if (confirm(`New app update is available!. Click OK to refresh`)) {
          window.location.reload();
        }
      }
    });
```

I added just a confirm call to test and on chrome it is been called but inside the webview it is not called. The confirm is just an extra test, The usual was to update the views with the new data, that works on chrome browser too, but also not in webview

The code to register the route is this one:

```javascript
registerRoute(
  ({ url }) => url.pathname.startsWith('/my-url/v1/something'),
  new StaleWhileRevalidate({
    plugins: [new BroadcastUpdatePlugin()]
  })
```

I don't know if there is an issue at all, or the webview part is bad configured perhaps? But the service-worker and offline caching working just fine, only the broadcast update is not performing well.

On android side is just a webview

```xml
    <WebView
        android:id="@+id/webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />
```

```kotlin
        webview.settings.javaScriptEnabled = true
        webview.settings.domStorageEnabled = true
        webview.settings.setGeolocationEnabled(true)
        webview.settings.mediaPlaybackRequiresUserGesture = false
        webview.loadUrl(url)
```

**Comment by jeffposnick** [comment]
CC: @andreban, my colleague whom I normally turn to for questions related to Android & the web. He might have some idea as to what's going on.

**Comment by heitorpr** [comment]
Hello! updating the issue with the working example problem, these both are public repos in my account:
- pwa: https://github.com/heitorpr/react-cra-shell
- android: https://github.com/heitorpr/androidwebviewstaletest

PWA published in firebase hosting: https://react-cra-shell.web.app/

the api is updating the message bellow the button

![image](https://user-images.githubusercontent.com/6535255/140833168-0c555723-fc69-44d4-a251-3d31f8544b3a.png)

"Practicality beats purity."

It is the zen api from github.

If you open the link you will see the workbox being stalling after that the request to zen api, if you quick again it will start to use the local cache instead of api response, when the response from backend changes the interface changes too to another message "O texto foi atualizado"

Unfortunatelly to test you will have to build the app locally, I should publish it on app-store testing, but it take some time...

Running it on webbroswer the broadcast update works just fine. But inside the app the text  "O texto foi atualizado". Never appears, which indicates the webview is not receiving the workbox-broadcast-update event...

**Comment by andreban** [comment]
🇧🇷  Oi Heitor!

I can see the message when using the example PWA you shared using WebView implementation in this gist: https://gist.github.com/andreban/40b22d321e4fc2de3f05f7753b8cd927.

![Screenshot_20211109-110133](https://user-images.githubusercontent.com/1733592/140912774-d45a67f1-c131-4ed9-bab8-7ca74fdbeb62.png)


The sample is a bit more involved than the one you shared, as it implements `onRenderProcessGone()`, which enables the app to recover to a potential WebView crash and also ensures that external links are handled in the user's browser.

However, I think that what may be making the difference here is the call to `webSettings.setDatabaseEnabled(true);`. Can you try this one out in your Android sample?

**Comment by heitorpr** [comment]
Still not working for me, I even copyed the entire jist in a new activity and tried it 😢 . I'm trying to figure out why

**Comment by heitorpr** [comment]
Maybe a missing permission?

**Comment by andreban** [comment]
> Maybe a missing permission?

The only permission added to the Android Manifest is: 

```xml
<uses-permission android:name="android.permission.INTERNET"/>
```

I have [added the full Android Manifest to the gist,](https://gist.github.com/andreban/40b22d321e4fc2de3f05f7753b8cd927#file-androidmanifest-xml) just in case.

Can you share details on the device model / WebView version?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
