### ISSUE TITLE
Better errors for a missing self.__WB_MANIFEST

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2969]
**Library Affected**:
`workbox-webpack-plugin`, `workbox-build`

I've heard from new developers using `injectManifest` that it can be difficult to trace the error message associated with a missing `self.__WB_MANIFEST` to an actionable solution.

We should update the error logic at

https://github.com/GoogleChrome/workbox/blob/e0bcb2984ab4881f0f52ae245be999aa452bba18/packages/workbox-webpack-plugin/src/inject-manifest.js#L316

to use the hardcoded error string that `workbox-build` uses, and then update that string at

https://github.com/GoogleChrome/workbox/blob/e0bcb2984ab4881f0f52ae245be999aa452bba18/packages/workbox-build/src/lib/errors.ts#L70-L71

so that the message includes a short link to a web page that explains the purpose of `self.__WB_MANIFEST`.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
