### ISSUE TITLE
Strategy plugins aren't working

### ISSUE THREAD

**Issue by FacuM** [GoogleChrome/workbox#2971]
**Library Affected**:
_workbox-strategies_

**Browser & Platform**:
_N/A._

**Issue or Feature Request Description**:
I'm currently running v6.3.1 (latest stable build) and I can't get to use any of the plugins, neither the built-ins nor my own. I'm building the service-worker using Webpack and the **injectManifest** method (code example below).

Currently, I've copied and pasted all cache-related events callbacks from the documentation regarding [custom plugins on Strategies](https://developers.google.com/web/tools/workbox/guides/using-plugins?hl=en#custom_plugins) and I've found out that none of my callbacks seem to trigger, ever.

The build system consists of a vanilla JS-like website based off Laravel Blade templates and Webpack + Mix minification.

Here's the relevant code:_

> webpack.mix.js
```js
mix.webpackConfig({
    plugins: [
        new InjectManifest({
            swSrc: './resources/service-worker.js',
            swDest: './service-worker.js'
        })
    ]
});
```

> service-worker.js
```js
import { registerRoute } from 'workbox-routing';
import {
    precache,
    precacheAndRoute
} from 'workbox-precaching';
import { NetworkFirst } from 'workbox-strategies';
```
...

```js
precacheAndRoute([], {
    ignoreURLParametersMatching: [
        /^utm_/,
        /^fbclid$/
    ]
});

precacheAndRoute(self.__WB_MANIFEST);

registerRoute(
    ({ url }) => url.pathname.startsWith('/discover'),
    new NetworkFirst({
        plugins: [{
            cacheWillUpdate: async ({request, response, event, state}) => {
                console.log(request, response, event, state);
                // Return `response`, a different `Response` object, or `null`.
                return response;
            },
            cacheDidUpdate: async ({cacheName, request, oldResponse, newResponse, event, state}) => {
                console.log(cacheName, request, oldResponse, newResponse, event, state);
                // No return expected
                // Note: `newResponse.bodyUsed` is `true` when this is called,
                // meaning the body has already been read. If you need access to
                // the body of the fresh response, use a technique like:
                // const freshResponse = await caches.match(request, {cacheName});
            },
            cacheKeyWillBeUsed: async ({request, mode, params, event, state}) => {
                console.log(request, mode, params, event, state);
                // `request` is the `Request` object that would otherwise be used as the cache key.
                // `mode` is either 'read' or 'write'.
                // Return either a string, or a `Request` whose `url` property will be used as the cache key.
                // Returning the original `request` will make this a no-op.
                return request;
            },
            cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event, state}) => {
                console.log(cacheName, request, matchOptions, cachedResponse, event, state);
                // Return `cachedResponse`, a different `Response` object, or null.
                return cachedResponse;
            },
        }]
    })
);
```

Here, `/discover` is being cached, but still, no callbacks get triggered (or at least they don't get sent out to the console). I've even gone as far as to manually and intentionally try breaking `cachedResponseWillBeUsed` by returning `null` but, even then, it still worked just fine without any logging.

I've also tried implementing the class-based method [explained here](https://web.dev/extending-workbox/) to no avail. I'm trying to intercept those events in order to append some data in case of a cache hit (i.e.: browser offline, server down, etc.).

Hope I didn't miss out on anything and I'm not being a waste of time.

**Comment by FacuM** [comment]
I've later found out that I could eventually expose some data by using [localforage](https://github.com/localForage/localForage) and even though it's not ideal, I managed to check on some of the events, and they're being triggered. However, the one I care the most is `cachedResponseWillBeUsed` and it does never seem to be firing.

This is the relevant code:

```js
let customPlugin = {
    // ...
    // Other event callbacks
    cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event, state}) => {
        localforage.setItem('lastEvent', 'cachedResponseWillBeUsed');
        // Return `cachedResponse`, a different `Response` object, or null.
        return cachedResponse;
    }
};
```

That's the point on which I'd like to inject either HTML or a header, but I'm never getting `lastEvent` updated to "cachedResponseWillBeUsed".

This is how I register the route:

```js
registerRoute(
    ({ url }) => url.pathname.startsWith('/discover'),
    new NetworkFirst({
        plugins: [ customPlugin ]
    })
);
```

**Comment by FacuM** [comment]
Alright so I finally got it working!

This is the relevant code:

```js
let online = false;

let customPlugin = {
    cacheWillUpdate: async ({request, response, event, state}) => {
        localforage.setItem('lastEvent', 'cacheWillUpdate');

        return response;
    },
    cacheKeyWillBeUsed: async ({request, mode, params, event, state}) => {
        localforage.setItem('lastEvent', 'cacheKeyWillBeUsed');
        localforage.setItem('mode', mode);

        // if a cache read is hit, the browser is offline or the server timed out
        online = mode == 'write'; 

        return request;
    },
    cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event, state}) => {
        localforage.setItem('lastEvent', 'cachedResponseWillBeUsed');

        return cachedResponse;
    },
    handlerWillRespond: async ({request, response, event, state}) => {
        if (!online) {
            let newHeaders = await new Headers(response.headers);

            newHeaders.append('X-Online', JSON.stringify(online));

            let newBody = await response.text() + '<script> const SW_OFFLINE = true; </script>';

            return new Response(newBody, { headers: newHeaders });
        }

        return response;
    },
};
```

Please note that appending RAW anywhere isn't ideal, but for testing it's great. The `X-Online` header isn't particularly useful to me at the moment, but I left it there as a way listen for headers somewhere else (maybe on a different service worker?).

`localforage` calls can be removed as they're just a way for me to debug which event fired last.

I'm not closing the issue myself as I'm pretty sure it should actually be logging to console and this is a real bug, however, feel free to close it anyways.

**Comment by jeffposnick** [comment]
Hello @FacuM!

I'm sorry you ran into issues; unfortunately, I'm having a hard time understanding what the root cause was, perhaps because you've gone back and edited the original issue.

If you have some suggestions as to how Workbox could have helped avoid whatever problem you experienced, could you distill that into a few points and we can try to address those? Otherwise, I'll close this issue.

**Comment by FacuM** [comment]
Hello @jeffposnick.

Well it looks like I'm still having some issues dealing with custom plugins on strategies.

Say I have the following setup:

```js
let online = false;

let customPlugin = {
    cacheWillUpdate: async ({request, response, event, state}) => { return response; },
    cacheKeyWillBeUsed: async ({request, mode, params, event, state}) => {
        // if a cache read is hit, the browser is offline or the server timed out
        online = mode == 'write'; 

        return request;
    },
    cachedResponseWillBeUsed: async ({cacheName, request, matchOptions, cachedResponse, event, state}) => {
        localforage.setItem('lastEvent', 'cachedResponseWillBeUsed');

        return cachedResponse;
    },
    fetchDidSucceed: async ({request, response, event, state}) => {
        // If the network transaction succeeds, drop all caches. 
        event.waitUntil(
            caches.keys().then(cacheNames => {
                return Promise.all(
                    cacheNames.map(cacheName => {
                        return caches.open(cacheName).then(cache => {
                            cache.delete(request.url);
                        })
                    })
                );
            })
        );

        return response;
    },
    handlerWillRespond: async ({request, response, event, state}) => {
        if (!online) {
            let newHeaders = await new Headers(response.headers);

            newHeaders.append('X-Online', JSON.stringify(online));

            let newBody = await response.text() + '<script> const SW_OFFLINE = true; </script>';

            return new Response(newBody, { headers: newHeaders });
        }

        return response;
    },
};
```
...
```js
[ 'profile' ].forEach(route => {
    precache([
        { url: '/' + route, revision: null }
    ]);

    registerRoute(
        ({ url }) => url.pathname.startsWith('/' + route),
        new NetworkFirst({
            ignoreVary: true,
            plugins: [
                new ExpirationPlugin({
                    maxEntries: 1
                }),
                customPlugin
            ]
        })
    );
});
```

Suddenly, my plugins don't seem to work anymore. I can't get `cachedResponseWillBeUsed` to write on localforage's `lastEvent`, even after manually **unregistering** my service worker, deleting all caches on the browser's **Cache Storage** and reloading the page.

Appart from that, I don't seem to be allowed to execute neither `console.debug` nor `console.log` within any of these events as they refuse to provide any console output at all.

My goal is to hook **before** the network operation is marked as succeeded so that I can drop the previously cached item and save the newly downloaded version back.

Thank you for your reply and I hope you can help me figure out if maybe I didn't get something right  or something's just broken.

**Comment by jeffposnick** [comment]
Hello @FacuM—I'm still having a hard time understanding what you're trying to accomplish, and therefore it's hard for me to comment on why what you describe isn't working.

Here's what I _think_ you're trying to do (which doesn't involve using `workbox-precaching` at all...):

```js
import {NetworkFirst} from 'workbox-strategies';
import {registerRoute} from 'workbox-routing';

const URLS = [
  '/profile',
  // ...
];

const CACHE_NAME = 'my-cache';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(URLS)));
});

const myPlugin = {
  cachedResponseWillBeUsed: async ({cachedResponse}) => {
    // For a NetworkFirst strategy, the only time cachedResponseWillBeUsed is
    // called is if the network request failed, so you don't have to do
    // anything special to confirm that.

    const headers = new Headers(cachedResponse.headers);
    headers.set('X-Online', 'false');

    const body =
      (await cachedResponse.text()) +
      '<script>const SW_OFFLINE = true;</script>';

    return new Response(body, {headers});
  },
};

const myStrategy = new NetworkFirst({plugins: [myPlugin]});
registerRoute(({url}) => URLS.includes(url.pathname), myStrategy);
```

If that misses the mark as to what you're trying to do, I'd encourage you to use the `state` parameter that's passed to all the plugin callbacks instead of using `localforage` to write state information. Using the `state` parameter will ensure that you're reading and writing to the same value throughout the lifetime of all the plugin's callbacks, and is not vulnerable to race conditions if your service worker is handling multiple incoming requests.
