### ISSUE TITLE
preloadResponse type declaration conflicts with typescript webworker declaration

### ISSUE THREAD

**Issue by RandomEngy** [GoogleChrome/workbox#2974]
**Library Affected**:
workbox-strategies v6.4.0

(6.3.0 was working)

**Browser & Platform**:
all browsers, Typescript 4.2.3

**Issue or Feature Request Description**:

On typescript build I get this error:

> ../../node_modules/workbox-strategies/index.d.ts:11:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'preloadResponse' must be of type 'Promise<any>', but here has type 'Promise<Response>'.
> 
> 11         readonly preloadResponse: Promise<Response | undefined>;
>                     ~~~~~~~~~~~~~~~
> 
>   ../../node_modules/typescript/lib/lib.webworker.d.ts:1572:14
>     1572     readonly preloadResponse: Promise<any>;
>                       ~~~~~~~~~~~~~~~
>     'preloadResponse' was also declared here.

Typescript has this interface declaration:

```typescript
interface FetchEvent extends ExtendableEvent {
    readonly clientId: string;
    readonly preloadResponse: Promise<any>;
    readonly replacesClientId: string;
    readonly request: Request;
    readonly resultingClientId: string;
    respondWith(r: Response | Promise<Response>): void;
}
```

Which conflicts with index.d.ts in workbox-strategies:

```typescript
declare global {
    interface FetchEvent {
        readonly preloadResponse: Promise<Response | undefined>;
    }
}
```

**Comment by jeffposnick** [comment]
Thanks for catching this—https://w3c.github.io/ServiceWorker/#fetchevent does list `Promise<any>` as the value, but at the same time, I'm not aware of any situation in which the browser will set it to anything other than `Promise<Response | undefined>`. (That's probably a question for the service worker spec editors.)

In any case, we'll update it, as I'd imagine this affects anyone using versions of TypeScript before v4.4.0.
