### ISSUE TITLE
Error with google tag manager

### ISSUE THREAD

**Issue by fisherspoon** [GoogleChrome/workbox#2979]
**Library Affected**:
workbox 6.4.1

**Browser & Platform**:
all platforms

**Issue or Feature Request Description**:
Hi, I am using workbox version 6.4.1 and I have an error in the console, it is related to gtm, when connected to the page, it creates additional scripts and this causes an error with one of them

<img width="1605" alt="Снимок экрана 2021-11-16 в 19 50 16" src="https://user-images.githubusercontent.com/17007495/142038751-8f291c9b-7986-487e-89fe-23fe12c5dc68.png">

<img width="1643" alt="Снимок экрана 2021-11-16 в 19 48 23" src="https://user-images.githubusercontent.com/17007495/142038491-04a5e8fd-cb26-4faa-adeb-2e6b7bd85fab.png">

<img width="1041" alt="Снимок экрана 2021-11-16 в 19 48 59" src="https://user-images.githubusercontent.com/17007495/142038560-9c83e5d3-f208-44e8-b4a2-3f0f1e12fc95.png">

<img width="1085" alt="Снимок экрана 2021-11-16 в 19 49 20" src="https://user-images.githubusercontent.com/17007495/142038608-e03b059f-a882-469f-8930-39b963178f08.png">

**Comment by fisherspoon** [comment]
In addition, I noticed that the problem disappears with disabled adblock

**Comment by jeffposnick** [comment]
Hello @fisherspoon! Workbox does not circumvent the network blocking behavior of any browser extensions that you might have installed. Depending on how you configure Workbox, it might make a `fetch()` request for a URL which is subsequently blocked by an extension, and if that happens, you'll get log messages like what you're seeing in the console.

If you really wanted to, you could implement a `handlerDidError` callback or a `try/catch` block around that code to attempt to provide some sort of fallback when that kind of failure occurs. But ultimately, what you're seeing is intended—you have an extension installed which blocks certain network requests, and the browser is making a request, which is proxied through Workbox, that gets blocked.

**Comment by fisherspoon** [comment]
Thanks [jeffposnick](https://github.com/jeffposnick) for the answer! Could you still answer my stupid question, is it possible to disable the service worker on certain routes?
Let's say I have a domain some-site.com and I would not like the worker to work, for example, on some-site.com/without-sw/
Of course, I can check with a regular expression in each strategy for js/css/fonts/images, but this is very inconvenient

**Comment by jeffposnick** [comment]
If you have a service worker registered with a scope of `/` (the top-level for your site), then it will control and therefore intercept network requests made by any pages underneath that top-level scope.

What you can do inside of your service worker is explicitly add in [routing criteria](https://developers.google.com/web/tools/workbox/guides/route-requests) to either respond or not respond to requests, using callback functions instead of RegExps if you find that more convenient.

If you have a particular scenario in mind that you could detail, and you could share what your service worker looks like right now, we could offer specific guidance about implementing that logic.

**Comment by fisherspoon** [comment]
Sure, but I'll leave it as a link to a third party resource. I have some pages after /
/work
/cpa
/admin

and I would like the service worker not to work for them, the only thing I came up with was to check the presence in the url for each strategy with a regular expression, for example, as I did for /admin. But as I understand it, it is impossible to completely disable the service worker?

[https://codepen.io/fisherspoon/pen/vYJvXLz?editors=0010](Codepen)

**Comment by jeffposnick** [comment]
Thanks for that info.

If you have flexibility over the URL structure of your site, the easiest approach would be have to a path that sits alongside all of the other paths on your site (`/work/`, `/admin/`, etc.) called `/pwa/` (or something similar), and to only register your service worker to control that `/pwa/` scope. That will ensure that page that are accessed from the `/admin/` prefix or anything else won't be controlled by the service worker.

If you can't do that, then using `NavigationRoute` with the `denylist` option, like you're doing in the example, is one way to ensure that the navigation requests for pages that include those prefixes aren't handled by the service worker. You may have noticed, though, that subresource requests made from those pages still do get intercepted by the service worker. You could potentially work around that by adding a clause to your route match logic that inspects `request.headers.get('Referer')` and returns `true` or `false` depending on that value, like:

```js
registerRoute(
  // Match requests for .png URLs if the referrer doesn't include /admin/
  ({url, request}) => !request.headers.get('Referer').includes('/admin/') && url.endsWith('.png'),
  new StaleWhileRevalidate()
);
```

This would only work if your [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) allows for that information to be exposed.

**Comment by fisherspoon** [comment]
Unfortunately, I cannot create separate url (/pwa) for pages where SW is needed.
And ignoring is very similar to what I used in the strategy for fonts, for example, do not create a cache for fonts if there is /admin and /work in the url. 

<img width="656" alt="Снимок экрана 2021-11-17 в 15 19 06" src="https://user-images.githubusercontent.com/17007495/142208184-a87e6e25-4951-4751-ac27-709293439b80.png">

But the actual shutdown of the service worker does not exist?

<img width="327" alt="Снимок экрана 2021-11-17 в 15 21 09" src="https://user-images.githubusercontent.com/17007495/142208497-c610a8f1-53aa-4b98-b718-d91ff48eb881.png">

**Comment by jeffposnick** [comment]
I'm not clear on what you mean when you mention "actual shutdown" not existing.

If you're asking about how long a SW will run for, please take a look at https://stackoverflow.com/a/29750936/385997

**Comment by fisherspoon** [comment]
whatever it was in devtools or it was turned off
