### ISSUE TITLE
Reloading the page refreshes the files in the cache

### ISSUE THREAD

**Issue by fisherspoon** [GoogleChrome/workbox#2980]
**Library Affected**:
workbox 6.4.1

**Browser & Platform**:
all browsers

Hi I noticed a strange thing, I have a notification for the user to install a new version of SW. I am on the page, at this moment I rebuild the files and make the Inject Manifest, then I reload the page and see the installation notification + in the console I see the old version + the new one pending and, most importantly, the files in which I made changes(js/css) are also old.
After that I do not confirm the installation of the new version and just reload the page and expect to receive all the same files. But the files are already updated and the notification about the installation + service worker is still the same - old and new. How is this possible, if not installing the worker to update the files in the cache?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
