### ISSUE TITLE
Alias runtimeCaching's urlPattern as match, eventually deprecate urlPattern

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2986]
**Library Affected**:
_workbox-build_

Workbox used to go all-in on RegExp based routing for runtime caching, and the `runtimeCaching` options in our build tools use the property named `urlPattern` to configure the match criteria. This criteria is passed in under the hood to the first parameter of `registerRoute()`, which is overloaded and takes either a string, a RegExp, or a [`matchCallback` function](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~matchCallback).

Beyond the fact that this overloaded can be confusing, I think it's doubly-confusing that the `runtimeCaching` property is called `urlPattern`, in that it makes it seem like only a RegExp pattern is supported.

I'd like to change that name to `match` as an alias for `urlPattern`, and then eventually deprecate `urlPattern` in a future release of Workbox.

This would lead to a configuration that looks like:

```
runtimeCaching: [{
  match: ({url}) => url.origin === 'www.example.com',
  handler: 'NetworkFirst',
}],
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
