### ISSUE TITLE
Ship CacheNetworkRace as part of workbox-strategies

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2989]
**Library Affected**:
_workbox-strategies_

We currently have code for a "cache and network race" strategy [in our docs](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#custom_cache_network_race_strategy). The entirety of it looks like:

```js
import {Strategy} from 'workbox-strategies';

class CacheNetworkRace extends Strategy {
  _handle(request, handler) {
    const fetchAndCachePutDone = handler.fetchAndCachePut(request);
    const cacheMatchDone = handler.cacheMatch(request); 

    return new Promise((resolve, reject) => {
      fetchAndCachePutDone.then(resolve);
      cacheMatchDone.then((response) => response && resolve(response));

      // Reject if both network and cache error or find no response.
      Promise.allSettled([fetchAndCachePutDone, cacheMatchDone]).then((results) => {
        const [fetchAndCachePutResult, cacheMatchResult] = results;
        if (fetchAndCachePutResult.status === 'rejected' && !cacheMatchResult.value) {
          reject(fetchAndCachePutResult.reason);
        }  
      });
    });
  }
}
```

Some folks have asked if we could ship it as part of `workbox-strategies` to make it more "official."

**Comment by kurtextrem** [comment]
Off-topic for this PR, but when would it be the case that the disk is slower than network? On slow and old HDDs?

**Comment by jeffposnick** [comment]
There's some analysis at https://simonhearne.com/2020/network-faster-than-cache/

**Comment by Midas847** [comment]
Hey, I am interested in this issue. Could you guide me a bit? From where should I start?

**Comment by The5cheduler** [comment]
Hello, I'm new to open source and I would like to give this a try!
If I understood the issue description correctly, the above-mentioned '**cache and network race**' code snippet needs to be integrated with **workbox-strategies**.
Please correct me if I am wrong and I would like to start working on this asap.

**Comment by regulas1** [comment]
Hi there is anyone working on this issue? If not may i please try this one out?
@parthpatel9414  or @Midas847  may you please advise me if this has been worked on?

**Comment by shreyash184** [comment]
Hey team, can someone please confirm if anyone is working on this issue, If not I would love to know more about it and resolve it :)

**Comment by Aditya-Naresh** [comment]
Guys happy to assist if anyone is working on this issue

**Comment by ZainGulbaz** [comment]
@Aditya-Naresh Can you please assign this to me?

**Comment by Aditya-Naresh** [comment]
@ZainGulbaz I think you have to ask @jeffposnick

**Comment by nickchomey** [comment]
Jeff left Google 8 months ago. The new maintainer finally confirmed the other day that workbox has been deprecated.

#3149

**Comment by tropicadri** [comment]
Workbox is not deprecated. It is understaffed, we are not releasing a new version this year, but it is in our roadmap and we want to find a path via the community or another organization to staff it better.

**Comment by mrpriyansh** [comment]
Hi @tropicadri, I am new here but really wanna contribute to Workbox. Can you guide me a little to work on this?

**Comment by dpsi9** [comment]
Hey, can I work on this issue

**Comment by gvc222** [comment]
Hello @tropicadri, please let me know how I could contribute! I'm really interested and would appreciate guidance.

**Comment by yagiz-aydin** [comment]
Is it still open ? I want to do this task

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
