### ISSUE TITLE
Files are refreshed after browser reload (not served from cache) // Reload to refresh

### ISSUE THREAD

**Issue by florianmatz** [GoogleChrome/workbox#2990]
**Library Affected**:
workbox-build, workbox-sw, workbox-window - all 6.4.1

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
I'm implementing a classic "Refresh to reload" Dialog.  Everything works pretty well but for one thing: When I do a reload on the site with a running service worker, sometimes changes are immediately present, even though the new worker has not been activated by the user.  Like it is not serving everything correctly out of the cached files.

------

I'm not totally sure, but I guess I am experiencing (kind of) the same issue like @fisherspoon in #2980.

**Status**: Service worker is running and is installed.
**Step 1**: Make update to some file; build the app and generate a new service-worker.js with workbuild-build (injectManifest)
**Step 2**: Head over to browser, reload. New service worker is installed, goes into waiting mode. My Refresh window that skips waiting and reloads the page shows up. BUT: The changes made are already present. So basically the refresh is kind of useless?

**Finding**:  Some of the chunks are served from memory cache (aka server) even they are correctly listed in the precache manifest. 

I have my code wrapped in a little react component:

```ts 
const SWManager = () => {
    const [isDialogOpen, setIsDialogOpen] = useState<boolean>(false);
    const registration = useRef<ServiceWorkerRegistration>(null);

    const closeDialog = () => {
        setIsDialogOpen(false);
    };

    const reloadWindow = () => {
        window.location.reload();
    };

    const skipWaiting = () => {
        registration.current.waiting.postMessage('SKIP_WAITING');
    };

    useEffect(() => {
        if ('serviceWorker' in navigator && process.env.REACT_APP_ENV === 'production') {
            const wb = new Workbox('/service-worker.js');
            const needsConfirmDialog = navigator.serviceWorker.controller !== null;

            navigator.serviceWorker.addEventListener('controllerchange', () => {
                console.log('controllerchange!');
                reloadWindow();
            });

            wb.addEventListener('waiting', () => {
                console.log('worker is waiting');

                if (needsConfirmDialog) {
                    setIsDialogOpen(true);
                }
            });

            wb.addEventListener('installed', () => {
                console.log('worker is installed');
            });

            const initWorker = async () => {
                registration.current = await wb.register();
            };

            initWorker();
        }
    }, []);

    return (
        <>
            {isDialogOpen && (
                <StylesProvider>
                    <Dialog
                        open
                        title="Neue Version verfügbar"
                        handleClose={closeDialog}
                        confirmButtonText="Jetzt neu laden"
                        handleConfirm={skipWaiting}
                    >
                       Eine neue Version ist für dich verfügbar. Bitte lade deinen Browser neu.
                    </Dialog>
                </StylesProvider>
            )}
        </>
    );
};
```

Service Worker
```js
self.importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-sw.js');

workbox.setConfig({ debug: true });

addEventListener('message', event => {
    if (event.data === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

workbox.core.clientsClaim();

workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);
```

Workbox 
```js
/* eslint-disable */
const { injectManifest } = require('workbox-build');

const workboxConfig = {
    globDirectory: 'build',
    globPatterns: ['index.html', '**/**.css', '**/**.js', '*.{jpg,png,svg,webp}'],
    swSrc: 'src/service-worker.js',
    swDest: 'build/service-worker.js',
};

injectManifest(workboxConfig).then(({ count, size }) => {
    console.log(`Generated ${workboxConfig.swDest}, which will precache ${count} files, totaling ${size} bytes.`);
});
```

Generally, it is working pretty well (kinda ok to do a useless reload :P), but  I just cannot understand what's happening here.
@jeffposnick, you've been pretty active in all the "Reload to Refresh" Issues I've gone through the last days. Maybe you have an idea?

**Comment by CapInSpase** [comment]
Hi, this is very similar to my problem, after I do the assembly of files, I injectManifest and if I am on the page at this moment and do a reload, the cache is updated itself.
And I also found all the strange behavior, I have a code that helps to reload all open tabs if the user agrees to install.

```jsx
if (!navigator.onLine) {
    document.querySelector('.offline-with-cache-notification').classList.add('show');
}

let refreshing
navigator.serviceWorker.addEventListener('controllerchange', function() {
        if (refreshing) return
        refreshing = true
        window.location.reload()
    }
)

// skipWaiting() functions
function promptUserToRefresh(registration) {
    document.querySelector('.notification-install-sw').classList.add('show');
    document.getElementById('reload').addEventListener('click', function(e){
        registration.waiting.postMessage('skipWaiting')
        document.querySelector('.offline-with-cache-notification').style.display = 'none';
    });
}

function listenForWaitingServiceWorker(registration) {
    function awaitStateChange() {
        registration.installing.addEventListener('statechange', function () {
            if (this.state === 'installed') promptUserToRefresh(registration)
        })
    }
    if (!registration) return
    if (registration.waiting) return promptUserToRefresh(registration)
    if (registration.installing) awaitStateChange()
    registration.addEventListener('updatefound', awaitStateChange)
}
//**


// Register service worker
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/pwabuilder-sw.js')
        .then( (registration) => {
            console.log('Service worker registered', registration)
            listenForWaitingServiceWorker(registration) // ** skipWaiting() code
        })
}else{
    console.log('Service worker not install')




So, if I have 2 tabs open in safari, then after clicking, as expected, both tabs are reloaded and in the first the cache is updated and in the second it is not, and even the reboot on the second tab does not update the cache. Moreover, if you open 3 tabs, the cache in it will be updated

**Comment by fisherspoon** [comment]
Hi, this is very similar to my problem, after I do the assembly of files, I injectManifest and if I am on the page at this moment and do a reload, the cache is updated itself.
And I also found all the strange behavior, I have a code that helps to reload all open tabs if the user agrees to install.

So, if I have 2 tabs open in safari, then after clicking, as expected, both tabs are reloaded and in the first the cache is updated and in the second it is not, and even the reboot on the second tab does not update the cache. Moreover, if you open 3 tabs, the cache in it will be updated

```jsx
if (!navigator.onLine) {
    document.querySelector('.offline-with-cache-notification').classList.add('show');
}

let refreshing
navigator.serviceWorker.addEventListener('controllerchange', function() {
        if (refreshing) return
        refreshing = true
        window.location.reload()
    }
)

// skipWaiting() functions
function promptUserToRefresh(registration) {
    document.querySelector('.notification-install-sw').classList.add('show');
    document.getElementById('reload').addEventListener('click', function(e){
        registration.waiting.postMessage('skipWaiting')
        document.querySelector('.offline-with-cache-notification').style.display = 'none';
    });
}

function listenForWaitingServiceWorker(registration) {
    function awaitStateChange() {
        registration.installing.addEventListener('statechange', function () {
            if (this.state === 'installed') promptUserToRefresh(registration)
        })
    }
    if (!registration) return
    if (registration.waiting) return promptUserToRefresh(registration)
    if (registration.installing) awaitStateChange()
    registration.addEventListener('updatefound', awaitStateChange)
}
//**


// Register service worker
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/pwabuilder-sw.js')
        .then( (registration) => {
            console.log('Service worker registered', registration)
            listenForWaitingServiceWorker(registration) // ** skipWaiting() code
        })
}else{
    console.log('Service worker not install')
}

**Comment by florianmatz** [comment]
**Additional finding**: When I make my App a bit "simpler" for testing purposes and make changes than, everything works as expected. Like changing stuff on the root level, where nothing is imported lazy by react etc. I have a strange feeling, that could have something to do with it, not having the chunks present at ServiceWorker Creation?! Although they should be precached...

**Comment by jeffposnick** [comment]
A "shift reload" (a.k.a. "force reload" or "hard reload") will cause the page to be loaded outside of service worker control. This is part of the service worker specification, and is outside of anything that Workbox could influence: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#shift-reload

(There are [some changes](https://github.com/GoogleChrome/workbox/issues/2788) we need to make to `workbox-window` to account for hard reloads, but that's outside the scope of what you're asking about.)

I'm pretty sure that explains the behavior you're seeing, so I'm going to close this issue. Let me know if there's more to it and we can revisit.

**Comment by fisherspoon** [comment]
> A "shift reload" (a.k.a. "force reload" or "hard reload") will cause the page to be loaded outside of service worker control. This is part of the service worker specification, and is outside of anything that Workbox could influence: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#shift-reload
> 
> (There are [some changes](https://github.com/GoogleChrome/workbox/issues/2788) we need to make to `workbox-window` to account for hard reloads, but that's outside the scope of what you're asking about.)
> 
> I'm pretty sure that explains the behavior you're seeing, so I'm going to close this issue. Let me know if there's more to it and we can revisit.

If you mean rebooting with Ctrl+shift+R then I do the usual reboot with Ctrl+R

**Comment by florianmatz** [comment]
Same 😂

Sorry for the confusing title and description. Going to change that. I meant hard reload only in comparison to the update I trigger on route change…

**Comment by jeffposnick** [comment]
Sorry, I'm just revisiting this issue and re-reading the original problem description. Specifically, this bit:

> Finding: Some of the chunks are served from memory cache (aka server) even they are correctly listed in the precache manifest.

This specific behavior is outside of the control of Workbox, and has to do with how Chrome's "memory cache" works. There's some background at [Chrome service worker not intercepting cached requests](https://stackoverflow.com/questions/44421110/chrome-service-worker-not-intercepting-cached-requests) and [What does Blink in-memory cache store?](https://stackoverflow.com/questions/52950068/what-does-blink-in-memory-cache-store) if you want more details. I _think_ that other browser engines have optimizations similar to Chrome's "memory cache," and I don't believe I've ever seen this behavior described as part of a web platform specification, so it's all a little murky.

There's nothing that Workbox can do to prevent requests from being fulfilled by the "memory cache," as those requests will never trigger a service worker's `fetch` event handler.

**Comment by florianmatz** [comment]
@jeffposnick Thanks Jeff for coming back to that issue and provide more context.
