### ISSUE TITLE
Release new npm version to fix security vulnerability

### ISSUE THREAD

**Issue by jdcoldsmith** [GoogleChrome/workbox#2991]
**Library Affected**:
workbox-build

**Issue or Feature Request Description**:
Could you please publish this package's most recent commit 01cba908d3a0f7b487b0b1f319c2bf7b41cd3287 to fix the security vulnerability that it is causing? Thank you!

**Comment by jeffposnick** [comment]
Yes; I want to get https://github.com/GoogleChrome/workbox/pull/2992 included in the next release as well, so once that's merged we will.

**Comment by jdcoldsmith** [comment]
You da man! Thank you!

**Comment by jeffposnick** [comment]
It's out: https://github.com/GoogleChrome/workbox/releases/tag/v6.4.2
