### ISSUE TITLE
Consider switching from ajv to zod

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2996]
We've recently switched to using a TypeScript translated to JSON Schema, validated at runtime by AJV in `workbox-build`. We've been held back a bit by the [limitations](https://github.com/GoogleChrome/workbox/blob/v6/gulp-tasks/build-node-packages.js#L44-L108) of JSON Schema, and been burned a couple of times by the number of security issues in the underlying AJV-related dependencies.

[Zod](https://github.com/colinhacks/zod) looks like an interesting alternative, with [`ts-to-zod`](https://github.com/fabien0102/ts-to-zod) available to generate the schema.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
