### ISSUE TITLE
Safari does not update cache in adjacent tabs when a new service worker is released

### ISSUE THREAD

**Issue by fisherspoon** [GoogleChrome/workbox#2997]
Hi, for several days I can not figure out the reason for this behavior in safari

**Library Affected**:
https://storage.googleapis.com/workbox-cdn/releases/6.4.2/workbox-window.prod.mjs
https://storage.googleapis.com/workbox-cdn/releases/6.4.2/workbox-sw.js

**Browser & Platform**:
Safari

[https://stackoverflow.com/questions/70328444/safari-does-not-update-cache-in-adjacent-tabs-when-a-new-service-worker-is-relea](https://stackoverflow.com/questions/70328444/safari-does-not-update-cache-in-adjacent-tabs-when-a-new-service-worker-is-relea)

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
