### ISSUE TITLE
Make workbox-sw npm package CDN-friendly

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#3003]
The `workbox-sw` package that's published to npm is of very limited usefulness; it's primarily loaded via `importScripts()` using our "official" CDN URLs, like https://storage.googleapis.com/workbox-cdn/releases/6.4.2/workbox-sw.js

Third parties, like the Nuxt community, have attempted to make `workbox-sw`-style loading play nicely with npm mirror CDNs via packages like https://www.npmjs.com/package/workbox-cdn

We should revisit what we actually publish to npm for the `workbox-sw` package, and see if we can release something that will play nicely with npm mirror CDNs out of the box.

Long term, we still want to steer developers towards creating their own custom bundles, but we plan on continuing to support `workbox-sw` as an option. Making this change will at least set us up to stop publishing to the storage.googleapis.com host at some point in the future, if jsdelivr.com, unpkg.com, etc. can fill that role officially.

**Comment by jimaek** [comment]
Let us know if the jsDelivr team can help with anything! We already serve more than 5 billion requests per month https://www.jsdelivr.com/package/npm/workbox-cdn

**Comment by mangelozzi** [comment]
> Let us know if the jsDelivr team can help with anything! We already serve more than 5 billion requests per month https://www.jsdelivr.com/package/npm/workbox-cdn
Seems to be some wrapper script, not the actual workbox script directly.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
