### ISSUE TITLE
Working with large local videos iOS Safari

### ISSUE THREAD

**Issue by iamthesiz** [GoogleChrome/workbox#3004]
# Summary
I'm building a video sharing/editing app. The idea here is: get a video from a file input, load it into a `<video />` element for seeking, playing, etc. These videos should be able to go up to 500MB in size. On my iPhone 11, a 3 minute video is about 200MB.

### tldr;
1. click file input - choose video
2. cache file (temporarily cached, removed once video is processed on the backend, used for re-upload and playing locally)
3. load video (up to 500MB)
4. play video
5. must work on iOS Safari

### The Problem
There's an [iOS Safari bug (10/29/2021)](https://bugs.webkit.org/show_bug.cgi?id=211295) that seems to crash the page when using `URL.createObjectURL` and loading the entire blob into the `<video />` (step 3 & 4 above). The [workaround](https://bugs.webkit.org/show_bug.cgi?id=232076#c3) others have found is to use CacheStorage API via a service worker and CacheOnly strategy. [Example implementation](https://bug-232076-attachments.webkit.org/attachment.cgi?id=442151) of the SW for that.

I was able to get a rudimentary version of that working, but it still causes the page to crash (in iOS Safari). Here's my current results using `workbox-range-requests` on different browsers with CacheStorage only approach.

#### Desktop Safari
- ✅ mp4 - larger files seem to work fine (100-200MB)
- ⚠️ mov - large files seem to be a little laggy at times (100-200MB)

#### Desktop Chrome
- ✅ mp4 - large files seem fine (300MB)
- ❌ mov - Shows black screen, but `video.paused === false` and I can see 206 requests happening - [maybe an issue with the Range header?](https://user-images.githubusercontent.com/5455859/146572874-a3f7d572-6ea6-42b6-9835-112c5fa393f1.png).

#### iOS Safari
Testing with a ~100MB video, I got the following.

On a **fresh/new PWA** I just now added to homescreen I get the following when
doing `cache.put(new Request(url), new Response(file))`:
```
WebSocket network error: Network process crashed.
Failed to load resource: WebKit encountered an internal error
```

On an **older PWA** I added to homescreen a while back I get the following when 
doing `cache.put(new Request(url), new Response(file))`:
```
Cache API operation failed: Quota exceeded
Unhandled Promise Rejection: QuotaExceededError: Quota exceeded
```
What's interesting is I cleared all the storage using the following, but still have the same issue.
```js
(async () => {
  // clear all CacheStorage
  const names = await caches.keys()
  names.forEach(name => caches.delete(name))
})()
```

I'm thinking it may be because of the [historical CacheStorage limit of 50MB](https://love2dev.com/blog/what-is-the-service-worker-cache-storage-limit/#:~:text=Up%20to%20this%20point%20Apple%20has%20decided%20to%20limit%20the%20service%20worker%20cache%20storage%20limit%20to%20roughly%2050MB.%20It%20is%20actually%20limited%20to%2050MiB%2C%20which%20equates%20to%20about%2052MB.). In iOS Safari though, it seems that the webkit team has [increased CacheStorage from 50MB to 1GB - comment 12 (2020)](https://bugs.webkit.org/show_bug.cgi?id=198133#c12) a couple years ago. There's a lot of mixed information out there so I wasn't sure if the CacheStorage was getting filled up.

This leads me to believe **it should** be the 50MB limitation.
> The Current Cache API quota is set to a fixed value of 50 MB per partition. This is the hard limit for the Mobile devices and as per the documentation of WebKit - [Browsers support and limitation towards PWA (2019)](https://medium.com/@zaffarabbasmughal/browsers-support-and-limitation-towards-pwa-2e6c58cd16d5#:~:text=The%20Current%20Cache%20API%20quota%20is%20set%20to%20a%20fixed%20value%20of%2050%20MB%20per%20partition.%20This%20is%20the%20hard%20limit%20for%20the%20Mobile%20devices%20and%20as%20per%20the%20documentation%20of%20WebKit)

This leads me to believe it **should not** be an issue with CacheStorage filling up.
> Nowadays, there is a unified quota for IDB and Cache - [webkit comment 15 (2020)](https://bugs.webkit.org/show_bug.cgi?id=198133#c15)

But from other places IndexedDB apparently has a larger limit.
> If the size of free disk space is over 1 GB, the default limit is 500 MB; otherwise it is half the free disk space - [webkit (2018)](https://trac.webkit.org/changeset/237700/webkit/).

> Take that 500MB as a low end average. I have stored a few GB in iOS Safari in some of my testing. I am currently working on more than one project to persist audio and video files in IDB instead of service worker cache for offline access. - [love2dev (2021)](https://love2dev.com/blog/what-is-the-service-worker-cache-storage-limit/#:~:text=Take%20that%20500MB%20as%20a%20low%20end%20average.%20I%20have%20stored%20a%20few%20GB%20in%20iOS%20Safari%20in%20some%20of%20my%20testing.%20I%20am%20currently%20working%20on%20more%20than%20one%20project%20to%20persist%20audio%20and%20video%20files%20in%20IDB%20instead%20of%20service%20worker%20cache%20for%20offline%20access.)

If it's a limit with the CacheStorage, maybe store in IndexedDB, add a fake URL to CacheStorage, hit the cached URL, then pull the file from IndexedDB, slice the file ([similarly to how it's being done here](https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/)) to return the proper Range Request / partial video file OR use `workbox-range-requests`.

It seems like a custom workbox strategy for this might be best. 

I don't seem to be hitting indexeddb quota limits so far, but does this seem to be the right approach? If so, how do I implement the correct strategy to pull the value from idb and still have the `workbox-range-requests` split the video file accordingly.

```js
const { get } = require('idk-keyval')

new WorkboxPlugin.GenerateSW({
  runtimeCaching: [{
    urlPattern: /\/local-static(.*)/i,
    handler: 'CacheOnly',
    method: 'GET',
    options: {
      rangeRequests: true,
      cacheName: 'local-static',
      expiration: {
        maxEntries: 16,
        maxAgeSeconds: 24 * 60 * 60 // 24 hours
        plugins: [{
          async cachedResponseWillBeUsed({ cacheName, request, matchOptions, cachedResponse, event, state }) {
            const idbKey = request.url.pathname.substring(1)
            const video = await get(idbKey)
            // split the video...
            return cachedResponse;
          },
        }]
      }
    }
  }]
})
```

Referencing:
https://github.com/GoogleChrome/workbox/issues/1663

**Browser & Platform**:
iOS Safari 14.8.1

**Comment by iamthesiz** [comment]
I'm working on a browser limitations app that will record
- version
- browser
- etc.

This will allow us to test different strategies, and see what browsers and versions they are failing in. Will post once it's ready. In the meantime, any advice on this would be great.

**Comment by bighitbiker3** [comment]
@alex-cory Any update on how you implemented this? I need to do the same thing and am having trouble figuring out how to best do it.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Comment by iamthesiz** [comment]
> @alex-cory Any update on how you implemented this? I need to do the same thing and am having trouble figuring out how to best do it.

I did "kind of" get this working, but I ended up implementing a different strategy requiring users to upload the video prior to doing any video editing. Then it was loading the videos from the server which worked.

The problem was too much inconsistency with how the browsers were working with local videos.

**Comment by tomayac** [comment]
Thanks for documenting your workflow and how you managed to get this working cross-browser, @alex-cory!
