### ISSUE TITLE
[workbox-build,workbox-webpack-plugin] `source-map-url` is deprecated

### ISSUE THREAD

**Issue by rtritto** [GoogleChrome/workbox#3019]
`source-map-url` is [deprecated](https://github.com/lydell/source-map-url#deprecated) and it's a dependency of _workbox-build_ and _workbox-webpack-plugin_.

**Comment by alexey-koran** [comment]
@jeffposnick Hi, maybe you can check this?

**Comment by jeffposnick** [comment]
We really only need one of the RegExps that the module provided, and it's MIT licensed, so we'll move an adaptation of that code into a local module in the Workbox project.

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/workbox/compare/source-map-url?expand=1 has the change for `workbox-build`.

Once #2882 is complete, I'll update the branch to do the same for `workbox-webpack-plugin`.

This should get published as part of our v6.5.0 release.

**Comment by jeffposnick** [comment]
This is resolved in the https://github.com/GoogleChrome/workbox/releases/tag/v6.5.0 release.
