### ISSUE TITLE
question: `generateSW` with `runtimeCaching` caches missing on initial request

### ISSUE THREAD

**Issue by userquin** [GoogleChrome/workbox#3023]
**Library Affected**:
`workbox-build`: `generateSW` (6.4.2 version)

https://streamable.com/xdhu3t

**Browser & Platform**:
Chrome and Edge on windows (also failing on Chrome Canary), not tested in other OS.

I don't know if this is a workbox bug or if I need to add somehting to the configuration: maybe I need to add some precaching entry.

When generating the sw using `workbox-build::generateSW` and configuring some runtime caching entries for CDN fonts and github avatars images (only in vitest docs), we need to refresh the page to cache resources: you can see the configuration here https://github.com/antfu/vite-plugin-pwa/blob/main/docs/vite.config.ts#L119.

You can check the vite plugin pwa docs on private window (https://vite-plugin-pwa.netlify.app/), cofirmn the sw is installed, then go to CacheStorage on devtools and check the fonts cache are missing: just refresh the page and the cache will be there.

I'm adding PWA to `vitest` docs and I need to cache also some images from github, this is the configuration (I also have 2 entries for CDN fonts and styles). You can check the configuration https://github.com/vitest-dev/vitest/blob/userquin/docs-add-pwa/docs/vite.config.ts#L113, following code is on local, just testing:
```ts
          {
            urlPattern: /^https:\/\/(cdn.jsdelivr.net|patak.dev|github.com|avatars.githubusercontent.com)\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'image-cache',
              expiration: {
                maxEntries: 1000,
                // maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                // github.com/{user}.png will redirect to avatars.githubusercontent.com
                statuses: [0, 200/* , 302 */],
              },
              fetchOptions: {
                redirect: 'follow',
              },
            },
          },
```

I activate the logs on local build, and it seems the sw is not precaching these resources: the resources are in the root page.

I also include all the images on head links for prefetching without success:

![imagen](https://user-images.githubusercontent.com/6311119/151669371-9ad7badd-298a-496c-8ae5-3476c962a88b.png)

**Comment by userquin** [comment]
I get it working using `injectManifest` strategy (on plugin pwa with custom sw) and `warmStrategyCache` from `workbox-recipes`, can this be achieve using `generateSW` instead using custom sw?:
```ts
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { warmStrategyCache } from 'workbox-recipes'
import { font, pwaFontStylesRegex, pwaFontsRegex, pwaImagesRegex } from '../docs-data'
import { antfuSponsors, contributors, coreTeamMembers, patakSponsors } from './contributors'

declare let self: ServiceWorkerGlobalScope

const imagesCache = new StaleWhileRevalidate({
  cacheName: 'image-cache',
  fetchOptions: { redirect: 'follow', mode: 'no-cors' },
  plugins: [new ExpirationPlugin({
    maxEntries: 1000,
  }), new CacheableResponsePlugin({
    statuses: [0, 200],
  })],
})

const fontsCache = new CacheFirst({
  cacheName: 'google-fonts-cache',
  plugins: [new ExpirationPlugin({
    maxEntries: 10,
    maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
  }), new CacheableResponsePlugin({
    statuses: [0, 200],
  })],
})

const fontStylesCache = new CacheFirst({
  cacheName: 'gstatic-fonts-cache',
  plugins: [new ExpirationPlugin({
    maxEntries: 10,
    maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
  }), new CacheableResponsePlugin({
    statuses: [0, 200],
  })],
})

const avatars = new Map<string, string>()
avatars.set(antfuSponsors, antfuSponsors)
avatars.set(patakSponsors, patakSponsors)
coreTeamMembers.forEach(({ github, avatar }) => {
  if (!avatars.has(github))
    avatars.set(github, avatar)
})
contributors.forEach(({ name, avatar }) => {
  if (!avatars.has(name))
    avatars.set(name, avatar)
})

// self.__WB_MANIFEST is default injection point
precacheAndRoute(self.__WB_MANIFEST)

warmStrategyCache({ urls: Array.from(avatars.values()), strategy: imagesCache })
warmStrategyCache({ urls: [font], strategy: fontsCache })

// clean old assets
cleanupOutdatedCaches()

// to allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')))

registerRoute(pwaFontsRegex, fontsCache, 'GET')

registerRoute(pwaFontStylesRegex, fontStylesCache, 'GET')

registerRoute(pwaImagesRegex, imagesCache, 'GET')

self.skipWaiting()
clientsClaim()
```

**Comment by userquin** [comment]
Another question, maybe a bug on chromium based browsers: the cache size is huge 290MB, there is no such ammount of data, just 30 images, a css file and a font:

![imagen](https://user-images.githubusercontent.com/6311119/151674785-5328dafd-5a40-41d1-9e0f-279aafdda8f9.png)

![imagen](https://user-images.githubusercontent.com/6311119/151674805-87b6a892-7247-42c9-b03d-08ba43b1c144.png)

**Comment by jeffposnick** [comment]
Correct approach for the initial question; if you're using runtime caching, then the caches are not populating ahead of time by default. They'll be populated "as you go" once the service worker has installed and taken control of the page after the initial registration, but that normally won't happen before the page has already made requests for its subresources. You can either just wait until the _second_ visit for the caches to be populated at runtime, or attempt to "warm" the runtime caches using `warmStrategyCache()` like you're doing.

Regarding the second question, this is due to the use of opaque responses on your page. There's a section in the [Workbox docs](https://developers.google.com/web/tools/workbox/guides/storage-quota#beware_of_opaque_responses) that describes this, as well as that "[Learn more](https://developer.chrome.com/docs/devtools/progressive-web-apps/?utm_source=devtools#opaque-responses)" link in Chrome's DevTools.

If you are runtime caching cross-domain images and your CDN supports CORS, you can work around this by adding the `crossorigin` attribute to your `<img>` element, e.g. `<img src="https://image.cdn.com/something.png" crossorigin="anonymous">`
