### ISSUE TITLE
Delay the cache write in StrategyHandler's fetchAndCachePut()

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#3025]
In the course of debugging some performance related issues with a Workbox-based service worker that uses a `CacheFirst` strategy for a burst (1000+) of requests, @wanderview [suggested](https://bugs.chromium.org/p/chromium/issues/detail?id=1293176#c8) that we should add in a short delay before we write to cache in `StrategyHandler`'s `fetchAndCachePut()`:

https://github.com/GoogleChrome/workbox/blob/1deeba932904bcea52ea9fe809e0aa5cc74b0941/packages/workbox-strategies/src/StrategyHandler.ts#L253-L260

I don't think we should do this outside of a major semver change, but it might be something to play around with as part of a Workbox v7 pre-release and get a feel for whether there are any unintended consequences.

**Comment by wanderview** [comment]
Or possibly an option with some documentation explaining why you might want to add delay.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
