### ISSUE TITLE
filter in workbox documentation not working

### ISSUE THREAD

**Issue by fernandobelotto** [GoogleChrome/workbox#3028]
Hi there! i found that the filter in the workbox documentation is not working properly. I typed in the text field in the sidebar, press enter, retyped and nothing happens.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/38187170/153686553-61fb4123-4541-4185-b56f-189b492e67f2.png">

**Comment by jeffposnick** [comment]
Sorry about that—we're close to migrating our canonical docs over to https://developer.chrome.com/docs/workbox/

We're not going to make any fixes/changes to the older site's functionality at this point.

**Comment by fernandobelotto** [comment]
thanks @jeffposnick
