### ISSUE TITLE
Enable Navigation Preload by default for SW with fetch handlers

### ISSUE THREAD

**Issue by garthenweb** [GoogleChrome/workbox#3030]
**Library Affected**:
_workbox-webpack-plugin_

**Browser & Platform**:
_all browsers_

**Feature Request Description**:

On our website the SW is only used for caching of JS and CSS at install time to speed up navigation in a SPA. We don't have offline support or something similar.

Based on [this article from Jake Archibald about Navigation Preloads](https://developers.google.com/web/updates/2017/02/navigation-preload), a service worker that uses fetch handlers can slow down the page for returning users (especially on mobile) in case the service worker was stopped. To fix this, you can use navigation preload to trigger the request and boot the service worker in parallel.

I'd therefore suggest, in case a fetch handler exists
- to activate `navigationPreload`
- add the config for `runtimeCaching` to use the network response

by default (if not overridden).

At the moment `navigationPreload` is disabled by default and if activated requires further configuration in `runtimeCaching`.

```
{
  navigationPreload: true,
  runtimeCaching: [{
      urlPattern: (({request}) => request.mode === 'navigate'),
      handler: 'NetworkOnly',
    }
}
```

Do you see any downsides in this proposal? I am not a service worker expert and might have missed something :)

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
