### ISSUE TITLE
`npm install workbox-cli` adds 12,432 files

### ISSUE THREAD

**Issue by lgarron** [GoogleChrome/workbox#3032]
Run:
```shell
# bash
function cost {
  cd $(mktemp -d)
  npm init -y
  npm install $@
  find node_modules -type f | wc -l
}

cost workbox-cli
```

This adds 12,432 files to `node_modules`, which seems really bloated to me. That's the kind of cost that makes me look around for another tool, which is a shame because I'm happy with the `workbox` functionality itself.

For comparison, here are the number of files for other common tools that I get on macOS:

- `cost typescript`: 132 files
- `cost esbuild`: 10
- `cost vite`: 314
- `cost parcel`: 3,773
- `cost wmr`: 12
- `cost swc`: 301
- `cost webpack-cli`: 2,884
- `cost rollup`: 28

For those of us using little more than `esbuild` for our web apps — quite a realistic option these days — `workbox-cli` can increase our dependency file count by 2 or 3 (decimal) orders of magnitude. For precaching, a few lines of script code used to be sufficient for the same functionality in the days of AppCache.

--------

It seems like ≈3,600 of the files used installed for `workbox-cli` are from `rxjs`, because of `inquirer`. A further 1,000 are due to `lodash`, and there are a few other deps with hundreds of files.

Would it be possible to adopt some alternative dependencies that keep down the cost a bit (or ideally a lot)?

**Comment by jeffposnick** [comment]
Thanks for the request. We can look into alternatives to `inquirer`, and I think we'll also be switching from `rollup` to `esbuild` (or `swc`) in Workbox v7 (#3002), which should cut down on the bundling- and transpilation-related dependencies as well.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
