### ISSUE TITLE
Can't add the Workbox Broadcast Update plugin to workbox-config

### ISSUE THREAD

**Issue by jmcgavin** [GoogleChrome/workbox#3034]
I am using [`GenerateSW()`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW) to add a service worker to my javascript application.

```js
import { generateSW } from 'rollup-plugin-workbox'
import workboxConfig from './workbox-config.js'

generateSW(workboxConfig)
```

I would like to use the [Broadcast Update](https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-update) feature of the service worker to notify users when a cached resource has been updated but I'm not sure how to add the plugin given my workbox config file:

```js
import path from 'path'

const config = {
  swDest: path.join(__dirname, 'dist', 'sw.js'),
  globDirectory: path.join(__dirname, 'dist'),
  globPatterns: ['**/*.{html,js,css,svg,png,jpg,jpeg,woff2,json}'],
  runtimeCaching: [
    {
      handler: 'StaleWhileRevalidate',
      urlPattern: /^https:\/\/.*.jwm.com\/v1\/catalogs/,
      options: {
        cacheName: 'catalogs',
        cacheableResponse: {
          statuses: [200]
        },
        expiration: {
          maxAgeSeconds: 60 * 60
        }
      }
    }
  ]
}

export default config
```

**Comment by jeffposnick** [comment]
The [`runtimeCaching.options`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry) parameter can be configured with a `broadcastUpdate` property, whose value roughly corresponds to what you'd pass to the [`BroadcastUpdatePlugin`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-broadcast-update.BroadcastUpdatePlugin) constructor.

E.g.:

```js
const config = {
  // ...
  runtimeCaching: [
    {
      // ...
      options: {
        broadcastUpdate: {
          // All values here are optional:
          channelName: 'my-test-channel',
        }
      }
    }
  ]
};
```
