### ISSUE TITLE
workbox-webpack-plugin InjectManifest missing vendor.js

### ISSUE THREAD

**Issue by pilipala6868** [GoogleChrome/workbox#3042]
I'm using workbox-webpack-plugin's InjectManifest to generate the `__WB_MANIFEST` list, for `precacheAndRoute` in the service-worker.js.

But I found that the `vendor.xxx.js` was not in list.
So the serviceWorker won't cache it either. (common.js、runtime.js no problem)

__WB_MANIFEST
![image](https://user-images.githubusercontent.com/25118028/158087625-fac7a8c8-32da-422a-abcd-5eb1af3853ab.png)

network
![image](https://user-images.githubusercontent.com/25118028/158087641-be1fa658-eef8-4983-bc54-c878db6fe4c0.png)

Btw, the vendor.js is in the webpack's manifest.json file.
And I had turn up the `maximumFileSizeToCacheInBytes` config over the vendor's size.
But it still doesn't work.

🙏🙏

webpack.config.js:
```js
plugins: [
    new InjectManifest({
      swSrc: './service-worker/service-worker.js',
      maximumFileSizeToCacheInBytes: 10485760, // 10M
    })
]
```

service-worker.js：
```js
import { precacheAndRoute } from 'workbox-precaching';

const precacheList = self.__WB_MANIFEST || [];

precacheAndRoute(precacheList, {
  cleanURLs: false,
});

self.addEventListener('install', (event) => {
  self.skipWaiting();
});
self.addEventListener('activate', (event) => {
  self.clients.claim();
});
```

**Library Affected**:
workbox-precaching^6.5.0, workbox-webpack-plugin^6.5.0, egg-webpack^5.0.1

**Browser & Platform**:
Google Chrome v99 for Mac

**Comment by jeffposnick** [comment]
I'm sorry that you're running into this.

Could you share the rest of your webpack config, or at least the part that's directly relevant to creating the `vendor` chunk?

And ideally, if you had a public project in a GitHub repository that I could run to reproduce the issue, that would be 👍

**Comment by pilipala6868** [comment]
@jeffposnick hi, thanks for your reply. 
I'm sorry that my project is pravite belongs to the company. But I'll show you the part that's relevant to the question.

The project is base on [egg](https://www.eggjs.org/) + react, using [easywebpack](https://github.com/easy-team/easywebpack) to complete the webpack config.
Here's part of the webpack.config.js.
```js
const { InjectManifest } = require('workbox-webpack-plugin');

module.exports = {
  dll: ['react', 'react-dom', 'react-router', 'mobx', 'mobx-react', 'axios'],
  entry: {
    login: 'app/web/page/login/index.tsx',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  module: {
    rules: [{ typescript: true }],
  },
  plugins: [
    new InjectManifest({
      swSrc: './service-worker/service-worker.js',
      maximumFileSizeToCacheInBytes: 10485760,
    }),
  ],
};
```

**Comment by pilipala6868** [comment]
I tried to dig into the source code to find out the answer.
And I found the `compilation.getAssets()` from `workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation` - `filterAssets()` will trigger 3 times during a webpack build process.

Here's the print infomation:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/25118028/158290948-ba2b7fbf-91e2-428e-9190-1f46027ab8ec.png">
<img width="308" alt="image" src="https://user-images.githubusercontent.com/25118028/158291272-3109c043-bb97-41ff-ab9c-1526d8c09ed2.png">
<img width="308" alt="image" src="https://user-images.githubusercontent.com/25118028/158291282-ea181147-8f82-47ab-bd5f-69dd2444fc48.png">

You can see the `vendor` **is** in the first `getAssets()`. Then the rest of it just disappear. 🙊

**Comment by jeffposnick** [comment]
Okay, if you're using [`DllPlugin`](https://webpack.js.org/plugins/dll-plugin/), then it's likely the same issue as https://github.com/GoogleChrome/workbox/issues/1348

Finding a resolution to the issue has not been a priority, as it seemed from that older discussion that using `DllPlugin` in production builds was uncommon/not recommended.

We can revisit that if there's a strong reason to, but let's move the discussion over to that issue instead.
