### ISSUE TITLE
Migrating the migration guides to the new docs site

### ISSUE THREAD

**Issue by planeth44** [GoogleChrome/workbox#3044]
Could you please document the path to upgrade from v5 to v6 as you did in the old docs pages ?

Thanks :)

**Comment by jeffposnick** [comment]
Good point! @malchata, just want to get this on your radar.

The following links all still work in the meantime:

- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v5
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw

**Comment by planeth44** [comment]
Thanks a lot :)

**Comment by malchata** [comment]
I think we should have a separate ToC for migration guides, @jeffposnick, something that lives at a URL like developer.chrome.com/docs/workbox/migration. You think that might work?

**Comment by jeffposnick** [comment]
Absolutely. That sounds 👍 

(And no rush, since the old pages are still hosted and discoverable. I know that there are other priorities, but I wanted to keep this open so that we don't lose track.)

**Comment by malchata** [comment]
Migration guides have been migrated to developer.chrome.com: https://developer.chrome.com/docs/workbox/migration/
