### ISSUE TITLE
Feature: Check if active service worker and replace

### ISSUE THREAD

**Issue by developdeez** [GoogleChrome/workbox#3047]
Feature Request

Would like to see if we can detect if there's already an active service worker on the client's device.

Currently I use getRegistration to do this but I was curious if Workbox could automatically detect if there is already and SW and avoid attempting to register the same service worker.

Also I've noticed when we clear out an SW or it updates. There's no way to know when it needs to refresh and expired SW. I saw the 'pushsubscriptionchange' in service workers but it doesn't seem to work here. Would be helpful if WB could detect and replace.

**Comment by jeffposnick** [comment]
If the promise returned by [`navigator.serviceWorker.ready`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready) fulfills, there's an active service worker.

Generally speaking, if there is already an underlying service worker API that's straightforward to use, we won't attempt to "wrap" it as part of Workbox. `navigator.serviceWorker.ready` falls into that category.

[There is no need to avoid registering the same service worker multiple times](https://stackoverflow.com/questions/50471486/what-happens-if-i-call-serviceworker-register-multiple-times/50475393#50475393), though. If you call `register()` and you pass in the same `scriptURL` with the same effective `scope` as the existing registration, it's effectively a no-op.
