### ISSUE TITLE
Switch to using real private class fields

### ISSUE THREAD

**Issue by jimmywarting** [GoogleChrome/workbox#3050]
instead of using private keyword 
https://github.com/GoogleChrome/workbox/blob/8afb37210d8f4fe62847f4e80e42fc95bced4895/packages/workbox-expiration/src/models/CacheTimestampsModel.ts#L42-L44

how about start using `#` instead?
```js
#db: IDBPDatabase<CacheDbSchema> | null = null; 
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
