### ISSUE TITLE
Cache Storage for file with missing hash using old js bundle.

### ISSUE THREAD

**Issue by anz000** [GoogleChrome/workbox#3058]
I have an SSR based app built on top of Razzle that uses workbox using https://www.npmjs.com/package/razzle-plugin-workbox.  This plugin is just a wrapper around the [WorkboxWebpackPlugin.GenerateSW](https://github.com/NickCis/razzle-plugin-workbox/blob/master/index.js#L11).

I have been running into issues whenever I try to load a new release version of the app. The app would just show a blank white screen with console showing random errors like "Uncaught SyntaxError: Unexpected token '<'". If I do a hard refresh, things load properly, but a normal refresh again runs into the same problem.

Upon digging further, it's related to the service worker and how it caches in the Cache Storage. The first entry in the Cache Storage is `?__WB_REVISION__=project-symantic-app-version`, where `project` is the project name and `symantic-app-version` is the current app version. When I probe the content of this html file, I can see that the js bundle it is using is an old one.

When a new release bundle comes in, service workers are being registered properly. However, the cache content are not updated for this particular entry is because of the missing hash. All the other entries have `?__WB_REVISION__=some-hash`. 

I would like to either

1. Remove the cache entry of the problematic html by avoiding it to cache at all based on some regex matching (possibly WB_REVISION and project name would be unique), and always fetch it from network.
2. Instead of `project-symantic-app-version`, apply some sort of hash so content gets updated when a new release bundle comes in.

I'd love some feedback. Thanks.

**Comment by jeffposnick** [comment]
Generally speaking, it's very important that precache entries have `revision` fields that are updated whenever the underlying content at the corresponding `url` is updated (or have `revision: null` if the `url` contains inline version info, like a `app.[hash].js`).

I am not familiar with `razzle-plugin-workbox`, but I can see from https://github.com/NickCis/razzle-plugin-workbox/blob/1c723e072a11a7df723f62de561378c5fd0cd1ce/index.js#L26 that there is a precache manifest entry added to the list for `/` whose `revision` is not based on the underlying HTML at `/`, but instead on `package.json` fields. This is problematic, for the reasons you're encountering.

I'd recommend filing a bug against that project letting them know, and if they can't remediate it, not using it in favor of using the `workbox-webpack-plugin` directly.

**Comment by anz000** [comment]
That's it, will let them know. Thanks for the great library.
