### ISSUE TITLE
Service worker not installing on Firefox

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/workbox#3060]
**Library Affected**:
- workbox-sw
- workbox-core

**Browser & Platform**:
- Firefox 98.0.2 (64-bit)
- Reported on OSX and Linux

**Issue or Feature Request Description**:
The service worker is not installing on Firefox. I then confirmed this is an issue originating from `workbox` by using the demo for [workbox-core](https://glitch.com/~workbox-core) and noticed that the service worker is not installing there either. On Google Chrome it works well and the Workbox logs and Cache Names are printed to the console.

The same behaviour is experienced on other service workers created using Workbox

URL to replicate: https://glitch.com/~workbox-core

**Comment by nabsta-eth** [comment]
I am also having this issue.  It works on Chrome (obvs), Brave, Opera, Edge, just not FF.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
