### ISSUE TITLE
[workbox-window] does not resolve esm version within node 14+ in ESM context

### ISSUE THREAD

**Issue by daKmoR** [GoogleChrome/workbox#3066]
**Library Affected**:

- workbox-window

**Browser & Platform**:

- node 14+ using ESM

**Issue or Feature Request Description**:

When trying to import `workbox-window` in a `"type": "module"` setting it does not correctly resolve.

**Current behavior**:

1. Use node 14+
2. have a package.json with `"type": "module"`
3. Create a 👉 `test.js` file

   ```js
   import { Workbox } from "workbox-window";

   console.log(Workbox);
   ```

4. Execute it via `node test.js`

Result is the following error message

```
node test.js
file:///html/tmp/workbox-export-map/test.js:1
import { Workbox  } from "workbox-window";
         ^^^^^^^
SyntaxError: Named export 'Workbox' not found. The requested module 'workbox-window' is a CommonJS module, which may not support all module.exports as named exports.
```

**Expected behavior**:

`import { Workbox } from "workbox-window";` uses an ESM version.

**Suggestion**:

Add an node export map to define the entry points for commonjs & es modules.
https://nodejs.org/api/packages.html#package-entry-points

It could look like

👉 `package.json`

```json
{
  "exports": {
    ".": {
      "import": "./build/workbox-window.prod.es5.mjs",
      "require": "./build/workbox-window.prod.umd.js"
    }
  }
}
```

I saw there are multiple other entry points as well like `workbox-window.dev.es5.mjs`.
How are they currently imported?

like this?

```js
const { Workbox } = require("workbox-window/build/workbox-window.dev.es5.mjs");
```

if so those would need to be added to the export map as well as it would otherwise be a breaking change (as ONLY what is in the export map can be imported).

```json
{
  "exports": {
    ".": {
      "import": "./build/workbox-window.prod.es5.mjs",
      "require": "./build/workbox-window.prod.umd.js"
    },
    "./build/workbox-window.dev.es5.mjs": "./build/workbox-window.dev.es5.mjs",
    "./build/workbox-window.dev.mjs": "./build/workbox-window.dev.mjs"
    // ...
  }
}
```

or we could consider adding them in a breaking change with a dev condition.
(e.g. import is always `import { Workbox } from "workbox-window";` and a build tool decided which of the exports to choose)

```json
{
  "exports": {
    ".": {
      "development": "./build/workbox-window.dev.mjs",
      "import": "./build/workbox-window.prod.es5.mjs",
      "require": "./build/workbox-window.prod.umd.js"
    }
    // ...
  }
}
```

But having multiple development conditions for esm/cjs would probably impractical 🤔
So that might be a push towards esm?

What do you think?

---

Potentially related to

- https://github.com/GoogleChrome/workbox/issues/2797

**Comment by KaelWD** [comment]
> those would need to be added to the export map as well as it would otherwise be a breaking change

You can just use a wildcard for this:

```json
{
  "exports": {
    ".": {
      "import": "./build/workbox-window.prod.es5.mjs",
      "require": "./build/workbox-window.prod.umd.js"
    },
    "./*": "./*"
  }
}
```

**Comment by jeffposnick** [comment]
Yes, as mentioned, https://github.com/GoogleChrome/workbox/issues/2797 covers the same ground, and we can move the discussion over there.

We would like to follow modern best practices for the `exports` field in our `package.json`, but my impression is that it's difficult to do this cleanly outside of a breaking change/major semver release. We have it on the list of things we'd like to accomplish in Workbox v7.

**Comment by daKmoR** [comment]
> but my impression is that it's difficult to do this cleanly outside of a breaking change/major semver release

yes a new major is definitely the safest option 👍 (but it's usually also the one that takes the longest to implement and to adopt 🙈)

**Comment by KaelWD** [comment]
I don't think this would be a breaking change. You're already distributing esm builds, they just can't be used without a bundler because `module` is only supported by webpack. I'm currently having to use patch-package to add exports to workbox-window's package.json so I can use it with vite.

**Comment by jeffposnick** [comment]
It's mainly that we don't know _how_ folks are using v6—either via `patch-package` like you are, or via different bundlers that might not follow the modern standards but still work today, or via some other mechanism—so making a backwards-compatible change that's not going to break _any_ current users is not something we can do with confidence.
