### ISSUE TITLE
(CacheFirst + ExpirationPlugin) Cache time seems to refresh when cache is served 

### ISSUE THREAD

**Issue by ZYinMD** [GoogleChrome/workbox#3070]
**Library Affected**:
CacheFirst, ExpirationPlugin

**Browser & Platform**:
Chrome v101

**Issue or Feature Request Description**:
```js
registerRoute(
  demoMatcher,
  new CacheFirst({
    cacheName: "demo-cache",
    plugins: [new ExpirationPlugin({ maxAgeSeconds: 10 })],
  })
);
```
This cache is supposed to expire in 10 seconds. However, if I repeatedly hit the route every 5 seconds, the cache seems never expire. It will only expire when two consecutive hits are >10 seconds apart. Not sure if this is by design, but I think it shouldn't be?

Meanwhile, if I look at the entry in Cache Storage in DevTools, the "Time Cached" won't change. It'll always be the time of the initial cache, which is expected, but the problem is the entry will never disappear as long as I keep hitting it.

**Comment by xanxuz** [comment]
I have the exact same problem!, did you solve it?, if so, can you please post the solution?

**Comment by mungojam** [comment]
Also see the conversation on [#2863](https://github.com/GoogleChrome/workbox/issues/2863#issuecomment-881791503) which establishes that the behaviour is actually different dependent on whether a `Date` header is returned from the server:

> In practice, this means that the behavior of the ExpirationPlugin can drastically change based on subtle differences. As an example, if you save your images with the CacheFirst strategy and set maxAgeSeconds to a month, then as long as all your images are served with a correct Date header, they will all be removed and get a fresh update from the server at least once a month. But if you one day accidentally disable the Date header on your server, then the serviceworker will fall back to IndexedDB timestamps, which are updated every time the images are used, so if a user watches those images at least once a month for several years, then the images will just stay in cache and never be redownloaded from the server for all those years.

**Comment by HazyFish** [comment]
I have the exact same problem even though a date header is present @mungojam

**Comment by HazyFish** [comment]
Is there anything wrong with this date header produced by Cloudflare?

```
date: Sun, 25 Dec 2022 00:22:14 GMT
```

**Comment by naoak** [comment]
It worked well in my environments that do not require CORS. A `Date` header is not a [CORS-safelisted response header](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header), so I think it must be added to [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) to access from JS if you are fetching contents that require CORS.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
