### ISSUE TITLE
determining on the client side if the failed request will be queued or not

### ISSUE THREAD

**Issue by pavlexander** [GoogleChrome/workbox#3072]
**Library Affected**:
    "workbox-background-sync": "^6.5.3",
    "workbox-core": "^6.5.3",
    "workbox-precaching": "^6.5.3",
    "workbox-window": "^6.5.3"

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

## TLTR
On the client side - how to tell if the failed request will be queued or not?

## Else
`sw.js`

```
import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
} from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { Queue } from "workbox-background-sync";
import { NetworkOnly } from "workbox-strategies";

const queue = new Queue("myQueueName", {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request.clone());
      } catch (error) {
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();
registerRoute(new NavigationRoute(createHandlerBoundToURL("index.html")));

const statusPlugin = {
  fetchDidFail: async ({ originalRequest, request, error, event }) => {
    console.log("fetchDidFail");
    queue.pushRequest({ request: originalRequest });
  },
  fetchDidSucceed: ({ response }) => {
    console.log("fetchDidSucceed");
    return response;
  },
};

registerRoute(
  new RegExp(".*/Exercises/.*"),
  new NetworkOnly({
    plugins: [statusPlugin],
  }),
  "POST"
);
```

On the **client** using `axios`:

```
    const add = async () => {
      try {
        var response = await axiosInstance.post("Exercises/Create", { name: 'test' });
      } catch (error) {
        console.log(error);
       // Error, but what kind of error?? Will the request be queued or not??
       // 400, 401, 5xx, etc, or network unavailable
      }
    };
```

The flows are following:

* case: no connection (**ERR_NETWORK**), or service unavailable (**ECONNABORTED**)
1. send `post` request from UI
2. client catches exception in `add` method
3. (with delay) in `sw.js`  - `fetchDidFail` is invoked, **request added to queue**

* case: bad request 400 (**ERR_BAD_REQUEST**)
1. send `post` request from UI
2. client catches exception in `add` method
3. (with delay) in `sw.js`  - `fetchDidSucceed` is invoked, request **NOT added to queue**

So in all 3 cases the client catches an exception while making a request. But the request will be queued only in **some** cases.

I would like to know in advance on the client side if the request will go through the `fetchDidFail` or the `fetchDidSucceed` chain! This is **so that I could warn the user that the request execution failed, but will be retried later**! The item should then be added to a `indexeddb` storage.  In case when the request is not queued - user just gets the error message and nothing gets stored.

So how to accomplish this?

Notes

1. I don't want to check for hardcoded error codes (ERR_NETWORK/ECONNABORTED/ERR_BAD_REQUEST). They come and go with new specifications, so I can't account for all situations using this method. Need a more robust solution. Unless??
2. If possible, I don't want to rely on a missing http status code (0) in response. Because I have noticed that in some cases this value is set to 0 when backend dotnet server throws the internal error (5xx http status code). When the CORS headers are not properly set for response then `axios` reads all codes as 0 ([feature, not a bug](https://github.com/dotnet/aspnetcore/issues/2378#issuecomment-475847271)). So this code is not reliable in my case.

**Comment by pavlexander** [comment]
I have looked into the "second note" more and decided to check if the fetch API is any different than the `axios`.. and it's not!

Meaning, if there is CORS problem - the service worker will always treat all responses with `fetchDidFail`!

so

* case 1: 500 error thrown by the server, valid CORS in response - `fetchDidSucceed`, not added to queue
* case 2: 500 error thrown by the server, **invalid** CORS in response - `fetchDidFail`, **added to queue**

![image](https://user-images.githubusercontent.com/20644772/165920439-98e9d4d5-1402-4e61-a18f-27951499a0fa.png)

![image](https://user-images.githubusercontent.com/20644772/165920550-750879ae-7b1a-47c2-b9bb-3064c02b11a6.png)

![image](https://user-images.githubusercontent.com/20644772/165920661-cb0d4394-a97c-4d7a-86ab-d62805906320.png)

I am surprised that this scenario is not properly addressed by the community. Maybe it is I am just not aware of it?

So, I think I actually have 2 problems:

1. how to distinguish to-be-queued requests
2. distinguish false-positive failed requests where status code is read as 0

**Am I correct to assume that if 2. is fixed then we can use the status code to solve the 1.?** 

My proposed solution - on the server side it is possible to set the custom header such as `x-status-code` that will always have the exact value as the real status code. Now we just need to tell the fetch logic of the worker service to use this header as a reference to making decisions!

So the question is - is it possible to override the `fetch` event of the service worker and tell him to use the custom header to decide whether the request failed or not?

I am guessing default logic is something like 
```
try {
    fetch(request)
    fetchDidSucceed(request)
}
catch (error) {
    fetchDidFail(request, error)
}
```

but we need to change it to

```
var response;
try {
    response = await fetch(request)
    fetchDidSucceed(request)
}
catch (error) {
    if (response.hasHeader("x-status-code")) {
        fetchDidSucceed(request)
    }
    else {
        fetchDidFail(request, error)
    }
}
```

Then, when it's done, I should be able to use the `x-status-code` header on the client side to determine if the `fetchDidSucceed` or `fetchDidFail` is going to be executed - or even better - maybe `axios` will treat responses as success because I can force-override the response and set the correct/actual status code. Is this correct?

I will continue to dig to this direction while there is no answer to this topic. Please let me know if this is a wrong lead. Or maybe this problem has already been solved by smart minds :)

**Comment by jeffposnick** [comment]
Does this information from the [docs](https://developer.chrome.com/docs/workbox/modules/workbox-background-sync/#basic-usage) help explain what's going on?

> `BackgroundSyncPlugin` hooks into the [fetchDidFail plugin callback](https://developer.chrome.com/docs/workbox/using-plugins/), and `fetchDidFail` is only invoked if there's an exception thrown, most likely due to a network failure. This means that requests won't be retried if there's a response received with a 4xx or 5xx error status. If you would like to retry all requests that result in, e.g., a 5xx status, you can do so by adding a `fetchDidSucceed` plugin to your strategy:

```js
const statusPlugin = {
  fetchDidSucceed: ({response}) => {
    if (response.status >= 500) {
      // Throwing anything here will trigger fetchDidFail.
      throw new Error('Server error.');
    }
    // If it's not 5xx, use the response as-is.
    return response;
  },
};

// Add statusPlugin to the plugins array in your strategy.
```

I know that talks specifically about the `BackgroundSyncPlugin`, but all that plugin does is set up a `fetchDidFail`callback, which you're already doing manually.

**Comment by pavlexander** [comment]
If I understood this correctly - any non-0 status code is threated as failure.

According to my observations - fetch will return a 0 status code/failure when there is a CORS issue with the response. Even if the service itself has processed the request correctly. My question was how to override the fetch response or the logic for fetching so I could handle the false-positive responses..

I have made a discovery that when axios is used with the custom `timeout` value - this timeout value essentially cancel's out all of the logic executed by `workbox` handler.

So if the client makes a request and it fails because of the axios timeout - the client will see the error message before the `fetchWillFail` callback is executed. This raises all kinds of problems, such as - you are not able to modify the response in the services worker, because user has already gotten this response.. The solution to this problem is to ditch the timeout property of the axios and start using the `networkTimeoutSeconds` which is global for all requests. This seems to the downside to this approach that you can't override this value per-request since it's private and is per-strategy.

But this will allow me to move forward at least.
