### ISSUE TITLE
endless service worker updates after first registration without page refresh

### ISSUE THREAD

**Issue by pavlexander** [GoogleChrome/workbox#3076]
**Library Affected**:
"workbox-background-sync": "^6.5.3",
"workbox-core": "^6.5.3",
"workbox-precaching": "^6.5.3",
"workbox-window": "^6.5.3"

**Browser & Platform**:
tested on Edge

**Issue or Feature Request Description**:
After SW registers for the fist time (or user manually unregisters a worker and refreshes the page) -  all following sw version updates will be auto-activated (`skipWaiting` auto-triggered).

## steps to reproduce

1. `sw.js`
```
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";

//precacheAndRoute(self.__WB_MANIFEST);
precacheAndRoute([
  { revision: "87f48b43683c695c054d937e20ecf20e", url: "manifest.webmanifest" },
  {
    revision: "1ee7e898708ec49a4f654f623b0579b0",
    url: "assets/index.b806230e.css",
  },
  {
    revision: "74ee3f6b2f7277cd72e41755634f7871",
    url: "assets/index.f4169c83.js",
  },
  { revision: "de1a8c1e5f67be18ed4d254f00217ea6", url: "index.html" },
]);

cleanupOutdatedCaches();

```

2. app
```
import { Workbox, messageSW } from "workbox-window";

let wb;
let registration;
if (process.env.NODE_ENV === "production") {
  if ("serviceWorker" in navigator) {
    isServiceWorkerSupported.value = true;

    wb = new Workbox("/sw.js");

    wb.register({ immediate: false })
      .then((r) => {
        console.log("onRegistered", r);
        setInterval(() => {
          console.log("updating!!");
          r.update();
        }, 10000);
      })
      .catch((e) => {
        serviceWorkerRegistrationError.value = e.message;
        console.error(e);
      });
  }
}
```

3. build. Open app first time. Refresh window. **This is our starting point**.

![image](https://user-images.githubusercontent.com/20644772/166153747-339004f8-73a9-4ba1-93d1-479fcea3eb11.png)

4. Change code in app. Build. New SW version shown in chromium debugger:

![image](https://user-images.githubusercontent.com/20644772/166153763-8844c57d-b5da-4a10-8b71-a9cf4546d707.png)

**Verify: no auto-activation triggered.**

5. Change code in app. Build. New SW version shown in chromium debugger:

![image](https://user-images.githubusercontent.com/20644772/166153799-85f8a120-7984-4b8d-8972-1b3b746dc79e.png)

**Verify: no auto-activation triggered.**

6. Unregister service worker in debugger:

![image](https://user-images.githubusercontent.com/20644772/166153816-e8806f56-d6d8-426c-b749-a9b25677034f.png)

![image](https://user-images.githubusercontent.com/20644772/166153830-d7dca83f-d842-4add-bbdf-52dab083470b.png)

**Verify: worker status is stopped and deleted**

7. refresh browser window

![image](https://user-images.githubusercontent.com/20644772/166153849-a02d7e5f-2168-47fc-b2ef-a4d71aee537e.png)

**Verify: version of the website from the last build is shown. Latest sw worker is activated and running.**

8. Change code in app. Build.

![image](https://user-images.githubusercontent.com/20644772/166153897-e64ca689-316f-42ec-9847-da6c36d293bf.png)

**Verify [PROBLEM]: Service worker new version got auto-activated (old version of the website is still used, no page refresh was done).** 

9. Repeat step 8 as many times  as you want. New SW version will be activated (`skipWersion` triggered for us). Old site version will keep running until browser window refresh.

### why is this a problem?
Because on first page load - if user keeps using this page without refresh - it will keep updating (installing AND activating) to new version forever! I also think that refreshing the page on first activation is bad solution so please do not propose this.

You can verify this problem by opening an incognito window in browser and checking the service worker statuses after new builds (manual de-registration is just a hack if you don't want to deal with incognito)

Another issue is that according to documentation:

https://developer.chrome.com/docs/workbox/reference/workbox-window/

> update: function: Checks for updates of the registered service worker.

`update` function should only invoke new version updates checks, not activate them.

`update` function works fine as long as you have done the page refresh after first activation. If you didn't - then you deal with the problem from above. :)

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
