### ISSUE TITLE
Pass caught error to catch handlers

### ISSUE THREAD

**Issue by dirk** [GoogleChrome/workbox#3089]
**Library Affected**: workbox-routing

**Browser & Platform**: all browsers

**Issue or Feature Request Description**:

Routes' `catchHandler`'s and the top-level `setCatchHandler` handlers currently do not have access to the error that was caught. This makes it impossible to create a fallback handler which both a) handles uncaught errors/promise rejections from route handlers and b) reports those errors for analysis (eg. to logging, Sentry, etc.). The `err` is only logged via the Workbox `logger` outside of production, in production the promise rejection is effectively silently swallowed.

I'd like to expand the interface of `this._catchHandler.handle(...)` to allow it to also receive the promise rejection `err` it's handling so that that error can be reported:

https://github.com/GoogleChrome/workbox/blob/4e80b585144ab16b2d251ff38e1a638289097214/packages/workbox-routing/src/Router.ts#L303

In simplistic terms, it'd be nice if that line were to eventually look like:

```ts
return this._catchHandler.handle({
    url,
    request,
    event,
    error: err,
}); 
```

I've been working in TypeScript for years, so I'd be happy to code this up (in a backwards-compatible way) if this interface change sounds okay to y'all.

**Comment by jeffposnick** [comment]
That offer sounds great—thank you. I am trying to remember whether there was any reason why we didn't do this initially, and I can't think of one.

**Comment by phoneticallySAARTHaK** [comment]
Is there any progress on this?
I was trying to catch failed requests due to access token invalidation and this feature seems to be a useful use case for this

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
