### ISSUE TITLE
docs: incorrect description for networkTimeoutSeconds? 

### ISSUE THREAD

**Issue by dadamssg** [GoogleChrome/workbox#3091]
I see this [in the documentation](https://developer.chrome.com/docs/workbox/reference/workbox-build/#property-RuntimeCaching-options-networkTimeoutSeconds) which i don't think is correct(?). Or maybe i just don't understand why setting this would have anything to do with manipulating the `cacheName`. 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/881986/175381083-821be7b4-2a42-4b22-ba73-c3f51bbe6c49.png">

**Comment by jeffposnick** [comment]
Thanks! We'll get this typo fixed.

**Comment by dadamssg** [comment]
your PR makes a lot more sense 😄
