### ISSUE TITLE
'Got' dependency has security issue (dependabot)

### ISSUE THREAD

**Issue by keean** [GoogleChrome/workbox#3093]
**Library Affected**:
workbox-cli@6.5.3 (npm) 

**Browser & Platform**:
All

**Issue or Feature Request Description**:
Dependabot is reporting the following alert for a dependency of workbox-cli:

'got' (npm) allows a redirect to a UNIX socket

This is the dependency tree for this package:

workbox-cli@6.5.3
 update-notifier@4.1.3
  latest-version@5.1.0
   package-json@6.5.0
    got@9.6.0

The earliest fixed version is got@11.8.5

**Comment by marang** [comment]
please fix / bump versions

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
