### ISSUE TITLE
cache.add(precacheAndRoute) will block the main thread, such as network bandwidth?

### ISSUE THREAD

**Issue by mamumu123** [GoogleChrome/workbox#3098]
**Library Affected**:
_workbox-sw

**Browser & Platform**:
Chrome

**Issue or Feature Request Description**:
I thought it would  request resources when the main thread is idle.
![截屏2022-07-14 下午3 20 57](https://user-images.githubusercontent.com/19382362/178945916-2bd35950-183c-465a-acfd-8f0d2c89b17b.png)

I have a very simple example here. [example](https://mamumu123.github.io/sw-test/)
First of all, I copied this repo（ https://github.com/mdn/sw-test ）, it was very smooth.
Next, I made some changes. I add  1000 pictures(or more) in 'cache.add',   When reloading, then i  found that the main thread is block.

![截屏2022-07-15 上午9 30 37](https://user-images.githubusercontent.com/19382362/179130931-ddb3f433-3d18-4adf-aa57-f4a88d4d2cd1.png)

```js
+const lotList = [];
+for (let index = 1; index < 1000; index++) {
+  lotList.push(`/sw-test/gallery/${index}.jpg`);
+}
+
 const putInCache = async (request, response) => {
   const cache = await caches.open('v1');
   await cache.put(request, response);
@@ -69,6 +74,7 @@ self.addEventListener('install', (event) => {
       '/sw-test/gallery/bountyHunters.jpg',
       '/sw-test/gallery/myLittleVader.jpg',
       '/sw-test/gallery/snowTroopers.jpg',
+      ...lotList,
     ])
   );
 });
```

step: 
step1： add 1000 image,
step2: tick ‘update on reload’
step3: reload
Then, the above problem will recur

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
