### ISSUE TITLE
Is there the workbox-background-sync can update the ui?

### ISSUE THREAD

**Issue by kaiwenxiao** [GoogleChrome/workbox#3104]
For my case, I'm using ```GenerateSW``` mode for ```workbox-background-sync```

which my webpack.config.js look like this:
```pwa: {
    workboxPluginMode: 'GenerateSW',
    workboxOptions: {
      cacheId: 'pwa-sample',
      swDest: 'service-worker.js',
      clientsClaim: true,
      skipWaiting: true,
      runtimeCaching: [
        {
          urlPattern: new RegExp('^http://localhost:5000/'),
          // handler: 'StaleWhileRevalidate',
          handler: 'NetworkOnly',
          options: {
            cacheName: 'api',
            expiration: {
              maxAgeSeconds: 60 * 60 * 24
            },
            cacheableResponse: {
              statuses: [200, 304]
            },
            fetchOptions: {
              mode: 'cors',
            },
            matchOptions: {
              ignoreSearch: true,
            },
            // broadcastUpdate: {
            //   // All values here are optional:
            //   channelName: 'my-test-channel',
            // }
            backgroundSync: {
              name: 'my-queue-name',
              options: {
                maxRetentionTime: 60 * 60,
              },
            }
          }
        }
      ]
    }
  }```



Thanks. I can get the re-request, but not UI updated

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
