### ISSUE TITLE
README room for clarifications

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#311]
**Library Affected**:
sw-cli, sw-build

When coming to the README we present users with a number of options to get started including the following:

> Build process: Generate a service worker or manifest in your build process using sw-build.
> Command line: Generate a service worker or manifest from the command line.

I was using sw-precache from my package.json file where npm scripts are effectively my build process so am looking for an equivalent for that workflow. 

When I navigate to the sw-build docs, they present me with a workflow that would totally work if I was in Gulp (or another Node based build system). This is something we should make more clear - rather than `Build process` perhaps we should say `Gulp Build Process`? In the end I think it's the Command-line that I'm after.

What I might suggest is a breakdown based on what your workflow might be:

- npm scripts > cli
- gulp > sw-build
- webpack > sw-build
etc.

**Comment by jpmedley** [comment]
@addyosmani You'r losing me in the last paragraph and bullets. What does 'npm scripts > cli' mean? I'm not following your shorthand.

**Comment by jpmedley** [comment]
@addyosmani Pinging you about this again. First see the previous note. I have or will cover everything in the above ticket except: 

>What I might suggest is a breakdown based on what your workflow might be:
>
>npm scripts > cli
>gulp > sw-build
>webpack > sw-build
>etc.
