### ISSUE TITLE
Information on RFC 6750 » RFC Editor

### ISSUE THREAD

**Issue by RyMc315** [GoogleChrome/workbox#3112]
https://www.rfc-editor.org/info/rfc6750

**Comment by l3d00m** [comment]
Has this been opened by accident?

**Comment by RyMc315** [comment]
Yes

**Comment by lourivall** [comment]
Não muito obrigado

Em seg, 29 de ago de 2022 16:53, RyMc315 ***@***.***>
escreveu:

> Yes
>
