### ISSUE TITLE
Is it possible to set `ignoreVary: true` when using `precacheAndRoute`?

### ISSUE THREAD

**Issue by landtechjoe** [GoogleChrome/workbox#3113]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I might be missing a reason for why this isn't possible but I want to use `precacheAndRoute` but be able to pass a `matchOptions` property in the options so that I can include `ignoreVary: true`. I am currently seeing console warnings about it but can see that there is no way to do this with `precacheAndRoute` the only option is a lower level option consisting of constructing the cache and setting a strategy. Maybe I am missing something in the documentation as I feel this should be possible but can't see how.

**Comment by Ryandev** [comment]
Just wanted to add I'm having the same issue at the moment. 

However I've tried updating the PrecacheController:
```
    import { getOrCreatePrecacheController } from 'workbox-precaching/utils/getOrCreatePrecacheController';
    getOrCreatePrecacheController().strategy.matchOptions = {
        ignoreVary: true,
    };
    precacheAndRoute(self.__WB_MANIFEST);
```

& I've also tried constructing the precache controller instead
```
    const PreCacheController = new PrecacheController({
        cacheName: 'workbox-precache',
    });
    PreCacheController.addToCacheList(self.__WB_MANIFEST);
    sw.addEventListener('install', event => PreCacheController.install(event));
```

In both instances the precaching behaviour works, however I'm seeing the following warning

`
workbox The response for /c/demo/manifest.json?__WB_REVISION__=eb19e6c3a26b676cb7c4d223c197cda4 has a 'Vary: Accept-Encoding' header. Consider setting the {ignoreVary: true} option on your strategy to ensure cache matching and deletion works as expected.
`

The articles at: 
[https://developer.chrome.com/docs/workbox/modules/workbox-precaching/)](https://developer.chrome.com/docs/workbox/modules/workbox-precaching/)
[https://developer.chrome.com/docs/workbox/reference/workbox-precaching/#type-PrecacheStrategy](https://developer.chrome.com/docs/workbox/reference/workbox-precaching/#type-PrecacheStrategy)

Don't cover this use case.

Is there any way to pass `CacheQueryOptions` to the Precache behaviour?

**Comment by rizqirizqi** [comment]
Adding this works for me! Thanks!

```
import { getOrCreatePrecacheController } from 'workbox-precaching/utils/getOrCreatePrecacheController';
getOrCreatePrecacheController().strategy.matchOptions = {
  ignoreVary: true,
};
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
