### ISSUE TITLE
NavigationPreload responses won't stream in Firefox

### ISSUE THREAD

**Issue by broguinn** [GoogleChrome/workbox#3116]
Hello - writing from the PWA team at Etsy.

**Library Affected**:
workbox-streams

**Browser & Platform**:
Firefox 104.0.1
OSX 12.5.1

**Issue or Feature Request Description**:
We use workbox-streams to construct a response out of multiple `Promise<Response>` sources. One of these sources is the result of a navigationPreload request. This works fine in Chrome and Safari, but the request in Firefox never resolves (or hits the network).

This is pretty close to how our set-up is:

```ts
import { strategy } from "workbox-streams";

// and from inside a custom strategy...

strategy(
    [
        () => {
            const preloadResponse = await handler.event.preloadResponse;

            // If we have a preload response, and it's not a redirect, stream it.
            if (
                preloadResponse &&
                preloadResponse.body &&
                preloadResponse.type !== "opaqueredirect"
            ) {
                if (process.env.NODE_ENV !== "production") {
                    logger.log(
                        `Using a preloaded navigation response for ` +
                        `'${getFriendlyURL(incomingRequest.url)}'`
                    );
                }

                return preloadResponse;
            }
            
            // else, network request
        },
    ]
)
```

I'm guessing that the `concatenate` module in `workbox-streams` isn't handling whatever is unique about the preloadResponse's body, which I've confirmed is a ReadableStream. I can create a simpler example that just uses `concatenate` at some point.

It's also possible this is a bug with firefox, but I don't feel that I have enough context on what's different about that readable stream to confirm it.

Any help you can be here would be much appreciated. Thanks!

**Comment by jcbbb** [comment]
Hey @broguinn, does Firefox hang forever with this? I am having the same issue with it.

I have the following:

```js
const navigation_preload = workbox.navigationPreload;
const warm_strategy_cache = workbox.recipes.warmStrategyCache;
const register_route = workbox.routing.registerRoute;

navigation_preload.enable();

const swr_content_strategy = new StaleWhileRevalidate({ cacheName: "swr-content" });
const partial_content_strategy = new CacheFirst({ cacheName: "partials" });

warm_strategy_cache({
  urls: ["/partials/top.html", "/partials/bottom.html"],
  strategy: partial_content_strategy,
});

const swr_content_handler = workbox.streams.strategy([
  ({ event }) => partial_content_strategy.hande({ event, request: new Request("/partials/top.html") })
  ({ event }) => swr_content_strategy.handle(event),
  ({ event }) => partial_content_strategy.handle({ event, request: new Request("/partials/bottom.html") })
])

register_route(new Route(({ request }) => request.mode === "navigate", swr_content_handler)
```

The above example works on chromium browsers, but with error `preload request used before navigation settled` printed in the console. It happens probably because I am passing `event` to `partial_content_strategy.handle` function, but I cannot get it to work without passing that event.

Another approach is using `precache`. This way it works in every browser, but I cannot update precached html when user logs in or any other action that might require changing look of header or footer;
```js
precacheAndRoute([
  {
    url: "/partials/offline.html",
    revision: GLOBAL_VERSION + 1,
  },
  {
    url: "/partials/top.html",
    revision: GLOBAL_VERSION + 1,
  },
  {
    url: "/partials/bottom.html",
    revision: GLOBAL_VERSION + 1,
  },
]);

const swr_content_handler = workbox.streams.strategy([
  ({ event }) => matchPrecache("/partials/top.html"),
  ({ event }) => swr_content_strategy.handle(event),
  ({ event }) => matchPrecache("/partials/bottom.html"),
])
```

Anyone have any idea how to solve this? Or am I using workbox wrong? Any help or guidance would greatly be appreciated. Thanks.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
