### ISSUE TITLE
[workbox-window] `workbox.getSW()` returns a redundant service-worker after `workbox.update()`

### ISSUE THREAD

**Issue by cvolant** [GoogleChrome/workbox#3119]
**Library Affected**: workbox-window

**Browser & Platform**: all browsers

**Issue Description**:
Context: I run `workbox.update()` when `document.visibilityState` is back to `"visible"`, to update the service-worker even if the page is not reloaded.
The problem is, after that, `workbox.getSW()` returns the old redundant service-worker, and the following events are not detected.
I think that the problem comes from `updateLikelyTriggeredExternally` being calculated to `true` (because `onUpdateFound` already fired before, so `this._updateFoundCount` is more than 0).

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
