### ISSUE TITLE
[workbox-window] "Installing" event not firing

### ISSUE THREAD

**Issue by Miodec** [GoogleChrome/workbox#3123]
**Library Affected**:
workbox-window

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
When registering a service worker, im trying to detect the start of installation (precaching) using the "installing" event. All other events are working correctly like "installed", "activating", "activated"

Code:

```ts
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    const wb = new Workbox("/service-worker.js");


    wb.addEventListener("installing", (event) => {
      console.log("installing", event);
    });

    wb.addEventListener("installed", (event) => {
      console.log("installed", event);
    });

    wb.addEventListener("activating", (event) => {
      console.log("activating", event);
    });

    wb.addEventListener("activated", (event) => {
      console.log("activated", event);
    });

    console.log(wb);

    wb.register();
    // }
  });
}
```

```ts
...
new WorkboxPlugin.GenerateSW({
      // these options encourage the ServiceWorkers to get in there fast
      // and not allow any straggling "old" SWs to hang around
      clientsClaim: true,
      skipWaiting: true,
      //include the generated css and js files
      maximumFileSizeToCacheInBytes: 11000000,
    }),
...
```

How can i detect that there is an update available and that it started pre caching the necessary files? 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/13181393/195215000-5b3c79f9-9d6c-4d0d-89fc-56588643b5be.png">

**Comment by Doctor-wu** [comment]
Same problem for me

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
