### ISSUE TITLE
precache unconditionally removes old assets upon activation breaking existing tabs

### ISSUE THREAD

**Issue by robbytx** [GoogleChrome/workbox#3126]
**Library Affected**: workbox-precaching
**Browser & Platform**: all

**Issue or Feature Request Description**:
If I generate a service worker that uses `skipWaiting` in order to immediately starting serving new assets upon browser reload, then the new service worker [unconditionally removes other assets](https://github.com/GoogleChrome/workbox/blob/48f53f7/packages/workbox-precaching/src/PrecacheController.ts#L258) from the precache upon activation, potentially breaking any browser tabs that were loaded from an earlier service worker.  

While this is a relatively well-known problem mentioned in the [service worker lifecycle documentation](https://developer.chrome.com/docs/workbox/service-worker-lifecycle/):
> Tip: You can speed up activation of updated service workers by calling [self.skipWaiting](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting), but this may be a bad idea. The old service worker may have handled fetches during page startup, but the new service worker then takes control later on. This can break [stuff like lazily-loaded subresources](https://dev.to/jeffposnick/paying-attention-while-loading-lazily-45ef) until the next navigation request.

It strikes me that, for an app whose build process creates immutable artifacts through the use of unique URLs, this problem could be mitigated by simply leaving old assets in the precache until a later point at which older tabs have closed.

In order to implement such a solution while using `generateSW`, I would like to have some option that can skip the precache cleanup logic.

**Illustration**:
When my app is loaded in a new tab, the service worker activates and updates the precache, including pruning other assets:
<img width="1037" alt="Screen Shot 2022-10-19 at 12 52 44 PM" src="https://user-images.githubusercontent.com/1022789/196767562-f231af3a-7953-4af6-b152-3a9d63eaca9a.png">

If I switch back to another tab that was already open, and attempt to access some asset that is imported dynamically, I get a loading error because the asset was purged, and the app is unexpectedly broken:
<img width="1120" alt="Failed to load chunk" src="https://user-images.githubusercontent.com/1022789/196767319-cd18610b-8af4-4e5e-b696-4641662580f8.png">

**Comment by robbytx** [comment]
Minor clarification:  I'm testing against Workbox 5.1.4 via the latest version of [ember-cli-workbox](https://github.com/BBVAEngineering/ember-cli-workbox), although I linked to the v6 code in the description that has the same logic.

FWIW I was able to workaround this issue by monkey-patching the activate function using `inlineWorkboxRuntime: true` and the following file passed to `importScripts`:
```js
logger.log('Patching PrecacheController.activate to workaround https://github.com/GoogleChrome/workbox/issues/3126');
PrecacheController.prototype.activate = () => {}
```

**Comment by robbytx** [comment]
In debugging this, I got myself into a perverse combination with Workbox 5 and non-`production` mode such that the new service worker no longer activated immediately (see https://github.com/GoogleChrome/workbox/issues/2302#issuecomment-1285705607).  I'm leaving this comment to warn anyone who may be tempted to do the same in applying my workaround.

**Comment by robbytx** [comment]
Following is an improved script that defers running cleanup (and updates `_urlsToCacheKeys` to serve legacy urls) until all pre-existing clients have closed:
```js
/* globals PrecacheController, logger */
(function deferPrecacheCleanup() {
  /*
   * Intercept PrecacheController.install() in order to populate its _urlsToCacheKeys map so that
   * it can retrieve the cached assets if it receives a request from an existing client.
   */
  const originalInstall = PrecacheController.prototype.install;
  PrecacheController.prototype.install = async function patchedInstall() {
    const result = await originalInstall.call(this);
    await preserveCacheKeys(
      this._urlsToCacheKeys || this[/\breturn this\.(\w+)/.exec(PrecacheController.prototype.getURLsToCacheKeys.toString())[1]],
      this._cacheName || this[/\bself.caches.open\(this\.(\w+)\)/.exec(originalInstall.toString())[1]]
    );
    return result;
  }

  let removeLegacyUrls;
  async function preserveCacheKeys(urlsToCacheKeys, cacheName) {
    const cache = await self.caches.open(cacheName);
    const legacyUrlsPreserved = [];
    (await cache.keys()).forEach(request => {
      const cacheKey = request.url;
      const url = new URL(cacheKey, location.href);
      url.searchParams.delete('__WB_REVISION__');
      const originalUrl = url.href;
      if (!urlsToCacheKeys.has(originalUrl)) {
        urlsToCacheKeys.set(originalUrl, cacheKey);
        legacyUrlsPreserved.push(originalUrl);
      }
    });
    removeLegacyUrls = () => legacyUrlsPreserved.forEach(url => urlsToCacheKeys.delete(url))
  }

  /*
   * Replace PrecacheController.activate() with a function that captures the ids of clients that may have loaded
   * prior to this service worker being activated, so we can defer cleanup until all such clients are closed.
   */
  const originalActivate = PrecacheController.prototype.activate;
  let originalClientIds, precacheController;
  PrecacheController.prototype.activate = async function patchedActivate() {
    precacheController = this;
    originalClientIds = new Set((await self.clients.matchAll()).map(client => client.id));
    if (originalClientIds.size) {
      log('Deferring precache cleanup due to pre-existing clients', originalClientIds);
    } else {
      performCleanup();
    }
  }
  log('Patched PrecacheController to workaround https://github.com/GoogleChrome/workbox/issues/3126');

  function onFetch(event) {
    if (event.request.mode === 'navigate' && originalClientIds) {
      pruneRemainingClients();
    }
  }
  self.addEventListener('fetch', onFetch);

  function pruneRemainingClients() {
    originalClientIds.forEach(async(clientId) => {
      if (!(await self.clients.get(clientId))) {
        originalClientIds.delete(clientId);
        log('Removed ' + clientId + ' from pre-existing clients', originalClientIds);
        if (!originalClientIds.size) {
          performCleanup();
        }
      }
    })
  }

  function performCleanup() {
    self.removeEventListener('fetch', onFetch);
    removeLegacyUrls();
    log('Performing precache cleanup now');
    originalActivate.call(precacheController);
  }

  function log() {
    if (typeof logger !== 'undefined' && typeof logger.debug === 'function') {
      logger.debug.apply(logger, arguments);
    }
  }
})();
```

Build requirements:
 * This requires `inlineWorkboxRuntime: true` so the `PrecacheController` is in scope of the imported script.
 * This also requires the `PrecacheController` class name to exists as-is, i.e. to not be mangled as is the default in `production` mode.  Either use a different mode or update the [mangle options](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/src/lib/bundle.ts#L75) to include `reserved: ['PrecacheController']`

**Note:** 
This implementation checks for missing clients only when some controlled window is navigated, so it may not clean up as aggressively as possible in the following scenarios.
   * It receives no notice when a client window is closed or navigated out of scope.
   * The lack of browser support for [replacesClientId](https://caniuse.com/?search=replacesClientId) prevents it identifying the reload or navigation of existing window, so it cannot determine that the existing client will soon be closed.  It takes another reload or other navigation fetch event before it can detect that the original client was closed.
   * It does not attempt to detect fetch events from reloaded workers.

If desired this could be improved through the use of a timer that periodically checks the remaining clients.

**Comment by robbytx** [comment]
It's probably worth addressing why one would precache assets that are loaded dynamically by the application.  Certainly precaching will force the assets to be downloaded automatically, so network bandwidth and its consequent impact on load time is essentially the same as if the assets were statically loaded into the app.  

Even so I think it is still valuable to defer loading assets unnecessarily into the app, since it relieves the browser of the need to parse and execute them on page load, which may be non-trivial for larger assets, and can improve page load times and memory consumption.

**Comment by robbytx** [comment]
Updates for v6 in `patchedInstall` and `performCleanup` to pass `event` argument into original install/activate methods (as well as changing `this._cacheName` to `this.strategy.cacheName`):
```js
  const originalInstall = PrecacheController.prototype.install;
  PrecacheController.prototype.install = async function patchedInstall() {
    const result = await originalInstall.apply(this, arguments);
    await preserveCacheKeys(
      this._urlsToCacheKeys || this[/\breturn this\.(\w+)/.exec(PrecacheController.prototype.getURLsToCacheKeys.toString())[1]],
      this.strategy.cacheName || /\bself.caches.open\(this\.([\w.]+)\)/.exec(originalActivate.toString())[1].split('.').reduce((obj, key) => obj[key], this),
    );
    return result;
  }

  ....

  function performCleanup() {
    self.removeEventListener('fetch', onFetch);
    removeLegacyUrls();
    log('Performing precache cleanup now');
    originalActivate.call(precacheController, new ExtendableEvent('activate'));
  }
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
