### ISSUE TITLE
sw-cli: document workflow for sw-precache users

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#313]
**Library Affected**:
sw-cli

My old workflow using sw-precache to generate a SW for each run of my build process for a particular app used to look a little like this:

```js
./node_modules/sw-precache/cli.js --root=public --config=sw-precache-config.json
```

Reading through the sw-cli docs, something that might be useful is explaining if your old workflow relied on doing this in a fully automated way with the above approach the new strategy is to walk through the wizard to generate your SW.

**Comment by gauntface** [comment]
This should be covered by https://developers.google.com/web/tools/workbox/v3/guides/precache-files#using_the_workbox_command_line_interface

We still have a bug open for the migration story which is more like to cover the (I use sw-precache, how do I switch), so going to close this in favor of that.
