### ISSUE TITLE
Workbox - How can i get the latest response instead of the proxied response that is proxied by workbox/service worker?

### ISSUE THREAD

**Issue by yichulau** [GoogleChrome/workbox#3131]
**Library Affected**:
Workbox

**Browser & Platform**:
workbox/service worker compatible browsers

**Issue or Feature Request Description**:
Context: Every single time i submit a data, i will call back a getData request to refresh my latest data. However, after implementing workbox, my data is not refreashed as shown in the screenshot

Currently workbox is proxying my get request, how can make it where i will get the latest get request, instead of retrieving from the previous get request that has been cached by workbox? 

![Screenshot 2022-11-08 162038](https://user-images.githubusercontent.com/39252336/200776166-d62f179f-d9b2-45ba-8033-cbd24aa3d5f9.png)

**Comment by tropicadri** [comment]
Add a route that responds with a [network only](https://developer.chrome.com/docs/workbox/modules/workbox-strategies/#network-only) strategy to the resource that you always want to be the latest version of.
