### ISSUE TITLE
Error when register service worker made with workbox-build

### ISSUE THREAD

**Issue by mihanizm56** [GoogleChrome/workbox#3133]
**Library Affected**:
"workbox-build": "6.5.4"
generateSW method used

**Browser & Platform**:
Google Chrome 106.0.5249.119 Linux

**Issue or Feature Request Description**:
My app can not register new sw due to deprecation
https://chromestatus.com/feature/5748516353736704

![image](https://user-images.githubusercontent.com/37120827/201137864-b88b6bbd-b532-4308-aece-acc757b0f702.png)

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
