### ISSUE TITLE
offlineFallback does not work with navigationPreload on Firefox

### ISSUE THREAD

**Issue by markokimpel** [GoogleChrome/workbox#3134]
**Library Affected**:
_workbox-recipes, workbox-navigation-preload, workbox-strategies_

**Browser & Platform**:
_Firefox 107.0 on Win, Firefox Android 107.1.0_

**Issue or Feature Request Description**:
_I am pretty much using the [Offline fallback](https://developer.chrome.com/docs/workbox/modules/workbox-recipes/#offline-fallback) recipe but with workbox-navigation-preload. This works fine for Chrome, Edge and Safari - the offline page is shown if there is no network connectivity - but it does not work for Firefox. On Firefox the standard offline error page is shown._

```javascript
"use strict";

importScripts("https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js");
workbox.setConfig({ debug: true });

const { setDefaultHandler } = workbox.routing;
const { NetworkOnly } = workbox.strategies;
const { offlineFallback } = workbox.recipes;
const navigationPreload = workbox.navigationPreload;

setDefaultHandler(new NetworkOnly());
offlineFallback();

navigationPreload.enable();
```

Demo: https://redcliff.de/sw-test/offlineFallback-navigationPreload-workbox/

**Comment by markokimpel** [comment]
I suspect the following code in StrategyHandler.fetch is the culprit:

```javascript
    if (
      request.mode === 'navigate' &&
      event instanceof FetchEvent &&
      event.preloadResponse
    ) {
      const possiblePreloadResponse = (await event.preloadResponse) as
        | Response
        | undefined;
      if (possiblePreloadResponse) {
        if (process.env.NODE_ENV !== 'production') {
          logger.log(
            `Using a preloaded navigation response for ` +
              `'${getFriendlyURL(request.url)}'`,
          );
        }
        return possiblePreloadResponse;
      }
    }
```

On Chrome, Edge and Safari `await event.preloadResponse` throws a network error if there is no connectivity. On Firefox event.preloadResponse resolves to a Response object with type 'error'. Thus the catch handler does not get invoked, the error response is handed to the browser, showing the standard offline error page.

Demo: https://redcliff.de/sw-test/preloadResponse-offline-simple/

IMO a check for `possiblePreloadResponse.type === 'error'` should be added and an error thrown to invoke proper handling. LMK if you agree and I can work on a PR.

**Comment by markokimpel** [comment]
Opened a [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1802711) with Mozilla to see if they think the Firefox behavior should be changed.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
