### ISSUE TITLE
workbox seems to drop the authorization header for NetworkOnly() requests on Google Nest Hub (2nd gen)

### ISSUE THREAD

**Issue by chiahsing** [GoogleChrome/workbox#3135]
**Library Affected**:
not sure

**Browser & Platform**:
Chrome/90.0.4430.225
Google Nest Hub (2nd gen)

**Issue or Feature Request Description**:
I noticed that when the main thread issues a request via the service worker, the authorization header is dropped unexpectedly, which casues the server to reject the request.

The screenshots of the headers of the request from the debug console:

main thread: https://paste.pics/6d5a1b3b8d8390dee3e1ce4fd5f5ed46
service worker: https://paste.pics/5d7baa15fc7dd5ad7a812892a8ec4aba

I can see that the `authorization` header clearly is not set in the request sent by the service worker.

The service worker code is here: https://github.com/home-assistant/frontend/blob/cb97918005ca0b2b4f47bd2cd77b698449d49e9f/src/entrypoints/service_worker.ts
At line 41, it registers the URLs with /api/.* (which matches the problematic request above) to be NetworkOnly().

The service worker registration code is here: https://github.com/home-assistant/frontend/blob/cb97918005ca0b2b4f47bd2cd77b698449d49e9f/src/util/register-service-worker.ts

Note that the same code works on the desktop version of Chrome (Linux), but it fails on Google Nest Hub (2nd Gen)

**Comment by chiahsing** [comment]
I think I have a minimal reproducible example here: https://github.com/chiahsing/chiahsing.github.io/tree/main/workbox

I use DashCast to cast "https://chiahsing.github.io/workbox/" (force=true) to my Nest Hub, and then click the test button.

The authorization header was set in the main thread request, but dropped in the service worker request. In this example, the request was still successful because it doesn't check the authorization header anyway. But for a real world use case, this would results to an unauthorized error.

Note that the Chrome browser on my Linux desktop does not have this issue.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
