### ISSUE TITLE
deprecated rollup-plugin-terser@7.0.2

### ISSUE THREAD

**Issue by PeterNelsonT** [GoogleChrome/workbox#3136]
**Library Affected**:
workbox-build

**Issue or Feature Request Description**:
deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

**Comment by avinmaster** [comment]
+++

**Comment by rtritto** [comment]
`package.json` to update:
- [/packages/workbox-build/package.json](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-build/package.json)
- [/package.json](https://github.com/GoogleChrome/workbox/blob/v6/package.json)

**Comment by Mister-Hope** [comment]
Is there any plan to fix this?

Maybe it's time to drop node<14 and update the whole project toolchain?

**Comment by ykute07** [comment]
> **Library Affected**: workbox-build
> 
> **Issue or Feature Request Description**: deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

How should I solve this exactly?

**Comment by tropicadri** [comment]
duplicate #3200
