### ISSUE TITLE
workbox ignoreURLParametersMatching  config not applay

### ISSUE THREAD

**Issue by felek000** [GoogleChrome/workbox#3138]
Hello,
I try to add some ignore to precache.
I use quasar as meta framework

```
//should not be in pre cache but it is
        cfg.ignoreURLParametersMatching = [/404/]
// should be in pre cache and it is
        cfg.additionalManifestEntries = [
          'aaa.png'
        ]

```
```
....
 { url: '404.png', revision: 'ce7e28ccabe62bcc628bf3e7a907f3cd' },
{ revision: null, url: 'aaa.png' }
```

Am i add some think wrong here ?
I want to create regex to match routes but this simple options seems not affect output at all

Thanks

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
