### ISSUE TITLE
types don't work with `exactOptionalPropertyTypes` codebases

### ISSUE THREAD

**Issue by dwelle** [GoogleChrome/workbox#3141]
Certain types in this codebase are written in a way that don't compile in codebases which have `exactOptionalPropertyTypes` enabled.

In particular, it's the workbox plugins that define their properties using the [WorkboxPlugin interface](https://github.com/GoogleChrome/workbox/blob/v6/packages/workbox-core/src/types.ts#L254). Their properties optionality must be aligned with the interface otherwise their instances won't be assignable to `plugins` array [here](https://github.com/GoogleChrome/workbox/blob/95f97a207fd51efb3f8a653f6e3e58224183a778/packages/workbox-strategies/src/Strategy.ts#L37), for example.

I have a diff for the changes necessary: https://github.com/dwelle/workbox/commit/5e3685299a8dcbd2e790904d25683be047c00602

But I'm sure it affects the codebase elsewhere, too.

Playground illustrating the issue: https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.9.4#code/JYOwLgpgTgZghgYwgAgAoBsCuBzUBJcaeJZAbxDgFsIB+ALmQGcwpRsBfAWACgeATCAnRwoKIXEaNkAZQD21DDlBkeyZBWoNFuEAUixEEANoAiDRBMBdANw8uvbglkhmyAA5YdyALzqIAdxl5CG1QAAoASh4eJxcwZFiYYGwGUg8lFy1PfEIDJCNLdh8ydJ1GBiNS0EKeIA

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
