### ISSUE TITLE
[Question] Maintain status [Answer] Yes!

### ISSUE THREAD

**Issue by Mister-Hope** [GoogleChrome/workbox#3149]
I am sure not only myself is curious about the project status.

The last commit is in Augest, and it seems that nobody is handling issues since July.

Also, no progress are made in [workbox v7 milestone](https://github.com/GoogleChrome/workbox/milestone/10 ) and also not seeing any plans after months that all Node LTS versions support ESM.

A lot of toolchain is targeting ESM now and the community perhaps is ready for packages requires Node14+

So my concern is:

1. Is this project deprecated? If so: Q2 If not Q3
2. Is there any alternatives
3. is there any active maintainer or is there any maintainer for this project now? If so Q4 if not Q5
4. Is there any plan for v7 and is there any timetable for it?
5. Since the docs are served by google and workbox is under googlechrome repo, I am not regarding this project as a full communify one. Does any related team has plans to remain its maintainance? Or what's the future plan for this project?

Thanks if anyone can give some answers to it. Special mention @jeffposnick here.

**Comment by jeffposnick** [comment]
Hello!

I left Google in August, so one of my former coworkers would be in a better position to comment on the current plans: @tropicadri, @petele, @PaulKinlan

**Comment by manuelc2209** [comment]
Bump

**Comment by Mister-Hope** [comment]
@tropicadri @petele @PaulKinlan can anyone leave a msg about this? Who is taking control of this project? Do you guys needs outside collaborators to maintain this project for you? Can we update major deps to drop node 12 and node 14 in near future?

**Comment by nickchomey** [comment]
I'm also very curious about this as I start to develop a PWA upon Workbox... The complete lack of communcation from Google is concerning...

**Comment by csvan** [comment]
@tropicadri @petele @PaulKinlan, sorry for the repeat pings, but would you be able to at least confirm whether or not there is an active roadmap for this project on the Google end of things? Workbox is a critical dependency for many of us in the community, and we would be happy to help out if you want to delegate work.

**Comment by Mister-Hope** [comment]
Yeah, even if Google want to drop this project, it could be better to have a fork running under community

**Comment by manuelc2209** [comment]
@tropicadri @petele @PaulKinlan @jeffposnick can anyone provide an answer to this thread please?

**Comment by tropicadri** [comment]
I am so sorry for the radio silence here. I am the maintainer for Workbox at the moment. I indeed do not have a lot of bandwidth right now. There are no plans for v7 at the moment. We are committed to any critical fixes. Right now I'm working on upgrading the TS version which is causing some typing issues when other projects update. If any one from the community is interested in helping I can coordinate getting the changes in.

**Comment by nickchomey** [comment]
@tropicadri Thanks for the update. 

Given the complete absence of resources from Google for this (which is, of course, their prerogative), it seems that ownership (or at least maintenance) of Workbox should be transferred to the community - there appear to be many motivated and capable people here who would like to do so. 

We could obviously fork the repo, but I believe that we would lose the issues and PRs like that, and it would surely break/decouple from countless downstream projects and packages as well.

So, could this issue please be re-opened for discussing all of this? Anything that you or others at Google can do to help facilitate the revival of this wonderful library (that many people poured so much effort into) would be greatly appreciated.

**Comment by tropicadri** [comment]
@nickchomey what's the best way to get in contact with people interested supporting the project as a community effort?

**Comment by nickchomey** [comment]
I don't have a clue, but I'm glad there's interest in it! 

Maybe a new Issue called something like Call for Maintainers, with some sort of template or other mechanism for cleanly receiving and evaluating candidates and other suggestions? You could then add a link to it in each open issue and PR? 

Perhaps also a post in web.dev/blog asking for Maintainers? (maybe even with the requisite explanation of why Google is effectively abandoning this core part of web tech, which even Apple is finally starting to embrace with Push Notifications in Safari...)

Surely, though, plenty of people within Google have ideas for and experience with this sort of thing?

**Comment by nickchomey** [comment]
Here's some possibly useful resources
- https://seeking-maintainers.net/
- https://adoptoposs.org/
- https://github.com/pickhardt/maintainers-wanted
- https://github.com/garritfra/seeking-maintainers.net
- https://dev.to/paulgoetze/announcing-adoptoposs-org-255f
- https://www.fastruby.io/blog/open-source/guide-for-unmaintained-open-source-projects.html
- https://opensource.guide/best-practices/#share-the-workload
- https://opensource.guide/building-community/#share-ownership-of-your-project
- https://github.blog/2023-04-03-calling-all-open-source-maintainers/

**Comment by Mister-Hope** [comment]
I can surely help.

I think the first thing you need to do is to build a clear  project board, to see if others can pick some job.

E.g.:

- moving to npm workspace or pnpm/yarn
- Update outdated deps to target Node18 (including deprecated deps)
   
   This can be sperated to a list of jobs to, e.g.: rollup4, typscript5, etc.

- Migrate existing code database to ESM

- Reviewing existing prs and working on issues

- Another clear roadmap plan for v7, 

Adding new feature plans and bug fixes and publishing alpha versions on timeline.

The project is absolutely lacking of maintenance, and I am pretty sure that it would be better to do the following to make most users happy:

- Create a new "v8" branch targeting Node18 and ESM, and release v8 alpha versions while we add and improve  features


If google team can have more people hande this, everything could be easier, but if not, without a clear roadmap and a clear project board, how can the community help you?

Plz at least let someone be a leader and give the community a project board containing a clear roadmap of changes and plans.

**Comment by chaffeqa** [comment]
I would also be interested in contributing to this project.  I think at this point it would make a lot of sense to source this out to be a community project (given the resource constraint in this area at google, understandable!  Google has done so much for the community IMO with projects like this!)

If I were to recommend one of the above options, it looks like from https://github.blog/2023-04-03-calling-all-open-source-maintainers/ that github is making a way forward in this area.

**Comment by kodai3** [comment]
Even the easy fix for deprecated dependency with approved PR has been left behind for months.
How is this topic going?

**Comment by nickchomey** [comment]
The complete lack of communication is disappointing. Apparently Workbox hasn't been deprecated, but given that Google has essentially unlimited resources but can't even give status updates on this (let alone set the stage for community maintenance) for over a year means it certainly has been abandoned...

I suppose the library works still, but it would have been nice for it to be able to continue to evolve or even just keep up with the times.

**Comment by manuelc2209** [comment]
> The complete lack of communication is disappointing. Apparently Workbox hasn't been deprecated, but given that Google has essentially unlimited resources but can't even give status updates on this (let alone set the stage for community maintenance) for over a year means it certainly has been abandoned...
> 
> I suppose the library works still, but it would have been nice for it to be able to continue to evolve or even just keep up with the times. 

It wasnt deprecated but at the same time, they cant enforce it through stores, both google & apple. If no monetization is envolved, it gets left to die apparently.

**Comment by csvan** [comment]
Any chance of Workbox getting a sustainable roadmap in 2024?

**Comment by jeffposnick** [comment]
CC: @tropicadri, @petele, @PaulKinlan for visibility.

**Comment by Mister-Hope** [comment]
I would like to reference my comment as well.
 https://github.com/GoogleChrome/workbox/issues/3149#issuecomment-1504814419

I believe there are people like me willing to help.

**Comment by DuCanhGH** [comment]
Given the radio silence over the past year, I figured it would be nice to do a bit of shameless plugging here. I'd like to invite some willing contributors to [Serwist](https://9-0-0.serwist.pages.dev) (Serwist -> SW, Service (workers), Swiss), a fork of Workbox initiated in October last year. It is not marked as a fork (doing so interferes with GitHub Search), but the commit history is kept intact. At the moment, after a lot of work has been poured into the project, the differences between Workbox and Serwist are fairly noticeable:

- Serwist is a pnpm monorepo powered by Turborepo, mostly written in TypeScript, whereas Workbox is a lerna monorepo with JS taking up around 67,3% of the codebase.
- Merged most service worker packages into one package, `serwist`, and deprecated them.
- GenerateSW has been removed. InjectManifest and GetManifest are now the only supported modes. `serwist.Serwist` is a replacement for GenerateSW, `PrecacheController`, and `Router`.
- Serwist doesn't ship a CDN build. Not sure whether it works with cdnjs, jsdelivr,... though.
- Serwist has built-in integrations for Next.js, SvelteKit, Nuxt,  and Vite and plans to extend this support to Remix and Astro as well (these are forks of `@ducanh2912/next-pwa` and Vite PWA's projects).
- Serwist is an ESM-only package, whereas Workbox is a CJS one.
- Serwist only supports Node.js >= 18 and TypeScript >= 5.
- Serwist ships declaration maps.
- Serwist has implemented a few parts of the Workbox v7 milestone (concurrent precaching, renamed `RuntimeCaching.urlPattern` to `RuntimeCaching.matcher`).
- Serwist uses Zod instead of AJV.
- Serwist is missing a lot of tests and examples. Would love some help with this one!

Would love some help on fixing some of Workbox's opened issues that apply to Serwist as well and implementing some more of the Workbox v7 milestone!
  - Make `revision` optional when `integrity` is set in precache manifest?

![Jeff's star](https://github.com/GoogleChrome/workbox/assets/75556609/d1f3f731-9598-4ac5-bb8f-e8a8b6d2b651)

P/s: got Jeff's star! Really proud of this one.

**Comment by tropicadri** [comment]
I am grateful for the community that has been finding alternatives. I am sorry we haven't been able to staff Workbox properly in the past year. For 2024 the Chrome DevRel team is actively working on a plan for the future of Workbox. My hope is it ends up in the hands of an engineering team that can dedicate the time it deserves and that can engage the community as it deserves. My apologies once again for not having more definitive news yet. 

cc @tomayac for visibility.

**Comment by chaffeqa** [comment]
Thanks @tropicadri for the update! Figured, just wanted to pass on our thanks for all the work you (and Google) have put into this area, it's not unnoticed!

**Comment by nickchomey** [comment]
Thanks for the update! 

I'd just like to reiterate that if Google isn't able to dedicate engineering resources towards Workbox (which is fine), would they at least be willing to move towards some sort of community stewardship arrangement? Lots of capable people have offered their assistance

**Comment by tropicadri** [comment]
Yes that is an option being considered.

**Comment by nickchomey** [comment]
Hey folks, apologies if this feels like spam. But, in one week, Apple will be killing Progressive Web Apps in the EU so as to maintain their App Store extortion racket. If they have their way, it won't even matter much for many people if Workbox revives or not!

The Open Web Advocacy group is leading the fight against this, and has launched this open letter which has gained nearly 2000 signatures in the first day.

Please sign the letter and spread the word far and loud!

https://letter.open-web-advocacy.org/

Edit: We won! https://open-web-advocacy.org/blog/apple-backs-off-killing-web-apps/

**Comment by tomayac** [comment]
Hey all,

I wanted to thank you all for your patience with the team while we were looking for new owners for the project. It's with great pleasure that I can pre-announce today that we have found an internal team at Google that will take over ownership of Workbox in the next couple of weeks. I will follow up with more details soon, but wanted to let you know the good news now, so you can continue planning with and counting on Workbox. `<3`

Cheers,
Tom

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Comment by pavlexander** [comment]
Hey

sorry to bring this topic up again but after reading the discussion from start to an end I still do not understand the state of the project. It seemed like the team to maintain the project was found, but the latest release was back in April 24. In other words since the new team takeover not a single new version was released in 5+ months.

not trying to be ungrateful, just genuinely wish to know if what @tomayac said is still true and we can still expect the project development to continue..

**Comment by tomayac** [comment]
Google's Aurora team _is_ the new owner. For example, @khempenius has fixed a critical dependency bug in https://github.com/GoogleChrome/workbox/pull/3359 recently. (Though it looks like this wasn't released to npm yet. I have just [pinged](https://github.com/GoogleChrome/workbox/pull/3359#issuecomment-2401760801) the thread to ask the team do.)
