### ISSUE TITLE
Migration from sw-precache to generateSW

### ISSUE THREAD

**Issue by KubaLorenc** [GoogleChrome/workbox#3152]
**Library Affected**:
workbox-webpack-plugin

**Issue or Feature Request Description**:
In the documentation regarding migrating from sw-precache https://developer.chrome.com/docs/workbox/migration/migrate-from-sw/
there is mentioned that **staticFileGlobs**  has been renamed to **globPatterns**, but unfortunatelly I have no luck with it. After renaming I get the following error
_ERROR in Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] 'globDirectory' property is not expected to be here. Did you mean property 'directoryIndex'?_
I was succesfull with migrating all the other propeties from sw-precache but this one is giving me problems.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
