### ISSUE TITLE
WARN deprecated rollup-plugin-terser@7.0.2: WARN deprecated sourcemap-codec@1.4.8:

### ISSUE THREAD

**Issue by jwbrede2217** [GoogleChrome/workbox#3154]
npm install workbox-build

Package.Json
`{
"name": "1.-npm-install-workbox-build",
"version": "1.0.0",
"main": "app.js",
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"keywords": [],
"author": "",
"license": "ISC",
"description": "",
"dependencies": {
"express": "^4.18.2",
"workbox-build": "^6.5.4"
}
[}`

**Comment by GamerBene19** [comment]
I experience the same warning
```
warning next-pwa > workbox-webpack-plugin > workbox-build > rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
warning next-pwa > workbox-webpack-plugin > workbox-build > @rollup/plugin-replace > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

seems like this package has to switch to `@rollup/plugin-terser` and `@jridgewell/sourcemap-codec` to fix this issue.

**Comment by emilbonnek** [comment]
Getting the same error.
```
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```
Using version 6.5.4

**Comment by tropicadri** [comment]
duplicate #3200
