### ISSUE TITLE
'Uncaught (in promise) bad-precaching-response' - error triggered by nuxt build module

### ISSUE THREAD

**Issue by Spencer-Sch** [GoogleChrome/workbox#3168]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
All browsers

**Issue Description**:
Project builds and runs free of errors with `npm run dev` and `npm run build / npm run start`.

When pushed live I get: 
(see screen shots for details)
- "Runtime Error" status code 500 
- "Uncaught (in promise) bad-precaching-response" status code 500
- A status code 500 error linked to "?standalone=true" initiated by workbox-core.prod.js
- Sometimes I get "Not Found" status code 404 linked to "favicon.ico" initiated by workbox-core.prod.js

If I remove `'@braid/vue-formulate/nuxt'` from the buildModules array in nuxt.config.js and push live the site works without error.
I tried a different form library (Vueform) after uninstalling vue-formulate from the project. I got the exact same errors and, again, the issue would be resolved if I removed the reference to the library from the buildModules array.

I turned on workbox debug mode through the `@nuxtjs/pwa` options in nuxt.config.js `pwa.workbox.config.debug = true`
Now workbox debug is giving me "Service worker installation failed. It will be retried automatically during the next navigation." (see screen shots)

With workbox debug on and pushing a version of the site I know works I get a successful precache for "site-url/?standalone=true" (see screen shots)

Any help toward a solution would be welcome; I am at a loss.
I'm happy to provide any additional info if necessary.

**Attempted solutions:**
Delete package-lock.json and node_modules folder and run `npm install`.
In nuxt.config set `pwa.manifest.start_url = ''`

**Project Details:**
```
package.json

"dependencies": {
   "nuxt": "^2.15.8",
   "vue": "^2.7.10",
   "@nuxtjs/pwa": "^3.3.5",
   "@braid/vue-formulate": "^2.5.3",
   // ...
}
// ...
```

```
nuxt.config.js

buildModules: [
   '@braid/vue-formulate/nuxt',
   // ...
]
// ...
```

![vue-formulate-nuxt-error_Chrome](https://user-images.githubusercontent.com/78219375/214953771-daf603ff-bde6-4992-9930-6b50b058484c.png)
![error-after-start_url-1](https://user-images.githubusercontent.com/78219375/214953824-d89af63a-8b67-4469-a105-294300498e9d.png)
![error-after-start_url-2](https://user-images.githubusercontent.com/78219375/214953840-a152ea24-3e56-4165-95b3-577bbabff56f.png)
![error details](https://user-images.githubusercontent.com/78219375/214953861-cd57e1a3-2a03-4745-a9ae-862004e441d0.png)
![prod-error-with-workbox-debug-1 1](https://user-images.githubusercontent.com/78219375/214953887-e4ef742e-d3b1-4f5c-b15d-03c55e429493.png)
![prod-error-with-workbox-debug-1 2](https://user-images.githubusercontent.com/78219375/214953896-d7cb0537-2dd0-4bd6-ab90-60a749ac0834.png)
![prod-error-with-workbox-debug-1](https://user-images.githubusercontent.com/78219375/214953879-09641589-7c19-45b3-8a7b-4fd46582f672.png)
![workbox-debug-no-vue-formulate](https://user-images.githubusercontent.com/78219375/214953904-88d5c18a-d1bf-46d5-ad9a-b9e1c42e78f0.png)

**Comment by pit07** [comment]
Hi  Spencer!

Did you find a solution?
I have the same issue... :( 

`workbox-precaching.prod.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://nougats-silvain.fr/","status":404}]`

**Comment by Spencer-Sch** [comment]
> Hi  Spencer!
> 
> Did you find a solution?
> I have the same issue... :( 
> 
> `workbox-precaching.prod.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://nougats-silvain.fr/","status":404}]`

No. I ended up building my own component library for the project because I kept running into issues with 3rd party libraries.

If I did it again today I would either try DaisyUI (if that works in Nuxt) or I just learned about NuxtUI that looks promising.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
