### ISSUE TITLE
what is the best way for using webpack and pre-cooked service-worker.js/manifest.json/ files?

### ISSUE THREAD

**Issue by kirill-linnik** [GoogleChrome/workbox#3175]
Hi all,

When using `workbox-webpack-plugin` (ver 6.5.4) the way [webpack suggests](https://webpack.js.org/guides/progressive-web-application/), it generates `service-worker.js` but then console doesn't look nice:

![image](https://user-images.githubusercontent.com/15168102/218261506-cd98de42-f775-4ced-b9ae-8c09c6eddc29.png)

and, well, it simply doesn't work (install app doesn't show up).

at the same time, react itself suggests [different way of creating PWA](https://create-react-app.dev/docs/making-a-progressive-web-app/), which creates `service-worker.ts`, `serviceWorkerRegistration.ts`, and `manifest.json` files one can manipulate. 

finally, question:
what is the way of using `service-worker.ts`, `serviceWorkerRegistration.ts`, and `manifest.json` with webpack?

**Comment by kirill-linnik** [comment]
ok, I spent some time and found the way. maybe it is a good idea do document it somewhere.
I put `manifest.json` and rest of files into `/pwa/` folder in the root of the project and:
```
const WorkboxPlugin = require("workbox-webpack-plugin");
const CopyPlugin = require("copy-webpack-plugin");
...
    new WorkboxPlugin.InjectManifest({
      swSrc: "./src/service-worker.ts",
      compileSrc: true,
      maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
    }),
    new CopyPlugin({
      patterns: ["./pwa/"],
    }),
```
and in `index.html`:
`<link rel="manifest" href="/manifest.json" />`

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
