### ISSUE TITLE
The definition of AbortSignal used in Workbox is outdated

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/workbox#3179]
The definition of AbortSignal used in Workbox is outdated: https://github.com/GoogleChrome/workbox/blob/ad7d3b712c99ee603bcdb276b5e85e429db1378e/packages/workbox-build/src/schema/WebpackInjectManifestOptions.json#L734 and incompatible with Typescript definition:

https://github.com/microsoft/TypeScript/blob/main/lib/lib.webworker.d.ts#L772

(it is missing "reason" property)

This is casueing errors in parsing .d.ts definitions from Workbox in developer.chrome.com project.

**Comment by tropicadri** [comment]
This shouldn't happen with the new version 6.6.0. Let me know if you run into new troubles.
