### ISSUE TITLE
[Warning] `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration` - Trace Error from babel

### ISSUE THREAD

**Issue by kziemski** [GoogleChrome/workbox#3182]
**Library Affected**:
workbox-build, workbox-webpack-plugin

**Browser & Platform**:
workbox-build, workbox-webpack-plugin - 6.5.4

**Issue or Feature Request Description**:
Babel in @babel/types@7.21.0 has deprecated isModuleDeclaration and is dumping a ton of trace errors reminding to migrate to isImportOrExportDeclaration.

workbox seems to be referring to different versions of babel/helpers 
[Here is the babel migration issue](https://github.com/babel/babel/issues/15466)

Comments make reference to upgrading to 7.20.7 for babel/helpers and traverse being the the fix.

I have attached an error log of that webpack will output when it runs with this issue
And i've attached a yarn why search of  babel/types, babel/core, babel/helpers and babel/traverse 

[yarnwhy.log](https://github.com/GoogleChrome/workbox/files/10924230/yarnwhy.log)
[error.log](https://github.com/GoogleChrome/workbox/files/10924002/error.log)

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
