### ISSUE TITLE
offlineFallback feature request in workbox-build

### ISSUE THREAD

**Issue by druzsik** [GoogleChrome/workbox#3184]
**Library Affected**:
workbox-build

**Browser & Platform**:
all

**Issue or Feature Request Description**:
offlineFallback(); from workbox-recipes is a [straightforward solution](https://developer.chrome.com/docs/workbox/managing-fallback-responses/) , for simplicity, which assumes offline.html located in root to cache in workbox-offline-fallback cache storage. 

In workbox-build generateSW, [offline.html needs to be precached](https://github.com/GoogleChrome/workbox/issues/2816) first, and then we have to add these extra lines  precacheFallback: {fallbackURL: 'offline.html'} into runtimeCaching in generateSW mode.

_Offline page only_
offlineFallback: 'true' or 'false' (false as default value) would be as sophisticated option as skipWaiting, navigationPreload and clientsClaim, for instance. 

Even though runtimeCaching and offlineFallback(); recipe are hand in hand just like runtimeCaching and navigationPreload, hope there is no any particular reason of why precache manifest is prefarable to offline fallback.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
