### ISSUE TITLE
Failed to register a ServiceWorker(sw.js) for scope 'https://workbox-strategies.glitch.me/'(workbox-strategies demo)

### ISSUE THREAD

**Issue by prakhart4** [GoogleChrome/workbox#3189]
**Library Affected**:
_demos > workbox-strategies_

**Browser & Platform**:
_all_

**Issue Description**:
_Failed to register `sw.js` ServiceWorker in [workbox-strategies Demo](https://workbox-strategies.glitch.me/)._

Console error at https://workbox-strategies.glitch.me/ (workbox-strategies demo):
```console
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://workbox-strategies.glitch.me/') with script ('https://workbox-strategies.glitch.me/sw.js'): A bad HTTP response code (404) was received when fetching the script.
```

As the `sw.js` is not registered the demo is not functional.

**Related issues**:
* loadModule() is called before setConfig() in `sw.js`.
* Warning: No package.json at `demos > src > workbox-strategies`.
* Warning: skipWaiting() no longer recommended.

**Comment by prakhart4** [comment]
**Fix:**
_The route and file name `sw1.js` can be replaced with `sw.js`_

At workbox\demos\src\workbox-strategies\updateServer.js
~~~diff
-app.get('/sw1.js', (request, response) => {
+app.get('/sw.js', (request, response) => {
-  response.sendFile(path.resolve('sw1.js'));
+  response.sendFile(path.resolve('sw.js'));
~~~

**Comment by prakhart4** [comment]
Other fixes are committed at [workbox-strategies_demo_fix](/prakhart4/workbox/tree/workbox-strategies_demo_fix)

Please let me know if I should create a PR

Thank you.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
