### ISSUE TITLE
build-error(react)

### ISSUE THREAD

**Issue by AshutoshMoharana** [GoogleChrome/workbox#3190]
while trying to build using : npm run build below error is showing, can anyone help me....how to resolve

npm run build

pcrf-portal@0.1.0 build
react-scripts build

(node:17020) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use node --trace-deprecation ... to show where the warning was created)
Creating an optimized production build...
Failed to compile.

Cannot read properties of undefined (reading 'includes')

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
