### ISSUE TITLE
Issue with `warmCache` option in `staticResourceCache` recipe

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/workbox#3207]
**Library Affected**:

`workbox-cli` 6.5.4 (using `injectManifest`) and `workbox-recipes` 6.5.4

**Browser & Platform**:

At least Chrome stable, couldn't replicate in Firefox where devtools are less powerful for service workers debuging.

**Issue or Feature Request Description**:

I'm using `workbox-recipes` in my Service Worker file on https://pack11ty.dev/ :
- https://github.com/nhoizey/pack11ty/blob/main/src/assets/js/service-worker.js

<details><summary>Content of the Service Worker source</summary>

```javascript
import {
	offlineFallback,
	pageCache,
	staticResourceCache,
	imageCache,
} from 'workbox-recipes';

// Serve pages as network first, with 2 seconds timeout and cache fallback
// https://developer.chrome.com/docs/workbox/modules/workbox-recipes/#page-cache
pageCache({
	networkTimoutSeconds: 2,
	warmCache: ['/', '/documentation/', '/news/', '/offline/'],
});

// Serve static assets from immediately from cache, and update (aka "Stale While Revalidate")
// https://developer.chrome.com/docs/workbox/modules/workbox-recipes/#static-resources-cache
//
// Also precache static assets with hashes in filenames
// See the "serviceworker" npm script and "workbox.config.js" configuration
// https://developer.chrome.com/docs/workbox/precaching-with-workbox/#precaching-with-injectmanifest
staticResourceCache({
	warmCache: self.__WB_MANIFEST,
});

// Cache a maximum of 100 images, for 90 days each at most
// https://developer.chrome.com/docs/workbox/modules/workbox-recipes/#image-cache
imageCache({
	maxEntries: 100,
	maxAgeSeconds: 60 * 60 * 24 * 90,
	warmCache: ['./images/logo-192px.png', './images/logo-512px.png'],
});

// Provide offline fallbacks for HTML and images
// https://developer.chrome.com/docs/workbox/modules/workbox-recipes/#offline-fallback
offlineFallback({
	pageFallback: '/offline/fallback.html',
	imageFallback: '/offline/fallback.svg',
});
```

</details>

It is transformed with `esbuild` included in my Eleventy project, with this code:
- https://github.com/nhoizey/eleventy-plugin-pack11ty/blob/00070d99627ee6c85129f273a064b7b886801d5e/_11ty/assets.js#L67-L76

```javascript
const output = await esbuild.build({
  entryPoints: [inputPath],
  // nodePaths: ['.', 'src/assets/js'],
  bundle: true,
  format: 'esm',
  target: 'es6',
  minify: data.eleventy.env.runMode === 'build',
  write: false,
  external: ['fs'],
});
```

The configuration file is here:
- https://github.com/nhoizey/pack11ty/blob/f6435fd1af47994c588b47879c48c56787e04a6c/workbox.config.js

```javascript
module.exports = {
  globDirectory: '_site',
  globPatterns: ['./bundle/*', './manifest.webmanifest'],
  swSrc: '_site/service-worker.js',
  swDest: '_site/service-worker.js',
};
```

After running `workbox injectManifest workbox.config.js` and loading a page in Chrome, I get 3 caches:

<img width="328" alt="image" src="https://github.com/GoogleChrome/workbox/assets/78213/4f2b5983-5522-4192-b65e-80657091542c">

The `static-resources` cache is missing.

When looking at the network tab during this first page load, it looks like the Service Worker tries to request wrong URLs with `[object%20Object]` as pathname:

<img width="1178" alt="image" src="https://github.com/GoogleChrome/workbox/assets/78213/b0f5c7e3-088b-41c9-b891-d770b3edd6d3">

Visible also in this WebPageTest audit result:
- https://www.webpagetest.org/result/230513_AiDcHY_607/2/details/#waterfall_view_step1

After reloading the page, these requests are not here anymore, and the `static-resources` cache is created:

<img width="325" alt="image" src="https://github.com/GoogleChrome/workbox/assets/78213/9ebd32aa-d3e3-44aa-b631-d125f019e124">

When building the script with `esbuild`'s `minify: false` option and running `workbox injectManifest workbox.config.js`, here's the end of the resulting script, which looks "normal":

```javascript
// src/assets/js/service-worker.js
pageCache({
  networkTimoutSeconds: 2,
  warmCache: ["/", "/documentation/", "/news/", "/offline/"]
});
staticResourceCache({
  warmCache: [{"revision":"89e7cbf3726b3ba6d553923cd563f93e","url":"bundle/i62IKo387H.css"},{"revision":"30475106d973bc24c4dd36f2f5527387","url":"bundle/jEQo5lXFGA.js"},{"revision":"c6479b9282e2543d55edec45b108aa82","url":"bundle/LljobFI2Wl.js"},{"revision":"2b86a6d92c5b0dd0ce19bccabc348820","url":"bundle/rVMdK1SCSc.css"},{"revision":"5f0eaddc8136795290cace74724e45ae","url":"manifest.webmanifest"}]
});
imageCache({
  maxEntries: 100,
  maxAgeSeconds: 60 * 60 * 24 * 90,
  warmCache: ["./images/logo-192px.png", "./images/logo-512px.png"]
});
offlineFallback({
  pageFallback: "/offline/fallback.html",
  imageFallback: "/offline/fallback.svg"
});
```

So I don't understand is there's an actual issue in the `staticResourceCache` recipe handling of the `warmCache` option.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
