### ISSUE TITLE
SonarQube vulnerability at addCacheListener(). [javascript:S2819]: Verify the origin of the received message.

### ISSUE THREAD

**Issue by AliaksandrPatapeika** [GoogleChrome/workbox#3209]
Hello everyone!
We use next-pwa that generate workbox-*.js file. After sonarqube scanning it gets vulnerability:
Verify the origin of the received message.
Origins should be verified during cross-origin communications [javascript:S2819](https://sonar.wolterskluwer.io/coding_rules?open=javascript%3AS2819&rule_key=javascript%3AS2819)
![Screenshot 2023-05-16 120557](https://github.com/GoogleChrome/workbox/assets/23075695/d12dbb4c-7ca6-4236-a6a5-75598001035a)

Is there a possible solution?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
