### ISSUE TITLE
Workbox-Google-Analytics not working correctly on Node

### ISSUE THREAD

**Issue by juanfe9118** [GoogleChrome/workbox#3210]
**Library Affected**:
_workbox-google-analytics v6.5.4_

**Browser & Platform**:
_All browsers and NodeJs (NextJS)_

**Issue or Feature Request Description**:
When trying to use the node library for _workbox-google-analytics_ in my NextJS app, I get a `SyntaxError: Cannot use import statement outside a module` as soon as I try to initialize the instance at the moment of compiling the code for the dev env. As shown in the screenshot below.

![image](https://github.com/GoogleChrome/workbox/assets/55112173/b17ccf9f-f48f-45cf-8dfe-c4b5f991968e)

It is worth noting that when I try to run the code from the [NPM RunKit](https://npm.runkit.com/workbox-google-analytics) the same error is shown when trying to initialize the instance as shown below.

![image](https://github.com/GoogleChrome/workbox/assets/55112173/c18b556f-bbe5-4186-a6cc-7a16ca65874c)

I tried running the libraries locally using the workbox CLI's _CopyLibraries_ directive as a workaround but I couldn't initialize the workbox instance either. 

I appreciate any help regarding this topic.

**Comment by Simple-Jian** [comment]
Have you solved this problem? I stumbled on it.

**Comment by juanfe9118** [comment]
> Have you solved this problem? I stumbled on it.

Hi @Simple-Jian in the end I ended up using the fetch implementation inside the node file. Like manually calling the API with all the params in it.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
