### ISSUE TITLE
Issue with Node 14 in version 6.6.1

### ISSUE THREAD

**Issue by osniel** [GoogleChrome/workbox#3220]
**Library Affected**:
_workbox-sw, workbox-build, etc._

**Browser & Platform**:
NodeJS 14

**Issue or Feature Request Description**:
Deprecated version 6.6.1 is incompatible with NodeJS 14. Since there's already a version 7 for NodeJS 16, it would be nice to have a 6.6.2 targeting NodeJS 14 as minimum engine, for projects that haven't been upgraded yet.

`

[2/4] Fetching packages...
--
error workbox-webpack-plugin@6.6.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.3"
error Found incompatible module.

`

**Comment by connorkatz-mb** [comment]
this is an issue running `yarn create react-app` on Node 14. react-scripts 5.0.1 is picking up the latest point release of `6.6.1` and failing due to incompatible node version.

can you release a `6.6.2` that fixes the engine property in package.json

**Comment by manuelodelain** [comment]
As temp workaround I freezed the version to `6.6.0`

**Comment by osniel** [comment]
Yes, that could work as a temporary workaround

**Comment by vinodsnayvik** [comment]
I'm also getting this:

[2/4] Fetching packages...
error workbox-webpack-plugin@6.6.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.0"
error Found incompatible module

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Comment by osniel** [comment]
Hi @tomayac,

Thank you for the update. Good luck on the new endeavors!
