### ISSUE TITLE
The trouble with documentation!

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#3224]
**Library Affected**:
workbox documentation

**Browser & Platform**:
none

**Issue or Feature Request Description**:
Dear colleagues!

I'm sorry that I have to write about this, but things with the documentation are very bad!
The old documentation, although it could have been better, but it introduced the course and gave a clear idea of the product, how to use it and how to configure it

I didn't go into the documentation for 2 years and wasn't connected with the development of the service worker, and so I had to start working with it again in a new project. Even I, who had experience working with workbox, cannot, according to today's documentation, integrate it into the assembly process, nor can I understand anything at all - there are just scattered pieces of information on the content, form and design on the site.

I asked a couple of my colleagues to try to figure it out - they gave up after 2 days and said: this is not possible

I expressed my opinion about the documentation in our community and many confirmed that the documentation in this form absolutely does not help to understand the workbox and many do not want to communicate with it at all because of this!

Please return the documentation to an understandable form and content!

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
