### ISSUE TITLE
Unable to use `networkTimeoutSeconds` with `NetworkOnly` strategy

### ISSUE THREAD

**Issue by firasdib** [GoogleChrome/workbox#3231]
**Library Affected**:
_workbox-webpack-plugin_

**Browser & Platform**:
_all browsers_

**Issue or Feature Request Description**:
My goal is to have the SW request the network for all pages, but if it fails, I want it to fall back to a pre-cached template I have. This works fine using `NetworkOnly`-strategy, but I would like to include a timeout for cases where the server is taking a super long time or is down.

The docs [here](https://developer.chrome.com/docs/workbox/reference/workbox-strategies/#type-NetworkOnlyOptions) say it should work, but it doesn't.

Using workbox 7, the error is the following:
```
ERROR in Unable to generate service worker from template. 'When using networkTimeoutSeconds, you must set the handler to 'NetworkFirst'.'
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
