### ISSUE TITLE
the workbox-build package pulls 73.63MB of dependencies

### ISSUE THREAD

**Issue by preynal** [GoogleChrome/workbox#3236]
In a bare folder I just npm install `workbox-build` and get:

<img width="575" alt="Screenshot 2023-08-06 at 21 54 18" src="https://github.com/GoogleChrome/workbox/assets/1218704/862560c9-454f-4d36-a9ce-d6b7bcbd97da">

with [npm](https://www.npmjs.com/package/workbox-build) listing 4.3M weekly downloads

<img width="419" alt="Screenshot 2023-08-06 at 21 41 33" src="https://github.com/GoogleChrome/workbox/assets/1218704/f6e35a5d-7188-470e-a9a5-ec45484a5470">

that would be above 323TB per week? more than 1.2PB per month ?

am I missing something? why is this package so large?

**Comment by THETCR** [comment]
Because the level of dependency management on this project is amateurish at best.
When you want to show examples on how it should not be done, this project is one of them.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
