### ISSUE TITLE
README.md site source link is not working

### ISSUE THREAD

**Issue by gautamsagar99** [GoogleChrome/workbox#3242]
The hyperlink provided in the README.md file is currently non-functional. This hyperlink is located within the Documentation section, and it corresponds to the Overview (site source), as illustrated in the image below:

![image](https://github.com/GoogleChrome/workbox/assets/47146980/d4697537-50fa-4d50-ac68-5e727c2082f3)

when you go into that folder we can see that workbox is not available.

So I hope we need to update the link.

**Comment by tomayac** [comment]
Closed via https://github.com/GoogleChrome/workbox/commit/a30d1aa683da2efd9e2ad4b0df17853b99e23aa6.
