### ISSUE TITLE
Staled index.html even using revision

### ISSUE THREAD

**Issue by pedrocostadev** [GoogleChrome/workbox#3247]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I have a SPA with the following code that Injects the manifest:

```
const revision = new Date().getTime().toString();

...

  env.plugins.append('WorkboxPlugin', new WorkboxPlugin.InjectManifest({
    swSrc: path.join(root, 'frontend/app/service-worker.js'),
    swDest: path.join(root, 'public/service-worker.js'),
    exclude: [/\.map$/, /asset-manifest\.json$/, /LICENSE/],
    additionalManifestEntries: [
      { url: '/index.html', revision },
      { url: 'https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;700&display=swap', revision },
    ],
    maximumFileSizeToCacheInBytes: 50 * 1024 * 1024,
  }));
```

As you can see, there is a revision and if I inspect the cache I can see it there:
<img width="825" alt="Screenshot 2023-09-21 at 11 40 02" src="https://github.com/GoogleChrome/workbox/assets/25672810/44ac913f-02b3-40cb-af9b-39b16552aca8">

On the SW side, I have this code too:

```
const indexNavigationRoute = new NavigationRoute(createHandlerBoundToURL('/index.html'), {
  denylist: [
    new RegExp('/service-worker.js'),
    new RegExp('.*/manifest.json'),
    new RegExp('/404.html'),
    new RegExp('/422.html'),
    new RegExp('/500.html'),
    new RegExp('/privacy'),
  ],
});
```

The issue is that the index.html file has the scripts for the JS chunks but even using the revision the browser is using a staled version.  Any idea how to fix this?

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
