### ISSUE TITLE
sw-cli creates a manifest including node_modules/

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/workbox#326]
**Library Affected**:
sw-cli

**Browser & Platform**:
Node v7.7.2

**Issue or Feature Request Description**:
If I specify my root dir as the project path, sw-cli includes js/html etc files from node_modules/. I feel like this might not be desirable or could be an option.

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by addyosmani** [comment]
> I feel like this might not be desirable or could be an option.

I ran into this last night and agree it probably isn't always desirable.

**Comment by gauntface** [comment]
@addyosmani 

With following file structure, are we saying it **shouldn't** cache node_modules by default:

- '.'
    - index.html
    - styles/
        - main.css
    - scripts/
        - main.js
    - node_modules/
        - something/
            - hello.js
