### ISSUE TITLE
precacheAndRoute may cause an infinite loop on Webpack's HMR

### ISSUE THREAD

**Issue by mxmauro** [GoogleChrome/workbox#3260]
**Library Affected**: `workbox-precaching`
**Browser & Platform**: `All browsers`

**Description**:

I'm creating a PWA application from scratch with React and Webpack, no third-party frameworks like Next.JS.

As recommended, added `precacheAndRoute(self.__WB_MANIFEST);` into my service worker script.

**Problem**:

If `Hot Module Reload` is configured on `Webpack`, `self.__WB_MANIFEST` includes some of the `.hot-update.json` files, used by Webpack to detect if something has changed.

The first time, you won't notice anything bad but, if you restart webpack and refresh the page, the precached code will try to look for an outdated hot update file. Because 404 is returned, webpack dev server executes a full page reload causing this event to be repeated for ever.

**Workaround**:

Removing the call to `precacheAndRoute` fixes the issue.

**Expected solution**:

I believe removing hot update JSON entries from `__WB_MANIFEST` is the correct solution.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
