### ISSUE TITLE
workbox-webpack-plugin InjectManifest missing a lot of files

### ISSUE THREAD

**Issue by albgen** [GoogleChrome/workbox#3270]
I'm using workbox-webpack-plugin's InjectManifest to generate the __WB_MANIFEST list, for precacheAndRoute in the service-worker.js.
The problem is that __WB_MANIFEST list does not include images, fonts, css or others resources.

Using CRA without eject.

Really can't understand if it is a bug or misconfig.

**service-worker.js**
```
/* eslint-disable no-restricted-globals */

import { clientsClaim} from 'workbox-core';
import {precacheAndRoute} from 'workbox-precaching';

// import { ExpirationPlugin } from 'workbox-expiration';
// import { registerRoute } from 'workbox-routing';
// import { StaleWhileRevalidate } from 'workbox-strategies';



// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// setLogLevel(workbox.core.LOG_LEVELS.debug);

// Main
clientsClaim();

// Install directly new version, don't wait to stop!
// The skipWaiting wrapper is deprecated https://developer.chrome.com/docs/workbox/modules/workbox-core/
self.skipWaiting();

self.addEventListener('fetch', (event) => {
    // Add any custom caching rules here
});
```

This is how i register the service worker 

```
import {Workbox} from 'workbox-window';

export default function registerSW() {  

  if ('serviceWorker' in navigator) {
    const wb = new Workbox('sw.js');

    wb.addEventListener('installed', (event) => {
      if (event.isUpdate){
        if (confirm('Update available, Click Ok to refresh!'))
         window.location.reload();
      }
      
    });

    wb.register().then((registration) => {
      console.log('Service Worker registered: ', registration);
    })
    .catch((error) => {
      console.log('Service Worker registration failed: ', error);
    });

  }
}
```

**config-overrides.js**
```
const { defaultInjectConfig, InjectManifest } = require('workbox-webpack-plugin');
const webpack = require('webpack');
const path = require('path');
const {rewireWorkboxInject} = require('react-app-rewire-workbox');

module.exports = function override(config, env) {
  const workboxConfig = {
    ...defaultInjectConfig,
    swSrc: path.join(__dirname, 'src', 'service-worker.js'),
    swDest: 'sw.js',
    exclude: [/.*\.txt/,'service-worker.js',/\.map$/, /^manifest.*\.js(?:on)?$/]
  };
  config.plugins.push(new InjectManifest(workboxConfig));

  config.resolve.fallback = {
    process: require.resolve('process/browser'),
    zlib: require.resolve('browserify-zlib'),
    stream: require.resolve('stream-browserify'),
    util: require.resolve('util'),
    buffer: require.resolve('buffer'),
    asset: require.resolve('assert'),
  };

  config.plugins.push(
    new webpack.ProvidePlugin({
      process: 'process/browser.js',
      Buffer: ['buffer', 'Buffer'],
    })
  );  

  return config;
};
```

**The following are the urls generated on sw.js**

` { revision: 'dfb30077622a99f76a2923a84cace995', url: '/index.html' },
      { revision: null, url: '/static/css/9851.21ee7f76.chunk.css' },
      { revision: null, url: '/static/css/main.69ae699e.css' },
      { revision: null, url: '/static/js/1066.ea61f9fc.chunk.js' },
      { revision: null, url: '/static/js/1107.bb0476b0.chunk.js' },
      { revision: null, url: '/static/js/1225.67033754.chunk.js' },
      { revision: null, url: '/static/js/1347.d139ab9d.chunk.js' },
      { revision: null, url: '/static/js/1406.3cbb2f40.chunk.js' },
      { revision: null, url: '/static/js/1626.14530edd.chunk.js' },
      { revision: null, url: '/static/js/1897.d5c33a0e.chunk.js' },
      { revision: null, url: '/static/js/2104.1d388dfb.chunk.js' },
      { revision: null, url: '/static/js/2247.35a130d3.chunk.js' },
      { revision: null, url: '/static/js/2323.d51f107f.chunk.js' },
      { revision: null, url: '/static/js/2569.4243e22c.chunk.js' },
      { revision: null, url: '/static/js/2619.68d84ac6.chunk.js' },
      { revision: null, url: '/static/js/2724.860ea74f.chunk.js' },
      { revision: null, url: '/static/js/2778.4f620227.chunk.js' },
      { revision: null, url: '/static/js/2793.0ec32099.chunk.js' },
      { revision: null, url: '/static/js/2878.b74f4a28.chunk.js' },
      { revision: null, url: '/static/js/2997.5dbc149b.chunk.js' },
      { revision: null, url: '/static/js/3120.3c19a87b.chunk.js' },
      { revision: null, url: '/static/js/3401.03123535.chunk.js' },
      { revision: null, url: '/static/js/3489.f5616155.chunk.js' },
      { revision: null, url: '/static/js/3543.a86fdcc0.chunk.js' },
      { revision: null, url: '/static/js/3558.828681a1.chunk.js' },
      { revision: null, url: '/static/js/3639.9cf15346.chunk.js' },
      { revision: null, url: '/static/js/3695.4521d1ea.chunk.js' },
      { revision: null, url: '/static/js/3705.3b8c7c9a.chunk.js' },
      { revision: null, url: '/static/js/3742.f44dcf90.chunk.js' },
      { revision: null, url: '/static/js/3764.cb678089.chunk.js' },
      { revision: null, url: '/static/js/3963.51fefafe.chunk.js' },
      { revision: null, url: '/static/js/4017.37bb3569.chunk.js' },
      { revision: null, url: '/static/js/4245.a61fbefc.chunk.js' },
      { revision: null, url: '/static/js/4294.2916e314.chunk.js' },
      { revision: null, url: '/static/js/4559.e1541e1f.chunk.js' },
      { revision: null, url: '/static/js/4832.a884a4d4.chunk.js' },
      { revision: null, url: '/static/js/5560.e10ef843.chunk.js' },
      { revision: null, url: '/static/js/560.7cc98310.chunk.js' },
      { revision: null, url: '/static/js/5644.a568c21d.chunk.js' },
      { revision: null, url: '/static/js/5726.0ec1f60a.chunk.js' },
      { revision: null, url: '/static/js/5825.b2208250.chunk.js' },
      { revision: null, url: '/static/js/6101.eed8d228.chunk.js' },
      { revision: null, url: '/static/js/6182.2ad5347d.chunk.js' },
      { revision: null, url: '/static/js/6250.2e0e44fa.chunk.js' },
      { revision: null, url: '/static/js/6263.52aeec26.chunk.js' },
      { revision: null, url: '/static/js/6323.0b813fd1.chunk.js' },
      { revision: null, url: '/static/js/6370.4a6e82f7.chunk.js' },
      { revision: null, url: '/static/js/6390.5e00c29f.chunk.js' },
      { revision: null, url: '/static/js/6648.ff20a1c5.chunk.js' },
      { revision: null, url: '/static/js/6870.0cc8b6d8.chunk.js' },
      { revision: null, url: '/static/js/7081.f2eff227.chunk.js' },
      { revision: null, url: '/static/js/7403.12168d36.chunk.js' },
      { revision: null, url: '/static/js/7434.5a15258c.chunk.js' },
      { revision: null, url: '/static/js/7774.b3e90fd8.chunk.js' },
      { revision: null, url: '/static/js/7797.83a9038e.chunk.js' },
      { revision: null, url: '/static/js/7995.04782ce0.chunk.js' },
      { revision: null, url: '/static/js/8042.229a37e5.chunk.js' },
      { revision: null, url: '/static/js/8054.abac2daf.chunk.js' },
      { revision: null, url: '/static/js/8301.38abc96c.chunk.js' },
      { revision: null, url: '/static/js/8495.29f0b04e.chunk.js' },
      { revision: null, url: '/static/js/8555.03ad1b59.chunk.js' },
      { revision: null, url: '/static/js/8755.e3b0b97e.chunk.js' },
      { revision: null, url: '/static/js/8829.30a5d5d4.chunk.js' },
      { revision: null, url: '/static/js/8880.db9273a5.chunk.js' },
      { revision: null, url: '/static/js/8969.359724bf.chunk.js' },
      { revision: null, url: '/static/js/8977.044a87a4.chunk.js' },
      { revision: null, url: '/static/js/916.b6edcf21.chunk.js' },
      { revision: null, url: '/static/js/9182.9876e9c7.chunk.js' },
      { revision: null, url: '/static/js/9487.86d868e8.chunk.js' },
      { revision: null, url: '/static/js/9522.bd1fb3d7.chunk.js' },
      { revision: null, url: '/static/js/9834.1a1374a3.chunk.js' },
      { revision: null, url: '/static/js/9851.6a838cfd.chunk.js' },
      { revision: null, url: '/static/js/main.f290494d.js' },
      { revision: null, url: '/static/media/axios.b2798fd764a875f97f44.cjs' },`

The following is the actual build folder content:

```
D:\GITREPOS\TBTECH.AMG.FRONTEND\BUILD
│   asset-manifest.json
│   index.html
│   manifest.json
│   robots.txt
│   service-worker.js
│   service-worker.js.LICENSE.txt
│   sw.js
│   sw.js.LICENSE.txt
│   _redirects
│
├───favicon
│       android-chrome-192x192.png
│       android-chrome-512x512.png
│       apple-touch-icon.png
│       favicon-16x16.png
│       favicon-32x32.png
│       favicon.ico
│
├───fonts
│       CircularStd-Bold.otf
│       CircularStd-Book.otf
│       CircularStd-Medium.otf
│       index.css
│       Roboto-Bold.ttf
│       Roboto-Regular.ttf
│
├───icons
│       ic_analytics.svg
│       ic_asset.svg
│       ic_banking.svg
│       ic_blog.svg
│       ic_booking.svg
│       ic_calendar.svg
│       ic_cart.svg
│       ic_chat.svg
│       ic_dashboard.svg
│       ic_ecommerce.svg
│       ic_invoice.svg
│       ic_kanban.svg
│       ic_mail.svg
│       ic_return.svg
│       ic_sales.svg
│       ic_transfer.svg
│       ic_user.svg
│       ic_warehouse.svg
│
├───images
│       illustration_empty_content.png
│       img_placeholder.svg
│       logo.png
│
├───logo
│       logo_full.jpg
│       logo_full.svg
│       logo_single.svg
│
└───static
    ├───css
    │       9851.21ee7f76.chunk.css
    │       main.69ae699e.css
    │
    ├───js
    │       1066.ea61f9fc.chunk.js
    │       1107.bb0476b0.chunk.js
    │       1225.67033754.chunk.js
    │       1347.d139ab9d.chunk.js
    │       1406.3cbb2f40.chunk.js
    │       1626.14530edd.chunk.js
    │       1897.d5c33a0e.chunk.js
    │       2104.1d388dfb.chunk.js
    │       2247.35a130d3.chunk.js
    │       2247.35a130d3.chunk.js.LICENSE.txt
    │       2323.d51f107f.chunk.js
    │       2569.4243e22c.chunk.js
    │       2619.68d84ac6.chunk.js
    │       2724.860ea74f.chunk.js
    │       2778.4f620227.chunk.js
    │       2793.0ec32099.chunk.js
    │       2878.b74f4a28.chunk.js
    │       2997.5dbc149b.chunk.js
    │       3120.3c19a87b.chunk.js
    │       3401.03123535.chunk.js
    │       3489.f5616155.chunk.js
    │       3543.a86fdcc0.chunk.js
    │       3558.828681a1.chunk.js
    │       3639.9cf15346.chunk.js
    │       3695.4521d1ea.chunk.js
    │       3705.3b8c7c9a.chunk.js
    │       3742.f44dcf90.chunk.js
    │       3764.cb678089.chunk.js
    │       3963.51fefafe.chunk.js
    │       4017.37bb3569.chunk.js
    │       4245.a61fbefc.chunk.js
    │       4294.2916e314.chunk.js
    │       4559.e1541e1f.chunk.js
    │       4832.a884a4d4.chunk.js
    │       5560.e10ef843.chunk.js
    │       560.7cc98310.chunk.js
    │       5644.a568c21d.chunk.js
    │       5726.0ec1f60a.chunk.js
    │       5726.0ec1f60a.chunk.js.LICENSE.txt
    │       5825.b2208250.chunk.js
    │       6101.eed8d228.chunk.js
    │       6182.2ad5347d.chunk.js
    │       6250.2e0e44fa.chunk.js
    │       6263.52aeec26.chunk.js
    │       6323.0b813fd1.chunk.js
    │       6370.4a6e82f7.chunk.js
    │       6390.5e00c29f.chunk.js
    │       6648.ff20a1c5.chunk.js
    │       6870.0cc8b6d8.chunk.js
    │       7081.f2eff227.chunk.js
    │       7403.12168d36.chunk.js
    │       7434.5a15258c.chunk.js
    │       7774.b3e90fd8.chunk.js
    │       7797.83a9038e.chunk.js
    │       7995.04782ce0.chunk.js
    │       8042.229a37e5.chunk.js
    │       8054.abac2daf.chunk.js
    │       8301.38abc96c.chunk.js
    │       8495.29f0b04e.chunk.js
    │       8555.03ad1b59.chunk.js
    │       8755.e3b0b97e.chunk.js
    │       8829.30a5d5d4.chunk.js
    │       8829.30a5d5d4.chunk.js.LICENSE.txt
    │       8880.db9273a5.chunk.js
    │       8969.359724bf.chunk.js
    │       8977.044a87a4.chunk.js
    │       916.b6edcf21.chunk.js
    │       9182.9876e9c7.chunk.js
    │       9487.86d868e8.chunk.js
    │       9522.bd1fb3d7.chunk.js
    │       9834.1a1374a3.chunk.js
    │       9851.6a838cfd.chunk.js
    │       9851.6a838cfd.chunk.js.LICENSE.txt
    │       main.f290494d.js
    │       main.f290494d.js.LICENSE.txt
    │
    └───media
            axios.b2798fd764a875f97f44.cjs
```

**Library Affected**:
     "workbox-core": "^7.0.0",
    "workbox-expiration": "^7.0.0",
    "workbox-precaching": "^7.0.0",
    "workbox-routing": "^7.0.0",
    "workbox-strategies": "^7.0.0",
    "workbox-webpack-plugin": "^7.0.0",
    "workbox-window": "^7.0.0"

**Browser & Platform**:
Google Chrome v119.0.6045.106 for windows. Did not tested on other browsers

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
