### ISSUE TITLE
TypeScript type mismatch for `directoryIndex` option in `precacheAndRoute`

### ISSUE THREAD

**Issue by tr4cks** [GoogleChrome/workbox#3272]
As indicated in the [documentation](https://developer.chrome.com/docs/workbox/modules/workbox-precaching/#directory-index), I wanted to alter the behavior of `precacheAndRoute` using the `directoryIndex` option so that none of the requests pointing to `/` would be precached using `index.html`. Therefore, I assigned `directoryIndex` to `null` to achieve this behavior, as `null` is a valid value according to the documentation.

```shell
precacheAndRoute(self.__WB_MANIFEST, {directoryIndex: null});
```

The issue is that in TypeScript, the `directoryIndex` option can only be either `undefined` or a `string`. If the option is assigned with `undefined`, then the default behavior is applied.

For now, I've forced this behavior as follows, and it works:

```shell
precacheAndRoute(self.__WB_MANIFEST, {directoryIndex: null as unknown as string});
```

Perhaps it is necessary to review the TypeScript types and reconsider if the logic aligns with assigning this option to `null`. It seems to me that it should, given that it works on my end by forcing the option to `null`. So, it must be a matter of TypeScript type definition.

**Library Affected**:
_"workbox-precaching": "^7.0.0"_

**Browser & Platform**:
_Version 119.0.6045.105 (arm64)_

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
