### ISSUE TITLE
Memory leak vulnerability by inflight package

### ISSUE THREAD

**Issue by ornew** [GoogleChrome/workbox#3277]
The workbox depends on the `inflight` package, which has a reported memory leak vulnerability.

https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116

https://github.com/isaacs/inflight/issues/5

**Library Affected**:
workbox-build

**Browser & Platform**:
all

**Issue or Feature Request Description**:
To fix this, you will need to use fast-glob or upgrade the dependency to glob v9 where the dependency on inflight has been removed.

https://github.com/isaacs/node-glob/issues/435
https://github.com/angular/angular/pull/50632

**Comment by TheNewSound** [comment]
Not a really vulnerability

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
