### ISSUE TITLE
sw-precache & sw-toolbox migration path

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#328]
**Library Affected**:
sw-build, sw-cli, sw-lib

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:

[Polymer App Toolbox](https://www.polymer-project.org/1.0/toolbox/) has been using sw-precache & sw-toolbox for a while and has had no issues with either. With an existing userbase that already have SW tooling config, they would like a 1:1 mapping for sw-precache that would help transition their users over to the newer sw-helpers libraries.

cc @justinfagnani @frankiefu @graynorton 

Potential requirements:

* sw-cli supports the same or similar API surface to sw-precache 
* sw-lib is able to translate/interpret existing rules built using sw-toolbox
* Ideally what this work looks like does not require users to rewrite 
* Shouldn't require Polymer CLI to adopt additional bundling tools (e.g RollUp)

**Comment by addyosmani** [comment]
Reading up on current implementation:

https://github.com/Polymer/polymer-cli/blob/026f9bd83f5b2e8f5b88b9867508b3cbe28a87e3/src/build/build.ts#L94

https://github.com/Polymer/polymer-cli/blob/ddb87a576816624ec0f9b58b72efc55f796e5df2/src/commands/build.ts#L74

**Comment by chucktowar** [comment]
+1, with Workbox reaching v1.0 it would be nice to see Workbox replacing the sw-precache library across Polymer projects.

**Comment by gauntface** [comment]
Going to close this. We should look to upgrade everything after v3 has landed but this will happen organically and will be difficult to truly mark this issue as "done" given the number of projects using sw-precache.
