### ISSUE TITLE
Support algorithms other than MD5

### ISSUE THREAD

**Issue by brostwalt87** [GoogleChrome/workbox#3280]
https://github.com/GoogleChrome/workbox/blob/ee62b5b5b9ed321af457a2d962b2a34196a80263/packages/workbox-build/src/lib/get-string-hash.ts#L12-15

As a DevOps support engineer for Government programs, we have some developers who are running into issues when running in our environment.  When running containers (docker/oci) on hosts with FIPS 140 enforcement enabled, nodejs will throw the following error:

ERROR in error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at getAssetHash (/..../node_modules/workbox-webpack-plugin/build/lib/get-asset-hash.js:28:29)
    
 This is because nodejs on redhat uses the underlying openssl configs to enforce FIPS.  Because of the mounting of the /proc/ directory from the host, which contains the file /proc/sys/crypto/fips_enabled, the source of truth for the FIPS config, nodejs is detecting FIPS settings from opennsl which is detecting from the host . You can test this by utilizing this module within a redhat container with nodejs on top of a fedora/redhat system with FIPS enabled
 
 We have no way to turn this off at runtime unless we completely disable FIPS on the host nodes, which is a last resort option.  My request is simply to stop using md5 as it is quite outdated, and switch to something like sha256 or another FIPS compliant algorithm
 
 https://csrc.nist.gov/pubs/fips/140-2/upd2/final

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
