### ISSUE TITLE
Missing proper 'Get started' docs

### ISSUE THREAD

**Issue by kwikwag** [GoogleChrome/workbox#3283]
**Library Affected**:
General

**Browser & Platform**:
All

**Issue or Feature Request Description**:
Sort of a feature request: the README points to `workbox/guides/get-started` which redirects to `workbox/the-ways-of-workbox` which begins with a rather esoteric discussion about `generateSW` and `injectManifest`. Even [in the main landing page for Workbox](https://developer.chrome.com/docs/workbox) it's unclear where to start.  The closest thing to an entry point seems to be the paragraph [mentioning `workbox-cli`](https://developer.chrome.com/docs/workbox/the-ways-of-workbox/#use_workboxs_build_tools) but there is simply no page guiding a user into installing and integrating Workbox into their framework.

**Comment by kwikwag** [comment]
The following paragraph should probably be at the top:

> If you're looking for the lowest possible barrier to entry with Workbox, the CLI is for you:
>
>     npm install workbox-cli --save-dev
>
> To start using the CLI, run the wizard with `npx workbox wizard`.

**Comment by pwbriggs** [comment]
Hi, @kwikwag, thanks for the report!

PRs are always welcome, though they probably won't be merged anytime soon. It looks like there isn't anyone with write access left on the team: the last commit was 7 months ago. All we can really do right now is wait.🤷

**Comment by manasvi111** [comment]
Hello all,

I would definitely love to work with you guys for all the documentation work, Please let me know how I can help you.

Thank you

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
