### ISSUE TITLE
sw-cli globIgnores field doesn't seem to work

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/workbox#329]
**Library Affected**:
sw-cli

**Browser & Platform**:
Node v7.7.2

**Issue or Feature Request Description**:
If I modify the generated config file (`sw-cli-config.json`) to update the `globIgnores` field by adding "node_modules/*" (or "/node_modules/*"), and rerun `sw-cli`, the generated `sw.js` file still has node_modules files in it.

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

```json
{"rootDirectory":"./","globPatterns":["**/*.{sample,md,js,svg,html,css}"],"dest":"sw.js","globIgnores":["sw.js","node_modules/*","/node_modules/*","node_modules"]}
```

**Comment by addyosmani** [comment]
@samthor Thanks for the feedback. I've been able to repro this locally - are you able to move ahead using just sw-build?

**Comment by sap9433** [comment]
Same issue exists 
``` ...(isAnalyze ? [new BundleAnalyzerPlugin()] : []),
        new workboxPlugin({
            globDirectory: '../',
            globPatterns: ['**/*.{css,js}'],
            swDest: path.join('../', 'sw.js'),
            clientsClaim: true,
            skipWaiting: true,
            globIgnores: [
                'node_modules/'
            ],```

I still see 

```
 {
    "url": "progressive/node_modules/@storybook/react/dist/client/preview/init.js",
    "revision": "18806467fa3e94c9224e1dcb231ec523"
  },
  {
    "url": "progressive/node_modules/@storybook/react/dist/client/preview/reducer.js",
    "revision": "80ce90213a58d285f0e22b7247f11232"
  },
`` In my sw.js . 

Using webpack workbox sw
```
  "raw": "workbox-sw@^2.1.1",
        "scope": null,
        "escapedName": "workbox-sw",
        "name": "workbox-sw",
        "rawSpec": "^2.1.1",
        "spec": ">=2.1.1 <3.0.0",
        "type": "range"
```

**Comment by jeffposnick** [comment]
The `glob` syntax is a bit funky with regard to partial vs. full matches, and what is necessary for the [`ignore` option](https://github.com/isaacs/node-glob#options).

The [default](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/constants.js#L7) `globIgnores` setting in v2, if you don't override it, is `'node_modules/**/*'`, and that *should* work. Can you try with the latest copy of Workbox installed, without overriding the default, and confirm that it's not picking up`node_modules/`?

**Comment by arthurmuchir** [comment]
Is this fixed ? Still got problems with `globIgnores: ['**/*.{json,map}']`, still getting `.json` files in my `precache-manifest.js`

**Comment by jeffposnick** [comment]
`globIgnores` should work, yes. If you're not seeing that, could you please open a fresh issue with the details of your full build configuration?

**Comment by arthurmuchir** [comment]
Done https://github.com/GoogleChrome/workbox/issues/1353
