### ISSUE TITLE
Allow filtering of logs with a callback

### ISSUE THREAD

**Issue by surma** [GoogleChrome/workbox#332]
... or something similar. This would allow to limit the logs in the console to certain routes, filetypes et al.

**Comment by gauntface** [comment]
Use case here with to filter logs based on route.

**Comment by jeffposnick** [comment]
In v4, we've removed the concept of log level filtering in the interest of a smaller logging runtime: https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-core/_private/logger.mjs

The general advice moving forward is for developers to use the built-in filtering (either log level based, or via substrings) in their browser's DevTools.

CC: @philipwalton
