### ISSUE TITLE
Incorrect doc for sw-build.getManifestFileEntries

### ISSUE THREAD

**Issue by arthurevans** [GoogleChrome/workbox#348]
**Library Affected**:
`sw-build`

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Docs example (https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-build.html) shows `getManifestFileEntries` returning a promise, but currently it appears to just return the array.

**Comment by jpmedley** [comment]
I followed the calls in the source code. It appears to be promises all the way down.

**Comment by arthurevans** [comment]
I tried to run this sample code:

```
const swBuild = require('sw-build');

swBuild.getFileManifestEntries({
  rootDirectory: './build/',
  globPatterns: ['**\/*.{html,js,css}'],
  globIgnores: ['admin.html']
})
.then((fileDetails) => {
  // An array of file details include a `url` and `revision` parameter.
});
```

The code throws an error (`swBuild.getFileManifestEntries(...).then is not a function`).

Looking at the API doc, it says the method returns an array, not a promise:

https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/get-file-manifest-entries.js#L30

Not sure if it was originally intended to return a promise, but it doesn't currently.

**Comment by gauntface** [comment]
So I'm a bit lost with this one.

The code returns a promise from what I can see and the tests are working with promises, so I'm unsure why you would be getting a promise.

Maybe we just shipped an old version that wasn't a promise and now it is.

Tested with:

```
const swBuild = require('sw-build');

swBuild.getFileManifestEntries({
  rootDirectory: '.',
  staticFileGlobs: ['**/*']
})
.then((fileDetails) => {
  console.log(fileDetails);
});
```
@addyosmani can you confirm the same?
