### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox#349]
According to Matt's comment in [my draft](https://docs.google.com/document/d/1MC6pO3rF8g9op22YRD9thG2k-YWhOT1EUm5PkYXOhN0/edit#heading=h.2pkgvbx78pck):

"It might be worth doing a few things:

- Include a way to install in a build process (copying from node modules).
- Include a way to just download the latest release as a zip to include (feels more natural that npm install and copy)"

**Comment by jeffposnick** [comment]
I'm not clear on what this is currently tracking. @jpmedley, is this an issue that should be assigned to you, reflecting some documentation changes?

**Comment by jpmedley** [comment]
No. This is a request for enhancement. When Matt made the suggestions in a draft, I thought I'd be nice and create a tracking bug for him.

**Comment by jeffposnick** [comment]
Thanks for the context.

"Include a way to install in a build process (copying from node modules)." currently happens automatically as part of `workbox-cli generate:sw`.

"Include a way to just download the latest release as a zip to include (feels more natural that npm install and copy)" is being tracked in https://github.com/GoogleChrome/workbox/issues/615
