### ISSUE TITLE
Not clear how this works: 'What is the root of your web app?' 

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/workbox#356]
**Library Affected**:
sw-cli

When I run `sw-cli generate:sw`, I get the question about the root of my web app, but I can only press return to then manually enter the path. 'Use arrow keys' doesn't seem to make sense at this point (and doesn't seem to do anything).

![image](https://cloud.githubusercontent.com/assets/205226/23931696/7df69e46-0987-11e7-9f03-eb25bb6239b2.png)

**Comment by gauntface** [comment]
@samdutton I don't suppose you recall what the file structure was when you ran this? This should list out the available folders in the current directory, but if none are available, then you have to manually enter something.

I can change this to just ask for the root directory and default to '.' if there are no directories, but it feels like a weird use case, would it be better to display an error message?
