### ISSUE TITLE
Create a standalone guide to routing

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#371]
**Library Affected**:
*sw-routing*, *sw-lib*

Related to https://github.com/GoogleChrome/sw-helpers/issues/237 (and somewhat related to https://github.com/GoogleChrome/sw-helpers/issues/281), I think we'd benefit from a standalone guide to routing that provides more context than what you'd get from reading the JSDocs.

Proposed outline:
- Why is routing important?
- How does routing work with precached assets?
  - Explain the cache-first routes that are automatically created.
  - `NavigationRoute` and App Shell concepts.
- How does routing work for assets cached at runtime?
  - `RegExpRoute` & `ExpressRoute`, with examples for both same- and cross-origin routes.
  - Advanced routing via `Route`, with examples of why that might come in handy.
- Specifying a handler, and using `RequestWrapper` plugins to apply options to that route.

I am happy to write the material, but would appreciate if once it's reviewed and in good shape, @jpmedley could take ownership and think about how it should fit into the overall documentation structure and onboarding flow.

**Comment by gauntface** [comment]
Can we delay writing this until #281 is fixed and solved.

I think we all are aware that this is a big issue - but I think we can make huge steps to simplify this stuff.

**Comment by addyosmani** [comment]
> Can we delay writing this until #281 is fixed and solved.

Yeah. Let's wait to address 281 before we try knocking this one out.

**Comment by gauntface** [comment]
Note from @philipwalton 

> Also, I remember not really understanding what the routing concept was the first time I looked at sw-toolbox last year.
>
> I think it makes perfect sense now, but I remember my initial reaction thinking it was related to route handling rather than just route caching. And I was like: I don't need route handling on my blog, so this library isn't for me.

**Comment by gauntface** [comment]
@jeffposnick you've been working on an extending workbox guide - would that close this issue?

**Comment by jeffposnick** [comment]
Yup.
