### ISSUE TITLE
[sw-build/sw-cli] Add all the options from sw-precache

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#397]
Add in sw-build
- [x] cacheId [String]
- [x] clientsClaim [Boolean]
- [x] directoryIndex [String]
- [x] dontCacheBustUrlsMatching [Regex]
- [x] dynamicUrlToDependencies [Object⟨String,Array⟨String⟩⟩]
- [x] handleFetch [boolean]
- [x] ignoreUrlParametersMatching [Array⟨Regex⟩]
- [x] ~~importScripts [Array⟨String⟩]~~
- [x] ~~logger [function]~~
- [x] maximumFileSizeToCacheInBytes [Number]
- [x] navigateFallback [String]
- [x] navigateFallbackWhitelist [Array⟨RegExp⟩]
- [x] runtimeCaching [Array⟨Object⟩]
- [x] skipWaiting [Boolean]
- [x] staticFileGlobs [Array⟨String⟩]
- [x] modifyUrlPrefix (This is a replacement of the following options)
    - [x] replacePrefix [String]
    - [x] stripPrefix [String]
    - [x] stripPrefixMulti [Object]
- [x] ~~templateFilePath [String]~~
- [x] ~~verbose [boolean]~~

Add in sw-cli
- [ ] cacheId [String]
- [ ] clientsClaim [Boolean]
- [ ] directoryIndex [String]
- [ ] dontCacheBustUrlsMatching [Regex]
- [ ] dynamicUrlToDependencies [Object⟨String,Array⟨String⟩⟩]
- [ ] handleFetch [boolean]
- [ ] ignoreUrlParametersMatching [Array⟨Regex⟩]
- [ ] ~~importScripts [Array⟨String⟩]~~
- [ ] ~~logger [function]~~
- [ ] maximumFileSizeToCacheInBytes [Number]
- [ ] navigateFallback [String]
- [ ] navigateFallbackWhitelist [Array⟨RegExp⟩]
- [ ] runtimeCaching [Array⟨Object⟩]
- [ ] skipWaiting [Boolean]
- [ ] staticFileGlobs [Array⟨String⟩]
- [ ] modifyUrlPrefix (This is a replacement of the following options)
    - [ ] replacePrefix [String]
    - [ ] stripPrefix [String]
    - [ ] stripPrefixMulti [Object]
- [ ] ~~templateFilePath [String]~~
- [ ] ~~verbose [boolean]~~

**Comment by addyosmani** [comment]
staticFileGlobs logic (we were just talking about it in person):

https://github.com/GoogleChrome/sw-precache/blob/ac7da0e19eda26a6fb1ac50ba6c35ee2145edf56/lib/sw-precache.js#L160

https://github.com/GoogleChrome/sw-precache/blob/13a12d665b2b7670c38123171a43e5ac8cc21d84/cli.js#L67

**Comment by gauntface** [comment]
globPatterns instead of staticFileGlobs.

**Comment by gauntface** [comment]
All config options can be passed to the CLI via the config file. I'm going to opt out of adding these as flags because frankly it makes little to no sense to me and @jeffposnick has given me the impression it was a bad thing to support in sw-precache as it became a maintanence burden.

Feel free to re-open if you disagree.

**Comment by jeffposnick** [comment]
👍  to not encouraging the use of complex CLI flags.
