### ISSUE TITLE
Offline-Analytics demo does not work in Firefox

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#402]
**Library Affected**:
sw-offline-google-analytics

**Browser & Platform**:
Firefox

**Issue or Feature Request Description**:
From @steveworkman (originally posted here: https://github.com/GoogleChrome/samples/issues/507)

When replaying the analytics request in Firefox, the object store is opened but the cursor is never returned due to a TransactionInactiveError. This does not happen in Chrome.

It may be better to re-write this code with IndexedDB 2 syntax and promises as the whole code isn't very testable with lots of global variables that aren't reset between tests. I've had a go at doing this for myself, and the gist of that is here: https://gist.github.com/steveworkman/90936242b21c7b85a43525fd911c1242

**Comment by gauntface** [comment]
@steveworkman Thanks for raising this.

We are actually looking to @philipwalton for a re-write of this module (largely to take advantage of the background sync library.

Can't say I'm aware of the IndexedDB 2 syntax.

**Comment by addyosmani** [comment]
@prateekbh @philipwalton  This raises an interesting point for us. The current plan for offline analytics was to rewrite it using the background-sync-queue library. 

This has a dependency on BackgroundSync, which, unless I'm mistaken hasn't shipped in Firefox just yet but appears to be [getting pretty close](https://bugzilla.mozilla.org/show_bug.cgi?id=1217544). Does the sync-queue library have any fallbacks? My understanding was it didn't, but Phil was asking earlier and it would be great to sanity check.

We would want the rewrite to both work in Firefox once BG sync ships (probably targeting Firefox Nightly once it lands) and may want to keep IDB 2.0 usage in mind if we're also running into transaction errors per Matt's original bug report.

**Comment by prateekbh** [comment]
@addyosmani yea background sync queue library currently only works on `sync` event of service worker.
It makes total sense to target for Firefox to ship this. Also I use `idb` node module from our package to do the indexed-db thingy. may be we can check `idb` works fine with IDB 2.0

**Comment by philipwalton** [comment]
Perhaps we could provide an API that gives us sync-like behavior in all browsers. We could feature detect `self.SyncEvent` and offer real sync in supporting browsers, and we could offer something similar to what we already do in `offline-google-analytics` today.

The basic gist of what we do now is add a fetch handler that keeps track of failed/successful requests. If a request we care about fails, we add it to a queue and then if any other request succeeds, we (at that point) retry everything in the queue.

**Comment by prateekbh** [comment]
@philipwalton great point. Of what I can imagine, I can imitate the entire behavior(replay all the queued requests) even on the event of a broadcastMessage or even a post message.
I'll expose a method replayAll in backgroundSync library that you can call in `service-worker` as per the `offline analytics` library logic.

**Comment by addyosmani** [comment]
As discussed in today's team sync, I think the approach of exposing a hook consuming libraries/modules can use to define their own fallback behavior sounds reasonable. Would that work for your use-case of getting everything working cross-browser, @philipwalton?

**Comment by philipwalton** [comment]
@addyosmani do we have a proposed API? I'm not sure what you mean by "define their own fallback behavior". What does this hook give me over manually implementing the feature detection and fallback myself?

**Comment by steveworkman** [comment]
Glad we're all having this conversation, background sync sounds like a better approach than having the worker do things when it's next active. My problem here was with IndexedDB itself, rather than the worker method.

The better news is that I solved it, and it was a lib from @jaffathecake that helped. 

In that gist, I had re-written the IndexedDB code to use promises, which made the whole thing more testable. However, I then ran in to Firefox issues with transactions. Turns out, as Jake puts it in https://github.com/jakearchibald/idb#transaction-lifetime

> At time of writing, all browsers aside from Chrome don't treat promise callbacks as microtasks, or call microtasks incorrectly. This means transactions end by the time promise callbacks are called. In practice, this means you cannot perform transactions that involve waiting for a value, then using it within the same transaction.

Also, from the MDN https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Adding_data_to_the_database

> Transactions are tied very closely to the event loop. If you make a transaction and return to the event loop without using it then the transaction will become inactive.

I've updated the gist and it now works cross-browser. The original offline-analytics will also work, as it's not written with promises.

Also, when I was talking about IDB2.0 I meant the [ObjectStore.getAll() method](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getAll) which would prevent that nasty bit of cursor code in the replayAnalyticsRequests function

**Comment by prateekbh** [comment]
@philipwalton as far as backgroundSyncQueue is concerned I will expose a method `.replayAll()` which offlineAnalytics library can decide to call inside the service worker, whenever it sees fit.

**Comment by philipwalton** [comment]
These issues should no longer apply in v3 (both the transaction issue and the `sync` event issue). I'm going to close this, and we can re-open if specific bugs appear.
