### ISSUE TITLE
sw-offline-omniture-analytics

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#41]
**Library Affected**:
sw-offline-omniture-analytics

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
There's some interest in replicating the general approach of `sw-offline-google-analytics`, but making it work with the URLs used by the [Omniture/Adobe analytics platform](http://www.adobe.com/marketing-cloud/web-analytics.html).

Bonus points if this was done in a way that abstracted the idea of queueing/replaying requests in generic core library, and then we can just add in specific logic to match the URL patterns used by each of the platforms we care about, with helper methods to adjust the URL parameters appropriately before the URLs are replayed.

**Comment by ithinkihaveacat** [comment]
Any thoughts on what to do with the responses? Seems difficult to return them to the caller in a reasonable way. Maybe `fetchMaybeLater()` could return an integer `id` (similar to `setTimeout`) that can be used to cancel requests and retrieve responses. (The caller will probably need to poll.)

Another possibility is to throw the responses away.

**Comment by addyosmani** [comment]
@ithinkihaveacat Did you have any interest in working on this one? :)

**Comment by ithinkihaveacat** [comment]
Why yes, yes I do.

You got any thoughts on what to do about responses? (I haven't got any better ideas in the month since I last thought about this…)

**Comment by jeffposnick** [comment]
I'm much more familiar with the Google Analytics platform, but at least there, the responses to the hit requests are [universally](http://stackoverflow.com/questions/19451738/universal-analytics-measurement-protocol-respond-200-ok-but-no-events-appers) `200 OK`, and aren't meaningful. The code that replays failed Google Analytics hits just ignores the responses rather than trying to communicate them to the controlled clients.

**Comment by gauntface** [comment]
Closing this since the next google analytics should be based off of bg-sync which someone could use to write this library if they wanted.
