### ISSUE TITLE
Defaults in sw-build

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/workbox#421]
**Library Affected**:
sw-build

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
Issue

So `sw-build` should have a defined set of defaults to it, which it can use if the developer passes nothing.

This will also avoid various build step plugins to define these defaults randomly on their own will.

**Comment by prateekbh** [comment]
Suggested defaults:
```js
{
  globPatterns: ['**\/*.{js,css}'],
  globIgnores: [],
}
```
I guess root directory and dest are vary a lot per project, hence its best to not to default them maybe. Thoughts?

**Comment by gauntface** [comment]
Also for the `<root directory>/sw.js` being the default service worker output.

**Comment by jpmedley** [comment]
Will this need to be documented anywhere other than the JSDoc annotations.

**Comment by gauntface** [comment]
I don't think so no.
