### ISSUE TITLE
Helper for cacheFirst, with default fallback URL?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#438]
**Library Affected**:
*sw-lib, sw-runtime-caching*

It's fairly common, especially with images, to want to use a cache-first strategy, and if the URL isn't already in the cache and the network is unavailable, fallback to a previously cached "default" entry.

It's possible to get this behavior in `sw-lib` using something along the lines of:

```js
// Assume that this URL is precached.
const FALLBACK_IMAGE_URL = '/images/fallback.png';
const imagesHandler = sw.strategies.cacheFirst();
swlib.router.registerRoute(new RegExp('/images/'), ({event}) => {
  return imagesHandler.handle({event})
    .catch(() => caches.match(FALLBACK_IMAGE_URL));
});
```

You can do something similar using the modules from `sw-runtime-caching` directly.

I wonder whether it makes sense to provide a helper to accomplish this? The most straightforward approach would be to add in an optional parameter to the cache-first handler constructor for the fallback URL.

An added wrinkle would be ensuring that the fallback URL is actually present in the cache, but rather than attempting to manage that cache entry, we could just use logging to let developers know if the fallback entry is missing.

**Comment by gauntface** [comment]
Given sw-lib is a worrying size as it is, for now I'd suggest making this a recipe in docs and see if it gets used or not - if it does, then look to bake it in.

**Comment by jeffposnick** [comment]
This has come up a few times (most recently by @codepunkt) and it's something that I wanted to bump up (though likely post-v3).

**Comment by codepunkt** [comment]
Ouch. If this is not possible right now, it's a deal breaker for me. Is it possible?

**Comment by jeffposnick** [comment]
As mentioned in the other issue thread, here's another use case that we should try to accomodate:

```js
const matcher = ({event}) => event.request.mode === 'navigate';
const handler = () => fetch('/app-shell.html').catch(() => caches.match('/offline.html'));

workboxSW.router.registerRoute(matcher, handler);
```

**Comment by gauntface** [comment]
There are a number of ways that we can solve this and I'm pretty set that *another* config option isn't the right way to do it.

Other options:
- plugin: Give a callback with a final option to return something. Gives developer full control of the behavior.
- Sanitise the API of the routing / runtime-caching modules such that there isn't the awkward`.handle()` call.
- Supply a catch handler to achieve the same thing.

**Comment by arthow4n** [comment]
Hi there, I found this is removed from V3 milestone, does that mean there will not be an official solution for this in V3?

**Comment by gauntface** [comment]
Not at the moment no sorry.

**Comment by joe1chen** [comment]
@jeffposnick For some reason the code that you posted just didn't work for me but it did give me a clue as to where to start.  The `catch` code just never got called when offline and it would show the default browser offline page.

I ended up getting getting it to work with the following code. I noticed that the `then` function returns an undefined response when offline so I return the cached offline page there.  Not sure if this is the best way to do it so any suggestions or improvements are appreciated.

In my use-case I want network first functionality, with fallback to cached pages when offline, and then fallback to offline.html when there is a cache-miss.

My sample code is using ES5 syntax, `networkFirst` instead of `cacheFirst` , and v3 `workbox.routing.registerRoute` instead of v2 `workbox.route.registerRoute`.

```javascript
var networkFirstHandler = workbox.strategies.networkFirst({
  cacheName: 'default-cache'
});

workbox.routing.registerRoute(
  function(r) {
    var event = r.event;
    return event.request.mode === 'navigate';
  },
  function(args) {
    return networkFirstHandler.handle(args).then(function(response) {
      if (typeof response == 'undefined') {
        // Offline
        return caches.match('/offline.html');
      }
      return response;
    });
  }
);

// Set a default network-first strategy to use when
// there is no explcit matching route:
workbox.routing.setDefaultHandler(networkFirstHandler);
```

**Comment by ctf0** [comment]
@jeffposnick for the cache name use `cacheName: workbox.core.cacheNames.precache,`, this way u add pages to the same cache as `templatedUrls`

**Comment by jeffposnick** [comment]
There's an updated recipe at https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route that outlines a generic fallback using `workbox.routing.setCatchHandler()` in Workbox v4.

I think we're going to stick to the recipe-based solution rather than explicitly adding to the core Workbox functionality.
