### ISSUE TITLE
Move to npm orgs?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#456]
**Library Affected**:
*all*

See https://docs.npmjs.com/misc/orgs

I can see the benefit of grouping all the "official" modules under `@workbox`.

It would also be nice to manage permissions on the organization level, rather than having to manually add all the folks who potentially might need to publish to `npm` to each individual package.

**Comment by addyosmani** [comment]
Drive-by thoughts:

- Are there user perceivable benefits or downsides to this change? Is switching to an org mainly for our own reasoning + permissions management needs.

- If we want to do this, we should do it for launch imo. It can get confusing for users (or has in other cases) when some of your community articles talk about `npm install foo` and official docs say `npm install @foo/bar`. I experienced this quite a bit when Angular made the shift to orgs.

**Comment by gauntface** [comment]
I'm personally **not** in favor of this because of the mental overhead for developers (i.e. remembering the org name followed by module name: workbox/*)

**Comment by jeffposnick** [comment]
I don't feel strongly either way—was just throwing it out there.

@gauntface's negative stance means it's worth leaving things un-organiz-ed.

**Comment by sindresorhus** [comment]
Just for reference, you can use npm orgs without using scoped packages (`@workbox/*`). I have for example a [`chalk`](https://www.npmjs.com/org/chalk) org to ease permission maintenance, but none of the packages are scoped.

**Comment by gauntface** [comment]
@jeffposnick it's back in the game.

@sindresorhus is it relatively easy to set up / anything we should be aware of?

**Comment by addyosmani** [comment]
@sindresorhus Oh super neat. I had no idea the orgs could be used without packages themselves being. With that in mind, I'd be down with us going down that path here.

Totes aside: how did you even come across this issue? :D.

**Comment by sindresorhus** [comment]
@gauntface The only slight annoyance is that the person that originally published the npm package is the one that has to add it to the org. At least it was like that a month ago.

This is the command you use to add a package to an org:

```
npm access grant read-write org-name:developers package-name
```

**Comment by sindresorhus** [comment]
> Totes aside: how did you even come across this issue? :D.

I was bored, so I stalked your recent activity.

**Comment by jeffposnick** [comment]
We're live with 12 packages owned by the @workboxjs org: https://www.npmjs.com/org/workboxjs
