### ISSUE TITLE
sw-lib docs need a complete example

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/workbox#462]
**Library Affected**:
*sw-lib*

**Browser & Platform**:
*Docs*

**Feature Request Description**:
sw-lib does a lot of out of the box stuff for devs, e.g. swlib.precache([]) precaches and handles fetch(by default). Whereas for custom caching strategies devs need to add URLS to cache manually.

https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.19/module-sw-lib.SWLib.html#runtimeCacheName

So its a mix of some things taken care of vs some to be still done by devs. This sometimes creates a confusion of what is already done vs what code is to be written.

Can we include a minimal sw written using SwLib which outlines well how to use this lib?

Also I guess being explicit about which methods have `fetch` handler by default and which do not, will help docs a lot.

**Comment by jpmedley** [comment]
Is there some reason the [sw-lib overview](https://googlechrome.github.io/sw-helpers/sw-lib.html#main) doesn't resolve this issue? FYI I just submitted a [PR that changes](https://github.com/GoogleChrome/sw-helpers/pull/509) `cacheRevisionedAsset()` to `precache()`.

**Comment by gauntface** [comment]
+1 @jpmedley's comment, is there anything missing from the explainer that you think we should add @prateekbh ?

**Comment by addyosmani** [comment]
Friendly ping @prateekbh

**Comment by prateekbh** [comment]
@addyosmani #514 is already out, but pretty sure wont be able to fix it before monday

**Comment by addyosmani** [comment]
Thanks for the update!

**Comment by jeffposnick** [comment]
This should hopefully be https://workboxjs.org/examples/workbox-sw/

If that's not sufficient, please file issues/PRs against `workbox-microsite`.
