### ISSUE TITLE
sw-cli Minor Tweak

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#469]
Instead of swapping out path seperators for glob paths, can do a trick with path.posix.

Instead of:
```
const globPath = path.join(relativePath, '**', '*').replace(path.sep, '/');
```

You can do:
```
const globPath = path.posix.join(relativePath, '**', '*');
```

**Comment by addyosmani** [comment]
As a quick fyi, `path.posix` won't replace `\` with `/` if our relative paths contain those so you end up needing to do them manually. React uses [this](https://github.com/Timer/create-react-app/blob/8707fa3f6f18dd3ea9f63923082d36a4b23f78da/packages/react-scripts/scripts/test.js#L35) pattern to work around it using `replace` with posix.

@sindresorhus might know if there are any other gotchas with switching to `posix` for the use-case here.

**Comment by gauntface** [comment]
This came from a comment @sindresorhus put in an old PR.

**Comment by gauntface** [comment]
@sindresohus what's you take on the React pattern vs your suggestion vs the origin solution?
