### ISSUE TITLE
Offer versioned library files for download (and perhaps in npm package)

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#470]
**Library Affected**:
*sw-build*

[`copy-sw-lib.js`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/utils/copy-sw-lib.js) is currently used inside of `generateSW()` to add versioning info to the `sw-lib.js` file, and copy it to the destination directory that will also host the service worker.

I think we need to extend that functionality to:
- Allow users to specify multiple libraries to apply this to. There might be a hardcoded default of `sw-lib`. It's easy to imagine users wanting to use it for, e.g., `sw-offline-google-analytics` or a push library.
- In addition to copying over the versioned files, automatically inject the correct `importScripts('sw-lib-v1.0.0.js', 'sw-blah-v1.0.0.js');` code into the generated service worker. Similar to how we currently look for `precache([])` and use that as a replacement point, we could look for an empty `importScripts()` and do the same (or we could just unconditionally put it at the top of the file).
- Expose it as an option in methods other than `generateSW()`, like `injectManifest()`.

The theoretical usage, with `injectManifest()`:

```js
swBuild.injectManifest({
  swSrc: SW_SRC_PATH,
  swDest: SW_DEST_PATH,
  // Should we require 'sw-lib' to be listed, or just unconditionally copy/inject it?
  importModules: ['sw-lib', 'sw-offline-google-analytics'],
  globDirectory: BUILD_DIR,
  staticFileGlobs: [
    'static/{js,css,data}/**/!(*map*)',
  ],
})
```

**Comment by gauntface** [comment]
Two concerns:

1.) How does a developer develop locally?
2.) Why not just give people a version file to download and move into their project?

**Comment by jeffposnick** [comment]
After having just tried the manually-copy-a-versioned-file-locally approach... okay, that's probably fine. I should have been more open minded!

Should we leave this open to track distributing versioned files as part of what we publish to npm?

**Comment by gauntface** [comment]
yeah - I'd also like to find some vague way to offer just a download button on the microsite.

**Comment by addyosmani** [comment]
> yeah - I'd also like to find some vague way to offer just a download button on the microsite.

I am supportive of a download button. Would this require CDN hosting?

**Comment by jeffposnick** [comment]
FWIW, the CDNJS folks took it upon themselves to host a mirror of `sw-toolbox`: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/sw-toolbox/

I don't know if that would make sense as the "official" distribution point or not.

**Comment by jeffposnick** [comment]
With #502 complete, links like

`<a href='https://unpkg.com/sw-lib@0.0.22/build/importScripts/sw-lib.prod.v0.0.22.js' download>sw-lib</a>`

should be sufficient to trigger a download. I'll add in those sorts of links into the docs templates.

**Comment by gauntface** [comment]
Closing this issue in favor of a more focused issue to cover library usage + docs: #615
