### ISSUE TITLE
Instructions Show Importing File that is No Longer Separate

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox#494]
[This heading](https://googlechrome.github.io/sw-helpers/recipes/rollup.html#service-worker-code) has example code that imports a `manifest.js` file. This file is no longer generated which makes that code impossible to use. Do I need to remove this instruction, or is there a way to create a manifest that I'm not aware of and that I need to document?

**Comment by jeffposnick** [comment]
There are different approaches to using `sw-build`. One approach that still works does involve generating a standalone `manifest.js` and then bundling it in using a tool like Rollup. There's an example of how to generate this manifest file just slightly below what you linked to, [here](https://googlechrome.github.io/sw-helpers/recipes/rollup.html#npm-scripts), via `swBuild.generateFileManifest()`. That method is already [documented via JSDoc](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.19/module-sw-build.html#.generateFileManifest) in addition to this "recipe".

It's not necessarily the approach that's the easiest onramp for new developers, but it does solve a specific use case.

**Comment by gauntface** [comment]
I do think the IA for the recipes needs a lot of work. Would be good to just call out "Working with Grunt, Gulp, Rollup, WebPack, XYW" to get people to pick their poison ASAP.
