### ISSUE TITLE
Issues with npm i -g sw-cli

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox#503]
**Issue or Feature Request Description**:
Upgrade is unable to correctly identify the most recent and the current.

After running sw-cli I was prompted to update to 19 even though 20 has been released.

```
   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 0.0.18 → 0.0.19    │
   │     Run npm i -g sw-cli to update     │
   │                                       │
   ╰───────────────────────────────────────╯
```
  
After upgrading I ran sw-cli again. The notice now correctly identifies 20 as the correct current version, but still thinks I'm running 18.

```
   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 0.0.18 → 0.0.20    │
   │     Run npm i -g sw-cli to update     │
   │                                       │
   ╰───────────────────────────────────────╯
```

**Comment by gauntface** [comment]
If you run `sw-cli --version` what do you see?

**Comment by gauntface** [comment]
Friendly ping on this: @jpmedley

**Comment by jpmedley** [comment]
I get 0.0.20.

**Comment by gauntface** [comment]
and it's still telling you to update?

**Comment by jpmedley** [comment]
Now running as `workbox-cli generate:sw`. It's not telling me to update.
