### ISSUE TITLE
Flaky "should be able to generate a service for example-1 with CLI" test on Windows

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#517]
**Library Affected**:
*sw-cli*

As per https://github.com/GoogleChrome/sw-helpers/pull/515#issuecomment-300049420, the update to `fs-extra` `3.0.1` has a fix for a bug in the `removeSync()` call on Windows. The call used to silently fail, and [now it throws an error when it fails](https://ci.appveyor.com/project/gauntface/sw-helpers/build/1.0.468#L1277), along the lines of

```sh
Error: EBUSY: resource busy or locked, rmdir 'C:\projects\sw-helpers\packages\sw-cli\test\node\tmp-nb4q2K'
```

The "should be able to generate a service for example-1 with CLI" test used to pass on Windows due to that older behavior, and now throws an exception in the `after()` block. The code that throws an exception isn't crucial—it just cleans up a temporary directory—so for the time being it can be suppressed by adding a `catch()` clause, getting back to a passing state in AppVeyor.

This bug tracks finding a way to cleanly remove that temporary directory on Windows, so we can remove the `catch()`.

**Comment by gauntface** [comment]
Thank you for this - I have noticed a problem on the  local test so happy to explore this.

**Comment by jeffposnick** [comment]
FWIW, I'm also seeing failures on OS X:

```sh
  1) Test Runner Environment  Node Tests for workbox-cli Generate SW End-to-End Tests should be able to generate a service for example-1 with CLI:
     Error: ENOENT: no such file or directory, open 'build/1494608589029-sw.js'
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.readFileSync (fs.js:491:33)
      at generateSWCb.then (packages/workbox-cli/test/utils/e2e-sw-validator.js:107:26)
```

It's happy in the Travis CI Linux environment, for whatever reason.

**Comment by gauntface** [comment]
With Windows builds fixed and a simplified build I'm going to close this. The removing of directories is still a problem but it looks like there is no easy fix (A number of other projects have the same issue). But we are catching the error and hopefully it won't be an issue in the future.
