### ISSUE TITLE
Setup Google Analytics for the site

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#521]
Account created. The snippet we'll be using is:

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98793201-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by jeffposnick** [comment]
Or, you know, maybe we can convince @philipwalton to give us a nice [AutoTrack](https://github.com/googleanalytics/autotrack) setup...

**Comment by addyosmani** [comment]
That would also be welcome :)

**Comment by gauntface** [comment]
We have basic tracking in. @philipwalton if you'd like to switch to autotrack on https://github.com/GoogleChrome/workbox-microsite I'd be more than happy to take that PR ;)
