### ISSUE TITLE
Investigate alternative ES2015-friendly minifiers

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#523]
While we're currently using `babili` for our production builds, both https://github.com/Rich-Harris/butternut and https://www.npmjs.com/package/uglify-es might be viable options.

We should do a bit of a bake-off and see what the results are for our codebase.

**Comment by jeffposnick** [comment]
Rich Harris was good enough to publish https://github.com/rollup/rollup-plugin-butternut early.

Quick-and-dirty comparison:
- The `iife` build of `sw-lib` goes from 45906 bytes (13644 gzip-ed) w/Babili to 41572 bytes (12629 gzip-ed) w/Butternut.
- `gulp build`, covering all our build targets, completes in 12s w/Babili, 5s w/Butternut on my Macbook.

I haven't looked at `uglify-es` yet, and I haven't confirmed that the `prod` bundles that Butternut is building don't have any subtle bugs, but that does look encouraging!

**Comment by jeffposnick** [comment]
I'm revisiting this, and bumped up against https://github.com/Rich-Harris/butternut/issues/170 when trying out `butternut`.

(Technically we could modify [the code in question](https://github.com/GoogleChrome/workbox/blob/3d9edcf0058279148112407cee1f3e7a36eccb22/packages/workbox-sw/src/lib/workbox-sw.js#L341) to work around the bug, as removing the `async` keyword would make `butternut` happy. `async` isn't needed there, because the arrow function it's applied to doesn't call `await`. But I don't feel great about making changes to our codebase to work around a minification bug.)

**Comment by jeffposnick** [comment]
And https://www.npmjs.com/package/uglify-es doesn't support `async`/`await` at all yet, so that's off the table.

**Comment by gauntface** [comment]
Is there anything else to do here? Given that you've explored and raised issues I think we just need to wait until a time that it's worth a new issue to re-explore.

**Comment by jeffposnick** [comment]
`butternut` resulted in bundles that were small enough that I think it's worth leaving this open, to remind us that moving to `butternut` would still be a Good Thing once the output passes our test suite.

**Comment by gauntface** [comment]
Could we not just reopen this once / if https://github.com/Rich-Harris/butternut/issues/170 is address?

**Comment by jeffposnick** [comment]
Okay.

**Comment by anilanar** [comment]
O made a PR for that bug.

**Comment by kzc** [comment]
`uglify-es@3.0.20` supports async/await. File a bug report if there's any issue.

**Comment by gauntface** [comment]
I'm going to take this on. Will add it as a bit of infra testing so we can quickly run and compare sizes.

**Comment by gauntface** [comment]
V3 is using uglify-es with some pretty aggressive minifcation so I think this can be closed for now.

**Comment by kzc** [comment]
`rollup-plugin-uglify-es` appears to be [unused](https://github.com/GoogleChrome/workbox/search?utf8=✓&q=rollup-plugin-uglify-es&type=) and can be removed.

https://github.com/GoogleChrome/workbox/blob/a88bfc0cc5c2a87a5b1b7280e284a728728f09f1/package.json#L92
