### ISSUE TITLE
Creating landing page explaining our different builds

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#526]
**Library Affected**:
*sw-lib*

Related to https://github.com/GoogleChrome/sw-helpers/pull/522#discussion_r115802273, it would be ideal to have a place to link to in our "you're running a dev build on a prod server" console log message.

And then just in general, having an explanation of `importScripts` vs. `modules`, and why there are versions in the bundles' filenames, would be a good idea.

**Comment by gauntface** [comment]
Would good to capture the imports usage here:  https://docs.google.com/document/d/1ZzEeHb1E8-4YYp8yWHBA5mgYt8NneA8zQt2bC6Q3NwE/edit?usp=sharing

For the CDN use case, I suspect we don't need to worry about dev vs prod as we'll have the debug flag for this and by default, I suspect we can get away with doing the right for developers out of the box (i.e. dev on localhost, prod on domain).

**Comment by gauntface** [comment]
This has changed a great deal and I think the existing guides for v3 are a reasonable step to closing this.

I created a place holder doc in the guides section to cover more on the general approach of a Workbox module: https://docs.google.com/document/d/1GZinpmLjRGoYkV534UAZe-gWUfx0i6sUo7JBqFsAb0o/edit?usp=sharing
