### ISSUE TITLE
Better documentation around lifecycle methods + plugins

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#533]
**Library Affected**:
*workbox-runtime-caching*

There's some basic info about what lifecycle methods are exposed by `RequestWrapper`, but it would be good longer-term to create something more formal using the `@callback` JSDoc construct. A guide for writing your own plugins would follow from that initial work.

**Comment by jpmedley** [comment]
@jeffposnick If this isn't for JSDocs, can you start opening doc issues in the [microsite repo](https://github.com/GoogleChrome/workbox-microsite).

**Comment by jeffposnick** [comment]
At least the first part is for JSDocs.

**Comment by gauntface** [comment]
JSDocs is done now - Jeff did the initial work and I cleaned some of it up further in a seperate PR.

**Comment by gauntface** [comment]
Empty page for docs here:  https://docs.google.com/document/d/1Qye_GDVNF1lzGmhBaUvbgwfBWRQDdPgwUAgsbs8jhsk/edit?usp=sharing
