### ISSUE TITLE
generate:sw wizard Should ignore hidden directories when presenting folder to use as root

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox#549]
**Library Affected**:
*workbox-cli*

My test directory had two folders, `app/` and `.git/`. It doesn't seem like _any_ hidden folder would ever be the root of a site's content. If I'm right, then workbox-cli shouldn't offer hidden folders as an option.

**Comment by addyosmani** [comment]
Marking as P1. We'll need to verify this is indeed still the current behavior, but I agree that user expectation would probably not be to include hidden directories as a default.
