### ISSUE TITLE
Service worker generated using workbox-cli have a leading / on all cache urls

### ISSUE THREAD

**Issue by happyahluwalia** [GoogleChrome/workbox#560]
**Library Affected**:
*workbox-cli *
Version - 0.0.2
**Browser & Platform**:
*Windows *

**Issue or Feature Request Description**:
Workbox-cli generates service worker with leading / for all resources. When the application is deployed with a context the service worker tries to get resources from the root in place of the deployed context.
_*Service-worker.js_
```
const fileManifest = [
  {
    "url": "/favicon.ico",
    "revision": "b9aa7c338693424aae99599bec875b5f"
  },
  {
    "url": "/index.html",
    "revision": "6cf204a0a953ee40d3fa141b7956f229"
  }
```,
```
Application deployed - https://happyahluwalia.github.io/workbox_cli_angular/
If the application is deployed on root https://happyahluwalia.github.io it would work

_Browser console_ -

```
Failed to load resource: the server responded with a status of 404 (Not Found)
workbox-sw.prod.v0.0.2.js:19 Uncaught (in promise) Error: A request failed the criteria to be cached. By default, only responses with 'response.ok = true' are cached. [Failed to get a cacheable response for 'https://happyahluwalia.github.io/favicon.ico': The fetched response could not be cached due to an invalid response code.]
createError @ workbox-sw.prod.v0.0.2.js:19
_cacheEntry @ workbox-sw.prod.v0.0.2.js:127
happyahluwalia.github.io/inline.57d2da1b2c25fa8b4b09.bundle.js?_workbox-precaching=ec805a12fa23cc612b6febda9dccc3de 

```

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*
**URL to reproduce** -
https://happyahluwalia.github.io/workbox_cli_angular/

*This works fine when using _sw-precache_ with the following config 
```
module.exports = {
  staticFileGlobs: [
    'dist/**.html',
    'dist/**.js',
    'dist/**.css',
    'dist/assets/images/*',
    'dist/assets/icons/*'
  ],
  root: 'dist',
  stripPrefix: 'dist/',
```
This generates a proper precache array
`var precacheConfig = [["assets/icons/android-chrome-192x192.png","64da5a4808b2f87ae0b586cd5b6ad788"],["assets/icons/android-chrome-512x512.png","04ef6ef91cfeeda196f3db9a076ecad6"],["assets/icons/apple-touch-icon-precomposed.png","4b69c7b8d64998edc30cf4471474bc1f"],["assets/icons/apple-touch-icon.png","be0d780e27355840b44d54c1d7528b87"],["assets/icons/favicon-16x16.png","5eed5ce21008cd26fea4e1aa2b711e24"],["assets/icons/favicon-32x32.png","8322de8efd5fc2b20048b80ef98376d3"],["assets/icons/favicon.ico","f3f70846cad486fc894f0d6145364266"],["assets/icons/manifest.json","59d6638b32e5cda707afa1a49a19f2d8"],["assets/icons/mstile-150x150.png","f7c07b1ec08636a47fcf11a0fb782393"],["assets/icons/safari-pinned-tab.svg","39b1a8cf10302a2e0b6715210e67d675"],["index.html","ea8a344aa5526cfe582a2b0ba0e4c861"],["inline.17df75fc5aa227088541.bundle.js","24bdf471ed164c6bc42dc07c952096c9"],["main.1aa80e5c8afd694f3da0.bundle.js","8adb5ba75c54f92a234b73f7a782f39a"],["polyfills.60187f338ba5b0a175a8.bundle.js","e9c9878491f71e039235b9d3ace5bb0e"],["styles.d41d8cd98f00b204e980.bundle.css","d41d8cd98f00b204e9800998ecf8427e"],["vendor.5381ef5ca17ea08b1649.bundle.js","668ffe100aaf5dd4c621fd44884ea51a"]];
`

_Console Log_
![image](https://cloud.githubusercontent.com/assets/8081182/26161297/8c96bbde-3af1-11e7-8df0-babd40c7a1d3.png)

**Comment by happyahluwalia** [comment]
Looks like the fix is in  workbox/packages/workbox-build/src/lib/utils/filter-files.js
 line 25 
```
 if (!url.startsWith('/')) {
        url = '/' + url;

```

**Comment by jeffposnick** [comment]
Sorry that you're running into this, @happyahluwalia.

As an immediate workaround, you should be able to add

```js
{
  // Other workbox-build options...
  modifyUrlPrefix: {
    '/': ''
  }
}
```

to your Workbox build configuration. I need to sync up with @gauntface about our original rationale behind forcing that leading `'/'` on all URLs, but it sounds like something we should change.

**Comment by happyahluwalia** [comment]
Thanks @jeffposnick the workaround works 👍

**Comment by gauntface** [comment]
@jeffposnick more than happy to remove the forced forward slash. Can't think of a solid reason for it being needed.

**Comment by jeffposnick** [comment]
Cool—I wanted to confirm with you first because I vaguely remember some discussion when it was initially implemented. But removing it seems like the right approach.

**Comment by happyahluwalia** [comment]
I am on windows and unable to run all the tests (selenium needs OSX or Linux), can I submit a pull request without running full tests for this fix ? :)
