### ISSUE TITLE
Updating documentation on workboxjs.org

### ISSUE THREAD

**Issue by adactio** [GoogleChrome/workbox#572]
There doesn't seem to be a public repo for the workboxjs.org site so I'm posting this here (apologies if this isn't the right place).

Would it be possible to update the text:

> Then just reference the file from your service worker:

To read:

> Then reference the file from your service worker:

Rationale: using words like "just" and "simply" in documentation can be counterproductive.

<http://bradfrost.com/blog/post/just/>

**Comment by addyosmani** [comment]
@adactio Thanks for the feedback! The repo for the microsite is over at https://github.com/GoogleChrome/workbox-microsite. I appreciate the feedback and have dropped `just` usage from the homepage in https://github.com/GoogleChrome/workbox-microsite/commit/51308609e71ba3dbef35208fcf5f1c02c25113a5.
