### ISSUE TITLE
Service Worker generated by Workbox webpack plugin not creating write caches

### ISSUE THREAD

**Issue by happyahluwalia** [GoogleChrome/workbox#574]
**Library Affected**:
*workbox-webpack plugin 1.0.0*

**Browser & Platform**:
* "all browsers".*

**Issue Description**:
Options mentioned for runtime Caching in webpack config do not take effect in the generated Service worker.

**Webpack configuration**
 ```
new workboxPlugin({
       globDirectory: DIST_DIR,
       staticFileGlobs: ['**/*.{html,js,css}'],
       swDest: path.join(DIST_DIR, 'sw.js'),
       modifyUrlPrefix: {
                          '/': ''
                        },
        runtimeCaching: [{
                        urlPattern: /bbc-news/,
                        handler: 'networkFirst',
                        options: {
                          cache:{
                          name: 'bbc-cache',
                          maxEnteries: 10,
                          maxAgeSeconds: 300
                          }
                        }
                      },
                      {
                        urlPattern: /cnn/,
                        handler: 'cacheFirst',
                        options: {
                          cache:{
                          name: 'cnn-cache',
                          maxEnteries: 10,
                          maxAgeSeconds: 300
                        }
                        }
                      }]
     })
  ]
```
**Generated Service Worker**
```
const workboxSW = new self.WorkboxSW();
workboxSW.precache(fileManifest);
workboxSW.router.registerRoute(/bbc-news/, workboxSW.strategies.networkFirst({
  "cache": {
    "name": "bbc-cache",
    "maxEnteries": 10,
    "maxAgeSeconds": 300
  }
}));
workboxSW.router.registerRoute(/cnn/, workboxSW.strategies.cacheFirst({
  "cache": {
    "name": "cnn-cache",
    "maxEnteries": 10,
    "maxAgeSeconds": 300
  }
}));

```

The service worker is installed correctly however all request made to http url containing "bbc-news" are not cached. No new cache by name of 'bbc-cache' is created. Same for other specified options.

**Missing 'bbc-cache'**
![image](https://cloud.githubusercontent.com/assets/8081182/26278383/56baa732-3d67-11e7-9791-5ced0161c3b9.png)

**Http request going to network instead of cache**

![image](https://cloud.githubusercontent.com/assets/8081182/26278441/9ed359d2-3d68-11e7-8ca9-f320bf66ec86.png)

**SW_Precache**
However when I try this with sw-precache things work fine.
Same runtimeCaching option given to sw-precache. 
_Generated Service Worker
```
toolbox.router.get(/bbc-news/, toolbox.networkFirst, {"cache":{"name":"bbc-cache","maxEnteries":10,"maxAgeSeconds":300}});
toolbox.router.get(/cnn/, toolbox.cacheFirst, {"cache":{"name":"cnn-cache","maxEnteries":10,"maxAgeSeconds":300}});

```
This service worker also have the register, fetch and the toolbox code embedded in it.
![image](https://cloud.githubusercontent.com/assets/8081182/26285765/eb4900d0-3e23-11e7-8156-95296347091a.png)

_

**Comment by addyosmani** [comment]
@prateekbh If you get a chance, PTAL.

**Comment by prateekbh** [comment]
@gauntface looks like the service worker is generated, can you please check if there is anything missing?

**Comment by jeffposnick** [comment]
Thanks for reporting. The generated code:

```js
workboxSW.router.registerRoute(/cnn/, workboxSW.strategies.cacheFirst({
  "cache": {
    "name": "cnn-cache",
    "maxEnteries": 10,
    "maxAgeSeconds": 300
  }
}));
```

doesn't look correct; it should be:

```
workboxSW.router.registerRoute(/cnn/, workboxSW.strategies.cacheFirst({
  "cacheName": "cnn-cache",
  "cacheExpiration": {
    "maxEnteries": 10,
    "maxAgeSeconds": 300
  }
}));
```

The `runtimeCaching` parsing at https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/write-sw.js#L54 needs to be massaged a bit to account for the differences in `sw-toolbox` and Workbox.

**Comment by happyahluwalia** [comment]
@jeffposnick I was comparing sw-precache/toolbox with workbox assuming they would be same. 
Is there a JSON schema that we can refer while specifying in webpack config file that workbox would use to generate the correct code.
Similarly is there an output code that we can cross check to see if its correct.
This would make it simpler to find out bugs.

**Comment by nesterenko0602** [comment]
I have the same problem.

My gulpfile:
```
wbBuild.generateSW({
    cacheId: 'mu',
    swDest: './sw/sw.js',
    handleFetch: true,
    directoryIndex: 'index.php',
    globDirectory: '../../',
    globPatterns: [
      path.join(tmplDir, 'images/icons.svg'),
      path.join('offline.html')
    ],
    runtimeCaching: [{
      urlPattern: prod ?
        /https:\/\/manutd.one\/(\S{1,400}.html|match_overview\/|news\/)/:
        /http:\/\/localhost\/(\S{1,400}.html|match_overview\/|news\/)/,
      handler: 'cacheFirst',
      options: {
        cacheName: 'pages',
        cacheExpiration: {
          maxEntries: 100,
          maxAgeSeconds: 72 * 60 * 60
        },
        cacheableResponse: {statuses: [200]}
      }
    }],
    navigateFallback: '/offline.html',
    verbose: true
  })
```

But after I open several pages, CacheStorage contains only pre-cache files.
<img width="971" alt="2017-05-26 10 39 41" src="https://cloud.githubusercontent.com/assets/20835560/26485579/55c9e584-4200-11e7-85c1-c26ae2f0a388.png">

**Comment by staabm** [comment]
It seems I see this problem with a cli generated SW (no webpack etc)

**Comment by jeffposnick** [comment]
The legacy `runtimeCaching` parity should be addressed by #590.

Regarding https://github.com/GoogleChrome/workbox/issues/574#issuecomment-304215538, @nesterenko0602, your use of `workboxSW.router.registerNavigationRoute("/offline.html");` would likely take precedence over your explicit `registerRoute()` call following it.

I don't think that the `workboxSW.router.registerNavigationRoute("/offline.html");` pattern is great, actually, and you'd probably be better off removing it entirely. `registerNavigationRoute()` is intended for SPA-style apps that have a single `index.html` that is used for all URLs.

You can also try adding in

```js
self.workbox.logLevel = self.workbox.LOG_LEVEL.verbose;
```

and you should see some additional context that might be helpful.

**Comment by nesterenko0602** [comment]
@jeffposnick Thanks, I know about registerNavigationRoute, It was config which I wrote for sw-precache and in service-worker.tmpl changed priority order of registerNavigationRoute and registerRoute.
In workbox config I have removed this lines already.

**Comment by housseindjirdeh** [comment]
@jeffposnick FWIW I'm noticing the exact same issue using both `navigateFallback` and `runtimeCaching` for an Angular app. I'm assuming this is also because `workboxSW.router.registerNavigationRoute("/index.html")` is preceding `registerRoute` in the output.

Can `runtimeCaching` be leveraged whilst using an `index.html` fallback in order to have dynamic caching for an SPA?

**Comment by jeffposnick** [comment]
Can you share your configuration? And are you talking about runtime caching for subresources (e.g. images, fonts, etc.), or runtime caching for navigation resources (e.g. distinct HTML documents used for distinct URLs)?

**Comment by housseindjirdeh** [comment]
Cheers thanks for getting back so quickly mate :pray: Nope just caching external API responses:

#### workbox-cli-config.js
```
module.exports = {
  globDirectory: 'dist/',
  globPatterns: ['**/*.{js,png,svg,html,json}'],
  swDest: 'dist/service-worker.js',
  globIgnores: ['**/service-worker.js'],
  navigateFallback: '/index.html',
  runtimeCaching: [
    {
      urlPattern: /^https:\/\/node-hnapi.herokuapp.com\/.*/,
      handler: 'networkFirst'
    }
  ]
};
```

#### service-worker.js

```
importScripts('workbox-sw.prod.v1.1.0.js');

const fileManifest = [
    ...
];

const workboxSW = new self.WorkboxSW();
workboxSW.precache(fileManifest);
workboxSW.router.registerNavigationRoute("/index.html");workboxSW.router.registerRoute(/^https:\/\/node-hnapi.herokuapp.com\/.*/, workboxSW.strategies.networkFirst({}), 'GET');
```

I can't see anything inherently wrong with the output, although it only looks like the static glob assets are in the cache storage:

![image](https://user-images.githubusercontent.com/12476932/29037161-7bf8c208-7b70-11e7-879c-433fe44c519d.png)

Hopefully I'm not just missing anything - will clear the cache, try regenerating the service worker file and redeploy.

**Comment by jeffposnick** [comment]
Based on your screenshot, I inferred that you're talking about https://angular2-hn-experiment.firebaseapp.com

I visited your PWA and after the first visit, I see Workbox respond to your `https://node-hnapi.herokuapp.com` requests, and I see the runtime cache created:

![screen shot 2017-08-07 at 1 12 36 pm](https://user-images.githubusercontent.com/1749548/29037548-1b215254-7b72-11e7-95d6-3bf9e45014fd.png)

<img width="621" alt="screen shot 2017-08-07 at 1 13 32 pm" src="https://user-images.githubusercontent.com/1749548/29037584-3d2c6618-7b72-11e7-9b53-b59ce39e951f.png">

Did you just change something and redeploy?

Alternatively, the Cache Storage display in Chrome DevTools is unreliable when it comes to picking up newly created caches. You sometimes need to explicitly right-click and choose Refresh in order to match the reality of the current cache state.

**Comment by housseindjirdeh** [comment]
I just did a fresh redeploy but didn't change the config at all :O

Awesome thank you, you're right it works smoothly! I think that must have been stale cache data being displayed but interestingly enough not sure why it didn't seem to cache the responses anyway :thinking: 

Thank again, appreciate the help :raised_hands:
