### ISSUE TITLE
EventListener for addToHomeScreen click by user 

### ISSUE THREAD

**Issue by singhvijayy** [GoogleChrome/workbox#576]
I didn't know where to add this issue, forgive me if this is the wrong place.

[This link from google](https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/) does not state a way to know when a user uses browser settings option to add a website to home screen. It will be great if there is an event listener for this event. Thanks.

**Comment by whtrbit** [comment]
Hi singhvijayy,
it's all across `beforeinstallprompt` event:
```javascript
window.addEventListener('beforeinstallprompt', function (e) {
 // prompt launched
 
  e.userChoice.then(function (res) {
    if (res.outcome === 'dismissed') {
      // cancel
    } else {
      // added
    }
  });
});
```

**Comment by jeffposnick** [comment]
Hello @singhvijayy—this probably isn't the right place to ask.

(But in general, there's no way of detecting when a user visits the Chrome menu and manually selects "Add to Homescreen...")
