### ISSUE TITLE
workbox-webpack-plugin throwing useless-glob-pattern error

### ISSUE THREAD

**Issue by gondar00** [GoogleChrome/workbox#580]
**Library Affected**:
*workbox-build*

**Issue or Feature Request Description**:
*ISSUE.*

Hi, in workbox-webpack-plugin globPatterns: ['**\/*.{html,js,css}'], is throwing an error

```
throw new Error(errors['useless-glob-pattern'] + ^
Error: One of the glob patterns doesn't match any files. Please remove of fix the following: {
  "globDirectory": "./static/",
  "globPattern": "./**/*.{html,css}",
  "globIgnores": []
}
```
Stacktrace- /workbox-build/build/lib/utils/get-file-details.js:20:11

**Comment by prateekbh** [comment]
are you missing `s` there? `globPatterns` ?

**Comment by gondar00** [comment]
Yep. That was it. Thanks :+1:
