### ISSUE TITLE
Simple usage of workbox-cache-expiration plugin throws an error "You cannot register more than one plugin that implements cacheWillMatch"

### ISSUE THREAD

**Issue by whtrbit** [GoogleChrome/workbox#581]
Hi there,
I tried to use workbox-cache-expiration@1.0.0 package to set some expiration to my assets, however the following code throws an error:
`Uncaught multiple-cache-will-match-plugins: You cannot register more than one plugin that implements cacheWillMatch.`

Part of my code:
```javascript
const cacheExpirationPlugin = new workbox.cacheExpiration.CacheExpirationPlugin({
  maxEntries: 50,
  maxAgeSeconds: 24 * 60 * 60
});
workboxSW.router.registerRoute(
  /(.*\/)?.*\.(js|css|jpeg|jpg|gif|png)/,
  workboxSW.strategies.cacheFirst({
    cacheName: 'assets',
    cacheExpiration: {
      maxEntries: 50,
      maxAgeSeconds: 24 * 60 * 60
    },
    cacheableResponse: {
      statuses: [0, 200]
    },
    plugins: [
      cacheExpirationPlugin
    ]
  })
);
```

`console.log(cacheExpirationPlugin )` properly logs my object.

With regards,
G!

**Comment by jeffposnick** [comment]
I believe that if you just leave out

```js
plugins: [
  cacheExpirationPlugin
]
```

things will work as you intend.

We could probably do a better job of explaining this, but if you're using `workbox-sw`, then there's no need to also explicitly use `workbox-cache-expiration`. `workbox-sw` "bundles" in the `workbox-cache-expiration` functionality already, and you're already opting into it via

```js
cacheExpiration: {
  maxEntries: 50,
  maxAgeSeconds: 24 * 60 * 60
}
```

So by setting *both* of those, you end up with two plugins that implement the same logic, and the library isn't happy with that.

(We intend `workbox-cache-expiration` to be used by folks who already have a service worker implementation and want to opt-in to using *just* the cache expiration logic, as a lighter-weight alternative to using the entire `workbox-sw` library.)

**Comment by whtrbit** [comment]
Thx jeffposnick for quick reply and clarifying things.
