### ISSUE TITLE
Failed to get a cacheable response for 'http://localhost:3000/11.js': Quota exceeded.

### ISSUE THREAD

**Issue by sridharAJ** [GoogleChrome/workbox#582]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
`Uncaught (in promise) Error: A request failed the criteria to be cached. By default, only responses with 'response.ok = true' are cached. [Failed to get a cacheable response for 'http://localhost:3000/11.js': Quota exceeded.]`

**The below is my service worker file**: 
```
importScripts('workbox-sw.prod.v1.0.0.js');

const workboxSW = new WorkboxSW();

workboxSW.precache([
  {
    "url": "/1.js",
    "revision": "e2ed1a92f9707cee67ffa441e1b09b2e"
  },
  {
    "url": "/10.js",
    "revision": "c0dd458de6ab2d72c6014bdd03353223"
  },
  {
    "url": "/11.js",
    "revision": "6cf27c8feb0047843c4498ab0949c71c"
  },
  {
    "url": "/12.js",
    "revision": "8d27e08af44ba6c73e6a77a619e55df4"
  },
  {
    "url": "/13.js",
    "revision": "ab1f38614a64ad56d928b3abedadee1c"
  },
  {
    "url": "/14.js",
    "revision": "cbe6d48cf3594283fdaf7cb8a706e8e9"
  },
  {
    "url": "/15.js",
    "revision": "f7ae1826f65dd2a50b4097c8aa2bb743"
  },
  {
    "url": "/16.js",
    "revision": "51597670b6897df832f4cf28a7ccd357"
  },
  {
    "url": "/17.js",
    "revision": "1a526f264a2d0d305f88b0ad46b5c1af"
  },
  {
    "url": "/18.js",
    "revision": "aaddd645a9bde99f4a471f7c12a5a46b"
  },
  {
    "url": "/19.js",
    "revision": "f303834091451e2a72cd56d9482bc058"
  },
  {
    "url": "/2.js",
    "revision": "6d97ef5cb9e13dd6b32e8441585126cc"
  },
  {
    "url": "/20.js",
    "revision": "392a007bdf49987a96a58bf93ccfe8f7"
  },
  {
    "url": "/21.js",
    "revision": "d56a635e2e89654d6938cab17fb00d13"
  },
  {
    "url": "/22.js",
    "revision": "54f82b32c04363d9cd991fe8b1ab68ba"
  },
  {
    "url": "/23.js",
    "revision": "9f450fbf3e1da331be0e2fdfac303e01"
  },
  {
    "url": "/24.js",
    "revision": "0314eea267e2b487363afb1393eadeea"
  },
  {
    "url": "/25.js",
    "revision": "7108f25ff6ae4d66085ead4a2dc57a66"
  },
  {
    "url": "/26.d6d9daf544edde08ad85.hot-update.js",
    "revision": "1211f745ef84bd6b8a8b8f7db0ce5550"
  },
  {
    "url": "/3.js",
    "revision": "58422e8d786cf31fd3bc78fe69117413"
  },
  {
    "url": "/4.js",
    "revision": "1e38e8dd5cb81b62e62310dea6f13dfc"
  },
  {
    "url": "/5.js",
    "revision": "572a531a08adb05e21006f6a03b02ed8"
  },
  {
    "url": "/6.js",
    "revision": "c49e18d222949af2f66d6e846a72a1b8"
  },
  {
    "url": "/7.js",
    "revision": "32ce1202d91866210d8a611622fcc260"
  },
  {
    "url": "/8.js",
    "revision": "5f9f86942ae95d5260e1fe1546709e85"
  },
  {
    "url": "/9.js",
    "revision": "a827625c296293bb665bfd83de52754a"
  },
  {
    "url": "/lib.min.js",
    "revision": "81b332cb7debe03412c55a5ba7f267c6"
  },
  {
    "url": "/manifest.js",
    "revision": "f8431a47ba39985b818c8fc3d1f3d5e8"
  },
  {
    "url": "/theme.dev.css",
    "revision": "83c735ae31e82f79c4818c7bbadc11e1"
  },
  {
    "url": "/vendors.js",
    "revision": "995f1ba9f89dbc458ae592e98c18b258"
  }
]);
```

**Comment by jeffposnick** [comment]
That particular error comes from [here](https://github.com/GoogleChrome/workbox/blob/d39c11da553e94f887c02d4470ba64e2ef7e2252/packages/workbox-precaching/src/lib/controllers/base-cache-manager.js#L147), when there's an exception thrown in the network request or the cache addition for a given URL.

The only times I've previously seen a `Quota exceeded.` exception is when attempting to add files using the Cache Storage API when the computer/phone's storage was full. Can you double-check whether you've run out of space on your device, and see if you can reproduce it on another device?

**Comment by sridharAJ** [comment]
@jeffposnick It seems to be memory issue. I restarted my mac and then it stared working automatically. Now its not reproducible. But not sure about this problem.

**Comment by jeffposnick** [comment]
Okay, fair enough. The underlying error is coming from the browser, and I don't think there's anything in particular that the Workbox library is doing that would trigger it. (I.e., it's equally likely that just doing a `cache.add('<some_ur>')` from your own code would lead to the same error.)

If you find a way to reproduce it that suggests that it's actually a bug in Workbox, feel free to re-open.

**Comment by sridharAJ** [comment]
@jeffposnick This happened again. I was working continuously till now since last restart of my mac yesterday. Now suddenly started showing the same error. This time I just closed my chrome and re-open, its gone. 
Is this issue related to chrome?

**Comment by jeffposnick** [comment]
Based on everything you've described, it sounds like you're running out of space on your Mac, and Chrome is rejecting operations that would end up writing to disk (like precaching files).

You can confirm that you're running out of space by following one of [these guides](https://www.google.com/search?q=check+free+space+on+mac).

**Comment by sridharAJ** [comment]
@jeffposnick I just checked my disk space in mac. I have 16gb free space available.

**Comment by jeffposnick** [comment]
Okay, I'll dig in a bit more. When the precaching fails, is it always when processing the same file (`11.js`)? How large of a file is `11.js`?

**Comment by sridharAJ** [comment]
@jeffposnick 
Its happening with even single entry in the precache list and that file size is around 60kb. 
```
workboxSW.precache([
  {
    "url": "/1.js",
    "revision": "e2ed1a92f9707cee67ffa441e1b09b2e"
  }
]);
```

**Comment by jeffposnick** [comment]
There are only two places in the Chomium source that I can find that error thrown, and they're both in https://github.com/scheib/chromium/blob/0ceb99da2db1300e2392a827203d791e426c1b9b/content/browser/cache_storage/cache_storage_cache.cc#L463

Those both look like an error that would be thrown if Chrome that thinks that you've run out of quota for storage, and I am not sure that Workbox could do anything about that.

What happens if you open up the DevTools JavaScript Console manually, and enter 

```js
caches.open('test').then(cache => cache.add('/1.js'))
```

**Comment by sridharAJ** [comment]
@jeffposnick For now `caches.open('test').then(cache => cache.add('/1.js'))` this code is working fine. Because I am not getting Quota Exceeded error. Let me try the above code, when I get Quota Exceeded error and let you know.

**Comment by addyosmani** [comment]
Friendly ping for any updates on your explorations @sridharAJ

**Comment by sridharAJ** [comment]
@addyosmani @jeffposnick I faced that issue again. I have tried this code `caches.open('test').then(cache => cache.add('/app/udp/static/theme.dev.css'))`. Getting the same Quota exceeded error. 

*Chrome Console:*
`caches.open('test').then(cache => cache.add('/app/udp/static/theme.dev.css'))`
`Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: DOMException: Quota exceeded.code: 22message: "Quota exceeded."name: "QuotaExceededError"__proto__: DOMException
:3000/udp/home?#:1 Uncaught (in promise) DOMException: Quota exceeded.`

**Comment by jeffposnick** [comment]
Thanks; that confirms that you're in a state in which Chrome thinks that you've used up the amount of storage it's willing to allocate to your origin.

There's not much that Workbox could do to prevent that from happening, as it's just passing along the underlying error from Chrome. The current error message also seems fairly high-quality in that it accurately logs what's happening.

Maybe there's an opening without Workbox for providing some insight as to *what's* consuming your storage quota, but the counterpoint to that is that the browsers DevTools should also be enhanced to tell you that.

**Comment by sridharAJ** [comment]
@jeffposnick I want to understand why is this happening event after clean the browser cache. Is there any storage limit for pre-caching? This looks so weird. Is this bug in chrome? where else can I report this issue. How it started working automatically after close and re-open the chrome.

**Comment by jeffposnick** [comment]
Filing a bug at https://bugs.chromium.org/p/chromium/issues/entry with the Component field set to "Blink>Storage>Quota" would be the best way to escalate if you believe that Chrome is inaccurately reporting that the storage for your origin is full when in fact it's not. If nothing else, the folks who respond to that report are more likely to know what questions to ask to debug things further.

As it stands, since an attempt to write to the cache outside of the context of Workbox was also failing, it does not appear to be directly related to an issue with Workbox.

**Comment by sridharAJ** [comment]
@jeffposnick
 I created the bug in chromium. [https://bugs.chromium.org/p/chromium/issues/detail?id=732064](url)

**Comment by shnigi** [comment]
Not sure if this is related but I got something similar on my macbook:

```
Uncaught (in promise) WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"http://localhost:8080/css/core.css","error":{}}'
    at http://localhost:8080/workbox-sw.prod.v2.1.0.js:160:1358
    at Generator.throw (<anonymous>)
    at step (http://localhost:8080/workbox-sw.prod.v2.1.0.js:83:30)
    at http://localhost:8080/workbox-sw.prod.v2.1.0.js:96:13
    at <anonymous>
```
