### ISSUE TITLE
Use workboxSW.router.registerRoute with Gulp-Task?

### ISSUE THREAD

**Issue by dertuerke** [GoogleChrome/workbox#583]
**Library Affected**:
workbox-gulp

**Question**:
How i can use this with the Gulp-Task?
```javascript
workboxSW.router.registerRoute(
  'https://httpbin.org/image/(.*)',
  workboxSW.strategies.cacheFirst({
    cacheName: 'images',
    cacheExpiration: {
      maxEntries: 2,
      maxAgeSeconds: 7 * 24 * 60 * 60,
    },
    cacheableResponse: {statuses: [0, 200]},
  })
);
```

**Comment by OlButTerAintDEAD** [comment]
Cha the futhi ngo Put Three and yogu
Neave???e;6ìßì5ébet6t8mèìgo.i,ide;kwayo???of(

**Comment by jeffposnick** [comment]
If you'd like to precache resources, then using `workbox-build` as part of your existing build process (i.e. using `gulp`) is recommended.

`workbox-build` has a few different methods that it exposes, as explained [in the docs](https://workboxjs.org/reference-docs/latest/module-workbox-build.html). If you'd like to precache and then add in additional logic, like you're asking about in your post, then the most flexible way to do that is to use the `workbox-build.injectManifest()` method, and pass in as your `swSrc` file a script that includes a "placeholder" for the precaching information:

```js
const workboxSW = new WorkboxSW();
// This is the placeholder; the [] will be replaced with
// the actual list of files to precache during the build.
workboxSW.precache([]);

// At this point, you can add in any additional runtime caching logic that you'd like:
workboxSW.router.registerRoute(
  'https://httpbin.org/image/(.*)',
  workboxSW.strategies.cacheFirst(/* ... */)
);
```

You can see an example of this in action in our iFixit example's [`gulp` task](https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/gulpfile.js#L113) and [source service worker file](https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/src/static/service-worker.js).

CC: @jpmedley as a heads-up that this is something folks are asking about and could potentially be clarified in the docs.
