### ISSUE TITLE
importScripts in workbox-build?

### ISSUE THREAD

**Issue by nasearle** [GoogleChrome/workbox#584]
**Library Affected**:
workbox-build

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
@gauntface Is there a way to import scripts with workbox-build if I want to include a JS file containing routes, for example? With sw-precache I could do something like the following to include some toolbox routes from another file in the generated service worker:

```
gulp.task('service-worker', function(callback) {
  swPrecache.write('service-worker.js', {
    staticFileGlobs: [
      'index.html',
      'css/main.css',
    ],
    importScripts: [
      'node_modules/sw-toolbox/sw-toolbox.js',
      'js/toolbox-script.js'
    ]
  }, callback);
});
```

Couldn't find an equivalent in the [workbox reference](https://workboxjs.org/). I tried just using importScripts in generateSW but it was ignored.

```
gulp.task('bundle-sw', () => {
  return wbBuild.generateSW({
    globDirectory: './',
    swDest: './sw.js',
    staticFileGlobs: [
      'index.html',
      'css/main.css'
    ],
    importScripts: ['routes.js']
  })
  .then(() => {
    console.log('Service worker generated.');
  })
  .catch((err) => {
    console.log('[ERROR] This happened: ' + err);
  });
});
```

**Comment by jeffposnick** [comment]
For that use case, [`injectManifest()`](https://workboxjs.org/reference-docs/latest/module-workbox-build.html#.injectManifest) is a better choice than using `generateSW()`.

`injectManifest()` lets you supply a full service worker file, including the routes and any other additional logic, as its `swSrc` input, and checks for a placeholder call to `precache([])` within the file. That `precache([])` gets replaced with the actual manifest of URLs to precache, and then it's written out to `swDest`.

You can see an example of this in action in our iFixit example's [`gulp` task](https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/gulpfile.js#L113) and [source service worker file](https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/gulpfile.js#L113).

CC: @jpmedley as another heads up (similar to #583). This is an important use case and it appears like the getting started material isn't leading developers in the right direction.

**Comment by nasearle** [comment]
Ok makes sense. Thank you!
