### ISSUE TITLE
Workbox codelab 👩‍🔬

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#593]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

**Task**

Write a codelab for Workbox that takes users through the flow of setting it up for precaching and runtime caching. Perhaps something not using Web Components as we [already](https://codelabs.developers.google.com/codelabs/prpl-ce-firebase/index.html?index=..%2F..%2Findex#3) have a codelab using Web Components and Workbox by Keanu that he'll update separately. 

**Ideas*

* Update the [existing](https://codelabs.developers.google.com/codelabs/sw-precache/index.html?index=..%2F..%2Findex#0) sw-precache codelab
* Modify an existing codelab to use Workbox like this [migration](https://codelabs.developers.google.com/codelabs/migrate-to-progressive-web-apps/index.html?index=..%2F..%2Findex) one
* Create a new codelab that walks through using Workbox on a new app

Perhaps my only feedback on the current sw-precache codelab is that because its using airhorner its pretty simplistic. That might be fine, but it would also be nice to highlight an app that's a little more dynamic. I also think the current codelab around migrating to a PWA is pretty great as is because it's a pretty straight-forward intro to raw Service Workers and it can be valuable to show this off. 

How would you feel about a codelab around a new/different app, @samthor? 🙃

**Comment by gauntface** [comment]
Done via ILT.
