### ISSUE TITLE
Background sync is not rescheduled if replaying fails

### ISSUE THREAD

**Issue by anilanar** [GoogleChrome/workbox#597]
**Library Affected**:
*workbox-background-sync*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
*Background sync is not rescheduled if replaying fails.*

Sync is only triggered when a new request is pushed to the queue. However, one of the use cases (the most important one IMO) of background sync is deferring requests to when network state changes from offline to online. For that purpose, browsers reschedule syncs that have failed with exponential backoff. As far as I know, the condition for a failing sync event is that it must receive a rejected promise from `event.waitUntil`. However `workbox-background-sync` catches all failed promises.

**Comment by prateekbh** [comment]
Are you observing no replay at all in case of network change?
Also is this in case of replay failure only or otherwise as well?

About catching failed promises, can you post your code on how you enqueue your requests to `workbox-background-sync`?

**Comment by anilanar** [comment]
I'm observing replay just fine, when network conditions are perfect. If browser thinks it's online, it immediately triggers a sync event. If it thinks it's offline, it defers sync event until it becomes online. However, with imperfect network conditions, a request that is made by `workbox-background-sync` may fail and when it does, replay never happens unless another request is pushed to the queue  (which registers a sync).

The code is quite complex to include here but the idea is:
1) I listen for `fetch` events for a certain route.
2) I'm debouncing requests. I cache their payload in memory. I flush the in-memory cache every 2 seconds (using `setTimeout/setInterval`).
3) During flush, I merge all payloads into 1 and create a `Request` object.
4) The final part of flushing is as follows:

```
const flush = request => {
        const requestClone = request.clone();
        // make the request normally, if it fails, push to background-sync-queue
        // where `queue` is an instance of `background-sync-queue`. 
        return fetch(request, {
            credentials: 'include',
        }).catch(() => {
            queue.pushIntoQueue({request: requestClone});
        });
};
```

**Comment by anilanar** [comment]
When I'm referring to "rescheduling a failed replay", please see the following part from https://developers.google.com/web/updates/2015/12/background-sync

> Then listen for the event in /sw.js:

```self.addEventListener('sync', function(event) {
  if (event.tag == 'myFirstSync') {
    event.waitUntil(doSomeStuff());
  }
});
```

> And that's it! In the above, doSomeStuff() should return a promise indicating the success/failure of whatever it’s trying to do. If it fulfills, the sync is complete. If it fails, another sync will be scheduled to retry. Retry syncs also wait for connectivity, and employ an exponential back-off.

So apparently `workbox-background-sync` should pass a rejected promise to `waitUntil` if replay failed. `RequestManager` calls `waitUntil(this.replayRequests())` and `replayRequests` catches all failure so the promise always resolves.

**Comment by prateekbh** [comment]
thanks for the input, will take a look.
Just a quick thing, can you add a `sync` handler of your own and see if under the above said conditions your `sync` is fired but the `workbox-background-sync` is not?
