### ISSUE TITLE
Preact-cli comparison SwPrecache vs Workbox

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/workbox#599]
**Library Affected**:
none

**Discussion**:
Please take this more like a discussion I have deployed a bare minimum project out of `preact-cli` and deployed it with SwPrecache and Workbox. Below are the links

Site with Workbox: https://www.webpagetest.org/result/170605_0T_e8021fc6664f38f5e73314b4e83fbdac/

Site with sw-precache:
https://www.webpagetest.org/result/170605_R6_8a8ea7f8d4619615ae4d5bf83f9577c3/

**Comment by gauntface** [comment]
Not really sure what to take away from this, they seem similar enough that I'm not too concerned

**Comment by prateekbh** [comment]
yeah just wanted you guys to take a look if there is anything which seems like a concern
