### ISSUE TITLE
Make Queue#replayRequests async-safe

### ISSUE THREAD

**Issue by anilanar** [GoogleChrome/workbox#600]
**Library Affected**:
*workbox-background-sync*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
*Make `Queue#replayRequests` async-safe.*

Assume the following code:

```
const queue = new Queue();

const enqueueRequests(requests) {
    return Promise.all(requests.map(r => queue.pushIntoQueue(r)));
}

setInterval(() => queue.replayRequests(), 5000);
```

If the first call to `replayRequests` has some pending requests until the second call, the second call will refetch those pending requests. That behaviour duplicates some requests.

Although that's not a problem with sync events using the same tag name, making `Queue` or `RequestManager` async-safe should not be responsibility of the user-land code. 

For example, a user may trigger `replayRequests` from different sync events with different tags:

```
// service worker
const queue = new Queue();

self.addEventListener('sync', event => {
  if (event.tag === 'replay' || event.tag === 'workbox') {
    event.waitUntil(queue.replayRequests());
  }
}

// main thread code
navigator.serviceWorker.ready.then(registration => {
  replayButton.addEventListener('click', () => {
    registration.sync.register('replay');
  });
  workboxButton.addEventListener('click', () => {
    registration.sync.register('workbox');
  });
});
```

If user clicks both buttons relatively quickly (before `replayRequests` succeed), it will cause duplicate requests.

If you agree with me, I can make a PR.

**Comment by gauntface** [comment]
@philipwalton do you have a feel for whether this is going to be a problem for you either with or without this behavior?

**Comment by philipwalton** [comment]
I *think* this will not be a problem for me because I'm using a unique tag name, but I agree this is a problem we should resolve in general.

**Comment by philipwalton** [comment]
This should be fixed in v3 as `Queue` instances no longer keep requests in memory; instead, IDB is the single source of truth and when a request is about to be replayed, it is removed from IDB immediately before doing so.

If two calls to `replayRequests()` are made at the same time, it's possible they'll alternate sending the requests, but no requests should ever be sent twice.
