### ISSUE TITLE
workbox-webpack-plugin doesn't work in node v4

### ISSUE THREAD

**Issue by anilanar** [GoogleChrome/workbox#603]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*node v4.7.0*

**Issue or Feature Request Description**:
*Due to missing `use script` in webpack plugin, it fails in node v4.*

```
<FULL_PATH>/node_modules/workbox-webpack-plugin/build/index.js:32
class WorkboxBuildWebpackPlugin {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.
```

**Comment by prateekbh** [comment]
can you check if just adding `use strict` fixes it?

**Comment by anilanar** [comment]
Adding `use strict` to `workbox-webpack-plugin` and to bunch of files in `workbox-build` fixed it.

**Comment by anilanar** [comment]
According to http://node.green/ ES6 built-in APIs are almost complete in node4. Why don't we add `babel-preset-env` targeting node4 to the build process?

**Comment by prateekbh** [comment]
building it to an es5 version shouldn't be a problem

**Comment by gauntface** [comment]
workbox-build and workbox-cli were fixed for node 4 in this PR: https://github.com/GoogleChrome/workbox/pull/670

@prateekbh or @anilanar could you raise a PR for the webpack plugin?

**Comment by gauntface** [comment]
I need to find a way to run some of the tests in various versions of node on Travis without running ALL of our tests.

**Comment by jeffposnick** [comment]
We're currently using `babel-preset-env` to target Node 4.0 as part of the [build process](https://github.com/GoogleChrome/workbox/blob/0d5e650147e916f8e21b43ed2e888b41391fe62a/gulp-tasks/utils/build-node-package.js#L25) for all our Node modules.

I'm personally happy to either close this or put it on the back burner by virtue of that.

**Comment by anilanar** [comment]
Can close.
