### ISSUE TITLE
Support for precached assets hosted on a CDN

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#604]
**Library Affected**:
`workbox-build`, `workbox-webpack-plugin`

A use case that comes up every now and then is deployments in which HTML pages (and the SW script) are hosted on a first-party server, but all assets are hosted on a third-party CDN.

We currently sort-of support this by using `workbox-build`'s [`modifyUrlPrefix`](https://github.com/GoogleChrome/workbox/blob/e9d1913fe31bb089d41c4bb974a77dc7aee9e6d0/packages/workbox-build/src/lib/generate-file-manifest.js#L31) option to add in the CDN's origin to the start of asset URLs when writing out the precache manifest, but it's difficult to do that without also adding in the CDN origin to the start of any HTML URLs.

A possible alternative would be to take in a `publicPath` option. If passed in, it would be prepending to any URLs in the precache manifest that we identify as being asset URLs. Identifying non-asset URLs would require a bit of guesswork, so the heuristic might be:
- Does the URL end in `.html`?
- Is the URL a key in `templatedUrls`?
- Is the URL passed in as the `navigateFallback` option?

We can automate things for the Webpack wrapper on top of `workbox-build` by checking to see if Webpack's [`publicPath` is set](https://webpack.js.org/guides/public-path/), and if so, use that value as the implied `publicPath` for `workbox-build`.

One complication is that this should only work if the CDN supports CORS, because precaching opaque responses and serving them cache-first isn't a good practice.

**Comment by gauntface** [comment]
We need to stop bolting on options.

A better solution for this, and probably untold other random scenarios is to supply a callback that gives developers a way to get the url and revision and manipulate before it's finally stamped out to the service worker.

**Comment by jeffposnick** [comment]
Sure—take a look at the proposal in #626, and if you're on board with that, then it would supersede this feature request.

**Comment by gauntface** [comment]
Can we close this in favor of #626?
