### ISSUE TITLE
Docs to differentiate when to generate a sw vs use injectManifest

### ISSUE THREAD

**Issue by johnpapa** [GoogleChrome/workbox#605]
**Library Affected**:
workbox-sw & workbox-build

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:
**nutshell:** was hoping `importScripts would exist as a setting to `generateSW`

I am generating a `sw` to take advantage of the pre cache and runtime caching features, instead of manually coding those. The `sw.js` generates well.

I also have code for background sync and push notifications in a separate file , `sync-and-push.js`. 

I'd like to use `importScripts` at  the end of the generated file to have it run `sync-and-push.js`.  But that feature appears not to exist in `workboxBuild.generateSW(input)`. 

How can we achieve this?

PS - I have a working scenario where I inject the manifest into an existing sw, and this works well. But in this scenario I have to register run time cache routes in code. The above scenario with `generateSW` handles the runtime routes in config, which is just another way of doing it.

cc @jeffposnick

**Comment by gauntface** [comment]
Personally I wouldn't want to add this feature.

If a developer doesn't revision their importScripts, there is no guarantee it's going to be updated when the file changes (Yes this behaviour will change in the future, but I'm not sure of status in Chrome or other browsers).

Instead the inject manifest is the way that I'd like to see developer go down.

**Comment by johnpapa** [comment]
I've been torn on it ... I think I agree with you @gauntface . In my head I am thinking that `generateSW` is more for folks who dont want to extend the sw. If they do, then they should use one of the other techniques. Maybe we just need more docs to explain the when and why.

**Comment by gauntface** [comment]
Assigning to myself and will add a section to the workbox-cli Module docs for when to use one vs the other.

**Comment by gauntface** [comment]
Should be fixed by: https://github.com/google/WebFundamentals/pull/5400
