### ISSUE TITLE
Update to npm 5?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#606]
**Library Affected**:
all

`npm` 5 brings with it lockfiles, which AFAIK are similar to the lockfiles that `yarn` has been generating.

The [recommendation](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/#libraries-vs-applications) from the `yarn` team is that lockfiles should always be checked in to GitHub, even for the "library" use case that our project falls under.

Presumably that also applies to `npm` 5 lockfiles, so once we start using that, we should check in the lockfile.

The other issue that's related to `npm` is whether it would play nicely with our `lerna` setup. The only issue I currently see in the `lerna` tracker that might be relevant is https://github.com/lerna/lerna/issues/856, but I *think* we're not using hoisting, so perhaps that's fine.

I'll update to `npm` 5 on a development machine and test things out.

**Comment by gauntface** [comment]
@jeffposnick I'm 100% happy to commit a lock file and have been using NPM5 and Node 8 locally so see now problem with us just moving to support this.

**Comment by addyosmani** [comment]
I'm generally in favor of us committing a lock file. Be aware that there are some issues around the current implementation that may or may not be addressed in npm 5.1:

https://github.com/npm/npm/issues/17091

James Kyle also had some thoughts on the implementation (which is not to say we shouldn't use them, just interesting to be aware):

https://twitter.com/thejameskyle/status/879577772313632768
