### ISSUE TITLE
Expose & log the precache bundle size

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#607]
**Library Affected**:
workbox-build

The [code that generates](https://github.com/GoogleChrome/workbox/blob/ab8281aca75d7ee97eb923ca9542308b038b7ffb/packages/workbox-build/src/lib/get-file-manifest-entries.js#L148) the precache manifest's list of URLs and hashes does not return information about the total size of the precache payload. If we start returning that information, we could then display it as the output of our build tools.

`sw-precache` currently logs something like `Total precache size is about 90 kB for 2 resources.` and you could imagine `workbox-cli` logging something similar by defualt.

Folks who are using `workbox-build` directly could log the total payload size using whatever mechanism they see fit, as long as we exposed it.

**Comment by gauntface** [comment]
What's the use case for this?

**Comment by jeffposnick** [comment]
It can serve as a sanity check—if the output is `Total precache size is about 90 mB for 2000 resources.` then a developer might realize that they're using a `globPattern` that includes many more files (or larger files) then they intended.

A more speculative use case would be if someone who's using `workbox-build` directly keeps track of the precache payload size over time, and raises a red flag if it increases more than X% from the previous build. (Similar to our proposed tracking of bundle sizes over time.)

**Comment by gauntface** [comment]
@jeffposnick did you add this in to the current v3 work? I faintly recall seeing size somewhere, but could be dreaming it up.

**Comment by jeffposnick** [comment]
Yup! It's [returned](https://github.com/GoogleChrome/workbox/blob/0d5e650147e916f8e21b43ed2e888b41391fe62a/packages/workbox-build/src/entry-points/generate-sw.js#L89) by the relevant `workbox-build` methods, and the `workbox-cli` will [log it](https://github.com/GoogleChrome/workbox/blob/2f1a520f9bf57597bcb25f57bae380fe2111cad6/packages/workbox-cli/src/app.js#L51) after the build completes.

(Thanks for scrubbing the issue tracker!)
