### ISSUE TITLE
Default NavigationRoute's blacklist to match common server-controlled URLs

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#610]
**Library Affected**:
workbox-routing

There's precedent in both Firebase Hosting and App Engine to use URLs whose pathname starts with `/_` for server-controlled pages, like admin tools or OAuth 2 flows.

`NavigationRoute` supports a blacklist of URLs that it shouldn't attempt to respond to, which we current default to [an empty array](https://github.com/GoogleChrome/workbox/blob/f60c13022bb33bef5e9d36fce28897bb8708b45c/packages/workbox-routing/src/lib/navigation-route.js#L75).

We've heard from enough developers who bump up against a bad combination of navigation fallbacks and these Firebase/App Engine URLs that I think defaulting `blacklist` to `[new RegExp('^/_')]` would make sense.

It seems unlikely to me that a developer would use URLs beginning with `/_` as part of a legitimate app-specific URL scheme, and any developer who did need to handle those URLs via `NavigationRoute` could explicitly set the `blacklist` to `[]`.

The main open question that I have is whether `/_` is common across other hosting platforms, and whether there are other examples of prefixes that are used elsewhere which should also be blacklisted by default.

**Comment by gauntface** [comment]
Personally I don't think this should be baked into our library.

Happy to add docs, recipes, logs but baking this in by default feels somewhat iffy to me.
