### ISSUE TITLE
No visible indication that a service worker is in control

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#618]
> If you don't know where to look, because you don't know anything about service workers, then it's very unlikely that you'd be able to understand the implications of those 

Logging here could help, we can get a list of clients and call out which ones are controlled and which one's aren't.

Only caveat is when to log this, when the service worker starts, on a navigation request, through an admin page the dev SW provides? (i.e. /__workbox/admin => SW intercepts and shows a page with some usefule info?)

**Comment by addyosmani** [comment]
>Logging here could help, we can get a list of clients and call out which ones are controlled and which one's aren't.

👍 

> when the service worker starts, on a navigation request

I'm personally down with either of these options (leaning towards SW starts)

> through an admin page the dev SW provides? (i.e. /__workbox/admin => SW intercepts and shows a page with some usefule info?)

Let's chat about the admin page idea a little more. I think you suggested it in #619

**Comment by gauntface** [comment]
Little to no traction on this so going to close for now.
