### ISSUE TITLE
Workbox Admin Page and/or Workbox in page GUI

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#619]
Just had this idea across a few issues and wanted to just mention this:

1. Have a page that could be current state of the world from workbox's P.O.V <Developers Origin>/__workbox/admin. This would only be available in dev builds.
1. Have an option to inject a script into the developers page that would display a GUI to callout Workbox service worker is controller the page and perhaps offer additional options.

**Comment by addyosmani** [comment]
Were you thinking this would be a togglable overlay (a la React/Vue) or a dedicated admin page (BrowserSync)?

**Comment by gauntface** [comment]
I was thinking move the browsersync seperate page. Only reason for seperate page is that way we can intercept a specific URL and do whatever we want.

Adding code and markup for an overlay feels somewhat risky / error prone.

**Comment by gauntface** [comment]
Little to no traction on this so going to close.
