### ISSUE TITLE
Support custom injectionPointRegex

### ISSUE THREAD

**Issue by mikefowler** [GoogleChrome/workbox#623]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
n/a

**Issue or Feature Request Description**:
I think we could make `injectManifest` far more powerful if we allow customization of the RegExp that is used to determine the injection point. As it stands, if I want to create a custom injection point, I need to create a second file (one that _cannot_ contain a call to `workboxSw.precache`) that I use as my injection template, and then use `importScripts` to include the main service worker code where I initialize Workbox.

If I could customize the RegExp defined [here](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/inject-manifest.js#L66), I could do the following, all in the same template file:

```js
// generateServiceWorker.js
swBuild.injectManifest({
  globDirectory: './build/',
  globPatterns: ['**\/*.{html,js,css}'],
  swSrc: './src/sw.js',
  swDest: './build/sw.js',
  injectionPointRegex: /^(const files = )\s*\[\s*\]\s*(;)$/gm,
})
```

```js
// src/sw.js
let workbox;

const files = [];
const filesToPrecache = doSomeLogicWith(files);
const filesForCustomCache = someOtherLogicWith(files);

// Create an instance of Workbox
workbox = new WorkboxSW();

// Precache certain files with Workbox
workbox.precache(filesToPrecache);

// Set up some other custom precaching/runtime caching logic with `filesForCustomCache`
```

**Comment by jeffposnick** [comment]
We might want to do this anyway (it's a question of balancing flexibility vs. adding in too many configuration options), but how do you feel about the proposal in https://github.com/GoogleChrome/workbox/issues/626, @mikefowler? If we had built-in functionality allowing your to map/filter URLs, would it take care of your use case?

**Comment by mikefowler** [comment]
@jeffposnick I don't think this would allow for the use-case I had in mind, which is that:

- `workbox-webpack-plugin` returns a list of files, some of which are assets (JS, CSS, etc), and one of which is an app shell documented, generated via `templatedUrls`. 
- The assets are language-agnostic, but the app shell document is language-_specific_. 
- I need to be able to store the language-specific shell in a separately, explicitly named cache so that I can open the cache by name and update the app shell resource _from the client_ (when the user changes languages, for instance, we need to invalidate and update the `/offline_shell` resource).

Does that make sense? It's also entirely possible that there's a way to do this as-is, in which case I'd gladly welcome your suggestions!

**Comment by gauntface** [comment]
Minor note - you can just get the array of url's and revisions here: https://workboxjs.org/reference-docs/latest/module-workbox-build.html#.getFileManifestEntries

Does getFileManifestEntries() not provide you with flexibility to do whatever you want?

**Comment by mikefowler** [comment]
@gauntface, for sure, that would allow (though require) us to implement our own Webpack plugin. I know that, right now, `workbox-webpack-plugin` calls `swBuild.injectManifest` behind the scenes, which is why I led my post with that, but I do think that it would be nice to have something akin to the functionality as described above.

**Comment by gauntface** [comment]
Ah, didn't realise this was a webpack related to Q, my bad

**Comment by gauntface** [comment]
This has been added in #1075
