### ISSUE TITLE
How to precache Firebase? 

### ISSUE THREAD

**Issue by amalshehu** [GoogleChrome/workbox#624]
**Library Affected**:
workbox-sw, workbox-build, etc.

**Browser & Platform**:
 Google Chrome v51.0.1 for Android, or "all browsers"

**Issue or Feature Request Description**:
How to precache Firebase? 

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by jeffposnick** [comment]
What do you mean by "Firebase" in this context? Are you asking about the JavaScript library files, data from a Firebase datastore, or something else?

**Comment by amalshehu** [comment]
Thanks for your response. I mean the data from firebase data store.

**Comment by jeffposnick** [comment]
As of right now, the best approach would be to interact with Firebase via its [REST API](https://firebase.google.com/docs/reference/rest/database/), and set up a [runtime caching policy](https://workboxjs.org/reference-docs/latest/module-workbox-sw.Router.html#main) to cache the data.

The Firebase Realtime API uses websockets to communicate with the server, and websockets can't be intercepted by service workers.

Offline support for the Realtime API has been attempted via helper libraries that run outside the service worker; the most robust that I'm aware of uses https://github.com/PolymerElements/app-storage to mirror the Firebase data in IndexedDB.
