### ISSUE TITLE
urlMapping option in workbox-build

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#626]
**Library Affected**:
`workbox-build`

An idea that's come up a few times (see https://github.com/GoogleChrome/workbox/issues/604) is to provide an additional configuration option to `workbox-build` that would allow developers to manipulate each URL prior to writing it out to the final manifest.

It would give developers to more fine-grained control over the final URLs than what `modifyUrlPrefix` currently supports, and `modifyUrlPrefix` could probably be rewritten to use this approach under the hood.

The (hypothetically named) `urlMapping` would take a callback function that's passed a single parameter, `url`, and if it returns a string, that string would be used instead of `url` in the manifest entry. If it returned a false-y value, we could omit the manifest entry entirely, giving developers more control over excluding manifest entries without having to deal with glob patterns.

We could then implement CDN asset paths via something like:

```js
workboxBuild.generateSW({
  // Other options...
  urlMapping: (url) => {
    // url is an asset path, relative to the SW file.
    if (url === 'something-to-skip.js') {
      return null;
    }
    return url.endsWith('.html') ? url : CDN_PREFIX + url;
  },
});
```

**Comment by gauntface** [comment]
Why not include the revision as well? This would allow developers the ability to prefix the revision if desired. Use case here would be you want to force everyone to re-download files. This feels like a last resort for most developers and I'd rather just give as much flexibility as possible with this API.

```javascript
workboxBuild.generateSW({
  .....
  urlMapping: ({url, revision}) => {
    // url is an asset path, relative to the SW file.
    if (url === 'something-to-skip.js') {
      return null;
    }
    return {
        url: url.endsWith('.html') ? url : CDN_PREFIX + url,
        revision: 'v1-' + revision,
    };
  },
});
```

Not a fan of `urlMapping` would prefer something like `revisionDetailsCb`.

FYI I imagine a much more common use case of the above code would would be:

```javascript
workboxBuild.generateSW({
  .....
  revisionDetailsCb: (revisionDetails) => {
    // url is an asset path, relative to the SW file.
    if (revisionDetails.url === 'something-to-skip.js') {
      return null;
    }
    
    const origUrl = revisionDetails.url;
    revisionDetails.url = origUrl.endsWith('.html') ? origUrl : CDN_PREFIX + origUrl;
    return revisionDetails;
  },
});
```

**Comment by gauntface** [comment]
Me and Jeff on hangouts agreed to `revisionMapping`.
