### ISSUE TITLE
Multi-language-strategy

### ISSUE THREAD

**Issue by koljakutschera** [GoogleChrome/workbox#628]
Hi, 

just a simple Question. Is there any multi-language-strategy for service-worker precaching or just some best-practice? Got a static multi-language and multi-page site with the following url-pattern:

http://some.site/en/...
http://some.site/de/...

Content is build via gulp-task(static). Would be nice to store just one language-version in sw but not a must. I'm thankful for every hint.

Thank you very much,
K.K

**Comment by gauntface** [comment]
Sadly this is a little beyond the scope of an issue (although PRs for documentation on this topic would be welcomed)

My gut says you'd probably want to use Workbox-build to generate some of the assets you'd precache and then precache additional elements based on the language. The main question  in my mind is how you'd revision and select those language pages and assets.

You could have all files be revisooned and filter on the current user language.
