### ISSUE TITLE
Allow NavigationRoute whitelisting/blacklisting to work with search parameters

### ISSUE THREAD

**Issue by mikefowler** [GoogleChrome/workbox#631]
**Library Affected**:
*workbox-routing*

**Browser & Platform**:
n/a

**Issue or Feature Request Description**:
It would be nice if `NavigationRoute`'s `whitelist` and `blacklist` options supported matching on `url.pathname + url.search` instead of just on `url.pathname`. Performing server-based redirects based on a query parameter seems _somewhat_ common, and such a redirect breaks if we can't specify that an app shell should _not_ be served for URLs containing that query parameter.

Take the following route that we've implemented:

```js
workboxSW.router.registerNavigationRoute(APP_SHELL_ROUTE, {
  whitelist: [
    /^\/$/,
  ],
});
```

On the page, a user can change languages. The language picker redirects the browser to the current URL but with `locale=de` appended to the search query. Normally the server would intercept these requests and 302 redirect to `de.domain.com`. With a service worker installed and the above `NavigationRoute` registered, this redirect breaks; the user is served the app shell as usual and no redirect occurs.

It makes sense to me that we should be able to do the following:

```js
workboxSW.router.registerNavigationRoute(APP_SHELL_ROUTE, {
  whitelist: [
    /^\/$/,
  ],
  blacklist: [
    /[&?]locale=/,
  ],
});
```

Thoughts?

**Comment by jeffposnick** [comment]
Sounds reasonable to me.
