### ISSUE TITLE
allow setting ignoreDirectories in workbox-cli first run

### ISSUE THREAD

**Issue by psimyn** [GoogleChrome/workbox#635]
Or maybe multiple globDirectories

**Library Affected**:
workbox-cli

**Issue or Feature Request Description**:

My usual setup for gh-pages apps is:

```
src/
dist/
node_modules/
index.html
favicon.png
```

And I want end up with the following config:

```
module.exports = {
  'globDirectory': './',
  'globPatterns': [
    '**/*.{js,svg,png,html}'
  ],
  'swDest': 'sw.js',
  'globIgnores': [
    'workbox-cli-config.js',
    'node_modules/**/*',
    'src/**/*'
  ]
}
```

**Comment by gauntface** [comment]
So is the problem that the globdirectory isn't dist?

Sorry I don't know what the end result is in terms of files being cached.

**Comment by gauntface** [comment]
@psimyn did the CLI not allow you to select `dist` as the main directory?

**Comment by psimyn** [comment]
Setting dist works, but I also wanted to add index.html (in parent folder). I instead use dist and have html files copied there by build, so can close this
