### ISSUE TITLE
registerRoutes don't accept subclass of Route

### ISSUE THREAD

**Issue by jmtt89** [GoogleChrome/workbox#636]
**Library Affected**:
*workbox-sw, workbox-routing*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
registerRoutes don't accept subclass of Route

```js
import WorkboxSW from 'workbox-sw';
import {RegExpRoute, ExpressRoute} from 'workbox-routing';
import {QueuePlugin} from 'workbox-background-sync';

const workboxSW = new WorkboxSW();

workboxSW.precache([...]);

//backgroundSync
let bgQueue = new QueuePlugin();

// Network Stategies
const networkOnly = workboxSW.strategies.networkOnly({
  plugins: [bgQueue]
});
const cacheFirst = workboxSW.strategies.cacheFirst();

//RuntimeCache
workboxSW.router.registerRoutes({
  routes: [
    new RegExpRoute({
      regExp: new RegExp('^https://fonts.googleapis.com/*'),
      handler: cacheFirst
    }),
    new RegExpRoute({
      regExp: new RegExp('^https://code.jquery.com/*'),
      handler: cacheFirst
    }),
    //Device Endpoints
    new ExpressRoute({
      path: '/my/custom/route',
      handler: networkOnly
    })
  ]
});
```

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

** Console Output **
```shell
Uncaught assertion-failed: The 'routes' parameter should be an array containing one or more 'Route' instances.
```

** Function throw error **
```js
function isArrayOfClass(a, b) {
  const c = Object.keys(a).pop(), d = `The '${c}' parameter should be an array containing one or more '${b.name}' instances.`;
  Array.isArray(a[c]) || throwError(d); // Here all Good
  for (let e of a[c])
    e instanceof b || throwError(d); //This throw error
}
```

```shell
e ->
        RegExpRoute$1 {handler: CacheFirst, method: "GET", match: function}
          handler: CacheFirst
          match:({url:e})=> {…}
          method: "GET"
          __proto__:Route$1
```

```shell
b
       class Route{constructor({match:a,handler:b,method:c}={})
       {this.handler=normalizeHandler(b),assert.isType({match:a},'function'),this.match=a,c?
       (assert.isOneOf({method:c},validMethods),this.method=c):this.met…
```

```shell
e instanceof b
        false
```

**Comment by jmtt89** [comment]
Extra update:
if use **registerRoute** method (two params, path and handler), **work's fine** but i can't add a *http method* 

```js
   //Calls OK
    workboxSW.router.registerRoute(new RegExp('^https://fonts.googleapis.com/*'), cacheFirst);
    workboxSW.router.registerRoute('/my/custom/path/:id', networkFirst);
```

**Comment by jeffposnick** [comment]
I'm pretty sure this is due to https://github.com/GoogleChrome/workbox/issues/385. We need to address that underlying issue.

**Comment by mikefowler** [comment]
@jeffposnick I've recently run into the same issue. Seems like #385 is pretty stale. Any avenue for me to help out here?

**Comment by jeffposnick** [comment]
The tactical fix is to re-export/alias the vanilla [`workbox.routing.Route`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-routing/src/lib/route.js#L98) class definition as `WorkboxSWInstance.router.Route`, and then it could be constructed or subclassed directly.

@gauntface and I have had some discussions about more elaborate workarounds, but in the interest of unblocking folks, I'm inclined to go that *route* for now, and perhaps consider a more comprehensive change for the next major release.

I'll put together a PR for that and give folks a chance to raise any objections there.
