### ISSUE TITLE
Error：Cannot find API  'cacheFirst'

### ISSUE THREAD

**Issue by zhouyao** [GoogleChrome/workbox#641]
https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-sw/demo/service-worker.js#L17

`workboxSW.cacheFirst()
`　 -> error
`workboxSW.strategies.cacheFirst()` -> correct

**Comment by jeffposnick** [comment]
We've removed those `demo/` directories, with the intention of https://workboxjs.org/examples/ being the canonical resource.
