### ISSUE TITLE
How to monitor caching progress

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#649]
**Library Affected**:
workbox-sw

**Browser & Platform**:
All

**Issue or Feature Request Description**:
Is there a way to keep track of workbox's progress in caching resources?

**Comment by gauntface** [comment]
@kaycebasques when you "progress" in caching resources? What sort of "progress" did you have in mind?

**Comment by kaycebasques** [comment]
Say I'm downloading an entire site over a flaky cell network. I want to know when every resource has been cached.

I suppose the service worker could loop through the assets manifest array and check the status of each item?

**Comment by gauntface** [comment]
Well your service worker wont be active until all the assets have been downloaded, so what is the use case for knowing when it's downloaded?

**Comment by kaycebasques** [comment]
So the active event is equivalent to what I'm looking for? Works for me
