### ISSUE TITLE
Bad Documentation :S

### ISSUE THREAD

**Issue by dertuerke** [GoogleChrome/workbox#651]
Hello, I find your work really cool. But I must say that the documentation is really bad. You can find nothing about the Gulp functions or the options you can use.

I would like to have a better documentation about the gulp functions.

Thank you: D

**Comment by mikefowler** [comment]
Howdy, @dertuerke! 

Knowing the wonderful folks at Google working on Workbox for us, they would gladly welcome pull requests from you, updating the parts of the documentation that you find to be inaccurate or lacking!

If you're unable to create pull requests, perhaps you could create a list of links to specific places in the documentation that need improvement? With that list in hand, Google or any other contributors could help out by updating the documentation appropriately.

✌️

**Comment by gauntface** [comment]
+1 @mikefowler's comments.

At the moment the pages that you can find on workboxjs.org are here: https://github.com/GoogleChrome/workbox-microsite

We also have reference-docs, which are taken directly from the source code, so if you find problems there, then that would involve changes to source code in this repo.

PR's are most certainly welcome or more specific pages you didn't find helpful and / or specific functions you couldn't find info on would be very helpful.

**Comment by addyosmani** [comment]
@kaycebasques as we think about the getting started experience, perhaps we can also keep in mind this feedback about options for one of the build process choices (e.g using Workbox with Gulp)

**Comment by prateekbh** [comment]
Both Gulp and webpack plugins rely for their config on `workbox-build`. One option is to direct people to a common place for the option available or add more verbose description on both pages.

**Comment by kaycebasques** [comment]
@dertuerke do you remember what specifically you were trying to do when you realized that the docs were bad? Or were you just exploring Workbox, and wanted to see what it is capable of?

**Comment by dertuerke** [comment]
@kaycebasques 
I only found this page, how to work with Gulp:
https://workboxjs.org/get-started/gulp.html

And this code:
https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/gulpfile.js#L112

Because rest I found in node_moduls/workbox-build/

On the website you can not find these settings, right?

**Comment by gauntface** [comment]
This looks like the gulp example is demonstrating the "generating an entire SW" of workbox-build where as fixit example is demonstrating how to inject the precache manifest into an existing service worker file.

This is a case where a CDN would make it easier to reason with and get set up, but I'm still not sure what the IA should be to explain this easily. @kaycebasques any ideas of how to manage this?

**Comment by gauntface** [comment]
This is going to be pretty different in V3 and PR's are out to improve the next version of docs AND the getting started story, so going to close this for now.
