### ISSUE TITLE
copy node_modules scripts in webpack plugin

### ISSUE THREAD

**Issue by zhirzh** [GoogleChrome/workbox#653]
If I have some `importScripts('node_modules/.../workbox-sw.js');` in my `src/sw.js`, webpack plugin should copy those files into *destination folder*.

This "copying" feature is present when generating a serviceworker, but doesn't work when using a serviceworker template.

**Comment by gauntface** [comment]
Going to merge this with #650 and mention the same exists for the webpack plugin.
