### ISSUE TITLE
How can I serve a `network-error` page offline with workbox

### ISSUE THREAD

**Issue by rayvafa** [GoogleChrome/workbox#655]
I spend hours trying to figure out how can I do this using workbox but couldn't find anything. 
This was possible before using sw-toolbox: https://alligator.io/js/service-workers-sw-toolbox-offline-page/

Thanks

**Comment by jeffposnick** [comment]
This is related to https://github.com/GoogleChrome/workbox/issues/438

If you'd like to see this "officially" supported via a standard `Handler`, then chime in there 😄
