### ISSUE TITLE
SW broken on Canary, but seems to work on Stable

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#656]
90% chance this is pilot error, but maybe there's something that needs to get documented

**Library Affected**:
workbox-sw, workbox-build

**Browser & Platform**:

Stable:
Google Chrome	58.0.3029.96 (Official Build) (64-bit)
Revision	2a03c99a5f45c6d507af8eb2345ad68a565d1518-refs/branch-heads/3029@{#787}
OS	Mac OS X

Canary:
Google Chrome	61.0.3144.0 (Official Build) canary (64-bit)
Revision	02c80fa9c3cc98fe3ae5e94e881f4a05d9cd174c-refs/heads/master@{#483234}
OS	Mac OS X

**Issue or Feature Request Description**:
1. Open Stable
1. Go to https://wordsmithweekly.com/blog/audience-analysis
1. Click **Save for offline** at the bottom of the post
1. Go offline and use the site, it seems to work as expected
1. Open Canary and repeat the steps. It seems to be broken

Airhorner works on both Canary and Stable, so it looks like I broke something, but can't figure out what.

**Comment by jeffposnick** [comment]
Hey @kaycebasques—everything seems to work as expected on **Version 61.0.3145.0 (Official Build) canary (64-bit)**. I can save your site, go offline, and then either reload or navigate to new pages, and everything loads.

Do you see errors in the JS console when the offline navigations fail? Can you try again in an Incognito window and see if it's reproducible there?

**Comment by addyosmani** [comment]
Friendly ping @kaycebasques in case you got this working in the latest Canary. Could you confirm?

**Comment by jeffposnick** [comment]
(Just confirming that I still can't reproduce in Canary.)

**Comment by kaycebasques** [comment]
We're good, thanks for checking
