### ISSUE TITLE
Document how to inject a manifest with workbox-cli in Get Started

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#657]
Looks like it accepts command-line and config flags, but not immediately obvious to me from the source how to do either of those

More generally speaking, every Get Started path should probably cover both cases (how to generate a SW, how to inject a manifest).

**Comment by Vintharas** [comment]
I had the same problem ^_^. I looked at the[ PR that implemented this functionality](https://github.com/GoogleChrome/workbox/pull/550) and it from what I understood given a source service worker file `srcSw.js`like this:

``` javascript
importScripts('workbox-sw.prod.v1.0.1.js');

const workboxSW = new self.WorkboxSW();
/* workbox-cli will inject precaching in the array below*/
workboxSW.precache([]);
```
It injects the files to precache inside the `precache` method based on your workbox-cli config file.

**Comment by gauntface** [comment]
@kaycebasques if you can point me in the direction of where you would like this documented, I can create a PR with content for it.

**Comment by Lyricalz** [comment]
Something else to look out for, is if you initially generated your config file with the cli, it doesn't include the 'swSrc' key, which is mandatory when using 
`workbox-cli inject:manifest`

**Comment by gauntface** [comment]
Discussing the wizard issue further here: https://github.com/GoogleChrome/workbox/issues/1052

Otherwise the documentation for CLI injection can be found on the "precache files" guide on the new doc site. (Will land soon here: https://developers.google.com/web/tools/workbox/guides/precache-files)
