### ISSUE TITLE
Consider a more hierarchical reference structure

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#658]
Can all of the workbox libraries be used as standalone modules? I think not. E.g. `workbox-routing` can only be used when `workbox-sw` is present.

If this is the case, consider organizing the reference to reflect dependencies. It's a simple yet effective way to quickly understand how all the modules relate to each other

**Comment by jeffposnick** [comment]
Yes, all of the libraries are meant to be usable from outside of `workbox-sw`. I.e. here's some hypothetical `workbox-routing` code:

```js
importScripts('https://unpkg.com/workbox-routing@1.0.0');

const route = new workbox.routing.Route({
  match: ({url}) => url.endsWith('.css'),
  handler ({event}) => event.respondWith(new Response('no styles for you!')),
});
const router = new workbox.routing.Router();
router.registerRoute({route});
```

We definitely need to do a better job of striking a balance between pointing the average developer who needs a "batteries included" experience to `workbox-sw`, while still documenting/providing examples for the smaller libraries that might be used by folks who don't want to/can't adopt the full framework.

**Comment by addyosmani** [comment]
> Can all of the workbox libraries be used as standalone modules?

We probably do a poor job of highlighting that many/most of our modules can be used outside of -sw. Perhaps we should include some blurb on the homepage (or a subpage) about this being supported?

**Comment by jeffposnick** [comment]
I'm in favor of a How-To page for this material.

It could focus on custom builds that combined a few named exports from the ES2015 source to produce a pared-down, focused library for a specific use case.

I think @philipwalton has been exploring this use case.

**Comment by gauntface** [comment]
This is a much better story in V3. I'm hoping to get some time in the next day or two to write up some of this stuff. Will share around as soon as possible.

**Comment by gauntface** [comment]
With V3 the API for workbox-sw and the individual modules is exactly the same after P@philipwalton landed the singleton PR.

This along with the CDN makes it easy to switch between workbox-sw and the individual modules so I'm going to close this for now - please re-open if you disagree.

p.s. all demos for the individual modules should only include for the current module + workbox-core. i.e. workbox-routing will not use workbox-runtime-caching in the demo - that is left for workbox-sw which will be a more expansive demo.
