### ISSUE TITLE
Consider rebranding as offline libraries

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#659]
<img width="1389" alt="screen shot 2017-06-29 at 5 05 23 pm" src="https://user-images.githubusercontent.com/4713486/27715618-477ff394-5ced-11e7-8e88-bb2375aac037.png">

"JS Libraries For Progressive Web Apps"? No idea what that means. PWA is a vague term that encompasses a bunch of modern best practices. Case in point, maybe I equate PWA with push notifications. Does Workbox help with that? I don't think so. Maybe I equate it with Add To Homescreen. Again, misleading. PWA is just too broad a term.

The "what's in it for you" section of WB ("Offline Caching", "Offline Analytics", "Background Sync") spans about 10% or less of the Above-The-Fold.

It looks like every library is related to offline capabilities. If that's the case, that's a much easier value proposition.

Maybe not *every* library is related to offline, but if that's the main value proposition, then maybe that's how the homepage should be branded regardless.

**Comment by addyosmani** [comment]
Is the suggestion we switch this to ~"Offline support for modern web apps" or similar?

cc'ing @tjsavage our PM on this for his initial take on the best way to highlight the value prop of WB in our framing of the project.

**Comment by gauntface** [comment]
I'm pro this change. We are in DevSite now so perhaps @kaycebasques would like to just do it and see what happens ;)

**Comment by kaycebasques** [comment]
The thing that prompted me to raise this issue was the fact that the tagline below the Workbox logo is "JavaScript Libraries For Progressive Web Apps". To me "JavaScript Libraries For Offline Web Apps" conveys the purpose more effectively.

However, Jeff mentioned while reviewing the Overview doc that one use of WB is to cache some files to make the page load faster, without really focusing on an offline experience. So "JS Libraries For Offline" may be too strong. 

> The "what's in it for you" section of WB ("Offline Caching", "Offline Analytics", "Background Sync") spans about 10% or less of the Above-The-Fold.

By this I meant that if you look at the above-the-fold (ATF) content, a very small amount of it (~10%) was being used to explain to our users why they should care about Workbox. Another way to phrase this suggestion would be: we should dedicate more ATF space explaining the value proposition of Workbox to our users.

**Comment by gauntface** [comment]
After discussing this in weekly sync I'm going to close this issue.

Docs at the moment are the weakest part of the Workbox project. We are working to change the IA and the content pretty heavily to a point where the docs will probably need a much wider review where this will come up again, but right now, it's really hard to action on it or comment on it given the general goals of workbox which is to make building PWAs easier.
