### ISSUE TITLE
runtime-caching-converter explicitly disallows non-GET

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/workbox#661]
**Library Affected**:
workbox-build

**Browser & Platform**:
All (well I'm using Node v8.1.3)

**Issue or Feature Request Description**:
[This line](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/utils/runtime-caching-converter.js#L42) explicitly disallows non-GET inside the converter code. Why? I can just write one manually, this just disallows it for -build.

Additionally, the `method` arg isn't [documented here](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/generate-sw.js)—although that makes sense if it's disabled.

**Comment by jeffposnick** [comment]
Ah, that was because we didn't have a clean way of supporting non-`GET` in WorkboxSW's `registerRoute()` until we added #644.

I can relax that restriction in the `runtimeCaching` conversion in a follow-up PR.
