### ISSUE TITLE
Background sync RequestQueue doesn't re-populate

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#674]
The `initQueue` method calls [`.concat(idbQueue)` here](https://github.com/GoogleChrome/workbox/blob/d60bf9744dd89ecaafe80205c329225771caf0ab/packages/workbox-background-sync/src/lib/request-queue.js#L55) when it should be calling `.push(...idbQueue)`, and as a result the queue is not initialized with existing data in the store.

In addition to fixing this, we should probably also add a test covering this case. @prateekbh are you able to do this? If not I can take a look.

**Comment by prateekbh** [comment]
will check and fix this ASAP

**Comment by prateekbh** [comment]
I am unable to reproduce this, need more info on this.

`idbQueue` is supposed to be an array of requests, hence the `.concat` call

**Comment by philipwalton** [comment]
The expression `this._queue.concat(idbQueue)` will return the new array, but it won't modify the value of `this._queue`, which means `this._queue` never gets populated with the values from IndexedDB.

If you replace that line with `this._queue.push(...idbQueue)` it will work as expected. But that's the easy part. The hard part is writing a test for this :)

**Comment by prateekbh** [comment]
So stupid of me! Yeah i'll change it to the spread operator
