### ISSUE TITLE
Relationship of header values to workbox-cacheable-response

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#676]
Deciding whether to cache a response based on status code is logical enough, but I don't get the header values scenario.

How are header values relevant to determining whether a response should be cached? What are some examples of relevant headers?

**Comment by gauntface** [comment]
Looks like max age is one example where it might be desirable: https://github.com/GoogleChrome/sw-toolbox/blob/587f9adb29b1149bd94d4723b15925a63dee51bb/lib/helpers.js#L180

**Comment by jeffposnick** [comment]
The use case was described at https://github.com/GoogleChrome/workbox/issues/131#issue-200535197 by @samuelli and seemed valid (if not particularly common).

**Comment by gauntface** [comment]
@kaycebasques is there anything you want as an outcome from this? I.e. docs, api changes or ...?

**Comment by kaycebasques** [comment]
We're good... the scenario seems uncommon so I'm not going to do any work on it. But if it does come up again and I need to document, I'll be able to explain with this issue and the other referenced issues
