### ISSUE TITLE
Enable syntax highlighting in code samples

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#678]
My eyes are bleeding

<img width="1289" alt="screen shot 2017-07-12 at 5 43 27 pm" src="https://user-images.githubusercontent.com/4713486/28145765-b19f3974-6729-11e7-8b70-6130e8a19677.png">

Another feature enabled by default in DevSite ;)

**Comment by gauntface** [comment]
This was a problem with jsdoc and I was just about to PR in a hack but realised this is an extremely nice way to do this and should be fixed now.
