### ISSUE TITLE
List of WB code alterations

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#679]
This section in the webpack tutorial is very helpful in explaining that WP transpiles `import` statements, but it doesn't touch any other code.

https://webpack.js.org/guides/getting-started/#es2015-modules

It was a jarring experience when I realized that Workbox altered some of my code. The WB docs should follow the WP model and explicitly mention all of the times that WB alters code.

The info I need is a list of when this can happen. Is it only `injectManifest()`?

**Comment by kaycebasques** [comment]
Do any other libs do this?

**Comment by gauntface** [comment]
Nope, only workbox-cli and workbox-build will look for and alter your code if you perform an "injectManifest"  action / function call.

This wasn't even a desirable solution, but it was the simplest for everyone to use and easiest to explain.

**Comment by addyosmani** [comment]
> The WB docs should follow the WP model and explicitly mention all of the times that WB alters code.

As Matt mentioned, -cli and -build are the only pieces that will make code modifications when using injectManifest on your behalf. Would it be useful if we had a special callout style for these types of important gotchas in the docs?

**Comment by gauntface** [comment]
@addyosmani I'm not sure of the use here, if you are using inject manifest, then you are expecting the manifest to be injected to the build version. I'm not sure a message will add anything here.

**Comment by gauntface** [comment]
@kaycebasques if you get a chance to call out where we can add some information or word something differently to highlight this it would be useful, otherwise I'm not sure how to action this item.
