### ISSUE TITLE
Is caching method POST requests with runtimeCaching still not allowed in v1.1.0?

### ISSUE THREAD

**Issue by dharmawankenny** [GoogleChrome/workbox#683]
Library Affected:
workbox-sw

Browser & Platform:
Chrome 59.0.3071.115 (Official Build) (64-bit)

Issue:
I've upgraded to v1.1.0 for feature updates regarding allowing caching other method than GET and allowing to register a vanilla Router in workbox-sw, however, while doing the first one i stumbled upon a console.log error saying that "Uncaught (in promise) TypeError: Request method 'POST' is unsupported", however while diving in the codebase i saw that POST was included in valid methods, but i keep getting this messages and it wont cache the request.

Currently, i am implementing the runtimeCaching in a way like this:

```javascript
workboxSW.router.registerRoute(
    {some route},
    workboxSW.strategies.staleWhileRevalidate({
       cacheName: 'tvlk-api',
       cacheExpiration: {
          maxAgeSeconds: 7 * 24 * 60 * 60
       },
       cacheableResponse: {
          statuses: [0, 200, 304]
       },
    }),
    'POST'
);
```
is this an error or my part or was this an unintended bug or intended restriction? because while reading the release notes, i presume POST is allowed and reading the code clearly shows that POST was included in the valid methods, even the testing file allows POST to be registered in the runtime caching API.

Thanks in advance and i am sorry for writing in broken english.

**Comment by jeffposnick** [comment]
The Cache Storage API [specification](https://w3c.github.io/ServiceWorker/#cache-put) won't allow you to use a `Request` with any method other than `GET` as a key when writing to a cache.

Creating a `Route` which matches non-`GET` requests and then handles them is now possible in`workbox-sw` 1.1.0 as long as you take that restriction imposed by the specification into account.

For instance, you might have a route which matched `PUT` requests and then a handler which attempted a `fetch()`, and then caught any errors and updated IndexedDB when they occurred. [Here's an example](https://github.com/GoogleChrome/ioweb2016/blob/master/app/scripts/sw-toolbox/offline-session-updates.js) of that sort of thing, using `sw-toolbox`. (Of course this use case might also be solved automatically, via `workbox-background-sync`.)

**Comment by dharmawankenny** [comment]
I see, thanks for the help, ill try the background sync.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prateekbh** [comment]
well background-sync basically stores your requests in indexedDB, so it does support a POST request 👍
