### ISSUE TITLE
Expose RequestWrapper options to workbox-sw strategies when initiating a strategy instance?

### ISSUE THREAD

**Issue by dharmawankenny** [GoogleChrome/workbox#686]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Version 59.0.3071.115

**Issue or Feature Request Description**:
How can i pass down a RequestWrapper's options when using workbox-sw's strategies, i need to provide an 'ignoreSearch: true' as an options when initiating the requestWrapper to tell serviceworker to ignore query parameters on the url and serve the request from the same url with different URL.

And if this was to be an option, can it be like sw-precache's ignoreUrlParametersMatching? i dont seem to find the way to ignore certain parameters when doing a runtime-caching, a way to do this like sw-precache does would be nice since it is normal to ignore certain parameters (like utm-) when providing a response in a lie-fie or offline situations.

Thanks in advance.

**Comment by jeffposnick** [comment]
We don't have an out-of-the-box plugin that implements the same logic at runtime that we do with the precached resources.

You do have the option of defining your own plugins that can be used with `workbox-sw`'s strategies. This is untested, but it should let you register a plugin that will attempt to match a request's URL using `ignoreUrlParametersMatching`-style logic when doing runtime caching.

If there's enough demand, we could probably package it up into a new reusable module, like `IgnoreUrlParametersPlugin`, and then adapt `workbox-precaching` to depend on the same logic.

```js
// The same basic logic used when stripping parameters for precaching matches.
function stripIgnoredUrlParameters(originalUrl, ignoreUrlParametersMatching) {
  var url = new URL(originalUrl);
  url.hash = '';

  url.search = url.search.slice(1) // Exclude initial '?'
    .split('&') // Split into an array of 'key=value' strings
    .map(function(kv) {
      return kv.split('='); // Split each 'key=value' string into a [key, value] array
    })
    .filter(function(kv) {
      return ignoreUrlParametersMatching.every(function(ignoredRegex) {
        return !ignoredRegex.test(kv[0]); // Return true iff the key doesn't match any of the regexes.
      });
    })
    .map(function(kv) {
      return kv.join('='); // Join each [key, value] array into a 'key=value' string
    })
    .join('&'); // Join the array of 'key=value' strings into a string with '&' in between each

  return url.toString();
}

function cacheWillMatch({request, cache, cachedResponse, matchOptions}) {
  // If there was already a match before applying this plugin, then return it.
  if (cachedResponse) {
    return cachedResponse;
  }
  const parametersToIgnore = [/^utm/]; // Add any others...
  const urlWithoutParameters = stripIgnoredUrlParameters(request.url, parametersToIgnore);
  return cache.match(urlWithoutParameters, matchOptions);
}

// Use networkFirst, staleWhiteRevalidate, or whatever base strategy you want.
const myStrategy = workboxSW.strategies.networkFirst({
  plugins: [{cacheWillMatch}],
  // Any other options.
});

workboxSW.router.registerRoute(
  '/my/routing/criteria',
  myStrategy
);
```

I'm going to close this issue with the assumption that the above code works for you, but please let us know if that's not the case.

**Comment by jeffposnick** [comment]
I just wanted to throw in an alternative approach if you prefer having more control over the URLs before they even pass through to the handler. This has the advantage of causing the cache writes to use the normalized URL as well as the cache reads.

```js
function stripIgnoredUrlParameters() {
  // Same code as before.
}

// Use networkFirst, staleWhiteRevalidate, or whatever base strategy you want.
const myStrategy = workboxSW.strategies.networkFirst();
const parametersToIgnore = [/^utm/]; // Add any others...

workboxSW.router.registerRoute(
  '/my/routing/criteria',
  ({url, event, params}) => {
    const urlWithoutParameters = stripIgnoredUrlParameters(url, parametersToIgnore); 
    return myStrategy.handle({url: urlWithoutParameters, event, params});
  }
);
```
