### ISSUE TITLE
📣 Call for Ideas to Improve Workbox

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#692]
It's been a while since Workbox was announced at Google I/O and there has been a tonne of great feedback from users of Workbox (Thanks y'all), so as we look to plan for V2 and beyond, I'd love to get input from anyone and everyone on changes they'd like to see in the project, some possible topics:

- Release Schedule
- New Modules
- Feature Requests
- Github / Community Support

Let us know what you'd like to see happen, any idea welcome

cc @addyosmani @jeffposnick @philipwalton @prateekbh @kaycebasques @goldhand @sethbergman @HoBi @gondar00 @johnpapa @MaxLeiter @zhirzh @mikefowler

**Comment by MaxLeiter** [comment]
One nitpick: I'd specify if Semver is being used in the README. It seems like it is, but the [changelogs](https://github.com/GoogleChrome/workbox/releases) (or lack thereof) make it hard to tell.

**Comment by gauntface** [comment]
### Bi-Weekly Community Time

Would anyone like / want to have a few hours every 2 weeks where we get together on slack / gitter / hangout / <Insert messenger here> to provide a place for everyone to sync up, chat and discuss but we could also use the time to power through Stackoverflow and just generally do some project maintenance.

@addyosmani mentioned we could just use the ChromiumDev slack channel.

### Testing Infra

We have some fairly funky testing set-up, not in a totally bad way, but it might be best to move some of the mocha wrangling out into a seperate repo, a so it can be re-used and two, de-tangles and tidies up some of the efforts there.

### Re-Assess Module 

Gulp has served us well in that we can get in the middle of a lot of stuff, but it has been changed over time and I feel like taking a fresh look could help us use clean up a lot of cruft.

### Errors

Would be great if someone could invest a chunk of time in figuring out how to easily create errors such that the error code, message and additional options can be displayed on workboxjs.org meaning in dev mode we can show full fat error messages in the console while using short error codes + links in production mode.

**Comment by gauravmediology** [comment]
I would be great if you add some more examples for implementation. for e.g. I want to implement background sync and I do not see a full example of that. How can I implement it in the service worker code?

**Comment by gauntface** [comment]
Going to close this as v3 work has been ongoing for some time,
