### ISSUE TITLE
Normalize all RequestWrapper lifecycle methods to return a Promise<*>

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#709]
**Library Affected**:
*workbox-runtime-caching*

The method signature for the public `cacheWillMatch()` interface is for it to return a `Response`, but there are use cases in which it would be ideal to perform some asynchronous operation prior to returning that response. In the next major release, we should change the interface to return a `Promise<Response>` instead.

The concrete use case for this is to perform an IndexedDB lookup prior to returning a response, which would have come in handy when fixing https://github.com/GoogleChrome/workbox/issues/691

**Comment by addyosmani** [comment]
> In the next major release, we should change the interface to return a Promise<Response> instead.

I was about to ask about the use-case, but you have that covered :) Making this change in the next major release SGTM.

**Comment by gauntface** [comment]
Should we make this consistent across all plugins, i.e. they all return a Promise?

**Comment by jeffposnick** [comment]
That would probably future proof everything, yes.

**Comment by addyosmani** [comment]
> Should we make this consistent across all plugins, i.e. they all return a Promise?

👍 Agree with going down this route for consistency sake. Do we need a separate issue for tracking doing this or did you want to reuse the same issue for it?

**Comment by gauntface** [comment]
Reuse this one.

**Comment by jeffposnick** [comment]
This was fixed in #736
