### ISSUE TITLE
Rename cacheWillMatch lifecycle method

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#713]
**Library Affected**:
*workbox-runtime-caching*

There's currently a lifecycle method triggered by `RequestWrapper.match()` called `cacheWillMatch()`, which gives a plugin the opportunity to inspect the cached response that would normally be returned for a given request, and either return `null` if the cached response isn't valid (because it's expired, for instance) or return an alternative response instead (like a 206 Partial Content version of it).

There's been some internal discussion about renaming this method in the next major semver release, with `cachedResponseWillBeUsed()` as the current leading candidate. If folks have alternative suggestions, add them here.

**Comment by gauntface** [comment]
Let's get this in for V2 - everyone seems in favor of this and no complaints found in meeting.

**Comment by addyosmani** [comment]
> cachedResponseWillBeUsed() as the current leading candidate

To echo internal support for it, 👍. SG to move ahead with it for v2.

**Comment by jeffposnick** [comment]
I'd like to get #710 merged to `v2` first, and then I'll handle this renaming, since that open PR still using the `cacheWillMatch()` lifecycle name.
