### ISSUE TITLE
Default Export - What is it?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#734]
During the last meeting I asked about the "instance" or "default" use of our modules having extra logic directly in the module instead of this "extra logic" living in `workbox-sw`. My hope with this is that we can sanitize our explanation of how workbox works (i.e. they'll be exposed to a module name for a particular task rather than something that covers over our module structure and use).

This raised the question, if a developer imports one of our modules what should they get?

```javascript
import workboxRouting from `workbox-routing`;
import workboxPrecaching from `workbox-precaching`;
import workboxStrategies from `workbox-strategies`;
```
When I was prototyping build and usage of ES2015 modules, the mental model I took was that importing the module should result in something easy to use that does what I'd expect/

`workbox-routing` => Something that **does routing**
`workbox-precaching` => Something that **does precaching**
`workbox-strategies` => Something that **has strategies**

etc etc....

Talking informally to a few people, this is referred to as the "default export" or it's just "using the module". No one suggested they expected a Class or an object of classes, it was more along the lines of expecting what makes sense for that module.

I'd argue that the result should be the most common use case. ES2015 modules afford the ability to cleanly supply public classes in case our default isn't what someone wants as well as handling more intricate uses of our modules.

Anyway just wanted to open this for discussion since it appears to have slipped in the V3 doc cc @addyosmani @jeffposnick @philipwalton @prateekbh @mikefowler @deanhume @goldhand

**Comment by jeffposnick** [comment]
After thinking about this a bit, I'm going to come down on the side of **not** exposing a `default` export for the ES2015 modules, pretty much anywhere. I like our model of using classes throughout the libraries, and configuring instances of those classes via their constructors, and don't feel like we need to shy away from requiring that.

I think we're still okay with moving some of the "magic" out of `workbox-sw` and into helper methods on the various classes used under the hood.

**Comment by deanhume** [comment]
Hi @gauntface - this looks great!

Just thinking of this from the end users point of view (and apologies if this comes across as a silly question!) - as @jeffposnick mentioned, will users still be able to load in the additional modules as they need them using importScripts using the example above? For example:

importScripts('workbox-sw.prod.vX.X.X.js');
importScripts('workbox-routing');

And so on. Hope that makes sense!

**Comment by gauntface** [comment]
@deanhume not a silly question at all.

Yes then will be able to. All our modules will come with a browser bundle as well (which will be available via a CDN as well).

So they can do the following:

```javascript
importScripts('workbox-routing');

// This is the default export for the module
const routing = goog.workbox.routing.default;

// This would be a public class:
const Router = goog.workbox.routing.Router;
```

**Comment by gauntface** [comment]
I've added some high-level "Default export should be <insert vague description>" to v3 tracker just to ensure this isn't completely overlooked.
