### ISSUE TITLE
[V3] Handling Releasing

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#743]
Next work load that will be added to my queue:

- [x] Create a project for CDN
- [x] Create a script that:
    - [x] Gets all tagged builds from github
    - [x] Figures out which tagged builds *aren't* on the CDN
    - [x] Collects all `dev.js`, `prod.js` and `.js.map` files for each tag and create directories for each tag
    - [x] Upload these collections into the CDN.
- [x] Create a script that will collect the `dev.js`, `prod.js` and `.js.map` files for a specific tag, create a tar.gz and upload them to a github release.
- [x] Create a script that will collect the `dev.js`, `prod.js` and `.js.map` files for a specific tag, create a .zip and upload them to a github release.
- [x] Finally find either an elegant way to add this script to the end of the lerna publish script OR add the lerna publish step as a pre-requisite *in* this script.

**Comment by gauntface** [comment]
This should be handled by #746 

The rough idea being that:

1. lerna publish is run from `gulp publish`
1. Once lerna publish is run, it'll publish a new tag to git
1. `gulp publish-bundle` will be run from `gulp publish`
    1. This task will then grab the current git tags and find ones without releases or releases without assets
    1. The script will create a github release
    1. Build the git tag and generate a .tar.gz and upload it to the github release.
    1. Then upload this to the CDN.

The only different from above is that a .zip isn't generated and the storage bucket assumes if it's in Github, it's in the CDN.

**Comment by addyosmani** [comment]
@gauntface It appears the items on this one are complete. Is there anything left to be completed?
