### ISSUE TITLE
Proposal: workbox-precaching explicit handler registration

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#747]
(Moved from https://github.com/GoogleChrome/workbox/issues/721#issuecomment-322492280)

**Library Affected**:
*workbox-precaching*

@gauntface wrote:

> For workbox-precaching, should we add `registerInstallHandler()`, `registerActivateHandler()` and `registerFetchHandler()` methods as well and pull any logic out of `workbox-sw`?
> 
> We can then seperate the `skipWaiting` and `clientsClaim` out into separate `install` and `activate` events in `workbox-sw`.

**Comment by jeffposnick** [comment]
I'm hard pressed to come up with scenarios in which you'd want an `install` handler from `workbox-precaching` and not an `activate` handler. I could see wanting both of those handlers and not a `fetch`, I guess.

If we do offer three standalone `registerBlahHandler()` methods we should also offer a general `registerHandlers()` shorthand that takes care of all of them at once, which we expect will be the most common use case.

**Comment by gauntface** [comment]
Given these are low level modules and the low level classes, I'm not concerned about creating functions that do nothing more than group together function calls.

I'm find merging install and activate events and then have an additional fetch handler event call.

Thinking about this, should we use the term handler here given that we have a "handler" notion already?

**Comment by addyosmani** [comment]
> I'm fine merging install and activate events and then have an additional fetch handler event call.

👍

**Comment by gauntface** [comment]
I'm going to close this. We have moved our listeners into default exports and agreed in one of the team syncs that events should only be registered in the default export.
