### ISSUE TITLE
Modules + Browser Bundles in V3.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#756]
My current thinking of how we will ship our code as imports / exports with a file structure as:

```
workbox-example/
    index.mjs
    browser.mjs
    FileName1.mjs
    FileName2.mjs
    exampleDirectory/
        FileName3.mjs
    INTERNAL/
        PrivateFileName1.mjs
        PrivateFileName2.mjs
```

The `browser.mjs` is the Rollup entry file for each package and will be excluded from final npm builds via `.npmignore` files.

###### How will a package reference another packages classes?

Each module will add dependencies in package.json to ensure Lerna bootstrap builds correctly.

A module should be able to import modules and classes as you'd expect:

```javascript
import module from '<module name>';
import ClassName from '<module name>/ClassName';
```

**Our** rollup config will be set up to replace `<module name>` and `<module name>/ClassName` with global references (We can auto-generate the mappings of module names and public classes to the global references.

So in the above example, our code would be:

```javscript
import example from 'workbox-example';
import FileName1 from 'workbox-example/FileName1';
import FileName3 from 'workbox-example/exampleDirecoty/FileName3';
```

The code would be converted to (This is pseudo code cos Rollup wraps in iife, but should illustrate the end result):

```javascript
const example = google.workbox.example.default;
const FileName1 = google.workbox.example.FileName1;
const FileName3 = google.workbox.exampleDirectory.FileName3;
```

The Rollup config for this would need to have the following:

```javascript
const externals = [
    'workbox-example'
];
const globals = {
    'workbox-example': 'google.workbox.example.default',
    'workbox-example/FileName1': 'google.workbox.example.FileName1',
    'workbox-example/FileName2': 'google.workbox.example.FileName2',
    'workbox-example/exampleDirectory/FileName3': 'google.workbox.example.exampleDirecoty.FileName3',
};
```

Pros: No duplication of code and can be auto-generated for public files.
Cons: Relies on a build step to be predictably and reliably swap out public files AND public exports must have the correct export structure.

###### 3rd Party Developers Using a Module file Imports

For 3rd party developers, they'd use the modules same as above, but without the build process:

```javascript
import example from 'workbox-example';
import FileName1 from 'workbox-example/FileName1';
```

This will have no re-use of modules BUT this is fine since 3rd party developers will likely want to pull in *all* their code into a single bundle and rollup should manage the code duplication for that single bundle.

Pros: Imports only pull in the code that is used.
Cons: We need to document the import paths for files (i.e. FileName1).

###### 3rd Party Developers Using Browser Builds

For 3rd party developers using the browser build, will use the global namespace:

```javascript
importScripts('workbox-example/v3.0.0-alpha/workbox-example.dev.js');

const example = google.workbox.example.default;
const FileName1 = google.workbox.example.FileName1;
```

Pros: Easy to reason with and namespaced cleanly.
Cons: The `default` name for a modules default is a nasty crinkle in this approach, but can be covered over with `workbox-loader` (See below)

###### 3rd Party Developers using `workbox-loader`

We can provide a loader to make importing and using modules a little easier (especially for CDN usage).

```javascript
importScripts('https://cdn.workboxjs.org/v3.0.0-alpha/workbox.js');
const workbox = new Workbox();
workbox.example.methodOnDefaultExport();
```

When the developer calls workbox.example, the `workbox-loader` will import the `workbox-example` module and return the 'default' export.

Pros: The notion of 'default' isn't exposed to the developer and this covers the majority use case.
Cons: Public scope of class names won't be loaded until the first call to the workbox.example getter is called.

##### Possible Changes We May Want

- Offer an explicit `loadModule()` function in `workbox-loader` that will take a module name, like `workbox-example`, and import the script. This allows developers to explicitly load up the namespace with classes for a particular module.
- `.mjs` vs `.js` I need to explore what Rollup's support is for the `.mjs` file extension. At the moment I think `.mjs` must be defined. If this is the case we should probably use `.js` to prevent developers from having to write `import FileName1 from 'workbox-example/FileName1.mjs'`.
- The build process for public Classes to globals will not be the prettiest thing, but will ensure that we enforce a clear public vs private class name structure and guarantee no code duplication.
- The browser bundles, i.e. the `browser.mjs` file, should be auto-generated to ensure the classes are exported the same way rollup expects.

**Comment by jeffposnick** [comment]
I didn't realize that we were going to run our source `.mjs` files through Rollup prior to publishing them on `npm`. There isn't currently an example of this in the `v3` branch, right? (Or have I missed it?)

So if we have a dependency on https://www.npmjs.com/package/path-to-regexp inside of our `.mjs` source code for the `workbox-router` project, we'll still end up using Rollup + the CommonsJS plugin to pull that it at build time, and both the browser and `.mjs` bundle we ship to `npm` will have that `path-to-regexp` code inlined?

**Comment by gauntface** [comment]
The`.mjs` files are run through Rollup to generate the browser bundles, which is in v3 right now.

Ideally, I'd like us to have no external dependencies (i.e. no path-to-regexp or indexeddb dependencies). If we need to have them, they'll need to be bundled with the places they are used.

Browser build will have it inlined - .mjs will **not** have it inlined but will have it as a dependency. Will be up to the 3rd party developer to manage how that is bundle.

**Comment by jeffposnick** [comment]
> The.mjs files are run through Rollup to generate the browser bundles, which is in v3 right now.

I just wanted to confirm that there's currently no example in the `v3` branch of the final, ready-to-be-published-to-npm `.mjs` output. In other words, the non-browser bundles. Because if there was, I'd like to take a closer look at them.

> Ideally, I'd like us to have no external dependencies (i.e. no path-to-regexp or indexeddb dependencies). If we need to have them, they'll need to be bundled with the places they are used.

Regarding the IndexedDB dependency, I don't think we could write more efficient Promise-based IndexedDB code than what Jake wrote in https://github.com/jakearchibald/idb

I could easily see that resulting in a net-gain of size for our codebase (and sacrifices in developer productivity) if we had to use callback-based IndexedDB, since IndexedDB is used widely in Workbox, and callbacks are more verbose than the Promise-based syntax.

We could special-case `idb` and somehow treat it like first-party code that we own, I guess?

**Comment by gauntface** [comment]
Discussed with Jeff offline:

- `.mjs` files will be used directly (i.e. they aren't transpiled in any way)
- Both in our own modules and 3rd party developers, will use `import x from 'module-name';` and **will not** use relative paths to cross-link code.
- `idb` just needs some exploring. If we can't improve on the size then fine, but I suspect some wins can be gained.

**Comment by gauntface** [comment]
Created this page to describe: https://github.com/GoogleChrome/workbox/wiki/V3-:-ES2015-Modules-&-Browser-Bundles.
