### ISSUE TITLE
Using ignoreUrlParametersMatching has a bug when testing with `directoryIndex`

### ISSUE THREAD

**Issue by emados** [GoogleChrome/workbox#758]
**Library Affected**:
workbox-sw

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Issue: using option `ignoreUrlParametersMatching` does not work as expected.

Expected behavior is for the `service-worker` to serve the following urls `//localhost/` & `//localhost/?launcher=true`. But `//localhost/?launcher=true` doesn't get served from cache despite the `launcher` parameter being added to be ignored.

Used options:
```js
new self.WorkboxSW({
  "skipWaiting": true,
  "ignoreUrlParametersMatching": [/launcher/]
});
```

I believe this is a bug with the `capture` function which tries to add the `directoryIndex` and test against the original `url` instead of the `strippedUrl`.

Suspected culprit line is: https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-sw/src/lib/workbox-sw.js#L329

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*
N/A

**Comment by addyosmani** [comment]
> I believe this is a bug with the capture function which tries to add the directoryIndex and test against the original url instead of the strippedUrl.

If `launcher=true` isn't being ignored by `ignoreUrlParametersMatching`, that does appear to be an issue with the current capture logic. cc @jeffposnick for a sanity check

**Comment by emados** [comment]
I can confirm again, that `launcher`, `launcher=true` are not being ignored by `ignoreUrlParametersMatching`.

**Comment by jeffposnick** [comment]
Thanks for reporting, @emados. It does sound like a bug that we can fix.

If you need a workaround in the meantime, and you have a single static `index.html` file, you can probably get away with adding this to your build configuration:

```js
{
  templatedUrls: {
    '/': ['index.html']
  },
  // ...other build config options as before...
}
```

That will explicitly create a cache entry for `/` which corresponds to the contents of `index.html`.
