### ISSUE TITLE
workbox-build API Changes

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#759]
cc @jeffposnick @goldhand 

During the last meeting, the idea of changing of the `workbox-build` API came up. I believe this is around some of the API's being confusing to developer, i.e. when and how to use one or the other and then there is the topic of sharing some of the logic in `workbox-build` that isn't currently available (this might be making some of the API's public or just ensuring the internal logic can be shared with the webpack plugin).

Things that have been mentioned a few time or were discussed during our meeting:
1. One change that has been requested a few times is adding the ability to define a regex for the `injectManifest()` point.
1. Webpack can generate it's own manifest
    1. Will this help us to work with webpack server?
    1. Will we be able to have the same filtering of files of certain size? glob pattern etc?
1. The runtime caching could be extracted to a seperate internal file that webpack could use

@jeffposnick did you have any additional ideas?

**Comment by addyosmani** [comment]
Cross-reference for those asks: https://github.com/GoogleChrome/workbox/issues/696

**Comment by goldhand** [comment]
> Webpack can generate it's own manifest

I've found that webpack can generate and manage revisions for files. Chunks that come from webpack can be managed with `chunkhash` which only changes when the chunk does. Other assets (from webpack loaders and plugins) will have to be managed using the compilation hash.

> Will this help us to work with webpack server?

I am able to generate a service worker as a webpack asset so I think this will work with webpack-dev-server. Will test and update you.

> Will we be able to have the same filtering of files of certain size? glob pattern etc?

The same filtering that webpack offers in it's loaders? Or is this from the workbox api?

**Comment by gauntface** [comment]
@goldhand regarding filtering. What I meant was that workbox-build has a few steps where, once it's globbed for files, you can filter that array of files based on file size etc. Would the WebPack plugin share the logic from workbox-build or would it just rely on WebPack to do this?

**Comment by goldhand** [comment]
We have access to the "chunk" size and can implement filtering using that attribute. Does the the existing filter logic take numbers for file size arguments or do we need to provide file paths?

**Comment by jeffposnick** [comment]
The current filtering logic around sizes is at https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/utils/filter-files.js#L57

The `fileDetails` object that's passed in currently has `size`, `hash`, and `file` (path) fields.

We could rewrite that logic in `v3` to use the `ManifestTransform` approach, which offers more flexibility.

Does it sound like something that would be easy to integrate with Webpack's output?

**Comment by goldhand** [comment]
so it looks like single `fileDetails` object (in the filter function; it's an array then it's a single object in the filter function?) is very similar to webpack chunk objects. Will be easy to include the filtering. Would need to be able to import the `filteredFileDetails` function though but it seems like a very small amount of code.

Not sure what the `ManifestTransform` approach is.

**Comment by jeffposnick** [comment]
`ManifestTransform` is basically the code in https://github.com/GoogleChrome/workbox/pull/664.

It provides a pluggable way of configuring modifications to the list of URLs + revision details (i.e. hashes) after the initial manifest is generated. Kind of like a post-processing thing.

We've moved some of the one-off modifications that fit into that category, like modifying the URL prefixes, to use `ManifestTransform` under the hood. Developers are free to add in their own, transformations as needed, and it may or may not be useful for your Webpack code—you might want to just create a manifest that initially meets all the requirements, instead of creating a manifest that then needed to be transformed.

**Comment by jeffposnick** [comment]
Closing in favor of https://github.com/GoogleChrome/workbox/issues/803
