### ISSUE TITLE
website broken until I did a hard reload

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/workbox#760]
no errors in the network makes me think there was a poisoned SW install that would not update, thus ... this result:

(I did two soft reloads before I did a hard reload and the page remained broken)

![image](https://user-images.githubusercontent.com/883126/29537996-b324e79e-8678-11e7-982b-3845cbb40e40.png)

**Comment by gauntface** [comment]
Without logs from the network or more info it's hard to debug this :(
