### ISSUE TITLE
Workbox CLI freezes on generate:sw and inject:manifest after selecting the root folder.

### ISSUE THREAD

**Issue by leolabs** [GoogleChrome/workbox#765]
**Library Affected**:
workbox-cli

**Browser & Platform**:
- macOS 10.12.6 (16G29)
- Node v8.1.0

**Issue or Feature Request Description**:
Workbox CLI freezes on generate:sw and inject:manifest after selecting the root folder. CPU usage stays normal, but it is not possible to kill the process using CTRL-C or CTRL-Z after it froze.

Edit: It seems to be working fine on Node v8.4.0 again.

**Comment by gauntface** [comment]
I've hit this a couple of times and assumed it was an issue with inquirer as it occured on a few different projects :(

**Comment by jeffposnick** [comment]
The code is changing quite a bit in v3, with https://github.com/GoogleChrome/workbox/pull/965

Given that it's not reliably reproducible and that the code will be different soon, we're going to close for now. If you're able to reproduce once v3 is launched, please let us know and reopen.
