### ISSUE TITLE
`entry.url` is using Windows separator

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/workbox#771]
Hi, there.

We are trying to precache our static assets for Bootstrap in this PR: https://github.com/twbs/bootstrap/pull/23533

With `workbox-build`  v2.0.0 on Windows, I'm getting this:

```js
  {
    "url": "about\\index.html",
    "revision": "f9307e727e85be5a2a420ca9a44a4f01"
  },
```

I can just do a replace for the backslashes, but I wonder if this should happen in the first place? I know that URLs do not use backslashes but here maybe this is normal?

Thanks!

**Comment by gauntface** [comment]
No this is definitely a bug, so thank you for raising this. I'm not sure how this is happening though as we have tests to check for this. Will have a look.

**Comment by XhmikosR** [comment]
I had a quick look and it seems the issue is caused by `path.join` [here](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/utils/get-file-details.js#L27)

If you use `path.posix.join` it works but I guess that is not the place to make the change.

**Comment by XhmikosR** [comment]
OK I think I figured it out.

**Comment by XhmikosR** [comment]
See #774
