### ISSUE TITLE
router.registerNavigationRoute not supported on some mobile browsers

### ISSUE THREAD

**Issue by nasearle** [GoogleChrome/workbox#775]
Just a heads up: `router.registerNavigationRoute` uses [`request.mode` under the hood](https://github.com/GoogleChrome/workbox/blob/e568e4e418dd1c85c1b70471cbb98d47c5042b70/packages/workbox-routing/src/lib/navigation-route.js). This lacks support on [some mobile browsers](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#Browser_compatibility) that support service worker. Workbox users may need to create regular routes that match pages directly instead, until request.mode is more widely supported.

**Comment by gauntface** [comment]
Navigate mode is support in Chrome 49 and Firefox 46.

Chrome 49 was released: 2016-03
Firefox 46 was released:   2016-04

Did you see a browser that didn't have support for this?

**Comment by jeffposnick** [comment]
FWIW, `sw-precache` [has used](https://github.com/GoogleChrome/sw-precache/commit/db3e199ef2ea9a93a45cb5be009f36e6fc890082#diff-badc166d987ef92476cea43bd2f0f2a8L157) `request.mode` for the past year or so, and no one has complained on its issue tracker.

I don't trust that MDN page regarding Firefox on Android support for `request.mode`. I just tried out a few Workbox demos that rely on it using Firefox 55 for Android, and they worked as expected. Also, https://jsbin.com/racosolujo/edit?js,console works as expected on Android Firefox.

There are non-evergreen browsers that do support service workers but don't support `request.mode`, but they almost certainly don't support `async`/`await` either, which is heavily used, untranspiled, within Workbox. So getting Workbox working on those out-of-date browsers would be a larger task than avoiding `request.mode`.
