### ISSUE TITLE
A Route should be able to support multiple methods

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#777]
At the moment the Route can only determine a single Route method. It should be able to support GET and POST and anything else if it wants.

**Comment by jeffposnick** [comment]
Counterpoint: it's not possible to use a non-`GET` request as the key when writing to the cache using the Cache Storage API. None of our built-in strategies will work with non-`GET` requests.
(See 3.2 of https://w3c.github.io/ServiceWorker/#cache-addAll)

Having the router default to matching only `GET`, and making users who want to use non-`GET` requests explicitly create a route for each method, was a design choice in response to that.

There are definitely times when intercepting requests for non-`GET` methods are appropriate—times when you're not just passing things through to the Cache Storage API—but I want that background to inform the decisions we make about changing the routing interface.

**Comment by gauntface** [comment]
It was primarily to avoid this: https://github.com/GoogleChrome/workbox/pull/770/files#diff-9bc96cf338ad095ad1837e5fb2766205R130

This does raise some questions around sw-toolbox's .post, .head etc API and how that plays with strategies.

**Comment by gauntface** [comment]
Closing this as a duplicate of #778
