### ISSUE TITLE
Feature: Add fetchDidSucceed method to requestWrapper

### ISSUE THREAD

**Issue by weeblr** [GoogleChrome/workbox#788]
Per this discussion https://stackoverflow.com/questions/46026849/postprocess-page-content-with-stalewhilerevalidate/

and @jeffposnick response, adding a method to allow modifying the response in all cases (ie fetched from network or fetched from cache). 

Currently, it is not possible to modify a response that was obtained from the network, only when it was obtained from the cache.

**Comment by gauntface** [comment]
@weeblr sorry for being so quiet on this issue. 

Use case here is having the ability to inject some JS into all pages.

**Comment by weeblr** [comment]
@gauntface No problem. Not sure your comment is a question or not.

My current use case is to inject javascript, but it could be any sort of page content modification I guess.

**Comment by gauntface** [comment]
Just o update - this is unlikely to get addressed in V3 so will leave as a discuss label - but it's unlikely to get attention until V3 is launched, sorry about that.

**Comment by weeblr** [comment]
Thanks for the update. Was not aware of v3 nearing release. Is there a place where I can follow progress and see announcements, a specific github issue?)
