### ISSUE TITLE
Integration tests to cover bundling scenarios

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#793]
@philipwalton You mentioned you'd be interested in adding integration tests (or that's the impression I got).

These tests could be simple or crazy so below is a set of ideas for what I think could be integration tests to make sure we work with the above tools.

- [ ] A smoke test for each module. Make sure each individual module can be imported and built with Rollup and WebPack.
- [ ] A smoke test for each module + custom process.env.NODE_ENV entries (i.e. what happens is it's not set vs when it's set to 'production' vs something else built with Rollup + replace plugin and WebPack + DefinePlugin.
- [ ] A smoke test that pulls in every module and builds with Rollup and WebPack.
- [ ] Explore use on main, module and browser to ensure best builds (Unsure how WebPack decides what is used and how).

```json
{
  "main": "path/to/entrypoint", // CommonJS or ESM (i.e. require(‘some-package’)) depending on node version
  "module": "path/to/entrypoint.mjs", // ESM - ES Modules (i.e. import thing from ‘thing’) used by webpack and Rollup
  "browser": {
    "path/to/entrypoint.js": "./path/to/entrypoint.js",
    "path/to/entrypoint.mjs": "./path/to/entrypoint.mjs"
  }
}
```

Let me know if this sounds sane, or completely different to what you had in mind.

**Comment by philipwalton** [comment]
Note, the webpack builds I used to test there are referenced here: https://github.com/GoogleChrome/workbox/issues/910#issuecomment-337284267

**Comment by gauntface** [comment]
These tests should also check file sizes if possible (i.e. make sure the treeshaking is working and we don't regress (if possible))

Closing #946 in favor of this.

**Comment by gauntface** [comment]
## Rollup Testing

Config:
```javascript
// rollup.config.js
import resolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';

export default {
  input: 'main.js',
  output: {
    name: 'precachingdemo',
    file: 'build/bundle.js',
    format: 'iife'
  },
  plugins: [
    resolve({
      // use "module" field for ES6 module if possible
      module: true, // Default: true

      // use "jsnext:main" if possible
      // – see https://github.com/rollup/rollup/wiki/jsnext:main
      // jsnext: true,  // Default: false

      // use "main" field or index.js, even if it's not an ES6 module
      // (needs to be converted from CommonJS to ES6
      // – see https://github.com/rollup/rollup-plugin-commonjs
      main: true,  // Default: true

      // some package.json files have a `browser` field which
      // specifies alternative files to load for people bundling
      // for the browser. If that's you, use this option, otherwise
      // pkg.browser will be ignored
      browser: true,  // Default: false

      // not all files you want to resolve are .js files
      // extensions: [ '.js', '.json' ],  // Default: ['.js']

      // whether to prefer built-in modules (e.g. `fs`, `path`) or
      // local ones with the same names
      // preferBuiltins: false,  // Default: true

      // Lock the module search in this path (like a chroot). Module defined
      // outside this path will be marked as external
      // jail: '/my/jail/path', // Default: '/'

      // If true, inspect resolved files to check that they are
      // ES2015 modules
      // modulesOnly: true, // Default: false
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify('production')
    })
  ]
};
```

Run command:
```
rollup -c ./rollup.config.js
```

Should do with production, dev. Need to document that replace is **REQUIRED** otherwise the sw will error on process no existing.

## Web Pack

webpack.config.js
```
const path = require('path');

module.exports = {
  entry: './src/main.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'build')
  }
};
```

Run command
```
webpack --config webpack.config.js --mode development
```

**Comment by jeffposnick** [comment]
We're effectively covering this in the `generateSW` integration tests now, which end up using Rollup for bundling under the hood.
