### ISSUE TITLE
workbox-webpack-plugin + workbox-precaching

### ISSUE THREAD

**Issue by frlinw** [GoogleChrome/workbox#794]
**Library Affected**:
workbox-build

**Feature Request Description**:
workbox-webpack-plugin compatible with workbox-precaching.

Currently, because of injection process (searching for .precache) https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/inject-manifest.js#L57 you have to use workbox-sw (47kb) even if you just need the workbox-precaching lib (22kb)

**Comment by prateekbh** [comment]
@gauntface it'd be great if we can split this up.
`SwPrecacheWebpackPlugin` already does this

**Comment by gauntface** [comment]
We will hopefully have a much nicer story for in you V3.

If webpack could generate just the manifest file, you'd be able to import that in and use just the workbox-precaching module.

cc @goldhand just as an FYI. @jeffposnick is starting to work on the workbox-build v3 stuff, so hopefully we can start enabling the next webpack version and take advantage of some of the V3 plans soon.

**Comment by goldhand** [comment]
Webpack can generate the manifest file! I have that working and meant to jump on the wednesday convo to chat a little. I've been out of the loop for a little but hoping to get caught up with the plans soon!

That said, not sure exactly what the context of this issue is.

**Comment by jeffposnick** [comment]
I believe that https://github.com/GoogleChrome/workbox/issues/933 tracks this in a more general form.
