### ISSUE TITLE
Serve cached navigationRoute only when offline

### ISSUE THREAD

**Issue by codepunkt** [GoogleChrome/workbox#796]
**Library Affected**:
*workbox-sw*

**Issue or Feature Request Description**:
I server render a react-based SPA. To be able to use the app offline, my build process generates an offline.html, which is a basic app shell. All JavaScript files required to run the app are cached in my service worker (automatically generated by the webpack plugin in injectManifest mode) as well as the offline.html file.

```javascript
workboxSW.router.registerNavigationRoute('/offline.html')
```

With this in my service worker script, the app works offline.
What doesn't work is my server side rendering when the user is online because this leads to the cached offline.html being served regardless of online or offline.

What i would like is the offline.html only being served when offline, otherwise always getting the non-cached server-rendered version for the navigation route that was navigated to.

I've played around with handlers and strategies, but couldn't get this to work. I suppose this is possible - can you give me a hint?

**Comment by jeffposnick** [comment]
This is closely related to https://github.com/GoogleChrome/workbox/issues/438

It's come up a few times in the past, and I'm going to re-open that issue. Feel free to chime in there.

**Comment by codepunkt** [comment]
@jeffposnick Is this actually the same thing?

What i want is to **only** serve my app shell from cache when offline, otherwise **always** use the network. On **all** navigation routes.

**Comment by jeffposnick** [comment]
You can accomplish what you want by using a somewhat modified version of the sample from #438. I think this is what you're describing—always attempt to use a network-retrieved version of `/app-shell.html` for navigations, and if that fails, return the cached `/offline.html`.

```js
const matcher = ({event}) => event.request.mode === 'navigate';
const handler = () => fetch('/app-shell.html').catch(() => caches.match('/offline.html'));

workboxSW.router.registerRoute(matcher, handler);
```

I'll still use #438 to track making this sort of thing more automatic.

**Comment by codepunkt** [comment]
@jeffposnik Great, that helps a lot! To me, this wasn't obvious by reading the documentation and examples.

This is how i got it to work with server side rendering.
```javascript
workboxSW.router.registerRoute(
  ({ event }) => event.request.mode === 'navigate',
  ({ url }) => fetch(url.href).catch(() => caches.match('/offline.html'))
)
```
