### ISSUE TITLE
Create a styleguide for our public API

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#799]
**Library Affected**:
*all*

We need to decide on, for instance, positional vs. desctructured parameters for specific types of methods.

It would also be good to document our naming conventions.

**Comment by jeffposnick** [comment]
WIP: https://docs.google.com/document/d/1YQFbCIAkN2mxROLbAG_sariUUx21jkAhCErbUdw98mY/edit

**Comment by gauntface** [comment]
Everyone should be able to edit / comment.

I took a first pass, take a look and see what you think.

**Comment by jeffposnick** [comment]
👍  to your first pass. Seems like a good approach.

**Comment by gauntface** [comment]
Moved to wiki:
- Styleguide: https://github.com/GoogleChrome/workbox/wiki/V3-:-Styleguide
- Node Support: https://github.com/GoogleChrome/workbox/wiki/V3-:-Node-Support
