### ISSUE TITLE
V3 Cache Naming

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#800]
Generally the cache naming situation in Workbox is a little confusing, so hopefully this can be tidied up a little in v3.

Current thinking is that defaults should be sane to begin with an easily altered.

```javascript
import core from 'workbox-core';

// Getter that returns {precache: 'precaching', runtime: 'runtime', prefix: 'workbox'}
console.log(core.cacheNames);
```

In the above example, the cache names would result in:
- **Precaching Cache**: workbox-precaching
- **Runtime Cache**: 'workbox-runtime

If the user wanted to customise these defaults, they could do something like:

```javascript
core.cacheNames = {precache: 'install', runtime: '', prefix: 'my-app'};
```

- **Precaching Cache**: my-app-install
- **Runtime Cache**: my-app

They could then use a custom cache name like:

```javascript
workboxSW.strategies.cacheFirst({
    cacheName: 'images'
});
```

Which would then use `my-app-images` for a change name.

The major risk with this is if someone alters this at some point after the caches have started being used. But for that scenario we should be able to detect when the service worker has installed and throw in the setter.

In terms of implementation, me and @jeffposnick discussed how we should have a single function that would handle getting the correct cachename, since users will be able to define custom cache names. We could do something along the lines of:

```javascript
core._private.cacheNameProvider.getPrecacheName(userCacheName);
core._private.cacheNameProvider.getRuntimeName(userCacheName);
```

In the above, if a user defined nothing (i.e. `undefined`) the above would grab the current prefix and precaching  or runtime name and return those joined with '-'. 

If a userCacheName was defined, it would return the current prefix joined with the cache name '-'.

@philipwalton @jeffposnick @addyosmani

**Comment by jeffposnick** [comment]
Thanks for writing this up, Matt! Generally on board, with a few nits:

- We've previously included the SW scope when coming up with a composite cache name (the values returned by `getPrecacheName()` and `getRuntimeName()`), and that plays an important role in segregating cached values for different PWAs running on the same origin. We should continue doing that.
- If the developer explicitly sets a cache name while configuring a strategy, I think we should use that as-is, without appending a prefix, like we do today. I think the developer expectation is that if I pass in a string as the `cacheName` when configuring a strategy, I should be able to pass in that same string value to `window.caches.open()` and get a reference to the underlying cache outside of the SW context. (`core._private.cacheNameProvider` is not going to be available in the `window` context.)
- Given that, I think we can simplify `core._private.cacheNameProvider` so that it just exposes two getters, one for the effective precache name, and one for the effective **default** runtime cache name.

**Comment by philipwalton** [comment]
I think a common developer customization would be to use only a single cache, and in this proposal it seems like doing that would be awkward.

AFAICT, you'd either have to do:

```js
core.cacheNames = {precache: 'cache', runtime: 'cache', prefix: 'workbox'};
```

Or manually specify a cache name with each strategy:

```js
workboxSW.strategies.cacheFirst({
    cacheName: 'workbox-cache'
});
```

But both of these feel a bit awkward to me.

I also think it's not great that `workbox-core` has runtime and precache-specific config in it, why wouldn't those live in their respective packages?

What if `workbox-core` defined a default cache name, then individual packages could either use that or define their own, and then individual caching strategies could also override the package defaults. To me this would offer the most flexible customizations with the most sensible defaults.

**Comment by jeffposnick** [comment]
I'm against making it easy for developers to combine precached and runtime cached resources in the same cache.

Precached resources have their own expiration and update lifecycle, and runtime caches have a separate, optional model for expiration via `maxEntries` and `maxAge`. If you start Having a `maxEntries`-based expiration that ends up deleting precached resources wouldn't be a great situation.

Is there a real need for a single cache that I'm overlooking?

**Comment by philipwalton** [comment]
I'm not super familiar with either of these packages, so take everything I say with a grain of salt, but my primary concern is that by having separate caches, the same resource might end up in both in some cases (if this isn't true, let me know).

**Comment by jeffposnick** [comment]
The most common use case would be something like:

```js
workboxSW.precache([manifest]);
workboxSW.routing.registerRoute(
  /.jpg$/,
  new workboxSW.strategies.networkFirst()
);
```

If there's a `.jpg` URL that's listed in `manifest`, then a `fetch` for that URL would end up being responded to by the precache handler, and would not "fall through" to the runtime caching handler below. So it would not end up in the runtime cache.

There are edge cases where you manually manipulate the caches and you could end up caching things twice, but for the use case we try to promote, it's not a developer concern.

**Comment by gauntface** [comment]
Ok after a few conversations:

Default output would be
```javascript
import core from 'workbox-core';

// Getter that returns {
//    precache: 'precaching',
//    runtime: 'runtime',
//    prefix: 'workbox',
//    suffix: 'https://origin.com/scope/'
// }
console.log(core.cacheNames);
```

In the above example, the cache names would result in:

**Precaching Cache**: workbox-precaching-https://origin.com/scope/
**Runtime Cache**: workbox-runtime-https://origin.com/scope/

If the user wanted to customise these defaults, they could do something like:

```javascript
core.cacheNames = {precache: 'install', runtime: '', prefix: 'my-app', suffix: ''};
```
Precaching Cache: my-app-install
Runtime Cache: my-app

This mains developers who want to just customise the caches for individual locahost projects could just do:

```javascript
core.cacheName = {prefix: 'awesome-proj'};
```

And it'll be unique for that app vs some other app using Workbox.

User cache names will be un-touched.

For getting the cachename, we can just require everything to go through:
```
core._private.cacheNameProvider.getPrecacheName(userCacheName);
core._private.cacheNameProvider.getRuntimeName(userCacheName);
```

If a `userCacheName` is provided it will just be returned as is. (This at least gives up a common place to add logic and / or error check if we want to).

**Comment by gauntface** [comment]
I am assuming this is preferable over any of these options:

```javascript
core.setCachePrefix(...), core.setCacheSuffix(), core.setPrecacheName(), core.setRuntimeCacheName()

core.cacheNames.prefix = '';
core.cacheNames.suffix = '';
core.cacheNames.precache = '';
core.cacheNames.runtime = '';
```

If we can support the last one it would be nice.

**Comment by gauntface** [comment]
Just had another thought, if the developer just wanted the cache name, (i.e. I want to get the precache or runtime cachename, the above doesn't really help), should we instead have

```
// Prints {precache: 'workbox-precaching-https://...../', runtime: 'workbox-runtime-https://...../'}; 
console.log(core.cacheNames);
```

Then change the setting to a more explicit function:

```javascript
core.updateCacheDetails({prefix: '...', suffix: '...', precache: 'precaching', runtime: 'runtime'});
```

Then using cache names can be:

``` javascript
const cacheToUse = userCacheName || core.cacheNames.runtime.
```
