### ISSUE TITLE
compatibility with webpack.DefinePlugin

### ISSUE THREAD

**Issue by elf-pavlik** [GoogleChrome/workbox#802]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
node (webpack build)

**Issue or Feature Request Description**:

Webpack provides https://webpack.js.org/plugins/define-plugin/ to *create global constants which can be configured at compile time*. It seems that workbox-webpack-plugin doesn't use it when processing service worker source file `swSrc` and generating `swDest`.

I used workbox-webpack-plugin 2.0.1

**Comment by gauntface** [comment]
@elf-pavlik What would you expect it to do?

**Comment by elf-pavlik** [comment]
Given in `webpack.config.js`

```js
const escapeStringRegExp = require('escape-string-regexp')
const config = require('./config.json')
const SRC_DIR = 'src'
const DIST_DIR = 'dist'

module.exports = {
  // ...
  plugins: [
    new webpack.DefinePlugin({
      ESCAPED_SERVICE_URL: JSON.stringify(escapeStringRegExp(config.service))
    }),
    new WorkboxPlugin({
      globDirectory: DIST_DIR,
      globPatterns: ['**/*.{html,js,css}'],
      swSrc: path.join(SRC_DIR, 'service-worker.js'),
      swDest: path.join(DIST_DIR, 'service-worker.js')
    })
  ]
}
```
I thought `ESCAPED_SERVICE_URL` in the *swSrc* file would get substituted with value provided to DefinePlugin in generated *swDest* file. On second thought I very likely made wrong assumption, should I create qestion on StackOveflow instead.

**Comment by goldhand** [comment]
@elf-pavlik Workbox isn't using webpack to compile the service worker so any webpack related plugins / config will likely miss the service worker (unless it's explicitly passed to workbox build via the WorkboxWebpackPlugin).

**Comment by gauntface** [comment]
@goldhand would your work current set of suggestions work here?

**Comment by elf-pavlik** [comment]
> Workbox isn't using webpack to compile the service worker so any webpack related plugins / config will likely miss the service worker (unless it's explicitly passed to workbox build via the WorkboxWebpackPlugin).

I didn't understand the *unless it's explicitly passed...* part. Can I define a chunk in webpack which will have the source service worker file (which I currently pass to WorkboxBuildWebpackPlugin via `swSrc`) as its entry point and this way `webpack.DefinePlugin` will apply to that source file.
I noticed in *sw-precache-webpack-plugin* config [importScripts](https://github.com/goldhand/sw-precache-webpack-plugin#importscripts-usage-example) option which supports `chunkName` (and also works when using [chunkhash]).

For my particular use case (including URL from app config file in the definition of a runtime caching route), having similar *importScripts* option in workbox-build might allow me to define that route in a dedicated chunk and just register it in the source service worker passed to workbox-build in webpack plugin as `swSrc`. Something in lines of:

```js
    new WorkboxPlugin({
      globDirectory: DIST_DIR,
      globPatterns: ['**/*.{html,js,css}'],
      swSrc: path.join(SRC_DIR, 'service-worker.js'),
      swDest: path.join(DIST_DIR, 'service-worker.js'),
      importScripts: [
        { chunkname: 'workbox' },
        { chunkname: 'dataServiceRoute' }
      ]
    })
```

Actually having *importScripts* available in workbox-build config, I would not need the `swSrc` any more which would allow me to use `runtimeCaching` config option directly in webpack.config.js (having now generateSW() instead of injectManifest())

```js
    new WorkboxPlugin({
      globDirectory: DIST_DIR,
      globPatterns: ['**/*.{html,js,css}'],
      runtimeCaching: [ /* ... */ ],
      swDest: path.join(DIST_DIR, 'service-worker.js'),
      importScripts: [
        { chunkname: 'push-notifications' }
      ]
    })
```

**Comment by goldhand** [comment]
@elf-pavlik I just meant config that was passed inside the plugin configuration. Other plugins won't affect the WorkboxPlugin because it is not in webpack.
Thats a good point with the `importScripts`. I can see a use for that, especially for assets that use `chunkHash`

**Comment by gauntface** [comment]
Unlikely to make it for v3 but would be good to address after.

**Comment by gauntface** [comment]
@jeffposnick @goldhand is this still an issue with V3?

**Comment by elf-pavlik** [comment]
> Thats a good point with the `importScripts`. I can see a use for that, especially for assets that use `chunkHash`

If you decide to add `importScripts` support for webpack chunks, it may make sense to open new issue or re-open #584
Soon I may need to share some chunks between service worker and the main app so it may provide another use case that could need such future.

This issue here probably should stay closed as it started with my misunderstanding of how WorkboxPlugin plays together with the rest of webpack build.

**Comment by jeffposnick** [comment]
Let's use https://github.com/GoogleChrome/workbox/issues/933 as a general issue for tracking opting-out of using the CDN copy of Workbox in favor of using custom Workbox bundled code.

**Comment by ondrejrohon** [comment]
I'm using workbox-webpack-plugin 3.6.3 and having the same issue. Variable from webpack define plugin is not replaced as expected, although I found recommendation to use it together here: https://stackoverflow.com/questions/48398658/read-env-variable-from-service-worker-file-using-workbox
