### ISSUE TITLE
Add docs on how to ignore url querystring from cached urls when using workbox

### ISSUE THREAD

**Issue by jecky011** [GoogleChrome/workbox#810]
Is there a way to ignore query string "?screenSize=" from below registered route using workbox! If I can use regex how would i write it in below scenario? Basically, I am looking to match the cache no matter what is the screenSize querystring.

```
workboxSW.router.registerRoute('https://example.com/data/image?screenSize=980',

workboxSW.strategies.cacheFirst({
    cacheName: 'mycache',
    cacheExpiration: {
        maxEntries: 50
    },
    cacheableResponse: {statuses: [0, 200]}
})
);
```

**Comment by jeffposnick** [comment]
See https://stackoverflow.com/a/46283973/385997

**Comment by addyosmani** [comment]
@gauntface @jeffposnick Do we want to make a call for how much docs posted to SO should be brought back into the core docs for the project? It might be sufficient to just evaluate this on a case by case basis. Asking in case we need to do a pass on the answers already posted for docs consideration.

**Comment by gauntface** [comment]
I have been re-opening stuff like this so that we do get something on `/web` because things like this (in my mind) are common enough / easy enough to miss if we don't consolidate.

**Comment by gauntface** [comment]
Added a note to document this along with how to use plugins: https://docs.google.com/document/d/1Qye_GDVNF1lzGmhBaUvbgwfBWRQDdPgwUAgsbs8jhsk/edit?usp=sharing
