### ISSUE TITLE
v3 Testing Pain Points

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#814]
Some random pain points that I've found when writing tests of browser packages in v3:

1. We're leaking `global` state across tests when we run `Object.assign(global, makeServiceWorkerEnv()))` to initialize the service worker mock environment. This has lead to oddness like https://github.com/GoogleChrome/workbox/pull/798#issuecomment-331281703, where tests might succeed under `gulp tests`, but fail under `gulp tests --package='something'`, since the *something* package may end up with different `global` state in each of those scenarios.

2. We need to run our test suites under `NODE_ENV = 'production'` and `NODE_ENV = 'development'` in order to achieve proper code coverage, but there's no automated solution to do this. The manual approaches that I've tried are not ideal, and involve copying and pasting a lot of of test cases, and remembering to save and restore the previous `NODE_ENV` value so as not to leak state changes across tests.

3. I'm still facing a strange issue where my `.mjs` imports only work when done inside a top-level `(async () => {})()`, and not when done inside of a `before(async function() {})`. I think this boils down to `nyc --require @std/esm` behaving in an unexpected way, but I am not clear on the root cause.

I'll try to help find solutions to all of these, but I wanted to get them recorded somewhere to open it up to a wider audience.

**Comment by gauntface** [comment]
1.) What would be the best approach for fixing this? We "could" add mocks to a single file that init's them and add them to the require list like we do with @std/esm. This would at least make it consistent and remove any boilerplate. thoughts?

2.) We can run the test suites twice and force if statements for every test case that deviates? Pros for this is that every test is run against both with zero thought. Cons are each test case is handling two scenarios and we will run tests where the expected result will be the same. Would you like this? Any alternative approaches?

3.) I'll dig into this now cos it's slightly worrying.

**Comment by jeffposnick** [comment]
The `v3` tests are currently run via

```sh
nyc --require @std/esm --reporter=lcov --reporter=text mocha "./test/*/node/**/*.{js,mjs}"
```

kicked off via a very lightweight `gulp` task.

How would you feel if we moved back to the model in `v2` where the `gulp` task did more work in establishing global state (both `NODE_ENV` and `makeServiceWorkerEnv()`) and then kicked off the test suite twice, and we also adopted [`mocha-assume`](https://github.com/dtanzer/mocha-assume) to specify which subset of tests in a given suite are only valid for a given `NODE_ENV`?

```js
const assuming = require('mocha-assume').assuming;

describe('Blah Tests', function() {
  it('should always do', function() {});
  assuming(process.env.NODE_ENV === 'development').it('should throw', function() {});
});
```

We could save the `process.env.NODE_ENV` comparison's result in global ` production` and `development` booleans, and then write `assuming(production).it('blah', function() {});`

**Comment by gauntface** [comment]
Personally I want to move away from that model. Everything in that space ended up in a fairly complex mess of stuff that was difficult to reason with and not particularly friendly. Phil's move to bundled tests ended up confusing things further.

Mocha is great as a tool to manage this stuff, but when you deviate, the API is really not friendly to work with either.

I'm fine with moving to running the tests twice, once for dev, once for prod and if someone wants to use mocha-assume to restrict the test to run ONLY in certain values, I think that seems like a good fix to avoid the if statements in each test.

**Comment by gauntface** [comment]
From meeting - Jeff to try rolling in a gulp solution.

**Comment by gauntface** [comment]
Phil fixed it. There is more tidy up to do, but it's optional and can be done over time.
