### ISSUE TITLE
staleWhileRevalidate called only once on image

### ISSUE THREAD

**Issue by diegocom** [GoogleChrome/workbox#817]
**Library Affected**:
workbox-sw 2.0.0/2.0.2

**Browser & Platform**:
Google Chrome v60.0.3112.113 for Windows
Google Chrome v61.0.3163.98 for Android
Internet Samsung v5.4.21.54 for Android

**Issue or Feature Request Description**:
When I try to implement the assets caching I see that the staleWhileRevalidate method on image is called only once in the page for each image, also if I try to refresh multiple times. I need to close the webpage and when I reopen it the image is updated correctly. It's normal that it work in this way?
When the PWA is added to home screen the images is never updated.
I have posted a more detailed question on stackoverflow [HERE](https://stackoverflow.com/questions/46413305/workbox-stalewhilerevalidate-called-only-once-on-image)

**Comment by jeffposnick** [comment]
I've added a comment to the SO question. Let's chat there, and we can reopen this if it turns out there's an underlying bug.
