### ISSUE TITLE
Our module versioning doesn't play nicely with rc releases

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#818]
**Library Affected**:
all

I ran into some issues while cutting the `2.0.2` release, moving from `2.0.2-rc1`. The code that we we use to change the version numbers in the built module filenames prior to publishing doesn't play nicely with the `-rc1` suffix, leading to filenames like `workbox-sw.prod.v2.0.2-rc1-2.0.2-rc1.0.js` after publishing.

I manually cleaned that up and published `2.0.3` with properly versioned filenames, but it's something to fix before we do another non-numeric release.

**Comment by addyosmani** [comment]
That's super unfortunate. This is a useful gotcha to be aware of as any of the work we complete before CDS may well end up being labelled similar to the `2.0.2-rc1`/alpha/beta with similar side-effects. 

Let's see if we can fit getting a fix in for this before the next big release.

**Comment by gauntface** [comment]
Could we add this as a step that `workbox-build` adds the versioning into the filename but the built filename we share on NPM is static / left alone?

The above, while worked, didn't feel pretty and complicated the build process.
