### ISSUE TITLE
Update workbox-google-analytics to support the new gtag script

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#836]
The Google Analytics tracking snippet has changed to this:

```html
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXX-Y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXX-Y');
</script>
```

This means that to support offline analytics we'll have to cache `https://www.googletagmanager.com/gtag/js?id=UA-XXXXX-Y` in addition to `https://www.google-analytics.com/analytics.js` (since it gets downloaded as well).

The only catch here is the script URL has the tracking ID included, which means we can't just generically reference it -- we'll have to somehow figure out 1) if it's being used, and 2) what its URL is.

The resource timing API is probably the most likely solution, but further investigation is needed to determine how widely that's supported.

**Comment by jeffposnick** [comment]
Setting up a runtime caching route in the SW matching `https://www.googletagmanager.com/gtag/js` would be what I'd imagine the cleanest approach, but that would mean that the JS would only be cached on the second visit, after the SW has been installed on the first visit.

Using the Resource Timing API to solve the first-visit-pre-SW-install runtime caching story is still tracked in #368 and I still see value in solving this generically via new code that runs in the `window` context, but it's proved controversial.
