### ISSUE TITLE
Runtime caching conflicts with precache

### ISSUE THREAD

**Issue by jaspermdegroot** [GoogleChrome/workbox#839]
When runtime caching is applied to a page that is precached, that page won't work offline anymore.

This affects the workbox-sw library. Tested on Chrome 61 on MacOS.

The Progressive Web AMP codelab at https://codelabs.developers.google.com/codelabs/amp-pwa-workbox/ illustrates the issue. The homepage is precached, but if you navigate from any of the articles to the homepage while offline the homepage won't be displayed and the console shows the following error:
```
The FetchEvent for "http://localhost:8081/" resulted in a network error response: the promise was rejected.
Promise rejected (async)
_isListenerRegistered.self.addEventListener @ workbox-sw.dev.v2.0.0.js:71
```
If you visit the homepage after the SW is installed and before going offline, so the page is added to the runtime cache, the page will be displayed.

I also included a more basic test case without app shell:

[workbox-issue.zip](https://github.com/GoogleChrome/workbox/files/1352954/workbox-issue.zip)

Is this indeed a bug or is this expected behaviour and is it up to the developer to keep precached files in mind when adding routes?

**Comment by jaspermdegroot** [comment]
I just saw the `Request precached.txt` example at https://workboxjs.org/examples/workbox-sw/ which shows the following message:
```
Requesting precached.txt...
...the response is 'I'm included in the manifest passed to workboxSW.precache([]), so I'll be added to the cache automatically whenever the service worker is registered. Additionally, I'll always be served with a cache-first strategy, even though there's also a runtime caching route that matches /\.txt$/. The cache-first route that .precache() sets up always takes precedence over any runtime caching routes. '.
```
Based on this I suppose the behaviour that I noticed is a bug.

**Comment by gauntface** [comment]
@jaspermdegroot this definitely sounds like a bug to me. Will take a look later today. Thanks for raising the bug.

**Comment by jeffposnick** [comment]
This sounds like something that went amiss when we changed the code to make registering the event listener for the `Router` class opt-in.

The [code from `workbox-sw`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-sw/src/lib/workbox-sw.js#L135) that currently reads:

```js
if (handleFetch) {
  this._router.addFetchListener();
}

this._registerDefaultRoutes(ignoreUrlParametersMatching, directoryIndex);
```

needs to be switched around so that the default routes are registered first.

**Comment by gauntface** [comment]
What a short term solution be to register a two fetch handlers - one for precaching and one for routing? 

We can't reliably add precaching to be the last route registered :(

**Comment by jeffposnick** [comment]
Yeah, that would probably be the best short-term solution. I can put something together for that in v2.

See https://github.com/GoogleChrome/workbox/issues/845 about some changes we could make in v3.

**Comment by jaspermdegroot** [comment]
Thanks all for the quick response and for fixing it!

@jeffposnick - Thanks for providing a temporary workaround. However, when setting the default handler I got an error saying the handler parameter is undefined instead of a function (I did change `workbox.strategies` to `workboxSW.strategies`).

Anyway, I only precache the homepage so I will use something like this until next release:
```
workboxSW.router.registerRoute('/*', args => {
	if (args.url.pathname!='/' && args.url.pathname!='/index.html') {
		return workboxSW.strategies.networkFirst().handle(args)
	}
})
```

**Comment by jeffposnick** [comment]
Sorry, that example should have been:

```js
workboxSW.router.setDefaultHandler({handler: workbox.strategies.networkFirst()});
```

(We're in the process of moving from objects with named properties to positional properties for this sort of thing in v3, and I got confused.)
