### ISSUE TITLE
Change the order of Route evaluation in v3

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#845]
**Library Affected**:
*workbox-routing*

In v1/v2 we [gave precedence](https://github.com/GoogleChrome/workbox/blob/3861bac4a70a57a38942badbc6a9b4fd8ba0b1ed/packages/workbox-routing/src/lib/router.js#L299) to the most-recently-registered `Route` when choosing the matching `Route` in our `Router`.

This was a somewhat arbitrary choice (I can't remember the original decision) and has periodically caused confusion, and in practice, has led to issues like https://github.com/GoogleChrome/workbox/issues/839

I'm cool with switching to making the earliest-registered `Route` take precedence in v3, which would match how things work in, e.g., Express.

**Comment by gauntface** [comment]
+1. No question in my mind.

Is there anywhere we should track breaking changes like this? We could just do a markdown doc on webfundamentals workbox-v3 branch. We can all commit, it's public and will most likely be a good place to host the changelog. Thoughts?

**Comment by jeffposnick** [comment]
This was done in #854.
