### ISSUE TITLE
Only accept functions as handlers when creating Routes

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#848]
**Library Affected**:
`workbox-routing`

A brief history of the `handler` parameter that's passed to the `Route` constructor:
- Initially, it had to be an Object that had a property named `handle`, and that property was a function. This played nicely with our `workbox-runtime-caching` classes, but was a pain for anyone who wanted to write their own handler logic.
- We switched things up to support either Objects with `handle` properties **or** functions, but that led to some [messy and hard to explain code](https://github.com/GoogleChrome/workbox/blob/8dfda82f4ba8fbd5973f33425360ee3c4e250570/packages/workbox-routing/src/lib/normalize-handler.js) that normalized the input.

I'm thinking that for v3, we can just drop support for Objects with `handle` properties and only take in functions.

We could retrofit the various `workbox-runtime-caching` subclasses by adding in a factory method on the parent [`Handler` class](https://github.com/GoogleChrome/workbox/blob/8dfda82f4ba8fbd5973f33425360ee3c4e250570/packages/workbox-runtime-caching/src/lib/handler.js) that would return a function that uses [`bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to wrap the `Handler.handle()` method, which will ensure that `this` can still be used.

Thoughts?

**Comment by gauntface** [comment]
I've been thinking the same thing after working on the runtime-caching so would love for this to be the case, would also make the `Route` a little nicer passing in two functions and seeing two functions on the prototype.

**Comment by gauntface** [comment]
Also gonna steal assignment if you don't mind ;)

**Comment by jeffposnick** [comment]
Any reason to try to sneak this into the v3 release? It still could be worthwhile, but we can save some breaking changes for v4 😄

**Comment by gauntface** [comment]
Yeah I'm pro that - precaching felt a bit close to add those changes, so I'm down for that.

**Comment by jeffposnick** [comment]
We've decided not to make this change.
