### ISSUE TITLE
Mechanism for reading current build filenames/CDN strings

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#851]
**Library Affected**:
all

We should come up with some methods, perhaps part of a utility package separate from any of the modules, that could be called to return some strings related to our build/release process:

- Return the current list of supported `NODE_ENV` values (`'dev'`, `'production'`)
- Given a `NODE_ENV` value and a module name, return a URL string corresponding to the expected CDN URL.
- Given a `NODE_ENV` value and a module name, return a URL string corresponding to the expected module filename.

**Comment by gauntface** [comment]
I'll work on this after the initial PR lands.

**Comment by gauntface** [comment]
This should be all good with changes to workbox-build to get the CDN urls for a module.
