### ISSUE TITLE
Remove Router.registerRoutes()/unregisterRoutes() methods

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#856]
**Library Affected**:
*workbox-routing*

See https://github.com/GoogleChrome/workbox/pull/854#discussion_r143250798

**Comment by gauntface** [comment]
Personally I'm in favor of this, although not super strongly opinionated.

Main reason is that I'm not aware of anyone wanting or using this.

**Comment by jeffposnick** [comment]
I'll update https://github.com/GoogleChrome/workbox/pull/854 to account for that.

**Comment by jeffposnick** [comment]
This was done in #854.
