### ISSUE TITLE
DBWraper's getAll method should return a Map instead of an Object

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#857]
I discovered a nasty bug when creating an object store with `autoIncrement: true`. I'd add new items to the store, and then when I'd use the keys returned by `getAll()` to reference them later, they couldn't be found. I also couldn't delete items using the keys returned by `getAll()`. At first I thought it might be a bug with the `shelving-mock-indexeddb` package, but I experienced the issue even when running it in the browser.

After some debugging, turns out the issue was `autoIncrement: true` uses numeric keys, but when converting them to Object keys, they were stringified, and matching keys in IndexedbDB, type matters.

An easy solution to this would be to return a `Map` instead of an `Object`. Then it wouldn't matter what type the key is.

I'm going to make this change as part of my background sync PR, but I wanted to open this issue so it's clear why.

**Comment by jeffposnick** [comment]
Thanks for digging into this, Phil. `DBWrapper` was initially conceived as a really naive promise-based interface over IDB, so don't be surprised if we need to extend it in future PRs.

The trick is to identify when we've got to the point where we've extended it to the point where it's effectively https://www.npmjs.com/package/idb

**Comment by gauntface** [comment]
Agreed - the current state is minimal.

I'm not against returning a map, although it urks me that you can't map over a map, but thats minimal. Make the change that you need for this.

**Comment by gauntface** [comment]
Landed.

**Comment by addyosmani** [comment]
\o/

**Comment by philipwalton** [comment]
Note, this is no longer needed after https://github.com/GoogleChrome/workbox/pull/968.
