### ISSUE TITLE
lerna changes in v3

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#859]
**Library Affected**:
*all*

Spinning off some of the conversation from https://github.com/GoogleChrome/workbox/pull/858:

We probably should move to the `lerna` mode where each package gets the same version number, even if there are no changes, since otherwise the CDN URLs are going to be impossible to infer.

We need to change the publishing pipeline to break things into at least three steps:

1. `lerna` publishes to a tagged GitHub release.
2. We upload to the CDN.
3. We publish to `npm`.

If any of the earlier steps fail, we don't move on to the next step.

We're already breaking up the GitHub and `npm` steps in `lerna`'s pipeline in v2, so that won't be a major change.

**Comment by gauntface** [comment]
I don't think we need to do anything (i.e. I believe the current pipeline will work) the only question in my head if whether the lerna pipeline will provide us with a sane way to replace the correct version numbers before publishing (Could be a post publish step).

The flow would be (with required changes in bold):

1. Lerna builds and bumps the version
    1. If lerna bumps the versions before building, we inject version information for all modules during build
    1. If lerna bumps the versions after building, we can have a postpublish step to inject version information for all modules.
1. Lerna will create the git tag and push this to the workbox repo.
1. The gulp publish-github will run if everything was successful and create a draft release with uploaded archive files of the built module files.
1. The gulp publish-cdn will run if everything was successful and publish the browser builds to the CDN under the git tag version.

This means NPM modules can be pushed with seperate versions (avoiding the churn) and we have a reliable new version number to use for the CDN.

**Comment by gauntface** [comment]
This should be all good to go with changes to use "version" npm step.
