### ISSUE TITLE
In Routing, Seperate handleEvent from canHandleEvent.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#861]
At the moment there is a method in the Router class that returns a promise or null depending on whether the router can respond to the request or not.

```javascript
self.addEventListener((event) => {
    const responsePromise = router.handleEvent(event);
    if (responsePromise) {
        return event.respondWith(responsePromise);
    }
    // TODO Something else
});
```

It might be nice to have a method that returns a boolean instead of a Promise or null.

```javascript
self.addEventListener((event) => {
    if (router.canHandleEvent(event)) {
        return event.respondWith(router.handleEvent(event));
    }

    // TODO Something else
});
```

This way, handleEvent() could always return a Promise and reject if the event can't be handled.

**Comment by jeffposnick** [comment]
The current implementation means that you only need to iterate through all of the routes looking for a match once, and if there is a match, the code returns the relevant handler.

If we broke things up into two separate methods, then we'd end up having to iterate through all the routes twice—once to return `true`/`false`, and then again to find the relevant handler.

Route iteration shouldn't be that expensive, but I'd like to hear more about the advantages of breaking this up into two steps to justify that extra work. The `responsePromise` (effectively the return value of the handler) can already reject if the request can't be handled, which seems similar to what you're proposing.
