### ISSUE TITLE
workbox-precaching Ability to differentiate between new and updated urls.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#875]
workbox-precaching in v3 doesn't differentiate between an updated entry and a completely new entry. Would be nice to be able to log these details, but not vital.

**Comment by jeffposnick** [comment]
I believe this is covered sufficiently by https://github.com/GoogleChrome/workbox/blob/a1e3c3164dad50d0c5f48e20b3ba5dfddebd549b/packages/workbox-precaching/controllers/PrecacheController.mjs#L196-L198

No one's asked for more details, so I'm going to close.
