### ISSUE TITLE
workbox-build: generate minified output?

### ISSUE THREAD

**Issue by UltCombo** [GoogleChrome/workbox#900]
**Library Affected**:
workbox-build, workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Hello, I would like a way to emit minified output from workbox. I see the libraries already have a minified production version, but it seems there's no option to minify the output from workbox-build.

I'm using the Workbox Webpack plugin specifically, but I believe this option could be useful for the whole ecosystem.

**Comment by gauntface** [comment]
The webpack plugin should fit in with the build pipeline a little better in V3.

@jeffposnick, @goldhand  do either of you know if this would be fixed by your changes?

**Comment by jeffposnick** [comment]
This functionality is not currently in v3. It's worth keeping open to track the request. (And PR contributions are welcome!)

**Comment by gauntface** [comment]
FYI: I'm not suggesting we build minification into workbox-build, just that we should work with a webpack setup that has minification.

**Comment by UltCombo** [comment]
> should work with a webpack setup that has minification.

👍 
Currently, my build script does a second Webpack run configured specifically to minify the generated service worker from the first run. Not ideal, but it suffices for the time being.

**Comment by prateekbh** [comment]
>FYI: I'm not suggesting we build minification into workbox-build, just that we should work with a webpack setup that has minification.

need to check the current code. But in case we're still listening to `emit` event from webpack, this might need some substantial work

**Comment by gauntface** [comment]
@UltCombo is there any chance you have an example webpack config that should result in minified output?

**Comment by dyaa** [comment]
@all Any updates on this?

**Comment by jeffposnick** [comment]
This is now possible via `terser` starting in the Workbox v5 alphas, when `mode: 'production'`:

https://github.com/GoogleChrome/workbox/blob/cff916d997600489ba48728be9ec33b28f745c6b/packages/workbox-build/src/lib/bundle.js#L50-L59
