### ISSUE TITLE
Self-executing code breaks tree shaking

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#909]
We have self-executing code in several of our modules, and as a result our bundles are much bigger than they need to be.

For example, if I create a file that just imports `LOG_LEVELS` from `workbox-core` and runs it through rollup, I'd expect a very small output. Consider this example:

```js
import {LOG_LEVELS} from 'workbox-core';

console.log(LOG_LEVELS);
```

But instead of just seeing the `LOG_LEVELS` code, I get a very large output that includes stuff from `./workboxCore.mjs`, `'./models/cacheNames.mjs`, and `./utils/indexedDBHelper.mjs`.

After digging around for a bit, I realized it's because `./workboxCore.mjs` and `./utils/indexedDBHelper.mjs` contain self-executing code and thus cannot be fully tree-shaken.

To see this in action, change the exports in `./workboxCore.mjs` and `./utils/indexedDBHelper.mjs` from this:

```js
// ./workboxCore.mjs
export default new WorkboxCore();
```

```js
// `./utils/indexedDBHelper.mjs`
export default new IndexedDBHelper();
```

To this:

```js
// ./workboxCore.mjs
export default WorkboxCore;
```

```js
// `./utils/indexedDBHelper.mjs`
export default IndexedDBHelper;
```

And now the bundle rollup produces only contains this:

```js
var LOG_LEVELS = {
  debug: 0,
  log: 1,
  warn: 2,
  error: 3,
  silent: 4,
};
console.log(LOG_LEVELS);
```

@gauntface and @jeffposnick, I know there's been discussion around having default exports that "do the right thing", but I think we should rethink anything in that category that involves self-executing code. I don't think it's worth it if it prevents effective tree-shaking.

**Comment by gauntface** [comment]
Just raise a PR and we'll deal with problems as they come. I know Jeff has never liked this pattern and the only reason it exists is to ensure singletons.

**Comment by gauntface** [comment]
We did a lot of refactoring after this issue was raised to help accomodate this so I don't think it's an issue. We have a seperate issue open for adding an integration test that proves whether we do the right thing or not and until that's done we can't prove if we've fixed this issue or not so closing for now as the initial work should have fixed this.
