### ISSUE TITLE
Certain patterns break tree shaking

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#910]
For example, if I have the following file and run it through rollup, I get very small results (assuming #909 is fixed):

```js
import {_private} from 'workbox-core';

throw new _private.WorkboxError('foo');
```

But if I use destructuring and change my file to this (so I don't have to write `_private` everywhere), I get tons of code:

```js
import {_private} from 'workbox-core';

const {WorkboxError} = _private;

throw new WorkboxError('foo');
```

Basically everything on the `_private` namespace is included. It seems that rollup isn't able to do tree-shaking in this case.

I'm not sure what the best solution to this is (arguably it's a bug in rollup), but here are some things I think we could try:

- remove the `_private` namespace and export everything directly from `workbox-core` (maybe use an underscore prefix).
- somehow enforce we always use the full namespace (seems hard).
- write tests to assert the bundle only contains what we expect, so this kind of thing doesn't pop up in the future.

**Comment by gauntface** [comment]
Can you write a failing test so we don't regress?

Does it make sense to just allow us to do:

```
import {WorkboxError} from 'workbox-core/_private.mjs';
```

**Comment by gauntface** [comment]
So after starting to make these changes, I recalled why _private exists at all.

Essentially, it means there is an easy conversion from the files to workbox namespace.

We could do a few things:

1. Flat the file structure so there are no directories - everything would need to be exposed on the top level export.

1. We change our file structure to match the expect exports and find some way of enforcing that structure, for example:

    - `import core from 'workbox-core'` > `const core = workbox.core`
    - `import logger from 'workbox-core/utils/logger.mjs'` > `const logger from workbox.core.utils.logger`
    - `import logger from 'workbox-core/_private/logger.mjs` > `const logger from workbox.core._private.logger`

1. We could allow `<module name>/_private.mjs` and only that file and have a rule that converts to the browser namespace.

    - `import logger from 'workbox-core/_private.mjs'` > `const logger = workbox.core._private.logger`

I'm probably in favor of option 3 if it'll fix this problem (Allow specific _private file). Reasoning being flattening the file structure (option 1) will just be frustrating if any modules grow in size. Option 2, would work, but would be a maintenance nightmare unless rollup has some build process along the lines of - export all files in a namespaced way that matches the file structure.

**Comment by gauntface** [comment]
I've done a check test for option 3 in branch 'v3-private-test' just to see if this will actually tree shake anything.

**Comment by philipwalton** [comment]
Here's the `rollup.config.js` file I was using:

```js
const resolve = require('rollup-plugin-node-resolve');
const replace = require('rollup-plugin-replace');
const uglifyPlugin = require('rollup-plugin-uglify');
const {minify} = require('uglify-es');

const plugins = [
  resolve(),
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  }),
];

if (process.env.NODE_ENV == 'production') {
  plugins.push(uglifyPlugin({}, minify));
}

module.exports = {
  input: './packages/workbox-background-sync/tree-shake-test.mjs',
  output: {
    file: 'bundle.rollup.js',
    format: 'es',
  },
  plugins,
};
```

And here's the `webpack.config.js` file:

```js
const webpack = require('webpack');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

const plugins = [
  new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  }),
];

if (process.env.NODE_ENV == 'production') {
  plugins.push(new UglifyJSPlugin());
}

module.exports = {
  entry: './packages/workbox-background-sync/tree-shake-test.mjs',
  output: {
    filename: 'bundle.webpack.js',
  },
  resolve: {
    mainFields: ['module', 'main'],
  },
  plugins,
};
```

I put the file `tree-shake-test.mjs` inside `workbox-background-sync` so it worked with the all the npm link stuff, and I used two versions of it to test things:

Version 1:

```js
import {LOG_LEVELS} from 'workbox-core';

console.log(LOG_LEVELS);
```

Version 2:

```js
import {Queue} from './index.mjs';

console.log(new Queue('foo'));
```

**Comment by gauntface** [comment]
The _private file is no longer used and we now reference files throughout.I'm not sure if there is anything else to do for this issue so closing for now. We need the Integration Tests for prove anything here.
