### ISSUE TITLE
Do we need the browser package.json field?

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#911]
When trying to create a bundle via webpack, I noticed `imports` are always using the prod version set on `browser` in `package.json`. This doesn't seem ideal for two reasons:

- It makes it harder to debug in development
- It means the entire package is always imported, even if I'm only using a few of its exports.

If we're not using `browser` for anything else, I propose we consider removing it.

**Comment by gauntface** [comment]
In short, you're right I can't think of a good reason to keep browser around. As long as it doesn't upset WebPack, Rollup and Browserify, I think using main and module should be enough.

WebPack prefers browser over modules (unsure why) but you can still give it module code

```
{
  "main": "./lib/index",
  "module": "./lib/index.mjs",
  "browser": {
    "./lib/index.js": "./lib/index.js",
    "./lib/index.mjs": "./lib/index.mjs"
  }
}
```
(from: https://github.com/webpack/webpack/issues/5673#issuecomment-329713876)

**Comment by philipwalton** [comment]
Yeah, and you can also tell webpack what priority to consider the main/module/browser fields via the [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) option:

```js
resolve: {
  // Prefer `module` over `browser`.    
  mainFields: ['module', 'browser', 'main'],
},
```

Though this is certainly not something we'd want to force people to use for optimal builds.

**Comment by addyosmani** [comment]
Dropping seems pretty reasonable at this point.

**Comment by jeffposnick** [comment]
We still need to know the path to the browser-compatible bundled build for use in `workbox-build`, when users choose to copy over the runtime libraries locally instead of using the CDN copies.

This doesn't have to be called `browser`, though. @gauntface suggested that `main` gets updated to point to the browser-compatible build, and that's fine with me.

**Comment by jeffposnick** [comment]
As part of the change for this, I'm also going to move from `build/browser/<file>` to `build/<file>`, unless anyone has a reason why we shouldn't.
