### ISSUE TITLE
Webpack builds are bigger than they need to be

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#912]
I'm not sure the best way to deal with this issue, but when trying to create bundles via webpack (the same bundles I was testing in #909 and #910), I noticed that pretty much no tree shaking happens.

Arguably this is a webpack issue, but it *is* possible for us to address it ourselves, so I wanted to raise the issue of whether or not we should.

The solution to the problem is to have files only import the stuff they need, and to have no files export more than one thing. E.g. instead of this:

```js
import {Foo, Bar} from 'workbox-stuff';
```

We'd do this:

```js
import Foo from 'workbox-stuff/Foo.mjs';
import Bar from 'workbox-stuff/Bar.mjs';
```

While this is more work (and may or may not work with our dynamic loader for the CDN version), it *would* guarantee webpack users get the smallest possible version. As it stands today (with our current setup) they get pretty much everything.

@addyosmani I remember hearing that webpack had plans to do tree shaking when the source files were ES modules, do you know what the status of that is?

**Comment by gauntface** [comment]
This is doable and won't affect our bundle story at all.

This is the same as the rollup stuff. I'll raise a PR to remove the restriction and we can move over to this model.

Would be good to get some test that show we can build our projects just so as we move forward, we know we aren't block rollup, webpack etc from building.

**Comment by philipwalton** [comment]
I wasn't sure how easy it would be given this [current restriction](https://github.com/GoogleChrome/workbox/blob/fe217e1aaf9800c2744104ece3a0b067ef23eb2e/gulp-tasks/utils/build-browser-bundle.js#L38-L46).

Could we update `externalAndPure` to include *any* reference to any `workbox-*` module (not just starting with)? Here's a use-case from `workbox-google-analytics`:

Today we have to do this:

```js
import {Route, Router} from 'workbox-routing';
import {NetworkFirst, NetworkOnly} from 'workbox-runtime-caching';
```

But we could get better tree-shaking (at least in webpack) if we do this:

```js
import Route from 'workbox-routing/Route.mjs';
import Router from 'workbox-routing/Router.mjs';
import NetworkFirst from 'workbox-runtime-caching/NetworkFirst.mjs';
import NetworkOnly from 'workbox-runtime-caching/NetworkOnly.mjs';
```

But my worry is our browser bundles won't know what to include. Seems like they still have to include the entire module no matter what.

**Comment by jeffposnick** [comment]
As per @gauntface, the work tracked in this issue has been completed.
