### ISSUE TITLE
Router.addFetchListener() deprecated—document new behavior

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#914]
**Library Affected**:
*workbox-routing*

`Router.addFetchListener()` was in v2, and has been removed in v3 (unless that decision is reversed in https://github.com/GoogleChrome/workbox/issues/913).

We need to also explain in the docs that folks need to either create their own `fetch` handler, or use the `default` export.

**Comment by gauntface** [comment]
This is covered in the Module Docs for workbox routing that will be published here: https://developers.google.com/web/tools/workbox/modules/workbox-routing
