### ISSUE TITLE
Router and strategies classes error when used together

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#916]
**Library Affected**:
*workbox-runtime-caching, workbox-routing.*

The jsdoc for all the runtime strategy classes [`.handle()`](https://github.com/GoogleChrome/workbox/blob/fe217e1aaf9800c2744104ece3a0b067ef23eb2e/packages/workbox-runtime-caching/NetworkFirst.mjs#L79) methods say it takes a FetchEvent, but the router class calls [`handler.handle()`](https://github.com/GoogleChrome/workbox/blob/fe217e1aaf9800c2744104ece3a0b067ef23eb2e/packages/workbox-routing/Router.mjs#L140) with the object [`{url, event, params}`](https://github.com/GoogleChrome/workbox/blob/fe217e1aaf9800c2744104ece3a0b067ef23eb2e/packages/workbox-routing/Router.mjs#L140).

Which one is correct?

At the moment the router and strategies classes error when used together.

**Comment by gauntface** [comment]
From Router:

```javascript
let responsePromise = handler.handle({url, event, params});
```

It should be an object like this. Will take a look at the runtime-caching classes now.
