### ISSUE TITLE
Re-add the Mutex to CacheExpiration?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#922]
**Library Affected**:
*workbox-cache-expiration*

One thing I noticed when doing a birds-eye review of the `workbox-cache-expiration` PRs is that the [v2 behavior of using a sorta-Mutex](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-cache-expiration/src/lib/cache-expiration.js#L267) to prevent multiple concurrent runs of the cache expiration code is gone in v3.

That code is not strictly necessary, but it did solve a couple of problems:
- The v2 code was lazy about guaranteeing that we didn't accidentally end up deleting more entries than we intended, due to multiple [`findExtraEntries()`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-cache-expiration/src/lib/cache-expiration.js#L366) calls running at once.
- It wasn't "expensive" to schedule additional cache expirations, since only one would run at a time, and if multiple expirations were scheduled while there was still an ongoing run, it would only result in one additional run (using the timestamp of the latest expiration attempt as the `now` timestamp for the next run).

I think we can get away without this mutex, especially if the new v3 IDB expiration code makes proper use of transactions and its implied locking, but I wanted to raise it as a topic of discussion since I hadn't brought it up in other reviews.

**Comment by gauntface** [comment]
I'll add it back in.
