### ISSUE TITLE
Service Worker Mock Update

### ISSUE THREAD

**Issue by zackargyle** [GoogleChrome/workbox#924]
Hey folks. Just pushed an update to service-worker-mock (1.6.0) that should help decrease the custom mocks you have in codebase. Let me know if there are any upgrade issues!

## Changes

- Everything uses URL internally (self.location, request.url, etc)
- Updated FetchEvent mock to match spec
- Fixed Response.type for opaque responses
- Event was renamed to ExtendableEvent to match spec
- Header is now a proper Map
- Request extends Body and has all the corresponding methods (json, text, blob, etc)

**Comment by gauntface** [comment]
This is awesome, thanks for doing this work. Will take a look shortly.

**Comment by gauntface** [comment]
I think the release needs a patch release with dom-urls added as a dependency.

https://github.com/pinterest/service-workers/issues/60

**Comment by gauntface** [comment]
- [x] Header is now a proper Map
- [ ] Request extends Body and has all the corresponding methods (json, text, blob, etc)
    - Two errors in bg sync (Some may be errors in our tests and some may be errors in the mock):
        - SyntaxError: Failed to construct 'URL': Invalid URL
        - TypeError: request.headers.entries(...)[Symbol.iterator] is not a function
- [x] Everything uses URL internally (self.location, request.url, etc)
- [ ] Updated FetchEvent mock to match spec
    - Error in routing:
        - Because we override Request and the FetchEvent method checks for type of Request, we don't match so request just isn't set.
- [x] Fixed Response.type for opaque responses
- [ ] Event was renamed to ExtendableEvent to match spec
    - 'should add a sync event listener that replays the queue when the event is dispatched' fails assertion when using the new ExtendableEvent. No idea why.
