### ISSUE TITLE
User is notified when SW Cache update is available, decides when to update

### ISSUE THREAD

**Issue by rjsteinert** [GoogleChrome/workbox#926]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Hi there. I've been studying service workers for some time and have yet to find an example of how to prompt users if they would like to install a cached version of the site and then also prompt them to install when an update is available. Is it possible to build an app around this use case with workbox? App devs would might need an API for detecting Service Worker Cache update and then triggering it.

__User Stories__

1. On first page load, prompt the user asking if they would like to cache the app. User says yes, caching of assets begins.
2. When caching of assets completes, notify the user the app is now available offline.
3. While app is still open, detect when an update is available and prompt the user to install. User says yes, caching of assets begins.
4. When caching of assets completes, notify the user the app is now available offline and gives directions how to reload the app (close the window and reopen?).
5. Repeat 3 and 4.

**Comment by gauntface** [comment]
This is currently possible listening for the broadcast messages from workbox.

We do it on workboxjs.org: https://github.com/GoogleChromeLabs/workbox-microsite/blob/master/src/themes/scripts/sw-controller.js#L18

Would be good to write a doc on this use case as I think it'll be fairly common question.

**Comment by rjsteinert** [comment]
@gauntface Thanks for pointing that out @gauntface. I see if that example you are notifying when the application has been updated and prompting them to reload. The tricky thing I'm trying to figure out is how to prompt the user that an update is available and then only download it when the user confirms now is a good time. This is not unsimilar to the case where an Android app notifies the user an update is available and then forwards them to the Play Store to click the update button that app. 

The approach of prompting the user to reload after an update has been downloaded is nice because it's not disruptive. There are however situations where downloading an update in the background can also be disruptive, particularly in areas where bandwidth is limited either due to infrastructure or cost. For example, I only update Android Apps over Wifi because why pay for the update with Cellular data? For our business use case, we have users who are in bandwidth constrained environment like Kenya, not constrained just because of cost but also because of network infrastructure. If an application update automatically downloads when connected to the Internet, this will disrupt their business critical operation of uploading data they collected while offline.

**Comment by gauntface** [comment]
Your use case pretty quickly goes against the default service worker update cycle.

You could check your server, realise the current service worker file it out of date and I then offer the user the update path, unregister the current service worker and install the new one, this would give you the flow you want.

**Comment by rjsteinert** [comment]
Thanks for the suggestion @gauntface! I think your point is starting to gel. Perhaps a strategy like...


## Generate release on server
1. Generate Service Worker with `workbox-cli generate:sw`
1. Generate a UUID for the release
1. Move `sw.js` to `{{release UUID}}.js`
1. Create `release.json`, `["{{release UUID}}"]`

## Client install and update flow  
1. Browser hits HTML page for the first time.
1. Client code sends HTTP request to `release.json`
1. Client code registers service worker at `{{release UUID}}.js`.
1. Client notifies user the app is now available offline.
1. Client code saves away the current release UUID in something like localStorage.
1. Client code fetches `release.json` on every app start, every five minutes, or when Client detects device is back online.
1. Client compares release UUID in storage vs. the fetched release UUID.
1. Client detects new UUID, notifies user an update is available.
1. User accepts update, Client code runs service worker registration with new `{{release UUID}}.js`.

**Comment by rjsteinert** [comment]
If the above workflow makes sense I could abstract the release process into a single `workbox-cli generate:sw-release` subcommand or a third party `workbox-sw-release` command.

**Comment by gauntface** [comment]
To be honest, most developers struggle with the current lifecycle of service workers to a point that I wouldn't feel comfortable pulling this into Workbox at the moment so I'd recommend going for a third party command - cc @jeffposnick who might have a different take on all of the above.

**Comment by jeffposnick** [comment]
What you describe sounds similar to what @alxhub has implemented with the SW tooling that's being developed for Angular: https://youtu.be/C8KcW1Nj3Mw?t=808

It requires a whole different model that opts you out of the normal service worker lifecycle flow, and it's not something that we want to adopt for a framework agnostic service worker toolchain like Workbox.

I'm not sure if you're an Angular developer, but I feel like you might find it useful to explore what Alex has built and potentially consider it for your own project.

**Comment by alxhub** [comment]
FWIW, nothing in the actual Angular Service Worker is Angular-specific, including the update logic. It could be used in any project. There is an accompanying library for use in an Angular app that makes talking to the SW more convenient, but you could code against the postMessage protocol yourself.

**Comment by rjsteinert** [comment]
Wow good stuff @jeffposnick! We use Angular 4 for the shell of our application and Polymer based app for the meat of it which does some crazy stuff closer to the DOM. 

Great demo @alxhub! My initial thought is what I'm describing might be accomplished in using a caching strategy defined in `ngsw-manifest.json`, one which only invalidates cache given some API that is triggered by a user's action. Is there a caching strategy like that bakes into the service worker in `worker-basic.min.js`?  

Before that action to stimulate an update is offered to the user, the app needs to determine if there is an updated manifest in the first place. Earlier in this thread I was thinking we would need to generate a `releases.json` file that does not get cached that an application can check to see if a new release UUID is listed, but I bet we can use this `ngsw-manifest.json` for just this purpose.

Lastly, @alxhub the API for the service worker via `postMessage`, where might I be able to glean what I can send over `postMessage` to interact with that API? I'm not getting `onmessage` hits here https://github.com/angular/mobile-toolkit/search?utf8=%E2%9C%93&q=onmessage&type=
