### ISSUE TITLE
Intentional console.log statement?

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#930]
**Library Affected**:
*workbox-routing*

I noticed when running my tests that there's some logging done via `console.log` instead of our logger: https://github.com/GoogleChrome/workbox/blob/b49939a16845767100aa8c16e1b4b6f108a1cd42/packages/workbox-routing/Router.mjs#L123

Is this intentional?

This adds noise to my test output (that can't be stubbed out), and I don't think we want it in the released versions since it means users can't turn off logging in dev mode either.

**Comment by gauntface** [comment]
Yeah its to make the logs a little nicer when printed into a console group.

Once the current precaching stuff is landed I'll explore how to add this to the logger class.
