### ISSUE TITLE
Pass-through config from Webpack plugin to workbox-build

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#934]
Adapted from @goldhand's comment at https://github.com/GoogleChrome/workbox/pull/808#discussion_r144745346 in reference to the ` get generateSWStringOptions()` getter:

> @jeffposnick this is where we should specify which generateSWString properties should be supported.

**Comment by jeffposnick** [comment]
I have a feeling that this would enable something that @anilanar is [trying to do](https://github.com/GoogleChrome/workbox/pull/808#issuecomment-337030397):

> Great work! I'll retest after `HtmlWebpackPlugin` is handled.

Passing through a `globDirectory` + `globPatterns` config to `workbox-build` should allow you to cache additional files that aren't included in the standard Webpack build pipeline. I'm assuming that's what's stopping you from being able to cache the `.html` file generated via `HtmlWebpackPlugin`?

**Comment by anilanar** [comment]
It would work, but it would be a half baked solution unless you are planning to use webpack's in-memory file system for `workbox-build`. Otherwise, dev-server wouldn't work.

I'd prefer using `html-webpack-plugin-after-emit` event in which you can access files generated by it. Example code can be found in `html-webpack-harddisk-plugin`.

I'm aware that workbox cannot and should not handle all possible cases for all kinds of webpack plugins. But HtmlWebpackPlugin has a special place and other plugins that work with asset names/hashes usually handle HtmlWebpackPlugin due to its widespread usage.

**Comment by jeffposnick** [comment]
Thanks for the additional context, @anilanar!

**Comment by goldhand** [comment]
Yeah, we definitely want to be able to make sure we get html-webpack-plugin emitted assets. We also should document that using globDirectory + globPatterns is a good way to grab other file's outside of the webpack build.

**Comment by goldhand** [comment]
@anilanar, in my testing, `html-webpack-plugin` assets are being picked up. Using a create-react-project app, my manifest looks like:

```
self.__precacheManifest = [
  {
    "url": "/workbox-sw.prod.v2.1.0.js",
    "revision": "89904e62e7da85112584"
  },
  {
    "url": "/workbox-sw.prod.v2.1.0.js.map",
    "revision": "89904e62e7da85112584"
  },
  {
    "url": "/static/media/logo.5d5d9eef.svg",
    "revision": "89904e62e7da85112584"
  },
  {
    "url": "/static/js/main.5ddeeb42.js",
    "revision": "5ddeeb42181f3270f4c3"
  },
  {
    "url": "/static/js/sw.29c471ec.js",
    "revision": "29c471ec1b3e0392549f"
  },
  {
    "url": "/static/css/main.9a0fe4f1.css",
    "revision": "5ddeeb42181f3270f4c3"
  },
  {
    "url": "/static/js/main.5ddeeb42.js.map",
    "revision": "5ddeeb42181f3270f4c3"
  },
  {
    "url": "/static/css/main.9a0fe4f1.css.map",
    "revision": "5ddeeb42181f3270f4c3"
  },
  {
    "url": "/static/js/sw.29c471ec.js.map",
    "revision": "29c471ec1b3e0392549f"
  },
  {
    "url": "/index.html",
    "revision": "89904e62e7da85112584"
  },
  {
    "url": "/asset-manifest.json",
    "revision": "89904e62e7da85112584"
  }
];
```

Could you confirm (again) that this does not work with `html-webpack-plugin`?

If it's still not working with html-webpack-plugin, I may need your help figuring out why

**Comment by anilanar** [comment]
@goldhand You are right, my bad. One thing that's missing for our use case is mapping between generated assets and urls.

For example:

```
self.__precacheManifest = [
  {
    "url": "/osp/vAssets/../../build/webpack-generated-twigs/OfflinePage/offline.html.twig",
    "revision": "90557b596354f76fe485"
  },
  {
    "url": "/osp/vAssets../../build/webpack-generated-twigs/OfflinePage/offline-urlway.html.twig",
    "revision": "90557b596354f76fe485"
  }
];
```

`/osp/vAssets/../../build/webpack-generated-twigs/OfflinePage/offline.html.twig` is supposed to be served from `/offline` and `/osp/vAssets../../build/webpack-generated-twigs/OfflinePage/offline-urlway.html.twig` from `/offline-urlway`. Everything else (js, css, others) are served from `/osp/vAssets`.

**Comment by jeffposnick** [comment]
I've filed https://github.com/GoogleChrome/workbox/issues/1037 to track getting per-asset revisions into the manifest, rather than per-build revisions.

Regarding the main questions about the URL `/offline-urlway` needing to be versioned based on the contents of `offline-urlway.html.twig` (and potentially to additional files, if there are more than one source file used when the server renders that URL), that's traditionally what the `templatedUrls` options in Workbox (and before that, `sw-precache`) has been for.

I'd hesitate to try to bake an equivalent `templatedUrls` behavior directly into the Webpack plugin, as opposed to passing-through the configuration and having `workbox-build` deal with it independent of the Webpack build pipeline. But if someone feels like they could replicate the behavior cleanly, I wouldn't stand in the way of them implementing it.

**Comment by sourvb** [comment]
Just for reference, 

> Passing through a globDirectory + globPatterns config to workbox-build should allow you to cache additional files that aren't included in the standard Webpack build pipeline.

I have achieved it using [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) for copying files which I do not want to include in Webpack pipeline otherwise.
