### ISSUE TITLE
Create & link to documentation about registration & deployment best practices

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#937]
**Library Affected**:
*workbox-build*

We should explain the best practices around serving your generated `sw.js` with `Cache-Control: no-cache` in either a comment in the generated `sw.js`, the JSDocs for the relevant `workbox-build` methods, a standalone guide, or all three.

While it should no longer be a problem according to the SW spec, none of the browsers that support SW are currently updated to support the modified behavior.

See https://stackoverflow.com/a/38854905/385997 for more background.

**Comment by gauntface** [comment]
Could we add a console log in developer builds for this?

**Comment by jeffposnick** [comment]
Sounds like a good approach, too. Maybe create a "using your service worker" page in the docs that we link to from the dev build console logging, and it contains
- Guidance on service your `sw.js` with caching disabled.
- A link to https://developers.google.com/web/fundamentals/primers/service-workers/registration for best practices on registration.
- Anything else?

**Comment by gauntface** [comment]
Getting started guide has the window load code
Will add a comment on the cache header and the the link to the getting started guide once the big changes land on WF.

**Comment by gauntface** [comment]
Will be fixed with: https://github.com/google/WebFundamentals/pull/5397
