### ISSUE TITLE
Don’t cache bust urls that already have [chunkhash/hash] specified in webpack builds

### ISSUE THREAD

**Issue by goldhand** [GoogleChrome/workbox#939]
Related to https://github.com/GoogleChrome/workbox/pull/808#pullrequestreview-64684918 We should omit the `revision` property of webpack assets if the asset is already using it's own filename cache busting.

> One thing that bears mentioning: as an optimization, the precache() function will not append a cache-busting query parameter when populating its caches if the revision field is not present.

> That's the same behavior that in sw-precache-webpack-plugin was defined by the dontCacheBustUrlsMatching configuration option, for which we recommended using a RegExp that matches URLs that contained hashes in them already.

> I'm not sure exactly how, but is there any indication at this point in the build process whether filePath contains a versioning hash in it? (I'd assume it wouldn't for HTML files, but would for most other assets.) If you can safely infer the presence of a hash, then you can leave out revision and get optimal behavior without developers needing to use dontCacheBustUrlsMatching.

*Note: we should sitill honor `dontCacheBustUrlsMatching` if specified.*

**Comment by gauntface** [comment]
@goldhand if the url has a hash in the revision I don't think we cache bust because the expectation is that that it'll be revisioned already.

**Comment by goldhand** [comment]
Yes, I guess I wasn't very clear but that is what I meant :)

**Comment by goldhand** [comment]
One way to do this would be to check if `[chunkhash]` is specified in the config.output but some plugins / loaders will disregard this param.

I dug up webpack's regex incase we want to use it: https://github.com/webpack/webpack/blob/ab2270263e9af5b0dd83e454c20ab3aa1797424a/lib/TemplatedPathPlugin.js#L7-L13

Another way is to use a regex to determine if there is a chunkhash in the asset filename. I'm a little concerned about this because its regex and there's a lot of ways to configure webpack filenames using chunkhash eg `[name].[chunkhash].js`, `[name].output.[chunkhash:8].js`, or maybe something silly like `12345.[name].js` that would get picked up by the regex as being a hash when really its just a weird string.

I'm thinking the best way will be to check the config, then use the config to try to find the hash in asset filenames.

eg:

if the `config.output.filename` is: `[name].output.[chunkhash:8].js`

then we can use a regex like: `/\w+?\.output\.\w{8}\./` but I'm not sure how I feel about this approach either...

**Comment by jeffposnick** [comment]
@TheLarkInn graciously volunteered to be looped in to questions that came up regarding Webpack internals.

Sean, is there any "official" way for a Webpack plugin to determine whether a given asset contains `[hash]` or `[chunkhash]` in it, given that there are a lot of flexibility when it comes to configuring names?

Is using the RegExps at https://github.com/webpack/webpack/blob/ab2270263e9af5b0dd83e454c20ab3aa1797424a/lib/TemplatedPathPlugin.js#L7-L13 the best bet?

**Comment by gauntface** [comment]
Stupid question, is the chunkhash string the same as what would be used in the filename?

If so, we can just check if the string is used in the filename, if it's different or short, it may be that we include revision information with filename for now until there is an API in webpack to reliably know if the revision info is in the filename or not.

**Comment by TheLarkInn** [comment]
Sorry have been catching up with GitHub mail debt. Let me find this out. I think you are on the right path with that plugin because it essentially provides the "across the board" templating.

**Comment by jeffposnick** [comment]
I've got a potential approach in #1042 if folks want to weigh in on how hack-y that is.
