### ISSUE TITLE
debug output is difficult to visually scan

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/workbox#942]
I am trying to move from sw-toolbox to workbox and the logging output seems much less practical. 

sw-toolbox logging is very clear and easy to visually scan for errors :
```
[sw-toolbox] Strategy: cache first [https://cdnjs.cloudflare.com/...]
[sw-toolbox] Strategy: network first [https://www.google.com/...]
...
```

Workbox is completely opaque.  I have a ton of assets and when I tweak the cache type of one and want to confirm it has taken effect, I am finding it impossible to know which line represents my asset without clicking into each one:  
```
[Info] The router found a matching route.
[Info] The router found a matching route.
[Info] The router found a matching route.
...
```

Would it be possible to make the high level debug message contain the strategy/asset so people can easily scan (and drill into it for more info only if necessary)?

**Comment by gauntface** [comment]
We are working on this in the next version: https://github.com/GoogleChrome/workbox/pull/902

Let me know if that would be better for you or if there are still concerns.

**Comment by Enalmada** [comment]
Ok, it looks like asset name was added...having asset name solves one critical need...being able to efficiently verify that a specific regex change has correctly taken effect.  

But it looks like strategy is not yet there.  I think it is still vital having both asset and strategy printed without drilling in because I can't tell you how many times I have turned on sw-toolbox debug just to scan the log feeling like everything is fine but just wanting to make sure everything that should be "cacheFirst" is "cacheFirst" and said something like "oh $#!%...<asset> should/should not be cacheFirst".

**Comment by gauntface** [comment]
The strategy has just been added in a PR that landed to today.

See them here: https://workbox-demos.firebaseapp.com/demo/workbox-runtime-caching/

**Comment by Enalmada** [comment]
Side note on debug...as a new user I found it a bit hard to know how to actually turn on debugging.  In sw-toolbox i just say "debug=true".  In workbox...I see there is a file called "prod" so I assume switching to the "dev" file is necessary?  And after that, is there logging levels and flags I should know about? 
Logging didn't seem to go on right away but I run my server with "www.OneOfManyTestDomain.com" and feel like perhaps some logging was tied to "localhost" which made it more painful for me.  Anyway, just a quick request to consider:
having a doc section on how to enable debugging, making sure logging isn't tied to "localhost" so I can turn it on/off with commandline parameters on any domain (file switch is ok, I just want to be sure I can get debug logs on more than just localhost). 

Cant wait for v3 to be live!

**Comment by gauntface** [comment]
Once again v3 will have a fix for this - if you check out the source code for v3 you'll see debug: true. This will pull in a debug build for each module (it's true by default for localhost).


I have doc outline here for configuring workbox (Needs some outdating with changes landed today but nothing too drastic): https://docs.google.com/document/d/1Oh6vRCE-AKuIlcYaxxwa0uoAFO2XjX-NQN3Ee-7MDGI/edit?usp=sharing

Comments welcome on the docs. Gonna close this issue for now - please feel free to raise further issue if there is moore.
