### ISSUE TITLE
filename/versioning not cdn friendly 

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/workbox#953]
Some consumers, especially non-npm based build processes, would find it most convenient to just reference external scripts from a quality cdn.  

[sw-toolbox](https://cdnjs.com/libraries/sw-toolbox) was so easy to get started with because of this and there is a request to get workbox into cdnjs too...but there seems to be a complication around the filename being combined with version:  https://github.com/cdnjs/cdnjs/issues/12041

I think getting this resolved before v3 could be great for the non-npm community.

**Comment by gauntface** [comment]
We intend to have a CDN for v3. The demos are using the URL's at the moment.

The next filenames won't have the version name in them which should make cdnjs possible too,

**Comment by Enalmada** [comment]
Thanks @gauntface!
