### ISSUE TITLE
Rollup 0.50.0 Isn't Building Correctly

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#961]
Rollup 0.50.0 has been released but it's breaking out builds (currently only shown via Precaching integration test). The global imports dont get imported correctly.

https://github.com/rollup/rollup/blob/master/CHANGELOG.md

```javascript
import {assert} from 'workbox-core/_private.mjs';

// Use assert here
```

Was originally being converted to something along the lines of:

```javascript
(function(_private_mjs) {
  const assert = _private_mjs.assert;

  // Use assert here
})(workbox.core._private);
```

It seems that 0.50.0 isn't building in such a way that `workbox.core._private` is being passed into the iife, instead an error is thrown for `_private_mjs` not existing.

Will investigate once #949 has landed.

**Comment by jeffposnick** [comment]
I believe that #1157 fixed this, as we're no longer stuck on `0.49`:

https://github.com/GoogleChrome/workbox/blob/29e85277ab80ce9ad728e16d1d50b6b51f0a2be8/package.json#L94

(Please reopen if I'm misinterpreting the original issue.)
