### ISSUE TITLE
workbox.clientsClaim() vs workbox.claimClients()

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#980]
I copied over the option name for workbox to the `workbox-sw` method name but I'm thinking that it should be `claimClients()`. What do others think?

**Comment by jeffposnick** [comment]
For the sake of continuity with `sw-precache`, the method name in v1/v2, and the `workbox-build` configuration option in v3 (unless we rename that too), I'd vote to stay with `clientsClaim()`.
