### ISSUE TITLE
workbox-runtime-caching / handlerCallback

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#981]
The API's for the `workbox-runtime-caching` strategies is slightly weird. None of them use the URL or params values from the `handlerCallback` function but they all use the `event` argument.

To make these strategies more intuitive to use, it would be great if we could move the `event` argument to the first argument and move url and params to an options argument:

```javascript
const cacheFirst = workbox.strategies.CacheFirst();
cacheFirst.handle({event});
```

to

```javascript
const cacheFirst = workbox.strategies.CacheFirst();
cacheFirst.handle(event);
```

Handlers would then become:

```javascript
new Route(matcher, (event, {url, params}) => {
    // Return response
});
```

This does violate the styleguide with respect to callbacks however, so understand if this is a no-go.

**Comment by gauntface** [comment]
Alternative could be to allow this event only API if the `handler` parameter implements the `Handler` interface and ensure the caching strategies extend this Class.

**Comment by jeffposnick** [comment]
My vote would be to stick to the decision we made regarding using an object with well-defined property names as the parameter to callbacks.

When I've written a custom `CalbackHandler`, I've found the `URL` object about as useful than the `FetchEvent` object.
