### ISSUE TITLE
[workbox-core] Module docs: Core’s `cacheNames`

### ISSUE THREAD

**Issue by surma** [GoogleChrome/workbox#983]
Core starts defining itself as follows:

> All of the Workbox service worker libraries use workbox-core for shared code as well as setting default values that need to be share

I kinda get that the name for the `runtime` cache needs to be globally accessible, but why do `precache` and `googleAnalytics` get this special treatment? What prevents them from being just another workbox module™️?

**Comment by gauntface** [comment]
Couple of things:

1. One of the use cases for have caches in a central place if that if you used workbox across multiple projects and you used the same localhost for each project, you could set a prefix that would prevent caches from interferring with each other:

```javascript
workbox.core.setCacheDetails({
    prefix: 'my-project-name'
});
```

2. If we set up this kind of expectation, it makes sense to be consistent with all of Workbox's caches (i.e. workbox precache, runtime, analytics, XYZ should all follow this pattern. If some do and some don't that's just confusing.

**Comment by surma** [comment]
Yeah, I get the `prefix`/`suffix` bit and I think that’s a really simple and effective idea.

I am not sure why the names for `precache` and `googleAnalytics need to be globally exposed, tho. Those should just be in the respective modules, not in `core`, right?

**Comment by gauntface** [comment]
The main reason for all of this is that the runtime cache can be used by a host of modules, so having it in core means that regardless of what you use in whatever fashion, the cache name will be the same for runtime stuff and you can override in a single place.

With that in mind, wouldn't it be weird is precache and googleAnaltyics couldn't be changed in the same place as the runtime cache name?

Bare in mind, with all of these, the cache names can be overriden in the respective place (i.e precaching can take a cacheName option, as can analytics and that trumps all of this.

**Comment by surma** [comment]
I guess the question then is: When I write my own module for `surmaAnalytics`, should I put my cache name into `core` as well? If so, how?

**Comment by gauntface** [comment]
What would you like to see as the behaviour here?

Original thinking was: 
- require consistency for Workbox modules
- make it easy to get the defaults
- make it easy to override the defaults

By the sounds of you - we haven't done any of this for you, so what would you expect and like?

**Comment by gauntface** [comment]
I think for now we'll carry on with the current cache naming. @surma if you have any more thoughts on what we should do please re-open as we can always change it in the future.
